.github/labeler.yml, lib/si-cli/src/cmd/start.rs
Fixes: #2609
When the credentials are incorrect, we want to be able to stop
and then restart the container to get the new credentials passed
to the container
=> fix(si): Ensure that we can recreate a new veritech container

lib/si-cli/src/cmd/start.rs
We don't need to expose specific ports - we only need ports for
web, sdf and jaeger
```
docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS         PORTS                                                                               NAMES
78392dab00d2   systeminit/web:stable        "/usr/local/bin/web"     2 minutes ago   Up 2 minutes   0.0.0.0:8080->8080/tcp                                                              local-web-1
a2826dff3cd7   systeminit/sdf:stable        "/sbin/runuser -u ap…"   2 minutes ago   Up 2 minutes   0.0.0.0:5156->5156/tcp                                                              local-sdf-1
18fefe7fca44   systeminit/pinga:stable      "/sbin/runuser -u ap…"   2 minutes ago   Up 2 minutes …
```
=> fix(si): Change the si binary to not expose unnecessary ports

README.md
For readability the logos for the dashboard and discord badges are now white. This was supposed to be the PR linked below, but due to performance degradation from external services, the amended commit was not picked up.
Previous PR: https://github.com/systeminit/si/pull/2621
=> Make dashboard and discord logos white on badges

lib/si-cli/src/containers.rs, lib/si-cli/src/key_management.rs
There was a chicken and egg scenario that the data_dir we store creds
in may not exist until we write the creds or the keys BUT we were trying
to read the SI email from it
We now default to sally@systeminit.com if it's not found
=> fix(si): Ensure that we have a default email in place when using the launcher

CONTRIBUTORS.md, docs/RUNNING_RUST_TESTS.md
My guess is this was a copy paste error?
=> docs: use buck2 targets to list targets

lib/si-cli/src/cmd/start.rs
Fixes: #2627
:Z indicates the bind mount is private which is required for systems
with selinux enabled
I tested this on a non-selinux enabled system and all works as expected
=> fix(si): Ensure we pass :Z to the sdf container mounts

bin/auth-api/src/routes/github.routes.ts, lib/si-cli/src/cmd/update.rs, lib/si-cli/src/containers.rs
- fix(auth-api): Reenable the container updates from the github releases API
- fix(si): Ensure we are comparing the container version vs release digest from the auth-api for updates
there is an order of operations here - we need to release the SI binary *first* to get the good update behaviour in place then we can launch the auth-api
=> feat(si): Ensure that the SI binary can update it's containers

lib/dal/src/func.rs, lib/dal/tests/integration_test/internal/func.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/clone_variant_def.rs
This commit clones the scaffolding func when cloning the schema variant def to retain 1:1 relationship constraints.
Without this commit, the func would be re-used from the existing variant def. Accessor queries will fail when that happens, as observed when executing "exec_variant_def" after the clone. Specifically, this error is observed when cloning an asset and immediate creating the clone.
=> Clone func when cloning variant def (ENG-1821)

lib/dal/src/schema/variant/root_prop/component_type.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs, lib/sdf-server/tests/service_tests/scenario.rs, lib/si-pkg/src/spec/variant.rs
The component_type property on the save/exec variant definition requests was being ignored. A bit of a goof here is that the enum is being serialized differently by strum than by serde, so aliases added to handle the different serializations.
=> fix(web,sdf): save component type when changed in variant definition

bin/si/src/args.rs, bin/si/src/main.rs, lib/si-cli/src/cmd/start.rs, lib/si-cli/src/state.rs
```
si --with-function-debug-logs start
```
=> feat(si): Enable the use of debug logs for veritech SI container

bxl/dependent_targets.bxl
This change fixes the dependent targets calculation used in CI/CD to look for target names *starting with* the appropriate phase names such as `check-format`, `check-lint`, etc.
Prior to this change, only an exact target name match of `check-format` would return a result. As we start to use more `test_suite` groups to group up similar tests to run under one convenient target we have started to generate such target names as `check-format-rust-bin` or `check-lint-rust-unit`. It appears as though the `test_suite` Buck2 rule type does *not* form a dependency  relationship with its inputs and therefore the rolled up target names such as `check-format` or `check-lint` were not being selected to run in a pipeline.
=> fix(buck2): when computing dependent targets, use `attrregexfilter`

lib/vue-lib/src/design-system/tabs/TabGroup.vue
Prevents the anchor click from propagating when closing a function tab, as it was was forcing a hard reload of the page.
=> fix(web): prevents anchor click from hard reloading

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue, app/web/src/store/asset.store.ts
Request was not keyed by id, and the key provided was not refreshing on asset change.
=> fix(web): fix exec_asset request status handling in details panel

lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_whiskers.rs
Whiskers nightly test was checking for the dropped region qualification and failing.
=> fix(sdf): fix nightly ci

README.md
- Rename "BUILD" badge to "MAIN" in README for clarity
- Expand "DASHBOARD" badge name to "BUILD DASHBOARD" for clarity
=> doc: rename build badge to main

app/web/src/components/FuncEditor/CodeGenerationDetails.vue, app/web/src/components/FuncEditor/ConfirmationDetails.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/LeafInputs.vue, app/web/src/components/FuncEditor/QualificationDetails.vue, app/web/src/store/func/funcs.store.ts
Reverting was not waiting for load before refreshing the "draft", and the leaf function input details where not fully reactive to changes from the API request.
=> fix(web): fix leaf function reactivity after revert

lib/vue-lib/src/design-system/modals/Modal.vue
when the modal is open, it is totally in charge, so I think it makes sense as a general rule to capture the mousedown events. This means you must first dismiss the modal before something else that may be listening for clicks will fire.
specifically this fixes https://github.com/systeminit/si/issues/2606
=> have modal capture mousedown events

lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs
When an asset is scaffolded via the UI, we give the func a name like
`new asset 2703`. When we package the asset, it doesn't make sense
to include a func with that name. Therefore, when the exec_variant_def
is called, we now generate the func name as:
myTestFuncScaffold_202308222128
We are camelcasing the assetname, adding `Scaffold` to it and appending
the date in year month day hour minute format. We need to ensure that funcs
are unique and generating to minute should be unique enough
=> fix(sdf-server): Ensure standard name for Asset scaffold funcs

.github/workflows/community-check.yml
This has all the same behaviour as pull_request but runs as a more
secure action to stop any malicious code from the pull-request doing
something
As this check will be able to create issues, we want to keep this
as secure as possible
=> chore(build): Change the community check to use pull_request_target

Cargo.lock, Cargo.toml, lib/si-cli/src/cmd/update.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
When the launcher (i.e. the `si` program) is installed from a non-root user and when they don't have either `$HOME/.local/bin` or `$HOME/bin` currently in their `$PATH`, the launcher is installed to `$HOME/.si/bin/si` and a symlink is created at `/usr/local/bin/si` with a sudo call (that is, the root user owns the symlink as it is a system directory).
Prior to this change, when a self update was attempted (via calling `si update --self) under the scenario above, the new binary would attempt to write itself to a temp file under the *symlink*'s  parent directory of `/usr/local/bin`. This would cause an permissions error that looks like:
```
Downloading new binary
Replacing '/usr/local/bin/si' with new binary
Error:
0: io: Permission denied (os error 13) at path …
```
=> fix(si): support self update through symbolic links on macOS

app/web/src/components/AssetPalette2.vue, app/web/src/components/ChangeSetPanel2.vue, app/web/src/components/ComponentOutline/ComponentOutline2.vue, app/web/src/components/ProgressBarOverlay.vue, app/web/src/components/RecommendationProgressOverlay.vue, app/web/src/components/Workspace/WorkspaceModelAndViewNew.vue, app/web/src/store/fixes.store.ts, lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
Creating a changeset in the middle of the fix flow causes inconsistency.
This PR prevents this by checking if fixes are running, and if they are
it
- disables the changeset button
- prevents dropping assets on the graph
- disables the right click menu
- Uses RecommendationProgressOverlay as the global overlay to give
status updates about actions while in flight
There are probably other paths that could create a changeset or get into
a conflict with the fix run.
A more robust solution is needed that prevents SDF itself from
performing operations that could cause inconsistency during the fix run,
but this should make for a smoother user experience.
=> fix(web): prevent changeset actions in frontend while fixes are running

lib/si-cli/src/cmd/stop.rs, lib/si-cli/src/engine/docker_engine.rs
When running `si stop` on a system that had stopped containers, we got
an error from docker as follows:
```
Stopping container local-web-1
Error:
0: docker api: error 304 Not Modified - Not Modified
1: error 304 Not Modified - Not Modified
Location:
bin/si/src/main.rs:121
```
This PR now checks that a container is running before attempting to
stop it
=> fix(si): Ensure we only stop containers that are actually started

CONTRIBUTORS.md, bin/si/src/main.rs, lib/si-cli/src/cmd/check.rs, lib/si-cli/src/cmd/delete.rs, lib/si-cli/src/cmd/start.rs, lib/si-cli/src/engine.rs, lib/si-cli/src/engine/docker_engine.rs, lib/si-cli/src/engine/podman_engine.rs, lib/si-cli/src/lib.rs
Resolves #2607
The `si` binary now supports the Podman container engine.
The Podman socket [must be activated](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md) before it can be used with `si`.
On Fedora, this can be done using systemd.
```sh
systemctl --user start podman.socket
```
The implementation uses `${XDG_RUNTIME_DIR}/podman/podman.sock` to ensure that the user-specific Podman socket takes precedence over any system Podman socket, falling back to a system Podman socket when the user-specific socket does not exist.
The implementation requires a Podman network named `si` to exist prior to starting System Initiative. This network must have DNS enabled.
You can create the necessary network using the Podman CLI.
```sh
$ podman network create si
$ …
```
=> feat(si): implement the podman container engine

CONTRIBUTORS.md, bin/si/src/main.rs, lib/si-cli/src/cmd/check.rs, lib/si-cli/src/cmd/delete.rs, lib/si-cli/src/cmd/start.rs, lib/si-cli/src/engine.rs, lib/si-cli/src/engine/docker_engine.rs, lib/si-cli/src/engine/podman_engine.rs, lib/si-cli/src/lib.rs
- chore: add sudomateo to contributors
- feat(si): implement the podman container engine
- fix(si): Ensure that the podman container engine sock works on macOS
This PR just builds on the wonderful work from @sudomateo to ensure that podman works on macOS - which it now does :)
```
SI_CONTAINER_ENGINE=podman buck2 run //bin/si start
File changed: root//lib/si-cli/src/engine/podman_engine.rs
File changed: root//lib/si-cli/src/engine/podman_engine.rs~
Build ID: 07d79a8a-c372-438c-ba68-cee337fab2cb
Network: Up: 0 B  Down: 0 B
Jobs completed: 6. Time elapsed: 5.2s.
Cache hits: 0%. Commands: 2 (cached: 0, remote: 0, local: 2)
System Initiative Launcher is in "local" mode
Launcher update found, please run `si update` to install it
System Initiative needs some credentials in order to be able to …
```
=> Add support for Podman

lib/si-cli/src/cmd/delete.rs
This stops the following from happening:
```
Deleting container: local-jaeger-1 (fb9df0409d90e4cfa68392c47ed09eb688453115e22d1d4ce79b151f9b2cd87f)
Error:
0: docker api: error 409 Conflict - You cannot remove a running container fb9df0409d90e4cfa68392c47ed09eb688453115e22d1d4ce79b151f9b2cd87f. Stop the container before attempting removal or force remove
1: error 409 Conflict - You cannot remove a running container fb9df0409d90e4cfa68392c47ed09eb688453115e22d1d4ce79b151f9b2cd87f. Stop the container before attempting removal or force remove
```
Related to #2700
=> fix(si): When si delete has been run ensure that the containers are stopped

app/web/src/App.vue, app/web/src/api/sdf/dal/user.ts, app/web/src/api/sdf/dal/workspace.ts, app/web/src/store/auth.store.ts, app/web/src/store/realtime/realtime.store.ts, app/web/src/store/workspaces.store.ts, bin/auth-api/src/custom-state.ts, bin/auth-api/src/routes/workspace.routes.ts, bin/auth-api/src/services/auth.service.ts, lib/sdf-server/src/server/service/session.rs, lib/sdf-server/src/server/service/session/auth_connect.rs, lib/vue-lib/src/pinia/pinia_api_tools.ts
this change helps us recover more gracefully from the database being empty - a situation that is now very common due to the way our launcher is setup and how we trash our containers.
The user remains logged in with a valid token, but the workspace (and user) do not exist in this freshly migrated db yet. Previously that initialization happened only in the handoff between the auth system and sdf.
Now instead we have an additional endpoint which can use the existing auth token and just handle this re-initialization. Note that we could do it on every reload (rather than just fetching from sdf which we do now) but this would add extra overhead to that call. So instead we first try to reestablish auth with sdf only, and then if we detect the situation of the workspace not existing, we reach out …
=> feat(web,sdf,auth-api) recover more gracefully from a reset database

lib/dal/src/change_set.rs, lib/si-pkg/pkg-workspace.json, lib/si-pkg/src/lib.rs, lib/si-pkg/src/node/change_set.rs, lib/si-pkg/src/node/change_set_child.rs, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/node/package.rs, lib/si-pkg/src/pkg.rs, lib/si-pkg/src/pkg/change_set.rs, lib/si-pkg/src/spec.rs, lib/si-pkg/src/spec/change_set.rs
Adds a new package "category" for change sets. Adds the idea of a "default_change_set" to the SiPkg. ChangeSets are a name, a status and a pointer to the change set that they are "based on", along with child nodes for functions and schemas. In the future they will also include Components (with Node Positions), and Edges.
=> feat(si-pkg): Add ChangeSet node to SiPkg

app/web/src/components/AddSecretForm.vue, app/web/src/components/ComponentOutline/StatusIconWithPopover.vue, app/web/src/components/CustomizeTabs.vue, app/web/src/components/PropertyEditor.vue, app/web/src/components/SecretsList.vue, app/web/src/components/Workspace/WorkspaceCustomizeSecrets.vue, app/web/src/router.ts, app/web/src/store/secrets.store.ts
Functional version of secrets store with add and delete functionality, not hooked up to back end yet
Also implements a global secrets panel on the customize screen. On this iteration,  this is for development purposes only
=> feat(web): Secret store with only browser local data

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetEditor.vue, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/AssetFuncListPanel.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/FuncEditor.vue, app/web/src/components/WorkspaceExportModal.vue, app/web/src/components/WorkspaceImportModal.vue, app/web/src/components/layout/navbar/Navbar.vue, app/web/src/components/layout/navbar/NavbarPanelRight.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, app/web/src/components/modules/ModuleDetailsPanel.vue, app/web/src/pages/WorkspaceSinglePage.vue, app/web/src/store/feature_flags.store.ts, app/web/src/store/workspaces.store.ts, lib/vue-lib/src/design-system/forms/VormInput.vue, lib/vue-lib/src/design-system/general/LoadingMessage.vue, lib/vue-lib/src/design-system/general/RequestStatusMessage.vue, lib/vue-lib/src/design-system/icons/icon_set.ts, lib/vue-lib/src/design-system/modals/Modal.vue, lib/vue-lib/src/pinia/pinia_api_tools.ts
adds a workspace settings cog, along with import/export modals. Currently mocking the requests with fake delays...
Some intermediate loading states as well, but these screenshots show the flow. Playing with the terms "backup" and "restore" a bit now, as this more accurately describes the flow as we will be implementing them for now. I suspect in the future that backup/restore may be some options within the broader category of export/import - ie you may be able to export/import subsets of a workspace without losing your local data, rather than only all or nothing.
new workspace settings menu
export modal
import modal
=> workspace export/import UI

bin/si/src/args.rs, bin/si/src/main.rs
Currently, if a user passes Podman as the engine and a docker-sock
then the CLI will error, We can make an assumption of the engine
based on the param passed and then let the user know we are doing so
```
si --podman-sock /var/run/podman.sock status
WARNING: A `podman_sock` location parameter was passed but no Podman engine was chosen. Continuing with the assumption you meant to choose Podman as the container engine...
Checking for user supplied docker.sock
System Initiative Launcher is in "local" mode
```
```
SI_CONTAINER_ENGINE=podman si --docker-sock /var/run/docker.sock status
WARNING: A `docker_sock` location parameter was passed but no Docker engine was chosen. Continuing with the assumption you meant to choose Docker as the container engine...
Checking for user supplied docker.sock …
```
=> fix(si): Infer the container engine based on args being passed

CONTRIBUTING.md, docs/PREPARING_YOUR_CHANGES.md
Replace conventional commits recommendation with overall suggestions. An optional template is provided alongside examples.
- [Preparing Your Changes](https://github.com/systeminit/si/blob/nick/eng-1922-replace-conventional-commits-recommendation-with-overall/docs/PREPARING_YOUR_CHANGES.md#commit-format)
- [Contributing Guide](https://github.com/systeminit/si/blob/nick/eng-1922-replace-conventional-commits-recommendation-with-overall/CONTRIBUTING.md)
=> Replace conventional commits recommendation

rust-toolchain
Rust 1.72.0 introduced compile time regressions for async heavy code:
https://github.com/rust-lang/rust/issues/115283
Reverting to 1.71.0 gets us back to reasonable compile times for sdf. We should stay there until a fix is released.
=> fix(*): pin rust to 1.71.0 until compile time regression fixed

lib/dal/examples/dal-pkg-export/main.rs, lib/dal/examples/dal-pkg-import/BUCK, lib/dal/examples/dal-pkg-import/main.rs, lib/dal/src/pkg/import.rs, lib/dal/src/workspace.rs
Because new exports will have a different hash with the added values to support workspaces, si:resourcePayloadToValue should temporarily be treated like an intrinsic on import and only imported once.
Also updates the dal-pkg-import tool to use a change set on import.
=> fix(dal): special case si:resourcePayloadToValue

lib/dal/examples/dal-pkg-export/main.rs, lib/dal/src/pkg/export.rs, lib/si-pkg/src/spec.rs, lib/si-pkg/src/spec/func.rs
We also only add unique_ids to non-function nodes if it's a module and not a workspace export
=> fix(dal,si-pkg): stabilize func unique ids for modules, requires change set pk for export tool

app/web/src/components/WorkspaceExportModal.vue, app/web/src/components/WorkspaceImportModal.vue
I got rid of the "backup" and "restore" terminology in favour of sticking with "export" and "import"
I will say it still feels quite awkward as export/import work well as the verbs but I feel there is a missing noun, for example "backup" or "snapshot"...  "Workspace export" feels like a bit of a mouthful and using just "workspace" doesnt quite feel right as you are not importing a "workspace" you are importing a fixed snapshot of a workspace.
=> chore(web) update import/export terminology

dev/Tiltfile
Setting the `SI_LOG=debug` for the veritech tilt service
=> chore(dev): Enable debug logs by default in Veritech

lib/object-tree/src/graph.rs, lib/object-tree/src/tar/read.rs, lib/si-pkg/src/node/action_func.rs, lib/si-pkg/src/node/attr_func_input.rs, lib/si-pkg/src/node/category.rs, lib/si-pkg/src/node/change_set.rs, lib/si-pkg/src/node/change_set_child.rs, lib/si-pkg/src/node/func.rs, lib/si-pkg/src/node/func_argument.rs, lib/si-pkg/src/node/leaf_function.rs, lib/si-pkg/src/node/map_key_func.rs, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/node/package.rs, lib/si-pkg/src/node/prop.rs, lib/si-pkg/src/node/prop_child.rs, lib/si-pkg/src/node/schema.rs, lib/si-pkg/src/node/schema_variant.rs, lib/si-pkg/src/node/schema_variant_child.rs, lib/si-pkg/src/node/si_prop_func.rs, lib/si-pkg/src/node/socket.rs, lib/si-pkg/src/node/validation.rs
We removed a node child kind (FuncDescriptions), but this breaks old modules that have func descriptions in them. We still want to be able to read those modules and we want the ability to make changes like this to the package format in the future without invalidating the old modules. This makes the read_bytes trait in object-tree return an Option, so if a node is not one we want to read any more, we can skip it (and its children!), while preserving the rest of the module.
=> feat(object-tree,si-pkg): Support optional nodes in object tree

app/web/src/components/AssetDetailsPanel.vue
Minor adjustments to asset creation screen to more accurately determine whether fields are mandatory or not.
There is a follow on task to then actually enforce this within the .js/vue. On this commit the POST to SDF will still occur but will still result in a 422 (unprocessable entity).
* UI adjustments can be seen below *
=> chore(web): amended placeholders for asset creation

dev/Tiltfile, prelude-si/pnpm.bzl, prelude-si/tilt.bzl
This change will run Tilt binding to all IPs as well as the `app/web` service.
This means you can run:
```
buck2 run dev:up -- --bind-all
```
=> chore: add `--bind-all` flag to `buck2 run dev:up`

dev/Tiltfile, prelude-si/pnpm.bzl, prelude-si/tilt.bzl
This fix un-reverts #2772 and also fixed the underlying issue by detecting if the command is an `up` or `down` command.
=> un-revert #2772 and fix `buck2 run dev:down`

app/web/src/components/WorkspaceExportModal.vue, app/web/src/components/WorkspaceImportModal.vue, app/web/src/store/module.store.ts, app/web/src/store/workspaces.store.ts, lib/module-index-server/src/migrations/U0004__modules_kind.sql, lib/module-index-server/src/models/si_module.rs, lib/module-index-server/src/routes/list_modules_route.rs, lib/module-index-server/src/routes/reject_module_route.rs, lib/module-index-server/src/routes/upsert_module_route.rs
Adds a column to the modules table in module index to filter modules by kind ('module', or 'workspaceBackup'). 
Supports listing workspaceBackups in the UX and adds the stub to the workspace import route (will be 404 until that PR lands).
=> feat(module-index,sdf,web): support workspace backups in module-index

app/web/src/components/CachedAppNotification.vue
We're fetching manifest.json on an interval, but axios throws an error on 404 which happens in dev mode since we won't have a build or a manifest.json. This quiets those errors while keeping the behavior intact when run from the container/nginx build. The interval will be killed if manifest.json 404s so we only fetch it once in dev mode.
=> fix(web): Catch axios errors in CachedAppNotification

app/web/src/components/modules/ModuleListPanel.vue, app/web/src/store/module.store.ts, bin/module-index/Dockerfile, bin/module-index/src/args.rs, lib/module-index-server/src/app_state.rs, lib/module-index-server/src/config.rs, lib/module-index-server/src/routes/list_modules_route.rs, lib/module-index-server/src/routes/reject_module_route.rs, lib/module-index-server/src/routes/upsert_module_route.rs, lib/module-index-server/src/server.rs
Module uploads were getting a random user id. Updated to store the user claim pk from the auth token as the user id. This allows us to filter workspace backups by user.
Removes "restrict-listing" and adds a "su" flag to list modules which will list modules for all users / allow module rejection if user token matches a systeminit.com user token.
=> feat(module-index,web): filter workspace backups by user pk

app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/store/func/funcs.store.ts, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/delete_func.rs
An orphaned function is a function that has zero associations to
prototypes, components or assets
PLEASE NOTE: We do not allow deletion of builtin functions at this time
=> feat(web,sdf-server): Add ability to delete orphaned functions

bin/sdf/src/args.rs, lib/sdf-server/src/server/config.rs
Pass `--module-index-url=` to the `sdf` binary, or set the `SI_MODULE_INDEX_URL` environment variable before starting `sdf` to point it to a different module-index endpoint (e.g., `localhost:5157` to hit the local module-index). Also needs to be set in `app/web/.env.local` as `VITE_MODULE_INDEX_API_URL`.
=> feat(sdf): Make module-index API url configurable

app/web/src/api/sdf/dal/diagram.ts, app/web/src/components/modules/ModuleExportModal.vue, lib/dal/src/migrations/U2311__drop_unique_func_name_live.sql, lib/dal/src/pkg/export.rs, lib/dal/src/schema/variant.rs, lib/sdf-server/src/server/service/diagram/list_schema_variants.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/create_func.rs
Remove the func name uniqueness condition to ease the import of updated builtins. A new schema variant will be imported with the same name, and the connected functions will be recreated, with the original functions left intact after import.
If a schema variant is net-new (whether a changed builtin or a new schema variant), it might reference a function from head. This lead to those functions being skipped from the package and missing on import, since they were not in the changeset that contained the new schema variant. This will grab them and create them new, with an identical name.
Adds a "builtin" boolean to the SchemaVariantView so that we can use that metadata to figure out which schema variant we want to add to a module export.
CAVEAT: This makes it possible for a user to create a …
=> feat(dal,web): Remove func name uniqueness, graceful builtin backups

lib/si-cli/src/engine/docker_engine.rs, lib/si-cli/src/engine/podman_engine.rs
Currently, we had a restart policy of on-failure BUT this causes us to
try and start containers on system boot as docker doesn't keep track
of the previous state - https://github.com/moby/moby/issues/35166#issuecomment-338211235
This means that we will continually hit this problem and the containers
may fail to start due to ordering issues
Fixes: #2802
=> fix(si): Change SI container restart policy

lib/module-index-server/src/routes.rs, lib/module-index-server/src/routes/list_modules_route.rs, lib/module-index-server/src/routes/upsert_module_route.rs
Axum's default body limit of 2mb is too small for uploading a large workspace. Ordering by created_at makes more sense, especially for the workspace backup list.
=> feat(module-index): Allow larger uploads, order modules by created at

lib/sdf-server/src/server/service/diagram/create_node.rs
The lack of a content-type header on the create_node HTTP response causes Firefox to raise an XML Parsing Error on every call (since it interprets the type as XML by default), and likely will cause issues with other HTTP clients. This quiets those errors.
=> fix(sdf): add json content-type to create_node response

app/auth-portal/src/pages/tutorial/TutorialPage.vue, lib/vue-lib/src/design-system/general/RichText.vue
Tutorial navigation bug was actually caused by an issue with the RichText markdown parser. Fixed!
=> fix(auth) - RichText hljs plaintext support

app/web/src/store/func/funcs.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/func/binding.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/execute.rs
Tested with:
*Note: the argument has to be the `FuncBackendJs{...}Args`, the one that the dispatcher sends to js, so each function kind will have a different wrapper*
```
fetch(http://localhost:8080/api/func/execute", { 
method: "POST", 
headers: { 
'Content-Type': 'application/json',
authorization: `Bearer ${yourBearerToken}`,
WorkspacePk: yourWorkspace,
body: JSON.stringify({
id: yourFuncId,
args: yourArgument,
executionKey: "random-key-to-group-logs-by",
visibility_change_set_pk: yourChangeSetPk
})
} ) 
```
=> feat(sdf,dal): api to test functions, streaming logs

app/web/src/components/CodeEditor.vue, app/web/src/utils/typescriptLinter.ts, lib/sdf-server/src/server/service/ts_types/asset_types.d.ts
Hover over a func to see tooltips! Pulls from comments in the `asset_types.d.ts` file. Currently on `setKind` and `setName` on `PropBuilder` have comments. We'll want to pad the rest of these out as we go.
=> feat(web): add hover tooltip for the code editor

lib/cyclone-server/src/server.rs, lib/veritech-server/src/server.rs
Currently the veritech process throws 100s of these (due to cyclone)
```
023-09-26T11:21:12.380324Z  INFO ThreadId(03) cyclone_server::server: received internal shutdown, performing graceful shutdown; source=Some(LimitRequest)
```
I have moved this to a trace level event
=> fix(cyclone-server,veritech-server): Reducing the logging of shutdown events

docs/BUCK2.md
Add BUCK2 docs file for getting started with buck2, grokking high level
concepts and how to use buck2 and BUCK files.
The document contains a link to the "RUNNING_RUST_TESTS" document, which
describes similar, but more pointed, functionality.
_**[view the rendered file here](https://github.com/systeminit/si/blob/nick/e17b215/docs/BUCK2.md)**_
=> Add BUCK2 docs file (ENG-1968)

docs/BUCK2.md
Currently, the buck2 vsix hyperlink in the new BUCK2 doc implies that it goes to "VS Code", the editor. Now, it should imply that it links to the extension that can be locally built.
This commit also fixes the Discord badge in the same file to link to the server.
This is follow-up to https://github.com/systeminit/si/pull/2811
=> Ensure buck2 vsix hyperlink is clear (ENG-1969)

app/web/src/components/AttributeDebugView.vue, app/web/src/components/ComponentDebugModal.vue, app/web/src/components/ComponentDetails.vue, app/web/src/store/components.store.ts, lib/dal/src/attribute/value/view.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/debug.rs
We often want to know the answer to a few questions about a component's state:
- which function set each value on the component?
- what was the input to that function?
- where did the function get its input?
This adds a modal (accessed by clicking on the component id on the attributes panel) which will display that information in a basic way so a the source for the data for each attribute on a component can be quickly inspected.
This came out of an effort to understand the necessary pieces for reconstructing a component from a workspace backup, but should be helpful for us outside of that context.
=> feat(web, dal): Add component debug view

lib/sdf-server/tests/service_tests/functions.rs, lib/sdf-server/tests/service_tests/mod.rs
I did not cargo fmt prior to committing code after adding unit tests for the new `/execute` endpoint
=> (cleanup) fix issues related to formatting

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/components/AddSecretForm.vue, app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/PropertyEditor.vue, app/web/src/components/PropertyEditor/PropertyWidget.vue, app/web/src/components/PropertyEditor/WidgetSecret.vue, app/web/src/store/asset.store.ts, app/web/src/store/secrets.store.ts, bin/lang-js/src/asset_builder.ts, lib/dal/src/prop.rs, lib/dal/src/property_editor/schema.rs, lib/dal/src/queries/secrets/list_secret_definitions.sql, lib/dal/src/secret.rs, lib/sdf-server/src/server/service/secret.rs, lib/sdf-server/src/server/service/ts_types/asset_types_with_secrets.d.ts, lib/vue-lib/src/pinia/pinia_api_tools.ts
- Fail secret defining schema creation with more than one secret prop
- Show function exec errors asset creation
- Load secret Definitions from the backend
=> feat(web,dal,sdf,lang-js): Integrate secret widget into PropertyEditor

app/web/src/components/AttributeDebugView.vue, app/web/src/components/ComponentDebugModal.vue, app/web/src/store/components.store.ts, lib/dal/src/attribute/value.rs, lib/dal/src/component/view.rs, lib/dal/src/component/view/debug.rs, lib/dal/src/func.rs, lib/dal/src/func/execution.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/debug.rs, lib/si-pkg/src/lib.rs, lib/si-pkg/src/node/attribute_value.rs, lib/si-pkg/src/node/attribute_value_child.rs, lib/si-pkg/src/node/change_set.rs, lib/si-pkg/src/node/change_set_child.rs, lib/si-pkg/src/node/component.rs, lib/si-pkg/src/node/component_child.rs, lib/si-pkg/src/node/func.rs, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/node/position.rs, lib/si-pkg/src/pkg/func.rs, lib/si-pkg/src/spec.rs, lib/si-pkg/src/spec/attribute_value.rs, lib/si-pkg/src/spec/change_set.rs, lib/si-pkg/src/spec/component.rs, lib/si-pkg/src/spec/func.rs, lib/si-pkg/src/spec/position.rs
Adds the ability to export a component in a change set as a bag of attribute values. Disabled by default because the structure might change as import is implemented.
Also adds some more detail to the component debug view, and makes it prettier.
=> feat(dal,si-pkg): components in workspace backups, improve dbg view

lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs, lib/sdf-server/src/server/service/diagram/create_connection.rs
Two sdf endpoints were still missing application/json content-types
=> fix(sdf-server): add missing content-type headers

lib/dal-test/src/lib.rs, lib/dal/src/builtins.rs, lib/dal/src/lib.rs, lib/dal/src/pkg/import.rs, lib/module-index-client/src/client.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
This commit adds support for migrating built-in functions from a module index. The `migrate_builtins_from_module_index` function is introduced, which takes in the necessary dependencies such as the PostgreSQL pool, Nats client, job processor, Veritech client, encryption key, package path, and module index URL.
The function starts by creating a context with the provided dependencies and initializing a workspace. It then updates the tenancy and commits the changes. Next, it migrates the intrinsic functions using the `migrate_intrinsics` function from the `builtins::func` module.
After that, it retrieves the list of built-in modules from the module index and starts installing each module in parallel using the `install_builtins` function. The installation process is executed in a spawned …
=> feat: add migration of built-in functions from module index

lib/module-index-client/src/client.rs
If the local module index returns a 404 then we should pull the builtin from the production module-index
=> fix(module-index): Ensure that we download from the production module-index

app/web/src/components/modules/ModuleDisplay.vue, app/web/src/components/modules/ModuleListItem.vue, app/web/src/store/module.store.ts
We could promote a module to be a builtin but we couldn’t reject a builtin when it was created and thus the situation of not being able to replace an existing builtin
=> feat(web): Allow rejection of builtins

lib/dal/src/attribute/value.rs, lib/dal/src/context.rs, lib/dal/src/pkg/import.rs, lib/sdf-server/src/server/server.rs
Two changes:
1. Install each builtin on its own Postgres connection so they run
truly concurrently.
2. Skip dependent values updates on builtin installation for
near-instant builtin creation.
I can't figure out a reason to execute dependent value update jobs on
builtin creation. If there is a value that needs to exist on an
attribute for a schema variant in the default context, we can
pre-execute the function during authoring to produce a default value for
that attribute, or explicitly set the default value.  Otherwise, every
value computed by a function will be properly computed when the
component is created, and this is the context where we care about
computing the most up to date values in any case.
This makes builtin installation take about 30 seconds, which is a huge
win to me versus …
=> fix(sdf): builtins on transactions, skip dependent values update for builtins

lib/sdf-server/src/server/service/func.rs
Same as described [here](https://github.com/microsoft/TypeScript/issues/38040), the Typescript system does not extract deep information from `interface`s, so if we want the details on the hover/hotkey, we need them to be `type`s.
I have no idea what implications this might have elsewhere, so insight there would be good. Everything seems good in my tests still.
=> feat: change interfaces to types for quickinfo

app/web/src/components/AttributeDebugView.vue, app/web/src/store/components.store.ts, lib/dal/src/attribute/context.rs, lib/dal/src/component/view/debug.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/provider/external.rs, lib/dal/src/provider/internal.rs, lib/dal/src/queries/find_schema_variant_for_schema_and_name.sql, lib/dal/src/schema.rs, lib/module-index-server/src/s3.rs, lib/sdf-server/src/server/service/component/debug.rs, lib/si-pkg/src/lib.rs, lib/si-pkg/src/node/attribute_value.rs, lib/si-pkg/src/node/component.rs, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/pkg.rs, lib/si-pkg/src/pkg/attr_func_input.rs, lib/si-pkg/src/pkg/attribute_value.rs, lib/si-pkg/src/pkg/change_set.rs, lib/si-pkg/src/pkg/component.rs, lib/si-pkg/src/pkg/position.rs, lib/si-pkg/src/spec/attribute_value.rs, lib/si-pkg/src/spec/component.rs
Components exported to workspace backups are now imported. Edges are not connected but all other attributes set on the component will be restored with the values they had on export.
=> feat(dal,si-pkg): Import components from workspace backups

lib/dal/src/component.rs, lib/dal/src/diagram/node.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs
We need to preserve deleted components in backups so they can be restored if they have a resource. This ensures we restore them in their deleted state.
=> feat(dal): properly delete components that are deleted in backups

app/web/src/components/WorkspaceExportModal.vue, app/web/src/components/WorkspaceImportModal.vue, lib/dal/src/pkg.rs, lib/dal/src/pkg/import.rs, lib/dal/src/prop.rs, lib/sdf-server/src/server/service/pkg/install_pkg.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
Does not create attributes for props that are missing or have changed types on the builtin. Also avoid connecting functions to inputs if the prop for that input cannot be found.
The info for the mismatch is not yet displayed in the import modal, but is returned on the install_pkg API response.
=> feat(dal,sdf-server): Gracefully import components from outdated builtins

bin/lang-js/src/sandbox/exec.ts, bin/lang-js/tests/exec.spec.ts
This adds 'siExec.watch()' to lang-js. It allows you to watch the output of an siExec.waitUntilEnd over repeated calls, and should be handy any time you need to poll the state of something while you wait for it to succeed.
```typescript
// Get the date in seconds since the epoch
const getCurrentTime = await siExec.waitUntilEnd("date", ["+%s"]);
const startSeconds = getCurrentTime.all || "3";
// Wait until its at least 3 seconds later;
const waitUntil = startSeconds + 3;
// Call date, trying again every 2 seconds, a maximum of 10 times, and
// return true if more than 3 seconds have elapsed.
const r = siExec.watch({
cmd: "date",
args: ["+%s"],
retryMs: 2000,
maxRetryCount: 10,
callback: async (r) => {
const elapsed = r.all || "3";
return elapsed > waitUntil;
}
});
// r.result == the …
```
=> feature: watch in siExec

lib/sdf-server/src/server/service/func.rs
The new watch func is missing a definition in SDF, so it appeared untyped in the editor. We absolutely need a better way to do this.
=> fix: missing watch def from SDF

app/web/src/components/WorkspaceExportModal.vue
The production build of the web app seems to be reacting differently, causing the loading button on the workspace export modal to stick around. This logic rework fixes it when tested with `vite build; vite preview`
=> fix(web): slightly rework workpace export modal logic

component/rabbitmq/BUCK, component/rabbitmq/Dockerfile, component/rabbitmq/README.md
Add si-rabbitmq DockerHub image for ENG-1703 ("Mostly Everything is a Node or an Edge") graph work. This directory is being added to main to get the image building and published in advance to the long running dev branch getting merged.
The new image is not used for anything other than image building, promoting and publishing.
The code in this PR was taken from https://github.com/systeminit/si/pull/2424.
=> Add systeminit/rabbitmq DockerHub image (ENG-1990)

app/web/src/components/WorkspaceExportModal.vue, lib/vue-lib/src/design-system/layout/Stack.vue, lib/vue-lib/src/utils/vue_utils.ts
very odd issue only visible when running the built version of the app where some children of `Stack` were not being re-rendered. I didn't manage to get a minimal reproduction put together, but I was eventually able to get it fixed 🤷
=> fix weird Stack rendering issue

app/web/src/components/AttributeDebugView.vue, app/web/src/store/components.store.ts, lib/dal/src/component/view/debug.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/prop.rs, lib/sdf-server/src/server/service/component/debug.rs, lib/sdf-server/src/server/service/pkg/install_pkg.rs, lib/si-pkg/src/node/attribute_value.rs, lib/si-pkg/src/pkg/attribute_value.rs, lib/si-pkg/src/spec/attribute_value.rs
Two issues were preventing the resource from being restored from a workspace backup:
1. The resource "payload" prop was being skipped because it is typed as a string but we store an object there typically (we store unrestricted json on it even though it is a "string").
2. We need to emit the implicit attribute values for props if they are there.
Adding 2 did not totally fix it, so component.set_resource was resorted to to set the resource on the component if a value for it exists.
=> fix(dal,si-pkg): export and import resource properly in backup

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/store/asset.store.ts, app/web/src/store/func/funcs.store.ts, app/web/src/utils/typescriptLinter.ts, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/create_func.rs, lib/sdf-server/src/server/service/func/defaults/action.ts, lib/sdf-server/src/server/service/func/defaults/attribute.ts, lib/sdf-server/src/server/service/func/defaults/code_generation.ts, lib/sdf-server/src/server/service/func/defaults/qualification.ts, lib/sdf-server/src/server/service/func/defaults/validation.ts, lib/sdf-server/src/server/service/func/get_func.rs, lib/sdf-server/src/server/service/func/save_func.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/create_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/get_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs, lib/sdf-server/tests/service_tests/functions.rs, lib/sdf-server/tests/service_tests/scenario.rs, lib/sdf-server/tests/service_tests/scenario/authoring_flow_asset.rs
We now handcode this to be `main` by default. We have already updated all the builtins to use `main` and we have added a typescript lint warning to let people know they need a main entrypoint for a function
=> feat(web,sdf-server): Remove the need to set handler on functions and assets

app/web/src/store/module.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/pkg.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/pkg.rs, lib/sdf-server/src/server/service/pkg/install_pkg.rs
Adds a new WsEvent for module import success and hard refreshes windows other than the one doing the import when a workspace backup import succeeds.
=> feat(dal,sdf,web): WsEvent for workspace backup import

lib/si-cli/src/cmd/configure.rs, lib/si-cli/src/key_management.rs
Fixes: #2659
This allows us to point our SI instance against a localstack setup in the veritech container
All we need to do is to pass an endpoint url as part of the configure command :) It can even use fake credentials
PLEASE NOTE: Qualifications that use `--dry-run` in AWS will return an empty response from localstack - but you would be able to check the localstack logs for a 200 response:
```
2023-10-18T22:11:31.320  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ec2.CreateVpc => 200
```
https://share.descript.com/view/Uq3tBNcL3oU
=> feat(si-cli): Add support for custom AWS ENDPOINT URLs

bin/lang-js/src/sandbox.ts, lib/sdf-server/src/server/service/func.rs
This will allow assets which need gzipped strings to be created.
Tested with a codegen func defined like so
```typescript
async function main(component: Input): Promise < Output > {
const zippedstring = "This string will be zipped";
zlib.gzip(zippedstring, (err, compressedData) => {
if (!err) {
console.log('Compressed data:', compressedData.toString('base64'));
} else {
console.error('Error compressing data:', err);
}
});
return {
format: "json",
code: JSON.stringify(component),
};
}
```
=> feat: (lang-js) Added zlib to the standard sandbox. 

app/web/src/components/AssetActionsDetails.vue, app/web/src/components/ComponentDetails.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, lib/dal/src/component/diff.rs, lib/vue-lib/src/design-system/layout/Inline.vue, lib/vue-lib/src/design-system/tabs/TabGroup.vue
adds new minimal tab style which can be toggled on. For now we'll use wherever we have nested tabs, but may want to consider using in other places as well.
also fixes the diff tab when viewing head and other small tab related issues.
=> feat(web,vue-lib) alternate minimal tab style

bin/lang-js/BUCK, prelude-si/macros.bzl, prelude-si/macros/pnpm.bzl, prelude-si/pnpm.bzl
With this change, the jest-implementated test suite for `bin/lang-js` will be executable and automatically picked up for execution in the CI environment.
=> build(buck2): create a `jest` rule for use in lang-js' test-unit target

lib/cyclone-core/src/schema_variant_definition.rs, lib/dal/src/func/backend/js_action.rs, lib/dal/src/func/backend/js_reconciliation.rs, lib/dal/src/func/backend/js_schema_variant_definition.rs, lib/dal/src/func/backend/js_validation.rs, lib/dal/tests/integration_test/internal/func/schema_variant_definition.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
Attribute functions will need more work to deal with how to return the failure to the user. As regular attribute functions only return a prop value, like a string or number.
We can implement for code-gen, qualification, etc. Which will be the next steps, but regular propagation functions will be though.
=> feat(sdf,dal,cyclone): handle js crashes except for attributes

lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_whiskers.rs
As per:
https://buildkite.com/system-initiative/si-nightly/builds/120#018b36db-600d-4cb5-aa4e-9fd5f1b49d58
Amended the response object assertion to correctly match our expectation in the integration test. Comment still present but returning success not warning.
=> chore(sdf): amend assertion in nightly integration test

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/components/CodeEditor.vue, app/web/src/components/PropertyEditor/PropertyWidget.vue, app/web/src/components/PropertyEditor/WidgetCodeEditor.vue, bin/lang-js/src/asset_builder.ts, lib/dal/src/property_editor/schema.rs, lib/sdf-server/src/server/service/ts_types/asset_builder.d.ts, lib/sdf-server/src/server/service/ts_types/asset_types_with_secrets.d.ts, lib/si-pkg/src/spec/prop.rs, lib/vue-lib/src/design-system/modals/Modal.vue
Does not have syntax highlighter, linter, etc because it doesn't know the language, we should improve that somehow (it's not clear to me right now how to do it best and it feels like a immediate benefit even without it)
=> feat(web,dal,sdf): add code editor widget

lib/dal/src/func/argument.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant/root_prop.rs, lib/dal/tests/integration_test/internal/component.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/node/root_prop_func.rs, lib/si-pkg/src/node/schema_variant.rs, lib/si-pkg/src/node/schema_variant_child.rs, lib/si-pkg/src/pkg.rs, lib/si-pkg/src/pkg/root_prop_func.rs, lib/si-pkg/src/pkg/variant.rs, lib/si-pkg/src/spec.rs, lib/si-pkg/src/spec/root_prop_func.rs, lib/si-pkg/src/spec/variant.rs
This allows us to define a function on a direct child of root (domain, resource_value, secrets, etc.) and then have it preserved in module import/export.
To preserve existing behavior, if a function is not defined on resource_value, we will automatically attach si:resourcePayloadToValue to set that value. Otherwise the custom function will be used.
That function must be detached before a custom function is attached to an asset's resource_value prop.
=> feat(dal,si-pkg,sdf): Export/import functions on direct children of root

BUCK, Cargo.lock, Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Ref: Discord issue regarding issues with SI Launcher.
[Bump models to v1.43](https://github.com/vv9k/docker-api-rs/commit/851f7091e945d04c055b24809a9b375fc3f0c80d) was merged into the docker-api crate on 10th June
The commit/change never made it into the crate itself, being [last published on 5th June](https://crates.io/crates/docker-api/versions) (0.14.0): There isn't a version of this crate with the updated option config in it
To that end, moved to using a git reference off HEAD for the build.
NB: It's noteworthy we have two different crates for docker-api interaction across our monorepo: bollard and docker-api. I suggest at some point we consolidate these/use the most common one.
Added `:si` build target for Buck for convenience
```
~/D/RISCOSPi.5.28 > si update
System Initiative …
```
=> fix: bump docker-api crate to git ref

app/web/src/components/AssetPalette.vue
Search was returning an entire group if it matched a single asset within the group. This fixes it so it returns matching groups and individual matching assets only.
=> fix: asset search not filtering assets from matched groups

app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/web/src/pages/auth/RefreshAuthPage.vue, app/web/src/router.ts, app/web/src/store/auth.store.ts, lib/dal/src/queries/user/list_members_for_workspace.sql, lib/dal/src/user.rs, lib/sdf-server/src/server/service/session.rs, lib/sdf-server/src/server/service/session/auth_connect.rs, lib/sdf-server/src/server/service/session/refresh_workspace_members.rs
This page is basic for now and we redirect both ways but we can make this better. It will compare the users from the auth-api against what’s in our DB - the auth-api is the source of truth!!
There are a number of improvements needed for this but we can start to use it immediately for internal use
In the future, this will be replaced by the use of websockets to do the same job
=> feat(sdf-server, auth-portal, web): adding a page that we can send a post request to that forces auth cleanup

app/web/src/components/FuncEditor/FuncTest.vue
Previously the test log was repeated 1000 times, now it is not.
=> bug (app): removed repeat line for testlogs

app/web/src/api/sdf/dal/history_actor.ts, app/web/src/components/ActionSprite.vue, app/web/src/components/ApplyHistoryItem.vue, app/web/src/components/ChangesPanel.vue, app/web/src/store/actions.store.ts, app/web/src/store/fixes.store.ts, lib/dal/src/action.rs, lib/dal/src/actor_view.rs, lib/dal/src/change_set.rs, lib/dal/src/diagram/node.rs, lib/dal/src/fix/batch.rs, lib/dal/src/migrations/U2402__actions_with_actor.sql, lib/dal/src/migrations/U2403__fix_batch_with_actor.sql, lib/dal/src/queries/change_set/get_actors.sql, lib/sdf-server/src/server/service/change_set/apply_change_set.rs, lib/sdf-server/src/server/service/change_set/list_open_change_sets.rs, lib/sdf-server/src/server/service/fix/list.rs, lib/sdf-server/src/server/service/fix/run.rs
We now show history actor details at an action and change level:
and we also work out the full list of actors involved in the Applied Changeset and list them alongside the person who merged the changeset
=> feat(sdf, dal, web): Add ability to understand who has taken what action in a changeset

lib/dal/src/user.rs, lib/dal/tests/integration_test/internal/user.rs, lib/sdf-server/src/server/extract.rs
If a user has been removed from a workspace, then we make a best guess at removing them from the workspace by removing them from the user_belongs_to_workspace table
That wasn't fully implemented because if they were still on the workspace then they could still interact with the diagram. If we remove the user from the user_belongs_to_workspace table then this will now check on any SDF interaction and if unathorized, the UI will kick them out
=> feat(sdf-server): Ensure that the user is authorized before allowing any interactions

app/auth-portal/src/components/WorkspaceLinkWidget.vue, app/auth-portal/src/store/workspaces.store.ts, bin/auth-api/prisma/migrations/20231102231111_workspace_members_invited_at/migration.sql, bin/auth-api/prisma/schema.prisma, bin/auth-api/src/services/workspaces.service.ts
Also, show when you were invited to a workspace. Any existing invitations will be set to the date we run this migration as we don’t have a backward set of data on this
=> feat(auth-api, auth-portal): Show the owner of the workspace when you are an editor

bin/auth-api/src/services/users.service.ts
If a user was invited, then signed up, we would get the auth0Id but never set it to the database. When they logged back in, they would have a signupAt but no auth0Id which would cause a user to be a new user not an existing user
This would have again caused a user to lose their invite as it would be for an account that didn’t exist
=> fix(auth-api): Ensure we are setting auth0id

.envrc
In the `.envrc` the `dotenv` directive requires the `.env` exist, or direnv will output an error message. Having a `.env` is an optional thing to support developer-specific things. By using `dotenv_if_exists`, direnv no longer considers it an error if the file doesn't exist.
=> chore(direnv) Make not having a .env no longer an error

app/web/src/components/AssetDetailsPanel.vue
Previous it would say create when it was updating now looks like
=> fix(web): Update terminology when updating an Asset

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/store/presence.store.ts
We now have 3 ways the modal can work:
-> There are no other users in the changeset and no actions - we get a simple confirmation
-> There are no other users in the changeset BUT there are actions - we get a modal with a list of the actions that will be applied
-> There are other users in the workspace - we now show a modal to the user who merged. That modal (in this turn) only gives the ability to `Skip Approval and Merge`
The next follow on will be to show the approvals workflow.
The outstanding question is:
* At what point do we list the actions that will be merged in the changeset? I beliefe that we should show it as part of the voting dialogue…
=> feat(Web): Change how Apply Changeset button works

Cargo.lock, Cargo.toml, bin/cyclone/BUCK, bin/cyclone/Cargo.toml, bin/cyclone/Dockerfile, bin/cyclone/create-firecracker-root-fs.sh, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, lib/cyclone-server/BUCK, lib/cyclone-server/Cargo.toml, lib/cyclone-server/src/config.rs, lib/cyclone-server/src/lib.rs, lib/cyclone-server/src/server.rs, lib/cyclone-server/src/vsock.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Allows cyclone-server to connect via vsock.
The changes for deadpool and cyclone-client (if any) are not ready to be merged. The changes introduced by this should be non-functional/dead until the other half of the change is merged into main.
=> feat: add vsock support to cyclone-server

app/web/src/api/sdf/dal/change_set.ts, app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/store/change_sets.store.ts, app/web/src/store/presence.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/change_set.rs, lib/dal/src/queries/change_set/cancel_merge_flow.sql, lib/dal/src/queries/change_set/open_list.sql, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/change_set.rs, lib/sdf-server/src/server/service/change_set/begin_approval_process.rs, lib/sdf-server/src/server/service/change_set/merge_vote.rs
There are a number of differnet states going on here:
1. No collaborators on the changeset
* No Actions so we get a simple confirmation modal (this is new!!)
* Actions so we get a list of actions to be applied in the modal
2. Collaborators in the changeset
* We begin a change set approval - changeset status moves to NeedsApproval
* Each collaborate gets a modal to vote (Accept, Pass, Reject)
* When a collaborate has voted their changeset usage is locked until the merge has completed or been cancelled
* If *ANY* of the collaborators reject the merge then the person needs to take an action of override or cancel. * If approved then it's a normal merge process * If cancelled then the changeset is unlocked for everyone and the status changes back to Open
* If all collaborators choose pass or …
=> feat(web, dal, sdf): Create a light approval / notification system

app/auth-portal/src/App.vue, app/auth-portal/src/components/WorkspaceLinkWidget.vue, app/auth-portal/src/store/api.ts, app/auth-portal/src/store/auth.store.ts, bin/auth-api/.env, bin/auth-api/.gitignore, bin/auth-api/package.json, bin/auth-api/src/lib/redis.ts, bin/auth-api/src/routes/auth.routes.ts, bin/auth-api/src/routes/user.routes.ts, bin/auth-api/src/routes/workspace.routes.ts, bin/auth-api/src/services/auth0.service.ts, bin/auth-api/src/services/users.service.ts, bin/auth-api/test/auth-routes.test.ts, bin/auth-api/test/helpers/auth0-mocks.ts, bin/auth-api/test/helpers/global-setup.ts, bin/auth-api/test/helpers/test-suite-hooks.ts, pnpm-lock.yaml
- add auth api endpoints to refresh profile from auth0 and resend verification email
- refresh auth0 profile (which includes email verification status) while connecting to workspace
- add error banner on auth portal to get users to verify their email
- block workspace login widget when email is not verified
- general cleanup around user creation/login and profile fetching logic
- this uses a new "machine to machine" auth0 app, so we are connecting as our app to fetch user profile data, rather than as the user themselves (using their token)
NOTE - we'll need to add a new env var for the m2m auth0 client secret to deploy
=> feat(auth) handle email verification and refreshing from auth0

Cargo.lock, Cargo.toml, bin/cyclone/Dockerfile, bin/cyclone/create-firecracker-root-fs.sh, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, lib/cyclone-client/src/client.rs, lib/cyclone-server/BUCK, lib/cyclone-server/Cargo.toml, lib/cyclone-server/src/config.rs, lib/cyclone-server/src/lib.rs, lib/cyclone-server/src/server.rs, lib/cyclone-server/src/vsock.rs, lib/deadpool-cyclone/examples/deadpool-cyclone-resolver-function-pool/main.rs, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/deadpool-cyclone/src/lib.rs, lib/sdf-server/tests/service_tests/functions.rs, lib/veritech-server/src/server.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Adds a new function execution platform variant of (`LocalUdsRuntimeStrategy` named `LocalFirecracker`) which uses Firecracker Micro-VMs to execute the functions within.
This PR also includes conditional compiling of the VSOCK elements which are not supported on Mac `M` series chips and some others. This allows the default compilation execution strategy (LocalProcess) to be used on `all` hosts compatible with SI, not just those which are compatible with the `firecracker specific` elements on the build. It's important to note that due to this, binaries produced on a host which does not support firecracker, will not be able to execute on firecracker even on another host that `does` support it. 
Currently the Firecracker host must be `local` to the context of the rest of the stack. I.e. this …
=> [wip] firecracker spawn variant

lib/sdf-server/BUCK, lib/sdf-server/src/server/service/ws.rs, lib/sdf-server/src/server/service/ws/crdt.rs, lib/sdf-server/tests/service_tests/crdt.rs
Since we used websockets the port had to be available when starting the test, causing a failure if for some reason it isn't.
So we moved that logic from websockets to Streams and Sinks.
- Abstract CRDT broadcast logic over a `Sink<Message>` and `Stream<Message>` instead of using WebSockets directly
- Create a `Sink<Message>` and a `Stream<Message>` in tests from a tokio::broadcast channel pair
- Create a `Sink<Vec<u8>>` and a `Stream<Vec<u8>>` in tests from the `Sink<Message>/Stream<Message>`, to properly integrate with y_sync test machinery
- Create server and client structs over those sinks/streams to emulate the websocket ones
=> Make crdt tests stable

component/firecracker-base/orchestrate-install.sh, component/firecracker-base/prepare_jailer.sh, component/firecracker-base/start.sh, component/firecracker-base/stop.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
This:
* Adds a new script that can prepare a jail in advance, including all necessary networking and filesystem bits
* Extends the orchestrate script to run this prepare script _n_ times with the intention that this can be used to prepare jails in advance (like when Veritech starts up)
* Removes all of the startup bits from `start.sh` besides actually running the VM, which should be much faster
* All aforementioned scripts are idempotent, so they can be re-run without explosions happening, except `start.sh` because...
I don't think we are ever running `terminate()` to clean up the VMs. This isn't an issue with docker (or tokio?) processes as they automatically die once complete, but there is a non-trivial amount of cleanup that needs to happen here. We'll need to address this in a …
=> feat: move jailer configuration to machine setup time

component/firecracker-base/orchestrate-install.sh, component/firecracker-base/prepare_jailer.sh, component/firecracker-base/start.sh, component/firecracker-base/stop.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
This fixes some bugs from the last round of changes, but primarily it adds Copy-on-Write support for the rootfs so we no longer need to copy the 1gb image to each jail. This drastically reduces both the size of the jails and the speed at which we can create them. this should allow us to create 5000+ jails in advance on the metal instances.
This was heavily influenced by the approach [here](https://parandrus.dev/devicemapper/)
=> feat: copy-on-write layer for rootfs

bin/cyclone/BUCK, bin/lang-js/BUCK, bin/veritech/BUCK, prelude-si/git/git_info.py, prelude-si/macros.bzl, prelude-si/macros/nix.bzl, prelude-si/nix.bzl, prelude-si/nix/BUCK, prelude-si/nix/nix_omnibus_pkg_build.py, prelude-si/nix/toolchain.bzl, toolchains/BUCK
This change adds a new Buck2 rule type called `nix_omnibus_pkg` which
can build a Nix package (that is, one from the local Nix flake) and
produce a compressed tarball with all required runtime packages
necessary to run the software (Nix users might call this a "nix package
closure").
Package Metadata
----------------
Some package metadata is generated to help track the origin of
the various Nix packages on disk. For example, after building a package
for `bin/council`, the following metadata might be produced:
```json
{
"architecture": "x86_64",
"author": "The System Initiative <dev@systeminit.com>",
"binaries": [
"/nix/store/qckjfjc1b1zyqbg5qc6aaxlwll2xnrfi-council/bin/council"
],
"commit": "9a1545a37afbf704699be0920f21ef48c7f43515-dirty",
"license": "Apache-2.0",
"name": "council", …
```
=> feat(buck2): create `nix_omnibus_pkg` rule to make portable binary pkgs

component/firecracker-base/orchestrate-install.sh, component/firecracker-base/prepare_jailer.sh, lib/veritech-server/src/config.rs
Just some small enhancements to the startup script. I'm pinning the jails to 1k instead of 5k for now. Creating 5k jails takes way too long, get exponentially slower and flakier as more jails are created. I think this is the best this script can do and that the more correct answer here is to have a discrete service or a background thread in Veritech that recycles jails as needed.
=> feat: small fixes for the startup scripts

app/web/src/components/ComponentDetails.vue
=> fix(web): Ensure we format the component code tab

bin/cyclone/BUCK, prelude-si/artifact.bzl, prelude-si/artifact/BUCK, prelude-si/artifact/promote.py, prelude-si/artifact/publish.py, prelude-si/artifact/toolchain.bzl, prelude-si/git/git_info.py, prelude-si/macros/nix.bzl, prelude-si/nix/nix_omnibus_pkg_build.py
`artifact_promote` Buck2 Rule
-----------------------------
This change adds a new Buck2 rule, `artifact_promote` which will create
or update AWS S3 [website redirect location] metadata in empty S3 objects
to serve as HTTP/301 redirects. Additionally, if the
`--cloudfront-distribution-id` option is provided or if the
`AWS_CLOUDFRONT_DISTRIBUTION_ID` environment variable is set, the
promotion will invalidate the appropriate paths in AWS CloudFront to
ensure that the redirects are up to date.
[website redirect location]: https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html#redirect-requests-object-metadata
Updated S3 Path Strategy
------------------------
This change also updates the S3 object locations to importantly include
a version path entry. This allows us …
=> feat(buck2): create `artifact_promote` rule & update `artifact_publish`

component/firecracker-base/orchestrate-install.sh, component/firecracker-base/stop.sh, lib/deadpool-cyclone/src/instance.rs, lib/deadpool-cyclone/src/instance/cyclone/local_http.rs, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/deadpool-cyclone/src/lib.rs
This adds some robustness to our startup script so that we can dynamically choose whether to do things like download new rootfs or kernel images. It also adds force recreating jails if necessary (such as if you download a new rootfs). I added some flags to make this easier to use on the command line and a help block.
I also made it so we actually call `terminate()` when when recycling the pool. In the case of Firecracker, we will clean the jail and set it up again. I think a better way to do this would be just clean replace the rootfs and remove the jailer bits, but this is fine for now.
=> feat: terminate on recycle, startup fixes

app/web/src/components/FuncEditor/LeafInputs.vue, app/web/src/store/func/types.ts, lib/dal/src/attribute/value.rs, lib/dal/src/schema/variant/leaves.rs, lib/dal/src/schema/variant/root_prop.rs, lib/sdf-server/src/server/service/component/update_property_editor_value.rs, lib/sdf-server/src/server/service/func/save_func.rs, lib/si-pkg/src/spec/leaf_function.rs
By setting the toggle above, `root/secrets` will be set as input to the function. At runtime, the system will detect the dependency on secrets, wipe that from the args of the main function to be executed and trigger fetching the before functions.
As a corollary, auth functions now  will only run when explicitly set by the user
=> feat(dal,web) Make secrets work inside the dependency reactivity system

app/artifact-status/README.md, app/artifact-status/index.html
Adds a simple webpage which is currently hosted at the root of the bucket behind https://artifacts.systeminit.com which gives a traversable view of the content of our production CDN.
We can extend this pretty easily in the future to also cover our docker registries, or other repositories as our footprint grows.
NB: Simple client-side implementation that leaves `a lot` of room for improvement.
=> feat: add artifact-status webpage

bin/veritech/src/args.rs, lib/cyclone-client/src/client.rs, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
This adds flags to veritech to configure the runtime type and the size of the pool. These flags are passed down into cyclone-server/client to configure the respective settings.  As an example, to tell Veritech to use Firecracker:
```bash
$ buck2 run bin/veritech -- --cyclone-local-firecracker --cyclone-pool-size 500
```
=> feat: veritech flags to configure runtime

app/web/src/components/layout/navbar/ChangeSetPanel.vue
Without this change, the following error fires starting the site and it just crashes:
```
Uncaught (in promise) TypeError: $setup.abandonConfirmationModalRef is undefined
_sfc_render ChangeSetPanel.vue:34
renderComponentRoot runtime-core.esm-bundler.js:816
componentUpdateFn runtime-core.esm-bundler.js:5701
run reactivity.esm-bundler.js:178
update runtime-core.esm-bundler.js:5814
setupRenderEffect runtime-core.esm-bundler.js:5822
mountComponent runtime-core.esm-bundler.js:5612
processComponent runtime-core.esm-bundler.js:5565
patch runtime-core.esm-bundler.js:5040
mountChildren runtime-core.esm-bundler.js:5284
```
=> fix(web): Ensure that the right func is called for changeset abandon

bin/veritech/veritech.service, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/veritech-server/src/config.rs
Adds the systemd service file for veritech. Ideally we ship this as an artifact along with veritech itself so we can version it with the binary. We can then just grab both in user data and `systemctl daemon-reload && systemctl enable veritech --now`
=> feat: add veritech service file

app/artifact-status/index.html
Amends the download link in the https://artifacts.systeminit.com webpage for the final objects in the S3 store to redirect the user back through the CDN for better cache performance on download.
Noted as a fix because previously the `stable` object pointers would never resolve/follow the S3 metadata redirects because it would be trying to resolve the redirect directly on the bucket, which never worked.
I.e. previously
```
curl https://si-artifacts-prod.s3.amazonaws.com/cyclone/stable/rootfs/linux/aarch64/cyclone-stable-rootfs-linux-aarch64.ext4
```
=> fix: amend download link on artifacts.systeminit.com static site

lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/deadpool-cyclone/src/orchestrate-install.sh
This removes startup parallelization to avoid some locking issues we found. It also appropriately handles file copy errors.
=> fix: startup script error handling

bin/council/src/args.rs, bin/pinga/src/args.rs, bin/sdf/src/args.rs, bin/veritech/src/args.rs, lib/si-data-nats/src/connect_options.rs, lib/si-data-nats/src/lib.rs
This adds the ability to authenticate with nats using either a credential file or a credential string. These credentials must follow the format defined [here](https://docs.nats.io/using-nats/developer/connecting/creds). 
This is only required if the NATs server is using authentication, such as if you are using [NGS](https://app.ngs.global/).
=> feat: add cred string and file options for NATs auth.

bin/council/src/args.rs, bin/pinga/src/args.rs, bin/sdf/src/args.rs, bin/veritech/src/args.rs, lib/si-data-nats/src/lib.rs
This allows giving a connection name to nats. This makes it easier to identify who is connecting to nats. We're considering using a managed nats solution and without this the UI shows all of the connections as `unknown` . Here's a before and after:
=> feat(nats): add connection name to nats connection

lib/sdf-server/src/server/service/func/defaults/validation.ts
The default message for a validation function was the opposite of what was intended. This fixes it.
I have rebuilt my local sdf after this change and the default function behaves as expected.
=> bug (sdf): fix default validation function message to be accurate

lib/dal/src/lib.rs, lib/sdf-server/src/server/service/diagram/create_node.rs
Currently, every asset is named in a `si-1234` style. With this change, they now default to `Schema Name 1234` style, which is much nicer on the old eyeballs.
=> feat(sdf): use schema names for model name defaults

lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/lib.rs, lib/dal/src/prop.rs, lib/dal/src/property_editor.rs, lib/dal/src/property_editor/schema.rs, lib/dal/src/property_editor/values.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/internal/mostly_everything_is_a_node_or_an_edge.rs, lib/dal/tests/integration_test/internal/mostly_everything_is_a_node_or_an_edge/property_editor.rs, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/get_property_editor_schema.rs, lib/sdf-server/src/server/service/component/get_property_editor_validations.rs, lib/sdf-server/src/server/service/component/get_property_editor_values.rs
Primary:
- Restore PropertyEditorSchema with the new engine
- Restore PropertyEditorValues with the new engine
- Use an empty response for PropertyEditorValidations
Secondary:
- Add "EdgeWeightKind::Root" for the root AttributeValue
- Components "use" both AttributeValues corresponding to providers as well as the root AttributeValue, so this edge indicates which one is root
- It is possible we may want _both_ a "Use" and a "Root" edge for the root AttributeValue in the future, but until multiple edges for a given source and target is functional, this will suffice
- Add integration test for assembling the property editor
- This test is trivial and is mostly useful for debugging output
- Restore the Prop "documentation" field
- Ensure "WidgetOptions" works with postcard
- Postcard wants a …
=> Restore property editor (read-only)

prelude-si/rootfs/rootfs_build.sh
This changes the rootfs build from using the alpine docker image to downloading the rootfs directly and `chroot`ing it into the right shape. The docker path works fine locally, but fails in CI due running this as docker in docker, which makes bind mounting the scripts and directories fraught with peril as it tries to mount from the **host**, not the local container. This should make this process more reliable in general and a little faster. @fnichol I think you made changes to make docker in docker work correctly. I'm not sure if we should go back and remove those, I'm not sure exactly where they live.
=> feat: refactor rootfs to not use docker

app/web/src/components/ApplyHistory.vue, app/web/src/components/ApplyHistoryItem.vue, app/web/src/components/AssetActionsDetails.vue
=> fix(web): Mark the applied history as collapsed by default 

app/web/src/components/ActionWidget.vue, app/web/src/components/AssetActionsDetails.vue, app/web/src/components/AssetDiffDetails.vue, app/web/src/components/AttributesPanel/AttributesPanelItem.vue, app/web/src/components/ComponentCard.vue, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, lib/vue-lib/src/design-system/icons/icon_set.ts
- disable the change set abandon button while on HEAD
- prevent users from naming a change set "head" (on the front end only)
- add map item error message if you try to add an item without a key
- AssetActionDetails UI more closely matches the rest of the UI
- hover states for clickable diff icons on the diagram and ComponentCard
- "No Code" message in AssetDiffDetails shows outside of a CodeViewer
=> feat(web) - various UI improvements

bin/council/src/args.rs, bin/pinga/src/args.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, bin/veritech/src/args.rs, lib/pinga-server/src/config.rs, lib/pinga-server/src/server.rs, lib/sdf-server/src/server/config.rs, lib/sdf-server/src/server/server.rs, lib/si-crypto/src/cyclone.rs, lib/si-crypto/src/cyclone/config.rs, lib/si-crypto/src/cyclone/encryption_key.rs, lib/si-crypto/src/lib.rs
Needs a bunch of clean up, but it works!
```bash
./buck-out/v2/gen/root/524f8da68ea2a374/bin/pinga/__pinga__/static_pic/pinga --cyclone-encryption-key-base64 $(cat lib/cyclone-server/src/dev.encryption.key | base64) -vvvv
2023-12-19T02:49:41.677935Z  INFO ThreadId(61) telemetry_application: updated tracing levels to: "trace,pinga=trace,pinga_server=trace"
2023-12-19T02:49:41.679335Z TRACE ThreadId(02) config_file::layered_load: merging defaults config for defaults=SerdeSource { source: ConfigFile { pg: PgPoolConfig { user: "si", password: ..., dbname: "si", application_name: "si-unknown-app", hostname: "localhost", port: 5432, pool_max_size: 128, pool_timeout_wait_secs: None, pool_timeout_create_secs: None, pool_timeout_recycle_secs: None }, nats: NatsConfig { connection_name: None, …
```
=> [wip] feat: pass encryption key as base64 string

app/web/docker-entrypoint.sh
This is a feature change fix to allow us to deploy + drive web api requests to a custom sdf endpoint/dns entry (whilst still hosted in dockerised nginx).
For Production, we are going to host the web docker image in ECS and front it with an ALB Cloudfront (excluding /api for the cache layer) and route the traffic via an ALB either to either the SDF service or web depending on route.
A bit like this:
```
Cloudfront (app.systeminit.com) <---------> WAF Association
<excluding /api/* from cache>
|
ALB 
| ___alb_________  / ________ web
|________ /api ______ sdf
```
So a user session will look like:
```
browser -----> api.systeminit.com/index.html 
*browser loads javascript/page*
browser -----> api.systeminit.com/api #for dynamic page content
```
This should be non-breaking throughout uses of …
=> feat: added drive-ability to web in docker for sdf route

app/web/docker-entrypoint.sh
Using a `/` delimiter in the replace was a poor choice, as something like `https://app.systeminit.com/api` as the SI__SDF__HOST variable escapes the sed and throws a non-zero exit code, failing the replace.
Using `^` should be better as we'll need want to pass various strings in there over time
=> fix: using alternative delimiter permits http-type forms

lib/si-cli/src/engine/docker_engine.rs, lib/si-cli/src/engine/podman_engine.rs
I changed how the defaults work so I could pass this as a base64 encrypted string. This adds the path to the containers directly.
Verified on both linux and macos.
=> fix: pass the encryption key path for the launcher

bin/pinga/src/args.rs, bin/sdf/src/args.rs, lib/dal-test/src/lib.rs, lib/dal/examples/dal-pkg-export/main.rs, lib/dal/examples/dal-pkg-import/main.rs, lib/pinga-server/src/config.rs, lib/sdf-server/src/server/config.rs, lib/si-cli/src/engine/docker_engine.rs, lib/si-cli/src/engine/podman_engine.rs, lib/si-crypto/src/symmetric.rs
This lets us pass the cbor encoded key that we use to encrypt secrets as a base64 string so we can host in ECS. This was a bit more surgery than the last one, but we got there in the end.
=> feat: allow passing the secret as a base64 string

app/web/src/store/asset.store.ts, app/web/src/store/change_sets.store.ts, app/web/src/store/component_attributes.store.ts, app/web/src/store/components.store.ts, app/web/src/store/fixes.store.ts, app/web/src/store/func/funcs.store.ts, app/web/src/store/qualifications.store.ts, app/web/src/store/realtime/realtime.store.ts, app/web/src/store/reconciliations.store.ts, app/web/src/store/secrets.store.ts
not a good longterm solution, as this actually introduces delay between receiving events and things happening... BUT this is a good fix for now until we fire off smarter events instead of refreshing everything constantly
=> debounce ChangeSetWritten

lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/value.rs, lib/dal/src/builtins.rs, lib/dal/src/component.rs, lib/dal/src/provider/external.rs, lib/dal/src/provider/internal.rs, lib/dal/src/schema.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/tests/integration_test/internal/mostly_everything_is_a_node_or_an_edge.rs, lib/dal/tests/integration_test/internal/mostly_everything_is_a_node_or_an_edge/connection.rs
- Add the ability to create inter-Component edges with the new engine
- These are called "connections"
- Extend AttributePrototypeArgument to hold side effect metadata for a given connection
- Add the ability to find the AttributeValue corresponding to a Component and an explicit InternalProvider
- Add an integration test to test the new functionality
=> Add the ability to create inter-component edges with the new engine (ENG-2202)

app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/store/feature_flags.store.ts
This may trigger unexpected behavior, but it's not something we want in the long run and it's probably not needed anymore.
The only missing piece to decide is, should we block running the same action on the same component if one is running? What if the action source code changed, or if the user changed a property in between?
But if 2 create actions for the same component run in parallel they may lose the resource from the first one to finish, since it will be overwritten.
=> Avoid blocking frontend when actions are running

lib/dal/src/workspace_snapshot/graph.rs, lib/rebaser-server/src/server/change_set_loop.rs
* Only prune & write out new workspace snapshot graph if there have been changes in rebaser
* Speed up garbage collection of un-referenced nodes in WorkspaceSnapshotGraph
We want to remove all of the "garbage" we've accumulated while operating on the graph.
Anything that is no longer reachable from the current `self.root_index` should be
removed as it is no longer referenced by anything in the current version of the graph.
Fortunately, we don't need to walk the graph to find out if something is reachable from
the root, since `has_path_connecting` is slow (depth-first search). Any node that does
*NOT* have any incoming edges (aside from the `self.root_index` node) is not reachable,
by definition. Finding the list of nodes with no incoming edges is very fast.
If we remove all nodes (that …
=> WorkspaceSnapshoGraph cleanup speedup

bin/veritech/scripts/stop.sh
We no longer use this script when stopping VMs, but we do use it when cleaning up all of the jails on veritech start. Just reverting this back to the previous incarnation.
=> fix: revert changes to stop script

lib/si-rabbitmq/src/environment.rs, lib/si-rabbitmq/src/error.rs
Fix RabbitMQ infinite hangs by using a timeout-and-retry technique. When RabbitMQ is booting up and a user tries to create an "Environment" using the streams port, there can be an infinite hang. That is an issue in its own right, but this change seeks to avoid it entirely.
On macOS aarch64 with an M1 Max, it appears that RabbitMQ needs about ~3-4 seconds for the streams feature to become available. It is unclear if other RabbitMQ services need the same amount of time.
=> Fix RabbitMQ infinite hangs when it isn't ready (ENG-2214)

bin/veritech/scripts/prepare_jailer.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
This adds some simple trace logs to deadpool execution steps so we can capture some basic metrics around how long we spend spinning up firecracker VMs vs just running tokio processes
=> feat: add trace logs for cyclone function execution

app/web/src/store/components.store.ts, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/paste_component.rs
uses same strategy that insert currently uses, which is very imperfect, but works ok until we rearchitect the realtime stuff to just push new components right away. This means
- on paste, we optimistically add show a loader at a certain position tracked under a temporary id
- when paste api request returns, we attach a new component id to the temporary loader (in this case we just use the first one if there are multiple components pasted)
- whenever we fetch the diagram, we look through any temporary loaders that are showing and if we find the new component id in the data fetched, we hide the loader
=> show loader until new components appear when pasting

app/web/src/components/ModelingDiagram/DiagramHelpModal.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue
if holding option when clicking and dragging, it will force drag-to-select (ie the blue box) mode. This will also have special behaviour which excludes the item that was clicked on and its parents. This allows you to drag to select within frames.
=> option + click/drag to select within frames

bin/veritech/src/args.rs, lib/cyclone-client/BUCK, lib/cyclone-client/Cargo.toml, lib/cyclone-client/src/client.rs, lib/cyclone-client/src/execution.rs, lib/cyclone-client/src/lib.rs, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/veritech-server/src/config.rs, prelude-si/rootfs/rootfs_build.sh
In some cases, we fail the initial connect to Firecracker, seemingly due to a race during VM startup. This adds retries to the connect method where we bail out attempting to read bytes if we get nothing back within 10 milliseconds (by default). We then create a new stream and try again. We'll do this up to 30 times before bailing out completely. 
This timeout can be configured via the `--cyclone_connect_timeout` in Veritech.
=> fix: add retry to firecracker connect

Cargo.lock, Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml, third-party/rust/fixups/proc-macro2-diagnostics/fixups.toml
This change bumps all Rust dependencies to use the ring 0.17.x release stream, leaving one version of ring to build, and benefits from the pin to ring 0.17.5 which the Buck2/Reindeer fixup supports.
References: jbg/tokio-postgres-rustls#17
=> build(deps): patch `tokio-postgres-rustls` to use ring 0.17

lib/deadpool-cyclone/src/lib.rs, prelude-si/rootfs/rootfs_build.sh
Ok, here me out. This reverts us back to the old behavior of never calling the `terminate()` methods and instead relying on cyclone exiting by itself. I figured out I can replicate this in Firecracker by simply following the cyclone call with `&& reboot`, which will kill the firecracker VM. This whole thing feels weird to me as we define terminate methods that are never used, but I think this method may be better as it's currently possible that we'll call terminate on a running VM because the healthcheck will return unhealthy if it's already (or currently) running one. I think this may be leading to some strange performance issues that are difficult to diagnose, but I'm not entirely sure.
@fnichol at some point I'd love to talk to you about this and how deadpool works. I'm not sure I …
=> feat: close the firecracker VM when cyclone exits

dev/Tiltfile
There was already 2 endpoint links provided automatically by Docker
Compose, but at least for this author, I kept clicking the "other" link
first which is the gRPC OpenTelemetry endpoint. Yeesh.
=> chore(tilt): add labelled link to Jaeger' UI for jaeger service

component/otelcol/BUCK, component/otelcol/Dockerfile, component/otelcol/docker-entrypoint.sh, component/otelcol/honeycomb-config.yaml
Adds a basic docker environment variable method of driving the configuration file to use for the otelcol docker image.
The environment variable changes are as below:
```
SI_OTEL_COL__CONFIG_PATH # Allows driving the specific config file in the build to use
SI_OTEL_COL__HONEYCOMB_API_KEY # Allows driving the API key for honeycomb
```
=> feat: add configuration option for otel + new honeycomb trace option

bin/cyclone/src/main.rs, bin/veritech/scripts/userdata.sh, dev/Tiltfile, lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh, prelude-si/rootfs/rootfs_build.sh
Adds a static route from cyclone into 10.0.0.3 which is then picked up via a NAT iptables route to push it into the otelcollector running on the veritech host on 4317.
This includes:
- Amendments to the rootfs for cyclone
- Adds docker to the veritech node
- Pulls & runs our otelcol container with the relevant honeycomb configuration
=> feat: added otelcol to cyclone within firecracker

lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh, prelude-si/rootfs/rootfs_build.sh
Amends the ip allocated from the context of the cyclone jail to permit communication into otel on the host network. `1.0.0.1` should never clash with any internal IPs.
=> fix: amend ip for otel within cylcone so it doesn't clash with any internal ips

bin/veritech/scripts/get_cyclone_logs.sh
Simple script for pulling Cyclone logs from a firecracker jail. This simply creates a temp dir, mounts the FS to it, and `less`es the log file if it is present. It cleans up after itself after it's done.
=> feat: convenience script for pulling logs from firecracker jails

lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh, prelude-si/rootfs/rootfs_build.sh
TLDR: Docker was being a pain
These were the existing rules in the iptables nat table regarding otel:
```
-A PREROUTING -d 1.0.0.1/32 -p tcp -m tcp --dport 4317 -j DNAT --to-destination 10.1.151.8:4317
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 4317 -j DNAT --to-destination 172.17.0.2:4317
```
The two iptables rules used are for different scenarios, but there is a potential conflict depending on the specific use case. In our case, they were conflicting causing irrational packet loss.
If there is a possibility that packets can match both rules, there might be a conflict. The conflict arises because both rules are trying to DNAT packets with the same destination port (4317) but to different destination addresses (10.1.151.8:4317 and 172.17.0.2:4317).
To avoid conflicts, make sure that the …
=> fix: docker + iptables conflicting rules amendment

lib/dal/src/attribute/value.rs, lib/dal/src/job/consumer.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/migrations/U2409__summary_qualifications.sql, lib/dal/src/qualification.rs, lib/dal/src/queries/summary_qualification/get_summary_qualifications.sql, lib/sdf-server/src/server/service/qualification/get_summary.rs
The get_summary endpoint was taking 30+ seconds to respond in production. This commit introduces the idea of 'summary tables', which get updated when the internal provider for the root prop is updated. We take the raw data, and then compute custom tables that cache the data, getting rid of the need to do the complex queries to get the information.
This is in a pretty raw state - if we decide that summary tables like this are a pattern we want more broadly, it'll certainly need some refactoring (like moving the summary table code into a single module, etc.)
=> feat: summary table for qualifications

lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh
For some reason on some launches this rule isn't required and is already set.
This ensures it is set for all veritech launches (it's required for the NAT traffic to leave for the firecracker VM's to reach the internet)
=> fix: add missing iptables rule for default network namespace forwarding

Cargo.lock, Cargo.toml, lib/council-server/src/client.rs, lib/council-server/src/server.rs, lib/dal/src/job/processor/nats_processor.rs, lib/dal/src/status.rs, lib/dal/src/tasks/status_receiver.rs, lib/dal/src/tasks/status_receiver/client.rs, lib/pinga-server/src/server.rs, lib/sdf-server/src/server/service/func/execute.rs, lib/sdf-server/src/server/service/ws/crdt.rs, lib/sdf-server/src/server/service/ws/crdt/y.rs, lib/sdf-server/src/server/service/ws/workspace_updates.rs, lib/si-data-nats/BUCK, lib/si-data-nats/Cargo.toml, lib/si-data-nats/examples/nats-publish/main.rs, lib/si-data-nats/src/connect_options.rs, lib/si-data-nats/src/lib.rs, lib/si-data-nats/src/service.rs, lib/si-data-nats/src/subscriber.rs, lib/veritech-client/src/lib.rs, lib/veritech-server/src/publisher.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change updates our coverage over the `async-nats` library, bringing it up-to-date with the 0.33.0. Importantly, it now exposes the [Services API] which will be used in future work.
[Services API]: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-32.md
=> feat(si-data-nats): update API surface coverage & add service API

app/web/src/components/ModelingDiagram/DiagramEdge.vue, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/store/components.store.ts, lib/dal/src/edge.rs, lib/vue-lib/src/design-system/icons/icon_set.ts
still wip but coming together
- show visual indicator of whether components are attached to their parent
- hovering that indicator highlights the parent frame(s)
- add "detach from parent(s)" to right click context menu and wire up (backend bug)
dragging components into frame behaviour still needs to be adjusted
- show indicator that an attachment is about to happen depending on mouse position
- determine attachment based on _mouse position_ rather than component bounds
- on attaching, we should bump components inside of frame bounds (or expand frame?) so we dont end up with components that are attached but outside the frame
BONUS
- small konva perf tweaks
- hover meta info moved to the store
- refactor hover handling - components now talk directly to the store rather than emitting events …
=> frame attach/detach improvements

component/nats/BUCK
This reverts commit b9f26c80506f7883297832888132493bd9f3b951.
I would like to better understand if there is a change in the connection details between these versions of NATS. Granted I made a massive jump and over 2 years of upstream releases :)
=> chore: revert "build(deps): upgrade to NATS 2.10.9"

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/components/ModelingDiagram/utils/math.ts, app/web/src/store/components.store.ts
probably needs some cleanup, but this is feeling pretty good!
- you can now drag items in/out of frames to attach/detach
- New parent is based on cursor position rather than what each component is hovering over
- we highlight the new parent so you can see what it will be attached to
- we optimistically update parent id so it feels snappy
- there is logic that bumps children into the new parent if they are outside, which means things sort of snap into the parent...
It's not perfect, but it feels pretty good!
Main issue is that when snapping things into place, you can still end up with items hovering over each other that are not actually attached.
=> feat(web) snap frame attach/detach with snapping

lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/diagram/connection.rs, lib/dal/src/diagram/node.rs, lib/dal/src/diagram/summary_diagram.rs, lib/dal/src/edge.rs, lib/dal/src/job/consumer.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/migrations/U2411__summary_diagram.sql, lib/dal/src/node.rs, lib/dal/src/provider/internal.rs, lib/dal/src/queries/attribute_value/is_for_internal_provider_of_root_prop.sql, lib/dal/src/queries/internal_provider/is_for_root_prop.sql, lib/dal/src/queries/summary_diagram/list_summary_diagram_components.sql, lib/dal/src/queries/summary_diagram/list_summary_diagram_edges.sql, lib/dal/src/queries/summary_qualification/get_summary_qualifications.sql, lib/dal/tests/integration_test/internal/diagram.rs, lib/dal/tests/integration_test/internal/provider.rs
Creating a summary table for get_diagram, in two parts - one for components, and one for edges. This one is a bit more complicated than the qualification summary table, as it has more spots where the data needs to be updated.
Add summary edges and collect parentNodeIds for components
Summary edges are now deleted and created automatically. The migration for summary diagram tables and functions has been incremented due to a conflict when rebasing with main. "ChildNodeIds" are now collected within the frontend and only "parentNodeId" is collected for summary components.
Correctly determine if the attribute value being processed in dependent values update corresponds to a root prop and a component. Fix integration tests broken by changing the diagram edges and nodes types.
=> feat: get_diagram is now a summary table

lib/deadpool-cyclone/src/instance.rs, lib/deadpool-cyclone/src/instance/cyclone/local_http.rs, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/deadpool-cyclone/src/lib.rs, lib/deadpool-cyclone/src/pool_noodle/pool_noodle.rs, lib/veritech-server/src/config.rs
* moves the PoolNoodle invocation to inside of local_uds instead of at the manager level to avoid repeating decision logic  specific to firecracker
* adds an `active` pool when we start an instance that keeps track of the start_time
* we now check if the pools are timed out and move them to the `to_be_cleaned` pool
* this check is pretty lazy and only happens if we don't have new jails to make or old jails to clean. Given that the timeout is 60 minutes, another few seconds should be fine
=> Add instance timeout to poolnoodle

app/web/src/store/component_attributes.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/component.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/ws_event.rs
This PR makes it so that we only re-load the properties and schema for impacted components. It adds a new WsEvent called "ComponentUpdated", which provides the component id and change set id. The component_attributes store then uses that event to trigger its update, rather than the raw ChangeSetUpdated event.
=> feat: only reload properties and schema for impacted components

app/web/src/store/change_sets.store.ts
Amends the wording to reflect "Change Set <number>" rather than "Demo <number>" as it's more appropriate as we move towards Production.
=> chore: amend wording in new change set dropdown

app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/store/components.store.ts, lib/dal/src/diagram/summary_diagram.rs
Fixes bug in which we were showing implicit frame edges
=> fix(web): calculate ancestry in frontend to ignore parentId stored for get_diagram

lib/dal/src/diagram/summary_diagram.rs, lib/dal/src/job/definition/dependent_values_update.rs
This commit fixes a bug where new components non-deterministically have a populated resource tree.
When rapidly creating components, sometimes "has_resource" is calculated prematurely for the underlying function execution. The "/resource" field is populated as a result. This was not seen before the summary tables work because "has_resource" was always calculated on fetch.
This commit contains one quality of life improvement and one core fix to combat the issue.
The QOL improvement is to _always_ set "has_resource" to false when a component is created. This works when importing components too via the import/export feature because pre-existing resources will be set using "set_resource", which indirectly calls the
"summary_diagram::component_update" call via dependent values update.
The core …
=> Fix new components sometimes having a populated resource tree (BUG-60)

lib/pinga-server/src/server.rs, lib/si-data-pg/src/lib.rs
Ensure pinga fails on startup if it cannot connect to PG. SDF works similarly by failing upon migrating. This does result in a duplicate test of the database connection. However, we want to retain both tests because the first one is used by "si-data-pg" to warm up the pool. This second one is used to block the listener loop from occuring.
=> Ensure pinga fails on startup if it cannot connect to PG (BUG-68)

lib/dal/src/diagram/summary_diagram.rs, lib/dal/src/migrations/U2412__summary_diagram_update_geometry_insert_row.sql
Fix components that existed on HEAD not having new positions (from a new change set) persist. This fix inserts the row into the summary table, like the "component_update" function, when setting geometry for a summary component.
=> Fix components from HEAD not having new positions persist (BUG-71)

lib/dal/src/migrations/U2412__summary_diagram_update_geometry_insert_row.sql
Fixes the issue where 'this_change_status' is seen as not existing as a column, because it's not set as a variable. We actually don't want to update the change status when you move the geometry anyway, so easy fix.
=> bug(geometry): this fixes the geometry upsert

app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/store/components.store.ts
we were running into issues sometimes when swapping change sets
This stuff gets pretty gnarly since we are keeping some state in sync between the URL, the store, and the tabs.
Unfortunately, there's not a good way out to make it much cleaner...
=> fix(web) url issues when switching change sets

Cargo.lock, lib/council-server/BUCK, lib/council-server/Cargo.toml, lib/council-server/src/client.rs, lib/council-server/src/client/management.rs, lib/council-server/src/lib.rs, lib/council-server/src/server.rs, lib/council-server/src/server/graph.rs, lib/council-server/src/subject_generator.rs, lib/dal/src/attribute/value.rs, lib/dal/src/job/consumer.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/pinga-server/src/lib.rs
This PR is a first pass at hardening council. It primarily encloses
council's core loop in an infallible wrapper as well as handles
situations where we have a missing dependency graph and need to restart
all running jobs. The restart broadcast is also published whenever
council boots up in case of a panic or restart.
Council:
- Upon startup, council will publish a message for all subscribers (all
running pinga instances) to restart actively running jobs
- The core loop for "bin/council" has been wrapped with an infallible
wrapper (within our control, the only way to escape the wrapper is via
a shutdown call or a closed connection)
- Bubbled up errors are logged in otel
- Explicit panics are now disallowed in "lib/council-server" with
additional clippy lints
- All "unwrap" usages have been …
=> Harden council and restart running jobs with a missing dep graph (ENG-2274)

lib/si-data-nats/src/lib.rs, lib/si-data-pg/src/lib.rs
This is a brutal hammer that disables some logic that tried to find the correct span for a transaction. It should make the spans a little weirder, but we think it will fix our performance problem.
=> bug: stop trying to find the span in our transaction libs

lib/dal/src/job/definition/fix.rs
Rather than processing fixes after the current batch is complete, let's process failures as they happen. When processing failures, we should log errors rather than bubbling them up.
For context, at the time of writing, "fixes" are the backend mechanism for "actions" performed in the frontend.
=> Fail fast on failed fixes (BUG-72)

Cargo.lock, Cargo.toml, lib/si-data-nats/src/lib.rs, lib/si-data-pg/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change incorporates an upstream fix in `tracing-opentelemetry` to prevent parent and "follows-from" span association from panicking under certain scenarios.
Additionally, the strategy to determine the appropriate span for PostgreSQL and NATS transactions/subscriptions has been updated slightly. The macros present prior to this change attempted to prevent another "Mutex poisoned" issue encountered a year ago. The updated `tx_span()` and `sub_span()` functions check to see if `Span::current()` is disabled, in which case a `Span::none()` is returned, otherwise the current Span is returned. The former macros were slightly less flexible in that they checked `target` and `level` span metadata--which happened to be correct in these two cases.
References: tokio-rs/tracing-opentelemetry#14 …
=> chore(si-data-pg,si-data-nats): compute appropriate Span for txns/subs

README.md
Scope the quickstart section to local development in the README. Replace the "configure providers" section with "configure docker" in the README as the secrets work has replaced the need to configure local providers, like "aws" for the "aws" CLI.
=> Scope quickstart to local development in the README (BUG-77)

app/web/src/store/components.store.ts, lib/dal/src/migrations/U2415__summary_diagram_update_fix_deadlock.sql
This fixes deadlocks relating to the calculation of child_node_ids by the backend. We remove the trigger that calcualtes them, and now the summary tables always return an empty array. The frontend then calculates the correct child node ids itself by manipulating the raw response.
CC: Victor!
=> bug(dal): fix some deadlocks

Cargo.lock, lib/dal/BUCK, lib/dal/Cargo.toml, lib/dal/src/context.rs, lib/dal/src/job/processor/nats_processor.rs, lib/dal/src/job/queue.rs, lib/telemetry-nats-rs/src/lib.rs, lib/telemetry-nats-rs/src/propagation.rs
This change marks the first transmission of OpenTelemetry trace metadata between 2 service components. In this case, from a `NatsProcessor` (in the DAL) to a Pinga job. Future work will connect more. Yay!
=> chore: inject otel ctx when dal submits jobs to pinga

bin/veritech/scripts/prepare_jailer.sh, bin/veritech/scripts/userdata.sh, prelude-si/rootfs/rootfs_build.sh
This adds a volume to the firecracker jails that is expected to include the cyclone decryption key. This volume must be present in the `/firecracker-data` directory when preparing the jail. The volume is teeny, one whole megabyte, so I thought it would be fine to just copy it around.
I also updated the userdata script to match what we have in the tools env plus having it pull the key from an aws secret, make the volume, and place it where it should go. 
I am removing the dev key from the rootfs entirely so this will break local development until I figure out how to add this to buck2. It's an easy fix, just create the volume with the dev key in it and put it where it goes.
=> feat: allow mounting cyclone decryption key into jails

bin/sdf/src/args.rs, bin/sdf/src/main.rs, lib/sdf-server/src/server/server.rs
This new flag operates like the former Cyclone key generation flags (i.e. `--generate-cyclone-secret-key-path` and
`--generate-cyclone-public-key-path`) in that it will generate a new key, write it to the file as requested and then terminate the program.
=> feat(sdf): add `--generate-symmetric-key-path` to SDF binary

prelude-si/rootfs/rootfs_build.sh
Cyclone is starting TOO FAST. It should start at a later runlevel and should wait for networking to be available.
=> fix: move cyclone start to default runlevel, add a dependency on net

bin/veritech/scripts/userdata.sh
Need to move this to after the dependency install. It works though. Promise.
=> fix: move decrypt key to after dependency install

bin/cyclone/src/main.rs, lib/cyclone-client/src/client.rs, lib/cyclone-server/src/lib.rs, lib/cyclone-server/src/server.rs
This change is pretty exciting (for me, hey I've been working with this code for a while now) as it delivers a `cyclone_server::Server` which has no external generic types while still supporting the various incoming streams internally.
The key insight was to create a `Runnable` trait which is implemented by an `InnerServer` which has all the trait-bound generics, but stored in a `Box` making an inner field of `inner: Box<dyn Runnable + Send>`.
=> chore(cyclone): refactor `Server` to not require generics externally

app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/component.rs, lib/sdf-server/src/server/service/diagram/create_node.rs, lib/sdf-server/src/server/service/diagram/paste_component.rs
This PR modifies the ComponentCreated event to pass along the changeset pk and component id, which is used by the front end to re-fetch the diagram when components are created
=> fix(dal,web,sdf) - fix up component created event firing and handling

Cargo.lock, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs
This change converts the `connect_component_sockets_to_frame_inner` function from an async/recursive strategy to an iterative strategy. Prior to this change, when working with a large workspace containing multiple levels of nested frames (like 5 and more), calls to this function would recurse enough times that it would exhaust the stack space and cause the program to panic and abort. The iterative approach guards against an *arbitrarily* deep set of nested frames.
=> fix(sdf): make connect_component_sockets_to_frame_inner iterative

Cargo.lock, lib/veritech-client/BUCK, lib/veritech-client/Cargo.toml, lib/veritech-client/src/lib.rs, lib/veritech-server/BUCK, lib/veritech-server/Cargo.toml, lib/veritech-server/src/config.rs, lib/veritech-server/src/publisher.rs, lib/veritech-server/src/server.rs
This change adds tracing context propagation between the Veritech client and server code (in `lib/veritech-client` and `lib/veritech-server` respectively). With this change, you can now track each incoming function request into the Veritech server and see the corresponding output and result messaging between client and server. Very cool!
=> feat(veritech): add service-spanning telemetry to/from Veritech

lib/dal/src/pkg/import.rs
Import should use new set_geometry method on nodes to ensure we update the diagram summary.
=> fix(dal): restore node position on import

component/nats/BUCK, component/nats/nats-server.conf
Confirmed we're good to upgrade--this also brings our development environments to closer parity with our production environment.
=> build(deps): upgrade to NATS 2.10.10

bin/council/src/args.rs, bin/council/src/main.rs, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, bin/module-index/src/args.rs, bin/module-index/src/main.rs, bin/pinga/src/args.rs, bin/pinga/src/main.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, bin/veritech/src/args.rs, bin/veritech/src/main.rs, dev/Tiltfile, lib/telemetry-application-rs/src/lib.rs
This change updates the telemetry setup and adds a couple of extra CLI arguments and environment variables to help control when it's appropriate for logging output to contain ANSI escape characters.
Each service has a new CLI argument of `--no-color` which will disable ANSI coloring of telemetry output when set. An associated environment variable of `SI_NO_COLOR` is also supported by setting the value to either `true` or `false`. Finally as a fallback of last resort, and to better support other operational ecosystems the `NO_COLOR` environment variable is also inspected and will disable coloring if this value is set to something non-empty.
In an attempt to make our services better behaved as Unix programs, they will now automatically disable ANSI coloring if the standard output of the …
=> chore: support opt-in ANSI coloring of telemetry logging output

bin/council/src/args.rs, bin/council/src/main.rs, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, bin/module-index/src/args.rs, bin/module-index/src/main.rs, bin/pinga/src/args.rs, bin/pinga/src/main.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, bin/veritech/src/args.rs, bin/veritech/src/main.rs, lib/telemetry-application-rs/src/lib.rs
This change ensures that the new color CLI flags are flags and *not* options. That means that passing `--no-color` sets the value to `true` rather than an option where `--no-color false` is valid (this was not intended behavior).
In an effort to determine whether a CLI flag was set the telemetry config was also updated so that the right config precedence is in effect.
=> fix: treat `--no-color`/`--force-color` as CLI flags

Cargo.lock, Cargo.toml, bin/council/src/args.rs, bin/council/src/main.rs, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, bin/module-index/src/args.rs, bin/module-index/src/main.rs, bin/pinga/src/args.rs, bin/pinga/src/main.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, bin/veritech/src/args.rs, bin/veritech/src/main.rs, lib/telemetry-application-rs/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change adds a new `--log-json` flag to all services which will configure the telemetry to output logging as JSON objects, one per line. An associated environment variable of `SI_LOG_JSON` is also supported to enable this output mode.
=> feat: support telemetry logging option as JSON lines

bin/council/src/args.rs, bin/council/src/main.rs, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, bin/module-index/src/args.rs, bin/module-index/src/main.rs, bin/pinga/src/args.rs, bin/pinga/src/main.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, bin/veritech/src/args.rs, bin/veritech/src/main.rs, lib/telemetry-application-rs/src/lib.rs, lib/telemetry-rs/src/lib.rs
This change updates the tracing from 5 prescribed levels to 7. This means that before there were a max of 4 `-v` levels and now there are 6.
Additionally, the `TelemetryConfig` has 2 new values that influence the tracing levels in addition to `app_modules`:
- `interesting_modules`: a `Vec` of Rust crate/module names that are not strictly the server's library code but rather "crates of interest" the application. For example, we care about `si-data-nats` when looking at the Veritech server as it's driven primarily via NATS. The default is an empty collection of modules.
- `never_modules`: a `Vec` of Rust crate/module names that will never be logged/transmitted/considered when setting levels. In other words, these modules are always set to `NAME=off` at any verbosity level. After operating …
=> chore: revisit telemetry tracing levels to make debugging easier

bin/council/src/main.rs, bin/cyclone/src/main.rs, bin/module-index/src/main.rs, bin/pinga/src/main.rs, bin/sdf/src/main.rs, bin/veritech/src/main.rs, lib/telemetry-application-rs/src/lib.rs, lib/telemetry-rs/src/lib.rs
This change adds several `*_and_wait()` method options to the `ApplicationTelemetryClient` type. When our services boot up we check the parsed CLI argument for verbosity flags. If there are more than one set then we issue a command to raise the tracing level but prior to this change, this operation was non-blocking/async. That means that the level may not have raised by the time the next line of code executes resulting in potential missing log messages.
=> chore: add optional API to make tracing level changes "wait-able"

bin/veritech/scripts/prepare_jailer.sh, bin/veritech/scripts/stop.sh, lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs, lib/deadpool-cyclone/src/pool_noodle/pool_noodle.rs
In some cases, jails were failing to clean and we were swallowing the error, meaning the jail would still be marked as clean. This would cause subsequent function calls using that jail to fail.
* Change `stop.sh` to only swap out the rootfs to remove some points of failure
* It also checks for the existence of things before trying to kill/remove and will retry if things fail
* Ensure that all jails are actually cleaned on Veritech startup
* Capture script errors and log them appropriately. In every case I've seen, a failure is due to a device not unmounting in a timely fashion. Therefore, if we fail we push that jail back onto the to-be-cleaned stack, but to the front  so we don't immediately try to clean it again. This is kind of weak, but I've not seen a jail fail to clean twice in a …
=> fix: jail clean flakiness

bin/rebaser/BUCK, lib/pinga-server/src/config.rs, lib/rebaser-server/src/config.rs, lib/sdf-server/src/server/config.rs
Now that the content store (Pg) has been moved to the ServicesContext, it must also use the TLS config that the regular "PgPoolConfig" uses.
=> Ensure content store works with TLS config (ENG-2315)

lib/cyclone-server/src/server.rs, lib/sdf-server/src/server/server.rs, lib/telemetry-http-rs/src/make_span.rs
This change adds a general capability to "filter" HTTP requests by their URI path and change the tracing level of the request span away from its default.
In our SDF and Cyclone server setups, we're creating an HTTP request span at the `INFO` level by default, and this change alters any request in SDF at `/api/` to create an HTTP request span at the `TRACE` level, effectively disabling these spans in all but the most intense debugging scenarios.
=> feat(telemetry): add path-filterable support into HTTP request spans

lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/diagram.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/internal/new_engine.rs, lib/dal/tests/integration_test/internal/new_engine/frame.rs, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/connect_component_to_frame_new_engine.rs, lib/sdf-server/src/server/service/diagram/create_component.rs
This is the first pass at adding frames to the new engine. This PR is primarily focused on restoring the ability to place a new component or an existing component onto an existing frame in the frontend.
Relevant changes:
- Restore ability to place a new component into a frame in the frontend
- Add `EdgeWeightKind::FrameContains` to replace symbolic edge functionality seen on main
- Add ability for Components to determine their parent
- Add integration test for converting a component into a frame and
attaching a component to that frame
This commit does not guarantee that nested frames, aggregation frames, and "up" frames will work. It is only concerned with components within "down" frames (without nesting).
This is an example of what happens when you place a new component onto an existing …
=> Add ability to attach components to frames in the new engine (ENG-2316)

bin/cyclone/src/main.rs
This change helps to support Cyclone server spans being emitted by default in development and production. Long prior to this change, the output from a Cyclone instance was so chatty that we dialed down the default log level but this has since been remedied. To further muddy the waters, the Tilt configuration has been running with `SI_LOG=debug` for the Veritech service meaning that all Cyclone server instances were also being hard-coded into running a `DEBUG` level. This development setting should eventually be removed as it widens the gap between development and production and should be increasingly less desirable under normal circumstances.
=> chore(cyclone): revert cyclone's default tracing level to `INFO`

lib/telemetry-http-rs/BUCK, lib/telemetry-http-rs/Cargo.toml, lib/telemetry-http-rs/src/make_span.rs
Yay! There is an extension on the Axum request type that returns the router matching string. This means that if the request path in the Axum router was `/api/summary/:workspace_id`, then a related request span name would now be `GET /api/summary/:workspace_id`.
With this implementation detail sorted we can now include the request path without matched ids and other path variables in the span name. This keeps the number of span names lower (in OpenTelemetry jargon "low cardinality") and thus helps to increase the power of querying later on.
=> feat(telemetry-http): add "matched" path to HTTP span names

lib/dal/src/component.rs, lib/dal/src/diagram/summary_diagram.rs, lib/dal/src/migrations/U2419__safe_restore_component.sql
This makes restore component safer.
Also updates component restore to hard delete the changeset version of summary components, instead of updating them. This was probably the cause of some ghost components too.
=> fix(sdf): don't hard delete stuff on HEAD

lib/dal/src/builtins.rs, lib/dal/src/diagram.rs, lib/dal/src/provider/external.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/internal/new_engine/frame.rs
Remove unused frame sockets (external provider and explicit internal provider) when creating schema variants. Add an extended test with not only multiple frames, but also a connection from a frame to an unattached component.
Misc change: now we import AWS EC2 PKG and AWS PKG for integration tests (again).
The test runs through a few non-trivial scenarios when working with multiple, non-nested frames. They are include, but are not limited to, the following:
- Ensure multiple frames with multiple connections work
- Ensure connections within frames work
- Example: two components are placed within a frame. They have an edge between one another for a given set of sockets.
- Ensure edges from frame sockets to unattached components work
- Example: create an AWS Region and create a AWS AMI …
=> Remove unused frame sockets and add multiple frames test (ENG-2325,ENG-2327)

bin/module-index/src/args.rs
We can't load a path from a SensitiveString so needed to change the path back to a string
=> Fix Module Index Server Startup

Cargo.lock, Cargo.toml, app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetEditor.vue, app/web/src/store/asset.store.ts, app/web/src/store/feature_flags.store.ts, lib/dal/src/func.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant/definition.rs, lib/dal/tests/integration_test/internal/func.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/clone_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs, lib/sdf-server/tests/service_tests/scenario.rs, lib/si-pkg/BUCK, lib/si-pkg/Cargo.toml, lib/si-pkg/src/spec/attr_func_input.rs, lib/si-pkg/src/spec/prop.rs, lib/si-pkg/src/spec/socket.rs, lib/si-pkg/src/spec/variant.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Instead of deleting the old schema variant and creating a new one, then attempting to migrate components, we just create a new schema variant on exec_variant_def and mark it as the default variant. Existing components are unchanged.
Component upgrades are coming next.
This is controlled by the "multiVariantEditing" flag, which is not yet in posthog (but can be easily turned on in the feature flags store).
=> feat(si-pkg,dal,sdf-server): multi variant editing

lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
Some logic errors in recent changes to the import code cause us to export "intrinsic" funcs with different unique ids. Intrinsics should be considered immutable, and should only exist on head. This fixes one part of the problem by ensuring we only ever export the intrinsic as defined in the IntrinsicFuncs module.
=> fix(si-pkg): ensure we always export invariant intrinsics

.github/workflows/e2e-validation.yml, app/web/.env, app/web/cypress.config.ts, app/web/cypress/e2e/4-value-propogation/value-attribute-propogation.cy.ts, app/web/cypress/support/auth-provider-commands/auth0.ts
**Adds a new E2E Synthetic which:**
- Logs in as synthetic user
- Goes to production workspace for Synthetics
- Changes value on Attribute of Component A on a new changeset
- Validates that that property which is changes on A is propogated to Component B
- Deletes the new changeset
This uses a workspace which already has the components and "Lego" module installed within it + you're able to run and validate this flow locally by simply changing the variables.
----
Variables for env
```
```
These may drift or change over time.
----
**Maintenance**
All of the Component IDs/Workflow IDs/URLs/Credentials for the production synthetic can be changed inside github actions without having to make a PR to the repo/main. These are injected into .env.local within the pipeline from these vars:
```
- …
```
=> feat/add e2e synthetic workflow for Production

app/web/cypress.config.ts
Compatibility with local runs `must` be retained but without this it isn't passing in CI (even if without it it passes locally against remote) 
Temporarily hardcoding this to give us stability coverage over the weekend + will amend properly config-wise next week when we are up and running.
=> fix: hardcode the baseurl as it isn't working in CI

lib/rebaser-server/src/server/core_loop.rs, lib/si-data-nats/src/jetstream/context.rs
This PR is a follow-up to #3300 and that ensures the new engine uses the "work queue" retention policy when using NATS Jetstream. As part of this change, we now make rebases non-blocking by spawning them off into separate tasks. This is unlikely to be the long term shape, but it's a step closer in the right direction.
=> Make rebases non-blocking and use work queue retention policy (ENG-2334)

lib/dal/src/attribute/context.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/component/migrate.rs, lib/dal/src/migrations/U2422__respin_component.sql, lib/dal/src/pkg/export.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/migrate_to_default_variant.rs, lib/si-pkg/src/spec/variant.rs
Adds the ability to take a component based on one schema variant and
migrate it to another schema variant without component deletion. Adds an
sdf route that facilitates this.
Frontend code not commited, resources have not been tested, and one
important feature is missing from this: the deletion and restoration of
edges to the new providers if they are compatible. But otherwise this
reliably "respins" a component onto a new variant.
=> feat(dal,sdf): upgrade components to new schema variants

.ci/docker-compose.test-integration.yml
This change configures the OpenTelemetry collector endpoint for any Cyclone servers running as part of an integration test. Prior to this change (and given past work), Cyclone servers try in vain to connect to a localhost collector only to fail. This causes a *lot* of stderr output in the CI logs, even though this is not a failure at all.
=> chore(ci): set OpenTelemetry environment varible in integration tests

bin/si-generator/src/render.ts, bin/si-generator/src/resource_generator.ts, bin/si-generator/src/run.ts, bin/si-generator/src/templates/assetMain.ts, bin/si-generator/src/templates/codeGenMain.ts, bin/si-generator/src/templates/createMain.ts, bin/si-generator/src/templates/refreshMain.ts
The generator can now produce codeGen and createFuncs.
In theory, there should only need to be 1 codeGen func created, and it should just be re-used across every asset. It should be named 'si:genericAwsCreate', which will then be re-used in the create functions.
=> feat(si-generator): add codegen and create funcs

bin/si-generator/src/render.ts, bin/si-generator/src/resource_generator.ts, bin/si-generator/src/run.ts, bin/si-generator/src/templates/actionMain.ts, bin/si-generator/src/templates/deleteMain.ts
Adds a 'delete' and 'action' generator.
Like the refresh generator, they essentially construct the arugments for the cli skeleton from 'input' arguments that specify the AWS Input path on the left, and the property to set it from on the right. Then it calls the API and checks the exit code. 
Delete should work for any AWS API - actions should work for anything except tagging, which is just fraught with peril.
=> Add delete and action generators

app/web/src/store/components.store.ts, lib/dal/src/component.rs, lib/dal/src/component/migrate.rs, lib/dal/src/diagram/summary_diagram.rs
When a component is upgraded to a different schema variant, we need to recreate all the edges (if possible). This attempts to do that, and also updates the component diagram summary row to have the new sockets.
=> feat(dal): restore edges on component upgrade

docs/RUNNING_RUST_TESTS.md, lib/dal-test/src/lib.rs, lib/dal/tests/integration_test/external/aws_region.rs, lib/dal/tests/integration_test/external/coreos_butane.rs, lib/dal/tests/integration_test/external/docker_image_intelligence.rs, lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_mocked_whiskers.rs
6 external tests disabled that basically tested the assets
We should test those assets, but the cypress baked in the package feels a better way.
Now the tests take 5 minutes instead of 20.
=>  Stop migrating most builtins for tests 

lib/dal/src/component/migrate.rs, lib/dal/src/func.rs, lib/dal/src/pkg/import.rs
Ensures we emit the resource correctly when migrating a component to a new schema variant. Also ensures we import func arguments when cloning functions for the new variant.
=> feat(dal,sdf): migrated components preserve resource

lib/dal/src/queries/defs_for_default_variants.sql, lib/dal/src/schema/variant/definition.rs, lib/sdf-server/src/server/service/variant_definition/list_variant_defs.rs
Ensure we only list one definition per schema in the asset editing panel by restricting to default schema variant ids (or NULL, for variant defs that have not yet been executed)
=> fix(sdf): only list schema variant definitions for default variants

app/web/cypress/e2e/modelling-functionality/create-component.cy.ts, app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts
Cypress tests have been failing in Production as overnight the create_node api calls degraded to over 4000ms. This allows our cypress tests to go green again to then allow us to debug further whilst maintaining coverage.
Validaed the timeout fix locally against Production
=> fix: increase timeout permitted to create_node as we know it's slow atm

.github/workflows/e2e-validation.yml
Save the cypress recordings for easy access/allowing you to see what didn't work during any run without having to re-run it to try and understand what went wrong.
**Example here**
https://github.com/systeminit/si/actions/runs/8005441473
See Artifacts: Produced during runtime
=> feat: save recordings to github artifacts

lib/dal/src/diagram.rs, lib/dal/src/lib.rs, lib/dal/src/node_menu.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/content_address.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs, lib/sdf-server/src/server/service/func/create_func.rs, lib/sdf-server/src/server/service/func/save_func.rs, lib/sdf-server/src/server/service/schema/create_schema.rs, lib/sdf-server/src/server/service/secret.rs, lib/sdf-server/src/server/service/secret/create_secret.rs
This PR converts the ephemeral `Secret` object to a graph node. It remains purely referential to the underlying `encrypted_secrets` table, but now persists to the workspace under a new "Secrets" category node.
This PR also restores the `create_secret` and `get_public_key` routes. Finally, it contains some lint fixes.
=> Convert ephemeral Secret object to graph node in the new engine

lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/async_route.rs, lib/sdf-server/src/server/service/diagram/paste_component.rs, lib/sdf-server/src/server/service/pkg/export_workspace.rs, lib/sdf-server/src/server/service/pkg/install_pkg.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs, lib/si-data-nats/src/lib.rs
Committing in the error handler for async tasks means we are not rolling our transactions back when a fatal error occurs. In the case of workspace import, this is catastrophic, since we begin import by clearing out the workspace entirely. A failed workspace import then leaves the user with an empty workspace, destroying any data they currently had.
Adds the ability to publish a WsEvent immediately, without requiring the commit to drain the pending event queue.
Adds a standardized error handler function `handle_error` which publishes the error event immediately and produces error telemetry.
The telemetry message for a failed async task looks like this now:
```
2024-02-22T17:18:10.901152Z ERROR ThreadId(47) sdf_server::server::service::async_route: async route '/api/pkg/install_pkg' error: …
```
=> fix(sdf): async routes should not commit on error by default

lib/dal-test/src/helpers.rs, lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/visibility.rs, lib/dal/src/workspace.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/update_property_editor_value.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/create_func.rs, lib/sdf-server/src/server/service/func/save_func.rs, lib/sdf-server/src/server/service/secret/create_secret.rs
This PR restores the "force new" functionality for change sets in the new engine. It uses the same interface through the existing `ChangeSet` struct, but goes through the new `ChangeSetPointer` interface under the hood.
As a result of this change, existing logic attempting to coerce change set pointer data into visibility has been unified to one method.
The `ChangeSetPointer` struct will eventually replace the existing `ChangeSet` struct. After or during replacement, it will likely be renamed to `ChangeSet`. Both will likely happen once the existing `ChangeSet` struct is no longer used and the new engine reaches near feature parity with `main`.
=> Restore "force new" for change sets in the new engine

component/deploy/docker-compose.yaml
The vector container should use Debian so it can run journalctl for the host's systemd logs.
=> fix: use debian for vector

.ci/docker-compose.test-integration.yml, dev/Tiltfile, dev/docker-compose.platform.yml, lib/dal-test/src/lib.rs
This change adds another running Postgres service in our Tilt/dev environment which is used exclusively by the DAL/SDF integration tests. This database is configured with `fsync=off` and greatly speeds up the database copy-from-template activity that happens in the integration test setup.
Reference: https://www.postgresql.org/message-id/CA%2BhUKGJwuVCJ7JYWchv1kFzRZO57_WChgsrzLmM9PeZTfo_bEQ%40mail.gmail.com
=> chore: use a dedicated postgres db for testing using `fsync=off`

lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh
The new AMI is using Amazon Linux 2023. Our setup script must include that distro in order to start Veritech.
=> fix: firecracker-setup must include Amazon Linux 2023

README_NEW_ENGINE.md, lib/dal-test/src/lib.rs, lib/dal-test/src/test_harness.rs, lib/dal/src/lib.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret.rs, lib/dal/tests/integration_test/internal/mod.rs, lib/dal/tests/integration_test/internal/secret.rs, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service/secret.rs, lib/sdf-server/src/server/service/secret/list_secrets.rs, lib/sdf-server/src/server/service/secret/update_secret.rs
This PR restores the ability to update and list secrets. Updating secrets remains the same, but now the referential secrets on the snapshot are updated. Listing secrets uses the same interfaces, but now the graph is purely used and mimics the original logic (this first pass is likely unoptimized as a result).
This is also the first time integration tests have been restored that aren't part of the `new_engine` module! The secrets tests return. We needed to expose `WorkspaceSignup` from the `dal-test` crate as a result, since `WorkspaceSignup` is still in the `dal` on main. The `test_harness` module has been partially restored as well.
We need to figure out the long term shape and relationship between referential secrets and encrypted secrets. The `update_secrets` route contains side effect …
=> Restore ability to update and list secrets in the new engine

app/web/src/store/asset.store.ts, app/web/src/store/feature_flags.store.ts, app/web/src/store/module.store.ts, app/web/src/store/workspaces.store.ts, lib/dal/examples/dal-pkg-import/main.rs, lib/dal/src/builtins/func.rs, lib/dal/src/builtins/schema.rs, lib/dal/src/builtins/schema/test_exclusive_schema_fallout.rs, lib/dal/src/builtins/schema/test_exclusive_schema_starfield.rs, lib/dal/src/pkg/import.rs, lib/dal/tests/integration_test/internal/pkg.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/service/pkg/install_pkg.rs, lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs, lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs, lib/sdf-server/tests/service_tests/scenario.rs
This behavior will be replaced by the ability to migrate a component to the latest schema variant.
=> fix(dal,web,sdf): remove the `override_schema` flag

lib/content-store/src/pair.rs, lib/content-store/src/store/pg.rs, lib/dal/src/workspace_snapshot.rs
Fix content pair creation races by only writing out and not returning anything. We do not use long-running transactions with the content store, and since there may be many users of the content store, we should not be picky when writing out. Simply write out, do nothing if the pair already exists, and move on.
=> Fix content pair creation races by only writing out

.github/workflows/e2e-validation.yml, app/web/.env, app/web/cypress.config.ts, app/web/cypress/e2e/authentication/login.cy.ts, app/web/cypress/e2e/authentication/logout.cy.ts, app/web/cypress/e2e/modelling-functionality/create-component.cy.ts, app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts, app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts, app/web/cypress/e2e/module-index/check-modules.cy.ts, app/web/cypress/e2e/web-functionality/get-summary.cy.ts, app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts, app/web/cypress/global.d.ts, app/web/cypress/support/commands.ts, app/web/cypress/support/posthog-commands/posthog.ts
Adds the possibility of driving cypress for test magnitude using `VITE_SI_CYPRESS_MULTIPLIER` to multiply the amount of times the tests are executed on each run to simulate user load. Additionally modified the CI build to be a matrix (of 1) so we can easily multiply on that vector too to give larger scale if needed. i.e.
CI Executor Multiples x VITE_SI_CYPRESS_MULTIPLIER x Test Number = Load
I also added a Posthog command to push a custom UUID into Posthog for each test to allow us to easily look at the user session for each event. This should be super helpful when we get more complicated tests or fragile tests to figure out what is wrong.
=> feat: run workflow with option for multiple executions, improve cypress execution logic

component/init/configs/config.yaml
Incorrect env var for the honeycomb api key means we weren't exporting traces. Whoops.
=> fix: incorrect env var in otelcol config

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs
When ordinal edges were added to the system as part of the dependent values update work, three unit tests regressed. This PR returns optional ordinal edge information from `add_ordered_edge` without performing any additional fetch logic. The three tests then use that information to assemble the missing edge.
=> Fix graph unit tests lacking ordinal edges

lib/dal/src/property_editor/values_summary.rs
This query is hanging and blocking work, disabling it while I work on an alternative approach
=> hotfix(dal): disable attribute override query temporarily

component/deploy/docker-compose.yaml, component/init/configs/vector.yaml
Vector needs to mount the journal on the host so it can ship systemd logs.
=> fix: vector needs to mount the journal in order to ship systemd logs

lib/dal/src/property_editor/values_summary.rs
Replaces controlling func info, socket info with fake data to avoid expensive queries until we can make them more efficient
=> hotfix(dal): remove most property editor metadata

lib/rebaser-server/src/server/core_loop.rs
We ack with progress when pulling a message off of the stream in the rebaser. However, we do not finishing acking the message once done. This probably needs a further look for the long term, but this will stop the bleeding in the interim.
Congrats to @vbustamante for finding this bug on the first day of working in the new engine :tada:
=> Ack messages when done rebasing in the new engine

.github/workflows/e2e-validation.yml
Moves it to every 5 minutes + retries on failure 3 times before accepting failure + finishing.
Also adds a basic Slack webhook back into #_alerts when failure occurs
=> feat(cypress): increase frequency and add retry

bin/veritech/scripts/prepare_jailer.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
UID was still too big and the jailer was not selecting the correct UID, so runs were failing.
=> fix: need both uids to match

lib/dal/src/migrations/U2614__correct_deleted_components_on_summary.sql
Due to issues with delete failing to update summaries correctly, we have some components stranded on a graph (zombies). This migration will clean up the zombie components by updating the summary tables to match the components tables.
=> fix(dal): Migrate deleted component summary data

lib/dal/src/builtins/func.rs, lib/dal/src/builtins/schema.rs, lib/dal/src/builtins/schema/test_exclusive_schema_bethesda_secret.rs, lib/dal/src/builtins/schema/test_exclusive_schema_fallout.rs, lib/dal/src/builtins/schema/test_exclusive_schema_starfield.rs, lib/dal/src/pkg/import.rs, lib/dal/src/property_editor/values.rs, lib/dal/tests/integration_test/internal/new_engine/before_funcs.rs, lib/dal/tests/integration_test/internal/new_engine/component.rs, lib/sdf-server/src/server/server.rs
This commit removes the override schema builtin feature flag. It also centralizes accessor patterns for property editor values.
=> Remove override flag and centralized property editor values accessors

lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs
In order to support the small graph and access to node and edge weights
through the caching layer, we cannot use the petgraph `node_weight` or
`edge_weight` methods directly in most cases. Instead we need to access
the weights through a method that will look them up in the caching layer
(or fetch it from the content store). This removes all direct calls to
the petgraph `node_weight` and `edge_weight` methods, replacing them
with calls to `get_node_weight` and `get_node_weight_opt`. These methods
are sync right now but will become async. Some other accesses remain
(calls to `edges_directed`, `node_weights()` and calls to
`node_weight_mut`, etc.) that also have to be made indirect.
=> feat(dal): remove direct node/edge weight accesses

README.md, docs/ARCHITECTURE.md, docs/DEVELOPMENT_ENVIRONMENT.md, docs/EDITORS_AND_IDES.md, docs/TROUBLESHOOTING.md
This PR adds a node modules troubleshooting section to the `docs/` directory within a new troubleshooting doc. The new troubleshooting doc centralizes other troubleshooting-related tasks from other docs.
- Add a new troubleshooting section related to NATS Jetstream not being enabled
- Refactor architecture diagram to include the rebaser and modernize descriptions
- Drop unnecessary parts of the architecture diagram (e.g. external services and naive depictions of the function execution flow)
- Remove irrelevant or outdated docs sections
- Fix a grammatical issue in the root README
=> Add node modules troubleshooting and centralize troubleshooting docs

bin/rebaser/src/args.rs, bin/rebaser/src/main.rs
Mimic sdf and pinga behavior by adding color to rebaser telemetry config and closing the tracker. We also add args the mimic the pinga args of the same name.
=> Add color to rebaser telemetry and close tracker (ENG-2381)

.cargo/config.toml, lib/dal/src/job/definition/dependent_values_update.rs
This change tracks an alternate "task ID" (in this case a random `Ulid`) which is used in the same `task_id_to_av_id` hash map logic, thus removing the need for the unstable task `Id` type. In this way it's a little easier to setup a development environment with editors that use `cargo clippy` and `rust-analyzer` underneath.
=> chore(dal): use alternative to JoinSet Id to drop unstable requirement

.ci/docker-compose.test-integration.yml, dev/docker-compose.platform.yml
The PG [docs for the fsync option][1] mention that you should consider turning off `full_page_writes` if you're disabling `fsync`. This doesn't make anywhere near as much of a difference as disabling `fsync` does, but should help some in more I/O bound environments when running tests.
[1]: https://www.postgresql.org/docs/16/runtime-config-wal.html#GUC-FSYNC
This is just a re-run of #3342 to test that it triggers the entire test suite
=> Disable PG full page writes in test DB instances

Cargo.lock, lib/si-data-nats/src/lib.rs, lib/si-layer-cache/BUCK, lib/si-layer-cache/Cargo.toml, lib/si-layer-cache/src/chunking_nats.rs, lib/si-layer-cache/src/error.rs, lib/si-layer-cache/src/lib.rs, lib/si-layer-cache/tests/integration.rs, lib/si-layer-cache/tests/integration_test/chunking_nats.rs, lib/si-layer-cache/tests/integration_test/mod.rs
This change adds a new `ChunkingNats` wrapping type around an underlying
NATS Jetstream messages `futures::Stream`. The publish side takes an
arbitrarily sized `payload` of `Bytes` and internally may send multiple
NATS Jetstream messages with the payload segemented into chunks.
On the receiving side, there is a `futures::Stream` implementation which
will reassemble the chunks into single messages. Any messages that are
not marking with chunking header metadata will pass through this stream
unmodified.
Testing and integration work remains but the basics of the behavior are
there!
Co-authored-by: Adam Jacob <adam@systeminit.com>
Signed-off-by: Fletcher Nichol <fletcher@systeminit.com>
=> feat(si-layer-cache): impl NATS chunking messaging

lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/definition.rs, lib/dal/tests/integration_test/schema/variant.rs, lib/dal/tests/integration_test/schema/variant/view.rs, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/variant_definition.rs, lib/sdf-server/src/server/service/variant_definition/list_variant_defs.rs
There are a number of things to node here:
1. We have no current way of understanding what the default variant is for a schema variant - so this assumes the first
2. We don't have a SchemaVariantDefinitionId so we are using the schema variant id for now
3. The only different between a schema variant and a schema variant definition is the missing input / output sockets so we may have an easier way to get that data rather than a separate route
4. It adds a basic test to ensure that the number of schemas == number of schema variant definitons
This is going to need more work later when we start to add defaults for schema_variants
=> feat(dal, sdf-server): Restore list_variant_defs SDF Route

lib/dal/src/socket/connection_annotation.rs, lib/ts-lib/src/connection-annotations.ts
Fixed connection annotations so that it converts to lowercase on both the server and the front end before selecting which edges can connect. Also added appropriate unit test to cover this case.
=> Fixed edge connections in backend and frontend

.ci/docker-compose.test-integration.yml, component/nats/BUCK, component/nats/nats-server.conf, dev/docker-compose.platform.yml, flake.nix
This change adds 2 new tools to our development environment (a NATS CLI `nats` and a top-like program `nats-top`), drops some of the default overly-verbose logging, and bumps the version of the NATS server.
=> chore: refresh NATS support

lib/si-events-rs/src/actor.rs, lib/si-events-rs/src/tenancy.rs, lib/si-layer-cache/src/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs
Generating the key before sending the data to the `write` method means serializing twice, since we'll need to get the postcard bytes to serialize the data (and then serialize the data in the write method). Write should handle this. For non content-address keys we will need a different interface.
Also adds some extensions to some types in `si-events` to ease conversion from dal types.
=> fix(si-layer-cache): write generates the keys from the hash of the value

lib/dal-test/src/lib.rs, lib/dal-test/src/schemas/mod.rs, lib/dal-test/src/schemas/test_exclusive_schema_katy_perry.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/get_code.rs, lib/dal/tests/integration_test/component/set_type.rs
This introduces a new test schema - Katy Perry - it's all codegen funcs and no actions :D
=> chore(dal): Ensure that all different get_code Language types are covered

app/web/src/store/components.store.ts
Rust is: `{id, created_by:None, deleted_by: None}`
TS was:
```
connection: {
id: string;
classification: "configuration";
destination: { nodeId: string; socketId: string };
source: { nodeId: string; socketId: string };
};
forceChangesetPk?: string;
```
=> ENG-2403 TS was out of alignment with the rust typedef, now matching

component/postgres/multiple-database-support.sh, dev/docker-compose.platform.yml
This prevents downstream services to postgres starting before the databases in postgres are available
Validated locally. Needs the clients to pull the newest image for postgres to consume the change.
=> fix: add healthcheck to postgres + only report healthy when database are available

Cargo.lock, lib/si-layer-cache/BUCK, lib/si-layer-cache/Cargo.toml, lib/si-layer-cache/src/db/cas.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/pg.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
This can be used to get many values from the cache at once. Values that fall through to database queries will be batched into a single query.<img src="https://media3.giphy.com/media/G4AdhRHsJK1ZbSCRRB/giphy.gif"/>
=> feat(layer-cache): add get_bulk method to layer-cache

lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/pg.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
Now that the values in pg are strings this is much more straightforward to implement.
=> feat(layer-cache): get_many returns to the PgLayer

Cargo.lock, lib/dal-test/src/helpers.rs, lib/dal/src/change_set_pointer.rs, lib/dal/src/context.rs, lib/dal/src/migrations/U3001__change_set_pointers.sql, lib/dal/src/queries/workspace_snapshot/find_for_change_set.sql, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/rebaser.rs, lib/rebaser-client/BUCK, lib/rebaser-client/Cargo.toml, lib/rebaser-client/src/lib.rs, lib/rebaser-core/BUCK, lib/rebaser-core/Cargo.toml, lib/rebaser-core/src/lib.rs, lib/rebaser-server/src/server/rebase.rs, lib/si-events-rs/src/lib.rs, lib/si-events-rs/src/workspace_snapshot_address.rs, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/db/cache_updates.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/src/event.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/migrations/U0002__workspace_snapshots.sql, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/mod.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
Moves storage and fetch of the workspace snapshot into its own layer cache and database (WorkspaceSnapshotDb). This enables us to use an Arc without extra copying when performing read-only graph operations.
Some changes were required to the blocking_commit and commit internals to ensure we perform a rebase even if no transaction has been opened in the Dal Postgres transactions state.
=> feat(*): move workspace snapshots into layerdb

Cargo.lock, Cargo.toml, lib/telemetry-application-rs/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
https://github.com/tokio-rs/tracing-opentelemetry/pull/86 fixes some Mutex poisoining issues we're seeing (only in our test harness). Upgrading the various opentelemetry crates so we no longer have to deal with this panic.
=> fix(*): upgrade opentelemetry crates

app/web/src/components/Workspace/WorkspaceViz.vue, app/web/src/components/Workspace/WorkspaceVizSchemaVariant.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, app/web/src/store/feature_flags.store.ts, app/web/src/store/viz.store.ts, lib/dal/src/workspace_snapshot.rs, lib/sdf-server/src/server/service/graphviz.rs
There are 3 different kinds of things you can view, all rendered as a graph.
1. The default view contains all the components you've placed on the diagram and all the nodes in the system they are connected to. We start at the components and walk the graph from there.
2. The next option contains everything. We walk from every node in the workspace, which includes assets and builtins that are not related to components. Components in the diagram are also included here.
3. The rest of the options are all the builtins themselves. We take a single schema variant and walk only its related nodes. This will never contain a component from the diagram.
I've included a handy refresh button. If you're viewing components, and change the diagram, you can hit that button to reload the page. You can search …
=> Improved Visualizer

lib/dal/src/action/batch.rs, lib/dal/src/action/prototype.rs, lib/dal/src/action/runner.rs, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/component.rs, lib/dal/src/func.rs, lib/dal/src/func/argument.rs, lib/dal/src/pkg/import.rs, lib/dal/src/prop.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/rebase.rs, lib/sdf-server/src/server/server.rs
Schema / Schema Variant Edges now exist as follows:
DEFAULT: Schema -> Uses -> Schema Variant
In order to make a schema variant the default for a schema, we need to update the
correct edge from Use to Default:
UPDATE: Schema -> Default -> Schema Variant
Therefore, when we are setting a default schema variant we need to find any existing
Default edges and convert them back to uses AND we need to find the existing Use edge
between our nodes and change that to be a Default
=> feat(sdf-server, dal): Adding an edge for default schema variants at pkg import time

lib/dal/src/attribute/value.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/property_editor.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/restore_default_function.rs
Allow user to revert manually setting a value by detaching the av from its direct prototype, making the av be set by the default prototype for its prop
=> feat(dal,sdf): unset overriden value

lib/dal/src/code_view.rs, lib/dal/src/component.rs, lib/dal/src/context.rs, lib/dal/src/func.rs, lib/dal/src/func/backend/js_action.rs, lib/dal/src/func/backend/js_reconciliation.rs, lib/dal/src/func/intrinsics.rs, lib/dal/src/lib.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/rebase.rs, lib/sdf-server/src/server/service/change_set/apply_change_set.rs
This PR disallows panics in the `dal` by default. It fixes or permits existing panic locations along the way.
=> Do not allow panics in the dal by default (ENG-2411)

lib/si-layer-cache/tests/integration_test/db/mod.rs
Adds a test that proves that we wind up with a load balanced work queue, by confirming that we don't get duplicate messages to the stream.
=> chore(layer-cache): add tests for the work queue

lib/dal/src/workspace_snapshot/graph.rs
This commit downgrades the log level for only "onto" and "to_rebase" edges when detecting conflicts and updates. Too noisy!
=> Downgrade log level for only "onto" and "to_rebase" edges (ENG-2420)

app/web/src/components/AttributesPanel/AttributesPanelItem.vue, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/prop.rs, lib/dal/src/property_editor/schema.rs, lib/dal/src/property_editor/values.rs, lib/dal/src/schema/variant.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/tests/integration_test/property_editor.rs
Previously, the rebaser was skipping any unordered children of ordered containers.
Since an attribute value for a map has an ordering node connection, when computing its children, the rebaser was only considering those edges to those nodes as updates. Since when we do an override we’re binding an attributePrototype directly to the attribute value, without the ordering connection, the rebaser was skipping it.
But this was working fine for string attribute values, for instance, since they are considered unordered containers (they’re not containers at all, but since they don’t have the ordering node that’s how we treat them).
This PR also fixes an issue in which adding an ordered node to a fresh graph fails, which was forcing unit tests to be more complex than they needed to be
=> fix(dal): make sure you can manually override maps and arrays

.gitignore, app/web/BUCK, app/web/cypress/e2e/authentication/login.cy.ts, app/web/cypress/e2e/authentication/logout.cy.ts, app/web/cypress/e2e/modelling-functionality/create-component.cy.ts, app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts, app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts, app/web/cypress/e2e/web-functionality/get-summary.cy.ts, app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts, app/web/cypress/global.d.ts, app/web/cypress/support/commands.ts, app/web/src/components/AttributesPanel/AttributesPanelItem.vue, app/web/src/store/auth.store.ts, prelude-si/e2e.bzl, prelude-si/e2e/BUCK, prelude-si/e2e/e2e_test.py, prelude-si/e2e/toolchain.bzl, prelude-si/macros.bzl, prelude-si/macros/e2e.bzl, prelude-si/tilt.bzl, toolchains/BUCK
This PR adds a new toolchain into our BUCK build system to allow us to execute Cypress end to end tests via BUCK directly.
In a follow up PR, the test will then be executed in CI.
The added target is runnable and buildable, depending on how you would like to execute it.
You can explicitly invoke as follows:
`buck2 run app/web:e2e-test -- --tests 'cypress/e2e/**' --web-endpoint http://localhost:8080`
This will run all our e2e tests against your local stack. These values are the defaults and can be excluded entirely on invocation if you desire, i.e.
`buck2 run app/web:e2e-test`
When executed, the target will check a few things before executing, these are listed below:
- The stack is responsive on the given `--web-endpoint` within 60s
- Cypress installation is valid
- You are on an supported …
=> feat: add target for cypress e2e tests into BUCK

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/components/AttributesPanel/AttributesPanelItem.vue
This resets the value of a map, array or object back to the default function for the schema variant, as the x button does for text fields (string, number)
=> feat(web): Show "set by socket" option on dropdown for maps and arrays.

component/ci-base/Dockerfile
Adding a virtual framebuffer/a display server implementing X11 within the ci-base as there are no FE packages in there at the minute.
I imagine this might not be the final change here as we will probably need chrome or some additional browser packages for cypress.
Will work forward as needed.
Not adding into the nix flake as any normal developer machine will have this dep already satisfied
=> feat: add xvfb into ci-base

component/ci-base/Dockerfile
Follow on PR to add the rest of the deps in for Cypress tests in CI. 
These will be satisfied locally on dev machines my default (normally)
=> feat: add more deps into ci-base image

lib/dal/src/attribute/value.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/workspace_snapshot.rs
The concurrency types used by the WorkspaceSnapshot to provide interior mutability in the tokio run time are *not* sufficient to prevent data races when operating on the same graph on different threads, since our graph operations are not "atomic" and the graph *WILL* end up being read from different threads while a write operation is still in progress if it is shared between threads for modification. For example after a node is added but *before* the edges necessary to place that node in the right spot in the graph.
A more general solution is needed to represent the concept of a "transaction" when mutating the graph, to prevent other readers from seeing incomplete graphs from in-progress write operations.
For now, we have added a lock to `DependentValuesUpdate` that ensures the portion of …
=> fix(dal): : synchronize graph access in dependent values updates

Cargo.lock, Cargo.toml, bin/cyclone/Cargo.toml, bin/si/src/args.rs, lib/config-file/Cargo.toml, lib/dal/Cargo.toml, lib/dal/src/lib.rs, lib/si-std/Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This PR updates every Rust-based dependency by its major, minor or patch version by default. It also moves the `postcard` version declaration from `dal` to the main `Cargo.toml` since the `alloc` feature is a subset of the `use-std` feature.
Given the large scope of these changes, this PR does not seek to change any Rust code or fixups barring a small change regarding`EnumVariantNames`. Exceptions to the goal of this PR include the following:
- Hold `rustls`, `webpki-roots`, `tokio-vsock` and `yrs` to their minor versions due to API changes
- Hold `nix` and `ring` to their current versions due to needing buck2-specific changes
- Hold all hyper v1 dependencies to their minor versions due to a longer term effort needed to get us to hyper v1
- Hold `serde_yaml` to its current version due to …
=> Update Rust dependencies since merging `new-engine` into `main` (ENG-2428)

lib/dal/src/component.rs, lib/dal/src/component/resource.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/component/get_resource.rs
This can't be merged yet  because refresh operations overwrite the /root/resource prop which means this will always return an empty resource to the UI
=> feat(sdf, dal): Restore get_resource endpoint to the system

lib/dal/src/action.rs, lib/dal/src/action/prototype.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs
This PR drops `ActionKind` from the `ActionPrototype` variant within `EdgeWeightKind`. This information is available within the `ActionPrototype` node and we should not store duplicate information unless strictly necessary.
=> Drop ActionKind from ActionPrototype edge (ENG-2434)

.buckconfig, config/BUCK, mode/debug, mode/release, prelude-si/build_context/build_context_srcs_from_deps.bxl, prelude-si/platforms/BUCK, prelude-si/platforms/defs.bzl, toolchains/BUCK, toolchains/toolchain.bzl
This PR enables release and debug builds for buck2. By default, we will always do debug builds (or, more accurately, whatever the rustc compiler thinks the defaults should be).
If you want to build for release or debug explicitly, you can do that with:
```
$ buck2 build @//mode/release //bin/sdf:sdf
```
And the result will be compiled with release optimizations. You can also use `@//mode/debug` if you want. Those files are just ways of DRY-ing up the configuration options - you could also pass them directly on the command line.
We can add as many configuration options as we want, and as many toolchain configurations as we want, by extending the options in the `//config` tree, adding a new toolchain statement, and extending the select statement for the `:rust` alias.
=> feat(ci): enable release and debug builds

app/web/src/api/sdf/dal/func.ts, app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/AssetFuncListPanel.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/FuncListPanel.vue, app/web/src/components/FuncEditor/FuncTest.vue, app/web/src/components/NewFuncDropdown.vue, app/web/src/store/asset.store.ts, app/web/src/store/func/funcs.store.ts, lib/dal-test/src/test_harness.rs, lib/dal/src/func.rs, lib/dal/src/func/kind.rs, lib/dal/src/func/view.rs, lib/dal/src/func/view/list.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/func.rs, lib/dal/tests/integration_test/mod.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/create_func.rs, lib/sdf-server/src/server/service/func/get_func.rs, lib/sdf-server/src/server/service/func/list_funcs.rs, lib/sdf-server/src/server/service/variant.rs, lib/sdf-server/src/server/service/variant/create_variant.rs, lib/sdf-server/src/server/service/variant/get_variant.rs
This PR replaces `FuncVariant` with `FuncKind`. `FuncKind` is being used in the new engine and `FuncVariant` is a very similar, but leftover, enum from the func authoring experience in the old engine. These changes do not guarantee that creating funcs will work, but listing and getting funcs in the frontend should continue to work.
This PR also consolidates the `"list_func"` route logic into one location in the dal. It is backed with an integration test as a result.
- Add "kind" to the `Func` struct since it is already on the node weight
- Move `FuncKind` to its own submodule
- Remove unnecessary conversions of `FuncBackendKind <> FuncVariant` and hardcode `FuncBackendKind` in relevant routes
- Separate `FuncKind` and `CustomizableFuncKind` in the frontend (the latter is a subset of the …
=> Replace FuncVariant with FuncKind and consolidate list func logic

app/web/src/components/modules/ModuleDisplay.vue, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/pkg.rs, lib/sdf-server/src/server/service/pkg/list_pkgs.rs
The functionality allows listing remote modules only at this time. It also [temporarily] removes the ability to install the package or to manage a builtin
=> feat(sdf): Restore Modules tab

lib/dal-test/src/schemas/test_exclusive_schema_swifty.rs, lib/dal/tests/integration_test/action.rs, lib/dal/tests/integration_test/action/with_update.rs, lib/dal/tests/integration_test/schema/variant/view.rs
Fixes ENG-2432
This test creates a component, merges to head, sees the create action happen, forks head, queues an update action, merged to head then checks the component resource view
=> chore(dal): Adding a test for setting an update action

lib/dal/src/builtins.rs, lib/dal/src/builtins/func.rs, lib/dal/src/module.rs, lib/dal/src/pkg/import.rs
This will allow us to be able to understand what makes up a package at import time - we are creating connections to funcs, schemas and schema variants
There are still some TODOs in this PR:
* Before we import funcs, schemas or schema variants, we need to check the graph to see if there's already an edge to them
That will be followed up with as it doesn't change the way that the import_pkg works
=> feat(dal): Add an edge from Module to package contents on import

lib/dal/src/module.rs, lib/dal/tests/integration_test/pkgs.rs, lib/sdf-server/src/server/service/pkg.rs, lib/sdf-server/src/server/service/pkg/get_pkg.rs
This used to load the package from disk and we don't need to do that anymore now that we have all the details on the graph
=> feat(dal, sdf): Reinstate get_pkg using the Modules on the graph

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/store/change_sets.store.ts, lib/dal/src/change_set.rs, lib/dal/src/change_set/event.rs, lib/sdf-server/src/server/service/change_set.rs, lib/sdf-server/src/server/service/change_set/abandon_change_set.rs, lib/sdf-server/src/server/service/change_set/abandon_vote.rs, lib/sdf-server/src/server/service/change_set/begin_abandon_approval_process.rs, lib/sdf-server/src/server/service/change_set/begin_approval_process.rs, lib/sdf-server/src/server/service/change_set/merge_vote.rs
Enable the routes for beginning the approval and abandon approval processes.
This change allows users to start the approval flow for change sets.
In-App flow is functioning with parity.
=> feat: Enable begin approval and abandon approval process routes

dev/Tiltfile, lib/dal/src/workspace_snapshot.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs
Adds `read_wait_for_memory` to the workspace_snapshot database to loop
for up to 2 seconds, waiting for the workspace snapshot to arrive over
the jetstream gossip layer.
Changes the Tiltfile to build our services in release mode (vroom!).
=> feat: don't wait for persist to request rebase

lib/rebaser-server/src/server.rs, lib/rebaser-server/src/server/core_loop.rs
The rebaser was failing to shut down when it was killed from a signal rather than a straight ctrl-c. The side effect is that you likely have multiple rebasers running.
=> chore(rebaser): fix graceful shutdown

lib/rebaser-server/src/server/core_loop.rs
This PR fixes the issue where the rebaser would rebase things as fast as it possibly could. Instead, it creates a queue for every change set ID it sees, and only processes one message at a time for each change set.
It currently doesn't support removing those queues - once we see it, the worker will stay resident forever. That's probably not a big deal, given that we mostly have single users and the proliferation of change sets isn't so high. But it's obviously not the optimal solution for long.
This is a stop-gap PR while Fletcher works on the long term solution, which likely involves some clever use of Jetstream's tuning options to ensure only one message can be in flight at a time, and that those messages get replayed if needed.
=> bug(rebaser): only rebase one request at a time per change set

lib/dal-test/src/schemas/test_exclusive_schema_category_pirate.rs, lib/dal-test/src/schemas/test_exclusive_schema_dummy_secret.rs, lib/dal-test/src/schemas/test_exclusive_schema_fallout.rs, lib/dal-test/src/schemas/test_exclusive_schema_katy_perry.rs, lib/dal-test/src/schemas/test_exclusive_schema_starfield.rs, lib/dal-test/src/schemas/test_exclusive_schema_swifty.rs, lib/sdf-server/src/server/job_processor.rs
import_pkg by default will import all schemas in pkg if the list is not passed, so we can get away with passing the default import options on tests.
=> chore(dal): Simplify test migrations

lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/value.rs, lib/dal/src/func/associations.rs, lib/dal/src/func/view.rs, lib/dal/src/prop.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/leaves.rs, lib/dal/tests/integration_test/func.rs, lib/dal/tests/integration_test/func/associations.rs
This PR adds the ability to find func associations for code generation and qualification funcs. It may have also done it for attribute funcs, but that remains to be seen.
There's one integration test added as part of this commit, but it's hardly enough for the authoring domain. Baby steps.
=> Find func associations for code generation and qualification funcs

lib/dal-test/src/test_harness.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/deprecated_action/runner.rs, lib/dal/src/func.rs, lib/dal/src/func/associations.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/func/variant.rs, lib/dal/src/history_event/metadata.rs, lib/dal/src/job/definition/action.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/json.rs, lib/dal/src/schema/variant/metadata_view.rs, lib/dal/src/schema/variant/value_from.rs, lib/dal/tests/integration_test/func/associations.rs
This PR restores func associations for actions. In addition, it refactors the schema variant domain to make the core module easier to navigate. That was fueled by listing schema variants for auth funcs moving to the `SchemaVariant` impl as well as the addition of a new function to list schema variants for action funcs.
This PR also includes an integration test for each association. They're non-comprehensive, but are a step in the right direction.
=> Restore func associations for actions

lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs
Ideally we should be dequeueing values that don't exist, but that's a can of worms since we can't ensure it will happen, as removing some edge may delete something because it gets garbage collected.
This should be ok, and not hide any bugs, and the warning is there so we can be informed of further consequence. Right now it will pretty much only happen in tests and copy pasting.
If the warning gets too verbose, we can remove it, or downgrade to a debug statement, but let's see how it behaves first.
=> Ignore deleted values in DVU

lib/dal/src/context.rs, lib/si-events-rs/src/function_execution.rs, lib/si-events-rs/src/lib.rs, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/db/function_execution.rs, lib/si-layer-cache/src/migrations/U0004__function_executions.sql, lib/si-layer-cache/src/pg.rs, lib/si-layer-cache/tests/integration_test/activities.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/function_execution.rs, lib/si-layer-cache/tests/integration_test/db/mod.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
This yet another db inside of layer db. What's special about this one is that it only interacts with postgres and does not use the in-memory or on-disk layers at all (so no NATs bits either).  Also, I'm attempting to use an ugly version of a composite key to ensure we can look these executions up from a few different angles. Currently, the key is `component_id + prototype_id + action_id` . This allows us to do lookups for specific actions and lookups for all action executions that ever happened for a given component/prototype. I _think_ there is a cleaner way to do this, so I'm all ears if anyone has thoughts.
Note that this doesn't implement the actual struct that will be stored. That will come next.
=> Add Function Execution DB 

app/web/src/api/sdf/dal/diagram.ts, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/FuncEditor/AttributeBindings.vue, app/web/src/components/FuncEditor/AttributeBindingsModal.vue, app/web/src/components/FuncEditor/FuncTest.vue, app/web/src/store/asset.store.ts, app/web/src/store/func/funcs.store.ts, app/web/src/store/func/types.ts, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/func.rs, lib/dal/src/func/argument.rs, lib/dal/src/func/associations.rs, lib/dal/src/func/authoring/save.rs, lib/dal/tests/integration_test/func/associations.rs
This PR restores func associations for attribute funcs. It also fixes how components and schema variants are derived from attribute prototypes via the new "eventual parent" concept. Now, we enforce that there must be one and only one eventual parent for a given attribute prototype.
- `ExternalProviders` and `InternalProviders` are completely scrubbed from `app/web`
- Simplify code gen and qualification func association logic
- Replaces some `pk` macro usages with the newer `id` macro
=> Restore func associations for attribute funcs, fix eventual parent logic and finish wiping provider concept from `app/web`

lib/dal/src/attribute/value.rs, lib/dal/src/job/definition/action.rs, lib/dal/tests/integration_test/action/with_update.rs
Running actions concurrently produces some race condition behavior with the current implementation (also we were rebasing at least 3 times per action, too much!). Actions will have to be refactored to support concurrent execution similar to the way we synchronize function execution in the dependent value update. For now, running them serially will produce correct results.
=> fix: run actions serially

app/web/src/store/component_attributes.store.ts, lib/dal/src/change_set/event.rs, lib/dal/src/ws_event.rs, lib/rebaser-server/src/server/core_loop.rs
This restores the change set written event, which it turns out we do need - the rebaser still handles when data is "committed", and therefore when it is visible in different parts of the UI. Long term, it would be great to figure out how to thread more specific events through, so that we don't have a cascade of calls that are needless from the frontend. But for now, this will work.
=> bug(*): need change set written after all

lib/dal/src/context.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/func.rs, lib/dal/src/func/before.rs, lib/dal/src/func/intrinsics.rs, lib/dal/src/pkg/import.rs, lib/dal/src/prop.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/root_prop.rs, lib/dal/src/workspace.rs, lib/dal/tests/integration_test/attribute.rs, lib/dal/tests/integration_test/attribute/prototype.rs, lib/dal/tests/integration_test/mod.rs, lib/dal/tests/integration_test/schema/variant.rs, lib/rebaser-server/src/server.rs, lib/sdf-server/src/server/service/session/auth_connect.rs
This PR removes the `PropParent` enum and replaces it with explicit methods. In addition, `Props` can now only have "ordered" `Prop` parents, which has been the only way we've created `Props` anyway.
This commit also fixes `SchemaVariant::all_funcs` to account for sockets. The method has been optimized it to batch load funcs after all `FuncIds` have been collected.
- Remove unneeded `dbg!` from the rebaser
- Remove unused `import_builtins` method from the old engine
- Allow `AsRef<str>` parameter for `IntrinsicFunc::maybe_from_str`
- Tweak ergonomics for downstream methods related to `SchemaVariant::all_funcs`
- Replace remaining references to providers in import logic
- Add `find_for_prop` integration test for `AttributePrototype` in addition to tests related to …
=> Remove `PropParent` and fix `SchemaVariant::all_funcs`

lib/si-layer-cache/src/activities.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs
We were using the wrong kind of lock a (RwLock rather than a Mutex) around the creation of broadcast channels in the activity multiplexer. When we went to create a new subscription, we would acquire a Read lock when checking for the existence of the broadcast channel, and if it didn't exist, continue on to create a new one by acquiring a Write lock later in the function.
This, of course, was racy - multiple consumers could acquire a failing Read lock condition, and then pass through to the critical section where we create a new broadcast channel - the result being multiple consumers of the underlying NATS jetstream would be created, only one of which was actually sending the messages we wanted.
I believe this is the source of the occasional deadline misses in rebase finished requests - at …
=> bug(layerdb): race to create broadcast channels

lib/dal/src/diagram.rs
We defaulted to false but since we started being able to create resources we can now return if the resource exists
=> fix(dal): Ensure we set if the component has a resource

lib/dal/src/context.rs, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/db/func_execution.rs, lib/si-layer-cache/tests/integration_test/activities.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/func_execution.rs
We don't actually need the bounds around the func execution db to be generic as we know the type we want to use and we don't interact with the DB layers that need it.
=> fix: remove unnecessary gerneric bounds for func execution

component/deploy/docker-compose.yaml, component/init/configs/pgbouncer.ini, component/init/configs/service.toml
We need these values in place in order to set the layer cache db name in pgbouncer and the related services.
=> feat: add layer cache dbname to init container config

lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/change_set.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/func/argument.rs, lib/dal/src/func/associations.rs, lib/dal/src/func/associations/view.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/func.rs, lib/dal/tests/integration_test/func/argument.rs, lib/dal/tests/integration_test/func/associations.rs, lib/dal/tests/integration_test/func/authoring.rs, lib/dal/tests/integration_test/func/authoring/save_func.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/service/func/save_func.rs
Currently, `save_func` works in the new engine. However, we need it to work for attribute funcs and advanced use cases. This commit is a step in that direction with the goal of ensuring of collecting and saving func associations works when saving an attribute func.
- Fix func argument mutation, removal and additional procedures when working with attribute funcs
- Fix action kind selection in the authoring screen
- Add integration tests for all func saving scenarios (with attribute funcs getting a full-length test)
- Fix code gen and qualification input checkboxes
- Convert stdout lines to logs when importing packages
- Make errors clearer when importing packages
- Replace default schema variant log with debug log
- Changing the type of a func argument for an attribute func does not work
- …
=> Re-introduce saving attribute funcs in the new engine

lib/rebaser-server/src/config.rs
Missed some defaults in my earlier PR for the rebase config.
=> fix: defaults in rebaser config overwrite local settings

app/web/src/store/change_sets.store.ts
`useRoute` cannot be used outside of a Vue component (it's enough to put it inside of the createStore). Quiet the warning about inject in the wrong context.
=> fix(web): don't inject route outside of createStore

flake.nix
Docker build and omnibus use nix-invoked builds to create the binaries/packages.
This moves those publishable Artifacts to use release build by default.
=> feat(binary): move nix-invoked buck build to use release mode by default

bin/pinga/src/args.rs, bin/rebaser/src/args.rs, bin/sdf/src/args.rs, component/init/configs/service.toml, lib/pinga-server/src/config.rs, lib/rebaser-server/src/config.rs, lib/sdf-server/src/server/config.rs
Adds a `--layer-cache-disk-path` arg to rebaser, pinga and sdf to allow us to specify a non /tmp/ path when running in Production/Tools Production.
This should let us monitor + work with the services more easily.
=> Add --layer-cache-disk-path arg to relevant services

app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, flake.nix, lib/dal/src/change_set.rs, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/diagram/create_component.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs
1. do not rely on browser hover when dropping components into frame. perform the math to see what we are inside.
2. this lets us remove the hack in cypress tests
3. fix to missing parentId (was renamed to parentComponentId)
4. `set_component_position` endpoint needed to change for the new engine
5. fixed a swap of width & height bug on resizing
6. send a web event from the `set_component_position` endpoint
7. frame movement now supports deeply nested children
8. nudging is debounced now, so we don't flood the system with changes
9. creating or attaching a component inside a frame expands the child to the available size and fully bounded by the parent
10. so long as there are no other children, in that case, it makes the frame smaller and does not attempt a "best fit".
=> Fix Frames, a journey

lib/si-layer-cache/src/memory_cache.rs
We should be smarter about this, but this should work for now to ensure we don't starve the VMs in AWS. We'll want this to get the max memory from the machine and set to some ratio of that.
=> feat: set moka max_size to 12gb to ensure we don't starve the host

lib/si-layer-cache/src/memory_cache.rs
This was not considered well enough. We actually make 4 distinct caches, so collectively we are setting the total memory to 48gb. Reverting so we can do this properly.
This reverts commit f108aec47d5cc32be89e0404d84339b349d69e6e.
=> Revert "feat: set moka max_size to 12gb to ensure we don't starve the host"

lib/dal/src/component.rs, lib/dal/src/prop.rs
This fixes the bug that broke the `region` frame. We were manually setting the name on component creation, overriding the prototype that makes the region prop control the root/si/name prop for that component.
=> fix(dal): don't break custom name functions on component creation

lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant.rs, lib/dal/tests/integration_test/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs, lib/dal/tests/integration_test/schema/variant/authoring/create_variant.rs, lib/sdf-server/src/server/service/variant.rs, lib/sdf-server/src/server/service/variant/clone_variant.rs, lib/sdf-server/src/server/service/variant/create_variant.rs
This keeps it inline with Func Authoring and will allow us to test the pieces in isolation rather than needing to go through SDF for testing
=> chore(dal, sdf): Refactoring the Asset Authoring experience behind a client

app/web/src/store/components.store.ts
`componentStore.selectedEdge` fails without saving over the tempID.
=> ENG-2502 edge set response id

lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/cycle_check_guard.rs, lib/dal/tests/integration_test/mod.rs
Ensures we check for graph cycles when connecting components (to prevent connecting components in a cycle), and when attaching children to parent frames.
=> feat(dal): check for cycles when connecting components

bin/pinga/src/args.rs, bin/rebaser/src/args.rs, bin/sdf/src/args.rs, bin/sdf/src/main.rs, component/init/configs/service.toml, lib/dal-test/src/lib.rs, lib/pinga-server/src/config.rs, lib/pinga-server/src/server.rs, lib/rebaser-server/src/config.rs, lib/rebaser-server/src/server.rs, lib/sdf-server/src/server/config.rs, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/src/error.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/lib.rs, lib/si-layer-cache/src/memory_cache.rs, lib/si-layer-cache/tests/integration_test/activities.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/func_execution.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
This adds the ability to configure the idle time of items in the memory portion of the layerdb. It defaults to 10 minutes. It does this by adding configuration structs for the memory cache and layerdb itself. This helps us on the front end for these settings as it makes it easier to turn args and config values into a normalized structure that we can pass through to app startup. Should make it much easier to add more settings as we go.
The pgpool and nats bits are shared in the args (except for the layerdb dbname), but you can configure the settings separately in the config file, which is what we use in prod.
```toml 
[nats]
creds = """
$SI_NATS_CREDS
"""
url = "$SI_NATS_URL"
[pg]
user = "si"
password = "$SI_PG_PASSWORD"
dbname = "$SI_PG_DB"
application_name = "$SI_SERVICE"
hostname = …
```
=> feat: add config struct for layerdb and the memory cache

component/deploy/docker-compose.yaml
I noticed that our node-exporter was having a bad time trying to ship a few metrics. This will ensure that it knows where to look for proc, sys, and the rootfs while also being able to pull metrics from systemd. Notably, we can get unit stats so we can tell if a service is thrashing.
```bash
[root@ip-12-0-10-253 ec2-user]# curl localhost:9100/metrics | grep rebaser
...
node_systemd_unit_state{name="rebaser.service",state="activating",type="exec"} 0
node_systemd_unit_state{name="rebaser.service",state="active",type="exec"} 1
node_systemd_unit_state{name="rebaser.service",state="deactivating",type="exec"} 0
node_systemd_unit_state{name="rebaser.service",state="failed",type="exec"} 0
node_systemd_unit_state{name="rebaser.service",state="inactive",type="exec"} 0
```
=> fix: correcting node-exporter flags that blocked seeing sysd metrics

app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/component.rs, lib/sdf-server/src/server/service/ws/workspace_updates.rs
The changes include:
1. Make sure all changes to position and size runs through a single function. That refactor is most of the diff. Nearly every single position change also had a line of code to POST the same position. We can encapsulate that logic to prevent errors and introduce clarity.
2. Adding a new receiver for WsEvents in SDF that reflects the payload back out to all clients.
3. Sending websocket messages onDragMove and onResize events.
=> Basic multiplayer experience for moving and resizing elements on the diagram

lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/context.rs, lib/dal/src/diagram.rs, lib/dal/src/socket/debug.rs, lib/dal/src/socket/input.rs, lib/dal/tests/integration_test/frame.rs
This PR moves around the check for deletes so we can pass the flag appropriately on inferred connections. I also added a test to make sure output sockets can pass values to children and manually connected components
<div><img src="https://media1.giphy.com/media/xzDIIZCozVXI4/giphy.gif?cid=5a38a5a2n5clqtpghj9isgn611f6ft41825b4aftiw62k7tq&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/><br/>via <a href="https://giphy.com/channel/tkyle/">T. Kyle</a> on <a href="https://giphy.com/gifs/realitytvgifs-rhonj-danielle-staub-tgif-xzDIIZCozVXI4">GIPHY</a></div>
=> Added to_delete to inferred connections and ensure output sockets can drive inferred and manual connections simultaneously

app/web/src/store/asset.store.ts, lib/dal/src/schema/variant/metadata_view.rs, lib/sdf-server/src/server/service/variant.rs, lib/sdf-server/src/server/service/variant/clone_variant.rs, lib/sdf-server/src/server/service/variant/get_variant.rs
We were using SchemaVariantId to load the Variant details. This meant when we needed to clone OR to create a new variant, the screen would have redirected
We are now going to use SchemaId as the identitifer and we will then load the default_schema_variant for the schema
=> fix(sdf, dal, web): Change Asset Panel to use schemaID

lib/si-layer-cache/src/db.rs
Use the tempdir() methods to ensure the path is actually created.
=> feat: verify disk_path values for layerdb on startup

lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/workspace_snapshot/conflict.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
Many nodes assume complete control of their direct, outgoing neighbors, and allowing them to be silently merged with other neighbors from another changeset would create an incorrect graph. For example, an AttributeValue should only ever have one outgoing Prototype edge defining the "component specific" prototype for that value. If another user merges in a changeset with an updated prototype edge that we have never seen in our change set, that should be considered a conflict, since otherwise the result of the rebase would be an AttributeValue with *two* Prototype edges, an incorrect state. The same applies for "Contains" edges and many others. This change will produce an `ExclusiveEdgeMismatch` conflict when the snapshot being rebased (the `to_rebase`) has a container with edges not seen …
=> feat(dal): add exclusive outgoing edge conflicts to rebase

lib/dal/src/job/consumer.rs, lib/dal/src/job/definition/action.rs, lib/dal/src/job/definition/compute_validation.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/job/definition/refresh.rs
Adds retry logic to the job consumer. Jobs can request retry and specify a retry policy (immediate, or exponential backoff), as well as the retry limit. Uses this to make the `DependentValuesUpdate` job retry on conflict.
=> feat(dal): retry dependent values update jobs on conflict

app/web/src/components/Debug/AttributeDebugView.vue, app/web/src/components/Debug/AttributePrototypeDebugView.vue, app/web/src/components/Debug/SocketDebugView.vue, app/web/src/store/components.store.ts, lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/debug.rs, lib/dal/src/component.rs, lib/dal/src/component/debug.rs, lib/dal/src/diagram.rs, lib/dal/src/socket/debug.rs, lib/dal/src/socket/input.rs, lib/dal/tests/integration_test/frame.rs
This PR contains the following fixes: 
- accurately infer if an input socket is manually configured or not (I was previously not filtering correctly by destination component)
- grab the correct Attribute Prototype Argument when showing inputs in the debug panel
- Display more helpful info in the debug panel. I added the value source, value id source, whether or not the data should pass through, and I now include inferred inputs to attribute prototypes (which matters only for input sockets) 
- Fixed a false positive integration test, that was falsely passing due to the above bug on inferring whether an input socket is manually inferred
=> More Frames Fixes

README.md, dev/BUCK, dev/Tiltfile, docs/RUNNING_THE_STACK_LOCALLY.md
This PR adds standard and debug rustc build modes when building and running the full stack via tilt. The "standard" rustc build mode is what the upstream prelude builds with by default. The "debug" rustc build mode explicitly uses debug build optimizations.
Debug optimizations...
```shell
buck2 run dev:up-debug
```
Standard optimizations...
```shell
buck2 run dev:up-standard
```
=> Add standard and debug rustc build modes for tilt

README.md
This PR removes the badge for nightly CI builds. With the new engine, we believe we do not need nightly CI runs (for now) because equivalent tests are expected to be much faster to run. Combine that with the fact that nightly runs have not been ran in nearly two months and it's evident that it's time to retire the badge.
=> Remove badge for nightly CI builds

README.md, docs/BUCK2.md, docs/EDITORS_AND_IDES.md, docs/LEARNING_ABOUT_SI_CONCEPTS.md, docs/RUNNING_THE_STACK_LOCALLY.md
This PR makes links between documents easier to read by using naturally flowing sentences rather than hard references by file names.
=> Make links between documents easier to read

lib/dal-test/src/helpers/change_set.rs, lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/rebaser.rs
We should not silently return from applying to head if conflicts caused the rebase to fail. This returns the conflicts in an error. Also fixes a bug where the target node was used instead of the container in detecting exclusive edge conflicts.
=> fix(dal): conflicts on apply are an error

lib/module-index-server/src/routes.rs, lib/module-index-server/src/routes/download_workspace_route.rs
We're merging the modules index changes first since they're additive, and we can test the export/import loop more thoroughly - wiping the local database also wipes the local module index
=> feat(module-index): Import workspace endpoint on module index

app/web/src/components/ModelingDiagram/DiagramEdge.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/components/ModelingView/DeleteSelectionModal.vue, app/web/src/components/ModelingView/RestoreSelectionModal.vue, app/web/src/store/components.store.ts, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/socket/input.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/frame.rs, lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs, lib/sdf-server/src/server/service/diagram/delete_connection.rs
Edges no longer have an inherent ID. They are defined by what they connect. Diagram::assemble now returns edges and inferredEdges and we need to reconcile both of those in the UI.
1. Change Vue to use edgeId that is a compound key made up by {to_socket_ulid}_{from_socket_ulid} for all edges
2. Change SDF to remove id  and edgeId from Diagram::assemble
3. In Vue add inferred edges to the store edgesById where the rest of the edges live.
4. Change SDF to accept two params {to_socket_ulid} and {from_socket_ulid} to delete an edge and to restore an edge
5. On detach component from parent remove inferred edges between the two components.
6. On attach component to parent fire the component updated WsEvent (which fires the big hammer).
7. isInvisible should reflect whether an edge is inferred or …
=> ENG-2508 update edge logic

app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
This PR fixes attribute bindings not appearing in the asset screen by using the schema variant id instead of the schema id.
=> Fix attribute bindings not appearing in the asset screen

.ci/DEV.md, .ci/docker-compose.test-integration.yml, component/deploy/docker-compose.yaml, component/pgbouncer/BUCK, component/pgbouncer/Dockerfile, dev/README.md, dev/Tiltfile, dev/docker-compose.platform.yml, lib/dal-test/src/lib.rs
This PR adds pgbouncer to our dev setup. It moves the "real" postgres instances to 7432 (si) and 8432 (si-test) respectively, replacing them with two different pgbouncers. This change is primarily to ensure that we avoid any threat of pool exhaustion in the test suite, but has the added benefit of making the dev stack closer to our production deployment (which would also include pgbouncer.)
PgBouncer configures a pool per hostname+database. Since each of our dal integration tests creates its own database, it thereby also creates its own pool. To manage this, we create a pool size of 10 per hostname+database tuple, which we will then reap after 10 idle seconds. The result is that the current test suite peaks somewhere around 300 tests, but very rapidly shrinks. We should have plenty of …
=> chore(db): add pgbouncer to our dev setup

.github/workflows/deploy-service.yml
Adds a dead simple deploy button with a drop down. This will either deploy all services or a specific one. All it does is tell the relevant autoscaling group to refresh it's instance. There is nothing here about deploying a specific version, it simply resets the cloudfront cache for the artifact store and then the ASGs pull the latest `stable` version on startup. Don't overthink it.
=> feat: add simple deploy workflow for tools-prod

lib/dal-test/src/lib.rs, lib/dal/src/pkg/import.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/get_diff.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/dependent_values_update.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs, lib/si-layer-cache/src/persister.rs
This PR removes dbg and println statements from the test suites, as they were mostly just generating noise (in particular in CI). Let's try and keep this tidy in the future :)
=> chore(test): remove dbg and println

lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/prop.rs, lib/dal/tests/integration_test/component.rs
When an object changes, it spins out its values into child attribute values. Update operations will enqueue the object's value itself to the dependent value update, but if an object changes, that means its children have also (maybe) changed, so we need to add those children to the dependent value graph as well, just in case
=> fix(dal): add child values of objects to dvu calculation

lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/module.rs, lib/sdf-server/src/server/service/module/export_module.rs
In order to support workspace level imports, the import code had a Changeset based thingmap. That thingmap was causing issues in variant export because some funcs were being added to the map with the incorrect changeset id
We no longer use the import_workspace code path so we only ever import a single changeset at a time
We have no rid the world of a Changeset scoped Thingmap and this means the update_variant is a happier world and we can now happily upgrade variants!
=> fix(dal, sdf): Ensure update_asset works in all scenarios

app/web/src/components/NoSelectionDetailsPanel.vue
We were showing a Pill counter beside "Apply Changes" that was Actions + diffs - we need to remove the diffs as these are no longer listed in the changeset
=> fix(web): Ensure that the count of changes in the changeset doesn't include diffs

bin/veritech/scripts/prepare_jailer.sh, lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
The default UID range on AML 2023 is 1000-60000. We set the pool size to 100 right now. This means that we were creating pools with UIDs of 300-3099, meaning the first 10 jails would fail to prepare and cause poolnoodle to thrash when it hit those ranges. This will put us in the 3000-30099 range, which should be more reliable.
I would really love to spend some cycles reintroducing the poolnoodle changes I attempted to make before and to rethink some of these bits. The flakiness here is always bothersome.
=> fix: UID range too low for AML 2023

Cargo.lock, Cargo.toml, bin/cyclone/BUCK, bin/cyclone/Cargo.toml, bin/cyclone/src/main.rs, bin/pinga/BUCK, bin/pinga/Cargo.toml, bin/pinga/src/main.rs, bin/rebaser/BUCK, bin/rebaser/Cargo.toml, bin/rebaser/src/main.rs, bin/sdf/BUCK, bin/sdf/Cargo.toml, bin/sdf/src/main.rs, bin/veritech/BUCK, bin/veritech/Cargo.toml, bin/veritech/src/main.rs, lib/si-service/BUCK, lib/si-service/Cargo.toml, lib/si-service/src/lib.rs, lib/si-service/src/startup.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
For production deployments, the binaries all now log out the metadata file associated with the build via the omnibus package so we can see exactly what version is running on any host.
```
{"architecture": "x86_64", "author": "The System Initiative <dev@systeminit.com>", "binaries": ["/nix/store/1gm83plfdmxcs4c03s5hakwfmmw7iyk7-rebaser/bin/rebaser"], "commit": "4412718b378360cc60d2822d2be471c57e9d9356", "license": "Apache-2.0", "name": "rebaser", "nix_closure": ["/nix/store/08n25j4vxyjidjf93fyc15icxwrxm2p8-libidn2-2.3.4", "/nix/store/1gm83plfdmxcs4c03s5hakwfmmw7iyk7-rebaser", "/nix/store/lmidwx4id2q87f4z9aj79xwb03gsmq5j-xgcc-12.3.0-libgcc", "/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27", "/nix/store/s2f1sqfsdi4pmh23nfnrh42v17zsvi5y-libunistring-1.1"], "os": "linux", …
```
=> feat: add logging of version/author/metadata during startup for all binaries running in Production

lib/vue-lib/src/design-system/utils/color_utils.ts
Access of undefined `theme` causing crash in theme switch if no theme setting was already saved.
=> fix(web): fix type issue in theme switch

lib/dal/src/component.rs, lib/dal/src/deprecated_action.rs, lib/sdf-server/src/server/service/diagram/paste_component.rs
We defined actions ordering through regular component connections, now that frames don't create them, actions ordering was not taking frames into account.
Also fixes pasting components into a frame.
=> Take new frames into account when tracking actions ordering

app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/FuncTest.vue, app/web/src/components/FuncEditor/FuncTestSelector.vue, app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue, app/web/src/store/func/funcs.store.ts, lib/dal/src/attribute/value.rs, lib/dal/src/component/properties.rs, lib/dal/tests/integration_test/attribute.rs, lib/dal/tests/integration_test/attribute/value.rs, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/attribute.rs, lib/sdf-server/src/server/service/attribute/get_prototype_arguments.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/get_func.rs, lib/sdf-server/src/server/service/func/test_execute.rs, lib/vue-lib/src/design-system/forms/VormInput.vue
This PR fixes test executions for attribute funcs. It also scopes test execution abilities to solely attribute, code generation and qualification funcs.
The existing code assumes that there was only one binding for attribute funcs. Attribute funcs may have multiple bindings, which means that they can have different input sources (`AttributePrototypeArguments`) for the same `FuncArguments`. For example: if you have a `FuncArgument` that takes in a string called `toddhoward`, it is possible for one binding to get that value from `/root/si/name` and another binding to get that value from an input socket who provides a string.
The existing code also assumed that there was only one `FuncArgument`. Now, we derive the arguments from the backend and avoid walking the result of `component/json` …
=> Fix test executions for attribute funcs and missing payload value

app/web/src/components/FuncEditor/FuncTestSelector.vue
This commit makes the func test selector placeholder for attribute funcs refer to bindings. The word "prototype" does not appear in this user domain and should not be used here.
=> Make func test selector placeholder refer to bindings

lib/dal/src/migrations/U0644__pganalyze_setup.sql
The user we run `sdf` under does not have the appropriate permissions to run the pganalyze migration in prod. We do not want to escalate permissions just to run this migration. This change checks if the `rds_superuser` role exists and if we have it. If it doesn't or it does and we have it, it will run the migration. This cause no disruption to the local dev experience while allowing us to perform migrations in rds without extra hoop jumping.
=> feat: only run pganalyze migration if not in rds

app/web/src/components/AssetEditor.vue, app/web/src/components/FuncEditor/FuncEditor.vue
- No CRDT on head, since it should be set from an apply
- Stop creating two change-sets (saving on the edit and then on unmount)
- Create new change-set with the updated func, leaving head untouched
=> Forbid editing functions on head

app/web/src/components/SiFuncListItem.vue
This is a controversial one - TL;DR, I don't believe a user cares about something being builtin or not. All a builtin is, is something we give a user at application startup time. It was more important in the old engine where there was no concept of lineage
In this new engine, we can allow editing of all builtins EXCEPT the intrinsics because they are important to the system. This feels less confusing to me, as a user now
=> feat(web): Removal of SiChip to denote if something is builtin or not

app/web/src/components/DiagramOutline/DiagramOutline.vue
The problem is that the computed `searchFiltersWithCounts` uses the fn `filterComponentArrayBySearchStringAndFilters` and that fn uses `searchFiltersWithCounts` within it. So I found a way to remove the reference from within the fn.
=> BUG-138 diagram outliner fix recursion

Cargo.lock, Cargo.toml, lib/dal/BUCK, lib/dal/Cargo.toml, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/debug.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/code_view.rs, lib/dal/src/component.rs, lib/dal/src/component/diff.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/prop.rs, lib/dal/src/qualification.rs, lib/dal/src/socket/debug.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/get_diff.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/dependent_values_update.rs, lib/dal/tests/integration_test/deprecated_action/with_secret.rs, lib/dal/tests/integration_test/frame.rs
Views are now calculated on the fly by walking the attribute value tree for a given value. This should enable updates of sibling properties on a component without causing a conflict.
=> feat(dal): remove materialized views

.github/workflows/deploy-service.yml
Cloudfront invalidations can take 5 seconds or 5 minutes depending on gamma rays and such. This ensures that we wait until the invalidation completes before we deploy our services to ensure we are always getting latest.
=> feat: wait for cloudfront to invalidate before deploying services

lib/dal/src/context.rs
We should only send WsEvents after we rebase. This PR fixes it, without needing to implement passhtrough of WsEvents to the rebaser (yet).
=> bug(dal): send nats events after rebase finishes

app/web/src/components/Debug/AttributeDebugView.vue, app/web/src/components/Debug/SocketDebugView.vue, app/web/src/store/components.store.ts, lib/dal-test/src/lib.rs, lib/dal-test/src/schemas/mod.rs, lib/dal-test/src/schemas/test_exclusive_schema_starfield.rs, lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/module.rs
This makes it possible to take the children of an object set by a custom function as the input to another function. It ensures we do not place the child values directly onto the dependent value graph, but instead we place the "controlling" attribute value onto the graph if one is discovered (we will resolve the input to the correct child value in function execution).
Many of our assets depend on this, since they take children of the resource_value tree as inputs to other functions.
Closes BUG-135
=> feat(dal): support children of "dynamic" objects as inputs to other functions

lib/cyclone-server/src/watch.rs, lib/si-service/src/startup.rs
Both of these `info!` messages are very noisy when running tests
=> chore(si-service,cyclone): quiet some noisy info messages

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
When the user confirms they want to override, we need to remove the overlay so the value populated by a socket can be manually edited
<div><img src="https://media2.giphy.com/media/a6O5pzQ8pAPTCoeagK/giphy.gif?cid=5a38a5a2wgh3yyda3qlum5z8ufhmz0jgfz86q8t8052pcrzq&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/latenightseth/">Late Night with Seth Meyers</a> on <a href="https://giphy.com/gifs/latenightseth-seth-meyers-lnsm-a6O5pzQ8pAPTCoeagK">GIPHY</a></div>
=> fix check for preventing edits

app/web/src/store/components.store.ts
WsEvents are firing *BEFORE* the POST returns and when a new changeset is created by the backend, we end up re-creating componentStore, so the store for HEAD never runs onSuccess below and we end up with pending components on HEAD that never go away
To fix it; don't create pending components if we're on HEAD
=> Fix: don't create pending components on head

lib/rebaser-server/src/change_set_requests/handlers.rs
=> Fix: send correct change_set_id back in WsEvent::ChangeSetWritten

lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/prop.rs, lib/dal/tests/integration_test/connection.rs, lib/sdf-server/src/server/service/diagram/delete_connection.rs
If we receive a None value from executing a function and the value being set is a container (object, map, array), we should still populate nested since otherwise we will not clear out the child values.
=> fix(dal): None values for container props should remove child values

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/AssetFuncListPanel.vue, app/web/src/store/func/funcs.store.ts, lib/dal/src/func.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/func/authoring/execute.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/func/authoring/test_execute.rs, lib/dal/src/schema/variant.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/save_and_exec.rs, lib/sdf-server/src/server/service/func/save_func.rs
This PR fixes the ability to attach funcs to assets. In the frontend, we needed to ensure that we were using `SchemaVariantId` corresponding to the default `SchemaVariant` of the selected asset. In the backend, we needed to use `WsEvent::FuncSaved` rather than a re-fetched `FuncView` in order to ensure that associations in the frontend are up to date.
This commit also polishes the func authoring client. Tracing has been added and tuned for all func authoring client methods (descending until "work" layer functions). In addition, re-exported functions have been replaced with their inner contents. Now, re-exported functions merely provide additional functionality needed in order to not bloat the `authoring.rs` file.
Updating associations for action and authentication funcs has been polished …
=> Fix func attachment to assets and polish authoring client

lib/si-layer-cache/src/activities.rs, lib/si-layer-cache/src/event.rs
The default timeout was 5 seconds so we want to prevent any slowness of instances causing a disconnect
=> fix(layer-cache): Prevent jetstream consumers from exceeding their inactivity threshold

app/web/src/store/components.store.ts
This fixes the bug where when you connect two Docker Images to one Butane component, only one is visible
<div><img src="https://media3.giphy.com/media/13b4aUr0Bqunp6/giphy.gif?cid=5a38a5a2mdps3i950vfylqpaqfip2hql49alcgcgav9ewwo3&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/foxadhd/">Animation Domination High-Def</a> on <a href="https://giphy.com/gifs/foxadhd-art-artists-on-tumblr-lol-13b4aUr0Bqunp6">GIPHY</a></div>
=> ensure id is unique for edges

lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/layer_db_types/content_types.rs, lib/dal/src/property_editor/values.rs, lib/dal/src/secret.rs, lib/dal/src/secret/before_funcs.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/secret.rs, lib/dal/tests/integration_test/secret/bench.rs, lib/dal/tests/integration_test/secret/with_actions.rs, lib/si-events-rs/src/encrypted_secret.rs, lib/si-events-rs/src/lib.rs
This PR is a follow-up to #3694 and fixes the attribute values corresponding to individual secrets containing an object instead of a string.
The encrypted secret key is now passed through the attribute subsystem alone. Since the property editor still needs to reference which encrypted secret key belongs to which secret, we determine the origin secret dynamically when assembling the property editor (~3.8ms wall clock time for 1000 secrets with a 3970X system on `Pop!_OS 22.04 LTS` with Linux kernel `6.8.0`).
As a result of these changes, we were able to remove intermediary types with a lot of footguns as well as move the encrypted secret key to the new `SecretNodeWeight` kind. Overall performance and consistency in results should be net positive.
Another change this PR brings is the …
=> Fix secret attribute value containing an object instead of a string

lib/dal/src/action.rs, lib/dal/src/workspace_snapshot.rs, lib/rebaser-server/src/change_set_requests/handlers.rs, lib/si-layer-cache/src/activities/rebase.rs
Whenever we have successfully rebased the default change set for a workspace, we need to dispatch any eligible Actions (and mark them as dispatched). By checking which Actions are eligible to dispatch on successful rebase, we ensure that any changes to the default change set (typically `HEAD`, or `main`) will automatically cause relevant Actions to run, such as an Action being removed from the graph because it succeeded, or new Actions being queued from merging a change set into the default change set.
=> Dispatch Actions V2 after successful rebase of default change set for workspace

lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/job/queue.rs, lib/rebaser-server/src/change_set_requests.rs, lib/rebaser-server/src/change_set_requests/app_state.rs, lib/rebaser-server/src/change_set_requests/handlers.rs, lib/rebaser-server/src/dvu_debouncer.rs, lib/rebaser-server/src/lib.rs, lib/si-events-rs/src/ulid.rs, lib/si-layer-cache/src/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs
Send the set of values we intend to run DependentValuesUpdate on along with the rebase request if a non-blocking commit is requested. If values appear in the rebase request, send them to a task which will dispatch DependentValuesUpdate jobs in 5 second intervals, blocking until they finish, so that they run serially for a change set.
Note, DalContext `commit` will no longer send DependentValuesUpdate jobs to pinga (no other job types are affected). Instead it sends them to the rebaser and the rebaser will send them to pinga. `blocking_commit` still processes the job queue the same way as before, since we expect this behavior in tests. Our tests should be restructured to not require the blocking commits.
=> feat(dal,rebaser-server): rebaser debounces dvu jobs

lib/telemetry-application-rs/src/lib.rs
We've been dropping spans in tools-prod. We should turn down the noise on some of the services, but we also want to make sure that we are capturing valuable trace data. We have plenty of headroom on the ec2 nodes to handle the extra memory/cpu consumption here. This doubles us from the default of `2048`.
=> feat: increase otel batch size so we don't drop traces

lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/get_diff.rs, lib/dal/tests/integration_test/secret/with_actions.rs
To reduce more chances of conflict, remove all calls to update_from_prototype_function for dependent functions, restricting their use to the DependentValuesUpdate job (except in the case of the function execution call on the customize screen, which we have to decide how best to handle).
=> feat(dal): only run update_from_prototype_function in DVU

lib/dal-test/src/helpers.rs, lib/dal/src/action/dependency_graph.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/context.rs, lib/dal/src/diagram.rs, lib/dal/src/func/binding.rs, lib/dal/src/property_editor/values.rs, lib/dal/src/socket/debug.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/frame.rs, lib/si-layer-cache/src/activities/rebase.rs
Frames are a bit messy, but functional! I will be refactoring this into modules in another pass this week, but I want to get this out there for now. 
This PR includes the following changes: 
- Up Frames can now take inputs from multiple children (for example, when turning a Butane Component into an Up Frame and dropping multiple Docker Images inside) 
- When you attach a component to a parent, we will now run queue up only those input socket's Attribute Values for Dependent Values Update that have different inputs as a result of the attachment (this fixes a bug where we were not always re-running the right functions, which was the original bug)
- When you orphan a component, we first cache the current impacted input sockets so we can rerun them after we remove the FrameContains edge …
=> Up Frames can connect to multiple child components and fix data propagation on attach/detach/delete

lib/si-layer-cache/src/persister.rs
We saw an error last week where some snapshots we expected weren't appearing in the database. Our theory was that perhaps we were doing some out-of-order writes. That might have been true, but the fix was that we stopped spawning tasks for each persister request - which slowed down the processing of those writes to a degree that, unless you had a very fast machine, would mean that the snapshot write hadn't been distributed by the time the rebaser hit its two second limit (and the write hadn't committed to postgres yet).
This would then cause the SDF instance running the migration to panic, which would destroy the remaining persister tasks, which would ensure the data never arrives.
This brings back spawning the write tasks in the persister, which lets us sail through the writes.
=> bug(layerdb): spawn those writes after all

lib/dal/src/func/authoring/save.rs, lib/dal/tests/integration_test/func/authoring/save_func.rs, lib/dal/tests/integration_test/func/authoring/save_func/attach.rs
This commit contains two fixes that present themselves as the same issue: attaching auth or action funcs to the same variant silently fails. The individual fixes are related in logic changes, but are different overall. Essentially, we were not handling the "existing vs. removed" `SchemaVariantId` logic for the associations properly. Now, we ensure that existing associations are not accidentally dropped.
=> Fix attaching two auth or action funcs to the same variant

dev/BUCK, dev/Tiltfile
When using `buck2 run //dev:up-debug`, the rebaser is now run in release mode regardless. If you really want everything in debug mode, there is another target `buck2 run //dev:up-debug-all`.
This makes migrations take much longer, but recompile times are cut by roughly 1/3 for SDF.
=> chore(rebaser): enable release mode for rebaser in debug build

lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/tests/integration_test/frame.rs
When we execute an attribute's function, we gather up any inferred inputs by walking the graph and finding inferred connections.  
As input sockets share prototypes across components, if there are multiple instances of the component on the graph, where one has an explicit edge drawn and one is supposed to take an inferred input, the existence of prototype arguments as a result of the edge being drawn meant we were never getting inferred inputs for the second component.  
This fixes the logic, such that we look to find inferred inputs only after we haven't found any explicit inputs for that attribute value. 
<div><img src="https://media3.giphy.com/media/l0IykOsxLECVejOzm/giphy.gif?cid=5a38a5a2lrni10a5rlt5y3e435tvu6gibi9hj3invwk89u4n&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" …
=> Fix the (not so) Mysterious Up Frame Bug

app/web/src/api/sdf/dal/component.ts, app/web/src/components/EdgeCard.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, app/web/src/store/status.store.ts, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs
OK—the front end now has all the info required to display sockets correctly through attach & detach. And the conflicts that happen when position and parentage are sent in separate rebases is avoided. This is the way.
=> Component position & parentage need to be sent together for rebaser. Send WsEvents to populate components & edges appropriately.

component/init/configs/service.toml
Change the cache eviction to a setting we can configure using parameter store
=> feat: make cache eviction configurable in init container

app/web/src/components/ActionV2Card.vue, app/web/src/components/ChangesPanel.vue, app/web/src/store/actions.store.ts, app/web/src/store/feature_flags.store.ts, lib/dal-test/src/schemas/test_exclusive_schema_swifty.rs, lib/dal/src/action.rs, lib/dal/src/action/prototype.rs, lib/dal/src/component.rs, lib/dal/src/deprecated_action.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/pkg/import.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/action.rs, lib/rebaser-server/src/change_set_requests/handlers.rs, lib/rebaser-server/src/rebase.rs, lib/sdf-server/src/server/service/action.rs, lib/sdf-server/src/server/service/action/cancel.rs, lib/sdf-server/src/server/service/action/list_actions.rs, lib/sdf-server/src/server/service/action/put_on_hold.rs, lib/sdf-server/src/server/service/change_set.rs, lib/sdf-server/src/server/service/change_set/list_queued_actions.rs, lib/sdf-server/src/server/service/component/get_actions.rs, lib/si-events-rs/src/tenancy.rs
- Close actions by deleting them from the graph
- put actions on hold by updating the status
- send all actions to frontend instead of just enqueued ones
- fix some issues in the actions_v2 tests
=> feat(dal,sdf): Close and Put On hold actions v2 endpoints

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramGroupOverlay.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue
We are experimenting with the removal of the spinner icon for component upgrades and changing the colour and opacity of the component
=> experiment(web): Remove component spinner on update

lib/dal-test/src/lib.rs, lib/dal/src/context.rs, lib/sdf-server/src/server/state.rs
This change removes the automatically derived `Debug` implementation from the `DalContext` type.
At present, this type is incredibly complex, with many complex parts. A developer who wishes to "debug" this type will not be helped by calling `dbg!(ctx)` as the output may grow into the megabytes/gigabytes. Furthermore this type can be accidentally debugged when using a tracing `#[instrument()]` call. For any function or method, the `instrument` macro has an implicit "register all function parameters" behavior, meaning that:
```rust
fn do_something(ctx: &DalContext) {}
```
will create a span called `do_something` with a field called `ctx`. The `ctx` field would contain the contents of the `impl std::fmt::Debug for DalContext` output. Removing the `Debug` implementation on `DalContext` makes …
=> chore(dal): remove `Debug` implementation on `DalContext`

lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/func/execution.rs
We no longer execute all functions for all values on component creation, so we can't assume every value's prototype function has in fact executed.
=> fix(dal): debug view should not assume all values have executed

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs
Replace references was doing too much work. This restores it to almost its original logic, without breaking the multiply parented nodes tests (or any others). I believe the issue fixed by the more complicated logic was actually out of date node indexes, and the extra walks were just duplicating work.
=> fix(dal): do less work in replace references

lib/si-pool-noodle/src/instance/cyclone/firecracker-setup.sh
Whoops. Missed a decryption key reference.
=> fix: remove decryption key referencce in setup script

app/web/src/store/actions.store.ts, lib/dal/src/action.rs, lib/dal/src/action/dependency_graph.rs, lib/dal/src/dependency_graph.rs, lib/sdf-server/src/server/service/action/cancel.rs, lib/sdf-server/src/server/service/action/list_actions.rs, lib/sdf-server/src/server/service/action/put_on_hold.rs, lib/sdf-server/src/server/service/change_set/add_action.rs
Allow on_hold and cancel to be passed multiple ActionIds, hydrate ActionView to include dependents, dependencies, and the list of actions influencing this status.
<div><img src="https://media0.giphy.com/media/26DOMQa5Ib2SmaRZm/giphy.gif?cid=5a38a5a2p4b32t6xmeqpp33mmven2igvg1vr22jfh9b3x6al&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:207px;width:300px"/><br/>via <a href="https://giphy.com/alexanderirl/">Alexander IRL</a> on <a href="https://giphy.com/gifs/alexanderirl-alexander-irl-26DOMQa5Ib2SmaRZm">GIPHY</a></div>
=> First Pass Actions Endpoints

lib/dal/src/change_set.rs, lib/rebaser-server/src/rebase.rs, lib/si-layer-cache/src/db/cache_updates.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/src/event.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/persister.rs, lib/si-layer-cache/src/pg.rs, lib/si-layer-cache/tests/integration_test/db/mod.rs, lib/si-layer-cache/tests/integration_test/db/workspace_snapshot.rs, lib/si-layer-cache/tests/integration_test/disk_cache.rs
This adds workspace snapshot eviction. The layerdb instance that calls evict will delete the entry from memory, disk, and postgres, and send an eviction event to all other layerdb instances. Those instances will then evict from memory and disk.
If we find ourselves adding a lot more eviction style calls, we need to refactor the layered event structure - right now, it always expects a value, and it's theoretically type safe to pass the wrong kind of layeredevent between eviction and writing. (It may be type safe, but it would be very hard to do in practice, since you never assemble these things directly anyway)
=> feat(layerdb): support eviction for workspace snapshots

lib/dal-test/src/expand_helpers.rs, lib/dal/src/change_set.rs, lib/dal/src/workspace.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs
Our logic in `detect_conflicts_and_updates` was incorrect. A big reason for this was that we were not marking changesets as seen in the tests, and we were also not marking forked / new change sets as *seen by themselves*. Since they had no vector clock entry for the change set itself, we could not reliably detect all the times that onto saw to_rebase or to_rebase saw onto.
For example, if I open up change set B, and make changes to it, in the rebase the changes I make will be the "onto" changeset and the not-yet-modified snapshot pointed to by B will be the "to rebase" changeset. Since onto was forked from to_rebase, onto should have a vector clock entry for to rebase (B). But we were not marking the snapshot for B as "seen" by B when we forked B from the base change set. Thus, we had no …
=> fix(dal): use correct logic in detect_conflicts_and_updates

lib/dal/src/workspace_snapshot/graph.rs
If import_subgraph cannot find an equivalent node in to_rebase, it will add the node from onto directly to the graph, and then call update_edge to add the edges. However, update_edge does not recalculate the merkle tree hash, and so the node added via add_node will have the merkle tree hash of node with no children. Add a call to update_merkle_tree_hash at the end of import subgraph to ensure the hash is updated properly.
=> fix(dal): recalculate merkle tree hash in import_subgraph

lib/dal/src/action/prototype.rs, lib/dal/src/deprecated_action/prototype.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs
This PR does the following things: 
- Create both types of action funcs (regardless of flag, this way new actions funcs are on the graph in the v2 flavor for tools prod)
- Only export v1 or v2 action funcs based on the flag (no need to duplicate what's exported as we can import either kind) 
- Fixes a bug with authoring action funcs where changing the action kind results in duplicate prototypes
- prevents users from creating duplicate action func kinds for a given schema variant
=> Support authoring for Actions V2

lib/dal/src/action.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/value.rs, lib/dal/src/change_set.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/context.rs, lib/dal/src/deprecated_action/batch.rs, lib/dal/src/func.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/execute.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/job/queue.rs, lib/dal/src/module.rs, lib/dal/src/schema.rs, lib/dal/src/secret.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs, lib/dal/src/workspace_snapshot/update.rs, lib/rebaser-server/src/change_set_requests/handlers.rs, lib/rebaser-server/src/dvu_debouncer.rs, lib/si-layer-cache/src/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs
Instead of sending the set of values to use as the starting point for calculating the dependent value graph in the DependentValuesUpdate job, place those values on the graph off a new category node. Then, when the job executes them, remove them from the graph.
=> feat(dal,rebaser): store pending dvu values on snapshot

.github/workflows/deploy-service.yml
Adds a basic CDN invalidation when we deploy to our tooling environment, see passing runs here
- https://github.com/systeminit/si/actions/runs/9163133049 (web only)
- https://github.com/systeminit/si/actions/runs/9163157549 (all services)
(Basically it prevents us from needing to remember to do it against tools. Production will be managed via SI directly in actions)
=> feat(ci): invalidation of tools CDN on web refresh

app/web/src/components/AttributesPanel/AttributesPanel.vue, app/web/src/components/AttributesPanel/AttributesPanelItem.vue
Domain and Secrets are props attached to the root and are not set directly, therefore, we were telling a user they had overridden them which was misleading
No icons in place for props directly connected to the root
=> fix(web): Don't show that a root prop has a value overridden

lib/dal/src/func/authoring.rs
We were making the asusmption that executable func types were limited to Attribute funcs when it was infact FuncBackendKind::JsAttribute which includes codegen and qualifications
The logic doesn't need to filter the runs to components on the graph, our DVU enqueue will do that for us as the attribute_value_ids for the prototype will find all the values across all components for that proto
=> fix(dal): Ensure that CodeGen and Qualifications can be executed

lib/dal/src/action.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/dependency_graph.rs, lib/dal/src/workspace_snapshot.rs
While there are AttributeValues for any given Component that are still involved in a DependentValuesUpdate, we want to hold off on dispatching any Actions for those Components. This will let us make sure that the Action will be operating with the most up-to-date data possible in the model.
Now that we're tracking the root nodes for the DependentValuesUpdate graph of AttributeValues to update, we can directly check the Components that are involved in the pending DependentValuesUpdate to see if an Action would operate on an involved Component.
=> Do not dispatch Actions with pending dependent value updates

lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/save.rs, lib/dal/tests/integration_test/func/authoring/save_func/attach.rs
If you have a Create func for an asset type, and we change a func type to be Create, then we want to error on save of the func because it's not allowed to have 2 different funcs of the same type for a schema variant
=> fix(dal): Ensure that we don't allow changing a func to an existing kind

lib/si-events-rs/src/ulid.rs
The derived implementation outputs something like
`Ulid(Ulid(2074909398796474926170115550060854782))`, which is not particularly helpful as we use the `.to_string()` version of the inner Ulid pretty much everywhere, instead of the internal `u128` version. This custom implementation gives us something more useful when comparing to the output pretty much everywhere else:
`Ulid("01HYEF0QQ1QPREN20776XYNEYX")`.
=> Use custom Debug implementation for si_events::ulid::Ulid

lib/dal/src/lib.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/conflict.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/update.rs, lib/si-events-rs/src/ulid.rs
Previously, we were only including the (internal to the graph) `NodeIndex` in the structs for representing conflicts & updates. While this is all that's strictly necessary for performing the updates and (eventually) having SDF report what the conflicts are, having more contextual information such as the node weight kind, and the ID of the node makes things a bit easier for debugging issues when looking at spans & traces.
=> Include node ID and kind in Conflict & Update records

lib/dal/src/action.rs, lib/dal/src/action/prototype.rs, lib/dal/src/attribute/value.rs
Fixed 2 bugs in this PR: 
- an issue with removing delete actions from the graph on successful action run (due to a race in removing all existing actions when removing a component, and the surgical 'remove this action because it finished') 
- when we set attribute values, (for example setting the resource), we were always deleting and recreating the Attribute Prototype. With this change we will first check if there's a component specific attribute prototype and if so, wipe the Arguments and repopulate them. Then, create one if it doesn't already exist. 
<div><img src="https://media1.giphy.com/media/EukOAWKKs0QoW3ps7Z/200.gif?cid=5a38a5a20ofneit8i6drtwh1shbm3p9v7l2ph4w4szu4n2ke&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a …
=> Actions V2 Fixes

lib/dal/tests/integration_test/mod.rs, lib/dal/tests/integration_test/qualifications.rs
This was found during func execution refactoring (#3825) since other tests rely on qualification view generation working.
=> Add regression test for qualification views

lib/dal/src/context.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/vector_clock.rs, lib/rebaser-server/src/dvu_debouncer.rs, lib/si-events-rs/src/workspace_snapshot_address.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/src/layer_cache.rs
EdgeWeights had no "recently seen" vector clocks. This lead to situations where we produced a conflict but should not have, because we only had the "first seen" clock to work with. This adds the recently seen vector clock to the graph. However, this cannot be done without a new version of the WorkspaceSnapshotGraph, so migration logic has been implemented to automatically migrate the snapshot on first read.
=> fix(dal): add recently seen clocks to edge weights

component/grafana/docker-compose.yaml, dev/Tiltfile, dev/datasources/datasources.yml, dev/docker-compose.platform.yml
This adds grafana to our platform stack and allows grafana to automatically use the trace data from Jaeger as a datasource
Hit localhost:3000 in your browser after bring up the tiltstack and log right in!
=> dev: add grafana to our platform stack

dev/Tiltfile, dev/docker-compose.platform.yml
We no longer need AWS credentials to be able to use the system - we can use the AWS_ENDPOINT http://0.0.0.0:4566 and we are good to go!
=> dev: Adding Localstack to our devstack

lib/si-pkg/src/pkg/variant.rs, lib/si-pkg/src/spec/socket.rs, lib/si-pkg/src/spec/variant.rs
We were not merging the socket data when exporting a schema variant and thus dropping all of the export details
=> fix(dal): Ensure that we copy Socket data on export schema variant

lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/workspace.rs, lib/dal/src/workspace_snapshot.rs, lib/rebaser-server/src/dvu_debouncer.rs, lib/sdf-server/src/server/server.rs
Migrates the builtin change set eagerly on boot, and migrates change sets lazily in sdf, when the change set is opened. Instead of the previous strategy of waiting for the rebaser to update the pointer with the snapshot that SDF updated, the first service to read the snapshot moves the change set pointer ahead itself.
=> fix(dal): fix snapshot migration to be more reliable

dev/Tiltfile, dev/datasources/datasources.yml, dev/docker-compose.platform.yml, dev/loki-config/config.yml, dev/promtail-config/config.yml, prelude-si/tilt.bzl
Four main changes:
- Adds a `/tmp/si-logs/<service>` log file when running tilt. Deletes/Recreates this folder just before starting tilt. 
- `tees` the logs of the rust services into those files
- Adds promtail + loki so that the service logs for the rust services can be aggregated in local grafana.
- Sorts out the groupings of the services within the tiltfile
Kudos should be directed to my partner in crime @keeb
=> feat: added log aggregation in grafana for local services

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/conflict.rs, lib/dal/src/workspace_snapshot/edge_weight.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs, lib/dal/src/workspace_snapshot/update.rs, lib/dal/tests/integration_test/rebaser.rs
Previously, the check was not taking into account that while there may be an `Update::NewEdge` that is creating an outgoing edge of the same `EdgeWeightKind` as an existing edge, there might also be an `Update::RemoveEdge` that is removing that pre-existing edge.
We now check to make sure that after all additions & removals of outgoing edges for a specific `EdgeWeightKind`, the net result is that we have no more than a single edge.
The following exclusive edge mismatch conditions have been removed as they are more nuanced than "Node X can have at most 1 of edge kind Y", and will be addressed at a later date.
* `AttributeValue` - `Contain`: `AttributeValue`s can have multiple outgoing `Contain` edges. The restriction on whether or not a specific `Contain` edge is a semantic conflict with …
=> Move check for Conflict::ExclusiveEdgeMismatch to operate on the net changes for the outgoing edges

lib/dal/src/action.rs, lib/dal/src/action/dependency_graph.rs
We need to ensure that things are destroyed in the reverse order of what we would have created them in.
=> Build & use reverse component dependency graph for finding dependencies of Destroy Actions

bin/pinga/src/main.rs, lib/dal/src/func/runner.rs, lib/dal/src/standard_id.rs, lib/si-events-rs/src/func_run.rs, lib/si-events-rs/src/lib.rs
This change adds rather extensive instrumentation coverage around all
function execution types. As this code lives in the DAL, we have access
to data such as change set and workspace identifiers so this is a very
nice location to attach this relevant data.
The largest refactoring step was to take the 2 spawned activities and
split them into explicit types to make future tracking and cancelling
easier.
=> chore(dal): refactor FuncRunner to support instrumentation

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/store/apis.ts, app/web/src/store/change_sets.store.ts, lib/dal-test/src/helpers/change_set.rs, lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/tests/integration_test/rebaser.rs, lib/dal/tests/integration_test/validations.rs, lib/sdf-server/src/server.rs, lib/sdf-server/src/server/service/action.rs, lib/sdf-server/src/server/service/attribute.rs, lib/sdf-server/src/server/service/change_set.rs, lib/sdf-server/src/server/service/component.rs, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/graphviz.rs, lib/sdf-server/src/server/service/module.rs
Return errors when conflicts happen on commit and blocking_commit, transform errors to 409 responses from SDF, basic front end handling of conflicts when trying to apply
=> Return 409 on Conflict!

app/web/src/store/actions.store.ts
Confetti was firing on a changeset when deleting a component that was added in the changeset.
=> Fix: dont confetti unless on head

lib/dal-test/src/lib.rs, lib/rebaser-server/src/change_set_requests.rs, lib/rebaser-server/src/config.rs, lib/rebaser-server/src/dvu_debouncer.rs, lib/rebaser-server/src/server.rs
To prevent DVU debouncer from racing with blocking_commit jobs in tests, increase tick interval in tests to 10000 seconds, so it will never run (unless an individual test takes several hours (unless an individual test takes several hours). This is a stop gap until we implement a way to wait on the completion of the debounced dvus.
=> fix(dal): give dvu 10000 second interval in tests

app/web/src/components/AttributesPanel/AttributesPanel.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_constants.ts, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/component_attributes.store.ts, app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, bin/sdf/src/main.rs, lib/dal/src/component.rs, lib/sdf-server/src/server/service/component/set_type.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs
Also fixes:
- moving children alongside group
- detaching/reparenting multiple components in a single call
=> feat(dal,sdf,web): Make components not grow across parent borders on type change

lib/si-pkg/src/spec/prop.rs, lib/si-pkg/src/spec/variant.rs
=> fix(si-pkg): ensure the asset definition controls identity funcs

app/web/src/store/actions.store.ts, app/web/src/store/change_sets.store.ts, app/web/src/store/components.store.ts, app/web/src/store/feature_flags.store.ts, lib/sdf-server/src/server/service/change_set/add_action.rs, lib/sdf-server/src/server/service/change_set/apply_change_set.rs, lib/sdf-server/src/server/service/component/get_actions.rs, lib/sdf-server/src/server/service/component/refresh.rs
Remove the `v2` request fields on front and back end now that we are post-actions v2 merging.
=> chore(sdf): remove `v2` request fields post-actions v2 merging

docs/LOCALSTACK.md, lib/dal/src/action/prototype.rs, lib/dal/src/func/authoring/save.rs
This commit fixes action associations during `save_func` by hardening the association logic. The fix not only aims to polish action association mutation logic as a whole, but fixes a user-level bug where mutating a refresh action func after a refresh action has failed causes the system to go into an unrecoverable state. There is likely another bug lurking there related to conflicts, updating, rebasing, etc., but this commit, at least, avoids the very bad times.
Additionally, this commit adds a developer document related to using LocalStack for local development with "AWS Credential".
=> Fix action associations when refresh mutating action funcs post failure

lib/dal/src/action/prototype.rs
We were not removing the payload after a successfull delete or a successfull refresh for a resource that has been removed in the real world (aws console for example).
=> Remove resource payload if action function is successfull

app/web/src/components/ComponentCard.vue, app/web/src/store/asset.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/sdf-server/src/server/service/variant/update_variant.rs
The asset pinia store was not updating with the newly generated schema variant id, so subsequent updates were all being done on the old version.
Closes https://linear.app/system-initiative/issue/BUG-275/cannot-upgrade-an-asset-twice
=> fix: refresh asset pinia store with new variant id

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/graph/tests/rebase.rs, lib/rebaser-server/src/rebase.rs
We had created a `ConflictsAndUpdates` struct for use as a convenience in some tests. This promotes it for general use, instead of relying on having to already know what the order of the tuple elements mean with `detect_conflicts_and_updates`.
=> Use ConflictsAndUpdates struct instead of tuple ordering for detect_conflicts_and_updates return value

app/web/src/store/asset.store.ts
Increase func editor save debounce to avoid rebaser conflicts. This is obviously a band aid, but in practice I no longer got any conflicts while editing and I did not lose any changes when navigating around. Verified scenarios pass.
=> fix: increase func editor debouce to avoid rebaser conflicts

lib/dal/src/pkg/export.rs
The value here was always coming back as null, so all modules were exported as `components` regardless of their type. The materialized view is being generated correctly, so switching to that ensures we export the module correctly. The Region module is fixed with this change. 
Closes https://linear.app/system-initiative/issue/BUG-292/region-prop-is-default-to-component-not-frame
=> fix: module export no longer ignores component type

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
=> Fix: show full prop value in modal

app/web/src/components/AssetEditorTabs.vue, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/FuncEditor.vue, app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue, app/web/src/store/func/funcs.store.ts, app/web/src/store/func/types.ts, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/value.rs, lib/dal/src/func.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/func/authoring/save.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs, lib/sdf-server/src/server/service/func.rs, lib/sdf-server/src/server/service/func/get_func_associations.rs
This PR allows for new attribute funcs to be bound to output locations with pre-existing dynamic funcs, including the identity func.
Here's why this is important: you can neither edit nor remove binding for `si:identity` since we do not allow authoring for intrinsics in the frontend. While going down the path to allowing overwriting `si:identity` usages when creating new funcs for a selected asset (schema with a default schema variant), we realized that we could also allow it for all dynamic functions. This requires existing attribute prototype arguments to be drained as well as enqueing all affected attribute values for a dependent values update job.
- Remove duplicate data in create func options for attribute funcs
- Restore and polish tests related to this functionality
- Fix doc …
=> Allow new attribute funcs for output locations with dynamic funcs

lib/dal/examples/snapshot-analyzer/main.rs
Adds a tool for analyzing offline snapshots. Needs to be extended to support the new recently seen vector clocks on edge weights.
To use: download the bytes from the database of the snapshot you want to analyze, then run
`cargo run --example snapshot-analyzer <PATH TO SNAPSHOT FILE>`
=> feat(dal): add snapshot analyzer

lib/dal/src/attribute/value.rs, lib/dal/src/property_editor/values.rs
If a an attribute does not exist, fallback to the prop default or null if one does not exist.
closes https://linear.app/system-initiative/issue/BUG-299/key-pair-default-key-type-is-rsa-but-it-does-not-select-as-default-in
=> fix: ensure default values are set

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue
Never save a dimension lower than the minimum (240px). Never render a dimension lower than the minimum (240px). This ought to prevent any strangeness.
=> BUG-303: no negative sizes

app/web/src/components/toasts/FiveHundredError.vue, app/web/src/components/toasts/MovedToHead.vue, app/web/src/store/apis.ts, app/web/src/store/change_sets.store.ts, app/web/src/store/status.store.ts
Some of the toasts hangout without a timeout. This turns out to be undesirable in regular use. I enabled the timeouts for moving back to head on apply/abandon, conflicts, and 500s. I also removed the OK button as it doesn't seem relevant anymore.
closes https://linear.app/system-initiative/issue/BUG-293/toast-doesnt-get-automatically-dismissed-after-migrating-away-from
=> feat: adding timeouts to all toasts, removing ack buttons where relevant

lib/dal/src/component.rs
We only want to add "- Copy" to the end of a component once, so if you copy a copy it won't endlessly append "- Copy". Copy?
closes https://linear.app/system-initiative/issue/BUG-280/copying-a-component-which-has-been-copied-appends-an-additional-copy
=> feat: only add - Copy once for copied components

app/web/src/components/toasts/FiveHundredError.vue, app/web/src/store/apis.ts
Okay, re-removing the timeout for 500s so we count them as bugs and address them. I also added the error and the route to the toast. My styling here is not so great, so maybe @jobelenus or @wendybujalski can school me at some point.
=> feat: display error message and remove timeout for 500s

app/web/package.json, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/StatusBar/StatusBar.vue, app/web/src/components/StatusBar/StatusBarConflictSummary.vue, app/web/src/components/toasts/Conflict.vue, app/web/src/store/apis.ts, app/web/src/store/components.store.ts, lib/sdf-server/src/server/service/diagram/set_component_position.rs, lib/vue-lib/package.json, lib/vue-lib/src/pinia/pinia_api_tools.ts, pnpm-lock.yaml
Retry set_component_position with most current data for components that are not in flight. No toasts for this endpoint. For most cases, the exact components that are conflicting are also in flight, which is a no-op, and we swallow the conflict.
Implemented generic retry! The bottom bar bounces!
You can see the conflicts and retry:
TADA!
=> Spike: Front end conflicts

lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs, lib/dal/src/workspace_snapshot/vector_clock.rs
This ensures we merge the vector clocks of nodes we are copying from onto into to_rebase, and vice versa. This gets us closer to being able to drop more vector clocks from the graph.
=> fix(dal): ensure we merge the vector clocks of nodes in import subgraph

lib/dal/src/action/prototype.rs, lib/dal/src/diagram.rs, lib/dal/src/workspace_snapshot.rs, lib/sdf-server/src/server/service/component/delete_property_editor_value.rs, lib/sdf-server/src/server/service/component/insert_property_editor_value.rs, lib/sdf-server/src/server/service/component/set_type.rs, lib/sdf-server/src/server/service/component/update_property_editor_value.rs, lib/sdf-server/src/server/service/component/upgrade.rs, lib/sdf-server/src/server/service/diagram/delete_component.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs
Rather than reporting that all Components are `ChangeStatus::Added`, we now detect whether the Component would be added to the base change set, if we were to merge this change set into it. If we are looking at the default change set for a Workspace, then we consider it to not have a base change set, even though it is possible to have one defined.
This does not detect `ChangeStatus::Modified`, or the `ChangeStatus` for Edges yet.
=> Detect ChangeStatus::Added for Components in summary diagram

lib/dal/src/pkg/import.rs, lib/dal/tests/integration_test/mod.rs, lib/dal/tests/integration_test/pkg/mod.rs
Okay, this feels too easy which makes me think I am missing something obvious. Instead of looking at associated schemas, we list all schemas and match by name. If a match is found, we add a schema variant and set it as the default. We also no longer check if the funcs we are importing are marked as a builtin as otherwise we were stomping over the schema variant def func.
=> feat: upgrade instead of duplicate on import

lib/dal/src/diagram.rs, lib/dal/src/workspace_snapshot.rs
* If either if the Components that an edge is connecting the Output & Input sockets of is new, then the edge itself must be new as well.
* If neither of the Components is new, then we check to see if it's a new `AttributePrototypeArgument` (as determined by a `NewEdge` update where the destination is an `AttributePrototypeArgument`).
=> Use Component ChangeStatus, and NewEdge updates to determine if a socket-to-socket connection is new

lib/si-pool-noodle/src/pool_noodle.rs
This will cause pool_noodle to attempt gets more frequently and set the over all timeout to 10 minutes, which seems like more than enough time to finish work :crossed_fingers:
=> fix: increase cyclone_pool get timeout to ten minutes

lib/dal/src/diagram.rs
The logic to drive this flag will come later, but the idea is that when this flag is `true` it is letting the frontend know that this is a "virtual" Component/Edge, and doesn't actually exist in the current change set.
=> Make from_base_change_set flag exist for SummaryDiagramComponent & SummaryDiagramEdge

lib/dal-test/src/helpers.rs, lib/dal-test/src/helpers/change_set.rs, lib/dal-test/src/schemas/schema_helpers.rs, lib/dal-test/src/schemas/test_exclusive_lego_schemas/test_exclusive_schema_lego_large.rs, lib/dal-test/src/schemas/test_exclusive_lego_schemas/test_exclusive_schema_lego_medium.rs, lib/dal-test/src/schemas/test_exclusive_lego_schemas/test_exclusive_schema_lego_small.rs, lib/dal-test/src/schemas/test_exclusive_schema_fallout.rs, lib/dal-test/src/schemas/test_exclusive_schema_swifty.rs, lib/dal/src/component.rs, lib/dal/src/job/definition/action.rs, lib/dal/tests/integration_test/change_set.rs, lib/dal/tests/integration_test/component/get_diff.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/frame/with_actions.rs, lib/dal/tests/integration_test/module.rs, lib/sdf-server/src/server/service/diagram/delete_component.rs
This PR ensures that we do not delete frames if dependent components have resources.
The original fix is from @britmyerss. I mainly rebased the fix, added tests, and provided miscellaneous changes.
- Block the commit when waiting for actions in tests
- Add delete action to fallout test exclusive schema
- Add test helper for fetching resource last synced value
- Remove async requirement from `build_action_func` helper
- Add `Component::view_by_id` and have `Component::view` call it
=> Do not delete frames if dependent components have resources

bin/veritech/scripts/stop.sh, lib/cyclone-core/src/process.rs, lib/si-pool-noodle/src/instance/cyclone/firecracker-setup.sh, lib/si-pool-noodle/src/instance/cyclone/local_uds.rs, lib/si-pool-noodle/src/pool_noodle.rs
This does a handful of things:
* modify stop script to match better and be more specific about cleanup tasks. This *should* allow it to be more reliable
* change some warnings to debug as they are needlessly chatty
* move initial jail cleaning to pool noodle instead of startup script
* capture the output of scripts runs and throw if they do not succeed
* remove the drop channel in favor of another drop arrayqueue. I'm pretty sure that there were issues in receiving drop messages causing us to not handle cleanup correctly. This is the likely cause of the pool leakage
* bubble up errors when interacting with the arrayqueues, just in case
* keep track of both the number of active and dropped instances
* emit pool stats on debug so we can better understand issues where we think the pool is in …
=> fix: flakiness in firecracker jail management

app/web/src/components/Debug/ComponentDebugDetails.vue
Due to how ... involved the layout of debug is, I went old school. Search the HTML and add a yellow highlight to what we find. Scroll to the first find.
=> Delighter: ability to search the debug view

bin/si-generator/src/render.ts, bin/si-generator/src/resource_generator.ts, bin/si-generator/src/run.ts, bin/si-generator/src/templates/refreshMain.ts
If a resource has been removed directly in AWS, we need to ensure that our refresh funcs check for specific 404s that we know mean it's been deleted so we can remove the resource locally
We can now do that:
```
si-generator  refresh eks describe-cluster --input clusterName:properties.resource.payload.clusterName --missingResource "ResourceNotFoundException" --output 'cluster'
```
This will print the following check:
```
if (child.exitCode !== 0) {
const payload = _.get(component, 'properties.resource.payload');
if (child.stderr.includes("ResourceNotFoundException") {
return {
status: "error",
message: `Refresh error; resource not found; (ResourceNotFoundException)`,
}
}
```
That will remove the resource from the system. We can pass multiple `missingResource` options and each of them will …
=> feat(si-generator): Add support for setting missingResource refresh settings

bin/veritech/scripts/prepare_jailer.sh, bin/veritech/scripts/userdata.sh, prelude-si/rootfs/rootfs_build.sh
This allows us to push arbitrary scripts into Firecracker Jails that will be executed just before Cyclone starts. The use case for this today is to push AWS credentials into a known location so we can use them to assume roles across accounts.
=> feat: push scripts file into cyclone jails

lib/dal/src/func.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/attribute/prototype.rs, lib/dal/tests/integration_test/func/argument.rs, lib/dal/tests/integration_test/func/associations.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs, lib/dal/tests/integration_test/func/authoring/save_and_exec.rs, lib/dal/tests/integration_test/func/authoring/save_func.rs, lib/dal/tests/integration_test/func/authoring/save_func/attach.rs, lib/dal/tests/integration_test/func/authoring/save_func/detach.rs, lib/dal/tests/integration_test/func/authoring/test_execute.rs, lib/dal/tests/integration_test/secret.rs, lib/dal/tests/integration_test/secret/with_schema_variant_authoring.rs
This PR adds a regression test for attaching existing code gen funcs to new schema variants. Specifically, the "attaching" step works, but when the "Secrets" input is added, sometimes we are unable to regenerate the variant due the following error: `pkg error: Can't convert identity to LeafInputLocation`.
The bug appears to no longer exist on main, but the test should still be valuable in catching a future regression.
- Rename `find_by_name` to `find_id_by_name` when looking for funcs by name
=> Add regression test for existing code gen funcs and new variants

lib/dal/src/func/runner.rs, lib/dal/src/input_sources.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret/definition_view.rs, lib/dal/tests/integration_test/schema/variant/view.rs
The `SchemaVariant::list_ids` func was doing just that, listing all of the variant ids, when we really want the latest default. This was causing inconsistency in api returns as we would often smash results into a hashmap and the default could have been stepped on in the process.
=> fix: list variant ids should only return default ids

app/web/src/components/modules/ModuleDisplay.vue, app/web/src/components/modules/ModuleListPanel.vue, app/web/src/store/module.store.ts
This fixes BUG-358 in linear, however, there is still more work to be done. The list is now out of sync with the `search modules` box because the search parameter is not wired all of the way through to do the filtering
I've also added a call  to LOAD_LOCAL_MODULES on built in promotion because that list will also need to be refreshed appropriately.
@jobelenus this area seems rife with these types of issues
=> Fix BUG-358

lib/dal/src/pkg/export.rs
If we do not have an AV setting the component type we should default to whatever is set in the variant, not `component`.
=> fix: have export get the type from the variant being exported

app/web/.env, app/web/Dockerfile, app/web/docker-entrypoint.sh, app/web/src/main.ts, app/web/src/shared/dynamicEnvVars.ts, app/web/src/vite-env.d.ts, app/web/vite.config.ts
Vite forces you to use env vars for config and then also forces you to set them at build time. This is some hot, hot garbage. This library allows us to pull in arbitrary env vars. We also then do some string replacement when starting the container so we can have dynamic config in the different environments.
=> feat: allow setting arbitrary runtime env vars in the web container

app/web/src/components/FuncEditor/AttributeBindings.vue, app/web/src/components/FuncEditor/AttributeBindingsModal.vue, app/web/src/store/asset.store.ts, lib/dal/src/func.rs, lib/dal/src/func/argument.rs, lib/dal/src/func/summary.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/export.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant/authoring.rs, lib/sdf-server/src/server/service/variant.rs, lib/sdf-server/src/server/service/variant/clone_variant.rs, lib/sdf-server/src/server/service/variant/get_variant.rs, lib/sdf-server/src/server/service/variant/update_variant.rs
This PR contains a bunch of changes related to authoring schemas (assets), schema variants (asset versions) and funcs involved when authoring them. Primarily, this commit is focused on showing all funcs for all versions of an asset to ensure the user has all the data they need for authoring.
When you regenerate an asset when there are components on the diagram using it, a new version of the asset is created (a new schema variant). As a result, the default schema variant changes for the asset (schema). If you were to edit the output location or change anything that would affect the bindings the asset, upon regeneration, you could lose access
to the func.
_Here's what we do to solve that problem, among others that are downstream to that problem:_
- List ALL funcs in existence when asked, …
=> Show all funcs for all versions of an asset and do not clone funcs on regeneration

component/toolbox/BUCK, component/toolbox/Dockerfile, component/toolbox/awsi.sh, component/toolbox/scripts/ssm
This creates a little helper container we can use to ease the burden of troubleshooting issues in tools/prod. This is the skeleton for the functionality plus a script for ssh'ing into instances in AWS. You can invoke it via `./components/toolbox/awsi.sh ssm -p [aws_profile] -r [aws_region]`. It will give you list of available instances you can shell into and then open up a session with whatever box you select.
=> feat: add toolbox for ops helper work

lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_conflicts_and_updates.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
If an ordered node's children are replaced, and the RemoveEdge operations come before the ReplaceSubgraph update for the ordering node, the ordering node's vector clock write will have been incremented *during the update*, which leads us to pick the wrong node, with the result that the ordering node now has incorrect children in its order property. This fixes that by not incrementing the vector clock write for the ordering node when processing a RemoveEdge update (and *only* when processing a RemoveEdge update).
Discovery of this bug came from the VectorClockId tuple work, but this bug exists on main.
=> fix(dal): pick correct ordering node in ReplaceSubgraph

app/web/src/store/func/funcs.store.ts, app/web/src/store/func/types.ts, lib/dal/src/input_sources.rs
Without this, people can set root or root/secrets - which is the dangerous props people can set
We now made it:
/root/resource_value/*
/root/domain/*
/root/si/color
=> fix(dal, web): Ensure attribute functions can't set incorrect output locations

lib/dal/src/attribute/value.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/authoring/save.rs, lib/dal/tests/integration.rs
Remove existing attribute prototypes when creating a new one or updating an existing one. This prevents us from having duplicate attribute prototypes for Props/Sockets that the user has manually attached attribute funcs for, and therefore ensures we run the correct, most recently configured one, with no lingering prototypes to the identity func. 
I added some traces to help us find resolution more quickly for other issues and fixed up a couple doc comments too.
<div><img src="https://media1.giphy.com/media/FuZjDL4fZ3vDz9E6EK/giphy.gif?cid=5a38a5a269kfc2sz7gbscidv7g3se7unhd2wwjl8kzvbj8o1&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/starz/">STARZ</a> on <a …
=> Fix Attribute Func Attachment

app/web/src/store/asset.store.ts
We are continually reloading the page when this WsEvent fires. The variant autosaves every few seconds so we don't need to reload everything every few seconds
=> fix(web): Remove Asset.Store SchemaVariantSaved Event

app/web/src/components/AssetDetailsPanel.vue
We need to be able to regenerate the asset at any time
=> fix(web): Remove the disabled state of the regenerate asset button

app/web/src/components/AssetFuncAttachModal.vue
We need to reset the output location when we have pop the modal for attaching new attribute funcs
=> fix(web): Reset Attribute Func Attachment between attribute funcs

bin/veritech/scripts/prepare_jailer.sh, lib/si-pool-noodle/src/errors.rs, lib/si-pool-noodle/src/lib.rs, lib/si-pool-noodle/src/pool_noodle.rs, lib/veritech-client/tests/integration.rs, lib/veritech-server/src/config.rs, lib/veritech-server/src/server.rs, prelude-si/rootfs/rootfs_build.sh
This runs a quick loop of whatever instance type is selected for Cyclone when starting Veritech. The idea is to catch faulty jail implementations at startup so we can report the service as unhealthy if it can't run functions
=> feat: health check pool on Veritech startup

component/toolbox/Dockerfile, component/toolbox/README.md, component/toolbox/scripts/info, component/toolbox/scripts/ssm
Adds a readme and a helper script to the toolbox. You can invoke it via 
```bash
./awsci.sh info
```
Like so
=> feat: add readme and helper to toolbox

app/web/src/api/sdf/dal/workspace.ts, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, app/web/src/store/workspaces.store.ts, bin/auth-api/prisma/migrations/20240620202654_workspace_token/migration.sql, bin/auth-api/prisma/schema.prisma, bin/auth-api/src/services/workspaces.service.ts, lib/dal/src/migrations/U3012__add_token_to_workspace.sql, lib/dal/src/workspace.rs, lib/sdf-server/src/server/service/session/auth_connect.rs
This allows the auth-api to generate new ulid on create -- the unique workspace token. The idea here is that we want some workspace-specific value to exist that can act as a protected value. It can then be used to integrate with things like AWS assume-role to identity a workspace. We should not use the existing workspace ID for this as it lives in the URL, so is trivial to leak. 
Caveats:
1. This does not populate the existing workspaces in the auth-api with new tokens. Prisma does not provide a way to do this via migrations for ULIDs (that I could find)
2. This does not does populate the existing workspaces in the SI database either. However, if a workspace is retrieved from the auth-api and it contains a token, the workspace record will be updated
So, if we write a script to update the …
=> feat: add workspace token ULID

bin/auth-api/Dockerfile
Cover jank with jank, we are hard pinning the version because it seems like the ARG commands are not passing the version correctly and we've just gotten lucky so far...
=> fix: auth-api pnpm version in dockerfile

lib/dal/src/component/qualification.rs, lib/dal/src/func/authoring/create.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/src/schema/variant/leaves.rs, lib/dal/tests/integration_test/schema/variant/authoring/update_variant.rs
This PR fixes leaf function mutations for existing components by creating attribute values when needed. Specifically, this commit focuses on mutations at the schema variant level found when regenerated assets with components in existence.
It contains an integration test used for testing leaf function additions intermingled with variant regenerations with existing components on the diagram. The test also looks at the raw attribute prototypes alongside the qualifications views themselves (`update_variant_with_leaf_func`).
- Polish functions related to leaf upsertion (i.e. finding attribute
values, input calculation logic, component listing for schema
variants, tracing touchups and more)
- Remove unused component-related leaf information for leaf upsertion
methods
- Add integration test for …
=> Fix leaf function mutations for existing components

bin/lang-js/src/sandbox/exec.ts
This stops execa from waiting for stdin, so we no longer just hang forever if someone writes a function that does something cool like `cat` with no input.
This also moves the execaOptions out of siExec because letting people configure this inside of functions seems rife for mischief.
=> fix: ignore stdin in execa

app/web/src/store/asset.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/schema/variant.rs, lib/sdf-server/src/server/service/variant/create_variant.rs
When on HEAD and creating a new variant, we were trying to load the variant on HEAD. This returns the correct information in the WsEvent to update the store and waiting for the new changeset URL to be set before trying to load the variant
=> fix(web, sdf, dal): Return created variant details from create_variant

lib/dal/src/component.rs, lib/dal/src/component/code.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs
When we author a new code gen or qualification, we find all existing components created with that schema variant and add the func to them. When doing this, we were incorrectly mapping new code gen functions to the qualification attribute value, now we find the correct attribute value for either the code gen or qualification attribute value and create the new attribute value for the new func there!
Also added a test!
Note: This is broken on upgrade until we fix BUG-405, meaning if you have a component on the diagram, regenerate the schema variant, add a new qualification or code gen function to the new schema variant, when you upgrade the component, the new qualification/code gen func won't be attached. Zack is fixing this in 405
<div><img …
=> Ensure we upsert leaf funcs to the correct attribute value for existing components

lib/dal-test/src/test_exclusive_schemas/dummy_secret.rs, lib/dal-test/src/test_exclusive_schemas/fallout.rs, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/prop.rs, lib/dal/src/secret.rs, lib/si-pkg/src/spec/attribute_value.rs
Walk the attribute value tree of the new component and find the values in the old component that match in the new, setting them when appropriate. Also detect if component specific prototypes were configured on the old component, and attempt to configure them here.
Closes BUG-405
=> fix(dal): calc prototypes and values correctly on component upgrade

lib/dal-test/src/test_exclusive_schemas/dummy_secret.rs, lib/dal-test/src/test_exclusive_schemas/fallout.rs, lib/dal/src/context.rs, lib/dal/src/func/runner.rs, lib/dal/tests/integration_test/secret/with_actions.rs
When we go gather the before funcs we momentarily decrypt them before re-encrypting to pass them to Veritech. Now, we will inject the workspace token as an arg into the before func before re-encrpyting. This means:
* workspace token will be available on all secrets as `secret.WorkspaceToken`
* it will be correctly redacted as it is just another arg on the before_func
This method is probably not ideal for when we want to add more values, but I think that there is a pretty large conversation around the most right way to do this that we can save for a later date.
The AWS Cred will need to remove the WorkspaceId and use this instead. Here's it working:
Something about the test setup meant that I needed to manually set the token before the functions that would use it check for it. Given that …
=> feat: implicitly pass workspace token to all secrets

bin/veritech/BUCK, lib/si-firecracker/BUCK, lib/si-firecracker/src/errors.rs, lib/si-firecracker/src/firecracker.rs, lib/si-firecracker/src/scripts/firecracker-setup.sh, lib/si-firecracker/src/scripts/prepare_jailer.sh, lib/si-firecracker/src/scripts/stop.sh
This moves the firecracker scripts into the firecracker library so we no longer go up to github to get them. This means you can make changes to them in a branch without having to muck with having to change which branch they are pulled from in the repo. Also some refactoring as I learn more about how to handle errors correctly.
=> chore: firecracker scripts as bytes instead of from repo

.github/workflows/deploy-on-main.yml, .github/workflows/deploy-service.yml, .github/workflows/deploy-stack.yml
The current behavior for deploying the ASG-based services is to fail if an existing refresh is in progress. This will now check and wait for that refresh to finish before continuing so we can not worrying about merges to main in rapid succession that run these workflows. Speaking of, this also adds a workflow to automatically deploy to tools prod on merges to main.
=> feat: poll existing instance refresh on deploy

.github/workflows/deploy-stack.yml
Apparently `workflow_call` requires the `inputs` context instead of the `github.event.inputs` context. Luckily, this context works for both types.
https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/
=> fix: inputs for workflow_call are available in a different context

bin/lang-js/src/asset_builder.ts, lib/dal/src/func/authoring/data/ts_types/asset_types_with_secrets.d.ts
This will add the specified connection annotation to the generated output socket
```
function main() {
const credential = new SecretDefinitionBuilder()
.setName("GHCR Credential")
.setConnectionAnnotation("Docker Hub Credential")
.addProp(
new PropBuilder()
.setName("Username")
.setKind("string")
.setWidget(
new PropWidgetDefinitionBuilder()
.setKind("password")
.build()
).build())
.build();
return new AssetBuilder()
.defineSecret(credential)
.build()
}
```
=> fix(lang-js): Add support for connection annotations to SecretDefinitions

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetListPanel.vue, app/web/src/components/AssetNameModal.vue, app/web/src/store/asset.store.ts, lib/dal/src/schema.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/src/schema/variant/json.rs, lib/dal/tests/integration_test/component/upgrade.rs, lib/dal/tests/integration_test/func/authoring/create_func.rs, lib/dal/tests/integration_test/pkg/mod.rs, lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs, lib/dal/tests/integration_test/schema/variant/authoring/create_variant.rs, lib/dal/tests/integration_test/schema/variant/authoring/save_variant.rs, lib/dal/tests/integration_test/schema/variant/authoring/update_variant.rs, lib/dal/tests/integration_test/secret/with_schema_variant_authoring.rs, lib/sdf-server/src/server/service/variant/clone_variant.rs, lib/sdf-server/src/server/service/variant/create_variant.rs, lib/vue-lib/src/pinia/pinia_api_tools.ts
This is in anticipation of making the schema name immutable after creation.
=> Clone or New Asset: provide an initial schema name in a modal

.github/workflows/crons.yml, .github/workflows/deploy-on-main.yml, .github/workflows/e2e-validation.yml
We're going to start running the cypress jobs on a 15 minute timer. Since they are now also running on merge after we deploy tools-prod, we want to cancel in-progress cypress jobs because they will fail anyways when we deploy. If a new cypress job is started while we are still deploying, it will queue up and wait it's turn.
=> feat: cypress on cron, cancel on deploy

.github/workflows/crons.yml, .github/workflows/deploy-on-main.yml, .github/workflows/deploy-stack.yml
Move cypress run into deploy job so it is always run against the environment we just deployed
=> feat: always run cypress after a deploy

lib/ts-lib/src/connection-annotations.ts
We weren't parsing connection annotations correctly (we had all the logic, we just weren't calling it.)
This fixes that.
=> bug(web): fix connection annotations

app/web/src/components/AttributesPanel/AttributesPanelItem.vue, lib/dal-test/src/helpers.rs, lib/dal/src/schema/variant/json.rs, lib/dal/src/validation.rs, lib/dal/tests/integration_test/validations.rs
This PR retains validations from asset funcs upon regeneration. Currently, we successfully execute the asset func when regenerating an asset. We see the validations in the resulting definition. However, when exporting using the definition and converting it into a spec, the validations are dropped. This PR ensures that are no longer dropped.
This PR also contains minor changes to how validations appear in the attribute panel. The existing classes relied on colors outside of our asset panel and neither matcher our light nor our dark theme. While the current colors are not likely the final ones, they are closer to our design language (even if only a little).
This will require all affected assets to be regenerated and re-exported, as applicable.
=> Retain validations from asset func on regeneration

bin/veritech/scripts/userdata.sh, component/deploy/userdata
Dockerhub is a curse on the land. SDF failed to start correctly because we use docker to build the config file and the pull was rate limited. I'm also going to change the healthcheck so the LB will kill the instance if it is unresponsive. We need better healthchecks for the other services, though.
=> chore: update userdata example to include dockerhub login

lib/dal/src/pkg/export.rs
While authoring, you could create 10s of versions of a variant. Our current export code would include them all in the exported module.
We only want to export the default schema variant as that's the most "stable". In the future this will be changed to be the latest locked schema variant
=> fix(dal): ensure that we only export the default schema variant

.github/workflows/e2e-validation.yml, app/web/cypress.config.ts
The Cypress Cloud free tier limits are too low for how we want to use it. I don't think we need it for automated runs. This PR give us parallelization by test_dir, so we test in the same way as we split the tests. It also changes the retry mechanism to be controlled by Cypress itself so it can retry individual tests failures instead of entire suites.
=> chore: remove cypress cloud parallelization

lib/dal/src/secret/definition_view.rs
This PR ensures the secret field order is correct by using ordered props. Assets may need to be regenerated from other changes (e.g. props can only be ordered on recent main) in order to see this effect.
=> Ensure secret field order is correct

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetNameModal.vue, app/web/src/components/AttributesPanel/AttributesPanelItem.vue
=> fix(web) - a few VERY minor UI fixes

lib/dal/src/pkg/export.rs, lib/si-pkg/src/pkg/variant.rs
A bit of code left over from the old system (where default values were the attribute value for a prop at the schema variant context) was grabbing the first attribute value and making it the default for props if a component existed on export. This fixes it and fixes the export of default values for strings.
Default values now can only be defined in the asset spec.
=> fix(dal): export default values correctly

app/web/src/api/sdf/dal/component.ts, app/web/src/components/ComponentCard.vue, app/web/src/components/DetailsPanelTimestamps.vue, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/components/ModelingView/RestoreSelectionModal.vue, app/web/src/store/components.store.ts, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/tests/integration_test/diagram.rs, lib/dal/tests/integration_test/mod.rs, lib/sdf-server/src/server/service/diagram/remove_delete_intent.rs
We now look at the series of updates that would be applied if we were to merge a change set into its base, and include "virtual" summary diagram component entries for any Components that would be removed and that only exist in the base change set. These virtual entries will have `from_base_change_set` set to true to signal that they don't actually exist in the snapshot for the change set.
This allows us to "undelete"/"restore" a Component from the base change set if we've removed it from the current change set, and change our mind.
Rather than creating a new API endpoint & method for attempting to restore a `Component -> Component` (`Output Socket -> Input Socket`) connection, `Component::connect` (and by extension `diagram/create_connection`) will now check the base change set to see if …
=> Restore components & edges from base change set

app/web/src/components/AssetListPanel.vue, app/web/src/components/QualificationViewerSingle.vue, app/web/src/utils/typescriptLinter.ts
* When showing the output of a qualification, we wrap it in a <pre> so that you can see newlines be rendered.
* We want to always show the contribute button, because otherwise we can never see it.
* Typescript is now configured to be much more relaxed, and to have an 'any' type for `_` while we figure out how to get the types for lodash loaded up.
=> Typescript chill-out, Qualification display fix, contribution always on

.github/workflows/deploy-on-main.yml
We need to be in flux during the authoring stability project
=> chore(si): Turn off auto-deploy to tools-prod

bin/lang-js/src/asset_builder.ts, lib/dal-test/src/helpers.rs, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/debug.rs, lib/dal/src/code_view.rs, lib/dal/src/component.rs, lib/dal/src/func/runner.rs, lib/dal/src/job/definition/compute_validation.rs, lib/dal/src/pkg/export.rs, lib/dal/src/prop.rs, lib/dal/src/property_editor/values.rs, lib/dal/src/qualification.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret/definition_view.rs, lib/dal/src/socket/debug.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/connection.rs, lib/dal/tests/integration_test/dependent_values_update.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/property_editor.rs, lib/dal/tests/integration_test/schema/variant.rs, lib/dal/tests/integration_test/secret.rs, lib/dal/tests/integration_test/secret/with_actions.rs
This PR allows secrets to depend on secrets by ensuring before funcs are ordered. The ordering is determined by the underlying dependency graph based on the target component's ancestry, regardless of component type (e.g. "frame" or "component").
This PR also changes the asset builder to only allow one output socket for secret-defining assets as well as allows more than one secret prop (needed for secrets dependent on secrets).
- Add ability to find a source component by a given input socket match where the input socket has an arity of one
- Make secret errors related to widgets more clear in func runner
- Find auth funcs for a given secret child prop id based on output socket rather than secret definition props (related to the asset builder change)
- Add ability to list default secret …
=> Allow secrets to depend on secrets with before func ordering

.github/workflows/labeler.yml
This labeler update includes a breaking change that needs to be staged out in a specific way. Rolling this back so I can make that change.
=> chore: temporary rollback of labeler

.github/workflows/pr.yml
The only way to block merges using the queue is to require status checks from jobs on the branch. However, we do not want to run `merge-queue` by default on every push on a PR, only when we actually go to merge. Adding this dummy workflow allows us to add the status check for PRs and for Buildkite to do the real thing for the merge queue (I think).
This should fail as I intentionally broke one of the tests to validate the failure.
=> chore: merge queue dummy workflow

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/assets/static/editor_typescript.txt, app/web/src/components/AttributesPanel/AttributesPanel.vue, app/web/src/components/AttributesPanel/AttributesPanelItem.vue, bin/lang-js/src/asset_builder.ts, lib/dal/src/func/authoring/data/ts_types/asset_types_with_secrets.d.ts, lib/dal/src/func/runner.rs, lib/dal/src/property_editor.rs, lib/dal/src/property_editor/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/func/authoring/binding/attribute.rs
This PR polishes the UX around secrets depending on secrets.
This commit allows connection annotations for input sockets corresponding to `/root/secrets/<secret>` props. This allows components to accept multiple secret shapes for a single input socket.
This commit does the following:
1. Shows the real definition for a populated secret rather than the secret for its kind (e.g. show `ECR Credential / <name>` and not `Docker Hub Credential / <name>` on a `Docker Image` component) since we now have connection annotations for input sockets and output sockets for secrets.
2. Blocks populating secrets outside of secret-defining components. This ensures that secrets are only selected at origin, which reduces papercuts when selecting secrets that may depend on secrets. In addition, it narrows the …
=> Polish UX around secrets depending on secrets

lib/dal/src/action/prototype.rs, lib/dal/src/func/associations.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/binding.rs, lib/dal/src/func/binding/action.rs, lib/dal/src/func/binding/leaf.rs, lib/dal/src/schema/variant.rs
This PR ensures detaching leaf funcs from schema variants also detaches them from components using the schema variant (unless overridden). This works by removing map entry attribute values that use the prototype being deleted (i.e. detaching logic).
This PR also fixes action func attachment showing the wrong kind by fixing the conversion from the events type to the real type.
=> Fix leaf func detachment and action func attachment

app/docs/.env, app/docs/BUCK, app/docs/package.json, app/docs/src/.vitepress/config.ts, pnpm-lock.yaml
Run buck2 run //app/docs:dev to start the app if outside of tilt - you can set DEV_HOST and DEV_PORT to override the .env file
=> fix(docs): Ensure docs works with DEV_HOST and DEV_PORT

lib/dal/src/func/binding.rs, lib/sdf-server/src/server/service/v2/func/binding/create_binding.rs, lib/si-frontend-types-rs/src/func.rs
When creating a new auth function, the front end doesn't send us a func id (because it doesn't exist yet!) so I just needed to update the front end type to accept an `Option<FuncId>` and make sure that when creating a new binding for an existing Auth Func, the `FuncId` exists
=> Fix create new auth function

app/web/.env, lib/dal/src/layer_db_types/content_types.rs, lib/dal/src/module.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/pkg/mod.rs, lib/module-index-client/src/client.rs, lib/module-index-client/src/lib.rs, lib/module-index-client/src/types.rs, lib/module-index-server/src/migrations/U0008__add_indexes.sql, lib/module-index-server/src/models/si_module.rs, lib/module-index-server/src/routes/list_builtins_route.rs, lib/module-index-server/src/routes/list_modules_route.rs, lib/module-index-server/src/routes/promote_builtin_route.rs, lib/module-index-server/src/routes/reject_module_route.rs, lib/module-index-server/src/routes/upsert_module_route.rs, lib/module-index-server/src/routes/upsert_workspace_route.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/service/module/export_module.rs, lib/sdf-server/src/server/service/module/install_module.rs
Installing an asset that is a variant of an existing asset will use the module "schema id" (along with the hashes, if the schema id is not available) to try and install the asset as a variant of the existing schema.
=> feat(dal,sdf,module-index-server): use schema id when importing

.github/workflows/deploy-module-index.yml
This will simply re-roll the module-index ecs service using the current deployed image tag, most likely 'stable'. It does not build the container image anymore, so we'll need to go figure that bit out separately.
=> chore: modify module index deploy to update shared cluster

lib/dal/src/pkg/import.rs, lib/dal/src/schema/variant/authoring.rs
It never returned an option, and just ran the code like normal when using an already imported sv
A similar thing on func import  is what allowed the bug  fixed in #4104 to happen, so I'm fixing this here before we shoot ourselves in the foot again
=> chore: Clean up import schema variant

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetEditor.vue, app/web/src/components/CodeEditor.vue, app/web/src/components/FuncEditor/FuncEditor.vue, app/web/src/store/asset.store.ts, app/web/src/store/func/funcs.store.ts, lib/sdf-server/src/server/service/variant/regenerate_variant.rs
We went down the rabbit hole on all the things that were causing code from one asset to either be presented, or saved, OVER another asset. (And the duplicate code for a bonus).
1. `Regenerate` should not accept the code body. (It had the code body because there could be a debouncing "save code" in waiting or in flight, and a user could hit regenerate and the backend would not have the most up to date code. It could either end up with the wrong result OR conflict—both bad.
2. As a result of No.1 you cannot press `Regenerate` while code debounce is in effect.
3. On unmount we emit'd a "change" event that resulted in a debounced save call. Now that call is NOT debounced, it happens immediately. Same for "onBlur". The only save that is debounced is typey-typey.
4. We only emit "change" on …
=> Resolving editor pain

lib/dal/src/func/authoring.rs, lib/dal/src/func/binding/attribute.rs
One other change here to discuss Monday: 
- When resetting an attribute prototype, if the prototype is for a Prop, default to the unset intrinisic func
- If it's for an output socket, reset to the identity func, so that regenerate can re-set the prototype to a value from if it's defined in the asset definition func
Update: discussed and we are not going to do this as it prevents that prop from ever having a default value again (under current constraints)
=> Enqueue DVU when modifying or creating attribute func bindings for variants with existing components

bin/auth-api/src/lib/redis.ts
I'm not entirely sure, but I assume that the more recent version of redis we are using now requires a tls config. I have verified that changing this allows us to connect to the new redis instance.
=> fix: add tls config to redis for auth-api

app/web/src/components/AssetEditor.vue, app/web/src/components/FuncEditor/FuncEditor.vue
On slower connections we were seeing old code in the editor, after a new code was selected, until it finally loaded and it all snapped into place.
This was happening because changing props does not re-run a component's setup code. Instantiating `loadFuncDetailsReq` with `props.funcId`means that as props change, the request watcher *does not update*. Basically, as the `props.funcId` changed from 123 -> 456, the `loadFuncDetailsReq` only ever observed the API request for funcId 123.
Instead, use a watcher to re-assign the value each time. This ensures that we get a new loading state when user selects another function.
=> Fix: always show code editor loading state when switching between funcs

app/web/src/components/CodeEditor.vue
I'm not sure what to make of Vue mount/unmounting behavior. This is what I observed:
1. start with func A
2. select func B
3. see the props change in the CodeEditor component to func B
4. see UNMOUNT called
I don't understand why unmount would be called AFTER the props changed—I would expect it to be BEFORE (e.g. the "old" state of the component). So... we don't save on unmount anymore now, because its the wrong values.
=> Fix to overwriting code

lib/sdf-server/src/server/routes.rs
We weren't quite permissive enough about CORs last time around. This ensures that all methods/headers/creds can pass appropriately, but we still only accept from our subdomains
=> feat: more details to the cors bits we allow

app/web/src/api/sdf/dal/schema.ts, app/web/src/components/AssetCard.vue, app/web/src/components/AssetFuncListPanel.vue, app/web/src/components/AssetListItem.vue, app/web/src/components/AssetListPanel.vue, app/web/src/store/asset.store.ts, bin/module-index/README.md, lib/dal/src/schema/variant.rs, lib/module-index-client/src/client.rs, lib/module-index-client/src/types.rs, lib/module-index-server/BUCK, lib/module-index-server/src/models/si_module.rs, lib/module-index-server/src/queries/list_latest_modules.sql, lib/module-index-server/src/routes.rs, lib/module-index-server/src/routes/list_latest_modules_route.rs, lib/sdf-server/src/server/service/v2/variant.rs, lib/si-frontend-types-rs/src/schema_variant.rs
This PR shows that an asset can be updated. This functionality is achieved by asking the module index what the latest module is for the corresponding local hash.
Why not use the `SchemaId` instead of the local hash? Existing SI deployments may not have the `SchemaId` in their local modules since the module-to-schema enforcement and corresponding table columns were only put in place recently.
One consideration for the future: we may want the "can I update?" logic to be moved into a different route in order to not hold up listing variants. For now, the determination logic is wrapper in an infallible wrapper in case something goes wrong, but that does not prevent poor performance.
- Ensure `app/web` no longer mutates the `canUpdate` field for `SchemaVariants`
- Add `README` for …
=> Show that assets can be updated

app/web/src/components/CodeEditor.vue
We are going to redesign that multi-player code editor. To limit the issues the current subsystem is creating, we are going to turn it off
This will be re-incarnated in a new format!
We lose the autoformat as part of this but that can come back
=> fix(web): Remove the Multiplayer CodeEditor

app/web/cypress/e2e/authentication/login.cy.ts, app/web/cypress/e2e/authentication/logout.cy.ts, app/web/cypress/e2e/modelling-functionality/create-component.cy.ts, app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts, app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts, app/web/cypress/e2e/web-functionality/get-summary.cy.ts, app/web/cypress/support/auth-provider-commands/auth0.ts
We're getting erroneuous `404`s when these tests are running that seem to have to do with the redirect and hosting on S3. These 404s do not appear when using the app in practice. I'm ignoring them here because in every case we go on to validate actual behavior after we visit.
=> fix: ignore erroneous 404s in cypress tests

lib/sdf-server/src/server/service/v2/func.rs
<div><img src="https://media0.giphy.com/media/lqFHf5fYMSuKcSOJph/200.gif?cid=5a38a5a22uc92q44b3bismhvlj898yeur9245muj762e3d7v&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a href="https://giphy.com/quickpage/">Quickpage</a> on <a href="https://giphy.com/gifs/quickpage-404-page-qewy-lqFHf5fYMSuKcSOJph">GIPHY</a></div>
=> fix(sdf): return 404 if the func is not found in the requested changeset

lib/dal-test/src/helpers/change_set.rs, lib/dal/src/pkg/export.rs, lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/src/schema/variant/json.rs, lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs, lib/dal/tests/integration_test/schema/variant/authoring/save_variant.rs, lib/si-pkg/src/node/schema_variant.rs, lib/si-pkg/src/pkg/variant.rs, lib/si-pkg/src/spec/variant.rs
This PR does a few things: 
- Add description to the Schema Variant package spec so we import/export it correctly
- Ensure that the newly unlocked variant immediately has the updated version
- Versions are formatted to include the nanosecond when it was generated (previously seconds)
- Add a test for the open change set, unlock, make changes, apply to head, open new change set, unlock again
<div><img src="https://media4.giphy.com/media/SfzHzeAQte2sl2RfK2/200.gif?cid=5a38a5a2f8v56nj1w9r1i5rjudjvmagzn49qq8rr0ziin8sy&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a href="https://giphy.com/pbs/">PBS</a> on <a href="https://giphy.com/gifs/pbs-science-human-footprint-shane-campbell-staton-SfzHzeAQte2sl2RfK2">GIPHY</a></div>
=> Add description to Schema Variant pkg import/export to ensure it persists across lock/unlock and import/export variant

lib/dal/src/module.rs, lib/dal/tests/integration_test/module.rs, lib/sdf-server/src/server/service/v2/module.rs, lib/sdf-server/src/server/service/v2/module/sync.rs
This PR moves module syncing to the dal. In addition, it fixes tracing for module syncing and includes more logging. As a result of module syncing moving to the dal, there's a new integration test too.
=> Move module sync to dal, fix its tracing and add integration test

.github/workflows/deploy-auth-api.yml, bin/auth-api/BUCK, bin/auth-api/Dockerfile, flake.nix
Compress the dockerfile into something somewhat readable, even if I don't get everything it is doing. It builds! Made it so buck2 can build that auth-api so we get containers automatically instead of arbitrarily sending them to ECR when we deploy. Also updates the deploy action to work with this scheme so things are finally normalized. There's some jank here, but I think unraveling it any further is just an exercise in diminishing returns.
=> feat: add auth-api to buck2 builds

lib/dal/src/module.rs, lib/sdf-server/src/server/service/v2/module.rs
This PR increases the log level for module syncing as well as tunes inner logs' levels. In addition, we now log instead of returning an error because either the deployment existed during a time where schemas were not one-to-one with modules, or the developer is testing schemas without corresponding modules (e.g. recent AWS IAM creation efforts).
=> Increase log level and log when module not found for schema

DOCS.md, README.md, app/docs/src/reference/dev/development-environment.md
From research on latest `main`, NixOS x86_64 and aarch64 works for both building and running SI (`buck2 run dev:up`). Data propagation in modeling and advanced function execution (e.g. "create" actions talking to AWS) works as expected. Now, the docs reflect the current state of compatibility.
=> Reflect NixOS compatibility in the docs

app/web/src/components/AssetCard.vue, app/web/src/components/AssetListPanel.vue, lib/dal/src/module.rs
This PR adds the ability to update assets, which is known on the backend as "upgrading modules". There are two ways to do so:
1. Update all assets at once by clicking the update button on the upper left-hand side of the asset list panel
2. Update individual assets by selecting them and then clicking the update button on the upper right-hand side of the asset card on the right-hand side of the application
In both cases, we unset the currently selected asset in order to avoid a mismatched state. In the future, we may be able to avoid unsetting (only for the "update all" case) by checking if the currently selected asset is not in the "upgradeable" list.
This PR also ensures that unlocked schema variants do not appear as "upgradeable".
=> Add ability to update assets (upgrade modules)

app/auth-portal/src/pages/ProfilePage.vue, app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/web/src/store/workspaces.store.ts, bin/auth-api/src/routes/workspace.routes.ts, bin/auth-api/src/services/users.service.ts, bin/auth-api/src/services/workspaces.service.ts, bin/auth-api/test/auth-routes.test.ts, bin/auth-api/test/helpers/dummy-factory.ts
Instead of creating a local dev workspace, the auth portal now creates an SI Managed Saas workspace for each new user.
Users who have verified their email before reaching the Workspaces page for the first time will be automatically redirected into this first workspace.
Workspaces now have a meaningful InstanceEnvType - LOCAL, PRIVATE, or SI
=> feat(auth) - prod workspace stuff for SaaS

app/web/src/components/AssetCard.vue, app/web/src/store/asset.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/schema/variant.rs, lib/sdf-server/src/server/service/v2/variant.rs, lib/sdf-server/src/server/service/v2/variant/delete_unlocked_variant.rs
In order to account for assets that are created in a changeset [these assets become the default schema variant for a schema], we need to delete the schema if that's the case
=> feat(sdf, dal, web): Allow deleting unlocked schema variants

flake.nix, lib/si-firecracker/BUCK, lib/si-firecracker/Cargo.toml, lib/si-firecracker/src/errors.rs, lib/si-firecracker/src/firecracker.rs, lib/si-firecracker/src/lib.rs, prelude-si/rootfs/rootfs_build.sh
Fixes the flake and hide linux-only dependencies behind comp targets. This is kind of a hokey way to do this but I think the most correct way is likely a refactor of the instance itself, which is a pretty huge undertaking.
=> fix: cfg out linux-only firecracker dependencies

app/auth-portal/src/router.ts
The tutorial page was deleted so we should redirect to the workspaces page
=> fix(auth-portal): Redirect tutorial to workspaces

app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
Both routes use the `WorkspaceCustomizeAssets` component. A fuller fix would be pulling the common bits into their own component, having two separate components in the route, and use slots to place the specific per-route components in place. There are some other upsides to that approach, too. But for a Friday, this resolves the problem that would confuse a user until they figured out how to unblock themselves.
=> Fix: asset editor and install module are mutually exclusive

lib/dal/src/pkg.rs, lib/dal/src/pkg/import.rs
When installing a generated variant, we need to check for the func by funcid rather than name because if we use name we can find a corresponding name and could end up with a conflicting func in a package
This was manifesting itself as a regenerate showing old func variants
=> fix(dal): ensure we don't search for funcs by name

app/docs/src/reference/index.md, app/docs/src/reference/vocabulary.md
```5:34:03 PM: x Build failed in 2.43s
5:34:03 PM: ✖ building client + server bundles...
5:34:03 PM: build error:
5:34:03 PM: [vitepress] 3 dead link(s) found.
5:34:03 PM:     at Object.renderStart (file:///opt/build/repo/node_modules/.pnpm/vitepress@1.0.2_@types+node@18.15.11_typescript@4.9.5/node_modules/vitepress/dist/node/serve-CEVH7KNu.js:42308:15)
5:34:03 PM:     at file:///opt/build/repo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
5:34:03 PM:     at async Promise.all (index 0)
5:34:03 PM:     at async PluginDriver.hookParallel (file:///opt/build/repo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19702:9)
5:34:03 PM:     at async Bundle.generate …
```
=> fix dead links which is preventing docs from being deployed

app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/auth-portal/src/store/workspaces.store.ts
This is currently set to false but this means the auth-api and the auth-portal will now be in sync
=> feat(auth-portal): Send isDefault when creating a workspace
