systeminit/si

CONTRIBUTING.md
README.md
docs/DEVELOPMENT_ENVIRONMENT.md

- Add about section to README
- Add rancher desktop notes to development environment doc
- Remove note about alphabetical requirement for contributors list
Fixes #2611 
Related #2605

Add about section and rancher desktop notes

---

README.md

Link public Buildkite dashboards

---

flake.nix

```
which aws && aws --version
/nix/store/np6apby08f71n6qxvk8i17gri5cqd1dc-awscli2-2.12.7/bin/aws
aws-cli/2.12.7 Python/3.10.12 Darwin/22.3.0 source/arm64 prompt/off
```

fix(lang-js): Upgrade to awscli v2

---

lib/si-cli/src/key_management.rs

fix(si): Ensure that the entire SI data directory path exists or create it

---

lib/si-cli/src/cmd/status.rs

feat(si): Expose the versions of the running containers in the status command

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/modules/ModuleExportModal.vue

fix(web): Force reload of schema Variants after schema creation

---

app/auth-portal/src/App.vue
app/auth-portal/src/components/DeployNotification.vue
app/auth-portal/vite.config.ts

This adds functionality which checks the currently running version (using the the script included in the rendered html file) against the latest (using the manifest.json produced during the build).
If the versions dont match, we pop up a modal prompting the user to please refresh.
This will likely need future work, but this is a good start.

New deploy modal for auth-portal

---

app/auth-portal/src/components/DeployNotification.vue

fix(auth-portal) fix bug during SSG in auth portal deployment notif

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml

adding linear label to Feature Requests so they comei into Linear 
adding feature-request label to Feature Requests
adding bug label to Bugs

chore(): update github issue templates (ENG-1892)

---

lib/si-cli/src/cmd/start.rs

This will ensure any race conditions are fixed by a restart

fix(si): Ensure SI containers restart on failure

---

lib/si-cli/src/cmd/stop.rs
lib/si-cli/src/cmd/update.rs
lib/si-cli/src/engine.rs
lib/si-cli/src/engine/docker_engine.rs
lib/si-cli/src/engine/podman_engine.rs
lib/si-cli/src/state.rs

ENG-1886
ENG-1887
- feat(si): Ensure we capture the name of the containe engine when tracking usage
- fix(si): Ensure that running an update when no containers installed doesn't trigger start

fix(si): Ensure that running an update when no containers installed doesn't trigger start

---

app/web/src/store/feature_flags.store.ts
app/web/src/store/secrets.store.ts

preparing for parallelizing work on secrets on the front end

feat(web) - secrets store exists

---

app/auth-portal/src/pages/DownloadPage.vue

fix(auth-portal): Adding extra podman machine installation instructions

---

app/web/src/components/FuncEditor/QualificationDetails.vue

This doc link no longer exists.

fix(web): remove stale qualification docs link

---

Cargo.lock
app/web/src/components/AddSecretForm.vue
app/web/src/components/PropertyEditor.vue
app/web/src/components/SecretsList.vue
app/web/src/components/Workspace/WorkspaceCustomizeSecrets.vue
app/web/src/store/secrets.store.ts
lib/dal/src/context.rs
lib/dal/src/diagram/node.rs
lib/sdf-server/BUCK
lib/sdf-server/Cargo.toml
lib/sdf-server/src/server/service/secret.rs
lib/sdf-server/tests/service_tests/secret.rs

feat(web,sdf): New SDF Secrets endpoints

---

prelude-si/pnpm.bzl

Just a small copy pasta I think

build: fix typescript rule docstring

---

lib/si-cli/src/cmd/start.rs
lib/si-cli/src/engine.rs

Closes: #2700
If you want to  change the port map for SDF or Web, then you'd currently
need to stop and delete the containers manually then re-run start
With this PR we can now do the following:
```
si --sdf-port 5157 start
```
This caused the Launcher to act as follows:
```
Container Port Mappings have changed for local-web-1 so recreating
Stopping container /local-web-1
Deleting container: local-web-1 (4d15095f701d8f2872a4e5a838f1187d1e0b980297bd23d15c21bc966eb41188)
Starting systeminit/web:stable as local-web-1
All system components running... System Initiative is alive!
You can now use the `si launch` command to open the System Initiative web portal:
```

feat(si): Recreate SDF or Web containers when port mappings change

---

app/web/src/api/sdf/dal/property_editor.ts
app/web/src/components/PropertyEditor.vue
app/web/src/components/PropertyEditor/PropertyWidget.vue
app/web/src/components/PropertyEditor/WidgetSecret.vue
bin/lang-js/src/asset_builder.ts
lib/dal/src/component/view.rs
lib/sdf-server/src/server/service/ts_types/asset_types.d.ts

Also did cleanup on the frontend to remove the "secretSelect" Widget kind and replace it with just "secret"

feat(web) - secret widget exists!

---

app/web/src/api/sdf/dal/change_set.ts
app/web/src/components/ActionSprite.vue
app/web/src/components/ComponentOutline/ComponentOutlineNode.vue
lib/dal/src/action_prototype.rs
lib/dal/src/diagram/node.rs
lib/sdf-server/src/server/service/change_set/list_open_change_sets.rs

This gives us the following when we attach different functions:

feat(dal,sdf-server,web): Add ability to display the func display names as part of the ActionSprite

---

app/web/src/App.vue

small bug in auth flow was causing reconnecting ui to fire even during login

fix(web) auth reconnect bug

---

app/auth-portal/src/App.vue
app/web/src/App.vue
app/web/src/store/auth.store.ts

last fix stopped the user facing bug, but we were still calling connect twice and had some other unexpected behaviour around logout.

fix(web) further fix to login flow

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/FuncEditor/ActionDetails.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/store/func/funcs.store.ts
lib/dal/src/action_prototype.rs
lib/dal/src/diagram/node.rs
lib/sdf-server/src/server/service/func/save_func.rs

The error message is because I made the action delete, but there already is one, so it rolled back and showed the error message

chore(web,dal): change action prototype kind setter UX

---

app/web/src/components/modules/ModuleDisplay.vue
app/web/src/store/module.store.ts
lib/module-index-client/src/client.rs
lib/module-index-client/src/types.rs
lib/module-index-server/src/migrations/U0003__modules_rejected.sql
lib/module-index-server/src/models/si_module.rs
lib/module-index-server/src/routes.rs
lib/module-index-server/src/routes/list_modules_route.rs
lib/module-index-server/src/routes/reject_module_route.rs
lib/sdf-server/src/server/service/pkg.rs
lib/sdf-server/src/server/service/pkg/reject_pkg.rs

When a module is rejected, it is no longer returned in the response to the modules page in the UI

feat(module-index-server): Allow rejecting modules

---

dev/Tiltfile
prelude-si/pnpm.bzl
prelude-si/tilt.bzl

This reverts commit 665f89cade8b9d7a4ae2ce00088658d97f8d0b13.
We'll revisit this with a follow up change, sorry to those affected in the meantime!

fix: revert "chore: add `--bind-all` flag to `buck2 run dev:up`"

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/AssetEditor.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/FuncEditor/AttributeBindings.vue
app/web/src/components/FuncEditor/CodeGenerationDetails.vue
app/web/src/components/FuncEditor/FuncArguments.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncEditor.vue
app/web/src/components/FuncEditor/FuncListPanel.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/components/modules/ModuleListPanel.vue
app/web/src/store/asset.store.ts
app/web/src/store/func/funcs.store.ts
lib/sdf-server/src/server/service/func.rs
lib/sdf-server/src/server/service/func/create_func.rs
lib/sdf-server/src/server/service/func/revert_func.rs
lib/sdf-server/src/server/service/func/save_and_exec.rs
lib/sdf-server/src/server/service/func/save_func.rs
lib/sdf-server/src/server/service/variant_definition.rs
lib/sdf-server/src/server/service/variant_definition/clone_variant_def.rs
lib/sdf-server/src/server/service/variant_definition/create_variant_def.rs
lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs

Revert "chore(web,sdf): auto create change-set on customize"

---

dev/Tiltfile
prelude-si/pnpm.bzl
prelude-si/tilt.bzl

Revert "un-revert #2772 and fix `buck2 run dev:down`"

---

app/web/src/components/ComponentOutline/ComponentOutline.vue
app/web/src/components/SidebarSubpanelTitle.vue

fix(web) - Diagram Outline loader padding issue

---

app/web/src/utils/typescriptLinter.ts
app/web/src/utils/typescriptLinterSnippets.ts

Adds support for snippets in code completion. Includes snippets for textbox props and sockets.

feat: add support for basic snippets in autocomplete

---

app/web/src/components/GenericDiagram/DiagramNode.vue

fix(web): Order socket names on a component by name

---

Cargo.lock
app/web/src/components/PropertyEditor.vue
bin/lang-js/src/asset_builder.ts
bin/lang-js/src/sandbox.ts
bin/sdf/endpoints.http
lib/dal/src/pkg/export.rs
lib/dal/src/pkg/import.rs
lib/dal/src/property_editor.rs
lib/dal/src/property_editor/schema.rs
lib/dal/src/schema/variant/definition.rs
lib/dal/src/schema/variant/root_prop.rs
lib/sdf-server/src/server.rs
lib/sdf-server/src/server/feature_flags.rs
lib/sdf-server/src/server/service/func.rs
lib/sdf-server/src/server/service/ts_types/asset_types_with_secrets.d.ts
lib/sdf-server/src/server/service/variant_definition/get_variant_def.rs
lib/si-pkg/pkg-complex.json
lib/si-pkg/src/node/schema_variant.rs
lib/si-pkg/src/node/schema_variant_child.rs
lib/si-pkg/src/pkg/variant.rs
lib/si-pkg/src/spec/prop.rs
lib/si-pkg/src/spec/variant.rs
lib/si-posthog-rs/BUCK
lib/si-posthog-rs/Cargo.toml
lib/si-posthog-rs/src/api.rs
lib/si-posthog-rs/src/client.rs
lib/si-posthog-rs/src/lib.rs
lib/si-posthog-rs/src/sender.rs

feat(web,dal,sdf,lang-js): Add Secrets and SecretDefinition to prop tree

---

lib/sdf-server/BUCK
lib/sdf-server/tests/service_tests/functions.rs
lib/sdf-server/tests/service_tests/mod.rs

Co-Authored-By: Paulo Cabral <paulo@systeminit.com>

test (sdf) function execution for new endpoint /execute

---

app/web/src/components/modules/ModuleDisplay.vue
app/web/src/store/module.store.ts
lib/module-index-client/src/client.rs
lib/module-index-client/src/types.rs
lib/module-index-server/src/routes.rs
lib/module-index-server/src/routes/promote_builtin_route.rs
lib/sdf-server/src/server/service/pkg.rs
lib/sdf-server/src/server/service/pkg/builtin_module_spec.rs

feat(web,sdf-server,module-index): Add ability to promote a module to be a builtin

---

app/web/src/components/ComponentOutline/ComponentOutline.vue
app/web/src/components/EdgeDetailsPanel.vue
app/web/src/components/GenericDiagram/DiagramEdge.vue
app/web/src/components/GenericDiagram/DiagramHelpModal.vue
app/web/src/components/GenericDiagram/GenericDiagram.vue
app/web/src/components/MultiSelectDetailsPanel.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
lib/vue-lib/src/design-system/tabs/TabGroup.vue

Wendy/eng 1950 bug fixes and UI improvements on the canvas based on user

---

app/web/src/utils/typescriptLinterSnippets.ts

snippets:
- valueFrom Prop
- valueFrom Socket
- selectBox Option
- AWS Region
- AWS Tags

feat(editor): adding more snippets for common tasks

---

app/web/src/components/CodeEditor.vue
app/web/src/utils/typescriptLinter.ts

Pop tooltip for current source under cursor using `ctrl/cmd+m`. Hotkey chosen arbitrarily as one that didn't have a binding in Chrome.

feat(editor): open tooltip on hotkey ctrl+m

---

app/web/src/components/AttributeDebugView.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/component/debug.rs

Adds the prop kind as the type to the debug view

feat(sdf-server,web): add attr type to debug view

---

lib/sdf-server/src/server/server.rs

We have to install our builtins serially or shared functions will be duplicated for each builtin. We could probably solve this with some clever locking, however this is the fastest way to get this fixed. This increases builtin installation time to about 70 seconds for me.

fix(sdf-server): install builtins serially

---

lib/dal/src/migrations/U0004__standard_model.sql
lib/dal/tests/integration_test/internal/attribute/prototype.rs

Revert "fix(dal): unsetting belongs to in wrong visibility"

---

app/auth-portal/src/components/WorkspaceLinkWidget.vue
app/auth-portal/src/pages/DashboardPage.vue
app/auth-portal/src/store/feature_flags.store.ts
app/auth-portal/src/store/workspaces.store.ts
bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/workspaces.service.ts
lib/vue-lib/src/design-system/modals/Modal.vue

Users can create new workspaces or edit ones that already exist from their dashboard.
https://github.com/systeminit/si/assets/8495209/7e885c82-3ece-4eec-ae00-a4b9aad90345

feat(auth) - creating and editing workspaces

---

bin/lang-js/src/sandbox.ts

This updates the vm2 sandbox to allow `fetch` to be used from within asset actions

(feat) (lang-js) add fetch to commandRunSandbox

---

lib/dal/src/pkg/export.rs

Schema Variants get deleted in the authoring process, and will often have deleted components (that were deleted in order to continue authoring). This simply ignores those deleted components for deleted variants and does not export them or import them on any changeset. Workspaces that were failing before will have to be re-exported.

fix(dal): Fix issues with components for deleted assets

---

bin/lang-js/src/sandbox.ts

Allows you to generate base64 strings, i.e
`console.log(Buffer.from("Hello World").toString('base64'));`

feat: (lang-js) add Buffer to common sandbox 

---

app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/components/StatusIndicatorIcon.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
bin/lang-js/src/action_run.ts
bin/lang-js/src/resolver_function.ts

feat(web) - final edits to FuncTest for Attribute Functions

---

.editorconfig
bin/lang-js/BUCK
bin/lang-js/README.md
bin/lang-js/bin-placeholder.js
bin/lang-js/examples/commandRunFailCode.js
bin/lang-js/src/action_run.ts
bin/lang-js/src/asset_builder.ts
bin/lang-js/src/base64.ts
bin/lang-js/src/index.ts
bin/lang-js/src/reconciliation.ts
bin/lang-js/src/resolver_function.ts
bin/lang-js/src/sandbox.ts
bin/lang-js/src/sandbox/exec.ts
bin/lang-js/src/schema_variant_definition.ts
bin/lang-js/tests/exec.spec.ts
prelude-si/macros.bzl
prelude-si/macros/pnpm.bzl
prelude-si/pnpm.bzl
prelude-si/pnpm/package_build_context.py
prelude-si/pnpm/toolchain.bzl
toolchains/BUCK

Prior to this change, no source formatting was being enforced by a build system and thus started to drift in consistency.

build(buck2): create a prettier_check rule for use in lang-js

---

app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/store/func/funcs.store.ts

feat(web): test validation functions

---

app/web/src/components/WorkspaceImportModal.vue
app/web/src/store/module.store.ts
lib/dal/src/pkg/import.rs
lib/sdf-server/src/server/service/pkg/install_pkg.rs

feat(web,dal,sdf): Display warning on skipped import items

---

lib/dal/src/pkg/import.rs

Just use update_for_context on the root prop using the implicit attribute value of root. This will spin out all child values correctly. Then scan the prop tree to catch missing values and to ensure prototypes are correct. Socket values are not set, since the dependent value update job will set them. This fixes issues with output sockets not propagating to input sockets after import.

fix(dal): Rethink component import to be more reliable

---

app/web/src/components/AssetEditor.vue
app/web/src/components/CodeEditor.vue
app/web/src/components/FuncEditor/FuncEditor.vue

- Stores only the last 50 undos and 50 dones
- Deletes buffer if it was written more than a week ago

feat(web): store history state in localstorage

---

app/web/src/components/WorkspaceInviteUserModal.vue
app/web/src/components/layout/navbar/Navbar.vue
app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue
app/web/src/pages/HomePage.vue
app/web/src/store/actions.store.ts
app/web/src/store/apis.ts
app/web/src/store/asset.store.ts
app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts
app/web/src/store/feature_flags.store.ts
app/web/src/store/func/funcs.store.ts
app/web/src/store/module.store.ts
app/web/src/store/qualifications.store.ts
app/web/src/store/status.store.ts
app/web/src/store/workspaces.store.ts
lib/dal/src/migrations/U2400__user_invited_to_workspace.sql
lib/dal/src/queries/user/get_by_email_raw.sql
lib/dal/src/queries/workspace/list_for_user.sql
lib/dal/src/user.rs
lib/dal/src/workspace.rs
lib/sdf-server/src/server/extract.rs
lib/sdf-server/src/server/routes.rs
lib/sdf-server/src/server/service.rs
lib/sdf-server/src/server/service/session.rs
lib/sdf-server/src/server/service/session/load_workspaces.rs
lib/sdf-server/src/server/service/workspace.rs
lib/sdf-server/src/server/service/workspace/invite.rs
lib/sdf-server/tests/service_tests/session.rs

- Invite users by email
- We do not validate emails for password logins
- Hard reload page if workspace changes to avoid reactivity issues

feat(web): implement multiple users per workspace

---

app/auth-portal/src/components/WorkspaceLinkWidget.vue
app/auth-portal/src/pages/DashboardPage.vue
app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/auth-portal/src/router.ts
app/auth-portal/src/store/feature_flags.store.ts
app/auth-portal/src/store/workspaces.store.ts
bin/auth-api/prisma/migrations/20231026214913_workspace_members/migration.sql
bin/auth-api/prisma/schema.prisma
bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/users.service.ts
bin/auth-api/src/services/workspaces.service.ts

In this PR, we check to see if the invited user is part of our system and if not, we create them a user based account that will be updated when they sign up
We have given the people that are invited to the workspace the “COLLABORATOR” role and we know if they have accepted the invite
There is no remove functionality at this time - this can be added in later as it's just a new route in the Auth API and a new button on the list
This work is using the CREATE_WORKSPACE feature flag so it's only visible to System Initiative users at this time

feat(auth-portal, auth-api): Add the ability to invite a user to a workspace

---

app/web/src/components/AssetPalette.vue

Adds a search bar above for assets in the model screen. Filters both group and asset names.

feat: asset panel search bar

---

app/web/src/components/GenericDiagram/DiagramCursor.vue
app/web/src/components/GenericDiagram/GenericDiagram.vue
app/web/src/components/GenericDiagram/diagram_types.ts
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/store/realtime/realtime.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/user.rs
lib/dal/src/ws_event.rs
lib/sdf-server/src/server/service/ws/workspace_updates.rs
lib/vue-lib/src/design-system/icons/icon_set.ts

Streams cursors if hovering diagram (but can be easily expanded to other
containers).

feat(web,dal,sdf): stream cursor and show on screen

---

bin/auth-api/test/workspace-routes.test.ts

This will show that it can be accessed, listed, added, deleted

chore(auth-api): Add some tests regarding the new members endpoint in auth-api

---

app/auth-portal/package.json
app/auth-portal/src/App.vue
app/auth-portal/src/components/WorkspaceLinkWidget.vue
app/auth-portal/src/main.ts
app/auth-portal/src/pages/ProfilePage.vue
app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/web/src/App.vue
app/web/src/components/ActionSprite.vue
app/web/src/components/ChangesPanel.vue
app/web/src/components/ComponentCard.vue
app/web/src/components/GenericDiagram/DiagramCursor.vue
app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/components/layout/navbar/Collaborators.vue
app/web/src/components/layout/navbar/Navbar.vue
app/web/src/components/layout/navbar/NavbarButton.vue
app/web/src/components/layout/navbar/NavbarPanelCenter.vue
app/web/src/components/layout/navbar/NavbarPanelLeft.vue
app/web/src/components/layout/navbar/NavbarPanelRight.vue
app/web/src/main.ts
app/web/src/store/feature_flags.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue
pnpm-lock.yaml

https://github.com/systeminit/si/assets/8495209/a6fde4e9-47f5-4216-9d8a-cc5d51e1c0af

fix(auth) - UI fixes, Collaborators on Navbar mock

---

app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/auth-portal/src/store/auth.store.ts
bin/auth-api/src/routes/workspace.routes.ts

Also ensure that we track the invitations in posthog to be able to send email invitations

feat(auth-api, auth-portal): Stop allowing unverified users to log into workspaces through the Dashboard

---

app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue

feat(app): Add ability to link a user from the workspace to workspace management in auth portal

---

app/auth-portal/src/App.vue
app/auth-portal/src/pages/WorkspaceDetailsPage.vue

feat(auth-portal): Add a section to WorkspaceDashboardPage regarding perms for inviting users

---

bin/auth-api/src/services/users.service.ts
bin/auth-api/test/auth-routes.test.ts

When a non-SI user is invited to a workspace, we create a row in the Users table with the email of the user and no other details. Previously, when that user attempted to signup, we didn’t check for a partially created user and instead we allowed the user to create a new account. This meant that the invitation to the workspace was for a “dead” user - i.e. a user that didn’t actually exist.
In this PR, we check for an existing user being either auth0 based OR that has an email and no signup date (email + no signup date means that they are invited but were not previously a member). This means we can now find the correct user and thus update the existing user with the auth0 response rather than creating a new user

fix(auth-api): Ensure that signing up as an invited user doesn’t create new user

---

app/web/src/components/GenericDiagram/DiagramControls.vue
app/web/src/components/GenericDiagram/DiagramEdge.vue
app/web/src/components/GenericDiagram/DiagramNode.vue
app/web/src/components/GenericDiagram/GenericDiagram.vue

https://github.com/systeminit/si/assets/8495209/3ba3f479-f21a-46ac-affb-d8b279c04d47

Wendy - Diagram View Modes

---

lib/dal/src/change_set.rs
lib/dal/src/ws_event.rs

This means we can use this data on the UI to show a user who was in a changeset who merged the changeset

fix(dal): Seed the change_set_applied WsEvent Payload with the actor who performed it

---

app/web/src/api/sdf/dal/change_set.ts
app/web/src/components/ApplyChangeSetButton.vue
app/web/src/components/Popover.vue
app/web/src/components/layout/navbar/ChangeSetAppliedPopover.vue
app/web/src/components/layout/navbar/ChangeSetApplyVotingPopover.vue
app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/components/layout/navbar/Collaborators.vue
app/web/src/components/layout/navbar/NavbarPanelRight.vue
app/web/src/components/layout/navbar/ProfileButton.vue
app/web/src/components/layout/navbar/UserCard.vue
app/web/src/components/layout/navbar/UserIcon.vue
app/web/src/store/change_sets.store.ts
app/web/src/store/feature_flags.store.ts
app/web/src/store/realtime/realtime.store.ts

feat(web) - multiplayer apply flow

---

app/web/src/components/layout/navbar/Collaborators.vue

fix(web): Remove the fake collaborators from the navbar

---

lib/dal/src/pkg/import.rs

- Does not backup secrets themselves

Fix(dal): Make secrets work on workspace import

---

app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/store/change_sets.store.ts
app/web/src/store/feature_flags.store.ts
lib/dal/src/change_set.rs
lib/dal/src/queries/change_set/abandon_change_set.sql
lib/dal/src/ws_event.rs
lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/change_set/abandon_change_set.rs

https://github.com/systeminit/si/assets/227823/bad4a508-933b-41a3-9241-53f8afbbcbd7

Add abandon changeset endpoint

---

bxl/dependent_targets.bxl

Dummy commit in dependent_targets.bxl to run all CI targets

chore: simulate work to validate CI changes

---

flake.nix

Let's try this again, nix flake should do it

chore: minor fix to trigger publishing CI

---

app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetPalette.vue
app/web/src/components/AttributeDebugView.vue
app/web/src/components/ComponentDebugDetails.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/ComponentDetailsCode.vue
app/web/src/components/ComponentDetailsResource.vue
app/web/src/components/DebugViewItem.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/store/components.store.ts

- confirmation model for change set deletion
- resources tab has a empty state graphic
- code panel supports multiple code outputs

Wendy/eng 2114 modeling bugs and UI issues fixing the debug panel

---

flake.nix

This will trigger everything to rebuild, yay!

chore(docs): update description of `flake.nix`

---

lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs

For some reason when veritech copies the orchestrate script it does not include the correct file permissions. I'm assuming the flags are getting altered during the build or when creating the package. This sets the permissions on the file after the copy.

fix: orchestrate file must be copied with the correct permissions.

---

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/store/component_attributes.store.ts
lib/dal/src/attribute/value.rs
lib/dal/src/index_map.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/delete_property_editor_value.rs

https://github.com/systeminit/si/assets/227823/7828ebbb-e175-4cf0-85d2-700a9ec826d5

Add delete property editor value endpoint

---

Cargo.lock
app/web/src/components/ChangesPanel.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
lib/dal/src/component.rs
lib/dal/src/diagram.rs
lib/dal/src/diagram/connection.rs
lib/dal/src/edge.rs
lib/dal/src/queries/edge/list_children_for_component.sql
lib/dal/src/queries/edge/list_children_for_node.sql
lib/dal/src/schema/variant.rs
lib/dal/src/socket.rs
lib/dal/src/standard_pk.rs
lib/sdf-server/BUCK
lib/sdf-server/Cargo.toml
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs
lib/sdf-server/src/server/service/diagram/create_node.rs

Notes:
- arity many sockets will not cause nested frames to disconnect the parents, they will accumulate the data
- node creation/dropping into a frame may be a bit slow, I need us to test it more to see how slow it is, it's easy to optimize but I prefer merging this first to then optimize based on a working state (and only if/when needed)
- sometimes you want to drop a component in a frame but the component is rendered behind the frame so you are unable

Implement nested frames

---

prelude-si/rootfs/rootfs_build.sh

This script was not creating a bootable rootfs. To fix this:
* At some point we moved some of the cyclone artifacts to `/run`. A tempfs gets mounted at `/run` at boot, so all files there were being masked. I moved all of these to `/cyclone`.
```bash
c8b21330e556:~# df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root              1992552    867572   1003740  46% /
devtmpfs                 10240         0     10240   0% /dev
**tmpfs                    98748        44     98704   0% /run**
shm                     246864         0    246864   0% /dev/shm
```
* I moved back the gathering of the binary inputs. This didn't need to happen later in the script like we thought before.
* Added back mingetty and the root shell so we could actually drop into the VM to figure …

fix: rootfs script fixes to ensure it is bootable

---

lib/dal/src/attribute/context.rs
lib/dal/src/component.rs
lib/sdf-server/src/server/service/diagram/paste_component.rs

- Parallelize component pasting (without edges)
- Filter existing attribute values/prototypes in rust (check context in rust)
- Commit more frequently to give the user the feeling of progress

Optimize components paste

---

app/web/src/components/AssetDiffDetails.vue
app/web/src/components/CodeViewer.vue
lib/dal/src/component/diff.rs

fix(web, sdf-server): Update code_diff for new components

---

app/web/src/components/AssetActionsDetails.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/ComponentDetailsResource.vue
app/web/src/components/ComponentOutline/ComponentOutlineNode.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/actions.store.ts
app/web/src/store/components.store.ts
lib/dal/src/diagram/node.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/get_actions.rs
lib/sdf-server/src/server/service/component/get_resource.rs
lib/sdf-server/tests/service_tests/scenario/fix_flow_deletion.rs

We load this data on request now

Remove resources and actions from get_diagram

---

Cargo.lock
bin/sdf/src/args.rs
bin/sdf/src/main.rs
lib/dal/BUCK
lib/dal/Cargo.toml
lib/dal/src/jwt_key.rs
lib/sdf-server/src/server/config.rs
lib/sdf-server/src/server/server.rs
lib/si-cli/src/engine/docker_engine.rs
lib/si-cli/src/engine/podman_engine.rs

This adds the ability to pass in the jwt to SDF as a base64 string. You know the drill!

feat: allow passing the jwt as a base64 string

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/paste_component.rs

I started using localstorage since I had problems with the clipboard API across browsers, it's doable, but doesn't seem like a deal breaker now.

Copy/Paste nodes with ctrl+c/ctrl+v

---

app/web/src/api/sdf/dal/change_set.ts
app/web/src/components/NoSelectionDetailsPanel.vue
app/web/src/store/actions.store.ts
app/web/src/store/change_sets.store.ts
lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/change_set/list_open_change_sets.rs
lib/sdf-server/src/server/service/change_set/list_queued_actions.rs
lib/sdf-server/tests/service_tests/scenario.rs
lib/sdf-server/tests/service_tests/scenario/fix_flow_deletion.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_aws_key_pair.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_mocked_whiskers.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_whiskers.rs

instead of including in list change sets

move proposed actions to new endpoint

---

app/web/src/components/Workspace/WorkspaceViz.vue
lib/dal/src/attribute/value.rs
lib/dal/src/context.rs
lib/dal/src/workspace_snapshot.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/tests/integration_test/internal/mostly_everything_is_a_node_or_an_edge/component.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/insert_property_editor_value.rs

Supports inserting new values into maps and arrays with the graph-based attribute values

feat(dal,sdf): insert property editor values in graph

---

README.md
bin/si/BUCK

Forcing a new build on the macos agents.

fix: dummy commit to force a new build

---

app/web/src/components/modules/ModuleListPanel.vue

fix(web): Fix search functionality in modules tab

---

app/web/src/store/component_attributes.store.ts

Also display array and map children better on the error log

fix(web): Deal with unset Joi validations correctly

---

lib/dal/tests/integration_test/internal/component/validation.rs

Thanks for the feedback, dear test. Sadly you've aged and sometimes misfire and have (apparently) become prone to races. I wish you long life and enjoyment in our source code attic. Say hello to the couchbase code when you arrive, it's been a while!

chore(dal): retire `ensure_validations_are_sourced_correctly` test

---

app/web/src/components/AssetEditor.vue
app/web/src/components/CodeEditor.vue
app/web/src/components/FuncEditor/FuncEditor.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/store/asset.store.ts
app/web/src/store/func/funcs.store.ts
lib/sdf-server/src/server/service/func/execute.rs
lib/sdf-server/tests/service_tests/functions.rs

Also saves function before running test to ensure its never stale
This is a proper fix for the bug Salmon experienced and reported on discord.

Remove debouncer from code editor to avoid data loss

---

Cargo.lock
lib/telemetry-http-rs/BUCK
lib/telemetry-http-rs/Cargo.toml
lib/telemetry-http-rs/src/lib.rs
lib/telemetry-http-rs/src/make_span.rs
lib/telemetry-http-rs/src/propagation.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock

feat(telemetry): extract otel context & associate with HTTP request spans

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/SecretCard.vue

https://github.com/systeminit/si/assets/8495209/0a01d18b-a444-489e-ae89-bf1a8fc7bf16

fix(web) - nudging fixed, pencil icon

---

app/web/src/components/SecretsPopover.vue

feat(web) - SecretsPopover can be taller

---

app/web/src/components/ActionCard.vue
app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/components/ChangeCard.vue
app/web/src/components/FixCard.vue
app/web/src/components/FixCardIconButton.vue
app/web/src/components/FixDetails.vue
lib/vue-lib/src/design-system/icons/custom-icons/code-pop-square.svg
lib/vue-lib/src/design-system/icons/custom-icons/code-pop.svg
lib/vue-lib/src/design-system/icons/custom-icons/logs-pop-square.svg
lib/vue-lib/src/design-system/icons/custom-icons/logs-pop.svg
lib/vue-lib/src/design-system/icons/icon_set.ts

- Icon improvements on ApplyHistory panel
- type icons inside of input fields on AttributePanel
- other minor style fixes in AttributePanel

fix(web) - AttributesPanel UI improvements, last ApplyHistory UI changes

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/ModelingDiagram/DiagramEdge.vue
app/web/src/components/ModelingDiagram/DiagramGroup.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/diagram_types.ts
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/asset.store.ts
app/web/src/store/components.store.ts
lib/dal/src/component.rs
lib/dal/src/edge.rs
lib/dal/src/queries/edge/list_children_for_node.sql
lib/dal/src/queries/edge/list_parents_for_component.sql
lib/dal/src/schema/variant/definition.rs
lib/dal/src/schema/variant/root_prop.rs
lib/dal/src/schema/variant/root_prop/component_type.rs
lib/dal/tests/integration_test/external/aws_region.rs
lib/dal/tests/integration_test/internal/component.rs
lib/dal/tests/integration_test/internal/edge.rs
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs
lib/sdf-server/src/server/service/diagram/paste_component.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_aws_key_pair.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_mocked_whiskers.rs
lib/sdf-server/tests/service_tests/scenario/model_and_fix_flow_whiskers.rs
lib/sdf-server/tests/service_tests/scenario/model_flow_fedora_coreos_ignition.rs
lib/si-pkg/src/spec/variant.rs

CLOSES ENG-2224
CLOSES ENG-2225
CLOSES ENG-2226
CLOSES ENG-2227
CLOSES ENG-2228
CLOSES ENG-2229
CLOSES ENG-2230

feat(web,dal,sdf) - add new configuration frame with direction

---

Cargo.lock
bin/veritech/scripts/stop.sh
lib/deadpool-cyclone/src/instance.rs
lib/deadpool-cyclone/src/instance/cyclone/firecracker-setup.sh
lib/deadpool-cyclone/src/instance/cyclone/local_http.rs
lib/deadpool-cyclone/src/instance/cyclone/local_uds.rs
lib/deadpool-cyclone/src/lib.rs
lib/deadpool-cyclone/src/pool_noodle.rs
lib/deadpool-cyclone/src/pool_noodle/pool_noodle.rs
lib/veritech-server/src/server.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock

PoolNoodle lives!
When using Firecracker, this will spin up a background thread responsible for ensuring that jails are available for consumption for functions. It favors creating new jails from the total available and will instead clean up old jails if none are available. 
```
/// Starts the loop responsible for jail lifetimes. The loop works by:
/// 1. Check if we have fewer ready jails than the `[MINUMUM_JAIL_PERCENTAGE]` of `[pool_size]`
/// 2. If so, go get an unprepared jail and prepare it!
/// 3. If not, check if there are any jails that need to be cleaned.
/// 4. If so, clean them and move them to `[unprepared]` so they can be made ready.
/// 5. If not, do nothing!
```
I am _certain_ there are edge cases here that I have not covered. Feel free to bring them up in the PR. The …

feat: add PoolNoodle to manage firecracker jails

---

app/web/src/store/components.store.ts
lib/dal/src/diagram/connection.rs
lib/dal/src/diagram/summary_diagram.rs
lib/dal/src/edge.rs
lib/dal/tests/integration_test/internal/edge.rs
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs

fix(web,sdf,dal): Allow only one parent frame socket connection

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/paste_component.rs

feat(web,dal,sdf) Pasting components to frames binds to them 

---

lib/dal/src/component.rs
lib/dal/src/edge.rs
lib/dal/src/queries/edge/list_children_for_component.sql
lib/sdf-server/src/server/service/diagram/delete_component.rs

fix(sdf,dal): Update frame children list on delete_component

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue

fix(web): Move child frames when parent frame moves

---

app/web/src/store/component_attributes.store.ts
app/web/src/store/feature_flags.store.ts
app/web/src/store/qualifications.store.ts

fix(web): Put JOI validations behind feature flag

---

lib/dal/src/migrations/U2413__summary_diagram_update_geometry_fix.sql

bug(summary): fixy-mergy for bad migration, and replace with a new migration

---

Cargo.lock
Cargo.toml
lib/si-data-nats/src/lib.rs
lib/si-data-pg/src/lib.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock
third-party/rust/Cargo.toml

Reverts systeminit/si#3222
Test PR for revert

Revert "chore(si-data-pg,si-data-nats): compute appropriate Span for txns/subs"

---

bin/veritech/scripts/userdata.sh

Adds Vector to ship logs to Cloudwatch. <img src="https://media3.giphy.com/media/GbpRRfKyq7Wzda6bVk/giphy.gif"/>

feat: add vector for veritech logs

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/components.store.ts
lib/dal/src/diagram/summary_diagram.rs
lib/dal/src/edge.rs
lib/dal/src/migrations/U2417__summary_diagram_fix_edge_summary_delete.sql
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs
lib/sdf-server/src/server/service/diagram/detach_component_from_frame.rs

- Make connect to frame auto detach from previous frame
- Make edge restoration work with summary tables
- Fix a component restore error related to frame edges
- Don't show "detach from frame" option when right clicking edges

fix(sdf,dal,web): Summary Diagram Edge errors

---

app/web/src/components/FixCard.vue
app/web/src/components/FixCardIconButton.vue
app/web/src/components/FixDetails.vue

feat(web) - logs and code in ApplyHistory, fixed Modal scrolling in FixDetails

---

lib/dal/src/job/definition/fix.rs

Pinga was using Nats to recurse the fix jobs for a given batch. This makes it use a loop instead, with a limit on the total number of times we will go over the list of fixes.
We don't think this fixes the underlying issue, but we do think it adds a bunch of useful telemetry and significantly reduces the blast radius.

bug(pinga): don't use nats for recursion

---

app/web/src/components/WorkspaceExportModal.vue
app/web/src/store/module.store.ts
app/web/src/store/realtime/realtime.store.ts
lib/sdf-server/src/server/service/pkg/export_workspace.rs
lib/sdf-server/src/server/service/pkg/install_pkg.rs

feat(web,sdf): Async workspace export

---

app/web/src/components/AssetActionsDetails.vue
app/web/src/components/AssetEditorTabs.vue
app/web/src/components/ChangesPanel.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/CustomizeTabs.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/components/NoSelectionDetailsPanel.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
lib/vue-lib/src/design-system/tabs/TabGroup.vue

feat(web) - compactify TabGroup

---

app/web/src/components/WorkspaceExportModal.vue

fix(web): Show errors to user on module export

---

app/web/src/components/ModelingDiagram/DiagramEdge.vue
app/web/src/store/feature_flags.store.ts

behind feature flag `show_edges_on_select`

feat(web) de-emphasize edges and highlight on selection

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/store/asset.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/func.rs
lib/dal/src/func/variant.rs
lib/dal/src/lib.rs
lib/dal/src/ws_event.rs
lib/sdf-server/src/server/service/func.rs
lib/sdf-server/src/server/service/variant_definition.rs
lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs
lib/sdf-server/src/server/service/variant_definition/save_variant_def.rs
lib/telemetry-rs/src/lib.rs

feat(web,sdf,dal): async exec variant def

---

lib/dal/src/node.rs

Small change - doesn't fix the frames issue we're seeing but it at least makes it a little easier to collaborate within a changeset

fix(dal): fire ws_event when component position is set

---

lib/telemetry-application-rs/src/lib.rs

This change will ensure that anytime we change the telemetry tracing log levels, we get an `INFO` level span transmitted to the OpenTelemetry endpoint with its associated events.

chore(telemetry): add a span around tracing level change events

---

Cargo.lock
lib/cyclone-server/src/handlers.rs
lib/cyclone-server/src/routes.rs
lib/cyclone-server/src/server.rs
lib/cyclone-server/src/tower.rs
lib/telemetry-http-rs/src/lib.rs
lib/telemetry-http-rs/src/make_span.rs
lib/telemetry-http-rs/src/propagation.rs

feat(telemetry): track web socket sessions in spans in Cyclone server

---

app/web/src/components/AssetPalette.vue
app/web/src/components/ComponentOutline/ComponentOutlineNode.vue
app/web/src/components/ModelingDiagram/DiagramEmptyState.vue
app/web/src/components/NoSelectionDetailsPanel.vue
app/web/src/components/SecretCard.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/components/Workspace/WorkspaceCustomizeFunctions.vue
app/web/src/components/Workspace/WorkspaceCustomizePackages.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/store/feature_flags.store.ts
lib/vue-lib/src/design-system/icons/icon_set.ts
lib/vue-lib/src/design-system/index.ts
lib/vue-lib/src/design-system/panels/PanelResizingHandle.vue
lib/vue-lib/src/design-system/panels/PanelResizingHandleOld.vue
lib/vue-lib/src/design-system/panels/ResizablePanel.vue
lib/vue-lib/src/design-system/panels/ResizablePanelOld.vue
lib/vue-lib/src/design-system/tabs/TabGroup.vue
lib/vue-lib/src/design-system/tree/TreeNode.vue

https://github.com/systeminit/si/assets/8495209/47b8755b-c42a-4b79-af08-d1c344819dd7

Wendy/eng 2318 UI changes to the side panels

---

app/auth-portal/package.json
app/web/package.json
lib/vue-lib/package.json
lib/vue-lib/src/design-system/forms/VormInputOption.vue
pnpm-lock.yaml

some awkward interactions between our Stack (which does some sneaky functional rendering stuff) and VormInputOption.
Managed to fix the bug, and will put together a repro to report the bug to the vue team...
bonus - updated some vue dependencies along the way as an attempt to fix it

fix(web,vue-lib) resolving some dicey issues with VormInput and Stack

---

dev/BUCK
prelude-si/macros.bzl
prelude-si/macros/tilt.bzl
prelude-si/tilt.bzl

This PR adds the ability to pull new images for supporting services via buck2. Just run `buck2 run //dev:pull`!
```bash
❯ buck2 run dev:pull
target root//dev:pull (prelude//platforms:default#213ed1b7ab869379) does not have any outputs: building it does nothing
Build ID: d437005a-2e02-469e-b267-2eea48da46f5
Jobs completed: 20. Time elapsed: 0.0s.
BUILD SUCCEEDED
[+] Pulling 41/41
✔ otelcol 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                              2.6s
✔ bca4290a9639 Pull complete                                                                                                                                                0.5s
✔ ffd946f9b9de Pull complete …
```

Add ability to pull new images via buck2 (ENG-2329)

---

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/store/component_attributes.store.ts
lib/dal/src/component.rs
lib/dal/src/job/definition/dependent_values_update.rs
lib/dal/src/prop.rs

Initial implementation of the new design

Redesign validations

---

app/web/src/components/CodeEditor.vue
app/web/src/components/ComponentOutline/ComponentOutline.vue
app/web/src/components/FilterPill.vue
app/web/src/components/SecretsModal.vue
app/web/src/components/SiSearch.vue
app/web/src/store/feature_flags.store.ts

https://github.com/systeminit/si/assets/8495209/56960881-c19e-4d8b-89d7-7b5f127fd5ac

Wendy/eng 2319 new UI for filtering in search bars

---

app/web/src/api/sdf/dal/code_view.ts
app/web/src/components/ComponentDetailsCode.vue
lib/dal/src/code_view.rs
lib/dal/src/component/code.rs
lib/dal/src/component/diff.rs

Display function name in codegen

---

app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts

Missed a timeout in the delete test which happened to pass when I checked locally

fix: amend other reference timeout

---

app/web/src/components/StatusBar/StatusBar.vue
app/web/src/components/StatusBar/StatusBarResourceSummary.vue
app/web/src/store/feature_flags.store.ts

feat(web): Expose the number of resources in a workspace

---

lib/dal-test/src/lib.rs

This change introduces a new test-specific environmental variable of `SI_TEST_KEEP_OLD_DBS` which, if non-empty, will not delete old test-specific databases on the next integration test run. Otherwise the prior behavior remains the default.

chore: optionally keep old test dbs on re-running integration tests

---

app/web/src/components/layout/navbar/Collaborators.vue
app/web/src/components/layout/navbar/UserIcon.vue
app/web/src/store/feature_flags.store.ts

By clicking on a user in the collaborators window, you will go to their changeset

feat(web): Allow navigating to collaborators changeset

---

app/web/cypress/e2e/authentication/login.cy.ts
app/web/cypress/e2e/authentication/logout.cy.ts
app/web/cypress/e2e/modelling-functionality/create-component.cy.ts
app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts
app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts
app/web/cypress/e2e/web-functionality/get-summary.cy.ts
app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts

Page must be visited before posthog event being sent. Validated locally against Production to be working, see https://us.posthog.com/project/20369/data-management/events/018dd875-9f8b-0000-3015-bb671a4893c6

fix: user session must be active to push event into posthog

---

lib/dal/src/property_editor.rs
lib/dal/src/property_editor/values.rs

fix(dal): Create prop editor summaries live if they don't exist on read

---

lib/dal/src/property_editor/values_summary.rs

fix(dal): o11y for prop editor summary

---

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/components/layout/navbar/Collaborators.vue
app/web/src/components/layout/navbar/UserCard.vue
app/web/src/components/layout/navbar/UserIcon.vue
app/web/src/store/feature_flags.store.ts

feat(web) - ability to view textArea and CodeEditor props which are disabled (plus Collaborator link fixes)

---

lib/dal/src/attribute/value.rs
lib/dal/src/component/migrate.rs
lib/dal/src/migrations/U2610__clear_dependencies_for_deleted_values.sql
lib/dal/src/pkg.rs
lib/dal/src/pkg/export.rs
lib/dal/src/pkg/import.rs
lib/dal/src/schema/variant/definition.rs
lib/dal/tests/integration_test/internal/pkg.rs
lib/si-pkg/src/node/schema.rs
lib/si-pkg/src/node/schema_variant.rs
lib/si-pkg/src/pkg/schema.rs
lib/si-pkg/src/pkg/variant.rs
lib/si-pkg/src/spec/schema.rs
lib/si-pkg/src/spec/variant.rs

Exports non-builtin variants for builtin schemas and imports them. Imports the components against the imported new schema variant

feat(dal): support workpace imports/exports with multi variants

---

lib/dal/src/secret.rs

fix(dal): Show secret creation form correctly

---

bin/lang-js/src/sandbox.ts

We need to expose the ability to load strings as YAML for some of the modelling

feat(lang-js): Export YAML load API in sandbox

---

lib/dal/src/component/migrate.rs
lib/dal/src/diagram.rs
lib/dal/src/diagram/summary_diagram.rs
lib/dal/src/migrations/U2611__add_use_default_variant_bool_to_component_summary.sql
lib/dal/src/pkg.rs
lib/dal/src/pkg/export.rs
lib/dal/src/pkg/import.rs
lib/sdf-server/src/server/service/variant_definition.rs
lib/sdf-server/src/server/service/variant_definition/exec_variant_def.rs

Changes the component summary table to have a boolean flag indicating whether a component is using the default variant for a schema. (This lets us determine whether we should upgrade the component to the default).

feat(dal,sdf): track whether a component is using the default variant

---

app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts

Basic amendment to selector for delete component based on the type change of AWS Credential from Component -> Frame

fix(cypress): amend div selector for delete

---

lib/dal/src/component.rs
lib/dal/src/migrations/U2613__fix_component_delete_and_propagate.sql
lib/sdf-server/src/server/service/diagram/delete_component.rs

fix(dal,sdf): Delete components on summary immediately

---

lib/dal/src/attribute/value.rs
lib/dal/src/authentication_prototype.rs
lib/dal/src/builtins.rs
lib/dal/src/builtins/schema.rs
lib/dal/src/builtins/schema/test_exclusive_schema_bethesda_secret.rs
lib/dal/src/component.rs
lib/dal/src/func.rs
lib/dal/src/func/before.rs
lib/dal/src/pkg/import.rs
lib/dal/src/prop.rs
lib/dal/src/property_editor/values.rs
lib/dal/src/queries/authentication_prototype/find_for_context.sql
lib/dal/src/queries/authentication_prototype/find_for_context_and_func.sql
lib/dal/src/queries/authentication_prototype/find_for_func.sql
lib/dal/src/schema/variant.rs
lib/dal/src/secret.rs
lib/dal/src/workspace_snapshot/edge_weight.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/graph/tests.rs
lib/dal/tests/integration_test/internal/new_engine.rs
lib/dal/tests/integration_test/internal/new_engine/before_funcs.rs
lib/dal/tests/integration_test/internal/new_engine/connection.rs
lib/dal/tests/integration_test/internal/new_engine/frame.rs
lib/sdf-server/src/server/service/func.rs
lib/sdf-server/src/server/service/func/create_func.rs
lib/sdf-server/src/server/service/func/list_funcs.rs

Import authentication prototypes and associations

---

Cargo.lock
Cargo.toml
lib/si-layer-cache/BUCK
lib/si-layer-cache/Cargo.toml
lib/si-layer-cache/benches/insert_speed.rs
lib/si-layer-cache/src/disk_cache.rs
lib/si-layer-cache/src/error.rs
lib/si-layer-cache/src/lib.rs
lib/si-layer-cache/src/memory_cache.rs
lib/si-layer-cache/tests/integration.rs
lib/si-layer-cache/tests/integration_test/disk_cache.rs
lib/si-layer-cache/tests/integration_test/memory_cache.rs
lib/si-layer-cache/tests/integration_test/mod.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock
third-party/rust/Cargo.toml
third-party/rust/fixups/criterion/fixups.toml
third-party/rust/fixups/moka/fixups.toml
third-party/rust/fixups/rayon-core/fixups.toml
third-party/rust/fixups/sled/fixups.toml

This adds an experimental layer cache to the new engine, which will allow us to start rebuilding the underlying write/read path for the new engine.

feat(si-layer-cache): adds an experimental layer cache

---

lib/dal-test/src/test_harness.rs
lib/dal/src/diagram.rs
lib/dal/src/pkg/import.rs
lib/dal/src/socket/input.rs
lib/dal/src/socket/output.rs

re added importing connection annotations and sending to the frontend

feat(dal): Restore connection annotations

---

lib/dal-test/src/test_harness.rs
lib/dal/src/component.rs
lib/dal/tests/integration_test/before_funcs.rs
lib/dal/tests/integration_test/component.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/set_type.rs

feat(dal) restore set_type

---

.github/workflows/community-check.yml
CONTRIBUTORS.md

Adding jobelenus to staff

---

lib/si-layer-cache/src/lib.rs
lib/si-layer-cache/tests/integration_test/mod.rs

Ensures that LayerCaches can be shared between threads (and tests this behavior)

feat(si-layer-cache): Ensure MemoryCacher is Send+Sync

---

lib/si-layer-cache/BUCK
lib/si-layer-cache/tests/integration_test/chunking_nats.rs

chore(si-layer): add test for chunking NATS!

---

bin/sdf/src/main.rs
lib/dal-test/src/lib.rs
lib/dal/src/context.rs
lib/pinga-server/src/server.rs
lib/rebaser-server/src/server.rs
lib/rebaser-server/src/server/core_loop.rs
lib/sdf-server/src/server.rs
lib/sdf-server/src/server/config.rs
lib/si-events-rs/src/cas.rs
lib/si-layer-cache/src/db.rs
lib/si-layer-cache/src/db/cas.rs
lib/si-layer-cache/src/layer_cache.rs
lib/si-layer-cache/src/lib.rs

chore(dal,sdf,pinga,rebaser): Add LayerDb to the ServicesContext

---

lib/dal/src/attribute/value.rs

All prepared function arguments for a prototype function are gathered as a mapping between function argument names and an *array* of values. In the old engine, we always transformed that array of values to a single value if the array was len() == 1. The new engine func binding preparation special-cased input sockets function arguments to always send an array, since this means that functions take take input socket values as an input would not require special logic for handling the scalar case and the array case (e.g., the si:normalizeToArray function). However, our components are not built with this change in mind, and the new behavior breaks some components slightly (for example EC2 Instance sets the user data prop from the input socket with identity, so what we write to the string prop …

fix(dal): restore old engine behavior when preparing function arguments

---

lib/dal-test/src/lib.rs
lib/dal-test/src/schemas/mod.rs
lib/dal-test/src/schemas/test_exclusive_schema_pirate.rs
lib/dal/src/attribute/value.rs
lib/dal/src/property_editor/values.rs
lib/dal/tests/integration_test/property_editor.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/delete_property_editor_value.rs

CLOSES ENG-2393
CLOSES ENG-2394
CLOSES ENG-2395
CLOSES ENG-2396

feat(dal,sdf) delete and create array/map items from prop editor

---

app/web/src/components/ComponentCard.vue
app/web/src/components/ModelingDiagram/DiagramEdge.vue
app/web/src/components/ModelingDiagram/DiagramGroup.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue
app/web/src/components/ModelingDiagram/diagram_types.ts
app/web/src/store/components.store.ts
lib/dal/src/action.rs
lib/dal/src/action/prototype.rs
lib/dal/src/action/runner.rs
lib/dal/src/attribute/value.rs
lib/dal/src/attribute/value/dependent_value_graph.rs
lib/dal/src/component.rs
lib/dal/src/diagram.rs
lib/dal/src/job/definition/action.rs
lib/dal/src/layer_db_types/content_types.rs
lib/dal/src/schema/variant.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/tests/integration_test/component.rs
lib/dal/tests/integration_test/dependent_values_update.rs
lib/dal/tests/integration_test/mod.rs
lib/sdf-server/src/server/service/diagram.rs
lib/sdf-server/src/server/service/diagram/delete_component.rs

This is more of a "mark things as having an intention to delete them", since we need the component(s) to still exist for Actions to be able to run against them, and have the Actions remove the thing that is being modeled from the outside world.

Let you (intend to) delete things on the diagram

---

lib/dal/src/context.rs

The rebase request must occur *after* a dal context has committed but *before* any dependent value update job has run, since it's the rebaser's responsibility to update the changeset pointer, and if the dependent values job picks up the change set pointer before it has been updated, the snapshot it uses might not contain the attribute values we have asked it to update. This ensures we make the rebase request at the correct time in commit (blocking_commit is already correct).

fix(dal): rebase must happen before dvu, but after commit

---

app/web/src/components/ComponentDebugDetails.vue
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/debug.rs

feat(web,sdf): Debug component id and schema variant id on UI

---

app/web/src/components/Workspace/WorkspaceVizSchemaVariant.vue

Flip-flopping the label color based on light or dark mode

ENG-2417 Visualizer supports dark mode

---

lib/dal/src/schema/variant/root_prop.rs

Fix last synced prop name (ENG-2436)

---

lib/dal/src/job/definition/action.rs

Fixes ENG-2433
Right now, when a create action has successfully completed, we run a refresh operation. The lack of a blocking commit meant that we were trying to run a refresh operation without the system having the correct data in place for a refresh to happen

fix(dal): Ensure we commit before we run a refresh action

---

lib/dal/src/workspace_snapshot.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs

ENG-2447
This allows us to start creating Modules on the graph

feat(dal): Adding a new CategoryNode for Module

---

lib/dal/src/layer_db_types/content_types.rs
lib/dal/src/lib.rs
lib/dal/src/module.rs
lib/dal/src/pkg.rs
lib/dal/src/pkg/import.rs
lib/dal/src/workspace_snapshot/content_address.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs

This isn't connected to anything at this time. I have also not removed the InstalledPkgs impl OR the storing in the old database structure

feat(dal): Adds a Module Node to the graph for each of the installed builtins

---

lib/dal/src/module.rs
lib/dal/tests/integration_test/mod.rs
lib/dal/tests/integration_test/pkgs.rs
lib/sdf-server/src/server/service/pkg.rs
lib/sdf-server/src/server/service/pkg/list_pkgs.rs

We are going to read the modules on the graph as the list packages now

feat(dal, sdf): Update list_pkgs to use Modules on the graph

---

app/web/src/components/modules/ModuleDisplay.vue
lib/dal/src/pkg.rs
lib/sdf-server/src/server/service/pkg.rs
lib/sdf-server/src/server/service/pkg/install_pkg.rs

There may be some reactivity things that we need to follow up on but this is largely working now

feat(sdf, dal): Restore install_pkg API Endpoint

---

app/web/src/components/ActionCard.vue
app/web/src/components/ApplyChangeSetButton.vue
app/web/src/store/actions.store.ts
app/web/src/utils/defaultmap.ts

NOTE: the 3 sets of icons is mocked to test the styles works when we've got multiple things in the list. There is really only one action, as per the rest of the screenshot.

Summarize and restyle proposed actions modal

---

lib/dal/src/attribute/value.rs

fix(dal): Run validations as pinga jobs

---

app/web/src/components/layout/navbar/ChangeSetPanel.vue

No longer need this reassignment to navigate to head

---

app/web/src/components/ApplyChangeSetButton.vue
app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/components/layout/navbar/UserCard.vue
lib/dal/src/change_set.rs
lib/dal/src/change_set/view.rs
lib/dal/src/migrations/U3001__change_set_pointers.sql

Fix possible dead-end during approval. Re-style approval flow

---

.ci/docker-compose.test-integration.yml
component/deploy/docker-compose.yaml
dev/docker-compose.platform.yml

References: docker/compose#11628

chore: remove obsolete "version" entry in Docker Compose files

---

lib/dal/src/func/authoring/create.rs
lib/dal/src/prop.rs
lib/dal/tests/integration_test/func/authoring/create_func.rs

This also includes tests for Qualification, CodeGeneration and Action func types

feat(dal):  Ensure that create action funcs can create ActionPrototypes

---

lib/dal/src/func.rs

chore(dal): Document dynamic funcs

---

app/web/src/store/module.store.ts

The module modals were being instantiated at load, and never getting the updated changeset  (since we need to await the fetch_changesets call to set the active changeset id - we get the id from the URL but need to confirm it before calling requests) - thus module requests were sending in the nil changeset id ("0000...") and failing
While we could get the changeset id from the url directly, the way that it is setup makes it so that setting selectedChangesetId based on the URL directly redirects to HEAD automatically instead of throwing an error when the url has an invalid changeset ID. 
The solution on this PR makes the calls functional, and it would be better to move the visibility params to something implicit in the API request lib anyway, which this code sort of points towards.

fix(web): changesetId on modules store

---

app/web/src/components/NoSelectionDetailsPanel.vue

fix(web): Update the Details Panel to have the name of the changeset

---

lib/dal-test/src/schemas/test_exclusive_schema_swifty.rs
lib/dal/src/func/authoring/create.rs
lib/dal/tests/integration_test/func/authoring/create_func.rs

@nickgerace this is the code we were just working on!

chore(dal): Adding integration tests for creating attribute funcs for props and sockets

---

app/web/src/App.vue
app/web/src/components/ApplyChangeSetButton.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/components/toasts/ChangesMerged.vue
app/web/src/components/toasts/IncomingChangesMerging.vue
app/web/src/main.ts
app/web/src/store/change_sets.store.ts

Eng-2459 experience after apply moving to head

---

bin/pinga/src/args.rs
bin/rebaser/src/args.rs
bin/sdf/src/args.rs
bin/sdf/src/main.rs
lib/pinga-server/src/config.rs
lib/pinga-server/src/server.rs
lib/rebaser-server/src/config.rs
lib/rebaser-server/src/server.rs
lib/sdf-server/src/server/config.rs

Adds an arg to pass through the layer db name to the associated services.

feat: add arg(s) for layer_db name

---

lib/si-layer-cache/src/persister.rs

The disk layer in the persister was swallowing errors. This PR makes that no longer happen.

bug(layerdb): fix error handling for disk layer

---

app/web/src/store/actions.store.ts
app/web/src/store/realtime/realtime.store.ts

Apologies for the large diff due to whitespace/indentation changes. Changes are smaller than they look in the mirror.

WsEvents are filtered by topic, define possible topics

---

app/web/src/store/status.store.ts
lib/dal/src/ws_event.rs
lib/rebaser-server/src/server/core_loop.rs

Ensures we also make the status bar reactive to rebase operations

feat(dal,web): mark as updating during rebases

---

app/web/src/components/AttributesPanel/AttributesPanel.vue
app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts

Fix ENG-2494 reflect component name change

---

Cargo.lock
lib/dal/src/workspace_snapshot.rs
lib/module-index-client/src/client.rs
lib/module-index-client/src/types.rs
lib/module-index-server/BUCK
lib/module-index-server/Cargo.toml
lib/module-index-server/src/routes.rs
lib/module-index-server/src/routes/upsert_workspace_route.rs
lib/sdf-server/src/server/service/module.rs
lib/sdf-server/src/server/service/module/export_workspace.rs

feat(dal,sdf,module-index): New Workspace export

---

app/web/src/store/status.store.ts

Replacing some of `this` with state in the getter. But mostly this is about deleting the two mutations within the getter and putting that logic down in the subscription callback

BUG-90 fix state mutation in getter

---

app/web/src/components/ChangesPanel.vue

BUG-114
This is part of preparing for the new actions work

feat(web): Remove the changes from the Proposed Actions Panel

---

lib/dal/src/diagram.rs

We can use this to understand if we can upgrade a component to a new version of a schema variant

feat(dal): Update SummaryComponent to suggest if on latest schema variant

---

Cargo.lock
lib/dal-test/BUCK
lib/dal-test/Cargo.toml
lib/dal-test/src/helpers.rs
lib/dal/src/property_editor/schema.rs

fix(dal): ignore hidden props in schema generation

---

app/web/src/components/WorkspaceImportModal.vue
app/web/src/store/workspaces.store.ts
lib/dal/src/change_set.rs
lib/dal/src/lib.rs
lib/dal/src/workspace.rs
lib/dal/src/workspace_snapshot.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
lib/dal/src/ws_event.rs
lib/module-index-client/src/client.rs
lib/module-index-client/src/types.rs
lib/sdf-server/src/server/service/module.rs
lib/sdf-server/src/server/service/module/export_workspace.rs
lib/sdf-server/src/server/service/module/install_workspace.rs

feat(web,sdf,dal) - Allow workspace imports

---

.github/workflows/deploy-service.yml

fix: use workflow_dispatch not _call

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/diagram_types.ts
app/web/src/store/components.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/component.rs
lib/dal/tests/integration_test/component.rs
lib/sdf-server/src/server/service/diagram/set_component_position.rs

This way we get only 1 job for the rebaser no matter how many components we are moving at a given time.

Batch Set Component Position

---

app/web/src/store/asset.store.ts
app/web/src/store/func/funcs.store.ts
lib/sdf-server/src/server/service/func/save_func.rs

fix(web): reload Variant funcs when a func is renamed

---

Cargo.lock
lib/dal/src/workspace.rs
lib/dal/tests/integration_test/mod.rs
lib/dal/tests/integration_test/workspace.rs
lib/module-index-client/src/client.rs
lib/module-index-client/src/types.rs
lib/module-index-server/src/routes/upsert_workspace_route.rs
lib/sdf-server/src/server/service/module.rs
lib/sdf-server/src/server/service/module/export_workspace.rs
lib/sdf-server/src/server/service/module/install_workspace.rs
lib/si-pkg/BUCK
lib/si-pkg/Cargo.toml
lib/si-pkg/src/lib.rs
lib/si-pkg/src/workspace.rs

feat(dal,si-pkg,sdf): Isolate and test workspace export and import

---

app/web/src/components/AssetActionsDetails.vue
app/web/src/components/AssetEditor.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/ChangesPanel.vue
app/web/src/components/ComponentCard.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/CustomizeTabs.vue
app/web/src/components/DetailsPanelMenuIcon.vue
app/web/src/components/DiagramOutline/DiagramOutline.vue
app/web/src/components/FuncEditor/FuncList.vue
app/web/src/components/FuncEditor/FuncListPanel.vue
app/web/src/components/IconButton.vue
app/web/src/components/NewFuncDropdown.vue
app/web/src/components/NoSelectionDetailsPanel.vue
app/web/src/components/SiChip.vue
app/web/src/components/SiFuncListItem.vue
app/web/src/components/SidebarSubpanelTitle.vue
app/web/src/components/modules/ModuleExportModal.vue
lib/vue-lib/src/design-system/general/VButton.vue
lib/vue-lib/src/design-system/icons/Icon.vue
lib/vue-lib/src/design-system/tabs/TabGroup.vue
lib/vue-lib/src/tailwind/tailwind.config.cjs

- New variant "fullsize" for TabGroup, general cleanup and improvements of TabGroup
- New variant for SiChip, general cleanup and improvements of SiChip
- Asset Details header removed and functionality compacted into the ComponentCard
- Replaced awkward buttons in Customize screens with IconButtons
- Improvements to FuncList and FuncListPanel
- Improvements to IconButton, new variant "simple"
- Fixed VButton "action" styling for dark mode
- Now Icons can be setup to spin either clockwise or counterclockwise
- Final compactifying work for the Customize left panels, a few other minor UI fixes

Many UI improvements!

---

lib/pinga-server/src/server.rs

Improves telemetry/metrics of `execute_job_task`.
Logs the number of concurrent tasks and limit every time a new job is spawned in pinga. Also logs if pinga is at full capacity, which means no new tasks will be consumed until one is finished.
We also are logging the status of execution, jobs without status are still being executed, so we can easily keep track of what is going on at each instance.

Add metrics to pinga jobs

---

lib/dal/src/attribute/value/dependent_value_graph.rs

It's only necessary to add an object's direct children to the workqueue (the next level down will be handled in the next iteration of the queue)

chore(dal): do less work when walking child values in dvu

---

app/web/src/store/component_attributes.store.ts
lib/sdf-server/src/server/service/component/delete_property_editor_value.rs
lib/sdf-server/src/server/service/component/insert_property_editor_value.rs
lib/sdf-server/src/server/service/component/update_property_editor_value.rs

This fixes reactivity for changing the input type for a prop, colour changes to the component, adding / updating or removing array and map elements

feat(sdf): Adding WsEvents when props change for a component

---

lib/si-layer-cache/src/persister.rs

Adding tracing to the persister

feat: tracing for the persister

---

app/web/src/store/components.store.ts

remove inferred edge in favor of explicit edge for the same toSocket

---

app/web/src/store/components.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/component.rs
lib/dal/src/ws_event.rs
lib/sdf-server/src/server/service/diagram/create_connection.rs
lib/sdf-server/src/server/service/diagram/delete_connection.rs

This allows us to reload the diagram correctly

feat(sdf, dal, web): Send a WsEvent after a component connected request

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs

Fix: batch connect components since frame edges are exclusive and concurrent rebases conflict

---

lib/dal/src/func/authoring/save.rs

This commit fixes attribute bindings creation by not processing a `ComponentId::NONE` value as `Some`... that's literally it. I'm going to come back and raze nilId, but I need a break first.

Fix attribute bindings creation

---

app/web/src/store/components.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/component.rs
lib/dal/src/ws_event.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/upgrade.rs

WE will be working through the work to implement the upgrade_to_new_variant next PR. The functionality doesn't do anything at this time!

feat(dal, sdf, web): Adds the sdf endpoint and func placeholder for component upgrades

---

bin/lang-js/src/asset_builder.ts

Revert "Update secret prop type to fix copy/paste"

---

app/web/src/store/actions.store.ts

feat(web): Add actions v2 functionality to store

---

lib/si-layer-cache/src/persister.rs

Not awaiting the write layer task means they could happen out of order, which is bad. We also want to log errors if the persister fails to persist.

fix: layer cache write order

---

app/web/src/api/sdf/dal/component.ts
app/web/src/components/ActionWidget.vue
app/web/src/components/AssetActionsDetails.vue
app/web/src/components/AssetQualificationsDetails.vue
app/web/src/components/ComponentCard.vue
app/web/src/components/Debug/ComponentDebugDetails.vue
app/web/src/components/DetailsPanelTimestamps.vue
app/web/src/components/DiagramOutline/DiagramOutline.vue
app/web/src/components/DiagramOutline/DiagramOutlineNode.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/diagram_types.ts
app/web/src/store/actions.store.ts
app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts
app/web/src/store/qualifications.store.ts
app/web/src/store/realtime/realtime_events.ts
app/web/src/store/secrets.store.ts
app/web/src/store/status.store.ts
lib/dal/src/component.rs
lib/dal/src/diagram.rs
lib/dal/src/node.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/delete_property_editor_value.rs
lib/sdf-server/src/server/service/component/insert_property_editor_value.rs
lib/sdf-server/src/server/service/component/set_type.rs
lib/sdf-server/src/server/service/component/update_property_editor_value.rs
lib/sdf-server/src/server/service/diagram/connect_component_to_frame.rs
lib/sdf-server/src/server/service/diagram/delete_component.rs
lib/sdf-server/src/server/service/diagram/detach_component_from_frame.rs

Lots of moving pieces around to fit in a new way.

Replace ID payload with full payload for WsEvent::component_updated

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/detach_component_from_frame.rs

Detaching components also needs to be done in a batch

---

app/web/src/components/StatusIndicatorIcon.vue
app/web/src/store/actions.store.ts
lib/dal/src/deprecated_action/prototype.rs
lib/dal/src/lib.rs
lib/dal/src/schema/variant.rs
lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/change_set/add_action.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/component/get_actions.rs

This allows you to view action prototypes in the frontend and be able to enqueue them if on v2 feature flag

Manually create actions v2

---

lib/dal/src/component.rs

When creating a new connection between components, check if the input socket has single arity and remove existing before creating the new one
<div><img src="https://media2.giphy.com/media/8iBVWBcraj2egpIVhR/200.gif?cid=5a38a5a238yb0zijwguam8otp5ucbteeq3jst1u7qj1kyy3i&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a href="https://giphy.com/travisband/">Travis</a> on <a href="https://giphy.com/gifs/travisband-8iBVWBcraj2egpIVhR">GIPHY</a></div>

Fix Single Arity Input Sockets

---

lib/dal/src/change_set.rs

When reviewing and discussing the conflicts we're seeing on apply, we noticed some places where we were committing but not erroring if conflicts are found. Let's error here so we don't pretend the apply succeeded

check for conflicts and error if found during apply change set and list actions, add some telemetry

---

lib/sdf-server/src/server/service/diagram/delete_component.rs

Component updated called when to_delete=True. Component deleted already called

---

.gitignore
CONTRIBUTORS.md
app/web/cypress.config.ts
app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts
app/web/cypress/support/attribute-panel-actions/component-attributes.ts
app/web/src/components/AttributesPanel/AttributesPanelItem.vue

This rebases #3774 PR into a single commit

feat: add page object model test example

---

lib/dal/src/component.rs

If the user upgrades the component, ensure we don't enqueue a create action but also enqueue anything the old component had queued

fix(dal): Ensure that we requeue any actions for the upgraded component

---

lib/sdf-server/src/server/service/action/put_on_hold.rs

endpoint is POST needs Json, not Query

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue

Fix: frames resize behavior with children

---

app/web/src/store/components.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/action/prototype.rs
lib/dal/src/component.rs
lib/dal/src/deprecated_action/prototype.rs
lib/dal/src/job/consumer.rs
lib/dal/src/job/definition/deprecated_action.rs
lib/dal/src/job/definition/refresh.rs
lib/dal/src/ws_event.rs

Send component payload when it updates with a resource

---

lib/dal/src/action.rs
lib/dal/src/attribute/value.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs

In theory, now we should get some default options.
Maybe don't fuck with weights?
Love,
Adam, Fletcher, Zack and Brit

bug(dal): fix back compat for workspace snapshots

---

lib/dal/src/attribute/value.rs

The change to introduce this behavior happened because the `ExclusiveEdgeMismatch` machinery was not detecting edge additions that had corresponding edge removals for the pre-existing exclusive edge.
Re-using the prototype was not fully cleaning up the pre-existing arguments, so we were ending up creating things like a `si:setObject` prototype with multiple arguments. This would result in an array being passed to `si:setObject`, and the execution blowing up as an array can't be (de)serialized as a map.
Now that the `ExclusiveEdgeMismatch` machinery has been updated to correctly handle the case where the exclusive constraint for an outgoing edge is not violated after all of the additions & removals are considered, the additional logic to try to re-use & clean up the old …

Do not attempt to re-use pre-existing Prototype nodes when setting the function for an AttributeValue

---

dev/BUCK
prelude-si/tilt.bzl

(chore) removed directory creation logic in tilt up bzl rule

---

lib/dal/src/workspace_snapshot.rs

There is a race condition:
* Process A consults change set X for current pointer address of the workspace snapshot
* Rebaser moves change set X on to point to a new snapshot
* Rebaser garbage collects snapshot change set X moved on from
* Process A tries to retrieve snapshot at pointer address it got
* Process A is unable to retrieve garbage collected snapshot
Rather than immediately failing, we now have a limited number of retries where we'll fetch what the address has moved on to, and attempt to fetch the content at that address, with a small sleep between each retry.

Retry fetching workspace snapshot for a change set if content for the snapshot address is not found

---

app/web/src/components/Actions/ActionCard.vue
app/web/src/components/DiagramOutline/DiagramOutline.vue
app/web/src/components/DiagramOutline/DiagramOutlineNode.vue

Follow the selected component in outline

---

lib/dal/src/pkg/export.rs

fix(dal): ensure data is set on output sockets

---

bin/sdf/src/main.rs

chore(sdf): add `dal` crate as "interesting" to telemetry

---

lib/dal/src/attribute/value.rs

Rather than trying to use `si:setString`, `si:setBool`, or any similar function with a `serde_json::Value::Null`, we now translate this to behave as though we had gotten a `None`, and use `si:unset`.
Ideally we would handle things in such a way that we can differentiate between "there is no value here" (`None`), and "the value here is `null`" (`Some(serde_json::Value::Null)`), but this is hard enough to do within JavaScript/JSON on its own, let alone round tripping data in & out of JSON multiple times before dealing with it.

Handle Some(serde_json::Value::Null) more gracefully when setting nested values

---

lib/dal/src/component.rs
lib/dal/tests/integration_test/component.rs

When setting to_delete on a component, we only want to enqueue Destroy actions if the component is not already in the to_delete state, so we don't automatically end up with multiple Destroy actions queued for the same component.

Only enqueue Destroy actions when transitioning from not to_delete to to_delete

---

app/web/package.json
app/web/src/components/ApplyChangeSetButton.vue
app/web/src/components/StatusBar/StatusBar.vue
app/web/src/components/StatusBar/StatusBarConflictSummary.vue
app/web/src/components/StatusBar/StatusBarTab.vue
app/web/src/components/toasts/Conflict.vue
app/web/src/main.ts
app/web/src/store/apis.ts
app/web/src/store/realtime/realtime_events.ts
app/web/src/store/status.store.ts
lib/vue-lib/src/pinia/pinia_api_tools.ts
pnpm-lock.yaml

ENG-2568 error and conflict toasts

---

app/web/src/components/toasts/FiveHundredError.vue
app/web/src/store/apis.ts

Display toast for 500 errors

---

app/web/src/components/AttributesPanel/AttributesPanel.vue

Oops, frame type fix

---

lib/dal/src/component.rs
lib/dal/tests/integration_test/component/upgrade.rs

Only enqueue actions for the upgraded component that were queued for the previous version. Extend a test to make sure we don't break this going forward!

Bug-287 - Stop duplicating create actions on upgrade

---

app/web/src/store/components.store.ts
app/web/src/store/realtime/realtime_events.ts
lib/dal/src/change_set.rs
lib/dal/src/change_set/event.rs
lib/dal/src/ws_event.rs

fix(dal,web): react to change sets applying to head/current change set

---

app/web/src/store/actions.store.ts
app/web/src/store/component_attributes.store.ts

Follow up: more apply to head reactivity

---

app/web/src/store/realtime/realtime.store.ts

Fix: broadcast to changeset that is being merged into

---

app/web/src/components/ApplyChangeSetButton.vue
app/web/src/components/ApprovalFlowModal.vue
app/web/src/components/layout/navbar/ChangeSetPanel.vue
app/web/src/components/toasts/ApprovalFlowCancelled.vue
app/web/src/components/toasts/MovedToHead.vue
app/web/src/store/change_sets.store.ts
app/web/src/store/presence.store.ts
lib/dal/src/change_set.rs
lib/vue-lib/src/design-system/forms/VormInput.vue

Many bug fixes and optimizations for the two approval flows

---

app/web/src/components/ApprovalFlowModal.vue

fix(web) - one last approval bug!

---

app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts

Fix: debounce was suppressing ws event data over the wire

---

app/web/src/components/ModelingDiagram/DiagramEmptyState.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue

- DiagramEmptyState under multiplayer cursors
- Delete icon for components/frames now in top right corner instead of big overlay

fix(web) - two bugs fixed

---

app/web/src/components/ModelingDiagram/DiagramGroup.vue
app/web/src/components/ModelingDiagram/DiagramGroupOverlay.vue
app/web/src/components/ModelingDiagram/DiagramHelpModal.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue

fix(web) - delete icon at top right instead of overlay

---

app/web/src/components/WorkspaceCustomizeEmptyState.vue
lib/vue-lib/src/design-system/general/ErrorMessage.vue
lib/vue-lib/src/design-system/general/LoadingMessage.vue
lib/vue-lib/src/design-system/general/RequestStatusMessage.vue

fix(web) - adjusted WorkspaceCustomizeEmptyState loader to be less disruptive

---

lib/dal/src/component.rs
lib/dal/tests/integration_test/component.rs

feat(dal): Don't create resources on copied components

---

app/web/src/api/sdf/dal/diagram.ts
app/web/src/components/modules/ModuleExportModal.vue
app/web/src/store/components.store.ts
lib/dal/src/schema/view.rs

BUG-263: show more variant detail on contribute panel

---

lib/sdf-server/src/server/service/diagram/paste_component.rs

Make components whose parents were also copied keep parented to the copies of their original parents when pasted inside of frame

feat(sdf): Don't reparent pasted children

---

.github/workflows/deploy-service.yml

allow deploying a specific version

feat: allow deploying a specific version (except for web)

---

lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/change_set/abandon_change_set.rs
lib/sdf-server/src/server/service/change_set/begin_abandon_approval_process.rs

<div><img src="https://media4.giphy.com/media/2AN7gVc1Az7pmdnFc3/200.gif?cid=5a38a5a2dpsc9la48v2n5blky781gofm3wtv8b3hr2ux67fp&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a href="https://giphy.com/amandaceemedia/">Amanda Cee Media</a> on <a href="https://giphy.com/gifs/amandaceemedia-i-need-you-clingy-dont-leave-me-2AN7gVc1Az7pmdnFc3">GIPHY</a></div>

return error when trying to abandon HEAD change set

---

app/web/src/components/StatusBar/StatusBarConflictSummary.vue

Copy update for conflict display

---

app/web/src/store/components.store.ts

Delighter: when moving to the diagram from the customizer, load the last component you had selected

---

lib/si-pool-noodle/src/instance/cyclone/firecracker-setup.sh

This makes the firecracker setup script architecture aware so we can run on ARM boxes.

feat: make setup script arch aware

---

lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
lib/dal/src/workspace_snapshot/vector_clock.rs

Revert "fix(dal): ensure we merge the vector clocks of nodes in import subgraph"

---

app/web/src/components/StatusBar/StatusBar.vue
app/web/src/components/StatusBar/StatusBarTabPill.vue

fix(web) - StatusBar has a fixed height of 40px

---

lib/dal/src/workspace_snapshot.rs
lib/dal/src/workspace_snapshot/edge_weight.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/lamport_clock.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
lib/dal/src/workspace_snapshot/vector_clock.rs

Revert "fix(dal): cleanup vector clocks on write"

---

app/web/src/store/actions.store.ts

Fix: added optimistic reverts to actions calls

---

.github/workflows/deploy-service.yml

This adds a dropdown for choosing which environment to deploy to.
**NOTE** I am going to need to redeploy some services in prod in order to normalize the names as we did not follow the same pattern in both environments. Please don't use this until after that is done.

feat: allow deploying both tools and prod.

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/ComponentDetails.vue
app/web/src/store/func/funcs.store.ts

fix(web) - bug 294, Modal Errors in Function Authoring

---

app/web/src/components/ModelingDiagram/DiagramNode.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/utils/math.ts
app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts
lib/dal/src/component.rs
lib/dal/tests/integration_test/component.rs
lib/sdf-server/src/server/service/diagram/paste_component.rs

feat(web,dal,sdf): Restrain pasted items to new parent

---

lib/sdf-server/src/server/service/action/cancel.rs

If an action fails to run to completion (i.e. func execution fails, there is a graph conflict, a transient/uncaught database error, etc), it may be left on the graph in a "running" state. Prior to this change we checked the action to see if it's dispatched or running and returned an error as this would imply that our system supports first-class interuptable cancellation of functions (which we do not yet support). This change removes the check and will consequently remove the action from the graph, allowing a user to re-enqueue the action to run again, etc.
Closes BUG-331

chore(sdf): remove check when cancelling an action

---

app/web/src/components/modules/ModuleExportModal.vue
app/web/src/store/components.store.ts

fix(web): Show metadata on export data list

---

app/web/src/components/Actions/ActionCard.vue
app/web/src/components/AssetListItem.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/AssetPalette.vue
app/web/src/components/ComponentDetails.vue
app/web/src/components/TruncateWithTooltip.vue
lib/vue-lib/src/design-system/general/PillCounter.vue

Wendy/bugs 279, 288, 335, and 336

---

app/web/src/components/ModelingView/EraseSelectionModal.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/components/Workspace/WorkspaceModelAndView.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/delete_component.rs
lib/vue-lib/src/design-system/icons/icon_set.ts

feat(web,sdf): Allow component erasing, even if it has resources

---

.github/workflows/deploy-service.yml
.github/workflows/deploy-stack.yml
.github/workflows/invalidate-cache.yml
.github/workflows/set-init-version.yml
component/deploy/userdata
prelude-si/nix/nix_omnibus_pkg_build.py

Just some fixes for github actions. It works!

fix: deployment bugs, add waiting for deploys

---

Cargo.lock
Cargo.toml
lib/dal/BUCK
lib/dal/Cargo.toml
lib/dal/src/action.rs
lib/dal/src/action/prototype.rs
lib/dal/src/component/resource.rs
lib/dal/src/job/consumer.rs
lib/dal/src/job/definition/action.rs
lib/dal/src/ws_event.rs
lib/dal/tests/integration_test/action.rs
lib/dal/tests/integration_test/property_editor.rs
lib/si-layer-cache/src/db/func_run.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock
third-party/rust/Cargo.toml

fix(dal): retry graph mutations after actions have run

---

.github/workflows/deploy-service.yml
.github/workflows/deploy-stack.yml
.github/workflows/invalidate-cache.yml
.github/workflows/set-init-version.yml

Using environments allows us to scope secrets in a more clean way and also opens us up to some interesting integration options.

feat: use environments for better secret scoping in gha

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/store/components.store.ts

Compute frame content boxes on the store so reactivity works

fix(web): Make sure frames can't get smaller than child areas

---

lib/dal/src/diagram.rs

Fix: check to_delete for component change status

---

app/web/src/components/Actions/ActionCard.vue
app/web/src/components/Actions/ActionsList.vue
app/web/src/components/ChangesPanelHistory.vue
app/web/src/components/ChangesPanelProposed.vue
app/web/src/store/actions.store.ts
lib/sdf-server/src/server/service/action/list_actions.rs
lib/si-layer-cache/src/db/func_run.rs

feat(web,si-layer-cache,sdf): Show action results on changes panel

---

.github/workflows/deploy-stack.yml

Missed this when I cleaned up how we did secrets last time around. It's unnecessary now.

fix: remove secrets step as it is no longer needed

---

app/web/.env
app/web/src/main.ts
component/otelcol/config.yaml
component/otelcol/honeycomb-config.yaml

Minor adjustments to web otel setup, adding health check endpoint for otel container

fix: web otel adjustments

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/store/func/funcs.store.ts

- Close the modal for a new FN after its created
- `Options` dropdown populated after creating a new Asset

BUG-379 two authoring UI fixes

---

flake.lock
lib/dal/src/socket/debug.rs
lib/module-index-server/src/extract.rs
lib/naxum/src/extract.rs
lib/sdf-server/src/server/service/graphviz.rs

• Updated input 'rust-overlay':
'github:oxalica/rust-overlay/bedc47af18fc41bb7d2edc2b212d59ca36253f59' (2024-06-11)
→ 'github:oxalica/rust-overlay/419e7fae2731f41dd9b3e34dfe8802be68558b92' (2024-06-14)
https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html

build(deps): update to Rust 1.79.0

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/AssetEditor.vue
app/web/src/components/AssetEditorTabs.vue
app/web/src/components/AssetListItem.vue
app/web/src/components/AssetPalette.vue
app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/components/ColorPicker.vue
app/web/src/components/FilterPill.vue
app/web/src/components/FuncEditor/ActionDetails.vue
app/web/src/components/FuncEditor/AttributeBindings.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/components/NodeSkeleton.vue
app/web/src/components/SiSearch.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/store/asset.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue
lib/vue-lib/src/design-system/tabs/TabGroup.vue

- New "Compact" VormInput style for giving the UI a unified compact look
- Compactified various forms in the UI using it to replace the "web form" look
- Fixed a few truncation bugs with the TruncateWithTooltip component
- Fixed a few TabGroup bugs in the CustomizeAssets screen
- Added filters to the AssetPalette, minor improvements to FilterPill
- Minor padding fixes in AttributesPanelItem
- Fixed ColorPicker so it doesn't get hidden via overflow-hidden
- Fixed language consistency in the ModelingRightClickMenu
- Prevented NodeSkeleton from shrinking in flex containers
- Fixed truncation and overflow issues in AttributeBindings

fix(web) - many bug fixes and UI improvements pt 2!

---

lib/dal-test/src/helpers.rs
lib/dal/src/component.rs
lib/dal/src/component/frame.rs
lib/dal/src/job/definition/dependent_values_update.rs
lib/dal/tests/integration_test/frame.rs

This PR does the following: 
**Add precision to which values need to rerun when upserting/orphaning components by caching the state of inferred connections and only rerunning what has been deleted/added/changed**
- When changes are made to a component tree, we now correctly capture the initial, in-between (in the case of upsert), and final state of the tree in terms of all of the various inferred connections. 
- Based on the deltas of state as we make changes to the tree, we calculate which input sockets have new/different/changed inferred connections to output sockets and enqueue them in DVU (forcing them to rerun)
- For example, with a deep-ish nested tree, if you orphan a frame in the middle, the tree is split into two, and we need to walk both trees to find what needs to be rerun, as …

Frames fixes, features, and more precision when enqueuing DVU

---

lib/dal/src/component.rs

<div><img src="https://media2.giphy.com/media/A4SLK7bj3bCYdiHWpL/giphy.gif?cid=5a38a5a2e5h9inqefu0o9b1d3x4me4ioz5bkvhy4qjs7489r&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:215px;width:300px"/><br/>via <a href="https://giphy.com/fallontonight/">The Tonight Show Starring Jimmy Fallon</a> on <a href="https://giphy.com/gifs/fallontonight-jimmy-fallon-tonight-show-A4SLK7bj3bCYdiHWpL">GIPHY</a></div>

fix(dal) - drop span to debug level

---

app/web/src/api/sdf/dal/diagram.ts
app/web/src/api/sdf/dal/prop.ts
app/web/src/api/sdf/dal/schema.ts
app/web/src/components/FuncEditor/AttributeBindings.vue
app/web/src/components/FuncEditor/AttributeBindingsModal.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/store/asset.store.ts
app/web/src/store/func/funcs.store.ts

fix: function binding list shows correct values after sv regeneration

---

app/web/src/store/asset.store.ts

Do not allow the same asset to be added to a list more than once

---

.github/workflows/deploy-stack.yml

chore: small workflow name tweak

---

flake.nix

This will make it available to veritech for execution

BUG-398: add fastly to the cli

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/FuncEditor/AttributeBindings.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/store/asset.store.ts
app/web/src/store/change_sets.store.ts

detach func fix, close fns windows appropriately, abandon changeset fix

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/ColorPicker.vue
app/web/src/components/FuncEditor/CodeGenerationDetails.vue
app/web/src/components/FuncEditor/FuncArguments.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/LeafInputs.vue
app/web/src/components/FuncEditor/RunOnSelector.vue
app/web/src/components/IconButton.vue
app/web/src/components/SiCheckBox.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/store/func/funcs.store.ts
app/web/src/store/module.store.ts
app/web/src/store/secrets.store.ts
lib/vue-lib/src/design-system/modals/Modal.vue

- fix "Creating Change Set…" hang bug on errors in Customize screen
- continuing improvements to customize assets UI for functions
- fix for bug where empty state showed in right rail even when it was not an empty state
- minor fixes to IconButtons in WorkspaceCustomize
- UI improvements to AssetFuncAttachModal

many UI improvements and bug fixes pt 3

---

app/web/src/store/module.store.ts

Fix: on promote or reject, fix the url selection

---

app/web/src/components/SiFuncListItem.vue

Only highlight the displayed func in the editor

---

app/web/src/components/AssetListPanel.vue

fix: always show contribute today

---

.github/workflows/deploy-on-main.yml
.github/workflows/e2e-validation.yml
app/web/cypress/e2e/authentication/login.cy.ts
app/web/cypress/e2e/authentication/logout.cy.ts
app/web/cypress/e2e/modelling-functionality/create-component.cy.ts
app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts
app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts
app/web/cypress/e2e/web-functionality/get-summary.cy.ts
app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts
app/web/cypress/support/auth-provider-commands/auth0.ts
app/web/cypress/support/component-actions/create.ts
app/web/src/components/FuncEditor/FuncDetails.vue

Minimum viable product to get all Cypress tests passing against a remote or local environment.

fix(cypress): amend minor issues in cypress tests to get them passing again

---

app/web/src/components/AssetEditorTabs.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/WorkspaceCustomizeEmptyState.vue

Fix authoring empty states when selecting multiple assets

---

app/web/src/components/AssetCard.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/FilterPill.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/components/IconButton.vue
app/web/src/components/SidebarSubpanelTitle.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
lib/vue-lib/src/design-system/general/ErrorMessage.vue
lib/vue-lib/src/design-system/icons/icon_set.ts

- Improve UI for the Test tab on the CustomizeAsset screen, disable the panel expanding
- finish improvements to the Properties tab on the CustomizeAsset screen, better icons
- make the functions panel section collapse when you select multiple assets
- fix search filter padding issues on Customize screen
- IconButton improvements, new ErrorMessage variant

ui improvements and bug fixes pt 4

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/store/asset.store.ts
app/web/src/store/feature_flags.store.ts
lib/dal/src/attribute/prototype.rs
lib/dal/src/attribute/prototype/argument.rs
lib/dal/src/diagram.rs
lib/dal/src/history_event.rs
lib/dal/src/layer_db_types/content_types.rs
lib/dal/src/pkg/export.rs
lib/dal/src/pkg/import.rs
lib/dal/src/prop.rs
lib/dal/src/schema/variant.rs
lib/dal/src/schema/variant/authoring.rs
lib/dal/src/schema/variant/metadata_view.rs
lib/dal/src/schema/view.rs
lib/dal/src/socket/input.rs
lib/dal/src/socket/output.rs
lib/dal/src/user.rs
lib/dal/tests/integration_test/schema/variant.rs
lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs
lib/sdf-server/src/server/service/graphviz.rs
lib/sdf-server/src/server/service/variant.rs
lib/sdf-server/src/server/service/variant/create_unlocked_copy.rs
lib/sdf-server/src/server/service/variant/get_variant.rs

also:
- Add is_locked, make display_name required, rename name to version on schema variant
- Add upgrade code on schema variant content
- Unlock variant button on UI, behind feature flag

feat(dal,sdf,web): Endpoint to create unlocked sv copy

---

app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
lib/dal/src/action/prototype.rs
lib/dal/src/func/authoring.rs
lib/dal/tests/integration_test/func/authoring/save_func/detach.rs
lib/sdf-server/src/server/service/func/delete_func.rs

<div><img src="https://media0.giphy.com/media/xULW8N9O5WD32L5052/giphy.gif?cid=5a38a5a2rjxm94xzfse8ar5v0cc1p9poa62hs0h2qdedyhym&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/><br/>via <a href="https://giphy.com/pixelsbyskab/">Skab</a> on <a href="https://giphy.com/gifs/bird-homer-simpson-xULW8N9O5WD32L5052">GIPHY</a></div>

Fix detachment for current schema variant. Allow users to delete funcs with attachments

---

app/web/src/components/AttributesPanel/AttributesPanelItem.vue

Now you can delete Arrays or Maps which are children of Arrays or Maps.
All empty props that are controlled by a parent now hide and a number of hidden props is shown in the parent.

fix(web) - BUG-412 and ENG-2585

---

app/web/src/components/Actions/ActionCard.vue
lib/sdf-server/src/server/service/action.rs
lib/sdf-server/src/server/service/action/list_actions.rs

fix(sdf, web): Ensure we add a description of the manual actions to run

---

app/web/src/assets/static/editor_typescript.txt
bin/lang-js/src/asset_builder.ts
lib/dal/src/func/authoring/data/ts_types/asset_types_with_secrets.d.ts

feat(sdf): Add deprecation warning to setValueFrom functionality

---

bin/veritech/src/args.rs
lib/dal/tests/integration_test/secret/with_actions.rs

I did some things wrongly and this was merged by mistake. Fixing! 
Also testing failing tests should block merge...

chore: bad merge from testing merge queues

---

.github/workflows/e2e-validation.yml

Let's go poke SDF a few times to make sure it is up before we attempt to run the Cypress tests. <img src="https://media4.giphy.com/media/1dLpUaRIQ5kXaIf0DN/giphy.gif"/>

feat: healthcheck SDF before running Cypress tests.

---

lib/dal/src/component.rs
lib/dal/src/diagram.rs
lib/dal/src/pkg/import.rs
lib/dal/src/schema/variant.rs
lib/dal/src/schema/variant/authoring.rs
lib/dal/src/workspace_snapshot.rs
lib/dal/src/workspace_snapshot/graph.rs
lib/dal/src/workspace_snapshot/node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
lib/dal/tests/integration_test/component/upgrade.rs
lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs
lib/dal/tests/integration_test/schema/variant/authoring/update_variant.rs
lib/sdf-server/src/server/server.rs
lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/change_set/apply_change_set.rs
lib/sdf-server/src/server/service/component/upgrade.rs
lib/sdf-server/src/server/service/v2/variant.rs
lib/sdf-server/src/server/service/variant/clone_variant.rs

feat(dal, sdf, rebaser): Only allow editing unlocked components

---

app/web/src/components/AssetListPanel.vue
app/web/src/components/AssetNameModal.vue
app/web/src/store/asset.store.ts
lib/dal/src/schema/variant.rs
lib/sdf-server/src/server/service/variant/create_variant.rs

Also show request status on asset creation modal

fix(sdf, web): Don't error out UI on asset creation

---

.gitignore
app/docs/BUCK
app/docs/package.json
app/docs/src/.vitepress/config.ts
app/docs/src/changelog/index.md
app/docs/src/index.md
app/docs/src/reference/index.md
app/docs/src/tutorials/index.md
app/docs/tsconfig.json
dev/Tiltfile
pnpm-lock.yaml
pnpm-workspace.yaml

This will start on localhost:5173 - we need to be able to wire in the --host endpoint for external runs
There is a fake page added to this for now so we get something and this is added to tiltfile so we can link to the docs site
There is no work for building and deploying this site yet

feat(docs): Initial Scaffolding of the Docs Site

---

app/web/src/api/sdf/dal/schema.ts
app/web/src/components/AssetCard.vue
app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/AssetEditor.vue
app/web/src/components/AssetFuncAttachDropdown.vue
app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/components/CodeEditor.vue
app/web/src/components/FuncEditor/ActionDetails.vue
app/web/src/components/FuncEditor/AttributeBindings.vue
app/web/src/components/FuncEditor/AttributeBindingsModal.vue
app/web/src/components/FuncEditor/CodeGenerationDetails.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncEditor.vue
app/web/src/components/FuncEditor/LeafInputs.vue
app/web/src/components/FuncEditor/QualificationDetails.vue
app/web/src/store/asset.store.ts
app/web/src/store/components.store.ts
app/web/src/store/feature_flags.store.ts
app/web/src/store/func/funcs.store.ts
lib/sdf-server/src/server/service/variant/regenerate_variant.rs

Has some fixes for code editor bugginess as well
Needs Brit's endpoints to work

Locked funcs!

---

app/web/src/components/AssetListItem.vue
app/web/src/components/SiFuncListItem.vue

Show editing pill on funcs

---

app/web/src/components/FuncEditor/FuncEditor.vue
app/web/src/store/func/funcs.store.ts
lib/sdf-server/src/server/service/v2/func.rs

Also never try to save locked funcs

fix: Delete unlocked funcs

---

app/docs/src/tutorials/orientation.md

A couple paragraphs of an orientation. Experimenting with using Hemmingway to keep the voice at a consistent, no frills tutorial level. (And doing some background experimenting with Runway for AI generated voice-overs.)
Worth merging as a sample of the tutorial/reference docs tone.

feat(doc): simple orientation tutorial

---

lib/sdf-server/src/server/service/module/install_module.rs

This will allow us to catch installing old development modules that have multiple schemas

fix(sdf): Update install_module to allow multiple schema packages

---

app/web/src/api/sdf/dal/func.ts
app/web/src/components/AssetActionsDetails.vue
app/web/src/components/AssetCard.vue
app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/CodeEditor.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncEditor.vue
app/web/src/components/toasts/FiveHundredError.vue
app/web/src/store/asset.store.ts
app/web/src/store/components.store.ts
app/web/src/store/func/funcs.store.ts
lib/dal/src/func/binding/action.rs
lib/dal/src/schema/variant.rs
lib/sdf-server/src/server/service/v2/func/binding/create_binding.rs
lib/sdf-server/src/server/service/v2/func/create_func.rs
lib/sdf-server/src/server/service/variant/create_unlocked_copy.rs

1. alpha sort variants and actions
2. fix too-big modal
3. move code editor types to match backend changes
4. reactivity fixes

Last Chainsaw Cleanup

---

app/web/src/components/AssetCard.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/store/asset.store.ts

The problem was that I was sending `schemaId` not `schemaVariantId`. But I also renamed, and refactored the func for clarity.

Fix: unlock button was showing where it should not

---

app/web/src/store/asset.store.ts
lib/dal/src/module.rs
lib/dal/src/schema/variant.rs
lib/sdf-server/src/server/service/module/export_module.rs
lib/sdf-server/src/server/service/v2/variant.rs
lib/si-frontend-types-rs/src/schema_variant.rs

feat: populate canContribute for schema variants

---

app/web/src/components/AssetFuncAttachModal.vue
app/web/src/components/SelectMenu.vue

I also swapped the <VormInput> for <SelectMenu> so all the dropdowns in this modal look the same. I needed to copy a bit of the input styling from elsewhere for consistency.

Feat: <SelectMenu> now has `canFilter` prop

---

app/web/src/components/CodeEditor.vue

When swapping between modeling and authoring the wrong code was being displayed.
There were two watchers here attempting to do the same thing. Removed one. Fixed the problem.
Also cleaned up `if props.id`... it is always a string now, no more `undefined`

More editor clean up

---

app/web/public/_redirects

If the Netlify docs aren't a bunch of liars then this should redirect api calls to the right place via a rewrite which should side-step CORS issues. We'll see.

feat: redirect api requests to appropriate location

---

lib/sdf-server/src/server/routes.rs

Relevant change:
```rust
// allows us to be permissive about cors from our owned subdomains
.layer(CorsLayer::new().allow_origin(AllowOrigin::predicate(
|origin: &HeaderValue, _| origin.as_bytes().ends_with(b".systeminit.com"),
)));
```
This allows us to accept requests from our domains to the relevant apis. I want to host web on netlify and point it to `api.tools.systeminit.com`, but cors makes this tricky and the netlify rewrite rules do not work for our needs. I _think_ this will allow us to make requests from `tools.systeminit.com -> api.tools.systeminit.com` without issue

feat: allow cors origin from our subdomains in sdf

---

app/web/src/components/AssetFuncAttachModal.vue

Feat: add filter to all dropdowns in attach func

---

flake.nix

fixed indentation and added doctl to the nix dependencies

Add digitalocean support to cyclone

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/components/FuncEditor/FuncArguments.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/store/asset.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue

Assorted authoring fixes

---

.github/workflows/deploy-service.yml
app/web/public/_redirects

S3 + Cloudfront > Netlify. This action will push web to the bucket that now hosts web. Static content is pretty neat.

feat: deploy web to S3 bucket

---

app/web/src/components/FuncEditor/AttributeBindings.vue

fix: Show input socket bindings

---

lib/dal/tests/integration_test/func/authoring.rs
lib/dal/tests/integration_test/schema/variant/authoring.rs
lib/dal/tests/integration_test/schema/variant/authoring/unlock_and_edit_variant.rs

chore(dal): Testing that unlocked funcs get locked on apply

---

app/web/src/components/EditingPill.vue

Fix editing pill text color and reactivity

---

lib/dal/src/component/frame.rs
lib/dal/tests/integration_test/frame.rs

While there is never supposed to be more than one *incoming* `FrameContains` edge, it is apparently possible to get into a situation where there is more than one. While we still need to improve the semantic conflict detection logic to ensure this doesn't happen in the first place, by allowing `Frame::orphan_child` to remove _all_ parents, we at least have an escape hatch to recover any workspace snapshots that have gotten into this situation.

Allow Frame::orphan_child to remove all incoming FrameContains edges

---

bin/auth-api/src/services/workspaces.service.ts

We want to pass the instanceUrl and instanceEnvType to posthog

feat(auth-api): Enhance create-workspace event details

---

app/docs/.vitepress/config.ts
app/docs/src/tutorials/creating-new-assets.md
app/docs/src/tutorials/index.md

Seeing what it's like to write tutorials in plain language with video.

feat(docs): sample of a new asset creation tutorial

---

app/docs/src/reference/vocabulary.md
app/docs/src/tutorials/creating-new-assets.md
app/docs/src/tutorials/orientation.md

This adds a sample getting started tutorial, and a vocabulary page.

docs: adding orientation and vocabulary

---

app/web/src/components/CustomizeTabs.vue
app/web/src/components/InstallAsset.vue
app/web/src/components/InstallAssetsPanel.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/components/Workspace/WorkspaceCustomizeModules.vue
app/web/src/components/modules/ModuleDisplay.vue
app/web/src/components/toasts/FiveHundredError.vue
app/web/src/router.ts
app/web/src/store/asset.store.ts
app/web/src/store/module.store.ts

Note: the intent is to display all the function code in the center pane. But, local development against the remote S3 bucket doesn't quite work. 🤞 we get something close to decent, and we can massage the UI as we go.
Also: fix the display of a long non-breaking URL string in the error modal.

Show modules to install, and let people install them!

---

app/web/cypress/e2e/authentication/logout.cy.ts

fixed cypress test for logout

---

app/web/cypress/e2e/authentication/logout.cy.ts
app/web/src/components/layout/navbar/ProfileButton.vue

okay now the test should be fixed

---

lib/module-index-server/src/routes/get_module_details_route.rs

We want to return the full module details response rather than jsut the model

fix(module-index): Ensure that we can get module details by id

---

lib/dal/src/pkg/import.rs

By searching the past hashes, this will ensure that a related module will install as a new variant rather than alongside it
Without this, in tools prod - we could see that installing a related schema (i.e. a schema related by past hashes) was installing as a new schema because the schema ids didn't match. Now we can check both

fix(dal): Ensure that we search the past_hashes when installing a schema

---

app/auth-portal/src/components/WorkspaceLinkWidget.vue
app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/auth-portal/src/pages/WorkspacesPage.vue
app/auth-portal/src/store/workspaces.store.ts
lib/vue-lib/src/design-system/icons/icon_set.ts

Also change the icon to make SaaS be a cloud and the others be a laptop

feat(auth-portal): Sort SaaS workspaces first in workspace list

---

app/auth-portal/src/pages/ProfilePage.vue
app/auth-portal/src/store/feature_flags.store.ts

This was causing some people to go directly to a workspace that they didn't have....

fix(auth-portal): Enable a feature flag for the new simplified signup flow

---

lib/dal/src/component.rs
lib/dal/src/job/definition/action.rs

The way we were doing this before resulted in some races if multiple delete actions were running in parallel, each wouldn't know about the other and so we'd never end up removing the parent frames.  This moves the check to after the func has run and we've removed the component that needed to be deleted, so now there might be races to delete the frames but that's ok, because we want them deleted.  If there's a conflict when deleting those parent frames, we won't retry (but we'll warn) but also won't fail the job as a whole. 
<div><img src="https://media2.giphy.com/media/3o6nV8mjvp0Ys8j4iI/giphy.gif?cid=5a38a5a2io4hs90tx7uqpaxf34fmvu1hg5ajvscrtp7ir8j5&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/><br/>via <a …

fix(dal): check for components that can be deleted at the end of the action job

---

app/docs/src/tutorials/getting-started.md

Adds an embed for the getting started tutorial video

docs: adding video for tutorial video

---

bin/auth-api/prisma/migrations/20240722190334_default_workspace/migration.sql
bin/auth-api/prisma/schema.prisma
bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/users.service.ts
bin/auth-api/src/services/workspaces.service.ts
bin/auth-api/test/auth-routes.test.ts
bin/auth-api/test/helpers/dummy-factory.ts

This is the first step of the work for this and it's related to the auth-api - we don't ever set this value right now, we just have a notion of it in the system

feat(auth-api): Let workspaces have a default set

---

bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/users.service.ts

The authportal has been wired up to send the correct data now so the auth-api can remove the hard coded nature of the "false"

fix(auth-api): The Auth API now accepts if a workspace is the default or not

---

lib/dal/src/pkg/import.rs

<div><img src="https://media4.giphy.com/media/QNFhOolVeCzPQ2Mx85/200.gif?cid=5a38a5a2w1ln3wkm25svp6qjuw2fzlbmxgxzp4vib1dsxypz&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/XRayAutomation/">XRay.Tech</a> on <a href="https://giphy.com/gifs/checkmatedigital-code-coding-monkey-QNFhOolVeCzPQ2Mx85">GIPHY</a></div>

fix(dal): Don't keep looping through past hashes if you find an existing schema when importing a pkg

---

bin/auth-api/src/routes/workspace.routes.ts

This is locked down to systeminit.com users only!

feat(auth-api): Adds a route that allows creating a user an auth workspace

---

.github/workflows/community-check.yml
CONTRIBUTORS.md

Adding jkeiser to staff

---

app/auth-portal/src/pages/SetupProductionUser.vue
app/auth-portal/src/router.ts
app/auth-portal/src/store/feature_flags.store.ts
app/auth-portal/src/store/workspaces.store.ts

First thing it does is to allow a user to be able to get a production saas while we are in invite mode

feat(auth-portal): Simple workspace admin page

---

app/web/src/App.vue
app/web/src/pages/WorkspaceSinglePage.vue
app/web/src/store/auth.store.ts

This wasn't working in App.vue so we needed to move it to WorkspaceSinglePage - this is guaranteed to be an authenticated user and we are using localstorage to control that we don't serve the popup on a page refresh

fix(web): Rework the first time modal tutorial experience

---

app/web/src/store/func/funcs.store.ts

ChangeSet Apply loads the Func List

---

.github/workflows/try.yml

more `/try` changes. I add steps to I can test this within PRs more directly.

feat: try, try again

---

.github/workflows/try.yml

feat: /try command kicking off buildkite builds

---

lib/module-index-client/src/lib.rs
lib/sdf-server/src/server/service/v2/module/sync.rs

Compare upgradeable modules to builtins list

---

app/web/src/main.ts
lib/vue-lib/package.json
lib/vue-lib/src/pinia/pinia_api_tools.ts
pnpm-lock.yaml

It looks like this in Honeycomb

Observability: ignore urls, create pinia-http-error

---

.github/workflows/try.yml

fix: scope try to pull request branch

---

lib/dal/src/workspace.rs

This change results in us always re-installing latest builtins every time SDF starts up.  This means we don't ever worry about updating existing builtins and newly created workspaces will have a more-up-to-date set of builtins. This also lets us create new workspaces in Tools Prod (where now the default workspace for Tools Prod is all sorts of wonky after months of iteration in this space). 
<div><img src="https://media4.giphy.com/media/BpGWitbFZflfSUYuZ9/giphy.gif?cid=5a38a5a2a73dftn1bo31cugr1vbwf77g1dmxdolqgkhg7yr5&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:249px;width:300px"/><br/>via <a href="https://giphy.com/theoffice/">The Office</a> on <a href="https://giphy.com/gifs/BpGWitbFZflfSUYuZ9">GIPHY</a></div>

fix(dal): always remigrate the default workspace on startup

---

.github/workflows/crons.yml
app/web/cypress/e2e/authentication/logout.cy.ts
app/web/cypress/e2e/modelling-functionality/create-component.cy.ts
app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts
app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts

fix: handle the tutorial popup in cypress

---

app/web/src/components/CodeViewer.vue
app/web/src/components/InstallAsset.vue
app/web/src/components/InstallAssetsPanel.vue
app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue
app/web/src/components/modules/ModuleListItem.vue
app/web/src/components/modules/ModuleListPanel.vue
lib/vue-lib/src/design-system/tree/TreeNode.vue

feat(web) - better UI for New Assets tab in Customize screen

---

app/docs/src/tutorials/creating-new-assets.md

(docs) Remove arcade video from new asset

---

bin/lang-js/src/sandbox/exec.ts

This makes it so we turn stdin off by default, but if a user explicitly passes in an `input` we will set it to `pipe` so it works as expected. This should prevent unexpected `read` calls (like docker login asking for creds) and still allow users to pass input if they need.
This fixes the butane qualification.

feat: dynamic stdin for langjs

---

lib/dal/src/module.rs
lib/dal/tests/integration_test/module.rs
lib/sdf-server/src/server/service/v2/module/contribute.rs

Our trigger for slack wasn't firing correctly

fix(dal): Ensure we send the correct contribute details to posthog

---

app/web/cypress.config.ts
app/web/cypress/e2e/authentication/logout.cy.ts
app/web/cypress/e2e/modelling-functionality/create-component.cy.ts
app/web/cypress/e2e/modelling-functionality/delete-component.cy.ts
app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts
app/web/cypress/global.d.ts
app/web/cypress/support/commands.ts
app/web/src/components/AssetPalette.vue
app/web/src/pages/WorkspaceSinglePage.vue

tests now check for page loading and the modal properly

---

app/web/src/components/Workspace/WorkspaceVizSchemaVariant.vue
app/web/src/store/viz.store.ts

feat: Add edge direction and label to viz

---

app/docs/package.json
app/docs/src/.vitepress/config.ts
app/docs/src/.vitepress/theme/Layout.vue
app/docs/src/.vitepress/theme/index.ts
pnpm-lock.yaml

Now all images used in the docs site have medium style lightbox zooming enabled.

docs: add zoom to images on the docs site

---

Cargo.lock
dev/prometheus-config/config.yml
lib/si-pool-noodle/src/pool_noodle.rs
lib/telemetry-application-rs/src/lib.rs
lib/telemetry-utils-rs/src/lib.rs
lib/veritech-server/BUCK
lib/veritech-server/Cargo.toml
lib/veritech-server/src/server.rs

`metric!(counter.i.am.a.metric = 1)` now works correctly! The filters and macro needed to be modified to create and filter the metadata correctly. Grafana and prometheus now work in tilt!

feat: metrics macro and function metric tracking

---

app/web/src/components/InstallAsset.vue
app/web/src/components/InstallAssetsPanel.vue
app/web/src/components/toasts/FiveHundredError.vue
lib/vue-lib/src/design-system/tree/TreeNode.vue

feat(web) - final UI improvements to New Assets screen

---

lib/dal/src/action.rs
lib/dal/src/change_set.rs
lib/dal/src/component/frame.rs
lib/dal/src/context.rs
lib/dal/src/func/runner.rs
lib/dal/src/job/definition/action.rs
lib/dal/src/job/definition/dependent_values_update.rs
lib/rebaser-server/src/change_set_requests/handlers.rs
lib/rebaser-server/src/rebase.rs
lib/rebaser-server/src/server.rs
lib/sdf-server/src/server.rs
lib/sdf-server/src/server/routes.rs
lib/sdf-server/src/server/service.rs
lib/sdf-server/src/server/service/async_route.rs
lib/sdf-server/src/server/service/change_set.rs
lib/sdf-server/src/server/service/component.rs
lib/sdf-server/src/server/service/dev.rs
lib/sdf-server/src/server/service/diagram.rs
lib/sdf-server/src/server/service/graphviz.rs
lib/sdf-server/src/server/service/module.rs
lib/sdf-server/src/server/service/node_debug.rs
lib/sdf-server/src/server/service/qualification.rs
lib/sdf-server/src/server/service/secret.rs
lib/sdf-server/src/server/service/session.rs
lib/sdf-server/src/server/service/v2/func.rs
lib/sdf-server/src/server/service/v2/module.rs
lib/sdf-server/src/server/service/v2/variant.rs
lib/sdf-server/src/server/service/variant.rs
lib/sdf-server/src/server/service/ws.rs

This is is the long way to add error messages until we add the right middleware but it's a stop gap in the short term until we fix this the right way.

Add error events to SDF routes and some other helpful tracing

---

lib/dal/src/job/definition/action.rs

This PR retries removing actions nodes upon action completion. This is a workaround for another bug where a `RemoveEdge` update is not being detected for children of the action category node when the `to_rebase` snapshot address has changed in between commit time in the job and the time that the rebaser performs update and conflict detection.

Retry removing action nodes upon completion

---

component/toolbox/scripts/upgrade

Basic implementation of a toolbox improvement allowing you to run the toolbox upgrade script with no user interaction.
Next steps will be implementing the change within CI.

feat: add automatic option to running the upgrade toolbox

---

app/auth-portal/src/store/feature_flags.store.ts
app/auth-portal/src/store/onboarding.store.ts
app/web/src/main.ts
app/web/src/store/actions.store.ts
app/web/src/store/asset.store.ts
app/web/src/store/auth.store.ts
app/web/src/store/change_sets.store.ts
app/web/src/store/component_attributes.store.ts
app/web/src/store/components.store.ts
app/web/src/store/counter.store.ts
app/web/src/store/feature_flags.store.ts
app/web/src/store/func/funcs.store.ts
app/web/src/store/func_runs.store.ts
app/web/src/store/module.store.ts
app/web/src/store/presence.store.ts
app/web/src/store/qualifications.store.ts
app/web/src/store/secrets.store.ts
app/web/src/store/status.store.ts
app/web/src/store/viz.store.ts
app/web/src/store/workspaces.store.ts
dev/docker-compose.platform.yml
lib/vue-lib/src/pinia/pinia_api_tools.ts
lib/vue-lib/src/pinia/pinia_hooks_plugin.ts

- Add URLPattern for grouping requests appropriately.
- Add workspace and changeset to the store definitions, add to instrumentation for all pinia calls

Replace auto-instrumentation with custom instrumentation

---

app/web/src/store/func/funcs.store.ts
lib/vue-lib/src/pinia/pinia_api_tools.ts

Fix: did not complete using the new array-based API Prefix

---

dev/datasources/datasources.yml
dev/prometheus-config/config.yml
lib/si-pool-noodle/src/pool_noodle.rs
lib/veritech-server/src/server.rs

Adds some structured metrics to pool noodle and ensures we handle errors in veritech land.

feat: add metrics for pool_noodle, handle errors in veritech

---

Cargo.lock
lib/pinga-server/BUCK
lib/pinga-server/Cargo.toml
lib/pinga-server/src/server.rs

Metrics for for the metrics god.

feat: add metrics for pinga concurrency limit

---

app/web/src/main.ts

fix: otelendpoint is undefined

---

flake.nix

Adds this to start to see how we can manage GCP infrastructure via SI

feat: add gcloud to nix flake for cylone execution usage

---

app/web/src/components/toasts/RebaseOnBase.vue
app/web/src/store/change_sets.store.ts

Clean up the rebase from head toast to reflect our new reality

---

lib/dal/src/workspace.rs

Ensure we set the workspace snapshot version to the latest when making a new workspace

fix(*): fix workspace new

---

lib/dal/examples/rebase/main.rs
lib/rebaser-server/src/rebase.rs
lib/si-layer-cache/src/activities/rebase.rs

feat(rebaser): send every batch applied to head to open change set

---

app/web/src/store/change_sets.store.ts

Small toast fixes for Rebase & Apply

---

component/deploy/docker-compose.yaml
component/init/Dockerfile
component/init/configs/prometheus.yml
component/init/docker-entrypoint.sh

Small enhancements for tuning prometheus

feat: prometheus tuning

---

app/web/src/store/change_sets.store.ts

BUG-484: code reactivity watches for change set written data

---

app/web/src/components/QualificationViewerSingle.vue

BUG-483: <pre> doesnt wrap by default, make it wrap

---

Cargo.lock
Cargo.toml
component/nats/BUCK
third-party/rust/BUCK
third-party/rust/Cargo.lock
third-party/rust/Cargo.toml
third-party/rust/fixups/ahash/fixups.toml
third-party/rust/fixups/multer/fixups.toml
third-party/rust/fixups/unicase/fixups.toml

build(deps): update to NATS server 2.10.8 & patched client 0.35.1

---

app/web/src/store/change_sets.store.ts
app/web/src/store/module.store.ts

1. Fix to abandon changeset message
2. Reload the new modules list after installing from the list

Fix: BUG-492 and BUG-490

---

component/init/configs/service.toml

Make the pinga concurrency limit configurable via ssm

chore: make pinga concurrency configurable

---

lib/rebaser-server/src/dvu_debouncer_task.rs

This change makes several timing interval adjustments which likely have
led to the "2 leaders" issue as seen in larger deployments.
Additionally, there are several fixes for pessimistic scenarios where
multiple debouncer tasks believe themselves to be the leader for the
same change set.
Timing Window Overlaps
----------------------
There are 3 timings here to consider:
1. the max age (that is, a "ttl") of a key in this K/V bucket
2. the "keepalive" interval (how frequent a leader updates the key to
reset the key's ttl)
3. the "check for missing key" interval (how often to check whether or
not a key is not present in the store)
Before these changes, if the max age of a key would be 5 seconds, then
the keepalive interval was 5 * 0.85 = 4.25 seconds and the missing key
interval was 5 seconds …

fix(rebaser): resolve timing window overlaps & add more resiliency

---

lib/dal/src/action/dependency_graph.rs
lib/dal/src/component/socket.rs
lib/dal/src/diagram.rs

So we can get better visibility into frames

Add some info spans

---

bin/cyclone/Cargo.toml
lib/cyclone-server/Cargo.toml
lib/si-firecracker/src/errors.rs
lib/si-firecracker/src/firecracker.rs
lib/si-firecracker/src/lib.rs
lib/si-firecracker/src/stream.rs
lib/si-pool-noodle/src/instance/cyclone/local_uds.rs

chore: cargo cfg for linux-only targets

---

lib/dal/src/attribute/value.rs
lib/dal/src/component/inferred_connection_graph.rs
lib/dal/src/component/socket.rs
lib/dal/src/job/definition/action.rs
lib/dal/src/job/definition/compute_validation.rs
lib/dal/src/job/definition/dependent_values_update.rs

Also adds a counter specific to the pinga jobs
<div><img src="https://media0.giphy.com/media/afvFQ6UbLbMFdQN3PA/200.gif?cid=5a38a5a27leqdsfy0sztz36vgksbo3or95f9crigmmbt5f97&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:171px;width:300px"/><br/>via <a href="https://giphy.com/snl/">Saturday Night Live</a> on <a href="https://giphy.com/gifs/snl-saturday-night-live-season-47-afvFQ6UbLbMFdQN3PA">GIPHY</a></div>

Drop Otel to Info for Frames Spans

---

lib/rebaser-server/src/dvu_debouncer_task.rs

This change adds one more internal state to the dependent values update task "debouncer" task when running as leader:
`DebouncerState::AbandoningLeadership`. When a key keepalive write fails, the returned state is now `AbandoningLeadership`, ensuring that a final purge of the key will not be attempted (remember that a purge or delete is another write to the key which will cause a revision update).
With this logic fix, when a leader notices write corruption to its key, it will now immediately stop writing to the key, transition back into `WaitingToBecomeLeader` and thus should allow the key to age out (assuming no other writers are active).

fix(rebaser): when error occurs, abandon leadership & don't purge key

---

app/auth-portal/src/App.vue
app/auth-portal/src/pages/QuarantineNoticePage.vue
app/auth-portal/src/pages/SetupProductionUser.vue
app/auth-portal/src/router.ts
app/auth-portal/src/store/auth.store.ts
bin/auth-api/.env
bin/auth-api/.eslintrc.cjs
bin/auth-api/prisma/migrations/20240819212424_add_quarantined_to_user_and_workspace/migration.sql
bin/auth-api/prisma/schema.prisma
bin/auth-api/src/routes/user.routes.ts
bin/auth-api/src/routes/workspace.routes.ts
dev/docker-compose.platform.yml

feat: Allow user quarantining from the UI

---

app/auth-portal/src/pages/QuarantineNoticePage.vue
app/auth-portal/src/pages/SetupProductionUser.vue
app/auth-portal/src/store/workspaces.store.ts
bin/auth-api/src/routes/index.ts
bin/auth-api/src/routes/user.routes.ts
bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/users.service.ts
bin/auth-api/src/services/workspaces.service.ts

feat(auth): Quarantine workspaces

---

lib/dal/src/job/definition/dependent_values_update.rs

If a function execution fails in the DVU, we will not "finish" the component if there are remaining values for that component that did not get processed. Ensure we send those messages so the frontend does not spin forever.

fix(dal): send status finished for downstream values of failed values

---

app/web/src/components/FuncEditor/LeafInputs.vue

hotfix: remove checkbox, revert commit to get it back

---

app/web/src/components/FuncEditor/CodeGenerationDetails.vue
app/web/src/components/FuncEditor/LeafInputs.vue
app/web/src/components/FuncEditor/QualificationDetails.vue

Can only use the code checkbox for qualification functions

---

lib/dal/tests/integration_test/func/authoring/binding.rs
lib/sdf-server/src/server/service/v2/func.rs
lib/sdf-server/src/server/service/v2/func/binding/create_binding.rs
lib/sdf-server/src/server/service/v2/func/binding/update_binding.rs

If we can't update or create a binding because it will result in a cycle, we will return a 422! 
<div><img src="https://media0.giphy.com/media/jhLEOwTuBE0be8KdtQ/giphy.gif?cid=5a38a5a2o0eyhkuvzgcm4gcj3dfbkg1usj11pak4mpm0ogtp&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/trickartt/">Ricky Trickartt</a> on <a href="https://giphy.com/gifs/cycling-post-it-note-trickartt-jhLEOwTuBE0be8KdtQ">GIPHY</a></div>

fix(sdf): Add cycle check guards when updating or creating func bindings

---

app/web/src/components/CodeEditor.vue

This definitely removes the problem. And I dont think it introduces any others

---

lib/pinga-server/src/server.rs
lib/rebaser-server/src/change_set_requests.rs
lib/veritech-server/src/server.rs

This change updates the naxum setup for Pinga/Rebaser/Veritech to use a work-limiting concurrency and will allow work-in-flight to complete when a graceful shutdown is requested (via a `SIGINT` or `SIGTERM`). The shutdown behavior is now closer to that of the example provided in #4444 which delivered the updated naxum functionality.
Closes: ENG-2655

feat(pinga,rebaser,veritech): impl work-draining graceful shutdown

---

component/nats/BUCK

See: https://github.com/nats-io/nats-server/releases/tag/v2.10.19

build(deps): upgrade to NATS server 2.10.19

---

app/web/src/components/Actions/ActionWidget.vue
app/web/src/components/AttributesPanel/AttributesPanel.vue
app/web/src/components/AttributesPanel/AttributesPanelItem.vue
app/web/src/components/ModelingDiagram/DiagramHelpModal.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
lib/vue-lib/src/design-system/icons/icon_set.ts
lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue

https://github.com/user-attachments/assets/43419b1c-2d06-45d2-8b78-9b7d0b27488f

link from Action to the associated func in dropdown and Actions tab

---

app/web/src/components/ModelingDiagram/ModelingDiagram.vue

Dragging components already did this, so it was EZ to apply to edge drawing

BUG-491: drawing an edge should pan diagram at its edges

---

app/web/src/components/ChangesPanelHistory.vue

Fix action history timestamp for head

---

app/web/src/components/FuncEditor/FuncDetails.vue

`blur` is firing _after_ the `selectedFunc` has changed... so, save from within the watcher before resetting the data... and in the `blur` detect no-ops and don't fire a save

Fix: when switching functions after editing data was being saved to the wrong func

---

.github/workflows/deploy-on-main.yml
BUCK

Change the pipeline tag trigger as per si-ci.
Add a "build the world" change so that it tests it properly.

chore: amend pipeline trigger to be on release/ not deploy/

---

BUCK

si-ci binary was not updated, now it is.
Re-check that things look good

chore: dummy commit to double check

---

lib/sdf-server/src/server/routes.rs

This moves the route for the health endpoint to after the maintenance mode check so it is still served when we are in maintenance mode.

feat: serve healthcheck endpoint in maintenance mode.

---

app/web/package.json
app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
app/web/src/store/admin.store.ts
app/web/tsconfig.json
lib/dal/src/change_set.rs
lib/dal/src/workspace.rs
lib/sdf-server/src/server/service/v2.rs
lib/sdf-server/src/server/service/v2/admin.rs
lib/sdf-server/src/server/service/v2/admin/get_snapshot.rs
lib/sdf-server/src/server/service/v2/admin/kill_execution.rs
lib/sdf-server/src/server/service/v2/admin/list_change_sets.rs
lib/sdf-server/src/server/service/v2/admin/list_workspaces.rs
pnpm-lock.yaml

Adds a workspace and changeset picker, with the ability to download a snapshot to disk directly from SDF.

feat(sdf-server,dal,web): Download workspace snapshots in Admin panel

---

lib/dal/src/workspace_snapshot/migrator.rs

If the content is missing for a snapshot the snapshot is unrecoverable, so we should just continue migrating the rest of the change sets in the system.

fix(dal): if content is missing mark change set as failed

---

.github/workflows/deploy-on-main.yml

Notify Slack alerts when tools prod deploys fail

fix: notify on failure to deploy to tools prod

---

DOCS.md

This PR adds both options for localstack use in the docs.

Add both options for localstack use in the docs

---

app/auth-portal/src/pages/WorkspaceDetailsPage.vue
bin/auth-api/src/routes/admin.routes.ts
bin/auth-api/src/routes/workspace.routes.ts
bin/auth-api/src/services/workspaces.service.ts

We now consistently add tracking events for the auth-api events we need to trigger pipeline from

fix(auth-portal): Track Auth API Events More Consistently

---

app/web/src/store/asset.store.ts

Fix: regenerate may send back a new variant ID, handle accordingly

---

.github/workflows/crons.yml
.github/workflows/soak-test.yml
bin/si-api-test/binary_execution_lib.ts
bin/si-api-test/main.ts
bin/si-api-test/sdf_api_client.ts
bin/si-api-test/test_execution_lib.ts
bin/si-api-test/test_helpers.ts
bin/si-api-test/tests/create_two_components_connect_and_propagate.ts

fix: refactor test profiles for api testing

---

app/docs/src/changelog/index.md

Update the docs page to include the most recent demos

feat: add more recent demos to docs site

---

app/web/src/components/ModelingView/RestoreSelectionModal.vue
app/web/src/store/components.store.ts
lib/sdf-server/src/server/service/diagram/remove_delete_intent.rs

Fix: remove delete intent doesnt need input for fromBaseChangeSet, look on the graph

---

.github/workflows/soak-test.yml
bin/si-api-test/main.ts
bin/si-api-test/sdf_api_client.ts
bin/si-api-test/test_helpers.ts

Add honeycomb  markers and more console logs to test runs

fix: add soak markers, console logs

---

.github/workflows/soak-test.yml
bin/si-api-test/binary_execution_lib.ts
bin/si-api-test/deno.json
bin/si-api-test/main.ts
bin/si-api-test/test_execution_lib.ts

feat: add concatenated test report

---

app/web/src/components/AssetCard.vue
app/web/src/components/AssetFuncListPanel.vue
app/web/src/components/AssetListItem.vue
app/web/src/components/AssetListPanel.vue
app/web/src/components/AttributesPanel/AttributesPanel.vue
app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/IconButton.vue
app/web/src/components/ModelingDiagram/DiagramGroup.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/diagram_constants.ts
app/web/src/components/ModelingDiagram/diagram_types.ts
app/web/src/store/components.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue
lib/vue-lib/src/design-system/icons/custom-icons/framedown.svg
lib/vue-lib/src/design-system/icons/custom-icons/frameup.svg

https://github.com/user-attachments/assets/157b61fe-5325-4237-b6c7-e9fa5b4cd468

feat(web) - rename components and frames on the diagram!

---

.github/workflows/soak-test.yml

Add run name to make it easier to find soak test runs

chore: update soak test run name

---

app/web/src/components/AssetCard.vue

Fix: dont let folks click on unlock button while the request is in flight

---

component/init/configs/service.toml

Add forklift data warehouse stream name passing

feat: add forklift data warehousing var

---

app/web/src/components/Actions/ActionWidget.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/func/funcs.store.ts

Currently we show "unknown" which isn't useful

fix(web): Default to func name if display name not  set

---

app/web/src/components/ModelingDiagram/DiagramControls.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingDiagram/diagram_types.ts

We are edges over by default and don't want to offer the alternative

chore(web): Remove the concept of edges over and edges under

---

app/web/src/components/AssetDetailsPanel.vue
app/web/src/store/feature_flags.store.ts
app/web/src/store/func/funcs.store.ts

*Basic* ugly UI for binding identity function

---

lib/dal/src/component.rs
lib/dal/src/func/binding/attribute.rs
lib/sdf-server/src/service/v2/func/binding/attribute/reset_attribute_binding.rs

fix: Removing a func binding sets the ap func  to si:Unset

---

lib/dal/src/func.rs

When we detach a func from an editing schema variant, it wasn't available to re-attach and we can't re-create with the same name
Now we check for truely orphaned funcs - funcs with no bindings - and we pass them back in the func list to allow them to be attached

fix(dal): Allow reconnected orphaned funcs

---

app/web/src/components/AssetCard.vue
lib/sdf-server/src/service/variant.rs

fix: invalid asset return type spits out status code 422

---

app/web/src/components/FuncEditor/AttributeBindings.vue

Fix: ignore bindings with a variant we dont have

---

app/web/src/components/ModelingDiagram/DiagramGroup.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue
app/web/src/components/ModelingView/ModelingRightClickMenu.vue
app/web/src/store/components.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue

https://github.com/user-attachments/assets/ab1062ce-d5b3-486b-a448-cdf2b5c75ace

fixed rename on diagram bugs + hotkey and menu option

---

lib/si-pool-noodle/src/pool_noodle.rs

Adds a simple exponential backoff retry to cleans which will eventually give up and abandon the instance. This should cover us for when jails fail to clean up in and timely fashion and can be safely retried and for broader error cases where we cannot clean the jail at all and would thrash forever otherwise.
This means that the pool size will slowly drain over time if instances become problematic, so we will want to think about how to detect and manage this.

feat: poolnoodle clean exponential backoff

---

Cargo.lock
Cargo.toml
lib/telemetry-application-rs/BUCK
lib/telemetry-application-rs/Cargo.toml
lib/telemetry-application-rs/src/lib.rs
third-party/rust/BUCK
third-party/rust/Cargo.lock
third-party/rust/Cargo.toml

Revert "feat: add tokio_console to the telemetry stack"

---

lib/dal-test/src/expected.rs
lib/dal/src/attribute/prototype/argument.rs
lib/dal/src/attribute/prototype/argument/value_source.rs
lib/dal/src/attribute/value.rs
lib/dal/src/workspace_snapshot/content_address.rs
lib/dal/src/workspace_snapshot/graph/v3.rs
lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs
lib/dal/tests/integration_test/node_weight/ordering.rs
lib/sdf-server/src/service/component.rs
lib/sdf-server/src/service/component/insert_property_editor_value.rs

Ensure we cannot accidentally create Map attribute values with duplicate keys

fix: correct Contains(key) conflicts for attribute values

---

app/web/src/components/ModelingDiagram/DiagramHelpModal.vue
app/web/src/components/ModelingDiagram/DiagramNode.vue

fix to socket bug, added hotkeys to help modal

---

lib/dal/src/attribute/value.rs
lib/dal/src/component.rs
lib/dal/src/func/runner.rs

Tracing the code and running locally, this seems to cover the missing gaps in telemetry.

add instrumentation

---

lib/dal/src/component/qualification.rs
lib/dal/src/qualification.rs

Ran a load test with a batch of 50 and got <1s for the get_summary request the whole time:

Feat: Speed up qualification summary calculation by not loading the func runs

---

lib/dal/src/workspace_snapshot/graph/v3.rs

This will ensure we remove any is_default: true edges and convert them to is_default: false if a NewEdge update for is_default: true comes in, for any source. This is a little more highly coupled to the updates than the transform correction but solves the problem for any source type. I could not produce this issue locally in a test, so i'm not sure if it's even possible, but this does not break schema variants during authoring.

fix: ensure only one is_default: true edge for any source

---

app/web/src/components/ModelingDiagram/DiagramEdge.vue
app/web/src/components/ModelingDiagram/ModelingDiagram.vue

Fix: Light up sockets even if they're connected via inferred edges

---

lib/dal/src/func/runner.rs

Data referred to by the func runs that are not written, should also not be written.

fix: don't write to func runs for intrinsic executions

---

lib/dal/src/func.rs
lib/dal/src/func/authoring.rs
lib/dal/src/func/binding/action.rs
lib/dal/src/func/binding/leaf.rs
lib/dal/tests/integration_test/func/authoring/binding.rs
lib/dal/tests/integration_test/func/authoring/binding/attribute.rs
lib/sdf-server/src/service/v2/func/list_funcs.rs
lib/si-frontend-types-rs/src/func.rs

was able to get a 30% speed up on list funcs with this change locally

fix: Only calculate func bindings once on func_list

---

lib/dal/src/context.rs

Add tracing to the validation enqueue and blocking commits

chore: add tracing to validations path

---

app/auth-portal/.env
app/auth-portal/src/content/legal/2024-09-19/1-tos.md
app/auth-portal/src/content/legal/2024-09-19/2-privacy.md
app/auth-portal/src/content/legal/2024-09-19/3-cookie.md
app/auth-portal/src/content/legal/2024-09-19/4-trademark.md
app/auth-portal/src/content/legal/2024-09-19/5-oss.md
app/auth-portal/src/pages/legal/LegalAgreementPage.vue
app/auth-portal/src/pages/legal/PrintLegalPage.vue
app/auth-portal/src/pages/legal/load-docs.ts
app/auth-portal/src/router.ts
app/auth-portal/src/store/feature_flags.store.ts
bin/auth-api/src/routes/user.routes.ts
bin/auth-api/src/services/tos.service.ts
bin/auth-api/src/services/users.service.ts
bin/auth-api/test/user-routes.test.ts
lib/ts-lib/src/terms-of-service.ts

feat: Add ability to have ToS versions behind a feature flag

---

app/auth-portal/src/App.vue
app/auth-portal/src/pages/DefaultWorkspacePage.vue
app/auth-portal/src/pages/LoginPage.vue
bin/auth-api/src/routes/workspace.routes.ts

Also fixes bad redirect when clicking on auth portal logo

fix: don't redirect to default workspace when tos needs updated

---

lib/dal-test/src/expected.rs
lib/dal-test/src/helpers.rs
lib/dal/src/component.rs
lib/dal/src/component/frame.rs
lib/dal/tests/integration_test/component/get_diff.rs
lib/dal/tests/integration_test/component/set_type.rs
lib/dal/tests/integration_test/frame.rs
lib/sdf-server/src/service/component/set_type.rs

Brit and I had this followon commit ready for #4629 but didn't hit the push button fast enough :)

Rename set_type_by_id -> set_type_by_id_unchecked

---

app/docs/src/reference/asset/function.md

Documents all the function types, and how to use the si-generator

docs: add asset function docs

---

lib/si-data-pg/src/lib.rs

chore(si-data-pg): promote `pool.get` to `INFO`

---

bin/auth-api/src/services/users.service.ts

This was behind a check on email - we want it to be behind a check for feature flag specificially

fix(auth-api): Switch the new create workflow to be behind a feature flag

---

app/auth-portal/src/pages/legal/LegalAgreementPage.vue
app/auth-portal/src/pages/legal/PrintLegalPage.vue

- Also fixes a recently introduced legal docs spacing issue

fix(auth-portal): Ensure legal documents comply to Mahir's doc naming standards

---

app/auth-portal/src/pages/legal/PrintLegalPage.vue

fix(auth-portal): fix legal file names with more than two words

---

app/web/src/components/AssetDetailsPanel.vue

Missed this from a previous PR

---

lib/si-data-pg/src/lib.rs

chore(si-data-pg): promote several query methods to `INFO`

---

lib/si-data-pg/src/lib.rs

Revert "chore(si-data-pg): promote several query methods to `INFO`"

---

lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
lib/dal/tests/integration_test/node_weight/component.rs

We're already detecting deletion in node weight transform correction so this change just adds a little more remove edge updates to the check. It also ensure we don't try to fix the frame contains relationships if the component is being deleted.

fix: ensure all incoming edges are removed from deleted components

---

lib/rebaser-server/src/handlers.rs

When running our system under synthetic load, we found several instances of the following error:
```
Error {
kind: JetStream(
Error {
code: 400,
err_code: ErrorCode(10013),
description: Some("consumer name already in use")
}
),
source: None
}
```
Prior to this change, the push-based ordered consumer that gets creating to process each change set subject had a name such as `rebaser-requests-$wk_id-$cs_id` where `$wk_id` was the Workspace ID and `$cs_id` was the Change Set ID. This change updates the name to be of the form:
```
rebaser-requests-$wk_id-$cs_id-$instance_id-$rand_ulid
```
where `$instance_id` the the Rebaser server's instance ID and `$rand_ulid` is a...Ulid used for randomness ;)
Of special note, when this consumer config is being constructed, the `inactive_threshold` value for …

fix(rebaser): ensure NATS requests consumer name is unique

---

app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/auth-portal/src/pages/WorkspacesPage.vue

- Show success message after invite
- Don't send request with invalid values

Feat(auth-portal): tidy up workspace invite

---

app/docs/src/.vitepress/config.ts

links are in two places - on the sidebar navigation at the bottom and in the social links area as our logo

added links to the docs site to the corp site

---

lib/si-data-pg/src/lib.rs

Revert "chore(si-data-pg): promote `pool.get` to `INFO`"

---

README.md

**System Initiative is the future of DevOps Automation**
<div><img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY21qMXl6eTRodnczOHliZW9qcGRtdGp4M2szdHJnYzVwdXMzczFycSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7qDSOvfaCO9b3MlO/giphy.gif">GIPHY</a></div>

feat: System Initiative is the future of DevOps Automation

---

.github/workflows/e2e-validation.yml

Revert the matrix part of the pipeline back to the original content

fix: amend matrix strategy

---

app/auth-portal/src/App.vue
app/auth-portal/src/pages/WorkspaceGoPage.vue
app/auth-portal/src/router.ts
app/web/src/pages/auth/AuthConnectPage.vue
app/web/src/router.ts
bin/auth-api/src/routes/workspace.routes.ts

fix: Links to web app pages work correctly if user is not logged in yet

---

.github/workflows/upgrade-web.yml

Enable option to deploying web manually (only web)

feat: add deploy web manually pipeline

---

app/web/src/components/FuncEditor/FuncDetails.vue
app/web/src/components/FuncEditor/FuncTest.vue
app/web/src/components/SiFuncListItem.vue
app/web/src/store/func/funcs.store.ts

fix: prefer function display name, make name input uneditable

---

CONTRIBUTORS.md
DOCS.md

docs: update DOCS.md

---

lib/sdf-server/src/service/action.rs

If an action is dispatched, running or on-hold, we throw an error to the user that they can't put that action on-hold
This was throwing a 500 but we want to change this to not throw a 500 toast and it will be a 304 instead!

fix(sdf): Don't fire 500 on failure to put action on-hold

---

app/web/src/main.ts
app/web/src/store/status.store.ts

Reduce timings to speed up perceived performance

---

app/web/src/api/sdf/dal/func.ts
app/web/src/api/sdf/dal/schema.ts
app/web/src/components/AssetDetailIntrinsicInput.vue
app/web/src/components/AssetDetailsPanel.vue
app/web/src/store/func/funcs.store.ts
lib/vue-lib/src/design-system/forms/VormInput.vue
lib/vue-lib/src/design-system/forms/VormInputOption.vue
lib/vue-lib/src/design-system/menus/DropdownMenu.vue

Configure bindings for intrinsic funcs on props and output sockets that don't have bindings

---

lib/dal/src/component.rs

Previously, on component upgrade, we were reattaching parents before the component creation had been finalized, and its id was a temp one instead of the one of the component it was going to replace. Since the parent_upsert functions send websocket events implicitly, even though the correct connection was made, the frontend would get the temp id intead of the real component id, making the graph wrong

fix: Don't send websocket events with component's temp id

---

.github/workflows/e2e-validation.yml
.github/workflows/run-api-test.yml

Amends the E2E tests to correctly fail after a third loop
Test passes:
https://github.com/systeminit/si/actions/runs/11150457035
https://github.com/systeminit/si/actions/runs/11150454023

fix: e2e tests weren't failing properly, amends it

---

lib/vue-lib/README.md

First draft of Frontend Best Practices

---

lib/dal/src/component.rs
lib/dal/src/diagram.rs
lib/sdf-server/src/service/component/delete_property_editor_value.rs
lib/sdf-server/src/service/component/insert_property_editor_value.rs
lib/sdf-server/src/service/component/set_name.rs
lib/sdf-server/src/service/component/set_type.rs
lib/sdf-server/src/service/component/update_property_editor_value.rs
lib/sdf-server/src/service/diagram/remove_delete_intent.rs
lib/sdf-server/src/service/diagram/set_component_position.rs

fix: Don't reset change status icon on changes to component

---

app/web/src/components/AttributesPanel/AttributesPanelItem.vue

BUG-627: fix validation icon over top drop down icon

---

component/spicedb/Dockerfile

fix: pull zed from docker image to get correct arch

---

component/lambda/BUCK
component/lambda/Dockerfile
component/lambda/docker-entrypoint.sh
component/lambda/functions/workspace_delegations_population.py

Adds a lambda docker image to execute our lambda functions from / centralise management of our scripts

feat: add lambda docker executor

---

.github/workflows/deploy-on-main.yml

Fixes the silly linting mistake preventing the alert firing

fix: amend silly linting mistake

---

component/init/configs/service.toml
lib/si-layer-cache/src/disk_cache.rs

fix: layer cache disk config pathing must match new config

---

lib/dal-test/src/expand_helpers.rs
lib/dal-test/src/signup.rs
lib/dal/src/workspace.rs
lib/dal/tests/integration_test/change_set.rs
lib/sdf-server/src/service/session/auth_connect.rs

fix: set workspace token on first workspace create

---

app/docs/src/roadmap/index.md

Updates the road map to have the management functions opportunity on it

docs: update road map

---

lib/dal/src/component.rs

<div><img src="https://media0.giphy.com/media/3o7TKVZ9pDTh2ZZ4Dm/200.gif?cid=5a38a5a220yjdtbzegzq4xqs2f76cp09578ed5f9mr6ssc5p&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/hairspraylive/">Hairspray Live!</a> on <a href="https://giphy.com/gifs/hairspraylive-2016-hairspray-live-3o7TKVZ9pDTh2ZZ4Dm">GIPHY</a></div>

chore(dal): set some spans to debug from info

---

app/docs/src/reference/vocabulary.md

minor-edits-vocab

---

app/auth-portal/src/App.vue
app/auth-portal/src/components/InfoCard.vue
app/auth-portal/src/components/WorkspaceLinkWidget.vue
app/auth-portal/src/pages/WorkspacesPage.vue
app/auth-portal/src/store/auth.store.ts
bin/auth-api/src/lib/lago.ts
bin/auth-api/src/routes/user.routes.ts
lib/vue-lib/package.json
lib/vue-lib/src/design-system/general/FilterPill.vue
lib/vue-lib/src/design-system/general/IconButton.vue
lib/vue-lib/src/design-system/general/SiSearch.vue
lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
lib/vue-lib/src/design-system/index.ts
lib/vue-lib/src/design-system/utils/color_utils.ts
pnpm-lock.yaml

Adds the tier status to the workspaces page as well as changing the design of the link widgets

feat(auth-portal): Let a user know they are in free tier

---

app/web/src/App.vue
app/web/src/components/FuncEditor/FuncList.vue

Improve the TS here so its clear what is happening with less forcing it

---

app/web/src/components/ManagementRunPrototype.vue
app/web/src/store/func/funcs.store.ts

Fix the run prototype loading icon

---

app/web/src/components/ComponentDetailsManagement.vue

Fix typo, copy, and some styling

---

app/web/src/main.ts

Fix: only one toast for "changes from head"

---

app/auth-portal/src/pages/WorkspaceDetailsPage.vue
app/auth-portal/src/store/workspaces.store.ts

Disabling this feature as it will be replaced with ReBAC

fix(auth-portal): Remove ability to self service change role

---

bin/si-api-test/sdf_api_client.ts
bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts
bin/si-api-test/tests/5-emulate_paul_stack.ts

I looked up previous successful runs and tried to set some reasonable limits for how long we will wait for DVU to finish - 20-30secs seems right but we can adjust if needed
<div><img src="https://media1.giphy.com/media/GJpJJPfhcoDl0xOZXI/200.gif?cid=5a38a5a2x4iahhfzec9sgw7g0bh4hddqme55lzhui6tjtsgk&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:171px;width:300px"/><br/>via <a href="https://giphy.com/cbs/">CBS</a> on <a href="https://giphy.com/gifs/cbs-the-neighborhood-theneighborhood-cedric-entertainer-GJpJJPfhcoDl0xOZXI">GIPHY</a></div>

Add configurable timeout when waiting for DVU to finish
