systeminit/si

app/web/src/store/components.store.ts
Component Upgrade replaces the old component with a new one at the same ID. But the socket ID's change. We aren't yet receiving a "RemoveEdge" event from SDF. So we're wrongly displaying edges that connect to a non-existing socket. This filters them out from what we draw.
=> Fix: dont show edge if socket is gone

app/web/src/components/AssetActionsDetails.vue
These were getting duped in certain cases. Fixed up!
=> Fix: actions duplicated, filter bindings for just this variant

lib/dal/src/component.rs
As we have an old component being deleted, we need to send WsEvents to delete the old connections
=> fix(dal): Send WsEvents to delete connections when upgrading a component

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue
Always have the selection box on top of all other nodes.
For example, if a frame gets trapped behind another frame, even when you select it from the diagram outliner, you have no indication where it is.
The solve here is to have the selection outline boxes drawn on a canvas layer above all other components.
=> Feat: improve diagram node selection

app/web/src/main.ts
This is new with the 0.4.0 release (we're already on 0.5.x)
=> Config: reduce extraneous honeycomb events

app/web/src/components/InstallAssetsPanel.vue, app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue, lib/vue-lib/src/design-system/tabs/TabGroup.vue
Clicking on "new assets" when coming from "modules" would send you to "assets"
=> Fix tab picker for new assets

app/auth-portal/src/pages/DefaultWorkspacePage.vue, app/auth-portal/src/pages/ProfilePage.vue, app/auth-portal/src/router.ts, app/auth-portal/src/store/workspaces.store.ts
When a user logs into the app (not from a redirect), we want to take the user to their default workspace.
The default workspace is chosen in the following order:
* If the workspace has a flag of isDefault
* The first production workspace owned by the user
This means that by shipping this code, we only affect users who have a production workspace. This will not redirect users with a local workspace
=> feat(auth-portal): Redirect to the default workspace on login

app/auth-portal/src/store/workspaces.store.ts
We just grabbed any of the workspaces you had in your list and redirected to that. it must be a workspace you created for it to be your default workspace
=> fix(auth-portal): Ensure that the default workspace is one you created

app/web/src/components/layout/navbar/NavbarPanelRight.vue, app/web/src/pages/WorkspaceSinglePage.vue
This PR adds a short sentence and a hyperlink to watch the tutorial on the docs site, fixes a bug with having the modal reappear properly, and removes "SI" from the Documentation and Discord pop-overs.
=> feat(app): add tutorial link and fix popovers for docs and discord

.github/workflows/try.yml
Ugh, these only ever run if they are on `main`, so the only way to test them is to merge first. Trash. Setting it so I can run these manually from PRs without checking the issue comment body so I can actually verify that this works
=> feat: tryest

.github/workflows/try.yml
This value is different depending on how the action is run. Neat!
=> fix: use head_ref to get the correct branch name

dev/healthcheck.py, prelude-si/tilt.bzl
This avoids a segfault running `buck2 dev:healthcheck`, `buck2 dev:stop` and `buck2 run dev:pull` with the latest docker version. Basically we install a `docker-compose` in nix, but we currently don't use it for these three commands.
All three commands do things that seem right when I run them after this change (they do some stuff and then segfault before the change):
```bash
jkeiser@Johns-MacBook-Pro si % buck2 run dev:healthcheck             
Build ID: 1d522276-8afd-4cf1-a031-4534207588af
Network: Up: 0B  Down: 0B
Jobs completed: 4. Time elapsed: 0.0s.
BUILD SUCCEEDED
--- Running health check on system for developing in the SI project
- Detected `docker` command (cmd=/usr/local/bin/docker)
- Detected running Docker Engine
- Detected Docker Compose is installed
- Found `bash` in Nix …
```
=> Use docker-compose from nix instead of "docker compose"

app/web/src/router.ts, app/web/src/store/change_sets.store.ts
But the real problem is that `head` is not a `ulid` and axum tosses it.<img src="https://media3.giphy.com/media/6o4TI6R4dvifniwOIk/giphy.gif"/>
=> Fix: do not call status_with_base when... you are on base

bin/auth-api/src/services/workspaces.service.ts, bin/sdf/src/args.rs, component/init/configs/service.toml, lib/dal/src/user.rs, lib/sdf-server/src/server.rs, lib/sdf-server/src/server/config.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/service/session.rs, lib/sdf-server/src/server/service/session/auth_connect.rs, lib/sdf-server/src/server/state.rs, lib/si-test-macros/src/sdf_test.rs
A permissions system for creating new workspaces.
Each instance of SDF can be configured in one of three ways -
- Closed - Only the first registered user can create new workspaces
- Open - Any registered user can create new workspaces
- Allowlist - Only registered users with an email on the Allowlist can create new workspaces. The allowlist can be specific email addresses, email domains to allow all addresses from (such as @systeminit.com), or a mix of both.
=> feat(sdf) - create workspace permissions system

DOCS.md
We bind localhost by default, and 0.0.0.0 doesn't work.
=> Point localstack credentials docs at localhost

lib/dal/src/func/binding/authentication.rs, lib/dal/tests/integration_test/func/authoring/binding/authentication.rs, lib/sdf-server/src/server/service/v2/func.rs, lib/sdf-server/src/server/service/v2/func/binding/delete_binding.rs
- Fix the SDF route for `delete_binding` to allow auth funcs to be detached
- Added tests for editing and detaching auth funcs
- fixed the name of a span and added one for the porting of auth funcs
=> fix(dal, sdf): auth funcs can be detached

lib/dal/src/schema/variant.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring/regenerate.rs
=> fix: don't delete auth funcs when regenerating variants

lib/si-data-pg/src/lib.rs
In addition to the in-process pool of PG connections, we also have connection pooling & recycling happening in pgbouncer. Because there are multiple layers that might result in us using an already established PG connection that is an unknown state, we need to make sure that we're also not dealing with a lingering open transaction in addition to the things we're already doing to make sure the connection is "clean" before we start using it.
=> Ensure recycled PG connections do not have lingering open transactions

bin/lang-js/src/function.ts
In a world where before funcs depend on beforeFuncs, we want the funcs to be able to see the results of each other so that they can work as expected
So if Func A writes to the environment, then we want that to be written before Func B runs otherwise Func B can't do it's thing
=> fix(lang-js): Set env vars before we iterate on beforeFuncs

lib/si-data-pg/src/lib.rs
In the case where we get back a clean (or at least cleanly committed) connection from either the in-process PG connection pool, or from pgbouncer, doing `ROLLBACK` will issue a warning that shows up in the logs. By temporarily setting the minimum log level to error before we do the `ROLLBACK`, and restoring it to the default value after rolling back we should no longer see the warning about not being in a transaction, while still getting other warnings.
=> Temporarily silence PG warnings during connection setup

.github/workflows/deploy-service.yml
Pass the dist id instead of string matching the name will be much more reliable.
=> fix: cloudfront dist id from secret instead of by name

lib/sdf-server/src/server/service/v2/module/contribute.rs
Without this event, none of the associated triggers on the event were firing
=> fix(sdf): Restore the correct name of the module contribution event

app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts, app/web/cypress/support/commands.ts
Minor fixes required to get the tests green again.
Builds upon previous PR https://github.com/systeminit/si/pull/4252 to:
- Give enough time for slightly slower workspaces (like tools prod) to allow the function value propagation completed before asserting the value is correct or not
- As they're dynamically loaded, the "create new change set" and "new user" modals seem to sometimes come into the user view in different orders. The force on the button click means we can dismiss the "You're an awesome new user!" modal even if it's behind.
=> chore: minor fixups to cypress tests

lib/sdf-server/src/server/service/v2/func.rs
We were making an incorrect API call to get the func execution history for a specific func run
=> fix(sdf): Allow getting code_execution_history

lib/rebaser-server/src/rebase.rs
If we detect an "exclusive edge mismatch" for an attribute value's prototype edge, we can automatically resolve it if:
1. The vector clock ids are the same.
2. The edge in to_rebase is newer than the edge in onto.
In this case, automatic resolution just means removing the NewEdge update and the conflict, leaving the edge as it exists in the to_rebase graph.
=> fix(dal): automatically resolve prototype edge conflicts

bin/sdf/src/args.rs, bin/sdf/src/main.rs
When using a config file, we didn't check that the args were empty before writing over the top
=> fix(sdf): Don't overwrite sdf config file with empty args

app/web/src/router.ts, app/web/src/store/change_sets.store.ts
We're seeing 500s on this endpoint. And its purpose is moot given that rebaser doesn't conflict with the most recent work.<img src="https://media1.giphy.com/media/26xBzL5fpjhJ9dQNa/giphy.gif"/>
=> Stop calling status_with_base

lib/sdf-server/src/server/service/v2/func.rs, lib/sdf-server/src/server/service/v2/func/create_unlocked_copy.rs, lib/sdf-server/src/server/service/v2/variant/create_unlocked_copy.rs, lib/sdf-server/src/server/service/variant.rs
IF you clicked the button fast enough you could dispatch multiple requests to create an unlocked schema variant. This resulted in multiple unlocked variants when the constraint is one.
This introduces a little defensive coding to prevent that from happening in the backend
=> fix(sdf): Prevent creating unlocked copies of funcs and variants

component/deploy/docker-compose.yaml, component/init/configs/proc-exporter.yml, component/init/configs/prometheus.yml, dev/Tiltfile, dev/docker-compose.platform.yml, dev/process-exporter-config/config.yml
We can use process-exporter to monitor firecracker and aggregate total CPU time and memory consumption, allowing us to derive usage over time. This works locally with this setup. Adding prometheus to the prod setup and having it scrape the local endpoints will allow us to point the region collector to it and pull the aggregated metrics from a single endpoint.
=> feat: add process-exporter to the stack to track firecracker metrics

dev/docker-compose.platform.yml
This change updates the host-mounted port of the `prometheus` service from a rebounded port assignment of `9000:9090` to `9091:9090`. That is, if a service or developer wishes to access Prometheus' port 9000, they would now access it via port `9091` rather than `9000` before this change.
In my case I have a local service running that attempts to bind to `localhost:9000` which is conflicting, causing the development environment to not completely spin up correctly.
Additionally while working this change up. I discovered that the `bin/auth-api` service will attempt to run on `localhost:9000` if needed while working on a feature/fix. This change avoids a future condition where a developer would appear unable to spin up a local auth-api as a result.
=> chore(tilt): change host-mounted port of Prometheus to 9091

app/web/src/components/AssetCard.vue, app/web/src/components/AssetListPanel.vue, app/web/src/components/InstallAsset.vue, app/web/src/components/modules/ModuleDisplay.vue, app/web/src/store/asset.store.ts, app/web/src/store/components.store.ts, app/web/src/store/func/funcs.store.ts, app/web/src/store/module.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/pkg.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/module.rs, lib/sdf-server/src/server/service/module/install_module.rs
1. No more tokio async on the rust side, its fast enough
2. Accept a list of modules
3. Send back schema variants in WsEvent and POST response
4. Module store removes the upgrade
5. Asset store & Component Store replace or add the variant
6. IconButtons reactive for the POST call
=> Fixes to install/upgrade remote module

.github/workflows/deploy-on-main.yml
Run the deploy based on the tags that buildkite pushes _after_ it finishes marking the artifacts as stable. This will also only deploy the services that change.
=> chore: deploy based on tags pushed from buildkite

component/init/configs/prometheus.yml
This will remove the need for a separate single instance prom server in the stack. With this setup we'll run a single prom server on each node that gathers all metrics from the local services (otelcol, node exporter, process exporter) and writes them to the Amazon Managed Prom server.
=> feat: remote write from the per-node prom instance

lib/dal-test/src/expected.rs, lib/dal-test/src/helpers/change_set.rs, lib/dal-test/src/lib.rs, lib/dal/src/attribute/value.rs, lib/dal/src/change_set.rs, lib/dal/src/lib.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/correct_transforms.rs, lib/dal/src/workspace_snapshot/graph/detect_updates.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/traits.rs, lib/dal/tests/integration_test/mod.rs, lib/dal/tests/integration_test/node_weight.rs, lib/dal/tests/integration_test/node_weight/ordering.rs, lib/rebaser-server/src/rebase.rs
This adds a framework designed by @jhelwig for us to detect when graph merges will create nonsensical results, and smooth them out. When we receive a set of OTs (updates) to apply to our branch, we ask the relevant nodes in our graph whether the set of updates makes sense, and give them a chance to massage the updates (modify, add, remove, etc.) until it generates a consistent graph.
The `CorrectTransforms` trait, implemented by all NodeWeights, is where the code for correcting transforms/updates goes. It is passed the entire set of updates and must return the set of updates (if there are no changes, it must return the updates unchanged).
Right now, the only conflict we're resolving is the `Ordering` node, which determines the order of values in an array value. If two people add ports to …
=> Resolve semantic conflicts

.github/workflows/community-check.yml, .github/workflows/deploy-on-main.yml, .github/workflows/deploy-service.yml, .github/workflows/deploy-stack.yml, component/toolbox/Dockerfile, component/toolbox/awsi.sh, component/toolbox/scripts/ssm, component/toolbox/scripts/supporting-funcs/ec2-funcs.sh, component/toolbox/scripts/supporting-funcs/inputs-funcs.sh, component/toolbox/scripts/supporting-funcs/ssm-funcs.sh, component/toolbox/scripts/upgrade
1. Adds support in the component toolbox for deployment to filter by service using the `-s` flag
2. Implements the CI changes to yield us a method to either deploy by binary or by a full instance refresh (the original method)
3.  Implements the CI changes to our merges to main to `just` deploy by binary
=> feat: add automatic deployment by binary on merge to main pipeline [defaulted to original strategy]

app/web/package.json, pnpm-lock.yaml
Upgrade cypress to fix the websocket closed bug in the client
```
(Run Starting)
┌────────────────────────────────────────────────────────────────────────────────────────────
│ Cypress:        13.13.2                                                                        │
│ Browser:        Electron 118 (headless)                                                        │
│ Node Version:   v18.18.2 (/opt/hostedtoolcache/node/18.18.2/x64/bin/node)                      │
│ Specs:          3 found (create-component.cy.ts, delete-component.cy.ts, value-attribute-propo │
│                 gation.cy.ts)                                                                  │
│ Searched:       cypress/e2e/modelling-functionality/**                                         │ …
```
=> feat: bump cypress version to fix e2e test flake for websocket disconnect issue

lib/dal/src/action.rs, lib/dal/tests/integration_test/func/authoring/binding/action.rs, lib/sdf-server/src/server/service/action/list_actions.rs
<div><img src="https://media1.giphy.com/media/9RXGuYWcUhScvV2D2H/giphy.gif?cid=5a38a5a2sadojdbk745wwr5z1kr5vipyfyf779ujsrbghvih&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:264px;width:300px"/><br/>via <a href="https://giphy.com/cbc/">CBC</a> on <a href="https://giphy.com/gifs/cbc-extra-too-much-over-the-top-9RXGuYWcUhScvV2D2H">GIPHY</a></div>
=>  Compute the ActionDependencyGraph at most twice per SDF route to list actions (as opposed to obnoxiously many...)

component/toolbox/scripts/supporting-funcs/inputs-funcs.sh
There was an issue with quoting around the cat glob which prevented the results being parsed correctly. This amends it and also appeases the shellcheck gods by not going from cat -> jq
=> fix: correctly parse json results in component toolbox

component/toolbox/scripts/upgrade
fix: amend exit code for case where no upgrades available. Was previously exiting non-zero for the case where no upgrades were available, even though it's a totally legitimate state to be in.
=> fix: amend exit code for case where no upgrades available

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/tests/integration_test/node_weight.rs, lib/dal/tests/integration_test/node_weight/component.rs
Corrects the FrameContains NewEdge transforms to ensure a component can only have one frame parent at a time.
=> fix(dal): components can only have one parent

app/web/src/components/Actions/ActionCard.vue, app/web/src/components/ChangesPanelProposed.vue, app/web/src/components/CodeViewer.vue, app/web/src/store/func_runs.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/func/runner.rs
1. Put the action ID in the func runner payload
2. When fun run logs come in over the wire, update a timestamp
3. Watch the time stamp, and reload the action from the now updated action list that has the new func run id
=> BUG-482: create reactivity in the func history panel

bin/veritech/src/args.rs, lib/cyclone-client/src/client.rs, lib/cyclone-client/src/execution.rs, lib/cyclone-server/src/config.rs, lib/cyclone-server/src/execution.rs, lib/cyclone-server/src/handlers.rs, lib/cyclone-server/src/server.rs, lib/cyclone-server/src/state.rs, lib/dal-test/src/lib.rs, lib/si-pool-noodle/src/instance/cyclone/local_http.rs, lib/si-pool-noodle/src/instance/cyclone/local_uds.rs, lib/veritech-server/src/config.rs, lib/veritech-server/src/server.rs
This PR adds a timeout wrapper when executing functions via the cyclone client in veritech. In addition, the default timeout value can be overriden as well as the recently added timeout value for cyclone server's lang server process.
As a result of this commit and recent commits, the following values are now configurable:
- cyclone client timeout
- dynamically configurable via veritech args and/or config file
- cyclone server timeout
- statically configurable with cyclone args and/or config file
- lang-js function timeout
- statically configurable with cyclone args and/or config file
- dynamically configurable with lang-js args, but they are also statically configured due to how cyclone is invoked via firecracker (see the rootfs builder script for more information)
This PR also renames …
=> Add cyclone client timeout and make func execution timeouts configurable

lib/veritech-server/src/config.rs, lib/veritech-server/src/server.rs
This is an embarrassing one. We tested #4318 extensively, but due to a last minute change with appeasing the test harness config, the default value of the veritech config would be "0" unless you specifically called the right constructor method to provide the correct value.
As a result of this change, the config for veritech is more clear anyway because the config option should be... well, optional. So now, whenever the config does not specify and option, we will fallback to the 35 minute timeout. Sorry, Victor, this is on me.
/<img src="https://media3.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif"/>
=> Fix function timeout set to 0 by default

Cargo.lock, Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change updates the Git branch to an `si/stable` branch so that any upstream changes can be made to the `js-kv-recreate-race` branch without impacting this codebase directly.
References: nats-io/nats.rs#1301
=> build(deps): update `async-nats` patch to stable Git branch

Cargo.lock, lib/rebaser-server/DEBOUNCER.md, lib/rebaser-server/src/change_set_requests.rs, lib/rebaser-server/src/change_set_requests/app_state.rs, lib/rebaser-server/src/dvu_debouncer_task.rs, lib/rebaser-server/src/lib.rs, lib/rebaser-server/src/nats.rs, lib/rebaser-server/src/server.rs, lib/si-std/BUCK, lib/si-std/Cargo.toml, lib/si-std/src/lib.rs, lib/si-std/src/time.rs
This change alters the implementation of the `DvuDebouncer` task to coordinate with other potenially running Rebaser services to ensure that (as before) only *one* dependent values update (i.e. DVU) is running per-change set.
As before, this debouncer Tokio task runs alongside each `ChangeSetRequestsTask` that a Rebaser spawns to process a work queue of rebase requests. However, the debouncer task now coordinates with other debouncer tasks via a NATS KV store which acts as a distributed lock (or could be though of as a leader election). Each key corresponds to a unique change set within a workspace. That is, the key is of the form `{workspace_pk}.{change_set_id}`. Additionally, there is a `max_age` set for all keys which will naturally age out if no update/delete/purge operations are …
=> feat(rebaser): support multiple rebasers that coordinate together

lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/traits.rs
When a dangling APA is removed, we should also walk to the value that it was a prototype argument for, and add that value to the dvu roots so that input sockets are recalculated.
=> fix(dal): add dvu roots for removed dangling connections

pnpm-lock.yaml
When attempting to launch the dev environment, the `app/web` resource in Tilt failed to build with an error. When running the equivalent of what Buck2 invokes (namely: `pnpm install --frozen-lockfile`), the following error message occured:
```console
❯ pnpm install --frozen-lockfile
Scope: all 11 workspace projects
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.autoInstallPeers" configuration doesn't match the value found in the lockfile
Update your lockfile using "pnpm install --no-frozen-lockfile"
```
Following the resolution as suggested yielded the `pnpm-lock.yaml` updates.
=> build(deps): fix out of date `pnpm-lock.yaml`

lib/rebaser-server/src/dvu_debouncer_task.rs
This PR makes the rebouncer's leader / waiting for leader loops a little clearer to reason about:
- To change from leader to non-leader, or when it's time to cancel, methods return the new desired `DebouncerState` instead of `ControlFlow` and the outer loop handles entering the new state. This removes `&mut self` from most of the methods, makes return statements work in a uniform manner, and puts state transitions in one place.
- Moves some bookkeeping and if statements out of the "waiting for leader" loop body (and one if statement back into the body) so it just has the code that tells you what each select() case is trying to handle.
- Any error returned from a function shuts down the server and restarts it. This lets us use `?` in all places errors are being returned and explicitly …
=> Simplify dvu rebouncer state transitions

lib/dal-test/src/helpers.rs, lib/dal/src/action/dependency_graph.rs, lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/component.rs, lib/dal/src/component/debug.rs, lib/dal/src/component/frame.rs, lib/dal/src/component/inferred_connection_graph.rs, lib/dal/src/component/socket.rs, lib/dal/src/diagram.rs, lib/dal/src/func/runner.rs, lib/dal/src/socket/debug.rs, lib/dal/src/socket/input.rs, lib/dal/tests/integration_test/frame.rs
This PR includes bug fixes and cleanup as the functionality of Frames has evolved since it was first ported to the new engine and there was lingering traversal bugs depending on if you were searching for Outgoing or Incoming inferred connections. 
There is a new module InferredConnectionGraph which encapsulates the logic around finding Inferred Connections (incoming and outgoing), moving this logic out of the Component module.  
All of the existing tests apply and I added a new one to account for the fix to ensure that multiple Input Sockets for an Up Frame don't connect to the same Output Socket.
<div><img src="https://media2.giphy.com/media/bgT142FWjRwV4hWsvX/giphy.gif?cid=5a38a5a2mbwtgikerycvivyv8g63x0a346srhucvnqku7f9m&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" …
=> Cleanup and encapsulate the logic for finding inferred connections

app/docs/src/how-tos/aws-ha-ec2.md, app/docs/src/how-tos/aws-iam.md, app/docs/src/how-tos/aws-vpc.md, app/docs/src/tutorials/getting-started.md
Use us-east-1 for readme's/guides rather than us-east-2
<hr/>
AMI check:
us-east-2: `ami-0c11a84584d4e09dd` is `al2023-ami-2023.5.20240730.0-kernel-6.1-x86_64`
us-east-1: `ami-0ba9883b710b05ac6` is `al2023-ami-2023.5.20240730.0-kernel-6.1-x86_64`
us-east-2: `ami-04000bc04ccee958e` is `fedora-coreos-40.20240616.3.0-x86_64`
us-east-1: `ami-068493ac5013f0936` is `fedora-coreos-40.20240616.3.0-x86_64`
=> feat: update how-to guides to use us-east-1

Cargo.lock, lib/dal-test/BUCK, lib/dal-test/Cargo.toml, lib/dal-test/src/expected.rs, lib/dal-test/src/lib.rs, lib/dal/src/component.rs, lib/dal/tests/integration_test/component/upgrade.rs, lib/dal/tests/integration_test/node_weight/component.rs, lib/dal/tests/integration_test/node_weight/ordering.rs
This fixes some issues upgrading components when the new schema variant has a different type (e.g. `Component` instead of `Configuration Frame (down)`). If you have not explicitly changed the type of the component, and it has another element as its children, upgrading to the new schema variant causes an error.
This PR fixes the problem by explicitly setting the component's type to the old value when upgrading the schema variant. This keeps it looking the same and allows the children to stay on it.
It also makes variable names in the upgrade procedure prefixed with `old` and `new` throughout, simply because it made it easier for me to read and understand. I'm happy to revert that if people prefer the old stuff.
Fixes BUG-474 and BUG-477 (though I'm still not sure how it fixes BUG-474 just …
=> Keep old component type when upgrading schema variant

lib/dal-test/src/expected.rs, lib/dal/src/pkg/export.rs, lib/dal/tests/integration_test/component/upgrade.rs
When you unlock a schema variant, it will sometimes pull the component type for the unlocked variant from a *component* rather than from the schema variant you are unlocking. Rather than fix the method that gets the component type, however, I had it not go out and get it from the graph at all: as far as I can tell, the component type is passed in to import correctly, so this PR just uses that.
This fixes BUG-496.
=> Fix component type mysteriously changing when unlocking schema variant

lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph/correct_transforms.rs, lib/dal/src/workspace_snapshot/graph/tests/exclusive_outgoing_edges.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/ordering_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/traits.rs, lib/dal/tests/integration_test/node_weight.rs, lib/dal/tests/integration_test/node_weight/attribute_value.rs, lib/rebaser-server/src/rebase.rs
When a secret changes or an attribute value changes, and those changes are replayed from head onto another change set, we need to add these values into the dvu roots so that any values that depend on them are recomputed in the context of that change set.
This is a pretty big hammer: if we detect any change in an attribute on replay that is already present in the graph, we add it to the dvu roots. This potentially means adding quite a few roots to the graph on big replays, and it also means recalculating a lot of values that really do not need to be recalculated.
Right now we don't have enough information in the transform corrections to be more surgical. What we would need would be
1. The snapshot of the graph that we are replaying updates *from*, after it has been updated.
2. Input socket …
=> feat(dal): dvus for secret and attribute changes from another change set

lib/dal/src/attribute/value.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/tests/integration_test/attribute/value.rs, lib/sdf-server/src/server/service/attribute/get_prototype_arguments.rs
This change improves performance of DVU by calculating the inferred connection graph once and using that to find the inputs for each function to run with
=> Calculate Inferred Connections Once for a DVU Job

app/auth-portal/src/pages/WorkspaceDetailsPage.vue
When you create a workspace, to go to it, you need to go back to the workspaces listing and find it and click it - this allows you to create then go there in a single page
=> feat(auth-portal): Add a go to workspace button

lib/dal/src/attribute/value.rs
I didn't realize inferred_connection_graph was going to get recorded in each span. Sorry to Pinga.
=> Turn down tracing

lib/dal/src/component/inferred_connection_graph.rs, lib/dal/src/func/runner.rs, lib/dal/tests/integration_test/frame.rs
This fixes a bug where we were incorrectly using the Attribute Value Id of the Secret Prop, not the Input Socket when gathering before funcs.  Also adds a test to ensure that secrets propagate correctly when using Frames and that DVU fires as expected when the secret being used changes
=> fix(dal): Use the correct attribute value id when looking for connections

lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/component.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/func/binding/attribute.rs, lib/dal/src/prop.rs, lib/dal/tests/integration_test/attribute/value.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/debug.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/node_weight/attribute_value.rs, lib/sdf-server/src/server/service/attribute/get_prototype_arguments.rs
One of our recent bugs was due to using Prop::attribute_values_for_prop_id instead of Component::attribute_values_for_prop_id, and it'd be nice to make it more obvious that the former method is almost never what you want.
This PR:
* Renames `Prop::attribute_values_for_prop_id` to the scarier and more accurate `Prop::all_attribute_values_everywhere_for_prop_id`, and adds a comment so that people will know where to get the method they probably *meant* to call.
* Calls `Component::attribute_values_for_prop_id()` everywhere we were previously calling the Prop version but really meant to get a component-specific value for the prop.
There do not appear to be other bugs around this, but the PR makes how we get props a bit more uniform and smaller to boot.
=> Use Component::attribute_values instead Prop almost everywhere

lib/dal-test/src/expected.rs, lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/component.rs, lib/dal/src/func/authoring/save.rs, lib/dal/src/func/binding/attribute.rs, lib/dal/src/socket/input.rs, lib/dal/src/socket/output.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/node_weight/attribute_value.rs, lib/dal/tests/integration_test/secret.rs, lib/sdf-server/src/server/service/attribute/get_prototype_arguments.rs
Just like with prop values, but this time for input and output sockets. This PR:
* Renames `Input/OutputSocket::attribute_values_for_input/output_socket_id()` to `all_attribute_values_everywhere_for_input/output_socket_id()`
* Adds `component_attribute_value_for_output_socket_id()` to `OutputSocket` for parity with `InputSocket`.
* Uses `Input/OutputSocket::component_attribute_value_for_input/output_socket_id()` wherever the everywhere method isn't needed.
* Also adds socket capabilities to `expected`.
=> Make it hard to accidentally get all socket values

Cargo.lock, Cargo.toml, bin/cyclone/BUCK, bin/cyclone/Cargo.toml, bin/cyclone/src/args.rs, bin/cyclone/src/main.rs, dev/Tiltfile, lib/cyclone-server/BUCK, lib/cyclone-server/Cargo.toml, lib/cyclone-server/src/config.rs, lib/cyclone-server/src/lib.rs, lib/cyclone-server/src/process_gatherer.rs, lib/si-firecracker/BUCK, lib/si-firecracker/Cargo.toml, lib/si-firecracker/src/disk.rs, lib/si-firecracker/src/errors.rs, lib/si-firecracker/src/firecracker.rs, lib/si-firecracker/src/lib.rs, lib/si-firecracker/src/scripts/firecracker-setup.sh, lib/si-firecracker/src/stream.rs, lib/si-pool-noodle/src/pool_noodle.rs, lib/telemetry-utils-rs/src/lib.rs, prelude-si/rootfs/rootfs_build.sh, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml, third-party/rust/fixups/procfs/fixups.toml
Hokay, so.
This PR creates three things:
1. A tool that can listen to TCP streams and forward the data to a vsock socket
2. A tool that can listen to UDS streams and forward the data to a TCP stream
3. A tool that polls the currently running processes and spits them out as metrics
All of these combined allows us to have Cyclone Server forward metric/trace calls to otel to a vsock socket on the host, Veritech to listen to a vsock-per-jail to accept that traffic and forward it along to the local otel, and for Cyclone Server to emit the processes that run through the lifetime of the jail as metrics so we can keep track of what people are doing with all these functions.
In short, this means we no longer need to rely on dodgy iptables rules to ship otel from cyclone.
The stream forwarder and …
=> feat: forward metrics from firecracker jails

lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/component/inferred_connection_graph.rs, lib/dal/src/component/socket.rs, lib/dal/src/func/runner.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/attribute/value.rs, lib/sdf-server/src/server/service/attribute/get_prototype_arguments.rs
Precompute the entire InferredConnectionGraph at the start of the DependentValuesUpdate job, store it on the WorkspaceSnapshot struct for that session only and use the cached version instead of calling `assemble` whenever possible.
=> feat(dal,sdf): use cached inferred conn graph when available

lib/dal/src/func/runner.rs
`si.change_set.id` and `si.workspace.id` should be recorded in high level spans only, not in `run_attribute_value`, which gets called multiple times on multiple tasks in the DependentValuesUpdate job, leading to one recording of each value for every function executed in the DVU.
=> fix(dal): don't repeat workspace and changeset id telemetry

component/init/configs/service.toml, lib/si-firecracker/src/scripts/firecracker-setup.sh
I don't know why I waited so long to do this. We get the version metadata and keep it locally. Don't download a new rootfs if we already have the same one locally.
Also, making the pool size configurable in ssm.
=> feat: check rootfs version before downloading

lib/dal/src/component/socket.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/workspace_snapshot.rs
This allows us to build the dependency graph with the cached values as opposed to rebuilding for each value
=> Calculate the inferred connection graph at the start of the job

app/web/src/main.ts
`window.location.host` includes the port, so we don't need to specify it here. It will be set by env vars at build time otherwise
=> fix: web otel traces should not include the port by default

.github/workflows/deploy-service.yml
We can just build in the url we want. We have the power. Go traces go!
=> fix: set otel url on web build

app/web/src/components/toasts/MaintananceMode.vue, app/web/src/main.ts, app/web/src/store/apis.ts, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/server.rs, lib/sdf-server/src/server/state.rs, lib/si-test-macros/src/sdf_test.rs, lib/telemetry-application-rs/src/lib.rs
Implements USR2 signal interpreter on the existing SDF tokio thread which can then be used by the applications to run custom business logic like:
- Go into maintenance mode/take yourself out of the working pool
- Change application behaviour on an individual node basis
- Debug out current state of running applications/like a statuscheck
Initially, we can use this signal handler to move a node out of the working pool/for maintenance mode to prevent write corruption while updating the application binaries.
With this PR, just SDF can be pushed into maintenance mode while running, which for any `future` API requests will throw a 503 / Service Unavailable with a corresponding body. The frontend now throws a toast when receiving a 503 describing to the user that maintenance mode is active. …
=> feat: add 503 on USR2 for maintenance mode in SDF

lib/si-pool-noodle/src/lib.rs
This change ensures that a Linux-specific unit test won't run (nor will attempt to be compiled) on the macOS platform.
=> fix(pool-noodle): add `target_os = "linux"` cfg on Linux test

.github/workflows/deploy-on-main.yml
I couldn't quite manage to figure out why the completely valid regex wasn't working, but I've validated this more explicit individual filtering per tag type does work. So switch to use that and move on with my life!
Checked with two tags:
`bin/veritech/image/20240820.031721.0-sha.0-test-jw-16-13`
`bin/sdf/image/20240820.143323.0-test-jw-16-11`
Both these triggered the correct pipeline.
There may be a bug with the pipeline still, but at least it should fire on merge.
=> fix: be more direct in tag filtering for deploying on main

app/web/src/components/AssetCard.vue, app/web/src/components/AssetListItem.vue, app/web/src/store/module.store.ts, lib/dal/src/module.rs, lib/dal/tests/integration_test/module.rs, lib/sdf-server/src/server/service/v2/module/sync.rs, lib/si-frontend-types-rs/src/lib.rs, lib/si-frontend-types-rs/src/module.rs
We used to depend on checking that a Module doesn't exist to understand if an asset can be contributed or not
We are now checking the module index to see if it can be contributed or not
=> fix(dal, sdf, web): Calculate if an asset can be contributed

app/web/src/components/Actions/FuncRunTabGroup.vue, app/web/src/components/AssetActionsDetails.vue, app/web/src/components/AssetFuncAttachDropdown.vue, app/web/src/components/AssetFuncListPanel.vue, app/web/src/components/AssetPalette.vue, app/web/src/components/ComponentDetails.vue, app/web/src/components/CustomizeTabs.vue, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/FuncTest.vue, app/web/src/components/NoSelectionDetailsPanel.vue, lib/vue-lib/src/design-system/tabs/TabGroup.vue
=> various style consistency fixes

lib/dal/src/action/dependency_graph.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/src/component/inferred_connection_graph.rs, lib/dal/src/diagram.rs, lib/dal/src/job/definition/action.rs, lib/dal/src/job/definition/compute_validation.rs, lib/dal/src/workspace.rs, lib/dal/src/workspace_snapshot.rs, lib/sdf-server/src/server/service/component/delete_property_editor_value.rs, lib/sdf-server/src/server/service/component/insert_property_editor_value.rs, lib/sdf-server/src/server/service/component/set_type.rs, lib/sdf-server/src/server/service/component/update_property_editor_value.rs, lib/sdf-server/src/server/service/component/upgrade.rs, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/delete_component.rs, lib/sdf-server/src/server/service/diagram/get_diagram.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs
Avoid expensive recomputation of various values in get_diagram. Provides about a 50% speedup locally. Also removes some noisy telemetry
=> fix(dal): speed up get diagram

lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/server.rs, lib/si-test-macros/src/sdf_test.rs
This PR removes an unused oneshot channel from the recent USR2 signal handling work in sdf (#4368).
- Move the maintenance mode message into a constant in order to make the code more readable
- Rename `Result` to `ServerResult` for clarity in `server/server.rs`
- Re-order imports to match style
=> Remove unused oneshot channel from USR2 sdf work

app/web/src/components/Debug/ComponentDebugDetails.vue
This search isn't useful in it's current state because if you don't want to use it then the panel is unusable due to everything being expanded by default
=> fix(web): Disable search on component debug view

lib/dal/src/module.rs, lib/dal/tests/integration_test/module.rs, lib/module-index-client/src/lib.rs, lib/module-index-server/src/migrations/U0009__modules_schema_variant_id_and_version.sql, lib/module-index-server/src/models/si_module.rs, lib/module-index-server/src/models/si_module/schema_variant_id.rs, lib/module-index-server/src/routes/promote_builtin_route.rs, lib/module-index-server/src/routes/reject_module_route.rs, lib/module-index-server/src/routes/upsert_module_route.rs, lib/module-index-types/src/lib.rs, lib/sdf-server/src/server/service/v2/module/contribute.rs, lib/sdf-server/src/server/service/v2/module/sync.rs
When we make a contribution, we now want to store the schema_Variant_id and the schema_variant_version so that we remove the contribute button if the user has already sent the contribution
This makes it a nicer user experience! In the future, we may want to mark assets that have been contributed by the user and that have not made their way back to the system
https://github.com/user-attachments/assets/3967fb74-0e71-4993-8a28-ecc1efb4e553
=> feat(module-index, sdf, dal): Add ability to understand if contribution made

lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/prototype/argument/value_source.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/tests/integration_test/secret.rs, lib/si-pkg/src/spec/attribute_value.rs
With @nickgerace
Right now, if you try to copy/paste a component with a credential hooked up, we fail to copy and toss an error.
This is because when we copy/paste the attributes to the new component, we currently:
1. Extract the attribute value as JSON and set the new attribute value to it (which removes reactive links to secret nodes, input/output sockets, and props).
2. Set the name and clear the resource_value.
3. Go back and fix up the prototypes to point to the correct nodes.
However, when there is a secret, we don't get that far, because when we try to set a secret to a JSON value it immediately throws an error trying to get the secret to compute dependent values.
This PR straight up clones the attribute prototypes and skips the JSON setting, and does the name setting and resource …
=> Allow components with secrets to be copy/pasted

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/action/prototype.rs, lib/dal/src/change_status.rs, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/job/definition/action.rs, lib/dal/src/socket/connection_annotation.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/ws_event.rs, lib/dal/tests/integration_test/component/upgrade.rs, lib/dal/tests/integration_test/diagram.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/workspace.rs, lib/sdf-server/src/server/service/component/delete_property_editor_value.rs, lib/sdf-server/src/server/service/component/insert_property_editor_value.rs, lib/sdf-server/src/server/service/component/set_type.rs, lib/sdf-server/src/server/service/component/update_property_editor_value.rs, lib/sdf-server/src/server/service/component/upgrade.rs, lib/sdf-server/src/server/service/diagram/create_component.rs, lib/sdf-server/src/server/service/diagram/create_connection.rs, lib/sdf-server/src/server/service/diagram/delete_component.rs, lib/sdf-server/src/server/service/diagram/delete_connection.rs, lib/sdf-server/src/server/service/diagram/paste_component.rs, lib/sdf-server/src/server/service/diagram/set_component_position.rs, lib/si-frontend-types-rs/src/component.rs, lib/si-frontend-types-rs/src/lib.rs
1. Move `SummaryDiagramComponent` struct to `si_frontend_types` & use `into_frontend_type` fn.
2. Stop firing event from `Component::new`, replace with events in create, paste, and upgrade.
3. Use SummaryDiagramEdge in `WsEvent::connection_created` (now `connection_upserted`) & `connection_deleted`.
4. Ghosted edge fixes in get_diagram
5. Ghosted component & edges fixes in delete_component
6. Ghosted edges fixed in delete_connection
7. Copying and pasting components with edges between them sends correct WsEvents
8. Upgrading components sends correct WsEvents.
=> Move SummaryDiagramComponent struct to si_frontend_types & use `into_frontend_type` fn

lib/si-firecracker/BUCK, lib/si-firecracker/src/disk.rs, lib/si-firecracker/src/errors.rs, lib/si-firecracker/src/firecracker.rs, lib/si-pool-noodle/src/instance/cyclone/local_uds.rs, lib/si-pool-noodle/src/pool_noodle.rs
Okay, so I kept thinking that our issues with larger pools were related to us not being able to unmount the disks quickly enough when under enough pressure, but after a dive I realized:
1. In some cases, we were failing because the disk was already unmounted, but we failed at a later step so we would retry and then fail forever when trying to unmount again
2. What surfaced as an unmount error (`EBUSY`) was actually because we would sometimes, when under enough pressure, timeout when waiting for the firecracker jail to startup. The timeout would error, but we wouldn't cleanup the spawned instance so the process would hang out and prevent us from unmounting the disk (hence `EBUSY`).
Solutions: swallow the "unmounted" error and ensure that we call `terminate` if we fail to start a watch. I …
=> fix: firecracker lifecycle fixes

package.json
This will go away when buck2 can run the auth API, but for now it's very helpful
=> chore: bring back root pnpm dev targets for auth api

Cargo.lock, Cargo.toml, bin/pinga/src/main.rs, lib/dal-test/src/lib.rs, lib/dal/BUCK, lib/dal/Cargo.toml, lib/dal/src/job/processor.rs, lib/dal/src/job/processor/nats_processor.rs, lib/dal/src/job/producer.rs, lib/pinga-core/BUCK, lib/pinga-core/Cargo.toml, lib/pinga-core/src/lib.rs, lib/pinga-server/BUCK, lib/pinga-server/Cargo.toml, lib/pinga-server/src/app_state.rs, lib/pinga-server/src/config.rs, lib/pinga-server/src/handlers.rs, lib/pinga-server/src/lib.rs, lib/pinga-server/src/server.rs, lib/si-test-macros/src/dal_test.rs, lib/si-test-macros/src/expand.rs, lib/si-test-macros/src/sdf_test.rs
This change refactors the Pinga server to consume its work (i.e. job requests) via a NATS Jetstream work queue. Leaving outstanding work on an external queue means that a Pinga instance won't lose pending requests when it's shut down or restarted.
The refactoring uses our `lib/naxum` crate to consume the requests from a Jetstream Stream and otherwise keeps the existing logic largely in place. Importantly:
- Processing a job request will almost unconditionally be successfully consumed. This means that if a job itself fails, it will be considered an "acked" message and a successful job run. This matches the prior behavior and can be changed in the future. The implication is that NATS currently will not help to re-deliver a job that has already been run (even if it failed).
- Jobs that have …
=> feat(pinga): consume work from a Jetstream work queue

lib/dal/src/workspace_snapshot.rs
We had a similar race condition in WorkspaceSnapshot::working_copy_mut, where we were checking to see if we needed to do something, then acquiring the write lock necessary to do the work if the initial check determined we needed to do it. Unfortunately, this means that the state of the thing being checked can change between when the conditions are checked and the write lock is acquired, as it is possible for another writer (or even multiple) to acquire the write lock and change things before the initial (potential) writer is able to act on the check(s) it did.
The way around this is to assume that a write will be necessary, acquire the write lock, and do the checks within the write lock. If the modification turns out to be unnecessary, then no modification is done, but if modification is …
=> Address read-lock-write race condition in WorkspaceSnapshot::revert

bin/lang-js/src/index.ts, lib/cyclone-server/src/execution.rs, lib/veritech-client/src/lib.rs, lib/veritech-server/src/publisher.rs, lib/veritech-server/src/server.rs
This removes the timeout we added to the veritech client (used by pinga) in favor of the timeouts we threaded through between cyclone client/server and lang-js. This particular timeout could be naughty because the timer starts immediately, so it's possible the a system under enough load would fail to even start lang-js before the timer times out. We believe that the scenarios this was put in to cover are also covered by the other timeouts we added, so away it goes.
=> fix: remove pinga heartbeat

app/web/src/components/ModelingDiagram/DiagramGroupOverlay.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/components.store.ts, app/web/src/store/status.store.ts
Decouple diagram node calculation from the status store to (vastly) improve frontend performance.
=> fix(web): don't recompute the whole diagram if one node is loading

app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/store/status.store.ts, lib/sdf-server/src/server/service/diagram.rs, lib/sdf-server/src/server/service/diagram/dvu_roots.rs
While a dependent values update job is running we should prevent applying, even if you come into the changeset after the status messages have all been sent but not "finished".
=> feat(sdf,web): report the count of dvu roots to prevent apply

app/web/src/App.vue, app/web/src/components/RealtimeStatusPageState.vue, app/web/src/components/StatusBar/StatusBar.vue, app/web/src/store/realtime/realtime.store.ts
Adds dynamic status indicator to the bottom status bar beside "System Initative"
It queries status.systeminit.com/data/payload.json every 30s and checks for active incidents, if we are:
- Degraded on any component it shows:
- Offline on any component it shows:
- In maintenance on any component it shows:
- if we are operational/no active incidents with affected components or the value cannot be established, the div is hidden/we are assumed to be operational.
**A memo: Death by CORS**
Running the application on one domain and querying another is tricky as client errors will present themselves from CORS if the server does not respond with valid `Access-Control-Allow-Origin` entries for the caller hostname. To get around this I have done two things:
- Asked firehydrant to include our managed …
=> feat: adds real time platform status indicator to UI

app/web/src/components/AssetDetailsPanel.vue, app/web/src/store/asset.store.ts, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring/clone_variant.rs, lib/sdf-server/src/server/service/variant/clone_variant.rs
The front end is sending the schema variant id, and as we were using the schema id to get the variant anyways, this change modifies the sdf route to accept the variant id.  This also enables users to clone any variant they can view (including unlocked). This change also fixes up the asset name picker and adds "-Clone" to the end of the display name so it's differentiated from what you were cloning.
<div><img src="https://media3.giphy.com/media/oCCLHVNt8YO64/giphy.gif?cid=5a38a5a2dzc2h47ngh1sg2gqcmas9i4btbybza5k29xsa6c6&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:444px;width:300px"/><br/>via <a href="https://giphy.com/gifs/oCCLHVNt8YO64">GIPHY</a></div>
=> Accept schema variant id when cloning

lib/dal-test/src/helpers/change_set.rs, lib/dal-test/src/test_exclusive_schemas/legos/large.rs, lib/dal-test/src/test_exclusive_schemas/legos/medium.rs, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/component.rs, lib/dal/src/job/definition/action.rs, lib/dal/tests/integration_test/component/delete.rs, lib/sdf-server/src/server/service/diagram/delete_component.rs
This change includes a few things:
- When we remove a component from the graph, re-parent any of it's children if they can be re-parented (we were already doing this in sdf, so just moved this logic to the dal)
- Rip out more of the work we were doing to compensate for conflicts in actions
- When deleting a frame with children, we were only marking it as 'to_delete' if the component was feeding data to other components that had resources. Now, we also check if there any children that have resources, regardless if data is flowing to them specifically, so that we don't need to deal with reparenting and other edge cases
- Adds a couple tests for this!
=> Avoid orphaned components that can't be restored

app/web/src/main.ts, app/web/src/pages/WorkspaceSinglePage.vue, app/web/src/store/apis.ts, app/web/src/store/status.store.ts, lib/sdf-server/src/server/routes.rs
**Who doesn't love a good two-fold problem?**
1. The toast library we are using serially runs the toasts if you run them with a `maxToasts` of 1. If you for example throw two toasts with a 30s timeout, this means that the toast will be shown for 60s, with the second toast being shown from the 30s mark.
2. With the change introduced here yesterday https://github.com/systeminit/si/commit/a8a8ffbcade7e662e3e74fe2b562dd3fbbb310bd
```
const dvuRootCheck = setInterval(() => {
if (
this.dvuRootsCount > 0 &&
Object.keys(this.activeComponents).length < 1
) {
debouncedFetchDvuRoots();
}
}, 3500);
```
We are running a BE API call every 3.5s if the user has active DVU pending within in the changeset. 
If you couple that with our maintenance strategy of making the backend throw 503's when in …
=> feat: stop burning our users with maintenance toasts

bin/pinga/src/args.rs
Guess what? It's currently 64!
=> fix(pinga): update CLI help default value for `concurrency`

app/web/cypress/support/component-actions/create.ts
Hotfix to the cypress tests in prod/tools to fix our coverage.
We changed the size from sm->xs to tighten up the UI, but caused the test regression.
Realistically we need to be selecting by data-ids in here, but this will put it green for now.
=> fix: hotfix to the cypress tests amending asset selection

app/web/cypress/e2e/modelling-functionality/value-attribute-propogation.cy.ts
Inconsistency in our tests means double the amount of fixes. Effort needs to go in here to improve stability/structure/div references
=> fix: amend cypress e2e modelling test

lib/naxum/src/extract/message_parts.rs, lib/naxum/src/extract/rejection.rs
This change adds a new extractor type `RequiredReply` that can be used by handler functions. It will ensure that a reply subject is present in the message and if not a `NoReplyRejection` is returned.
The most likely use case for this extractor is when processing core NATS messages where a reply inbox is expected. Note that there is also a `Reply` extractor already present in naxum, however it returns an `Option<Subject>`.
Example
-------
```rust
pub async fn process_message(
RequiredReply(reply_subject): RequiredReply,
Json(request): Json<MyRequest>,
) {
// ...
}
````
=> feat(naxum): add `RequiredReply` extractor

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/components.store.ts, app/web/src/store/qualifications.store.ts
computing the qualification status and resource status in the diagramNodes getter meant we re-rendered every node on the diagram whenever a single qualification status changed. This was another cause of constant frontend re-rendering during dependent values updates and action apply.
=> fix(web): decouple diagramNodes getter from qualification store

lib/dal/src/job/definition/action.rs, lib/dal/tests/integration_test/component/delete.rs
If there is more then one component of a given variant, when delete actions run, we try and remove other eligible components.  Without rebasing the initial component's removal, there are orphaned attribute values left on the graph that are accessible via edges to the Props, which was causing an error when trying to remove the other component of the same kind as the original.
=> fix(dal): Remove initial component and rebase before removing others

app/web/src/components/DiagramOutline/DiagramOutlineNode.vue, app/web/src/components/ModelingDiagram/DiagramEdge.vue, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramGroupOverlay.vue, app/web/src/components/ModelingDiagram/DiagramIcon.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/store/components.store.ts
- Use diagram outliner to collapse frames
- Use context menu to collapse frames
- Add caret icon to frame upper left to collapse frames
- Store positions, sizes, and collapsed state in browser local storage
- Incoming connections terminate at the center of the frame
- Display children stats for collapsed frames in the bottom right corner
- Removing resize handles on collapsed frame
- Collapsed frames can be moved
- Enforce boundary box on collapsed child within a parent
- Send stats to posthog
=> ENG-2639: collapsed frames

Cargo.lock, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/vite.config.ts, bin/lang-js/src/function.ts, bin/lang-js/tests/exec.spec.ts, bin/lang-js/tests/executeFunction.spec.ts, lib/cyclone-core/BUCK, lib/cyclone-core/Cargo.toml, lib/cyclone-core/src/lib.rs, lib/cyclone-core/src/progress.rs, lib/cyclone-server/src/execution.rs, lib/dal/src/func/backend.rs, lib/dal/src/func/runner.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/func/authoring.rs, lib/dal/tests/integration_test/validations.rs, lib/sdf-server/src/server/service.rs, lib/sdf-server/src/server/service/v2/func.rs, lib/sdf-server/src/server/service/v2/func/test_execute.rs, lib/sdf-server/src/server/service/variant.rs, lib/si-pool-noodle/src/lib.rs, lib/veritech-client/src/lib.rs, lib/veritech-client/tests/integration.rs, lib/veritech-server/src/handlers/kill.rs, lib/veritech-server/src/server.rs
To ensure bad user code is not reported as server errors, we return 422 Unprocessable Content when that's the reason for an API call failure.
To enable this, I had to make the language server errors static and parseable into a rust enum, that has an extra UserCodeException variant containing a string so easily support JS errors on the frontend.
This PR also cleans up code error messages in the frontend
=> feat: Return 422 on user code errors

app/web/src/components/QualificationViewerSingle.vue
Replaces the \<pre> rendering for qualifications to use the code viewer instead, which makes things easier to format in the output of qualifications.
=> feat: display qualification output as code

lib/naxum/examples/graceful-shutdown/BUCK, lib/naxum/examples/graceful-shutdown/main.rs, lib/naxum/src/lib.rs, lib/naxum/src/serve.rs
This change adds an alternative naxum app setup `naxum::serve_with_incoming_limit` which takes an optional number. When set, the app will limit the number of incoming messages being handled at the same time.
=> feat(naxum): add ability to limit incoming work to a naxum app

bin/veritech/src/args.rs, bin/veritech/src/main.rs, lib/dal-test/src/lib.rs, lib/pinga-server/src/config.rs, lib/pinga-server/src/server.rs, lib/veritech-client/tests/integration.rs, lib/veritech-server/src/config.rs, lib/veritech-server/src/lib.rs, lib/veritech-server/src/server.rs
This change harmonizes the server configuration and server setups between Pinga and Veritech. The following changes are made:
- Veritech takes an `--instance-id` option on the CLI and a random ID is generated if not provided (similar to other services).
- Veritech takes a `--concurrency` option to override the default concurrency limit.
- The concurrency option is `--concurrency` in both Veritech & Pinga.
- The config file value `concurrency_limit` is honored in both Veritech & Pinga.
- Default for concurrency limits are now in each respective server's `config` module and is used to render the value indirectly through its `Config` type.
- Veritech's execution timeout option is updated to `--cyclone-client-execution-timeout-secs` to reflect the numerial value.
- Veritech's execution …
=> chore(pinga,veritech): normalize server config & setups

app/web/src/components/toasts/UnscheduledDowntime.vue, app/web/src/main.ts, app/web/src/store/apis.ts
Adds some toasty behaviour when we are experiencing an outage that we didn't internally instigate, looks a bit like this:
We basically throw this "unable to serve request" toast when the backend is throwing a 502 or 504 [no backend available or something like that]
<hr/>
fixup: `  return toast;` was missing from the filterBefore toast middleware so what was happening is any other toast but the maintenance toast was getting filtered out. This is amended in this PR.
=> feat: push unable to serve request toast on 502 and 504

clippy.toml, lib/dal/examples/rebase/main.rs, lib/dal/src/action.rs, lib/dal/src/action/prototype.rs, lib/dal/src/attribute/prototype.rs, lib/dal/src/attribute/prototype/argument.rs, lib/dal/src/attribute/prototype/argument/static_value.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/func.rs, lib/dal/src/func/argument.rs, lib/dal/src/module.rs, lib/dal/src/prop.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/dal/src/secret.rs, lib/dal/src/socket/input.rs, lib/dal/src/socket/output.rs, lib/dal/src/validation.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/tests.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_updates.rs, lib/dal/src/workspace_snapshot/graph/tests/exclusive_outgoing_edges.rs, lib/dal/src/workspace_snapshot/graph/tests/rebase.rs
Profiling of slow rebases with lots of updates revealed that most of the time was being spent in replace_references, both calculating the merkle tree hash and cloning node weights in copy_node_index_by_id. This "copy on write" logic no longer makes sense to me with the operational transforms. And in any case, we are still copy on write (from the read only graph to the working copy). This PR removes the "copy on write" logic which no longer makes sense. Instead we mutate the graph in place, and keep a list of touched nodes. Using that list of touched nodes, we recalculate the merkle tree hash for the graph once, in `cleanup_and_merkle_tree_hash`. The result is a massive speed up in graph operations. Even huge rebases come in under a second, and usually under 300ms. Small rebase operations …
=> feat(dal): graph goes vroom

lib/dal-test/src/expected.rs, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/tests/integration_test/component.rs
Fixes pasting not carrying explicitly written values over.
When we paste a node, constant values (things the user edited) were being copied, but the JSON value cache was not carried over. Since constant values do not get touched in dependent value updates, they never got set. Now we clone the value cache when pasting a node.
Fixes BUG-511.
=> Copy computed value cache when pasting a node.

lib/dal-test/src/test_exclusive_schemas/starfield.rs, lib/dal/src/action.rs, lib/dal/src/attribute/value.rs, lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/component.rs, lib/dal/src/context.rs, lib/dal/src/func.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/migrations/U3101__add_component_concurrency_limit_to_workspaces.sql, lib/dal/src/workspace.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph/v2.rs, lib/dal/src/workspace_snapshot/node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/finished_dependent_value_root_node_weight.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/dependent_values_update.rs, lib/dal/tests/integration_test/node_weight/attribute_value.rs, lib/rebaser-server/src/config.rs, lib/sdf-server/src/server/service/diagram/dvu_roots.rs
Adds a column to the workspaces table that allows us to control how many components can be updated by the DependentValuesUpdate job in one run. When the limit is reached, the job will write the current set of DVU roots back to the graph so the dependency graph can be reconstructed in the state it was when the job finished. Currently every workspace will get a hefty default limit of 256 components, but this is configurable by updating the column in the workspaces table, which the Admin panel will make possible in a future change.
Also reduces the dvu interval for the rebaser to 800ms, so that dvu jobs are enqueued more frequently.
This adds a database migration, and a new node weight, so cannot be rolled back easily (however no graph migration will be required)
=> feat(dal): dvu component concurrency limit

.github/workflows/deploy-on-main.yml, .github/workflows/deploy-stack.yml, .github/workflows/invoke-and-check-invalidations.yml, .github/workflows/try.yml, BUCK, component/toolbox/scripts/check-invalidation, component/toolbox/scripts/supporting-funcs/cloudfront-funcs.sh
Sister PR to https://github.com/systeminit/si-ci/pull/132/files once it's merged we can hook off the tag to deploy on merge to main more cleanly. 
We were having trouble with cloudfront cache so this invalidates the cache explicitly before every deployment.
Adds a cloudfront distribution checker to the toolbox so we can quickly validate that the CDN is invalidated, or there are no active invalidations before continuing with the deployment.
=> fix: amend deployment strategy for tools on main

bin/pinga/src/main.rs, bin/rebaser/src/main.rs, bin/veritech/src/main.rs, lib/si-service/src/shutdown.rs
This change updates the common binary program `graceful()` function into a function that returns an internal builder capable of the same graceful shutdown logic as before. This refactoring will allow for future extensions (i.e. additional optional shutdown scenarios) as well as making the setup a little more ergonomic.
=> feat(si-service): refactor `shutdown::graceful` to a builder pattern

bin/pinga/BUCK, bin/pinga/src/main.rs, bin/rebaser/BUCK, bin/rebaser/src/main.rs, bin/veritech/BUCK, bin/veritech/src/main.rs
This change uses the `CARGO_BIN_NAME` in the programs' `main.rs` in an effort to more closely unify the construction of a common SI Rust program.
=> chore(pinga,rebaser,veritech): extract bin name into const

component/toolbox/scripts/ssm, component/toolbox/scripts/supporting-funcs/ssm-funcs.sh
It is easy to confuse which service or environment you are interacting with when using this tool. This adds a custom prompt that makes it very obvious.
=> feat: include the env and service name in the toolbox shell

lib/sdf-server/src/server/extract.rs, lib/sdf-server/src/server/routes.rs, lib/sdf-server/src/server/service/v2.rs, lib/sdf-server/src/server/service/v2/admin.rs
Adds middleware for the entire api/v2/admin route set that limits it to users with @systeminit.com email addresses.
=> feat(sdf-server): admin auth middleware for api/v2/admin

lib/dal/src/component.rs, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/component/upgrade.rs, lib/sdf-server/src/server/service/component/insert_property_editor_value.rs
Previously, when upgrading a component and reaching an attribute value that didn't have a correspondent on the new variant yet, we assumed it was a map or array scalar item and created it, which resulted in us not creating attribute values for fields of objects inside arrays and maps. This resulted in unusable array entries on the prop editor. 
Now, when cloning objects that are inside arrays and maps, we forcefully create all attributes.
This unearthed another problem, which was that we were using the prop id + the key to determine equivalency between avs of new and old components, meaning in the case of fields of objects within arrays (which don't have keys or indices themselves), we'd copy the value from random items with the same prop id. This is resolved by matching on the full av …
=> fix: Clone object children of arrays and maps correctly

app/web/src/components/FuncEditor/FuncDetails.vue
As per Paul. If folks unlock this FN for every asset, and make a mistake—everything in broken. So we're just preventing that possibility.
=> Cannot unlock resourcePayloadToValue

Cargo.lock, Cargo.toml, lib/dal/tests/integration_test/dependent_values_update.rs, lib/si-layer-cache/src/db/cache_updates.rs, lib/si-layer-cache/src/layer_cache.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
When receiving writes from other services we have to deserialize them to load them into the memory cache. But deserialization of large values is (relatively) slow, and can lock up the tokio reactor, causing unexpected issues elsewhere. This puts the deserialize ops on the blocking pool so that other tasks can continue. The "slow runtime" is not available in the layer cache. We may want to factor that out into its own crate so that non-Dal crates can use it.
=> fix(si-layer-cache): deserialize on blocking pool

bin/veritech/src/args.rs, lib/dal-test/src/lib.rs, lib/si-firecracker/src/firecracker.rs, lib/si-pool-noodle/src/errors.rs, lib/si-pool-noodle/src/instance/cyclone/local_uds.rs, lib/si-pool-noodle/src/lib.rs, lib/si-pool-noodle/src/lifeguard.rs, lib/si-pool-noodle/src/pool_noodle.rs, lib/si-pool-noodle/src/task.rs, lib/veritech-server/src/config.rs, lib/veritech-server/src/handlers.rs, lib/veritech-server/src/server.rs
Post the Veritech Jetstream changes, this refactors PoolNoodle to run over a single loop that works based on tasks in a queue. The veritech cancellation token is threaded through to we shutdown and clean up when veritech is shut down. We now only spin up as many tasks as there is max_concurrency to help manage back pressure (it's currently set to an arbitrarily high number).
This also does some quality of life changes, a config struct, better defaults, and more metrics to track things like the number of jobs waiting for instances when we're under enough pressure.
Here's an undersized pool fighting for its life.
=> chore: refactor pool_noodle loop to use cancellation token and config

app/web/src/components/ModelingDiagram/DiagramEdge.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/components.store.ts
- Move collapsed & real children when parent moves ✅ 
- Parent resize should act as if collapsed children were never collapsed ✅ 
- Dont show multiple edges to the same coordinates ✅ 
- Dont render edges to or from a component that is not rendered because its parent is collapsed ✅
=> Collapsed frame improvements

prelude-si/rootfs/rootfs_build.sh
`$HOME` is set, but it does not show up in the envs for cyclone as it runs via rc-service. Manually setting it here causes it to be available to `siExec`.
Note that in some cases running with `shell: true` is required for the env var to be expanded properly.
```typescript
await siExec.waitUntilEnd("echo", ["$HOME"], {shell: true});
````
=> fix: manually set home dir in cyclone service

lib/dal/src/attribute/prototype/debug.rs, lib/dal/src/attribute/value/debug.rs, lib/dal/src/component/debug.rs, lib/dal/src/socket/debug.rs
The info! in the component debug routes is not helping us anymore, and fills up the logs, making them harder to read. Let's ditch it
=> fix(dal): quiet info messages in debug routes

bin/si-smoketest/main.ts, bin/si-smoketest/sdf_api_client.ts
Moves the api test suite to use constructor-type pattern for each API endpoint we want to use to drive SDF, means you can use them like:
```
await sdfApiService.abandonChangeSet(changeSetId);
or
await sdfApiService.createChangeSet(changeSetName);
```
Tested locally using
```
SDF_API_URL="https://app.systeminit.com/api" AUTH_API_URL="https://auth-api.systeminit.com" deno task run workspaceid 'username@systeminit.com' 'pass' 
Task run deno run --allow-env --allow-net main.ts "workspaceid" "username" "pass"
calling GET https://app.systeminit.com/api/change_set/list_open_change_sets
get_head_changeset OK - 445ms
calling POST https://app.systeminit.com/api/change_set/create_change_set
calling GET https://app.systeminit.com/api/v2/workspaces/workspaceid/change-sets/01J6ZNQYE4FBZ6HZ3FMTQPD1M6/sch …
```
=> feat: move api calls into their own constructor within api test toolbox

lib/dal/src/workspace_snapshot/migrator.rs
During migration of the "universal" change set, we have been orphaning change sets, and some of these change sets are broken (referencing content store content that has not been successfully saved). Rather than attempting to migrate snapshots that are both unreferenced, and likely broken, we'll skip over them.
=> Skip migrating graph version for orphaned change sets

lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1.rs
Even though the field is no longer optional, the front-end has been treating it as an optional field by checking if it is the empty string, and falling back to using the schema name if so.
=> Use empty string for default display_name when upgrading SchemaVariantContent

.github/workflows/upgrade-service.yml, component/toolbox/scripts/supporting-funcs/inputs-funcs.sh
This _should_ ensure we handle upgrade failures by replacing instances. I also increased the timeout for pulling the results from SSM invocations, hopefully this helps with some of the spurious errors we are seeing.
=> fix: handle upgrade failures correctly.

Cargo.lock, Cargo.toml, lib/tokio-dedicated-executor/BUCK, lib/tokio-dedicated-executor/Cargo.toml, lib/tokio-dedicated-executor/src/lib.rs, lib/tokio-dedicated-executor/src/parent.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
An executor which manages a Tokio runtime that is dedicated to a specific set of workloads. The futures and any spawned tasks will run on this runtime which can be purpose-tuned.
The implementation of this crate comes from the [`executor`] crate in [InfluxData]'s [influxdb3_core] project which is collectively released under the [MIT] or [Apache v2.0] license.
This implementation is based on the `executor` crate as of July 10, 2024:
<https://github.com/influxdata/influxdb3_core/tree/78b4d56989410b30a3cc48020c1491405943b4ad/executor>
References
----------
- [The New Stack: Using Rustlang’s Async Tokio Runtime for CPU-Bound Tasks](https://thenewstack.io/using-rustlangs-async-tokio-runtime-for-cpu-bound-tasks/)
- [Rustacean Station: Rebuilding InfluxDB with Rust with Andrew …
=> feat: `tokio-dedicated-executor` for dedicated Tokio runtime workloads

Cargo.lock, Cargo.toml, lib/dal/src/slow_rt.rs, lib/si-runtime-rs/BUCK, lib/si-runtime-rs/Cargo.toml, lib/si-runtime-rs/src/lib.rs, lib/si-service/src/rt.rs, lib/tokio-dedicated-executor/BUCK, lib/tokio-dedicated-executor/Cargo.toml, lib/tokio-dedicated-executor/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change adds an `si_runtime::compute-executor` function which builds and returns a `DedicatedExecutor` tuned for running CPU-intensive tasks.
There are a few tunings applied to the underlying Tokio runtime:
- The Tokio I/O types such as net, process, signal, etc. are not enabled
- A reduced thread priority is set when the Tokio runtime spawns threads, allowing another primary/main reactor a chance to have some preferential priority
In addition, the `si_runtime::build_runtime` is renamed to `si_runtime::main_tokio_runtime` with better thread names by default.
=> feat: create a compute executor that can run CPU-intensive tasks

bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/create_and_use_variant.ts
API Test to cover creating a new asset in a changeset and dropping it onto the diagram
=> feat: add authoring new asset API test

component/nats/BUCK
Notably in the release notes:
> Fix regression in KV CAS operations on R=1 replicas introduced in
> v2.10.19
See: https://github.com/nats-io/nats-server/releases/tag/v2.10.20
References: nats-io/nats-server#5841
=> build(deps): upgrade to NATS server 2.10.20

lib/dal/src/workspace_snapshot/graph/detect_updates.rs, lib/dal/src/workspace_snapshot/graph/v3.rs, lib/dal/src/workspace_snapshot/graph/v3/tests.rs
`has_path_to_root` was only used in one place to make sure that if we were given a dirty graph, we wouldn't end up looking at "zombie" nodes (prior versions of things that can no longer be reached using forward edges from the current root node). This check would end up walking parts of the graph multiple times through the course of detecting diffs.
Given we are already calling `graph.cleanup()` in the place where we would have been looking at a dirty graph, this check is not necessary.
This PR is built on #4436.
=> Remove graph::has_path_to_root

lib/dal-test/src/lib.rs
This change changes the size of the cyclone pool that are set for *each* integration test. Prior to this change the value was updated recently to `50` and this led to issues running the DAL integration test suite on some larger Linux systems (namely Threadripper workstations with 64 or 128-cores). The test suite issue would manifest as:
```
thread 'main' panicked at third-party/rust/tokio-1.40.0.crate/src/runtime/scheduler/multi_thread/worker.rs:466:13:
OS can't spawn worker thread: Resource temporarily unavailable (os error 11)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
A little misleading in that the number of threads per-process *and* the number of processes both contribute to this failure.
While the update pool size is considerably smaller, the …
=> fix(dal-test): reduce the default cyclone pool size for tests

Cargo.lock, Cargo.toml, bin/sdf/src/main.rs, lib/billing-events-server/src/app_state.rs, lib/billing-events-server/src/handlers.rs, lib/billing-events-server/src/lib.rs, lib/billing-events/src/lib.rs, lib/dal/src/change_set.rs, lib/data-warehouse-stream-client/BUCK, lib/data-warehouse-stream-client/Cargo.toml, lib/data-warehouse-stream-client/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml, third-party/rust/fixups/aws-config/fixups.toml, third-party/rust/fixups/aws-sdk-firehose/fixups.toml, third-party/rust/fixups/aws-sdk-sso/fixups.toml, third-party/rust/fixups/aws-sdk-ssooidc/fixups.toml, third-party/rust/fixups/aws-sdk-sts/fixups.toml, third-party/rust/fixups/aws-types/fixups.toml
This PR adds a data warehouse stream client that can be used for multiple things, but is presently and solely concerned with publishing billing events to the stream.
The client is unused by any running service in builds using this commit. However, it is ready to be used and will likely be done so with opt-in configuration from SDF's own configuration options.
When a client is not present, the billing events server will run in "no-op" mode, which consumes the message off the NATS Jetstream stream (preventing overload), logs that the message was received and then does a whole lotta nothing.
As a result of these changes, this commit adds `aws-sdf-firehose` and `aws-config` third party dependencies to the repository. They are scoped purely to the new `data-warehouse-stream-client` crate, …
=> Add data warehouse stream client

lib/si-layer-cache/src/db/serialize.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-runtime-rs/src/lib.rs
performance seems to massively degrade on macOS when large number of spawn_blocking calls are issued, even when the max blocking pool threads are reduced to 8. Using a suggestion by @fnichol to break the deserialization up with a tokio::task::yield_now() call instead.
=> fix(si-layer-cache): remove spawn_blocking calls which break macOS

.github/workflows/deploy-on-main.yml, .github/workflows/deploy-stack.yml, bin/si-api-test/main.ts, bin/si-api-test/test_execution_lib.ts
This fixes the concurrency of the api-tests in the pipeline so they don't inadvertently cancel the cypress tests. Tests should also exit 1 if they contain a `failure`.
=> fix: fail pipeline on tests, correct concurrency naming

component/deploy/docker-compose.yaml
This tool is useful for collecting metrics about firecraccker specs, but ultimately burns a non-trivial amount of cpu on the machine that we could be using to operate more quickly. We can collect these usage metrics locally.
=> chore: remove proccess-exporter from prod

dev/Tiltfile, dev/docker-compose.platform.yml, dev/process-exporter-config/config.yml, dev/prometheus-config/config.yml
As in https://github.com/systeminit/si/pull/4538, we're removing this from the dev stack.
=> chore: remove proc exporter from the dev stack

app/web/src/components/SecretCard.vue, app/web/src/store/realtime/realtime_events.ts, app/web/src/store/secrets.store.ts, lib/dal/src/secret.rs, lib/dal/src/secret/event.rs, lib/dal/src/secret/view.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/server/service/secret.rs, lib/sdf-server/src/server/service/secret/delete_secret.rs
We can delete a secret if it has no connected components. Now we will also allow a user to see how many components are connected to a secret as part of the secrets list
=> feat(web, sdf): Add ability to delete a secret

lib/dal-test/src/test_exclusive_schemas/mod.rs, lib/dal-test/src/test_exclusive_schemas/starfield.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/tests/integration_test/module.rs, lib/dal/tests/integration_test/node_weight.rs, lib/dal/tests/integration_test/node_weight/attribute_prototype.rs
If a new connection update is detected for input socket with an Arity of one, issue RemoveEdge updates for any existing connections to ensure we don't accidentally merge multiple inputs to a 1-arity socket.
=> feat(dal): use corrections to protect socket arity

lib/sdf-server/src/server/service/change_set.rs
Tested locally, shown to throw 304 instead now when you intentionally API call add the same action twice, no 500 modal
```
< HTTP/1.1 304 Not Modified
< Access-Control-Allow-Origin: *
< content-type: application/json
< content-length: 102
< access-control-allow-credentials: true
< vary: origin, access-control-request-method, access-control-request-headers
< date: Wed, 11 Sep 2024 00:05:28 GMT
< connection: keep-alive
< 
```
This was causing grief in Production + metrics
=> feat: don't throw 500s on action already enqueued

lib/dal/src/action.rs, lib/dal/src/action/dependency_graph.rs, lib/sdf-server/src/server/service/action/list_actions.rs, lib/si-layer-cache/src/db/func_run.rs
`get_hold_status_influenced_by` will loop forever if there is a cycle in the dependency graph. Prevent that. Add instrumentation to detect cycles and also see more progress in list_actions.
=> fix: avoid potential infinite loop in list_actions, add instrumentation

lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1.rs, lib/dal/tests/integration_test/node_weight.rs, lib/dal/tests/integration_test/node_weight/schema_variant.rs
Ensure we replace existing default edges with non-default Use edges if there is a new default use edge to a schema variant in the set of updates.
=> feat(dal): ensure there can only be one default schema variant

app/web/src/components/ModelingView/ModelingRightClickMenu.vue
If component is not selected, the right click menu creates a component attribute store for the "NONE" component id, and then we react to events by attempting to fetch data about this "NONE" component. Let's avoid that.
=> fix(web): don't create NONE component attribute store

bin/si-api-test/README.md, bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/add_action.ts
Added action_list API Endpoint to client and created a test checking an action is added to the action_list when a component is created on a change set. 
Updated Readme for API testing tool. 
<div><img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWRjMjAwMzR4ZDBrZ3B1NWppOXFoMzduM2F0eWVtYXBveGRzejJudiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9dg/KpJ47gKe6b7v7xQyWj/giphy.gif"/></div>
=> feat: add_action api test and fix up readme

Cargo.lock, app/web/src/components/AttributesPanel/AttributesPanelItem.vue, app/web/src/components/SecretCard.vue, app/web/src/components/SecretsModal.vue, app/web/src/store/secrets.store.ts, lib/dal/src/func/runner.rs, lib/dal/src/key_pair.rs, lib/dal/src/queries/key_pair/get_by_pk.sql, lib/dal/src/queries/key_pair/public_key_get_current.sql, lib/dal/src/secret.rs, lib/dal/src/secret/view.rs
Only allow keypairs to be accessed from their original workspace, to avoid secret leaks. If a secret is unusable when gathering before funcs, the respective before func will be skipped as if the secret was empty.
Also adds UI that shows unusable secrets clearly:
=> fix: Only allow keypair access from the original workspaceId

app/web/src/api/sdf/dal/func.ts, app/web/src/store/func/funcs.store.ts, lib/dal-test/src/helpers.rs, lib/dal/src/func.rs, lib/dal/src/func/binding.rs, lib/dal/src/func/binding/attribute.rs, lib/dal/src/func/binding/attribute_argument.rs, lib/dal/src/func/binding/leaf.rs, lib/dal/src/pkg/export.rs, lib/dal/src/schema/variant.rs, lib/dal/tests/integration_test/func/authoring/binding.rs, lib/dal/tests/integration_test/func/authoring/binding/attribute.rs, lib/dal/tests/integration_test/schema/variant.rs, lib/dal/tests/integration_test/schema/variant/view.rs, lib/rebaser-server/src/dvu_debouncer_task.rs, lib/sdf-server/src/server/service/v2/func/binding/create_binding.rs, lib/sdf-server/src/server/service/v2/func/binding/update_binding.rs, lib/sdf-server/src/server/service/v2/func/list_all_funcs.rs, lib/si-frontend-types-rs/src/func.rs
This is part one of the intrinsics work, adding support to SDF while filtering these out on the front end so there's no impact to users. 
Intrinsic Functions will rely on the existing Attribute Bindings subsystem (as opposed to adding another abstraction as with Leaf Funcs).  For now, we are filtering out component specific bindings, and bindings for Input Sockets as these will not be configurable by users.  
Now, when listing functions, we include Attribute Bindings for the Identity and Unset Functions, so that we can expose the ability for users to configure identity funcs in the UI as opposed to using the asset builder `setValueFrom()` or having to create an attribute function that simply returns another prop/socket.  
This enables us to build the experience for configuring them, but …
=> feat(dal,sdf): Expose the ability to configure Identity and Unset Attribute Bindings via SDF.

lib/billing-events/src/lib.rs, lib/dal/src/action/prototype.rs, lib/dal/src/billing_publish.rs, lib/dal/src/job/definition/action.rs, lib/dal/tests/integration_test/action.rs
This PR removes the metadata field in billing events due to its potential unbounded size. While the metadata retrieval logic is still in play (mainly due to the "count"), it is unused. In the future, it should be batched up and sent in a another process or thread to adhere to data warehouse design conventions.
In addition to these changes, the ID of the func run is now recorded for both resource creations and resource deletions.
The chunking idea from #4562 has been abandoned, but the PR is there for history's sake.
=> Remove metadata field in billing event

lib/si-layer-cache/src/activity_client.rs
This is a pretty naive attempt to allow the system to wait longer during rebases to ensure we are correct even if we are slower. During load testing, the vast majority of errors seem to come from pressure on nats. While we definitely can (and will) scale up nats, it seems like having more padding here would be good under high-pressure situations. We typically see either nats failing to ack, which is likely directly due to nats being under too much load, and us throwing [this error](https://github.com/systeminit/si/blob/main/lib/si-layer-cache/src/error.rs#L33-L34), which is probably due to the same root cause, but is a lever we can pull more directly.
=> chore: increase parent_activity_timeout to 60 seconds

Cargo.lock, Cargo.toml, lib/si-data-nats/src/jetstream/context.rs, lib/si-data-nats/src/lib.rs, lib/si-data-nats/src/subscriber.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Notable is that this release contains our upstream KV create race fix and some lower level data types to work with direct getting messages.
https://github.com/nats-io/nats.rs/releases/tag/async-nats%2Fv0.36.0
References: nats-io/nats.rs#1301
=> chore(si-data-nats): upgrade to `async-nats` 0.36.0

Cargo.lock, lib/billing-events/BUCK, lib/billing-events/Cargo.toml, lib/billing-events/src/lib.rs, lib/dal/src/billing_publish.rs, lib/data-warehouse-stream-client/src/lib.rs, lib/forklift-server/src/handlers.rs
We were base64 encoding before forklifting, this wasn't required but was caused by confusion in the rust docs for the AWS client lib. Also when the data landed in S3 we can't analyse it.
Also we had no idea which order the events landed in, so I've added a timestamp to each event.
=> feat: move events away from base64 encooded, add timestamp

lib/dal/src/job/definition/dependent_values_update.rs
The condition for finishing the DVU after function failure was broken. This should ensure we always send StatusFinished events even if an execution fails.
Should close BUG-513
=> fix(dal): ensure DVU finishes after function failure

lib/dal/tests/integration_test/func/kill_execution.rs
The kill execution sender test runs a function that sleeps for 30 seconds, but this might not be enough time in CI for the test to run, given how many services it has to interact with. Up this to 240 seconds, which hopefully should make this test less flaky.
=> fix: kill execution sender test

lib/si-pool-noodle/src/lib.rs, lib/si-pool-noodle/src/lifeguard.rs, lib/si-pool-noodle/src/pool_noodle.rs, lib/veritech-client/tests/integration.rs, lib/veritech-server/src/config.rs, lib/veritech-server/src/server.rs
After a conversation with @fnichol we decided it would be better to use channels to pass work around here so we aren't hammering `pop()` in a bunch of threads and are instead just polling for work. We should be just as fast (if not faster) under load, but we'll be a lot quieter when sitting still. We limit total threads using a semaphore so we will block work until new slots  appear.
=> feat: change pool noodle to use channels to prevent spamming pop

lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs, lib/dal/tests/integration_test/node_weight/schema_variant.rs
A misunderstanding of how the default edge works meant my test for this was wrong, and this is currently removing default edges.
=> fix: revert schema variant default edge correction

lib/si-layer-cache/src/activities.rs
Based on the investigation, increasing the queue depth removes the bottleneck currently implied on the system. Onwards and upwards.
=> feat: change broadcast channel depth to 1000000

lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/rebaser-server/src/rebase.rs, lib/sdf-server/src/service/change_set/rebase_on_base.rs, lib/si-layer-cache/src/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs
Ensure we send the "from change set id" when applying to head, so that we can avoid replaying changes onto the change set that was just applied.
=> fix: don't replay onto the change set that was just applied

lib/sdf-server/src/lib.rs, lib/sdf-server/src/server.rs
The sdf refactor dropped the sigusr2 handler that set maintenance mode. This restores it. We don't have maintenance mode in prod right now so will have to be careful when deploying.
=> fix: restore maintenance mode signal handler

bin/si-api-test/binary_execution_lib.ts, bin/si-api-test/main.ts, bin/si-api-test/sdf_api_client.ts, bin/si-api-test/test_helpers.ts, bin/si-api-test/tests/emulate_paul_stack.ts
The paul stack tests builds a more complex diagram inspired on a section of  the  [AWS VPC si tutorial](https://docs.systeminit.com/how-tos/aws-vpc)
Adds a bunch of quick helpers to this specific test that I didn't want to declare as part of the client yet, but were invaluable for this implementation
You can run a batch of tests at once by passing -b or --batchSize to the deno task. Default for that is 1
=> feat: Implement the paul stack load test and immediate batches to api tests

lib/rebaser-server/src/rebase.rs
Double applied event causes frontend to try and fetch deleted components.
=> fix: don't send double applied event on apply to head

Cargo.lock, Cargo.toml, lib/telemetry-application-rs/BUCK, lib/telemetry-application-rs/Cargo.toml, lib/telemetry-application-rs/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Note: this acts badly in local dev as each service will attempt to spin this up. We can make this behave more nicely if we decide we want to ship this for real.
=> feat: add tokio_console to the telemetry stack

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
This removes the double change set creation when editing a select box on HEAD. The other types seem fine, this only happened with select boxes, and using onChange appears to be enough for them.
=> fix: remove onBlur for select boxes, only fire update on change event

lib/si-layer-cache/src/db/cache_updates.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/memory_cache.rs
Rather than deserializing all values from cache update messages immediately upon receipt, the MemoryCache is now able to store both the deserialized values, and the raw, serialized bytes. If an entry that is currently storing the raw, serialized bytes is retrieved, it will deserialize it at that time, and replace the entry with the deserialized version to prevent having to deserialize it again on next retrieval.
Since we are unlikely to need to retrieve every object we receive cache update messages for, this should significantly reduce the overall amount of time spent processing incoming cache updates, with a hit to the time it takes for the first retrieval of an object we received through a cache update (with no change in subsequent retrieval times).
=> Update LayerDb to lazily deserialize values from cache update messages

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetListItem.vue, app/web/src/store/asset.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/schema/variant.rs, lib/dal/src/ws_event.rs, lib/sdf-server/src/service/variant/regenerate_variant.rs
Regenerate could set the active asset id to a value that the websocket hadn't filled in yet. This PR makes schema variant replace operation into a single message, and the regenerate success call back not do anything, so we don't race anymore.
Schema variant update also used to move multiplayer users to the latest updated asset even if they weren't editing it, this PR fixes that.
=> fix: regenerate was racing websockets

lib/sdf-server/src/service/diagram/delete_component.rs
When deleting multiple components of the same SV, we didn't clean up the graph, so after the first component deletion the orphaned AVs would be touched, but wouldn't refer to anything anymore, triggering the error - thanks @zacharyhamm for spotting this!
=> fix: Cleanup graph after individual deletes

app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/store/components.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/component.rs, lib/sdf-server/src/service/diagram/set_component_position.rs
We were filtering component geometry websocket requests via user pk, which made diagrams from different tabs for the same user not be in sync with each other. 
Now the frontend generates a temporary client_ulid so it can know to ignore messages from the same tab (movement gets laggy if we don't), but not from other tabs from the same user.
=> fix: Same account diagram position multiplayer

lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/input_socket_node_weight/v1.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
Turns out that `self.content_address.to_string()` is just the name of the enum variant (`SchemaVariant`, `InputSocket`, etc.) and doesn't actually include any of the hash itself.
The uses of `self.content_address` inside of `serde_json::json![...]` are technically fine, since `serde_json` will basically output a form of the debug output of the enum, but it's such an easy thing to forget that `serde_json` has special handling that it felt like we should avoid using it directly for the `node_hash` in general.
=> Correct node_hash calculation for InputSocketNodeWeight and SchemaVariantNodeWeight

component/init/configs/service.toml
Making this configurable to we can more easily experiment with pg pooling mechanisms
=> chore: allows db proxy target to be configurable

lib/si-pool-noodle/src/errors.rs, lib/si-pool-noodle/src/pool_noodle.rs, lib/veritech-server/src/handlers.rs, lib/veritech-server/src/server.rs
This allows Veritech to `nack` function run requests that fail prior to the actual function execution, such as if the cyclone pool is starved or the message fails to deserialize. On `nack`, the message will be put back into Jetstream, allowing an Veritech to pick it up (the same one or a different one) and try again. This should help cover off on pool starvation scenarios, giving us a chance the retry failures and let the pool refill. We will retry messages up to five times before giving up.
In the future, we should consider a [dead letter queue](https://docs.nats.io/using-nats/developer/develop_jetstream/consumers#dead-letter-queues-type-functionality) so we can determine what to do with these when they completely fail out.
This PR also reduces the execution pool timeout to 2 minutes, …
=> feat: nack veritech function run failures

lib/dal/src/action.rs, lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/action_prototype_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/category_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/dependent_value_root_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/finished_dependent_value_root_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_argument_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/input_socket_node_weight/v1.rs, lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs, lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1.rs, lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
The only reason we were using `serde_json::json![...]` was to have something to feed into the `ContentHash` hasher. We didn't need the JSON itself as anything other than a sequence of bytes.
Rather than spending the time to serialize everything as JSON, just to feed the string representation as a sequence of bytes to the hasher, we now feed the values in directly to the hasher as sequences of bytes, bypassing the JSON serialization entirely.
=> Remove all usage of serde_json::json![...] in node_hash node weight methods

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/toasts/RetryApply.vue, lib/sdf-server/src/service/change_set.rs, lib/sdf-server/src/service/change_set/apply_change_set.rs
This PR ensures that we fail on applying a change set in `sdf` if DVU roots are not empty. A toast will be fired if this happens, which should be rare and require no additional user action.
=> Fail on apply if DVU roots are not empty

lib/dal/src/attribute/value.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/runner.rs, lib/dal/src/job/definition/dependent_values_update.rs
There were several more func run writes hiding in the execution path for functions. Removing these for intrinsics. We should also consider doing them less often for js attributes if it makes sense.
=> fix: remove even more func run writes

app/web/src/store/components.store.ts, lib/sdf-server/src/service/diagram/create_connection.rs, lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
onSuccess response for create_connection was creating an edge with an outdated id on the store
bonus: Now you can't select disabled dropdown entries
=> fix: Delete newly created edges correctly

lib/naxum/src/middleware/ack/maintain_progress.rs
Make it so we `ack` messages as soon as we get them and then continue the current `ack` loop on a timer. This is to ensure we aren't doing duplicate work when under load by accidentally pulling the same message multiple times.
=> feat: ack nats streams as soon as we get them

lib/dal/src/component.rs, lib/dal/src/job/definition/action.rs
This makes it so we send the ResourceCreated event anytime a resource payload is added, and ResourceDeleted event when a resource payload is removed. Before this, we triggered ResourceCreated for a Create action, and ResourceDeleted for a Delete action; but if the action fails we still send the event; and if the create has no payload, or some other action *has* a payload, we send the wrong event or don't send it.
With this code, it doesn't matter what our logic is for whether to add a resource: if there was no resource before and there is one now, it's a create; and if there was a resource before and not after, it's a delete. This way the creates and deletes will exactly match changes in the resource count, which is what we want.
=> Only send create/delete events if the resource property is set or unset

app/web/src/api/sdf/dal/schema.ts
These dropdowns get awful big, and having a random order makes it *very* hard to find the attribute or socket I want.
After:
Before:
=> Order sockets and props in binding dropdowns alphabetically

bin/si-api-test/binary_execution_lib.ts, bin/si-api-test/main.ts, bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/create_and_delete_component.ts, bin/si-api-test/tests/create_two_components_connect_and_propagate.ts, bin/si-api-test/tests/emulate_paul_stack.ts
This adds a rudimentary listener for DVU-related ws events for a specific workspace. The idea is to gather all DVU started events for a given component and watch for related finished events to ensure that we wait until they all complete. This is not an exact science and could potentially miss DVU started events if they take too long to start.
This also adds the ability to pass specific change sets into the api tests.
=> feat: add DVU listener for API tests

lib/dal-test/src/expected.rs, lib/dal-test/src/helpers.rs, lib/dal/src/component.rs, lib/dal/src/component/frame.rs, lib/dal/tests/integration_test/component/delete.rs, lib/dal/tests/integration_test/component/get_diff.rs, lib/dal/tests/integration_test/component/set_type.rs, lib/dal/tests/integration_test/frame.rs, lib/dal/tests/integration_test/frame/omega_nesting.rs, lib/sdf-server/src/service/component/set_type.rs
This PR adds an ability to `update_type_by_id` which, when called, and the component type is changing to or from an up or down frame, ensures we update any relevant attribute values that have different inputs given the new type. 
I also fixed up some of the tests that are manually setting the type on creation to use a helper, and added comments to differentiate when we should `update_type_by_id` vs. `set_type_by_id` which does not update necessary values, nor does it ensure that the new component type won't cause other problems.
=> Ensure values are updated correctly when changing a component's type.

lib/dal/src/component.rs, lib/dal/src/job/definition/action.rs
We handled all the crazy cases such as when a delete action succeeds but contains a payload, and ended up with a failure in the simple, normal delete case! Since the resource delete event reports the component name, the event needs to be built before the resource is actually deleted. This does it right at the time the resource is set or unset.
This means the window where the event could be sent but the commit could fail is wider; but if such a thing does happen, there will be *extra* anomalous events in the record rather than missing ones, which seems better.
This was also causing pinga to complain that the delete action failed (even though all the commits had gone through). Seems like it was just a logging thing, however--no functionality seems to have been impacted.
=> Send delete event correctly when component is actually deleted

component/deploy/docker-compose.yaml
Set pgbouncer based on the init version as they are more likely to be built together.
=> fix: pgbouncer should be set by init version

app/web/src/components/AttributesPanel/AttributesPanelItem.vue
=> Fix BUG-548: move the X for select box and combo box to not be on top of dropdown icon

app/web/src/components/AssetCard.vue, app/web/src/components/AssetEditor.vue, app/web/src/store/asset.store.ts, lib/vue-lib/src/pinia/pinia_api_tools.ts
Adding a new option to ApiRequest for a callback that will run when a new change set is created. This is a halfway elegant feature. It's not the prettiest thing, given that it is in the context of the OLD store with the original change set where the change was initiated. 
So, to resolve that, you have to go grab the correct store—which is in the midst of being activated and all the requests to build the data within the store is in flight. You have to wait for the data to arrive before interacting in some cases. I tried making that not the case here, but it really introduces unnecessary complications in other components, where you have to take into account a number of things that by default don't make sense and no one would do by nature.
=> BUG-561: authoring pain when starting from head

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
The problem was that the "fitInsideOf" size was too large/overflowing the boundary checking... make it a bit smaller and we're all set here.
=> BUG-575: fix first resize on child frame

lib/dal/src/pkg/import.rs, lib/sdf-server/src/migrations.rs
This PR tunes down sdf migrations logging in three areas. In all areas, the logging is tuned to debug-level.
The first change involves logging when migrating individual modules. At the time of writing, these modules take ~0.00-0.01 seconds to migrate each. In addition, there are now over 100 modules installed, so the logging spammed is not only no longer useful, but is also particularly noisy.
The second change involves logging when modules have already been installed. Currently, this is a warning-level log and now, the message has been re-written to indicate that we are explicitly skipping the installation.
The third change involves logging when importing a schema from a module. This area is potentially the area most sensitive to change as it will also change the log level for installed …
=> Tune down sdf migrations logging

lib/dal/src/attribute/value/dependent_value_graph.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/dependent_values_update.rs
A bug in the implementation of the component concurrency limit meant we were writing all dvu roots as "finished", but luckily still executing them (i'm not really sure how it worked!). But this broke some transform corrections related to DVUs, which was noticed when fixing the component deletion bug. This ensures we write the roots correctly and restores the component concurrency limit test.
=> fix: don't write all dvus as finished by default

bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/create_and_apply_across_change_sets.ts
All of these test workspaces now have the test asset installed.
1. ensure the HEAD has 0 components by deleting them all and applying
2. create 10 change sets and create one of the test components
3. `pop` one of the change sets off and apply it
4. walk all of the remaining change sets, ensure they now have two components  on the graph, and abandon them
=> feat: add test for applying with 10 open change sets

lib/naxum/src/middleware/trace/mod.rs, lib/rebaser-server/src/server.rs
This isn't a complete solution to inspect a change set-processing task
*during* its execution, but a starting signal that we can use in tracing
to better understand the process task's lifecycle.
=> chore(rebaser): add INFO event when a processing task is starting

Cargo.lock, Cargo.toml, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/service.rs, lib/sdf-server/src/service/change_set.rs, lib/sdf-server/src/service/component.rs, lib/sdf-server/src/service/diagram.rs, lib/sdf-server/src/service/module.rs, lib/sdf-server/src/service/qualification.rs, lib/sdf-server/src/service/session.rs, lib/sdf-server/src/service/v2/admin.rs, lib/sdf-server/src/service/v2/func.rs, lib/sdf-server/src/service/v2/module.rs, lib/sdf-server/src/service/v2/variant.rs, lib/sdf-server/src/service/variant.rs, lib/sdf-server/src/service/ws.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This pushes all SDF APIErrors through the ApiError type so we can centralize decision making about what level to emit for different types of errors. By default, we will `WARN` on 400s and `ERROR` on 500s. It is currently unused, but `ApiErrors` can take an optional level which will force emitting at that level regardless of the status code (like if we want to throw a 500, but only have it appear as a warn in the logs). 
Note that the default `on_failure` mode still exists, so tower will always throw an error on 500s. We could disable this entirely, but it seems like it will be useful to catch things like networking issues so we can still return. The actual error types are not pushed down into this level, so we cannot do the matching here (nor do the tower devs recommend we try.
Here's an …
=> feat: allow trace level to be set for API Errors

lib/dal/src/component/frame.rs, lib/dal/src/diagram.rs
This PR informs the frontend of new, inferred edges on component creation. This happens when creating a component and directly placing it into a frame.
This PR also handles an edge case for mutated, inferred connections when detaching children of frames.
Example scenario: there's a grandparent up-frame, a parent down-frame and a child component or up-frame. If the parent frame has an input socket with an arity of one and both the child and grandparent have an output socket with a matching annotation, then the edge will be mutated. The parent will now have a different value at its input socket because the source side of the edge has changed.
=> Upsert new inferred edges on creation

lib/sdf-server/src/service/v2/variant.rs
Deleting won't happen as there are nodes on the graph connected to the variant - it's not really a 500 more of a 412
The user already gets notified of this with messages like:
=> fix(sdf): Don't send 500 on schema variant deletion precondition failure

lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring/update_variant.rs
We used to keep around old unused variants to be garbage collected eventually, which possibly left a lot of broken bindings laying around. This PR deletes variants that will be left unused immediately after a regenerate
=> fix: Delete old variant on fast-forward regenerate

Cargo.lock, lib/billing-events/BUCK, lib/billing-events/Cargo.toml, lib/billing-events/src/lib.rs, lib/forklift-server/src/handlers.rs, lib/forklift-server/src/server.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock
This change allows the Forklift service to participate in cross-service traces. In theory, the time between
`billing_events_work_queue.publish_workspace_update` and the server's `billing.workspace_update.:workspace_id receive` spans is the time the message is sitting in the NATS stream. Cool, no?
=> feat(forklift): add publish/process span propagation

lib/dal/src/job/definition/dependent_values_update.rs
Turns it down to a warn event instead of an error
=> fix(dal): Warn instead of error during DVU when functions fail

component/spicedb/BUCK, component/spicedb/Dockerfile, component/spicedb/entrypoint.sh, component/spicedb/schema.zed, dev/Tiltfile, dev/docker-compose.platform.yml
We're planning to use SpiceDb as our authz solution. This adds it to the tilt stack. I set the container to build when starting tilt so we can add changes to `schema.zed` to validate changes as we go without having to push container images along the way. We will still build and ship images in CI.
I also reorganized the tilt file a bit.
=> feat: add custom spicedb container image

app/docs/src/reference/typescript/asset_builder/classes/MapKeyFuncBuilder.md, app/docs/src/reference/typescript/asset_builder/classes/PropBuilder.md, app/docs/src/reference/typescript/asset_builder/classes/SocketDefinitionBuilder.md, app/web/src/api/sdf/dal/schema.ts, app/web/src/assets/static/editor_typescript.txt, app/web/src/components/AssetDetailIntrinsicInput.vue, app/web/src/components/AssetDetailsPanel.vue, app/web/src/store/feature_flags.store.ts, bin/lang-js/src/asset_builder.ts, lib/dal/src/schema/variant/authoring.rs, lib/dal/tests/integration_test/schema/variant/authoring/regenerate.rs, lib/sdf-server/src/service/v2/func.rs, lib/si-pkg/src/spec/prop.rs, lib/si-pkg/src/spec/variant.rs, lib/vue-lib/src/design-system/forms/VormInput.vue
This PR switches to the new asset details paradigm, which involves intrinsic func editing. To start, it will use the unset func and the identity func to set bindings. This PR includes several UI changes to support this includng a caution lines setting, converging on one design for the dropdowns, filtering for the dropdowns, checkboxes for the dropdown, and sorting configurable props and output sockets by name.
This PR also ensures that we retain func bindings when regenerating assets and switches to the new asset details panel paradigm, which replaces `setValueFrom` and it enables intrinsic func authoring for all.
The bug was caused by relying on the identity func when merging prototypes for both prop and socket output locations between two schema variants. Now, conditional logic based on …
=> Switch to new asset details panel paradigm

lib/dal-test/src/lib.rs, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/lib.rs, lib/si-layer-cache/src/persister.rs, lib/si-layer-cache/tests/integration_test/activities.rs, lib/si-layer-cache/tests/integration_test/activities/rebase.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/func_run.rs, lib/si-layer-cache/tests/integration_test/db/func_run_log.rs, lib/si-layer-cache/tests/integration_test/db/workspace_snapshot.rs, lib/si-layer-cache/tests/integration_test/disk_cache.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs, lib/si-layer-cache/tests/integration_test/mod.rs
Adds a simple, configurable TTL to disk cache items. The default behavior is to check hourly for items that have been in the cache for more than 24 hours, removing them if it finds them. 
On get, we will write the got data back to the cache to ensure that the metadata is current. This is wasteful, but should be infrequent as we should find these items in the memory cache until the next start.
=> feat: add basic TTL-based eviction to the disk cache

component/spicedb/BUCK, component/spicedb/Dockerfile, component/spicedb/entrypoint.sh, component/spicedb/schema.zed, component/spicedb/validation.yaml
This adds a super basic approval schema and way to validate it by setting assertions and validations in a yaml file. The container will be built when tilt is up and the validations will run automatically. 
```
Success! - 1 relationships loaded, 2 assertions run, 1 expected relations validated
```
=> feat: add rudimentary authz schema and validation

component/spicedb/Dockerfile
=> fix: spicedb entrypoint permissions must be execute

lib/dal/examples/rebase/main.rs, lib/dal/src/workspace_snapshot/graph.rs
The changes to the "rebase" example here were used to repair a broken workspace in prod, so this is a good starting point if we have to do this again.
=> chore: show how snapshots can be repaired

component/lambda/functions/si_lago_api.py, component/lambda/functions/si_logger.py, component/lambda/functions/si_redshift.py, component/lambda/functions/si_types.py, component/lambda/functions/track_resource_counts.py, component/lambda/functions/upload_billing_resource_hours_to_lago.py, component/lambda/sql/billing.sql
The SQL file here captures the views and tables we've created for billing so far in Redshift. The python scripts correspond to two other lambdas:
- `upload_billing_resource_hours_to_lago.py`: uploads all billing resource counts to Lago to be counted in each user's Usage (and eventually, invoice).
- `track_resource_counts.py`: processes incoming events from SDF into a coherent table, `workspace_resource_counts`, with a row for each time a workspace's resource count changed, as well as the timespan it was active, so you can query it to find out what count a workspace had at any arbitrary time. This will be replaced with `workspace_resource_counts_view` in the SQL when I have time for testing that.
- `si_logging.py`: just sets up a common logging object.
- `si_redshift.py`: a little query …
=> Upload billing events to Lago via Lambda

.ci/docker-compose.test-integration.yml, Cargo.lock, Cargo.toml, lib/dal-macros/Cargo.toml, lib/dal-macros/tests/ui/07-node_weight-no-discriminant-specified-fail.stderr, lib/dal-macros/tests/ui/08-node_weight-bad-node_hash-custom-code-fail.stderr, lib/si-data-spicedb/BUCK, lib/si-data-spicedb/Cargo.toml, lib/si-data-spicedb/src/lib.rs, lib/si-data-spicedb/src/types.rs, lib/si-data-spicedb/tests/integration.rs, lib/si-data-spicedb/tests/integration_test/mod.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This client wraps the `spicedb-client` and `spicedb-grpc` crates with instrumentation and some request/response wrapping types.
=> feat(si-data-spicedb): create initial SpiceDB Rust client

bin/module-index/README.md, lib/dal/src/func.rs, lib/dal/src/pkg.rs, lib/dal/src/pkg/import.rs, lib/dal/src/schema.rs, lib/dal/src/schema/variant.rs, lib/sdf-server/src/service/module.rs, lib/sdf-server/src/service/module/install_module.rs
This PR installs module upgrades as editing assets in order to not clobber your local changes to a module's asset. Now, you'll be able to work with the editing asset from upstream before applying your change set. Alongside the editing asset will be its unlocked asset func so that regenerations are possible.
This commit also blocks upgrading modules when you having an editing asset for the module available. If there's an older module that does not know its core `SchemaId`, then we will install anyway, which is how things work on main today. However, those modules should not exist anymore since the `SchemaId` is now required for new modules.
The import code has been polished and modernized a bit with unused variables and code being dropped wholesale.
=> Install module upgrades as editing assets

lib/si-runtime-rs/src/lib.rs
this should prevent the severe slowdown Wendy has been seeing on her M1 macbook
=> fix for tokio blocking pool size on macos

lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/tests/integration_test/disk_cache.rs
Currently, every 3600 seconds, 10s of thousands of disk cache tasks will attempt to evict stale files, exhausting CPU. Let's stop the disk cache eviction feature from spawning one long running eviction task per layer cache event. Instead spawn just one per distinct disk cache (as defined by the write path).
=> fix: spawn one cleanup task per distinct disk cache

component/init/configs/service.toml, lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/tests/integration_test/disk_cache.rs
* Allows the disk cache cleanup to be run in no-op for validation
* Adds a config setting for adjusting the disk cache cleanup mode
* Re-enable disk cache cleanup
* Track and report on the disk cache cleanups
* Ensure we are removing both the index and the content when we remove from the disk cache
```
2024-10-14T15:25:13.975559Z  INFO ThreadId(57) si_layer_cache::disk_cache: Disk cache cleanup mode no-op removed 0 out of 0 expired items
2024-10-14T15:26:13.984540Z  INFO ThreadId(50) si_layer_cache::disk_cache: Disk cache cleanup mode no-op removed 0 out of 368 expired items
2024-10-14T16:12:05.830532Z  INFO ThreadId(64) si_layer_cache::disk_cache: Disk cache cleanup mode remove removed 0 out of 0 expired items
2024-10-14T16:12:15.869308Z  INFO ThreadId(30) si_layer_cache::disk_cache: …
```
=> fix: add no-op mode and ensure item cleanup for disk cache

lib/dal/src/audit_log.rs, lib/dal/src/lib.rs, lib/dal/tests/integration_test/audit_log.rs, lib/dal/tests/integration_test/mod.rs, lib/sdf-server/src/service/v2.rs, lib/sdf-server/src/service/v2/audit_log.rs, lib/sdf-server/src/service/v2/audit_log/list_audit_logs.rs, lib/si-events-rs/src/audit_log.rs, lib/si-events-rs/src/lib.rs, lib/si-frontend-types-rs/src/audit_log.rs, lib/si-frontend-types-rs/src/lib.rs
This PR adds mocked audit logs for the frontend. Currently they are based in the `dal`, though it is likely that they will move to their own crate.
It's not in this PR, but there is a difference between a "frontend type" audit log and the audit log that will be ultimately be stored in the database. The purpose of this commit is to unlock frontend creativity by providing generated audit logs. It is not meant to reflect the structure that will ultimately be used by backend services.
=> Mock audit logs for frontend

Cargo.lock, component/spicedb/entrypoint.sh, lib/si-data-spicedb/BUCK, lib/si-data-spicedb/Cargo.toml, lib/si-data-spicedb/src/lib.rs, lib/si-data-spicedb/src/types.rs, lib/si-data-spicedb/tests/integration_test/mod.rs
This adds crud operations for relationships and the ability to verify permissions against them.
=> feat: add spicedb client relationship and permission calls

component/lambda/functions/set_user_prices_in_lago.py, component/lambda/functions/si_lago_api.py, component/lambda/functions/si_redshift.py
This Python code determines which users are (and are not) in free tier, and sets the price on their subscriptions accordingly. What it does:
1. Figures out whether last month has been invoiced or not yet. (At the moment this means it waits until the 5th, after the invoices have been moved out of draft on the 3rd.)
2. Determines who is in free tier and who is not based on `SELECT owner_pk, max_resource_count FROM owner_billing_months WHERE month = :billing_month` from Redshift
3. Gets the subscription ID we downloaded from Lago to Redshift in a separate process, via `SELECT owner_pk, external_subscription_id FROM latest_owner_subscriptions`.
4. For each user, checks if their subscription is at the right price already. If it isn't, does `PUT /api/v1/subscriptions/{external_subscription_id}` …
=> Set user prices based on whether they are in the free tier

lib/dal/src/audit_log.rs, lib/dal/tests/integration_test/audit_log.rs, lib/sdf-server/src/service/v2/audit_log/list_audit_logs.rs, lib/si-events-rs/src/audit_log.rs
This PR adds filtering and pagination to fake audit logs that were first introduced in commit 51f424a.
It performs a "second pass" filtering and pagination run on a generated list of audit logs. Not only that, but this PR also polishes audit log generation log, standardizes users and makes random number generation easier to follow.
=> Add filtering and pagination to fake audit logs

lib/dal/src/change_set.rs
Right now, we're reporting the old snapshot address when we publish the "SnapshotUpdated" event, because we do it before we actually set the snapshot address. This moves the event to after, reporting the correct address.
=> Report new snapshot address (not old) in billing event

lib/si-firecracker/src/firecracker.rs, lib/si-firecracker/src/scripts/firecracker-setup.sh
This will ensure that when we need to download a new rootfs image, we will completely remove the existing image by cleaning all jails and removing the existing dmsetup bits for the rootfs.
=> fix: ensure the rootfs can be replaced

lib/si-layer-cache/src/disk_cache.rs
`remove_hash()` removes the content, which is checked by `.exists()`.
`remove()` removes the index, which is checked by `.metadata()`.
=> fix: disk cache removal types swapped

bin/lang-js/src/function_kinds/action_run.ts, lib/cyclone-core/src/action_run.rs, lib/cyclone-server/src/result/action_run.rs, lib/dal/src/component.rs, lib/dal/src/func/authoring/ts_types.rs, lib/dal/src/func/backend/js_action.rs, lib/dal/src/job/definition/action.rs
Actions can now return a resourceId which will set the /root/si/resourceId prop (if it exists on the component). This enables creates that set resourceId instead of the payload, allowing the refresh to set the resource payload.
=> feat(ENG-2745): actions can set resourceId

Cargo.lock, Cargo.toml, lib/permissions/BUCK, lib/permissions/Cargo.toml, lib/permissions/src/lib.rs, lib/permissions/src/schema/schema.zed, lib/permissions/tests/integration.rs, lib/permissions/tests/integration_test/mod.rs, lib/si-data-spicedb/src/lib.rs, lib/si-data-spicedb/src/types.rs, lib/si-data-spicedb/tests/integration_test/mod.rs
Adds a lib for defining concrete permission and relation types and a builder for interacting with them. The spicedb client itself must be passed in.
=> feat: add permissions lib and builder for relations and permissions

app/web/src/components/AssetDetailIntrinsicInput.vue, app/web/src/components/AssetDetailsPanel.vue, app/web/src/store/func/funcs.store.ts, lib/vue-lib/src/design-system/forms/VormInput.vue
Addresses three problems:
1. The VormInput child registration was not coming back in the expected order, so the value that was set was not the one the user actually selected. I'm not sure exactly why we were looking at indexes, rather than using the value in the target. I attempt to keep multi-select/checkboxes working, but I don't see any examples in the app to test against.
2. The "flashing" we were seeing was due to WsEvent `SchemaVariantUpdated` firing before `FuncUpdated`. The latter updates the bindings struct, so the former was resetting the form based on the prior saved value. The fix is to optimistically change the bindings data structure.
3. When you unlock a function the prop/socket display is wrong. It is wrong because the new SchemaVariant that comes into being does not …
=> Fix intrinsics dropdown

.github/workflows/crons.yml, .github/workflows/deploy-stack.yml
This is fun. Since the crons that run against prod were set to `e2e-tools` so we were cancelling them during tools deploys :upside_down_face: . 
We set concurrency based on the environment during deploys. The result will be:
* Multiple deploys will queue and happen sequentially to ensure that deploys don't cancel each other and put us in a weird state
* Deploys will share concurrency with the crons, so we won't deploy until the tests are finished running (and tests won't start while a deploy is happening) to ensure we don't get erroneous errors
=> fix: e2e concurrency flags

bin/lang-js/src/component.ts, bin/lang-js/src/function_kinds/management.ts, lib/cyclone-client/src/client.rs, lib/cyclone-core/src/component_view.rs, lib/cyclone-core/src/lib.rs, lib/cyclone-core/src/management.rs, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/attribute/value.rs, lib/dal/src/func/authoring/ts_types.rs, lib/dal/src/func/backend/management.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/tests/integration_test/management.rs, lib/sdf-server/src/service/v2/management.rs, lib/veritech-client/src/lib.rs, lib/veritech-client/tests/integration.rs
Authoring a real import has revealed some missing pieces to the management function types. This reworks it so we will be ready for the future extensions to the type (like managing multiple components, and setting geometry on the managed components) and so we can report failures in the management execution.
=> feat: Add more to management func types

.github/workflows/deploy-stack.yml, .github/workflows/prod-crons.yml, .github/workflows/tools-crons.yml
<div><img src="https://media2.giphy.com/media/wIAzgC4sqiGaeKMhr2/200.gif?cid=5a38a5a21hxpwrbqcbof6iqdtzr43f2uiqbkgw5ufwhdyi5l&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:171px;width:300px"/><br/>via <a href="https://giphy.com/paramountplus/">Paramount+</a> on <a href="https://giphy.com/gifs/paramountplus-season-3-paramount-icarly-wIAzgC4sqiGaeKMhr2">GIPHY</a></div>
=> Add second cron for running e2e tests against tools production, fix deployment so we cancel running e2e tests if a deploy is kicked off

bin/lang-js/src/function_kinds/management.ts, lib/dal/src/func/authoring/ts_types.rs, lib/dal/src/management/mod.rs, lib/sdf-server/src/service/v2/management.rs
Adds `actions?:` to the return type of a management operation, keyed by the component id, allowing you to add or remove actions. Adding an action that does not exist is an error, but removing an action that does not exist is a no-op. Adding an already added action is a no-op, so is removing an already removed action.
=> feat: management functions can add or remove actions

lib/si-pool-noodle/src/instance/cyclone/local_uds.rs
We're not printing the actual issue, so we didn't learn that the *reason* it couldn't create a temp socket was it couldn't access `/tmp/nix-ag234sfd` :)
=> Print underlying error for pool noodle issues

app/auth-portal/src/components/WorkspaceLinkWidget.vue, app/web/package.json, app/web/src/components/AuditLogHeader.vue, app/web/src/components/Workspace/WorkspaceAuditLog.vue, app/web/src/components/layout/navbar/NavbarPanelCenter.vue, app/web/src/pages/DebugPage.vue, app/web/src/router.ts, app/web/src/store/feature_flags.store.ts, app/web/src/store/logs.store.ts, lib/dal/src/audit_log.rs, lib/dal/tests/integration_test/audit_log.rs, lib/sdf-server/src/service/v2/audit_log/list_audit_logs.rs, lib/si-events-rs/src/audit_log.rs, lib/vue-lib/package.json, lib/vue-lib/src/design-system/general/IconButton.vue, lib/vue-lib/src/design-system/menus/DropdownMenu.vue, pnpm-lock.yaml
- Currently the filters for Actor and Change Set are based on the current data in the frontend. Eventually in order to filter for any possible event, we need to expand that data to include Actors who have been removed from the workspace and Change Sets which have been abandoned.
- Logs can be sorted by timestamp and filtered by everything except IP address. Would like to add filtering by IP address UI if I get the time.
- The pagination controls work, though I'd like to add UI for selecting an arbitrary page so that if there are 100's of pages you can jump to a specific one.
- The display of the data is pretty bare bones for now, will be doing improvements on that as well.
=> audit log mock behind feature flag

component/toolbox/scripts/supporting-funcs/ssm-funcs.sh
Tools is failing deployment, possibly because a new migration that's already on main is running for too long, since it needs to touch all the graph nodes.
=> fix: Raise sdf migration timeout on tools

app/web/src/store/func/funcs.store.ts
This PR fixes the ability to update display names and descriptions for funcs. This adheres to the logic enforced by https://github.com/systeminit/si/commit/f7618f6081996b4bc553a4cfea5a56cd6bcb6791.
=> Fix ability to update func metadata

lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/disk_cache.rs
It seems that the `cacache` index grows more or less indefinitely, meaning our list calls get more and more expensive over time. We are going to disable this temporarily while we devise a better long-term solution.
=> fix: disable disk cache cleanup

lib/dal-test/src/expected.rs, lib/dal/src/attribute/value.rs, lib/dal/src/pkg/import.rs, lib/dal/src/prop.rs, lib/dal/src/secret.rs, lib/dal/tests/integration_test/attribute/value.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/property_order.rs, lib/dal/tests/integration_test/rebaser.rs
Right now, object fields on a component are rearranged sometimes (for example, when setting properties, switching an object property from "set from socket" to "set from manual," and when updating a component to a new asset version. This has several effects:
* This causes the component property editors to show properties in different orders at different times (and for different components from the same asset), making it hard to work with.
* The orders also don't tend to match what was specified by the asset author, which makes it hard for authors to group related fields or put important fields first (hurting the experience for authors and users alike).
* This also causes BUG-633, where copy/pasting a component can cause values to copy into the wrong fields. This is because the copy/paste …
=> Always sort object fields in their schema-defined order

Cargo.lock, Cargo.toml, lib/dal/src/audit_log.rs, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/extract.rs, lib/sdf-server/src/service/v2/audit_log/list_audit_logs.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml, third-party/rust/fixups/target-triple/fixups.toml
This PR adds a custom extractor for filtering audit logs. Generally, it handles array notated query string parameters, which is likely the first time we needed to do so in `sdf`.
=> Add custom extractor for filtering audit logs

Cargo.lock, lib/dal-test/BUCK, lib/dal-test/Cargo.toml, lib/dal-test/src/test_exclusive_schemas/category_pirate.rs, lib/dal-test/src/test_exclusive_schemas/category_validated.rs, lib/dal-test/src/test_exclusive_schemas/dummy_secret.rs, lib/dal-test/src/test_exclusive_schemas/fake_butane.rs, lib/dal-test/src/test_exclusive_schemas/fake_docker_image.rs, lib/dal-test/src/test_exclusive_schemas/fallout.rs, lib/dal-test/src/test_exclusive_schemas/katy_perry.rs, lib/dal-test/src/test_exclusive_schemas/legos/large.rs, lib/dal-test/src/test_exclusive_schemas/legos/medium.rs, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal-test/src/test_exclusive_schemas/mod.rs, lib/dal-test/src/test_exclusive_schemas/starfield.rs, lib/dal-test/src/test_exclusive_schemas/swifty.rs, lib/dal/tests/integration_test/module.rs
In order to test management of other components, we need stable schema ids in our integration tests. This gives our test schemas those necessary stable ids.
=> chore: give test schemas stable schema ids

component/lambda/functions/si_logger.py, component/lambda/functions/si_redshift.py, component/lambda/functions/upload_billing_resource_hours_to_lago.py
We were logging it with WARN before, which seems to have been triggering some metrics.
Also makes Redshift logger only log query status every 5 seconds to stop spamming the log
=> Billing lambda: log upload stats using INFO

lib/rebaser-server/src/app_state.rs, lib/rebaser-server/src/change_set_processor_task.rs, lib/rebaser-server/src/handlers.rs, lib/rebaser-server/src/rebase.rs, lib/rebaser-server/src/server.rs
This PR adds the ability to track server-level tasks in the rebaser. This is useful for spawning tasks in the change set processor that are allowed to outlive the lifetime of the processor task itself.
This PR is a continuation of the initial effort from https://github.com/systeminit/si/pull/4814.
=> Track server-level tasks in the rebaser

component/ci-base/Dockerfile
See https://buildkite.com/system-initiative/si-merge-queue/builds/3718#0192b88d-cf84-43f0-8f40-871fb2272185
<div><img src="https://media4.giphy.com/media/HxnMNAEQgHqEHcGKBb/200.gif?cid=5a38a5a2hu05j1kzbmzpzhg126j0gq3mktt8tpzjks5ob5eb&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:165px;width:300px"/></div>
=> fix: nixFlakes renamed to nixVersions.stable

.github/workflows/prod-deploy-cron.yml
You can't have a downstream workflow with the same concurrency indicator as the parent caller. Remove it from the caller (cron).
=> fix: remove concurrency indicator from cron

lib/dal/src/component.rs, lib/dal/tests/integration_test/component/upgrade.rs
While attempting to (re)connect the children of a frame to the newly upgraded version, we try to find the `OutputSocket` `AttributeValue`s from the old version, but this has already been removed. Rather than creating specialized (re)connect logic for the schema version upgrade scenario, we can have the existing logic treat it as a brand new parent/child relationship by orphaning the children before we remove the old version of the parent frame.
=> Orphan all children before removing old frame version on schema version upgrade

Cargo.lock, component/deploy/userdata, lib/si-layer-cache/BUCK, lib/si-layer-cache/Cargo.toml, lib/si-layer-cache/src/disk_cache.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/src/memory_cache.rs, lib/si-layer-cache/src/pg.rs
Remove the span collection for layer cache hits, it spams way too hard to be useful. Add individual metric calls for layer cache hits in different places.
I suspect that the memory hits will be too much here, too, but we can pull them out if that's the case.
=> feat: add metrics to layer cache hits

component/lambda/functions/billing-set-prices.py, component/lambda/functions/github_lambda_loader.py, component/lambda/functions/si_lago_api.py, component/lambda/functions/si_redshift.py, component/lambda/functions/upload-billing-hours.py
This makes it so that we can deploy a new version of a lambda by updating `main`. To use it, you replace your lambda with the contents of `github_lambda_loader.py`, and it will:
1. Pulls the `si_*.py` modules from [`components/lambda/functions` on main](https://github.com/systeminit/si/tree/main/component/lambda/functions)
2. Pulls `<lambda function name>.py` from the same place (e.g. `upload-billing-hours.py`). This means different lambdas will automatically pick up the right script.
3. Imports `lambda_handler` from `<lambda function name>.py` (AWS will run this function).
We're already doing this for the `workspace_delegations_population` lambda, with a miniature version of this; this just lets us write modules.
=> Update lambdas whenever `main` updates

Cargo.lock, Cargo.toml, lib/shuttle/BUCK, lib/shuttle/Cargo.toml, lib/shuttle/src/app_state.rs, lib/shuttle/src/handlers.rs, lib/shuttle/src/lib.rs, lib/shuttle/src/middleware.rs, lib/shuttle/tests/integration.rs
This PR provides "shuttle", a new crate and service that "shuttles" or "forwards" messages from a limits-based NATS JetStream stream to a given NATS subject.
This is needed for the pending events architecture and audit logging work in order for the rebaser to drain pending events and publish them to appropriate subjects.
Relevant PRs: #4814, #4852, #4854
=> Add shuttle crate

app/web/src/components/AuditLogCell.vue, app/web/src/components/AuditLogDrawer.vue, app/web/src/components/AuditLogHeader.vue, app/web/src/components/Workspace/WorkspaceAuditLog.vue, app/web/src/components/layout/navbar/NavbarButton.vue, app/web/src/components/layout/navbar/NavbarPanelCenter.vue, app/web/src/components/layout/navbar/NavbarPanelRight.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, bin/auth-api/README.md, lib/vue-lib/src/design-system/general/Timestamp.vue
- Each event row can now be expanded to see the raw JSON data for each event
- A button appears on the header area to collapse all rows when any rows are open
- Each timestamp cell now has a tooltip to display the raw timestamp data
- Each change set cell now has a tooltip to display the change set id
- Also fixed some typos in the auth-api README
- Posthog tracking each time a set of logs are loaded (including when the user first navigates to the Audit page)
=> audit logs JSON display and other improvements

lib/sdf-server/src/service/v2/func/list_funcs.rs
<div><img src="https://media4.giphy.com/media/550h6RQfuOuhtaDwdl/giphy.gif?cid=5a38a5a2bq78c8lrrr1byi8digrf33eohupqnkcn16ht8wtm&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/billions/">Billions</a> on <a href="https://giphy.com/gifs/billions-season-4-episode-1-showtime-550h6RQfuOuhtaDwdl">GIPHY</a></div>
=> Don't filter out bindings for schema variants that have components on the canvas

Cargo.lock, Cargo.toml, app/web/src/components/Ai/GenerateAwsAssetSchemaPanel.vue, app/web/src/components/AssetEditorHeader.vue, app/web/src/store/asset.store.ts, app/web/src/store/feature_flags.store.ts, bin/sdf/src/args.rs, component/init/configs/service.toml, lib/asset-sprayer/BUCK, lib/asset-sprayer/Cargo.toml, lib/asset-sprayer/prompts/aws/asset_schema.yaml, lib/asset-sprayer/src/config.rs, lib/asset-sprayer/src/lib.rs, lib/asset-sprayer/src/prompts.rs, lib/dal/src/schema/variant.rs, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/app.rs, lib/sdf-server/src/app_state.rs, lib/sdf-server/src/config.rs, lib/sdf-server/src/extract.rs, lib/sdf-server/src/server.rs, lib/sdf-server/src/service/v2/variant.rs, lib/sdf-server/src/service/v2/variant/generate_aws_asset_schema.rs, lib/si-test-macros/src/sdf_test.rs, lib/vue-lib/src/design-system/icons/icon_set.ts, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This adds a button to the asset schema code editor that lets you generate your asset schema function with AI.
https://github.com/user-attachments/assets/9cfd344e-2188-45e5-9855-cededb8ed23e
* Generation is imperfect, but passable. This turn is about hooking it up end to end so we can iterate more rapidly.
* AI generation is in the new `asset_sprayer` crate, which `sdf` calls out to to generate the code. `dal` does not depend on this.
* Locked behind the `ai-generator` feature flag, which is restricted to SI internal only
* Use `SI_OPENAI_API_KEY` when launching `buck2` to pass your API key
* Use `SI_ASSET_SPRAYER_PROMPTS_DIR=<path to your si dir>/lib/asset-sprayer/prompts` when launching `buck2` to have it load prompts from disk for faster prompt dev cycle
* Deployable using SI config …
=> AI Asset Generator

app/web/src/api/sdf/dal/workspace.ts, app/web/src/store/change_sets.store.ts, lib/dal-test/src/helpers/change_set.rs, lib/dal/src/change_set.rs, lib/dal/src/change_set/event.rs, lib/dal/src/change_set/status.rs, lib/dal/src/change_set/view.rs, lib/dal/src/func/binding/action.rs, lib/dal/src/migrations/U3002__change_set_approvers.sql, lib/dal/src/workspace.rs, lib/dal/src/ws_event.rs, lib/dal/tests/integration_test/change_set.rs, lib/rebaser-server/src/rebase.rs, lib/sdf-server/src/service/v2.rs, lib/sdf-server/src/service/v2/change_set.rs, lib/sdf-server/src/service/v2/change_set/approve.rs, lib/sdf-server/src/service/v2/change_set/cancel_approval_request.rs, lib/sdf-server/src/service/v2/change_set/force_apply.rs, lib/sdf-server/src/service/v2/change_set/list.rs, lib/sdf-server/src/service/v2/change_set/reject.rs, lib/sdf-server/src/service/v2/change_set/reopen.rs, lib/sdf-server/src/service/v2/change_set/request_approval.rs, lib/si-events-rs/src/change_set_status.rs, lib/si-frontend-types-rs/src/change_set.rs, lib/si-frontend-types-rs/src/lib.rs, lib/si-frontend-types-rs/src/workspace.rs
- Adds new structs for Frontend Types
- Adds endpoint for each action taken on a change set (Request approval, approve, reject, cancel request, reopen, apply, force apply)
- Adds new endpoints to `change_sets.store` (nothing is calling them, but was helping me click test)
- Adds new integration test for the overall flow
<div><img src="https://media4.giphy.com/media/gremU0LQdTvpna46kv/giphy.gif?cid=5a38a5a2yrjd9ia1yelijru9j51nh0xj7l65pgpd50ct8h2d&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/Amsterdenim/">Amsterdenim</a> on <a href="https://giphy.com/gifs/Amsterdenim-approved-stamp-stamped-gremU0LQdTvpna46kv">GIPHY</a></div>
=> Adds V2 routes for change set approval and apply

bin/si-api-test/test_helpers.ts, bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts
Add the test identifier to the changeset created in the API tests so we can see if it's causing runaway issues/identify one's that lurk.
<div><img src="https://media2.giphy.com/media/QjZXUBUr89CkiWLPjL/200.gif?cid=5a38a5a2iwwcgwlc2e8a7oqfjzrelyb4hcpumbfxd9a16ia4&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/></div>
=> feat: add test name to temp changesets to identify lurkers

Cargo.lock, component/init/configs/service.toml, lib/asset-sprayer/BUCK, lib/asset-sprayer/Cargo.toml, lib/asset-sprayer/src/config.rs, lib/asset-sprayer/src/lib.rs, lib/si-settings/BUCK
We don't use these in any production environment, and this will get us where we can deploy.
=> Remove optional parameters from service.toml

bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts, bin/si-api-test/tests/5-emulate_paul_stack.ts
We are sometimes seeing flakey behaviour in the first race between the 20s allotted time and the backend services being able to execute the DVU in time.
This gives (particularly tools) a little more time to get through what it needs to do before hard failing the test.
There should be no real impact of this change, rather than reducing unnecessary red flags in our internal alerting. 
I.e. The majority of the time this is flagged to us, the stack is actually fine, it's just not quite ready yet.
=> fix: increase timeout waiting for DVU in api tests

NOTICE, flake.nix
This PR bumps the end date in the "NOTICE" file from "2023" to "2024". It also removes an unused flake input override since "rust-overlay" no longer uses "flake-utils".
=> Bump notice year and remove unused flake override

CONTRIBUTORS.md, DOCS.md, README.md, dev/healthcheck.py
I ran into `inotify` errors when trying to bring up the dev stack, in both the `web` service and the `docs` service. 
```
Error: ENOSPC: System limit for number of file watchers reached
```
This PR adds a new check to the healthcheck command and doc updates that explain it in more detail.
=> [healthcheck] added inotify check for Linux and docs around it

lib/si-layer-cache/src/db.rs, lib/si-layer-cache/src/hybrid_cache.rs
Issue with casting types around between `f32` `u64` and `usize` caused incorrect cache size calculations. Here we use `usize` and integer math to do our work. `usize` should be `u64` on any machine we run on, which is more than large enough for what we need (until we start deploying on machines with ~~more than 600 TB of disk~~ disks the size of the universe).
=> fix: cache size calculation fixes

app/web/src/components/AuditLogCell.vue, app/web/src/components/AuditLogHeader.vue, app/web/src/components/Workspace/WorkspaceAuditLog.vue, app/web/src/store/logs.store.ts, lib/dal/src/audit_logging.rs, lib/dal/src/context.rs, lib/dal/tests/integration_test/audit_logging.rs, lib/sdf-server/src/service/component/update_property_editor_value.rs, lib/sdf-server/src/service/diagram/create_component.rs, lib/sdf-server/src/service/diagram/delete_component.rs, lib/si-events-rs/src/audit_log.rs, lib/si-events-rs/src/audit_log/v2.rs, lib/si-events-rs/src/audit_log/v3.rs, lib/si-frontend-types-rs/src/audit_log.rs
This PR solidifies the audit log structure in the UI. In order to do this, there is now an `AuditLogV3`.
> [!NOTE]
> Backwards compatibility only matters for the "beta" streams and we can reset the counter once
we switch over to the production streams.
Now, we have a display name for the event, an entity type for the event and an entity name for the event.
This PR re-orders the columns and headers as well as adds selected and hover background coloration to the rows. It does not contain fixes for the filters nor are the selected and hover colors final. In those verticals, this PR is just another step towards where we want to be.
=> Solidify audit log structure in the UI

app/web/src/api/sdf/dal/func.ts, app/web/src/components/FuncEditor/FuncDetails.vue, app/web/src/components/FuncEditor/LeafInputs.vue, app/web/src/components/FuncEditor/ManagementDetails.vue, app/web/src/store/asset.store.ts, lib/dal/src/func/binding.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/prototype.rs, lib/dal/src/prop.rs, lib/dal/tests/integration_test/func/authoring/binding.rs, lib/sdf-server/src/service/v2/func/binding/update_binding.rs, lib/si-frontend-types-rs/src/func.rs
Adds managed schemas to the management bindings, and allows you to edit them from the function editor. This makes it possible to author management functions that create, update, and connect other asset/variant types than the managing component's type.
=> feat: modify schemas managed by management prototype

app/web/src/api/sdf/dal/change_set.ts, app/web/src/api/sdf/dal/workspace.ts, app/web/src/components/AbandonChangeSetModal.vue, app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/ApprovalFlowModal.vue, app/web/src/components/ApprovalFlowModal2.vue, app/web/src/components/ApprovalPendingModal.vue, app/web/src/components/ApprovalPendingModalCard.vue, app/web/src/components/InsetApprovalModal.vue, app/web/src/components/NoSelectionDetailsPanel.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/components/toasts/ChangeSetStatusChanged.vue, app/web/src/store/change_sets.store.ts, app/web/src/store/realtime/realtime_events.ts, lib/dal/src/change_set.rs, lib/dal/src/change_set/event.rs, lib/permissions/src/lib.rs, lib/sdf-server/src/service/v2.rs, lib/sdf-server/src/service/v2/change_set.rs, lib/sdf-server/src/service/v2/change_set/approve.rs, lib/sdf-server/src/service/v2/change_set/cancel_approval_request.rs, lib/sdf-server/src/service/v2/change_set/list.rs, lib/sdf-server/src/service/v2/change_set/reject.rs, lib/sdf-server/src/service/v2/change_set/reopen.rs, lib/sdf-server/src/service/v2/change_set/request_approval.rs, lib/si-data-spicedb/src/lib.rs, lib/si-data-spicedb/src/types.rs, lib/si-data-spicedb/tests/integration_test/mod.rs, lib/si-frontend-types-rs/src/change_set.rs
This PR includes the following changes: 
- When the `REBAC` feature flag is enabled, users will no longer see the consensus voting approval and will instead use the new approval flow that leverages SpiceDB for authorization
- Note: it is not recommended to have multiple users in the workspace with varying states of toggle
- Uses the `list_subjects` function of SpiceDB to find all users that have the permission to Approve a change set being applied (and extends an integration test for this) 
- Note: this should be refactored to follow a more ergonomic interface, but that will happen as a follow up.
- If a user is an approval, they'll be able to `Approve and Apply` a change set
- If a user is not an approver, they will be able to request approval and withdraw their request
- Non-approvers …
=> Use SpiceDB to facilitate Change Set Approvals end to end

Cargo.lock, Cargo.toml, lib/si-data-spicedb/Cargo.toml, lib/si-data-spicedb/examples/read-schema/BUCK, lib/si-data-spicedb/examples/read-schema/main.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This change adds URL-detecting TLS support when connecting to SpiceDB endpoints starting with `https://`. Prior to this change the SpiceDB client would attempt a connection and then be disconnected when TLS negotiation failed. Later API calls would fail with a "transport error" message.
References: lunaetco/spicedb-client#3
=> chore(si-data-spicedb): support TLS-enabled SpiceDB endpoints

lib/sdf-server/src/routes.rs, lib/sdf-server/src/service/session.rs, lib/sdf-server/src/service/session/refresh_workspace_members.rs
This API endpoint is used more as a Webhook than it is with managing information
The AuthPortal talks to this endpoint and tells the endpoint to assemble the correct data for the wroksapce. It doesn't push that data to SDF. so if a user who doesn't have access to manage my workspace hits the endpoint, they cannot manipulate the workspace. This means we can work without this check at this time.
=> fix(sdf): Remove ManagePermissionLayer on refresh_workspace_members

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
Currently, you can take a frame and drag it over another frame, which hides it. (This was always possible before too). But now when you move the frame "on top" of it, the "lower/hidden" frame comes for the ride, because its "inside" the other one... So I at least put a fix to bring it to the top when its selected so you can move it.
There is one more potential step to take, ordering frames based on their bounding box (e.g. smaller frames on top)
=> Fix frames ordering and parentage

app/web/src/components/ChangesPanelHistory.vue, app/web/src/components/Management/ManagementHistoryCard.vue, app/web/src/components/Management/ManagementHistoryList.vue, app/web/src/components/ManagementRunPrototype.vue, app/web/src/store/func_runs.store.ts, app/web/src/store/management_runs.store.ts
Some reactivity issues and a bug when fetching history were a consequence of using the FuncRuns pinia store, which is not namespaced to the change set. This moves the management functionality over to its own, change set specific store, which resolves these issues.
Fixes BUG-664
=> fix: use change set sharded store for management runs

bin/lang-js/src/function_kinds/management.ts, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/component.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/tests/integration_test/management.rs, lib/sdf-server/src/service/v2/management.rs
Adds an optional `parent` property to creates and updates returned by management functions that sets the frame parent. Also allows you to change a component into a frame by setting the `root/si/type` property of a component.
Component geometries returned and set via management functions are now all relative to the "manager" component, which gets x and y of 0.0. To place a component to the left or above the manager, use negative geometry. To the right or below, positive geometry. This allows reliably placing components inside the parent frame in any view.
=> feat: mgmt fns can set component type, and set parent for components

app/web/src/api/sdf/dal/audit_log.ts, lib/sdf-server/src/service/change_set/abandon_change_set.rs, lib/sdf-server/src/service/v2/change_set/apply.rs, lib/sdf-server/src/service/v2/change_set/approve.rs, lib/sdf-server/src/service/v2/change_set/cancel_approval_request.rs, lib/sdf-server/src/service/v2/change_set/force_apply.rs, lib/sdf-server/src/service/v2/change_set/reject.rs, lib/sdf-server/src/service/v2/change_set/reopen.rs, lib/sdf-server/src/service/v2/change_set/request_approval.rs, lib/si-events-rs/src/audit_log/v1.rs, lib/si-frontend-types-rs/src/audit_log.rs
Reused the existing Apply and Abandon Change Set events, and added new audit events for Rejection, Approval, Reopening, and Withdrawing a request, 
<div><img src="https://media0.giphy.com/media/OmTkBPi4v6nSL4SJHK/200.gif?cid=5a38a5a2k7756tsxlrkiwt3va3fj39v58tf6tnxbwaqns06i&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/travisband/">Travis</a> on <a href="https://giphy.com/gifs/travisband-writing-travis-dougie-payne-OmTkBPi4v6nSL4SJHK">GIPHY</a></div>
=> Add audit events as Change Set status gets updated

dev/Tiltfile
While otelcol is used for telemetry, it is also a core service that the applications expect to be available. When otelcol is not started, we get a _large_ amount of error output from `sdf`, `veritech`, etc., as well as from the integration tests when only `buck2 run dev:platform` has been run with no other intervention.
=> Move otelcol back to platform group in Tiltfile

lib/dal/src/attribute/value.rs, lib/dal/src/management/mod.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph/tests/detect_updates.rs, lib/dal/src/workspace_snapshot/graph/v4.rs, lib/dal/tests/integration_test/management.rs
In order for frames to manage children, we had to allow parallel edges
in our graph. There should be no problem here, nothing we do should
break on parallel edges.
Also, we need to ensure we send the connection WsEvents *after*
component WsEvents so that the frontend knows about all components
before getting connection messages.
=> fix: frames can manage children,  connection events sent after component events in management operator

lib/dal/src/audit_logging.rs, lib/dal/src/ws_event.rs
This PR ensures that we get the change set when preparing audit log publish events. We do not want to rely on the reference as it will only be stored when updating the visibility.
=> Get the change set for audit log published events

app/web/src/components/FuncEditor/FuncEditor.vue, app/web/src/store/func/funcs.store.ts
Right now, you often (not always?) have to reload the code editor after AI generation of an action function. This makes it so that the code editor reloads when the code changes (not just the FuncId).
Performance implications are unknown, but this doesn't happen on every keystroke, so it shouldn't be a huge burden.
=> Make code reload after AI gen

lib/dal/src/schema/variant.rs, lib/sdf-server/src/service/variant.rs, lib/sdf-server/src/service/variant/regenerate_variant.rs
Right now, Regenerate Asset causes socket bindings to disappear, and prop bindings to stop showing their values. A reload fixes it.
This is because `SchemaVariantRegenerated` adds bindings for all props but does not send a WsEvent notifying the frontend. `SchemaVariantUpdated` has this problem for new props and sockets, as well.
Fixes BUG-653.
=> Fix Regenerate Asset making bindings disappear

lib/dal/src/schema/variant.rs, lib/sdf-server/src/service/variant.rs, lib/sdf-server/src/service/variant/regenerate_variant.rs
Reverts systeminit/si#4982
In tools-prod, Regenerate Asset now emits this error:
This was happening locally too, and the source was that you can't generate `FuncUpdated` events because there are dangling bindings and props from the unlocked variant that got removed. The `cleanup()` line in `cleanup_unlocked_variant()` fixed it, but doesn't seem to affect tools. Reverting so it doesn't go to prod, and will investigate.
=> Revert "Fix Regenerate Asset making bindings disappear"

Cargo.lock, lib/audit-logs/BUCK, lib/audit-logs/Cargo.toml, lib/audit-logs/src/lib.rs, lib/audit-logs/src/migrations/U0002__audit_logs.sql, lib/audit-logs/src/pg.rs
This PR contains the migration for the audit logs table. It contains a mirrored Rust struct with an insertion method. None of the Rust code replaces what exists in `si-frontend-types` or `si-events` but may do so in the future.
```
2024-11-19T17:56:36.083814Z  INFO ThreadId(02) sdf.init.from_config:sdf.init.from_services: sdf_server::server: http service bound to tcp socket socket=0.0.0.0:5156
2024-11-19T17:56:36.131223Z  INFO ThreadId(02) sdf.migrator.run_migrations:sdf.migrator.migrate_audit_database:audit.init.migrate:audit.init.migrate.inner: refinery_core::traits: schema history table is empty, going to apply all migrations    
2024-11-19T17:56:36.131246Z  INFO ThreadId(02) sdf.migrator.run_migrations:sdf.migrator.migrate_audit_database:audit.init.migrate:audit.init.migrate.inner: …
```
=> Write migration for audit logs table

app/web/src/api/sdf/dal/component.ts, app/web/src/components/EdgeCard.vue, app/web/src/components/ModelingDiagram/DiagramEdge.vue, app/web/src/components/ModelingDiagram/DiagramNodeSocket.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_types.ts, app/web/src/store/components.store.ts, app/web/src/store/feature_flags.store.ts, app/web/src/store/realtime/realtime_events.ts, app/web/src/store/views.store.ts, lib/dal/src/attribute/value.rs, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/src/schema/variant.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/ws_event.rs, lib/dal/tests/integration_test/management.rs, lib/sdf-server/src/service/component.rs, lib/sdf-server/src/service/component/manage.rs, lib/sdf-server/src/service/component/unmanage.rs, lib/sdf-server/src/service/diagram/create_connection.rs, lib/sdf-server/src/service/diagram/delete_component.rs, lib/sdf-server/src/service/diagram/delete_connection.rs, lib/sdf-server/src/service/diagram/paste_component.rs, lib/sdf-server/src/service/v2/view/paste_component.rs, lib/si-frontend-types-rs/src/component.rs
Management edges now render on the diagram, and can be drawn from one component to another, if that component is capable of managing the other. They can also be deleted.
=> feat: management edges

lib/dal/src/audit_logging.rs, lib/dal/src/ws_event.rs
This PR ensures that we skip publishing ws events when audit logs are published for ephemeral change sets.
=> Write to audit logs table from forklift

lib/dal/examples/rebase/main.rs, lib/dal/src/workspace.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/src/workspace_snapshot/graph.rs, lib/dal/src/workspace_snapshot/graph/v2.rs, lib/dal/src/workspace_snapshot/graph/v3.rs, lib/dal/src/workspace_snapshot/graph/v4.rs, lib/dal/tests/integration_test/deserialize/mod.rs, lib/si-layer-cache/src/activities.rs, lib/si-layer-cache/src/db/cas.rs, lib/si-layer-cache/src/db/encrypted_secret.rs, lib/si-layer-cache/src/db/func_run.rs, lib/si-layer-cache/src/db/func_run_log.rs, lib/si-layer-cache/src/db/rebase_batch.rs, lib/si-layer-cache/src/db/serialize.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/src/event.rs, lib/si-layer-cache/src/hybrid_cache.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
This change addresses an issue when inserting a Rust type into a Foyer cache, where the memory used by that rust variable was not being accurately calculated. Prior to this change, the `size_of_val()` would dereference one level of "smart pointers" (i.e. deref an `Arc`, or `Vec`, or `String`), but no more levels. This led to an undercount of memory for that Rust value. For example, perhaps a workspace snapshot that was 30mb in size would be incorrectly calculated as 5mb.
As determining the size of an arbitrary Rust object is surprisingly difficult, we opted to use the *uncompressed* size of serialized Postcard bytes as our "size hint" (note that Postcard adds very little extra information into the stream of bytes, so could be considered as a very close approximation) and to provide this …
=> fix(layer-cache): add size hinting when inserting Rust types into caches

lib/si-layer-cache/src/hybrid_cache.rs
Using the percentages and reservation configurations, the minimum values wreck this percentage math.
=> chore(layer-cache): remove minimum memory values

component/deploy/docker-compose.yaml
This PR adds `pgbouncer` to forklift in tools. We did the math for tools with the configurable pool size and how many instances/replicas are running. We should be fine... in theory!
=> Add pgbouncer to forklift in tools

app/web/src/components/ModelingDiagram/DiagramControls.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, lib/vue-lib/src/design-system/panels/ResizablePanel.vue
I'm not entirely happy with the animation flash underneath, but this solves the worst of the problem
=> Bug-676: add/remove the padding for the diagram based on left drawer collapsed state

lib/module-index-server/src/server.rs
Handle IO errors when loading from profile in module index.
=> fix: incorrectly handle io error with fail to load credential profile

lib/dal/src/func.rs, lib/dal/src/func/resource_payload_to_value.rs, lib/dal/src/schema/variant/authoring.rs
This ensure that `si:resourcePayloadToValue` is always added to new variants. This is a stub approach in favor of the more complicated effort of making this an Intrinsic function. That work as been started [here](https://github.com/systeminit/si/tree/resource_to_payload). 
Intrinsics are not installed in existing workspaces, so there are edges around managing the existing javascript function and the new intrinsic. That work is better pushed off until after the upcoming holiday.
=> feat: add resourcePayloadToValue by default to all variants

app/web/src/components/ManagementRunPrototype.vue, app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/store/func/funcs.store.ts, bin/lang-js/src/component.ts, bin/lang-js/src/function_kinds/management.ts, lib/cyclone-client/src/client.rs, lib/cyclone-core/src/management.rs, lib/dal-test/src/expected.rs, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/diagram/geometry.rs, lib/dal/src/func/backend/management.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/src/schema/variant/root_prop/component_type.rs, lib/dal/tests/integration_test/management.rs, lib/dal/tests/integration_test/secret.rs, lib/sdf-server/src/service/diagram/create_component.rs, lib/sdf-server/src/service/diagram/set_component_position.rs, lib/sdf-server/src/service/v2/management.rs, lib/sdf-server/src/service/v2/view/create_component.rs, lib/sdf-server/src/service/v2/view/set_component_geometry.rs, lib/veritech-client/tests/integration.rs
Management funcs are now run in the context of a view. They can only create components in that view. But they can manage components in other views. The position of created components is relative to the manager component, but the position specified in updates is absolute.
If a manager component is in more than one view, a the "play" button will open a dropdown allowing you to select the view to run the function in.
This also makes position (x,y) optional, allowing you to update just the size of a component.
=> feat: management functions understand views

lib/sdf-server/src/service/v2/variant.rs, lib/sdf-server/src/service/v2/variant/list_variants.rs
Checks the uninstalled asset list against the modules in the graph, so that we don't show assets that are actually already installed when on demand assets is enabled.
Will not eliminate all the duplicates that show on old workspaces, but will hide all the ones that cannot be used.
=> fix: ensure already installed assets not treated as uninstalled

app/web/src/store/asset.store.ts, app/web/src/store/views.store.ts
WsEvent reaction did not account for uninstalled variant list. This ensures the first install of an asset does not list the asset twice.
=> fix: eliminate temporary duplicate after install on demand

app/web/src/components/modules/ModuleDisplay.vue, app/web/src/components/modules/ModuleListPanel.vue, app/web/src/store/module.store.ts
When on an on-demand installation workspace, we lost the ability to promote / reject the builtins as we no longer had all of the modules installed anymore
We have replaced the modules list with the ability to see builtins - this is something we have feature flagged for SI cohort at this time
=> fix(web): Ensure we can always promote / reject builtins

.github/workflows/run-api-test.yml, bin/si-api-test/sdf_api_client.ts, bin/si-api-test/test_helpers.ts, bin/si-api-test/tests/5-emulate_paul_stack.ts, bin/si-api-test/tests/7-emulate_authoring.ts
The `doubler` is now enshrined in API tests! 
This test does the following: 
- create the doubler
- Add an attribute function (that doubles a prop)
- Add a qualification
- Create a component
- Set a prop
- See that it doubles as expected
- Add another prop to the schema variant
- Add another attribute function
- See that the component auto-upgrades, and the new attribute func runs!
A bit of pain here in feature flags and adding a new test, but we'll get it figured out! 
<div><img src="https://media3.giphy.com/media/q5KSpsbhXp3lw7HxXl/giphy.gif?cid=5a38a5a2c18phxsk0a0thn8t7z5hc2tfn35uv2nlmwijd1az&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/latenightseth/">Late Night with Seth Meyers</a> on <a …
=> Add an API test for basic authoring scenario

lib/forklift-server/src/server/app/audit_logs.rs
This change fixes an issue where Forklift attempts to process an audit log message from a NATS subject which may or may not contain a change set id segment. This fix was found when inspecting live data in a pre-production environment. Real world data to the rescue!
=> fix(forklift): properly handle optional change set id in NATS subject

app/web/src/components/LeftPanelDrawer.vue, app/web/src/store/views.store.ts
Also calculate socket info when components are moved to/copied to a view so edges render
<div><img src="https://media0.giphy.com/media/a5MFvAwc6GPf2/giphy.gif?cid=5a38a5a2wcxsy1ff3db3uj1yhymycmshs56luxtq6n0r8wtu&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/pusheen/">Pusheen</a> on <a href="https://giphy.com/gifs/cat-cartoon-move-a5MFvAwc6GPf2">GIPHY</a></div>
=> fix(web): wait for all components to be loaded into the components.store before hydrating each view's geometry mapping lazily

component/toolbox/awsi.sh
This change conditionally propagates the following local environment variables into the `systeminit/toolbox` container:
- `AWS_PROFILE`
- `AWS_REGION`
If either of these variables are not present they do not get added to the `docker run` command.
In order to confirm the behavior change, several other updates are included:
- Add `set -eu` resulting in the shell script aborting if an expected environment variable is not set. To preserve the error message when you aren't authenticated, the existing `AWS_*` credential variables are still passed in as empty if not set.
- Add a `DEBUG` and `TRACE` mode to the script which add `set -v` and `set- xv` respectively when running the shell script. This helps to understand the final `docker run` command that is about to be executed (among other …
=> feat(toolbox): use AWS_PROFILE/AWS_REGION if set when calling `awsi.sh`

lib/sdf-server/src/migrations.rs
This change removes the "attempt to migrate and log errors" behavior when migrating the `si_audit` database. With this change a migration is performed, identical to migrations for the `si` and `si_layer_cache` databases. When an error is encountered, it early-returns with the error.
=> chore(sdf): always migrate `si_audit` database

lib/audit-logs/src/database/config.rs, lib/forklift-server/src/server.rs, lib/forklift-server/src/server/app.rs, lib/forklift-server/src/server/app/audit_logs.rs
This change adds a tunable in forklift's configuration called `insert_concurrency_limit` to control how many concurrent inserts are running.
This can be set in a `forklift.toml` with:
```toml
[audit]
insert_concurrency_limit = 4
```
Or in an environment variable with:
```sh
SI_FORKLIFT__AUDIT__INSERT_CONCURRENCY_LIMIT=4
```
Longer term, each microservice that forklift runs should have its own tunable for its own concurrency as one broad brush stroke won't be sufficient in the various environments. Additionally the name for the idea of a concurrency limit has `insert_` in it because currently we render the exact same `config.toml` template in all environments and for all services. This is one way for the moment to be very clear as to what this tunes (as read from a more "global" context).
=> chore(forklift): add tuning for concurrent audit log database inserts

lib/asset-sprayer/src/lib.rs, lib/asset-sprayer/src/prompt.rs, lib/dal/src/lib.rs, lib/dal/src/migrations/U3402__prompt_overrides.sql, lib/dal/src/prompt_override.rs, lib/dal/src/ws_event.rs, lib/dal/tests/integration_test/mod.rs, lib/dal/tests/integration_test/prompt_overrides.rs, lib/sdf-server/src/service/v2/admin.rs, lib/sdf-server/src/service/v2/admin/prompts.rs, lib/sdf-server/src/service/v2/admin/prompts/prompt.rs
This allows prompts to updated (stored in SQL) on the server so that they can be iterated upon. UI forthcoming.
=> Add SDF endpoints to update AI gen prompts on the server

app/web/src/store/func/funcs.store.ts
SchemaVariantReplaced and SchemaVariantUpdated are fired when we click Regenerate Asset; we need to update function bindings when that happens so the asset editor will trigger.
This is a bit of an overkill hammer, but it gets the job done when the slightly more targeted https://github.com/systeminit/si/pull/4982 was causing issues. When performance becomes an issue, we may want to allow events to be sent when *bindings* are changed.
Fixes BUG-653 and BUG-660.
=> Fetch func list on SchemaVariantReplaced/Updated

app/web/src/components/AssetPalette.vue
This fixes a problem where a child dragged onto the canvas does not properly get parented.
=> Fix: de-select component when adding to the diagram

bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/6-get_head_changeset.ts
Adds a bit of missing client coverage for the change_set set of routes for the API tests. Renames one reference that was mis-mapped to the route name. Bit of a simple one with no real functional impact but it should be a step in the right direction. 
<div><img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGx2dWpjZmt1aWR0YzlyaXhpcjB1cTl4M2tsY2lzOTV6dW14YmdjaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/14mgxYFJHXGmoo/giphy.gif"/></div>
=> feat: add remainder of changset routes to API client

app/web/src/store/components.store.ts, app/web/src/store/views.store.ts, lib/sdf-server/src/service/component/set_type.rs
Issue 1:
The set type endpoint sent the `ComponentUpdated` event with the geometry for the default views, instead of no geometry, so set_type outside of default always failed. Leading to 
Issue 2:
The nodes would disappear on change type, since we store components and groups on separate arrays in both the components and views stores. On type changes we need to move the data to the correct array.
=> Fix: Change component type on views other than the default

lib/sdf-server/src/service/v2/variant/list_variants.rs
If an installed asset (of any kind) has a cat+name matching one in the on-demand uninstalled list, don't offer it as an on-demand installable asset. This ensures duplicates don't appear in legacy workspaces.
=> fix: hide uninstalled duplicate assets

Cargo.lock, Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
Required so we can upgrade our version of rustls for a vulnerability
=> chore(deps): Updating Rust Deps

app/web/src/components/Workspace/WorkspaceAuditLog.vue
Now, we will show the correct row when expanding rows in the audit logs UI.
=> Show current expanded row for audit dashboard

app/web/src/store/logs.store.ts
With this commit, the filter options should be sorted alphabetically, like they were in the past.
=> Fix filter option sorting for audit dashboard

bin/sdf/src/main.rs, lib/sdf-server/src/config.rs, lib/sdf-server/src/migrations.rs
Use the same technique for "development run" detection used to set up the signing keys to set a dev_mode flag on the SDF config. If this dev_mode flag is true, and we are running migrations, also update the local module cache. This ensures we have an asset list locally on SDF boot.
=> feat: migrate local module cache on sdf boot, in dev mode

app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/store/views.store.ts, lib/sdf-server/src/service/v2/view.rs, lib/sdf-server/src/service/v2/view/create_view_and_move.rs
=> ENG-2871: move components to a new view and replace with a hexagon

CONTRIBUTORS.md, Cargo.lock, Cargo.toml, lib/si-layer-cache/src/hybrid_cache.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
foyer v0.13.1 refines the metrics framework, you can use provisioned metrics exporters or customize your own metrics exporter.
=> feat: upgrade foyer to v0.13.1

bin/auth-api/src/services/users.service.ts
Auth0 doesn't support email verification for Enterprise users 🙄 , so we must map a separate SAML claim to the `email_verified` user attribute in Auth0, and coerce this to a boolean in the Auth API
See here: https://community.auth0.com/t/email-verification-for-enterprise-users/28230/3 
In the Auth0 side of configuring the SAML Connection, we'll map the user's email to `email_verified` but this broke the AuthAPI as now the value on the Auth0Profile is not a bool anymore.  This fixes that. 
Note: when it comes to self-service SAML integration set up, this is something we'll need to account for when setting up SAML Connections. 
<div><img src="https://media1.giphy.com/media/d3EdJTouFN890fMnGP/giphy.gif?cid=5a38a5a2rmea5mvqh2lrvjdmuyydgcbccpl0i0wco3iuk9k9&amp;ep=v1_gifs_search&amp;rid=giphy.gif …
=> Coerce email_verified to a boolean in the Auth API

app/web/src/components/AuditLogDrawer.vue, app/web/src/components/Workspace/WorkspaceAuditLog.vue
This PR ensures that changing filters does not affect the contents of the inner table used in the Audit Log dashboard. This does not fully fix the performance issues observed when using filters in the Audit Log dashboard, but does improve them.
Now, the data for the table is only changed when the total set of Audit Log entries loaded changes. This PR takes advantage of TanStack's built-in filtering features. However, this PR does not fully take advantage of every TanStack feature at our disposal. There is likely more room for improvement.
Additionally, there is a now a distinct message for scenarios where there are no audit logs in the workspace (e.g. brand new workspace).
=> Ensure filters do not affect audit table contents

.github/workflows/try.yml
I have no idea if this works, I think the only way to verify this is to change the default branch to this one, which seems fraught with peril. 
What this _should_ do is
1. on `/try`, comment that it's going to try
2. do the try
3. once the build is started, update the first comment with a link to it
=> chore: comment on the PR when a try is run

.github/workflows/try.yml
This should `/try` so it does what was intended in the other PR. Here's an example from below
=> fix: try comments have incorrect permissions

.github/workflows/try.yml
See [this example](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only) for usage
=> fix: incorrect reference for pr number in scope

bin/si-api-test/sdf_api_client.ts, bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts, bin/si-api-test/tests/2-create_and_delete_component.ts, bin/si-api-test/tests/4-create_two_components_connect_and_propagate.ts
Completed client coverage for diagram and added test coverage for deleting an edge into `4-create_two_components_connect_and_propagate`. Forgot how the alphabet worked in `changeset` routes, so fixed that too and renamed `deleteComponent` reference to `deleteComponents` to fit with the route. 
<div><img src="https://media1.giphy.com/media/26gYO4oCowW8bH0Ws/giphy.gif"/></div>
=> feat: deepen api client coverage for diagram

Cargo.lock, Cargo.toml, lib/si-layer-cache/src/hybrid_cache.rs, lib/telemetry-application-rs/src/lib.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml, third-party/rust/fixups/opentelemetry/fixups.toml
With the latest version of foyer we can export usage metrics to opentelemetry. This requires an opentelemetry update to `0.26.0`. I originally attempted to update to `0.27.0`, but we have some other dependencies on the older version that made it trickier than it was worth. The API also changes pretty drastically, so I think that undertaking would be better left to a dedicated effort. 
[I borrowed a graph ](https://github.com/foyer-rs/foyer/blob/main/etc/grafana/dashboards/foyer.json)from our friends over at the foyer repo. It'll need some minor changes to adapt it to our environment, but it works decently enough locally.
cc @MrCroxx Thanks for the related PR. These metrics should help us get to the bottom of our memory issues. I'll let you know what we turn up next week!
=> feat: add foyer metrics to our metrics pipeline

lib/asset-sprayer/prompts/aws/asset_schema.yaml, lib/asset-sprayer/prompts/aws/create_action.yaml
Fixes the schema prompt for AWS assets, to always include a region property and a corresponding socket.
=> bug: update asset schema and create action prompts

lib/module-index-server/src/config.rs
This will ensure module index boots without extra config
=> fix: ensure module index has a default algo for the jwt

.github/workflows/e2e-validation.yml, .github/workflows/run-api-test.yml, bin/si-api-test/main.ts
I'm not particularly happy with this indirect assertion system, but logically it ties together and should hold us in good stead moving forward to prevent unnecessary pages.
It works off the premise that the only reason we should page someone from CI is:
- If we have a valid failure test result
- It's the correct environment
Previously we had a bunch of other failure scenarios which would have also paged, such as:
- NPM outage
- Github orchestration issue/infrastructure issue on their side
- Cypress results not uploading correctly in CI
- Other networking issue/blip
- Other 3rd party dependency issue
Now for every time the system wants to assert whether to page someone, the CI runner MUST have a valid failure artifact or marker pulled from the CI workflow.
`ALL` failures, regardless of …
=> feat: don't page unless you're absolutely sure it's worth waking someone up for 

component/lambda/functions/billing-set-prices.py, component/lambda/functions/si_lago_api.py, component/lambda/functions/si_redshift.py, component/lambda/functions/workspace_delegations_population.py
Right now, under the race condition where workspaces have been created for a user but their subscriptions are still being created, the subscription import lambda will trigger an error and cause an alert. This treats that situation as a new user and creates their records.
We could have fixed this by ignoring users without subscriptions in SI entirely, but then these cases would never get their subscriptions imprted and couldn't be billed. This way, they get fixed when the subscriptions appear.
This also reduces the eyestrain of output, includes progress reporting for subscription updates (which take a long time), and adds statements to tell us how many records have been processed, so that we can key alerts off of that:
```
INFO:root:Insert missing workspaces complete: 0 workspaces …
```
=> Billing: don't alert when new users race with subscription import

.github/workflows/run-api-test.yml
Towers of bash are not always stable, but can always upset you
=> fix: typo in shell, my tower of bash failed me

lib/si-id/src/conversions.rs, lib/si-id/src/lib.rs, lib/si-id/src/macros.rs, lib/si-id/src/ulid.rs
This PR splits the core si-id macro into four macros and is a follow-up to #5093.
The macros are based on the existence of PostgreSQL conversion implementations and the "nil" ID. The macros using "nil" should not be used by any new IDs and exist for backwards compatibility.
- All macros have moved into their own module
- All conversions between IDs have been moved into their own module
- Our standard set of lints for new crates have been added to "si-id" (along with resolutions to failed lints)
The below list has been carried over and modified from from #5093:
- Migrate all IDs in "si-layer-cache" (currently not reliant on a macro)
- Migrate all IDs in "module-index-server" (currently not reliant on a macro)
- Clean-up ID call sites (e.g. reduce "pub use" statements, but we may not …
=> Split core si-id macro into multiple macros

app/web/src/components/WorkspaceIntegrationsModal.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, app/web/src/store/feature_flags.store.ts, app/web/src/store/workspaces.store.ts, lib/dal/src/lib.rs, lib/dal/src/migrations/U3410__workspace_integration.sql, lib/dal/src/workspace.rs, lib/dal/src/workspace_integrations.rs, lib/sdf-server/src/service/v2.rs, lib/sdf-server/src/service/v2/change_set.rs, lib/sdf-server/src/service/v2/change_set/apply.rs, lib/sdf-server/src/service/v2/change_set/approve.rs, lib/sdf-server/src/service/v2/change_set/cancel_approval_request.rs, lib/sdf-server/src/service/v2/change_set/reject.rs, lib/sdf-server/src/service/v2/change_set/request_approval.rs, lib/sdf-server/src/service/v2/integrations.rs, lib/sdf-server/src/service/v2/integrations/get_integrations.rs, lib/sdf-server/src/service/v2/integrations/update_integration.rs, lib/si-id/src/lib.rs
We currently only post to that webhook from the change set approval flow but we want to make this more of an opt-in to what you can / can't to
=> feat(sdf, dal): Adding the ability to set a webhook url for a workspace

lib/dal/src/component.rs, lib/dal/src/diagram/geometry.rs, lib/dal/src/diagram/view.rs
=> Fix: Restore geometries too

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/DiagramView.vue
=> Fix: prevent rendering 0x0 components, always force a minimum size

app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/web/src/App.vue, app/web/src/components/AssetCard.vue, app/web/src/components/AttributesPanel/TreeFormItem.vue, app/web/src/components/FuncEditor/FuncTestSelector.vue, app/web/src/components/FuncEditor/ManagementDetails.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/components/WorkspaceImportModal.vue, app/web/src/components/layout/navbar/ChangeSetPanel.vue, app/web/src/components/layout/navbar/Collaborators.vue, app/web/src/components/layout/navbar/Navbar.vue, app/web/src/components/layout/navbar/NavbarPanelCenter.vue, app/web/src/components/layout/navbar/NavbarPanelLeft.vue, app/web/src/components/layout/navbar/NavbarPanelRight.vue, app/web/src/components/layout/navbar/ProfileButton.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenu.vue, app/web/src/components/layout/navbar/WorkspaceSettingsMenuItems.vue, app/web/src/main.ts, app/web/src/store/presence.store.ts, lib/vue-lib/src/design-system/forms/VormInput.vue, lib/vue-lib/src/design-system/general/SiSearch.vue, lib/vue-lib/src/design-system/index.ts, lib/vue-lib/src/design-system/menus/DropdownMenu.vue, lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue, lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue, lib/vue-lib/src/design-system/modals/Modal.vue, lib/vue-lib/src/design-system/panels/ResizablePanel.vue
- Created `DropdownMenuButton` component for using `DropdownMenu` to replace `VormInput` dropdowns
- Workspaces and Change Sets dropdowns on the Navbar now use `DropdownMenuButton` and have search enabled when there are more than 20 Workspaces or Change Sets
- Replaced a few other instances of `VormInput` dropdowns with `DropdownMenuButton`
- Fixed minor style bug on `WorkspaceDetailsPage`
- Minimum browser window width of 650 pixels is now enforced cleanly on the application
- Navbar elegantly collapses down to the minimum width of 650 pixels instead of breaking on narrower widths
- Fixed bugs in the `Collaborators` component, added a function for testing it
- Fixed ModelingDiagram misalignment bug caused by `LeftPanelDrawer` changes
- Fixed `SiSearch` styles to look better inside of …
=> Searching workspaces and change sets, minimum app width, and more!

Cargo.lock, Cargo.toml, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This PR updates Rust dependencies that neither require code changes nor fixup changes. This is a follow-up to #5103.
=> Update Rust deps that do not require code changes

lib/sdf-server/src/service/session.rs, lib/sdf-server/src/service/session/auth_connect.rs
The original code was only creating the integrations table entry for new workspaces but we should also ensure that we do it for old workspaces as well
=> fix(sdf): Ensure that Workspace Integrations exist for old workspaces

lib/si-layer-cache/src/db.rs
This will shrink the size of the workspace snapshots cache. I want to see how the cache behaves in tools prod. We currently deploy often enough that we keep resetting the cache before it hits the limit. This size should be achievable in a few hours, but still large enough to contain the largest cache size we've observed in prod so far.
=> chore: temporarily shrink size of workspace snapshots cache

lib/sdf-server/src/service/diagram/delete_component.rs
Sends a WsEvent without geometry so views are not taken into account when deleting a component.
Fixes BUG-699
To test this: create two components in a view that is not the default view. One that will have a resource (successfully get created) and one that does not (sec group and docker image were my test). Apply to head, be sure that a resource is created for the resource one. Then in a new change set, attempt to delete them. Delete should succeed.
=> fix: delete components on head if they are not in default view

.github/workflows/run-api-test.yml
If all the retries for the e2e tests fail, it was setting the exit code to 1, which is not the exit code we want to report on/alert from.
If all the retries fail, we want to report the exit_code of the deno task, which if it is a valid failure is 53.
=> fix: retry case on api tests exiting with wrong exit code

lib/si-layer-cache/src/db.rs
Seems that now we have a smaller mem cache, that the layer cache startup has triped in duration, likely due to additional pressure on the disks now the cache is smaller.
Where the deployment happened at 3pm on the graphs
Reverting just to give us a bit more time to figure out what to do here to make it less likely that the train to prod will have issues tomorrow.
=> Revert "chore: temporarily shrink size of workspace snapshots cache"

component/init/configs/service.toml, lib/si-layer-cache/src/hybrid_cache.rs
I _think_ this controls how many threads foyer spins up to read in the disk cache. This is set to the foyer default of `8`. We should tune this in tools prod to see how it impacts our startup performance
=> feat: make foyer disk recover concurrency configurable

.github/workflows/deploy-service-restart.yml, .github/workflows/instance-refresh.yml, .github/workflows/service-restart.yml
Adds a new pipeline which we can trigger that will restart the service replicas that are impacted by our current run-away memory issue. It will basically quickly drop the replicas and bring them back. For SDF it pushes the FE into maintenance mode first to give a bit of better user experience, all the other services are gracefully stopped so they should finish up their current work before attempting to be started again.
In theory, it's much better to take just one node offline at a time, but it would require a fair bit more re-work in our toolbox to let us do it.
We can schedule this like a maintenance event (using the maintenance mode) and it should be very minimally impactful for the users.
This is untestable until I merge it, because the workflow doesn't exist in the UI/API until it's …
=> Add pipeline to restart SDF/Rebaser/Pinga units on relevant nodes

app/docs/src/explanation/aws-authentication.md, app/docs/src/how-tos/aws-ecr-ecs.md, app/docs/src/how-tos/aws-ecs.md, app/docs/src/how-tos/aws-eks.md, app/docs/src/how-tos/aws-ha-ec2.md, app/docs/src/how-tos/aws-iam.md, app/docs/src/how-tos/aws-lambda.md, app/docs/src/how-tos/aws-macos.md, app/docs/src/how-tos/aws-static-cloudfront.md, app/docs/src/how-tos/aws-vpc.md, app/docs/src/reference/vocabulary.md, app/docs/src/tutorials/actions-and-resources.md, app/docs/src/tutorials/creating-components.md, app/docs/src/tutorials/editing-components-and-contributing.md, app/docs/src/tutorials/getting-started.md, app/docs/src/tutorials/index.md, app/docs/src/tutorials/working-with-components.md
Amended our Vocabulary to include "View" as a concept/term.
Amended all references to any vocabulary reference to have a capital letter. yes. all of them.
<div><img src="https://media0.giphy.com/media/UoSWDKPpCNaRLmaBKm/200.gif?cid=5a38a5a2ge608vxsoevt3zj6h15reka1s1xs5h9e39buwmw4&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/></div>
=> nit: possibly the biggest vocabulary nitpick of all time

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/AssetFuncAttachModal.vue, app/web/src/components/ComponentCard.vue, app/web/src/components/EdgeCard.vue, app/web/src/components/FuncEditor/FuncList.vue, app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingView/DeleteSelectionModal.vue, app/web/src/components/ModelingView/EraseSelectionModal.vue, app/web/src/components/ModelingView/ModelingRightClickMenu.vue, app/web/src/components/ModelingView/TemplateSelectionModal.vue, app/web/src/components/MultiSelectDetailsPanel.vue, app/web/src/components/SecretsPanel.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/store/components.store.ts, app/web/src/store/feature_flags.store.ts, lib/vue-lib/package.json, lib/vue-lib/src/design-system/forms/ColorPicker.vue, lib/vue-lib/src/design-system/forms/VormInput.vue, lib/vue-lib/src/design-system/index.ts, lib/vue-lib/src/design-system/modals/Modal.vue, pnpm-lock.yaml
https://github.com/user-attachments/assets/0221f09b-1944-48ac-b331-1c73051c7939
also some `VormInput` fixes, a fix on the diagam, some new `ModelingDiagram` debug info, and a little refactoring
=> Template management func generation UI

pnpm-lock.yaml
This is stillcausing dependabot to complain about a version being out of date
=> chore(cleanup): Cleanup old nanoid dependency

app/web/src/components/ModelingView/TemplateSelectionModal.vue, app/web/src/store/components.store.ts, lib/dal/src/component.rs, lib/dal/src/management/generator.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/tests/integration_test/management.rs, lib/dal/tests/integration_test/management/generator.rs, lib/sdf-server/src/service/v2/management.rs, lib/sdf-server/src/service/v2/management/generate_template.rs
Takes a set of component ids, and a view, and generates a management function that will recreate the components on demand, with their (relative) position, connections, and parentage preserved. Then attaches that function to a brand new schema variant.
=> feat: generate templates from selected components

app/web/src/components/Workspace/WorkspaceCustomizeAssets.vue, app/web/src/store/func/funcs.store.ts
https://jam.dev/c/1acf7e4b-25c5-444e-8146-b06d379cccf5
Without this, it wasn't apparent that a prompt was actually generating
=> feat(web): Add a modal overlay when prompt is executing

app/web/src/App.vue, app/web/src/components/AttributesPanel/AttributesPanel.vue, app/web/src/components/ManagementRunPrototype.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingView/TemplateSelectionModal.vue, app/web/src/components/toasts/CreatingTemplate.vue, app/web/src/store/components.store.ts
=> toasts and other UI adjustments for template generation

lib/dal/src/schema.rs, lib/dal/src/workspace_snapshot/graph/v4.rs
On demand asset installation can produce identical Schema nodes by id, but they will have different lineage ids. Since the lineage ids are different, we will treat them as new nodes on the graph. The idempotency of our updates usually means this is fine. But the interaction with the code to ensure there is only one default edge caused an issue.
This fixes both, by ensuring new schemas are always created with the lineage id equal to the schema id. This will ensure we compare the nodes instead of treating the schema node as a new node.
It also ensures that if a new edge update comes in that sets a schema variant to the default, but that variant is already default, we preserve that default.
=> fix: schemas should be created with lineage_id == id 

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
This ensures we don't attempt to correct the size of a parent if there are not in fact new parents.
=> fix: allow moving components inside of their parents

lib/si-layer-cache/src/hybrid_cache.rs
This disables the disk cache portion of Foyer as we investigate issues with memory growing unbounded, leading to OOMs in production environments. Local testing indicates that the disk portion of the cache and the rate at which we flush to it may be causing us to greatly over allocate memory. More investigation needs to happen in this area, so this is mainly to stabilize prod.
=> chore: disable the foyer disk cache

lib/dal/src/workspace_snapshot/graph/v4/diagram/view.rs, lib/dal/src/workspace_snapshot/node_weight/view_node_weight/v1.rs, lib/dal/tests/integration_test/view.rs, lib/si-frontend-types-rs/src/component.rs
Because of the edge directionality, removing the `DiagramObject` for a `View` is insufficient to also remove all `Geometry` that represent that `DiagramObject`/`View`. To account for this, we now use the source of all `Represents` edges pointing at the `DiagramObject` to explicitly remove the `Geometry` that represent the `DiagramObject`/`View`.
Additionally, when we check to see if we would be orphaning anything by removing a `View`, if we encounter a `Geometry` that has no `Represents` edge, we ignore it and move on, as it's not representing anything to orphan.
=> Ensure all Geometry for a View are removed when removing a View

lib/si-layer-cache/src/db/rebase_batch.rs, lib/si-layer-cache/src/db/workspace_snapshot.rs, lib/si-layer-cache/src/hybrid_cache.rs, lib/si-layer-cache/src/layer_cache.rs, lib/si-layer-cache/tests/integration_test/db/cas.rs, lib/si-layer-cache/tests/integration_test/db/func_run.rs, lib/si-layer-cache/tests/integration_test/db/func_run_log.rs, lib/si-layer-cache/tests/integration_test/db/workspace_snapshot.rs, lib/si-layer-cache/tests/integration_test/layer_cache.rs
The original implementation of these calls went directly to the memory cache, knowing that we were waiting for something new and it couldn't be on the disk yet. When foyer was added, this changed to go directly to the cache, meaning that we are knowingly spawning a thread that reads from disk with every attempt here, every millisecond, for up to 2000 milliseconds. This creates a TON of disk pressure and additional allocations. I _think_ this might be part of the source of our memory pressure issues, but this really leads me to believe that there is a leak internal to foyer around how they load things from the disk (maybe specifically around misses?).
Another curious thing is that I don't seem to have any traces that point to the disk misses, of which there should be many thousand.
Not …
=> fix: retrieve from memory when waiting for snapshots

lib/dal/src/func/argument.rs, lib/dal/src/func/authoring.rs, lib/dal/src/func/binding.rs, lib/sdf-server/src/service/diagram/create_connection.rs, lib/sdf-server/src/service/diagram/delete_connection.rs, lib/sdf-server/src/service/v2/func.rs, lib/sdf-server/src/service/v2/func/argument/create_argument.rs, lib/sdf-server/src/service/v2/func/argument/delete_argument.rs, lib/sdf-server/src/service/v2/func/binding/attribute/reset_attribute_binding.rs, lib/sdf-server/src/service/v2/func/binding/create_binding.rs, lib/sdf-server/src/service/v2/func/binding/delete_binding.rs, lib/sdf-server/src/service/v2/func/create_func.rs, lib/sdf-server/src/service/v2/func/create_unlocked_copy.rs, lib/sdf-server/src/service/v2/func/delete_func.rs, lib/sdf-server/src/service/v2/func/execute_func.rs, lib/sdf-server/src/service/v2/func/test_execute.rs, lib/sdf-server/src/service/v2/func/update_func.rs, lib/sdf-server/src/service/v2/module/contribute.rs, lib/sdf-server/src/service/v2/variant/create_unlocked_copy.rs, lib/sdf-server/src/service/v2/variant/delete_unlocked_variant.rs, lib/sdf-server/src/service/v2/view/create_view.rs, lib/sdf-server/src/service/v2/view/remove_view.rs, lib/sdf-server/src/service/v2/view/set_component_parent.rs, lib/sdf-server/src/service/v2/view/update_view.rs, lib/sdf-server/src/service/variant/create_variant.rs, lib/sdf-server/src/service/variant/regenerate_variant.rs, lib/si-events-rs/src/audit_log/v1.rs, lib/si-events-rs/src/func_run.rs, lib/si-events-rs/src/lib.rs
This PR adds coverage to the following areas:
- Function Authoring (Test, Execute, Attach for each function kind, Detach, Delete, Create, Updating Metadata )
- Schema Variant Authoring (Create, Regenerate, Delete, Unlock,)
- Contributing a module
- Components (Creating/Deleting Connections, Attaching/Orphaning) 
- Views (Create, Update, Delete)
To do still include: 
- Handling code changes
- Handling View Diagram Objects
- Updating Schema Variant Metadata 
- Installing a Module
- More granular Func Binding updates (depending on how we want to approach this, for ex: updating the arguments for an attribute function)
<div><img src="https://media0.giphy.com/media/26nfp8HGGHLPGY2KQ/giphy.gif?cid=5a38a5a2dp3y22kf4gylzq6hwz7kk69gjc4z3dbryyzyqve4&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" …
=> Instrument more audit log events

app/web/src/components/ApplyChangeSetButton.vue, app/web/src/components/ApprovalFlowModal2.vue, app/web/src/components/ComponentDetails.vue, app/web/src/components/DetailsPanelTimestamps.vue, app/web/src/components/InsetApprovalModal.vue, app/web/src/pages/WorkspaceSinglePage.vue, app/web/src/store/views.store.ts
1. A race is happening with the router where the change set applied pushes to head
2. That push brings the head stores back
3. The head stores attempt to sync selected data back into the URL
4. But the route URL has not been set to "head"
5. So the head stores sync overwrite the push to head
6. And it pushes you to the changeset you were on previously
7. Which is merged, and causes tons of breakage
=> BUG-725: remove selections from head prior to applying.

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
=> Fix: dont make parents smaller, also fixed the bug why we thought new children didnt fit inside the parent

app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/store/views.store.ts
- View store doesnt FETCH_VIEW, which does a router push, on customize page.
- When we load the modeling workspace, find this state and call FETCH_VIEW
=> Fix: initial load on customize page, move to empty modeling page

app/web/src/store/components.store.ts, app/web/src/store/views.store.ts
After first paint, but before the data is required by other things! And don't do it twice!
Tested this against all the regressions we've been bashing away on (e.g. no blank modeling screen, no missing component on apply)
=> Fix: load all components at the right time

app/web/src/store/views.store.ts
=> Fix: missing new edges on apply

lib/dal/src/workspace_snapshot/node_weight/view_node_weight/v1.rs
If components are deleted, then the view deleted, the geometry for the component might be there in the graph still. It will be removed on view deletion. Be graceful here, and allow the view to be deleted in this case.
=> fix: view deletion if components are deleted

app/web/src/components/LeftPanelDrawer.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/pages/WorkspaceSinglePage.vue, app/web/src/store/views.store.ts
1. make a changeset
2. create a new view
3. be looking at your new view
4. hit apply
5. you get this error
We also had a subtler 404 bug in step 2 when creating a view that is fixed.
We also fixed:
- sockets did not draw connections correctly after a component was changed into a frame
- when selecting a frame that had "to be deleted" child frames in it the children were "behind" the selected frame, not on top
=> Fix: creating new View fixes, and two Scenario 1 fixes

lib/sdf-server/src/service/v2/management.rs, lib/sdf-server/src/service/v2/management/generate_template.rs, lib/si-events-rs/src/audit_log/v1.rs
Adds audit log and posthog track calls for template generation, and for the "operating" portion of management operations (functions could execute but not produce operations, so these are distinct events)
=> feat: add audit trail and posthog tracking for templates

.github/workflows/prod-service-restart-cron.yml, .github/workflows/prod-test-cron.yml
This changes things slightly so we only test during the times where we are NOT refreshing.
It should prevent the page when we know we are refreshing so things might be a little flakey. It should also prevent the clash to allow the refresh to work correctly.
p.s. I know this isn't the tidiest thing but it should tide us over and prevent pages/manual intervention
=> fixup: only test when not refreshing, otherwise it will cause grief

CONTRIBUTORS.md, DOCS.md
The wiki has recently moved to a new domain: https://discourse.nixos.org/t/wiki-nixos-org-is-now-live/42570.
=> docs: link to new NixOS wiki

.github/workflows/deploy-service-restart.yml
During the service restarts we are returning the task for the restart being completed a little too quickly with no active "healthchecker" after to actually verify that the services are able to take traffic. Then we start testing and they obviously fail as the services aren't available.
This adds a little time to give the services a longer grace period before being expected to take traffic.
=> A little patience never hurts

Cargo.lock, bin/lang-js/src/function_kinds/management.ts, lib/dal-test/Cargo.toml, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/BUCK, lib/dal/src/component.rs, lib/dal/src/diagram/geometry.rs, lib/dal/src/diagram/view.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/generator.rs, lib/dal/src/management/mod.rs, lib/dal/tests/integration_test/management.rs, lib/dal/tests/integration_test/management/generator.rs
The return type for management functions has been extended to support creating views, and creating new components in views other than the current view.
The "geometry" property on a create can now *either* be a plain geometry object, which will create the component in the current view, or it can be a map of view names to geometries, which will create the component in the specified view with that geometry.
Additionally, you can add to your ops return an object like so:
```
ops: {
views: {
create: ["view a", "view b", "view c"]
}
}
```
to create new views in a mangement function. The views will be available for create and update operations in the management func itself.
=> feat: mgmt fns can create views, create components in views

lib/sdf-server/src/extract.rs, lib/sdf-server/src/middleware/workspace_permission.rs, lib/sdf-server/src/routes.rs, lib/sdf-server/src/service.rs, lib/sdf-server/src/service/session/restore_authentication.rs, lib/sdf-server/src/service/whoami.rs, lib/sdf-server/src/service/ws/crdt.rs, lib/sdf-server/src/service/ws/workspace_updates.rs, lib/si-jwt-public-key/src/lib.rs
This adds a "whoami" endpoint that you can hit to check your token and email (who SI thinks you are). It mainly exists to validate that we can actually authorize automation tokens for an endpoint (since all other endpoints reject automation tokens).
This also factors the token and authorization extractors so they always use the same code. web/automation authorization still work via extractors, they just all run through a single funnel now.
`EndpointAuthorization` is the main authorization extractor you will use (or `AccessBuilder`, which uses it), which:
1. Extracts the access token from the `Authorization: ` header using the RawAccessToken extractor.
2. Validates the access token and checks expiration date using the ValidatedToken extractor.
3. Checks that the user is a member of the …
=> feat: Add sdf whoami endpoint accessible to user or automation tokens

app/auth-portal/src/components/AuthTokenListItem.vue, app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue, lib/vue-lib/src/design-system/forms/VormInput.vue, lib/vue-lib/src/design-system/general/ErrorMessage.vue
=> Feat: Make automation token UI conform to figma

bin/auth-api/src/services/auth.service.ts
This just ties up a loose end: we were minting old v1 tokens for web users to ensure backwards compatibility during the upgrade. That's been working for a few weeks, so now we can switch to new-style tokens.
Testing: We already have unit tests that we're handling the v2 tokens correctly, and I've run the entire stack locally once again to make sure the module index, web app and SDF all work correctly.
This will require a deploy of the auth api, but nothing else. Existing tokens will continue to work, as well (this doesn't deprecate them or anything).
=> Mint v2 tokens for regular users now that all callers can accept them

app/web/src/store/views.store.ts, lib/sdf-server/src/service/v2/view/get_diagram.rs
We are overwriting the view ID with the geometry ID in some cases.
This made it so that if you added a link to a view and then merged to head, you would get errors (@keeb was seeing them).
W/ @vbustamante and @jobelenus
=> Don't send geometry Ids to the frontend

bin/auth-api/README.md, dev/Tiltfile
This adds auth-api and auth-portal to Tilt in manual mode, so that you can host them as part of your local stack. They must be started manually, similar to module-index.
You still have to initialize the database and set the proper env variables; and it requires you to enable the services soon after starting tilt (since the database creation gets angry if there are other services connected to postgres). We'll take a look at these papercuts in the future.
=> chore: Add auth-api and auth-portal to Tilt

bin/auth-api/src/services/auth.service.ts
Reverts systeminit/si#5206
It looks like new sessions are using old tokens from the wrong workspaces in the web ui.
=> Revert "Mint v2 tokens for regular users now that all callers can accept them"

dev/Tiltfile
Right now auth-portal just sits in suspension, waiting for auth-api to come up; but that means if you don't plan to *run* auth-api, tilt shows "21/22" forever and it feels like you haven't got the whole system up!
This makes it so you have to manually bring up auth-portal after bringing up auth-api, so it doesn't show in stats :)
=> Make auth-portal something you have to manually bring up

lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/component.rs, lib/dal/src/component/delete.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/dal/tests/integration_test/component/delete.rs, lib/dal/tests/integration_test/management.rs, lib/sdf-server/src/service/diagram/delete_component.rs
Components managed by a management component can now be deleted in a management func. Two new properties have been added to the ops return value: `delete?: string[]` and `erase?: string[]`. Delete will mark components with resources as to_delete, while erase will delete components regardless of their resource status. Components to delete or erase can be specified either by their name, or their id (available on the components input array). id will be more reliable if there is more than one managed component with the same name.
=> feat: delete components from management functions

app/web/src/store/components.store.ts, app/web/src/store/views.store.ts
This fix is explicitly for components, since their size is calculated, and not stored 😄 
Also, see my note for something to come back to in the future:
```
note: if a person added a hundred sockets to a component
and that component was a frame, it would not resize itself
and the sockets would appear outside the frame
```
I tested it:
```
function main() {
const asset = new AssetBuilder();
[...Array(99).keys()].forEach((i) => {
const outputTest = new SocketDefinitionBuilder()
.setName("Test" + i)
.setArity("one")
.setConnectionAnnotation("Test<string>")
.build();
asset.addOutputSocket(outputTest);
})
return asset.build();
}
```
=> Fix: BUG-735 consolidate these two events into one place and add the geo assignment

lib/dal/src/change_set.rs
This audit log is emitted from the `dal` as otherwise every route handler we'd have to remember to do this
<div><img src="https://media1.giphy.com/media/5bbuRxeHd1NhlC86bN/200.gif?cid=5a38a5a2lqg4cjivpazjbr1rl1y5ohwuqkvj14qwnxjz96ss&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/newcastleuniversity/">Newcastle University</a> on <a href="https://giphy.com/gifs/newcastleuniversity-whatever-written-5bbuRxeHd1NhlC86bN">GIPHY</a></div>
=> fix(dal): Emit audit event when forcing a change set to be created

app/web/src/store/feature_flags.store.ts
Best Practice: preface with `workspace-`
Required: no collisions with other feature flag names!
Set them up in Posthog like this, where the distinct ID is the workspace ID
=> Feat: workspace level feature flags

app/web/src/components/Actions/ActionCard.vue, app/web/src/components/Actions/ActionsList.vue, app/web/src/components/FuncRunTabDropdown.vue
This got accidentally killed in `3ff15cf`
=> Fix: restore the ellipsis in the actions history, clean up history for no ellipsis

.github/workflows/deploy-stack.yml
Adds some grace time like we do on our service refresh to allow the services to come back before testing.
NB: I am not happy about this fix but it'll prevent the unnecessary noise
=> feat: add waiter to deploy pipeline for grace

lib/dal/src/component/frame.rs, lib/dal/src/management/mod.rs, lib/sdf-server/src/service/v2/view/create_component.rs
This ensures all edge events, including inferred edge upsert and removals, happen after all component events in management funcs
=> fix: send inferred edge events after component events in mgmt fns

lib/dal/src/diagram.rs
I tested both the bug repro steps:
1. move components from Default into another View
2. See that it works
3. go back to default view
4. Refresh the browser
5. see the old components as deleted
As well as a "regular" delete, still showing ghosted... And we are all set
=> Fix: to determine what components are removed, we need all components, not just components in the view

app/auth-portal/src/App.vue, app/auth-portal/src/components/AuthTokenList.vue, app/auth-portal/src/components/AuthTokenListItem.vue, app/auth-portal/src/components/MemberListItem.vue, app/auth-portal/src/main.ts, app/auth-portal/src/pages/SetupProductionUser.vue, app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue, app/auth-portal/src/pages/legal/PrintLegalPage.vue, app/auth-portal/src/store/authTokens.store.ts, app/web/src/components/ApprovalPendingModalCard.vue, app/web/src/components/AssetListItem.vue, app/web/src/components/AssetPalette.vue, app/web/src/components/DebugNavbar.vue, app/web/src/components/InstallAssetsPanel.vue, app/web/src/components/LeftPanelDrawer.vue, app/web/src/components/ProgressBar.vue, app/web/src/components/SecretCard.vue, app/web/src/components/layout/navbar/UserIcon.vue, app/web/src/main.ts, app/web/src/pages/HomePage.vue, bin/auth-api/src/routes/auth_token.routes.ts, bin/auth-api/src/services/auth_tokens.service.ts, lib/vue-lib/src/design-system/general/Timestamp.vue, lib/vue-lib/src/design-system/index.ts, lib/vue-lib/src/design-system/utils/floating_vue_utils.ts
=> feat(web) - UI for revoking auth tokens, active and inactive token lists

lib/sdf-server/src/extract/request.rs, lib/sdf-server/src/extract/services.rs, lib/sdf-server/src/extract/v1.rs, lib/sdf-server/src/extract/workspace.rs, lib/sdf-server/src/middleware/workspace_permission.rs, lib/sdf-server/src/routes.rs, lib/sdf-server/src/service.rs, lib/sdf-server/src/service/public.rs, lib/sdf-server/src/service/public/change_sets.rs, lib/sdf-server/src/service/public/workspaces.rs, lib/sdf-server/src/service/session/restore_authentication.rs, lib/sdf-server/src/service/v2.rs
This is a "create change set" endpoint for automation tokens (`POST /api/public/v0/workspaces/:workspace_id/change-set`). It takes `changeSetName` and is identical to the v2 create changeset api.
**Versioning**: This is designed to support a GitHub Action (which is the real public API we're shipping and supporting). The API endpoints themselves are not something we're exposing and documenting. (This is part of why `v0` is in the URL, to give a sense of semantic versioning independence.)
This largely copies the v2 create changeset API.
It also has a couple of extractor ergonomics improvements (used in the new endpoint) that we can fold back into v2 endpoints. (I did not do the folding right now, to limit blast radius and to make this more reviewable.) Specifically:
* `WorkspaceDalContext`: …
=> feat(sdf): Add automation API for "create changeset"

bin/auth-api/BUCK, bin/module-index/BUCK, prelude-si/macros/docker.bzl
This change changes the default machine architectures that are expected to have Docker images being built and published to Docker Hub for tag promotion (in the `si/merge-main` CI pipeline).
By default, it's expected that an ARM and an X86-64 image will be produced. In this change it's now possible to change that default assumption and to only specify the machine architectures expected to have been published. The underlying Python script and corresponding `docker_image_promote` rule already had this capability but the `docker_image` Buck2 macro wasn't able to handle this prior to this change.
This change works in concert with changes to `si-ci` which will filter out non-critical artifact builds in the `si/merge-queue` pipeline.
=> build: alter Docker image multi-arch promotion for certain images

lib/dal/src/change_set.rs, lib/dal/src/context.rs, lib/dal/src/workspace_snapshot/migrator.rs, lib/dal/tests/integration_test/change_set.rs
This change introduces `ChangeSet::find_across_workspaces` to differentiate from `ChangeSet::find` to ensure we're not acting on ChangeSets that don't belong to the Workspace in question. 
<div><img src="https://media1.giphy.com/media/iQ5xPFRDM2jnsjpWj2/giphy.gif?cid=5a38a5a2z3q3wiwryno9w1sep04jym423qah0eg2aoreef9a&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:228px;width:300px"/><br/>via <a href="https://giphy.com/fallontonight/">The Tonight Show Starring Jimmy Fallon</a> on <a href="https://giphy.com/gifs/fallontonight-weird-al-yankovic-i-dont-belong-here-iQ5xPFRDM2jnsjpWj2">GIPHY</a></div>
=> fix(dal,sdf): when finding change sets, ensure it belongs to the relevant workspace

lib/sdf-server/src/extract.rs, lib/sdf-server/src/extract/change_set.rs, lib/sdf-server/src/service/public.rs, lib/sdf-server/src/service/public/change_sets.rs, lib/sdf-server/src/service/public/components.rs, lib/sdf-server/src/service/public/management.rs
This adds two management API endpoints:
* Component update: PUT /api/public/v0/workspaces/:workspace_id/change-sets/:change_set_id/components/:component_id/properties
Lets you pass a set of properties with either `{ "propId": <value> }` or `{ "<prop name/path>": <value> }`, and sets those properties to the given values.
This is patchy at the top level in that it will only set properties you specify at the top level, but it will replace the entire value of anything you set. So if you have a property like `{ a: { b: 1, c: 2 } }` and you POST with `{ "a": { b: 10 } }`, then `c` will be reset to its default value. But if you set `{ "a/b": 10 }`, then `c` will retain its value.
The final interface is something we intend to experiment with; this gets us to where we have some flexibility writing …
=> feat(sdf): Management APIs to update components+trigger management functionsAdd "update component properties" and "trigger management functions"

.github/workflows/deploy-stack.yml
The API test stage was not waiting like I wanted so it was testing way too early. This fixes that problem and should stabilise false alerts.
=> fix: amend minor typo in dependency for deploy pipeline

lib/dal/tests/integration_test/func/kill_execution.rs, lib/veritech-server/src/handlers.rs
This change ensures that for all functions types, when errors occur (such as killing a function, or timing out), we inform subscribers of the failure so they can handle them appropriately. 
The main issue this fixes is during DVU jobs, if a function times out or is killed, the job will continue to run until it hits its own time out, exacerbating hung change sets
<div><img src="https://media3.giphy.com/media/HNEmXQz7A0lDq/200.gif?cid=5a38a5a2lrlurzvfwqm1iisnw35fjbxb1j3mbsc8nyam7cn3&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:234px;width:300px"/><br/>via <a href="https://giphy.com/gifs/fail-failed-HNEmXQz7A0lDq">GIPHY</a></div>
=> fix(veritech): When errors occur that don't cause us to retry the function, inform subscribers

lib/sdf-server/src/service/session/restore_authentication.rs
When you refresh, you are sent back to the auth portal.
We're getting 500 ChangeSet not in Workspace on restore_authentication, and it appears to be due to https://github.com/systeminit/si/pull/5249/files#diff-330148b6e26e474bbe8c5b90dbb8f574e97786bf077c33be74f7a9d9bf0c604cL16 .
This reverts that part of the change (we're not reverting the whole PR because there are others stacked on top of it and this may well be faster). It fixes the issue locally.
=> fix: Restore restore_authentication to before last change to resolve 500

app/web/src/store/views.store.ts
=> Fix: if no view data is received, but component exists on this view, we need to allow it to process

bin/lang-js/package.json, bin/lang-js/src/function.ts, bin/lang-js/src/function_kinds/management.ts, bin/lang-js/src/transpile.ts, deno.lock, flake.nix, lib/cyclone-client/src/client.rs, lib/veritech-client/tests/integration.rs
I created this link manually in an arm64 rootfs and things started to work
=> fix: arm rootfs needs an arm linker

lib/dal/src/diagram.rs
Same fix as the one before, but very different
=> Fix: to determine what mgmt edges are removed, we need all mgmt edges, not just components & edges in the view

bin/lang-js/src/transpile.ts
This is adding time to func runs as we now wait a second per beforefunc executed
=> fix: reduce lockfile update in langjs

app/web/src/components/AssetDetailIntrinsicInput.vue, app/web/src/components/AssetDetailsPanel.vue, lib/dal/src/func/binding/attribute.rs, lib/sdf-server/src/service/v2/func/binding/create_binding.rs
This change fixes a number of bugs with the intrinsics panel: 
1. Cannot destructure in AssetDetailIntrinsicInput, as we rely on the object reference (which exposed....)
2. When func bindings change, ensure we're firing func_updated to capture the func that was detached as well as attached (which exposed....)
3. ensure the funcId in the URL matches the funcId in the payload 
This was tested collaboratively: 
1. Unlock the region schema and create an editing component (that auto-upgrades as bindings change)
2. Change the region output socket to unset, see that it works (both in the UI and in the created component)
3. Change it back to a Prop and input socket (and see that it works) 
5. Change the region prop to take input from the si/root/name prop (see that it works)
6. Add a new prop, …
=> Fix(web,sdf,dal): Ensure Intrinsics Panel functions correctly and is reactive to changes

bin/si-gen-cloud-control/src/commands/generateSiSpecDatabase.ts, bin/si-gen-cloud-control/src/spec/props.ts, bin/si-gen-cloud-control/src/spec/siFuncs.ts, bin/si-gen-cloud-control/src/spec/sockets.ts, bin/si-gen-cloud-control/test/spec_test.ts, deno.lock
Add siFuncs and lays out the props like:
* all props go in the domain
* create- and write-only props in the domain get input sockets and related attrFuncs
* read-only props in the domain get output sockets that they are inputs to
* all read-only props go in resource_value
* they get added as inputs in the related domain prop
This means things like VpcId that come back from a resource get added to `/root/resource_value/VpcId`, then `/root/domain/VpcId` then as an output socket with the value. 
Other domain props can be set normally or via the related input socket. 
This includes setting the paths, but the path for objects and maps might be... wrong. For now. Deal with it.
=> feat: sifuncs, resource_values, paths, and input

Cargo.lock, lib/rebaser-server/BUCK, lib/rebaser-server/Cargo.toml, lib/rebaser-server/src/change_set_processor_task.rs, lib/rebaser-server/src/handlers.rs, lib/rebaser-server/src/lib.rs, lib/rebaser-server/src/serial_dvu_task.rs
This change alters the logic that helps a change set "process" task to shut down when no Rebaser requests have been seen over our `quiescent_period`. Prior to this change there was a shutdown window period where the `ChangeSetProcessorTask` would not be looking for new Rebaser requests to process while waiting for the `SerialDvuTask` to end. As a hedge against this scenario the process task handler checks the change set subject just before ending to ensure that if there's at least one request message that we don't ack/delete the task.
In this altered version of a quiescent shutdown we notice the quiet period as before in the Rebaser requests subscription stream. However, now a `quiesced_notify` `tokio::sync::Notify` is fired to signal the `SerialDvuTask`. Then the `ChangeSetProcessorTask` …
=> feat(rebaser): change quiescent shutdown to reduce missed activity

lib/dal/src/action.rs, lib/sdf-server/src/service/public/change_sets.rs, lib/sdf-server/src/service/public/management.rs, lib/sdf-server/src/service/public/workspaces.rs
* Copies over almost verbatim the existing force_apply and request_approval endpoints to the automation API, so that we can make a Github Action trigger a management function and merge to HEAD (or request merge to head).
* Adds a "merge_status" endpoint to the automation API, which yields the status of the changeset and any actions enqueued from it in this format:
```json
{
"changeSet": {
"createdAt": "2025-01-18T01:20:59.869049Z",
"updatedAt": "2025-01-18T01:25:44.315196Z",
"name": "2025-01-18-01:20",
"id": "01JHVFZFYS5N65J4QN76004G9N",
"status": "Applied",
"baseChangeSetId": "01JH8VFFYD4FAYF1VPCS7TSWHX",
"workspaceId": "01JH8VEGZYXF5WYFF9Z538F3Q0",
"mergeRequestedByUserId": "01JH8VEGMN6Q385M3Q44RWJG22",
"mergeRequestedByUser": "jkeiser",
"mergeRequestedAt": …
```
=> feat(sdf): Add apply/merge_status automation API endpoints

dev/BUCK, dev/Tiltfile
This change changes the build step for a Tilt local resource (called the
`cmd` attribute) to a common `buck2 build` command with all core backend
targets enumerated. In other words, all the following services:
- `//app/web:dev`
- `//bin/forklift:forklift`
- `//bin/pinga:pinga`
- `//bin/rebaser:rebaser`
- `//bin/sdf:sdf`
- `//bin/veritech:veritech`
will use the *same* `buck2 build ...` command.
Why and How?
Prior to this change, each service only tried to build itself (that is,
the Rebaser only attempted to build `//bin/rebaser:rebaser`). The
problem with this approach is that each `buck2 build` subcommand would
interfere with other in-flight `buck2 build` commands as they share a
single `buckd` daemon (this is enforced by design in the Buck2 daemon).
With this change, the first service to …
=> build(tilt): refactor build cmds to speed up initial dev:up

bin/si-gen-cloud-control/.gitignore, bin/si-gen-cloud-control/cloudformation-schema/.gitignore, bin/si-gen-cloud-control/deno.json, bin/si-gen-cloud-control/si-specs/.gitignore, bin/si-gen-cloud-control/src/cfDb.ts, bin/si-gen-cloud-control/src/cli.ts, bin/si-gen-cloud-control/src/commands/generateSiSpecs.ts, bin/si-gen-cloud-control/src/commands/generateTarFromSpec.ts, bin/si-gen-cloud-control/src/pipeline-steps/generateAssetFuncs.ts, bin/si-gen-cloud-control/src/pipeline-steps/generateSocketsFromDomainProps.ts, bin/si-gen-cloud-control/src/spec/props.ts, bin/si-gen-cloud-control/src/spec/sockets.ts, bin/si-gen-cloud-control/src/specPipeline.ts, bin/si-gen-cloud-control/tar-packages/.gitignore, bin/si-gen-cloud-control/test/spec_test.ts, deno.json, deno.lock
- Make generator create spec files on a folder
- Add command to make specs into tars on another folder
- Change architecture a little bit so the generator can have steps added easily
- Add asset func generator step, that only generates top level props for now
- Fix issue that made generated input sockets not send values to props
- Make socket generation into its own step
=> Make generator into pipeline, add asset func step

lib/si-firecracker/src/scripts/prepare_jailer.sh
This was increased incorrectly [here](https://github.com/systeminit/si/commit/8ebad96e11d37628e691fa3e6894cf8a8baf37e2).  This was part of the deno work. I increased this for local development as I thought the issues I was seeing were OOM-related, but did not set this back in the PR. I've tested this locally and everything seems to run smoothly.
=> fix: jail memory size incorrectly increaed

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/assets/static/editor_typescript.txt, app/web/src/components/AttributesPanel/TreeFormItem.vue, bin/lang-js/src/asset_builder.ts, lib/dal-test/src/helpers/property_editor_test_view.rs, lib/dal/src/prop.rs, lib/dal/src/property_editor/schema.rs, lib/dal/tests/integration_test/prop.rs, lib/dal/tests/integration_test/property_editor.rs, lib/sdf-server/src/service/component/get_property_editor_schema.rs
When this value is set, if the component has a resource associated with it, then we won't allow a user to set the value in the attribute editor
We know a VPC CidrBlock can't be modified after the resource is created. So we can change the prop definition to be:
```
const cidrBlockProp = new PropBuilder()
.setKind("string")
.setName("CidrBlock")
.setValidationFormat(Joi.string().required().regex(/^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/)(1[6-9]|2[0-8])$/).messages({
'string.pattern.base': 'Must be a valid IPv4 CIDR with CIDR Blocks between /16 and /28'
}))
.setWidget(new PropWidgetDefinitionBuilder().setKind("text")
.setCreateOnly()
.build())
.build();
```
Notice the `.setCreateOnly()` as part of the PropWidget
That causes …
=> feat(dal): Add the ability to set an annotation on a prop in the asset builder that it's create only

lib/sdf-server/src/service/public/components.rs
This adds `GET /api/public/v0/components/:componentId`, which is similar (but not identical) to the mainline /api/v2/components/:componentId endpoint. This endpoints gets the data we most need to handle graceful input validation and defaults in the GitHub Action:
```typescript
{
// The usual component data.
component: { displayName, ... },
// List of views this component is in.
viewData: { viewId, name, geometry }[],
// List of management functions associated with this component.
managementFunctions: { managementPrototypeId, name }[],
// Domain property values. This isn't presently used, but being able to see this is really useful debug information in logs.
domain: <JS value of domain props>
}
```
This gives us enough information that the github action can:
* Allow the user to omit the …
=> feat(actions): Add "get component" management function API

lib/sdf-server/src/service/v2/fs.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
Writes to funcs (tested in vim, more editors should be tested).
Reorgs so asset defs and funcs have their own locked/unlocked subfolders (per func).
=> feat: write to funcs, reorg a bit

lib/sdf-server/src/service/v2/fs.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
Adds an attrs.json file to the schema definition folder. Editing it on
an unlocked schema allows you to update schema attributes (like
description, link).
=> feat: edit schema attributes, fix size after writes

component/init/configs/prometheus.yml
Currently managed prometheus is our highest non-compute AWS bill component in each of our tooling and production accounts. 
We don't really need the 5s granularity so this should reduce the cost component by 6x by pushing the granularity to 30s.
If it turns out we need it super granular to debug something, we can either manually change it or just push it back down when needed.
=> feat: increase scrape interval into prometheus to 30s

lib/dal-test/src/helpers.rs, lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs, lib/dal/tests/integration_test/node_weight/component.rs
During rebase, when we discover a component has been removed that had connections to other components, only enqueue those impacted attribute values (and not all attribute values with the same socket id, as it was before)
This ensures that when change sets are applied to head with deleted components, we do detect that values need to update in other change sets and enqueue them appropriately.
<div><img src="https://media0.giphy.com/media/WQCv56djMTCmQkySAg/giphy.gif?cid=5a38a5a24afgohpj2nbvykynniypzzh49h4qrvy9xq0jen2l&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:381px;width:300px"/><br/>via <a href="https://giphy.com/gifs/moodman-WQCv56djMTCmQkySAg">GIPHY</a></div>
=> fix(dal): Ensure we're only updating what is actually impacted by component deletion

BUCK, bin/lang-js/BUCK, prelude-si/deno.bzl, prelude-si/deno/BUCK, prelude-si/deno/deno_workspace.py, prelude-si/deno/toolchain.bzl, prelude-si/macros.bzl, prelude-si/nix/nix_omnibus_pkg_build.py
Creates a rule that takes all of the dirs declared in the workspace and make the available as buck2 output. I could not figure out how to get the contents of the `workspace` directory just into the root of the build_contents, so I added a bit to copy them up from the workspace dir into the root. 
The result here is hopefully that changes to si-gen-cloud-control won't cause a dependency chain resulting in dal builds when we really don't need them slowing down CI.
=> feat: add a deno workspace buck2 rule

app/web/src/components/ModelingDiagram/ModelingDiagram.vue
The current scheme for copy & paste won't work across views... just nullifying the bad stuff here
=> BUG-710: don't throw, reset copying

bin/lang-js/src/function.ts, bin/lang-js/src/worker.js
Errors were getting swallowed here, so we weren't properly bubbling them up to the user. Now you'll see something like this on obvious failures.
=> fix: lang-js errors not propogating correctly

app/web/src/store/change_sets.store.ts, lib/sdf-server/src/service/v2/change_set/approve_v2.rs, lib/sdf-server/tests/service_tests/change_set_approval.rs, lib/si-events-rs/src/change_set_approval.rs
This PR adds the ability to reject a change set with the fine grained access control feature enabled.
Essentially, rejection is a "social" feature in the sense that it does not affect what can be done with a change set. However, in this world, we still have the ability to determine if a rejection is "stale" and what requirements it is applicable for.
How is this a one-liner change in the backend? Approval checksum calculation is automatic and the overall creation flow is already set up for different status types. In addition, when checking if requirements have been satisfied, we already check if the status is "approved", even though there was only one enum variant at the time that code was written.
That all being said, this PR introduces the ability to reject in the frontend and a …
=> Support rejection in fine grained access control

bin/si-gen-cloud-control/src/commands/generateSiSpecs.ts, bin/si-gen-cloud-control/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/si-gen-cloud-control/src/pipeline-steps/generateSocketsFromResourceProps.ts, bin/si-gen-cloud-control/src/spec/props.ts, bin/si-gen-cloud-control/src/specPipeline.ts
Changes the domain and resource_value layout
* All read-only props will be on the resource_value only
* All output sockets will have a value like `/root/resource_value/VpcId -> VpcId`
* All other props go on the domain
* Create- and write-only props will have a value like `Ipv4IpamPoolId -> /root/domain/Ipv4IpamPoolId`
=> feat: split out resource_values and domain

bin/module-index/src/args.rs, dev/Tiltfile, lib/module-index-server/src/app_state.rs, lib/module-index-server/src/config.rs, lib/module-index-server/src/routes/list_modules_route.rs, lib/module-index-server/src/routes/promote_builtin_route.rs, lib/module-index-server/src/routes/reject_module_route.rs, lib/module-index-server/src/server.rs, lib/module-index-server/src/whoami.rs
We talk to the auth api from the module-index to figure out if you are a systeminit.com user. This honors the SI_AUTH_API_URL environment variable in the module-index (similarly as sdf). It defaults to the production API server.
=> Support local auth api on module-index

app/web/src/components/ComponentConnectionsPanel.vue, app/web/src/store/components.store.ts, lib/dal/src/diagram.rs
Testing Steps:
1. I had the "Basic Template Pattern" mgmt component on the diagram in a separate view
2. I ensured that another component could connect its `Manager` input socket to that mgmt component.
3. I refreshed the page to make sure it would be there. I deleted the connection. And refreshed the page again
4. I made the connection and deleted it (w/o refresh) to ensure that would work.
5. I added two Tailscale Users to the diagram because they can manage one another
6. I made sure I could set and delete both output and input sockets accordingly
7. Try to create a loop in the graph, and see the error message that you can't, and you see the optimistic edge removed
8. I made sure that the dropdown did not have duplicate entries (e.g. output socket "Manage" dropdown had *both* input and …
=> Feat: connections panel now has management sockets

app/web/src/store/feature_flags.store.ts
=> Fix: we have the workspaceId in the URL, dont need to wait & race for the fetch all workspaces call here

bin/auth-api/src/custom-state.ts, bin/auth-api/src/main.ts, bin/auth-api/src/routes/index.ts, bin/auth-api/src/routes/user.routes.ts, bin/auth-api/src/services/auth.service.ts
Right now, automation tokens can do anything the user can in the authentication api. This is because SDF tokens are given the same level of access as auth tokens (we do this so that sdf can talk to the auth api on the user's behalf by just forwarding on the SDF token).
This PR:
* Requires a "web authorized" token for all auth api routes except / and /whoami. This means includes SDF web tokens, auth api tokens, and v2 tokens with role = web, and *excludes* v2 tokens with role = automation.
* Allows automation API access to the `/` and `/whoami` endpoints, but if a token is passed, it checks for token revocation and throws 401 Unauthorized if the token has been revoked. This is necessary for the next PR, which will check for token revocation. Since the auth api must be deployed first, it is …
=> auth-api: Deny automation tokens the ability to access the auth api

app/web/src/utils/typescriptLinterSnippets.ts
This is not required for the majority of our props
=> fix(web): Drop propertyWidget from prop snippet

Cargo.lock, app/web/src/store/change_sets.store.ts, lib/dal-test/src/helpers/change_set.rs, lib/dal/src/change_set.rs, lib/sdf-server/src/dal_wrapper.rs, lib/sdf-server/src/dal_wrapper/change_set.rs, lib/sdf-server/src/service/v2/change_set.rs, lib/sdf-server/src/service/v2/change_set/apply_v2.rs, lib/sdf-server/src/service/v2/change_set/approval_status.rs, lib/sdf-server/src/service/v2/change_set/approve_v2.rs, lib/sdf-server/tests/service_tests/change_set_apply.rs, lib/sdf-server/tests/service_tests/change_set_approval.rs, lib/sdf-server/tests/service_tests/mod.rs, lib/sdf-test/BUCK, lib/sdf-test/Cargo.toml, lib/sdf-test/src/helpers.rs, lib/sdf-test/src/lib.rs
This PR adds a new route for applying a change set with fine grained access control. This route contains new dal wrapper logic to ensure that applying a change set (unforced) only happens if all requirements have been met. There's a new integration test for this as well.
Other changes include, but are not limited to, the following:
- Split apply prepare step into two versions because sdf now handles the protection layer
- Rename the "change_set_approval" module to "change_set" in dal wrapper
- Add sdf-test helpers for mimicking protected apply behavior in the route, which is used by the new test
=> Protect against unforced apply without reqs met

app/web/src/components/AttributesPanel/AttributesPanel.vue, app/web/src/components/AttributesPanel/TreeFormItem.vue, app/web/src/store/component_attributes.store.ts, lib/dal/src/property_editor/schema.rs
If a component has resource_value props, then we are going to show them on the attributes panel. 
the panel will be closed by default and the user can expand it. The panel won't even show if there are no child_props of the resource_value prop
**Existing Component:**
**component with resource_value props**
Notice the value can't be set - as it's set via an attribute func - this is the functionality we want. This panel will be collapsed by default so not to take any extra space
=> feat(web): Show resource_value props in AttributePanel

dev/healthcheck.py
I found this trying to run our stack on macOS
=> chore: update `dev:healthcheck` to check for a higher open file count

dev/Tiltfile
`web` doesn't get much startup build time improvement from being included in the pack of rust apps, and including it in the frontend apps means restarting just web will wait for sdf and friends to build. This breaks that dependency. web still waits for sdf, so we're not losing anything in terms of dependency. Initial build likely isn't affected at all, but the web startup is fast enough that it's not worth trying to parallelize it :)
=> Let web rebuild without rebuilding all the rust

Cargo.lock, lib/dal/src/func/binding/action.rs, lib/dal/src/func/binding/attribute.rs, lib/dal/src/func/binding/authentication.rs, lib/dal/src/func/binding/leaf.rs, lib/dal/src/func/binding/management.rs, lib/sdf-server/src/service/v2/fs.rs, lib/sdf-server/src/service/v2/func/binding/update_binding.rs, lib/si-filesystem/BUCK, lib/si-filesystem/Cargo.toml, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
Also adds a cache to the si-fs client to prevent hammering the backend
when filesystem clients make lots of syscalls.
=> feat(si-fs): create funcs except attr and action, edit bindings

.github/workflows/prod-test-cron.yml, .github/workflows/tools-test-cron.yml
There's an issue with the cypress install step and we can't have this add noise to our internal alerting
=> chore(ci): Temporarily silence cypress tests

app/web/src/components/ViewCard.vue, app/web/src/store/views.store.ts, lib/dal/src/diagram/view.rs, lib/dal/src/workspace_snapshot/graph/v4/diagram/view.rs, lib/sdf-server/src/service/v2/view.rs, lib/sdf-server/src/service/v2/view/remove_view.rs
There was no protection to stop a user from deleting ALL views. We now check to see if there's at least 1 view available before allowing a deletion to proceed
=> fix(sdf, web): Protect against deleting last view

lib/dal/src/workspace_snapshot/graph/v4/approval_requirement.rs, lib/sdf-server/tests/service_tests/change_set_approval.rs
* Restore generated ApprovalRequirements for SchemaVariants
The business logic is that changes to SchemaVariants require approval by the workspace approvers, and we should be generating an ApprovalRequirement for every individual change that requires approval, instead of trying to collapse them down into a single requirement based on who should be approving.
* Move generated ApprovalRequirement for Schema category to individual Schemas
`ApprovalRequirement` are intended to have the `EntityId` of the thing that has changed, and is requiring approval, not the category of the thing that has changed. By having the `EntityId` of the thing that has changed, we are able to provide information for where to look to see the specific thing that has changed, instead of "there is an X that has …
=> Restore generated Schema Variant Approval Requirements and fix Schema Approval Requirements

lib/sdf-server/src/service/v2/fs.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
Call mkdir in the actions or attributes folder to create a "pending"
action or attribute function. A file "PENDING_BINDINGS_EDIT_ME.json"
will appear in the new folder. Edit that file with a correct action or
correct output location for a function, and the save will create the
pending function.
You can also configure function arguments in the bindings for attribute
functions now.
=> feat(si-fs): create action and attribute functions with mkdir

app/web/src/store/func/funcs.store.ts, lib/dal/src/management/prototype.rs, lib/sdf-server/src/service/public/management.rs, lib/sdf-server/src/service/v2/management.rs
Before we throw a raw error as a 500 now we capture the data only and send it as a 400 with a toast
before:
after:
=> feat(sdf): Capture a better error message from mgmt func failures

app/web/src/components/AssetDetailIntrinsicInput.vue, lib/vue-lib/src/design-system/forms/VormInput.vue
This is a stop gap solution until we redesign that panel. This is going to be useful in the interim
=> fix(web): Small turn to expose the prop path in the intrinsics panel

lib/forklift-server/src/server/app/audit_logs/handlers.rs, lib/si-events-rs/src/audit_log.rs, lib/si-events-rs/src/audit_log/v1.rs
Looking into the billion-spans issue, we have a theory that something may be choking on some messages in a NATS queue that don't have the new authenticationMethod field. There are some reasons to think this might not be the issue, but it seems like a safe bet to try back-compatting the format.
=> fix(forklift?): Allow old generated audit logs to be deserialized

app/web/src/components/ApprovalFlowModal.vue, app/web/src/components/InsetApprovalModal.vue, app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/components/layout/navbar/Notifications.vue, app/web/src/store/change_sets.store.ts, lib/sdf-server/src/dal_wrapper.rs, lib/sdf-server/src/dal_wrapper/change_set.rs, lib/sdf-server/src/service/v2/change_set/approve_v2.rs, lib/sdf-server/tests/service_tests/change_set_apply.rs, lib/sdf-server/tests/service_tests/change_set_approval.rs
Here is a breakdown of the changes:
- there is no more change set status === `rejected` or `approved`
- we look at "are all requirements `isSatisfied===true` to determine if someone can apply
- any one can withdraw
- we've updated how we determine "who is an approver" and "how many changesets they can approve"
- any one can "apply", so long as every requirement `isSatisfied`
- you can offer a vote if you're in any approver group of any requirement.
This needs solid testing both with `WORKSPACE_FINE_GRAINED_ACCESS_CONTROL = true` as well as `false`.
=> Feat: Show approvers the breakdown of changes

Cargo.lock, Cargo.toml, bin/hoist/BUCK, bin/hoist/Cargo.toml, bin/hoist/src/main.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
This ensures that when we push a new module, if a module already exists with the same schema, we reject the existing module and then promote ours as a built-in.
Also adds a progress bar for hoist and some basic throttling to ensure we don't lock up when uploading many packages to the module index. The module index should really handle S3 throttling .
=> feat(hoist): reject and promote new modules

lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/management/mod.rs, lib/dal/tests/integration_test/management.rs
This change means that if you try to set a value from a management function, and the value would otherwise be set by another function (for example the region prop takes it's input from an input socket), we will override the value and override the default prototype.  
Tested by writing management functions that do this, and added a integration test.
<div><img src="https://media0.giphy.com/media/SqTa7KFVfBJ9b1QFPo/giphy.gif?cid=5a38a5a2n02qjmtp094c1awymz2fwqsjc5w50jny16jmbmmm&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/power/">Power</a> on <a href="https://giphy.com/gifs/power-starz-season6-episode605-SqTa7KFVfBJ9b1QFPo">GIPHY</a></div>
=> fix(dal): Allow attribute values set by dynamic funcs to be set by management funcs if the value is not controlled by an ancestor

lib/dal/src/job/consumer.rs, lib/dal/src/job/definition/compute_validation.rs, lib/dal/src/job/definition/dependent_values_update.rs, lib/rebaser-server/src/rebase.rs, lib/rebaser-server/src/serial_dvu_task.rs
If it's a DVU job, we need to remove the roots so it's not enqueued again.
I will follow up with an integration test for this if it works but want to get this into Tools ASAP.
<div><img src="https://media4.giphy.com/media/iPRnsx9RzW5e0oQOsJ/200.gif?cid=5a38a5a28nv6j19pbb01ya35eur1f4ual80vlv7guhopptre&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/AppleTV/">Apple TV</a> on <a href="https://giphy.com/gifs/AppleTV-apple-tv-app-iPRnsx9RzW5e0oQOsJ">GIPHY</a></div>
=> fix(dal, rebaser, pinga): If a change set is abandoned, do not process rebase requests or execute jobs. 

app/web/src/components/Workspace/WorkspaceModelAndView.vue, app/web/src/pages/WorkspaceSinglePage.vue, app/web/src/store/router.store.ts, app/web/src/store/views.store.ts
And that required some type updates and making tsc happy
The symptoms were:
- if you were switching between two views, the URL would not change
- if you were switching view 1, 2, 3, the URL would not update until the 3rd change, every time
Testing plan:
1. Switch between views and make sure that every time the URL changes
=> Fix: we need to replace `currentRoute` in the router store as we push & replace new routes, not wait for "beforeResolve"

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts
Adds the capability to do per-schema overrides for special cases. 
EC2 Routes need a `GatewayId`, but it could be either a `VPNGatewayId` of `InternetGatewayId`.
Also adds generating connection annotations in the asset builder func
```typescript
const GatewayIdSocket = new SocketDefinitionBuilder()
.setName("GatewayId")
.setArity("one")
.setConnectionAnnotation("GatewayId")
.setConnectionAnnotation("test<InternetGatewayId>")
.setConnectionAnnotation("test<cats<VPNGatewayId>>")
.setConnectionAnnotation("VPNGatewayId")
.build();
```
=> feat(clover): allow for schema-specific overrides

bin/clover/src/cfDb.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateSubAssets.ts, bin/clover/src/spec/sockets.ts
=> fix(clover): Build sub sub assets

.github/workflows/deploy-stack.yml, .github/workflows/e2e-validation.yml, .github/workflows/prod-test-cron.yml, .github/workflows/run-api-test.yml, .github/workflows/tools-test-cron.yml
- Only test if we're deploying to prod. The Cron for tools will catch any issues post-merge anyway. This should allow us to ship to tools faster and prevent unnecessary queueing
- Re-enable the cypress tests and fix the binary issue there
- Change the test failure strategy to fail_fast, i.e. if literally any subtask fails, immediately fail and page/alert
=> feat: remove tests from the deploy on main cron

dev/Tiltfile
This makes it so when you click the little Restart button next to rebaser, forklift, pinga, veritech, or sdf, they will only rebuild what is necessary for *themselves* to restart. This speeds up restart.
At the same time, we preserve the new "build everything in a single command for performance" on tilt startup by creating a new "rust-backend-build" resource, which those 5 services all depend on. On startup, they will wait for this; but on restart, this won't be retriggered (this is how tilt works in general, inter-service dependencies only matter on startup).
The net effect is to speed up service rebuilds without slowing down initial startup.
<IMG SRC="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGQyMmllNmNzYzkwcDZwenpqZjFuY2c1bjVmdzNxbmw1bDR6OGpjZiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/20NQ …
=> chore(tilt): Only rebuild individual service on Restart in tilt

app/web/src/components/DiagramOutline/DiagramOutlineNode.vue
Currently the diagram outliner shows all ancestors that are frames even if they are not in the current view. Thats not the intention.
Testing steps, easier to use pictures, but the basic setup is:
- have a child of region (VPC outside frame) in TEST that has **no children** in DEFAULT... it should not show in DEFAULT outliner (primary bug)
- have children of region (generic frame, VPC inside frame) in TEST that **have** children in DEFAULT (key pair, ec2 instance)... it should show in DEFAULT outliner (this _was_ working, but needed to make sure the fix to above didn't break this)
- make sure that everything else in both views looks right/didn't break (e.g. root components, frames with no children)
=> BUG-768: only show child frames in the diagram outliner when an ancestor is in the view

bin/lang-js/src/function_kinds/management.ts, lib/cyclone-client/src/client.rs, lib/cyclone-core/src/component_view.rs, lib/cyclone-core/src/lib.rs, lib/cyclone-core/src/management.rs, lib/dal/src/component.rs, lib/dal/src/component/socket.rs, lib/dal/src/func/backend/management.rs, lib/dal/src/func/binding/management.rs, lib/dal/src/management/generator.rs, lib/dal/src/management/mod.rs, lib/dal/src/management/prototype.rs, lib/veritech-client/src/lib.rs, lib/veritech-client/tests/integration.rs, lib/veritech-core/src/lib.rs, lib/veritech-server/src/handlers.rs
This allows your management function to pass on its input connections to any components it creates or manages. It adds three basic functionalities to achieve this:
1. **Reading your input sockets:** `thisComponent` now has a new `incomingConnections` property, containing all incoming connections for each input socket, with `component` and `socket` for each one.
2. **Connecting input sockets:** `ops.create.<component>.connect` now supports input sockets in addition to output sockets (just specify `{ from: { component, socket }, to: string }`). (`ops.update.<component>.connect.add/remove` support this as well.)
3. **Connecting to non-managed components:** You can now connect sockets to arbitrary components by component ID. If `component` is set to a ULID, it will connect to that component …
=> feat(mgmt): Allow management functions to connect their input to their progeny

app/web/src/store/components.store.ts
Can't believe that assignment to rawEdgesById didn't get noticed and cleaned up. Adding the delete pattern we used above as well, just for posterity.
Testing steps:
- we found this during John's workshop steps.
- a views edges were clobbering edges already stored
=> Fix: edge not selectable

Cargo.toml, bin/hoist/src/main.rs, lib/module-index-server/src/config.rs, lib/module-index-server/src/server.rs, third-party/rust/BUCK, third-party/rust/Cargo.toml
Hoist:
* download and upload in threads to make it go _fast_
Module Index:
* add a rate limit configuration for requests to the module index to ensure we don't crush the database or S3 when doing mass uploads or downloads
Hoist downloads ~1800 packages from module index without knocking it over
```bash
❯ time buck2 run //bin/hoist:hoist -- --endpoint http://0.0.0.0:5157 write-all-specs -o .pkgs
File changed: root//.pkgs/AWS::EC2::IPAMAllocation.json
File changed: root//.pkgs/AWS::IoT::ThingType.json
File changed: root//.pkgs/AWS::SageMaker::CodeRepository.json
1831 additional file change events
Build ID: 22ce2f63-447e-4158-a8f5-794ad1a85dbf
Network: Up: 0B  Down: 0B
Command: run. …
```
=> feat(module-index, hoist): rate limiting and parallelization

lib/sdf-server/src/service/v2/management/generate_template.rs
In the generated template function, check if the SI name's of the components are unique, to avoid a bit of a messy user experience if this isn't the case.
I tried to put this in the converge function, but it didn't seem right as the complexity is more hidden to the user. At least with this they can read the code that ensures uniqueness and what it's running the check against.
This is a bit of a patch/hotfix whilst we implement genuinely unique idempotency keys for each component.
it looks like this on failure of the condition:
[
](url)
=> feat: add catch in converge for non-unique si-names of components

lib/sdf-server/src/service/v2/fs.rs, lib/sdf-server/src/service/v2/fs/bindings.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
A new file `bindings.json` in the schema/definition/{locked|unlocked}
folder now exists. It looks like this:
```
{
"props": {
"root/domain/baseCapacity": "Unset",
"root/domain/configParameters": "Unset",
"root/domain/enhancedVpcRouting": "Unset",
"root/domain/ipAddressType": "Unset",
"root/domain/maxCapacity": "Unset",
"root/domain/namespaceName": "Unset",
"root/domain/port": "Unset",
"root/domain/publiclyAccessible": "Unset",
"root/domain/region": {
"InputSocket": "region"
},
"root/domain/tags": "Unset",
"root/domain/workgroupName": "Unset"
},
"output_sockets": {
"workgroupName": {
"Prop": "root/domain/workgroupName"
}
}
}
```
=> feat(si-fs): read and write identity bindings

lib/dal-test/src/expected.rs, lib/dal-test/src/test_exclusive_schemas/legos/small.rs, lib/dal/src/management/mod.rs, lib/dal/tests/integration_test/management.rs
This adds regression tests for incomingConnections. In particular, it tests that incomingConnections values can be used in ops.create.connect and ops.update.connect.add/remove. It also tests that incomingConnections contains the correct values for the given sockets.
=> test(sdf): Add regression tests for incomingConnections

bin/clover/src/cfDb.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/spec/props.ts
When we know the types (because there is an enum present) add the prop as a combobox
```typescript
new PropBuilder()
.setName("HostnameType")
.setKind("string")
.setHidden(false)
.setWidget(new PropWidgetDefinitionBuilder()
.setKind("comboBox")
.addOption("ip-name", "ip-name")
.addOption("resource-name", "resource-name")
.build())
.build()
```
=> feat: splat enums into comboboxes

flake.nix
Adds the govc binary to the nix flake, for interacting with vSphere
=> feat: add govc to interact with vSphere

lib/dal-test/BUCK, lib/dal-test/src/expected.rs, lib/dal/src/component.rs, lib/dal/tests/integration_test/management.rs
This fixes the bug where management connections are removed on upgrade. Specifically:
1. Use a management function to create a component
2. Unlock and regenerate the management component (or the created component)'s schema variant.
3. (If it wasn't already unlocked) upgrade the component
4. Reload the browser.
Before this patch, all management connection from the manager to the managee were removed on step 3. (Step 4 is what reveals the fact that they are gone--we don't send wsevents about it.) This fixes it so it's retained (whichever side gets regenerated).
Tested manually, and wrote an integration test that checks both directions.
=> Keep management connections on upgrade

bin/clover/src/pipeline-steps/updateSchemaIdsForExistingSpecs.ts, bin/clover/src/specUpdates.ts, bin/hoist/src/main.rs
* stream logs from hoist when we use it in clover to check for updates
* add to hoist the ability to generate simple name:schema_id map to make the upgrade process much simpler
* get latest _builtins_ instead of latest modules because @stack72 said to
=> feat: stream hoist logs, simplify update process

bin/clover/src/pipeline-steps/generateAssetFuncs.ts
If there is a default value on the prop spec, we need to add `.setDefaultValue({defaultValue})` to the asset definition function, otherwise on regenerate, this is missing, and we interpret that the user wants to remove the default value for that prop. 
I have not yet uploaded this to a local module index and installed for testing, but hoping this gets us a head start.
=> fix(clover): .setDefaultValue in asset definition func if there is a default value in the prop spec

bin/si-fs/README.md, lib/sdf-server/src/extract/change_set.rs, lib/sdf-server/src/service/v2.rs, lib/sdf-server/src/service/v2/fs.rs, lib/si-filesystem/src/client.rs
The "v2/fs" route hierarchy now supports automation tokens generated in the auth portal. (Web tokens will still work since they are considered a superset of the Automation role)
=> feat(si-fs): support automation tokens for si-fs

bin/clover/src/cfDb.ts, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/pipeline-steps/generateOutputSocketsFromProps.ts
- Generate output sockets for all primaryIdentifiers
- Generate input sockets for string props that match other asset names, which already happened for string arrays
=> feat(clover): Generate sockets for string props

bin/hoist/src/main.rs
We were showing the counts including skipped modules before so the progress bar didn't make sense
=> fix(hoist): Show real total numbers for uploads

lib/dal/tests/integration_test/schema/variant/authoring/regenerate.rs, lib/si-pkg/src/spec/variant.rs
Before this change, if you created a variant with a socket, then modified the socket arity or connection annotations, the updates would not be reflected on regeneration. 
<div><img src="https://media1.giphy.com/media/gWyhZM3XKcyaI/giphy.gif?cid=5a38a5a2pc4u6kg6qpxcd7fyhodcp5rbfjb6qxtx9l1aeax3&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/gifs/metal-while-protractor-gWyhZM3XKcyaI">GIPHY</a></div>
Tested this manually by modifying connection annotations and arity with components on the diagram and seeing them update, and wrote an integration test for it.
=> fix(dal): respect socket arity, connection annotations, and other socket metadata when it changes from variant to variant

bin/clover/src/cfDb.ts, bin/clover/src/cli.ts, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/specUpdates.ts
Allows you to add arguments to `generate-specs` to restrict which services will be run.
```
deno run task generate-specs
deno run task generate-specs ECS S3
```
And gets rid of the hardcoded list of specs.
It also adds `SI_MODULE_INDEX_URL` environment variable support so you can point at an arbitrary module index server. Defaults to what it did before. Probably should default to something else, however :)
=> feat(clover): Allow generation of just specific specs with argument

bin/clover/src/cfDb.ts
This clears out the two remaining clover typescript errors in my Problems tab.
1. JSONSchemaObject is now JSONSchema.Object in the upstream.
2. Typescript doesn't realize that !Array.isArray(prop.type) means "prop.type is not a string" and therefore it doesn't narrow the type down to just the boolean one. This causes some errors because it worries that some of the props from other types might be around and don't match the result.
=> feat(clover): Fix last typescript errors

lib/sdf-server/src/service/v2/fs.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs
After more testing of editing asset definitions, I've made a few fixes.
We don't save the asset func id since after regeneration it can change.
Regeneration happens in a separate commit, so that we don't commit an incompletely assembled variant if the install fails midway through.
=> fix(si-fs): asset def editing improvements

app/web/src/components/AssetDetailsPanel.vue, app/web/src/components/ModelingView/TemplateSelectionModal.vue, lib/vue-lib/src/design-system/forms/ColorPicker.vue, lib/vue-lib/src/design-system/layout/ScrollArea.vue
This PR fixes a number of outstanding bugs with the `ColorPicker`, including -
- The `ColorPicker` selection hitbox was sometimes painting over other elements incorrectly.
- The `ColorPicker` was not properly disabled on the `AssetDetailsPanel` when an Asset was locked.
- The `ColorPicker` did not reset to the given modelValue color when closed.
- The `ColorPicker` itself could cause the application to break the window bounds if opened in the wrong spot.
=> NO MORE COLOR PICKER BUGS

lib/cyclone-server/src/execution.rs, lib/cyclone-server/src/handlers.rs, lib/naxum/src/middleware/ack/maintain_progress.rs, lib/naxum/src/serve.rs, lib/pinga-server/src/handlers.rs, lib/si-data-pg/src/lib.rs, lib/si-pool-noodle/src/instance/cyclone/local_http.rs, lib/veritech-client/src/lib.rs
When we do something like `error=?err` the `error` attribute in Honeycomb is mapped to a bool, so we lose the context. By sending the error struct to `si.error.message` we get more context. This would have been helpful when troubleshooting this week, so I tried to update them everywhere for consistency sake.
=> use si.error.message instead of error in spans

bin/clover/anonymize-specs.sh, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/spec/props.ts, bin/clover/src/spec/sockets.ts
1. Create input sockets for props if they have the same name as the output of some *other* asset. This rule already existed, but we weren't doing it if it was also an output socket on the *current* asset. Now we allow it (as long as we could also connect to some other asset besides ourselves).
2. Make sure we add annotations to sockets even if something else created the socket. This adds Arn as an annotation to a lot of sockets.
3. If a socket has the same name as an asset, but that asset has a compound identity (more than one primaryIdentifier), do *not* automatically create a socket--a single socket can't possibly do the job.
=> feat(clover): Several input socket generation fixes

bin/pinga/src/args.rs, lib/dal-test/src/lib.rs, lib/pinga-server/src/config.rs, lib/pinga-server/src/handlers.rs, lib/pinga-server/src/server.rs, lib/rebaser-server/src/serial_dvu_task.rs
This PR adds a configurable max delivery field to pinga, which defaults to "1".
First, why does the new configuration option default to "1"? The single naxum handler in pinga server relies on the default AckLayer and its inner logic is infallible. How is that the case? The job execution code is wrapped with an infallible wrapper.
There are two feasible ways that the handler can fail, which causes a NACK to be sent via the code in the default AckLayer... the JSON extractor can fail (error 422 on deserialization) or the subject is not a valid UTF8 string. The other extractors are fallible, but their default implementations immediately return "Ok". Therefore, either the request payload is a poison pill or the subject is invalid. In either case, we should not retry the job and we should …
=> Add max deliver config to pinga (default is 1)

lib/sdf-server/BUCK, lib/sdf-server/src/service/v2/fs.rs, lib/sdf-server/src/service/v2/fs/editor_typescript.txt, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs
This adds a new file to the asset definition directories: `index.d.ts`, containing all the types for the asset builder. It inserts a triple-slash directive at the top of the asset index.ts file that references these types, so typescript language servers will pick up the types automatically. This directive will be removed from the code when the file is saved, before it is sent to the backend.
=> feat(si-fs): asset def types

bin/clover/README.md, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/addSignatureToCategoryName.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateActionFuncs.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/pipeline-steps/generateIntrinsicFuncs.ts, bin/clover/src/pipeline-steps/generateLeafFuncs.ts, bin/clover/src/pipeline-steps/generateManagementFuncs.ts, bin/clover/src/pipeline-steps/generateOutputSocketsFromProps.ts, bin/clover/src/pipeline-steps/generateSubAssets.ts, bin/clover/src/pipeline-steps/updateSchemaIdsForExistingSpecs.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/spec/props.ts, bin/clover/src/spec/sockets.ts, bin/clover/src/specPipeline.ts, bin/clover/test/cfdb_test.ts, bin/clover/test/spec_test.ts
Clover is passing a bunch of PkgSpecs that it has dotted with extra cloudformation metadata, which actually contain `ExpandedPropSpec`s deep underneath. But because the PkgSpec *type* only has normal PropSpecs, we have to cast or check all props each time we look at them. The casting is dangerous (can be wrong), and the checking is unnecessary.
This PR adds an ExpandedPkgSpec that is just like PkgSpec except all props underneath are ExpandedPropSpecs. Typescript infers the types everywhere, therefore, and we can remove casts.
* Adds explicit types for everything in the pipeline. This gives us a lot more type safety, completion and editor type features, as many types showed up as "any" due to how ts-rs generates the bindings.
* Removes "type assumption" casts `as *Spec` everywhere (so we …
=> chore(clover): Strongly type Clover working types (specs)

bin/clover/README.md, bin/clover/src/extend.ts, bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/addSignatureToCategoryName.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateActionFuncs.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/pipeline-steps/generateLeafFuncs.ts, bin/clover/src/pipeline-steps/generateManagementFuncs.ts, bin/clover/src/pipeline-steps/generateOutputSocketsFromProps.ts, bin/clover/src/pipeline-steps/generateSubAssets.ts, bin/clover/src/pipeline-steps/updateSchemaIdsForExistingSpecs.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/spec/props.ts
We have a lot of repeated checks for there being 1 schema, 1 variant and that domain is an object prop. This ensures those things at the type level.
It also makes tooltips for individual prop types (object, string, etc.) a bunch more readable by pulling out each PropSpec kind individually (typescript then does the work ahead of time so you can just look at the props on the kind you are looking for).
=> chore(clover): Guarantee single schema, variant and that domain is object prop

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateOutputSocketsFromProps.ts, bin/clover/src/spec/sockets.ts
- Overrides for CloudTrail::Trail sockets
- Stop creating input sockets for the same component that has the output sockets, it that's the only matching socket
- Always create output socket for `${VariantName}Name` and `${VariantName}Id`
=> fix(Clover): Multiple socket fixes

app/auth-portal/package.json, app/web/package.json, lib/vue-lib/package.json, pnpm-lock.yaml
Mitigates https://github.com/systeminit/si/security/dependabot/377
<div><img src="https://media2.giphy.com/media/tHIRLHtNwxpjIFqPdV/giphy.gif?cid=5a38a5a277z1mtnais4oxbi9bfokne2maojgnu4rdhdekksc&amp;ep=v1_gifs_trending&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/></div>
We don't use the development server in production (obviously), but it's nice to tidy up
<hr/>
Tested a dev server for create/update/delete a key pair in AWS. Everything went smoothly
=> fix: bump vite to accommodate CVE-2025-24010

Cargo.lock, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/service/v2/management/generate_template.rs
Uses a regex to replace any invalid characters with valid ones, and checks that the leading character is correct.
=> bug: escape bad variable names in template generation

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/createPolicyDocumentInputSockets.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/spec/sockets.ts
Any prop ending with PolicyDocument, which is a text or json type, will become a textare (if it isn't already) and have an input socket with type `policydocument<aws>` on it, to connect to the new Policy Document asset.
It also fixes asset functions for Clover assets with text area props (right now we generate `setWidgetKind("textarea")` when it needs to be `textArea`).
This affects:
* AWS::CodeArtifact::Domain/Repository
* AWS::DynamoDB::Table
* AWS::EC2::VerifiedAccessEndpoint/VerifiedAccessGroup/VPCEndpoint
* AWS::IAM::GroupPolicy/ManagedPolicy/Policy/Role/RolePolicy/UserPolicy
* AWS::IoT::Policy
* AWS::Logs::AccountPolicy/ResourcePolicy
* AWS::NetworkManager::CoreNetwork
* AWS::S3::BucketPolicy
* AWS::S3Express::BucketPolicy
* AWS::S3ObjectLambda::AccessPointPolicy
* …
=> feat(clover): create input sockets for PolicyDocument props

bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/createPolicyDocumentInputSockets.ts, bin/clover/src/spec/sockets.ts
Most sockets are arity one (only allow one thing). This changes them to arity=one, so that other UI features (and things such as incomingConnections) will disallow multiple connections and yield the right types.
- Validated that Tags stays arity=many
- Validated that "Subnets" and other array-typed props stay arity=many
=> feat(clover): generate arity=one for non-array sockets

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/createPolicyDocumentInputSockets.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/spec/funcs.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/spec/props.ts, bin/clover/src/spec/sockets.ts, bin/clover/src/specPipeline.ts, dev/Tiltfile
This PR:
* Adds doc links to all props that go to the cloudformation documentation (they go directly to the prop when the prop exists, otherwise to the page for the asset). e.g. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnetroutetableassociation.html#cfn-ec2-subnetroutetableassociation-routetableid
* Preserves documentation when regenerating assets (docs weren't in the asset function)
* Uses the modern Node API for base 64 encoding, so that we can support Unicode documentation in asset functions
* Uploaded assets to local module index
* Regenerated the Subnet asset to ensure it regenerated, and clicked the documentation
* Clicked some doc links to make sure they went to the right assets
=> feat(clover): Add doc links to all props; don't lose documentation when regenerating

bin/clover/src/cloud-control-funcs/code-gen/awsCloudFormationLint.ts, bin/clover/src/cloud-control-funcs/qualifications/awsCloudFormationLint.ts, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/generateQualificationFuncs.ts, bin/clover/src/spec/funcs.ts, flake.nix
Adds support for python3 packages to the nix flake, and installs cfn-lint.
Adds the functions that we need in the clover directory, but I'm uncertain how to wire them up.
=> feat: add cfn-lint for clover asset qualifications

component/deploy/docker-compose.yaml, component/init/configs/prometheus.yml, component/pgbouncer-prom-exporter/BUCK, component/pgbouncer-prom-exporter/Dockerfile, component/pgbouncer-prom-exporter/docker-entrypoint.sh, component/pgbouncer-prom-exporter/pgbouncer-conn-string-exporter.sh
Capture those metrics and push them up to our centralised observability stack.
Tested in Tools.
Once this is merged I need to adjust the entrypoint scripts of the relevant nodes to pull the variable required for the metric ingestion.
=> feat: implement pgbouncer metric collection into prometheus

bin/clover/src/cfDb.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/spec/props.ts, deno.lock
This PR adds Joi validations for scalars:
- number: minimum, maximum, exclusiveMinimum, exclusiveMaximum, multipleOf
- string: minLength, maxLength, pattern, format: date-time/timestamp/uri
It does this by:
1. prop.joiValidationGenerating the Joi validation expression (`Joi.string().max(255).pattern(new RegExp("^arn:"))`) based on the type and validation criteria on the property. If there are no modifiers besides the type (like string / number / boolean), validation is not generated. This is stuffed in prop.joiValidation, which will be used by the asset function generator later.
2. prop.data.validationFormat: We then eval() the joiValidation Calling it in the generator with `eval()`, calling `describe()` on the resulting Joi object and encoding that to JSON before putting it into package …
=> feat(clover): add Joi validations

bin/lang-js/src/function.ts, bin/lang-js/src/index.ts, bin/lang-js/src/request.ts, deno.lock, lib/cyclone-core/src/action_run.rs, lib/cyclone-core/src/kill_execution.rs, lib/cyclone-core/src/management.rs, lib/cyclone-core/src/request.rs, lib/cyclone-core/src/resolver_function.rs, lib/cyclone-core/src/schema_variant_definition.rs, lib/cyclone-core/src/validation.rs, lib/cyclone-server/src/execution.rs, lib/cyclone-server/src/handlers.rs, lib/cyclone-server/src/server.rs, lib/cyclone-server/src/state.rs
Instead of starting lang-js at the time we execute a function, we will start it when cyclone starts. This should helps us churn through functions more quickly when pool is full as we won't have to incur the ~80ms lang-js startup time.
=> feat: start lang-js with cyclone

bin/si-fs/BUCK, flake.nix
This change introduces a new Nix derivation helper
(`standaloneBinaryDerivation`) which uses a `binDerivation`-built
package and prepares its main binary to be runnable without the full Nix
package closure.
Note that at the moment, this very much depends on the
dynamic libraries at play and whether or not the executing system has
the correct versions. At the moment, we're targetting the `si-fs` binary
which only depends on `libc` and `libgcc`. Future work will attempt to
make these binaries more flexible and portable where possible.
=> build(nix): create si-fs-standalone Nix pkg for a Nix-free binary

Cargo.lock, Cargo.toml, lib/si-layer-cache/BUCK, lib/si-layer-cache/Cargo.toml, lib/si-layer-cache/src/hybrid_cache.rs, third-party/rust/BUCK, third-party/rust/Cargo.lock, third-party/rust/Cargo.toml
I don't have definitive evidence, but I suspect this change will help with the memory pressures we have not been able to resolve. Specifically, [this change](https://github.com/foyer-rs/foyer/commit/170a4108b5dcccbfbcfe0912bcd36eb0eef6dd78).
> fix: fix memory leak caused by circle reference count
This has some interesting implications around how the disk cache works and make me wonder if we'll be writing to it as often. The ideal situation here is that we'll be caching old entries without busting our memory limit and flushing all entries when stopping the service.
Note that they broke out the metrics collection to a separate crate, so I brought that in here.
=> chore: bump foyer to 14.1

bin/clover/src/cfDb.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/spec/props.ts, bin/clover/src/specPipeline.ts
This adds validation for required fields.
- An object field is required if it is in `required: ["A", "B"]` in its parent object. The parent object must not be optional.
=> feat(clover): Add vallidation for required fields

bin/si-api-test/README.md, bin/si-api-test/benchmark/abandon_all_change_sets.ts, bin/si-api-test/benchmark/install_modules.ts, bin/si-api-test/benchmark/one_upper.ts, bin/si-api-test/main.ts, bin/si-api-test/sdf_api_client.ts, bin/si-api-test/test_helpers.ts, bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts, bin/si-api-test/tests/5-emulate_paul_stack.ts
The tests for benchmarking aren't really doing many assertions, so I created a separate benchmark folder to house them. We ignore this folder during end to end tests, and if you want to trigger a benchmark, invoke Deno with `--tests benchmark/{testName}`
<div><img src="https://media0.giphy.com/media/MCOMLZSvTGD1CaqQug/giphy.gif?cid=5a38a5a24wu3ykasw4lu6w9y7kfzhc4y8hd76phvh0xzaorb&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/Similarweb/">Similarweb</a> on <a href="https://giphy.com/gifs/Similarweb-valentines-day-data-similarweb-MCOMLZSvTGD1CaqQug">GIPHY</a></div>
=> feat(si-api-test): Adding the few tests we've been running to benchmark and measure performance

bin/clover/src/pipeline-steps/generateSubAssets.ts, bin/clover/src/spec/props.ts, bin/clover/src/specPipeline.ts
This PR:
* Adds top-level documentation links for all schemas (including sub-assets)
* Fixes links to many props that referenced definitions (these get their own pages in AWS).
There are still at least some props that are under referenced definitions which don't link to the sub-page. I suspect it's because of how often things like oneOf/anyOf are used when $ref is used (we don't support $ref there). Future turn.
* Regenerated and diffed all assets to make sure doc links generally looked right
* Loaded up an asset, looked at the doc link
=> feat(clover): Add top-level doc links

bin/si-fs/BUCK, bxl/dependent_targets.bxl, prelude-si/artifact/publish.py, prelude-si/macros.bzl, prelude-si/macros/nix.bzl, prelude-si/nix.bzl, prelude-si/nix/BUCK, prelude-si/nix/nix_binary_build.py, prelude-si/nix/toolchain.bzl
This change introduces a `nix_binary` Buck2 rule (and macro) which is used in `bin/si-fs` to build, publish, and promote a "standalone" binary of the `si-fs` FUSE filesystem daemon.
=> build(buck2): impl `nix_binary` Buck2 rule to build/publish/promote

Cargo.lock, bin/hoist/BUCK, bin/hoist/Cargo.toml, bin/hoist/src/main.rs
Right now, we tend to overwhelm the module index with 1400 requests when uploading. This PR imits concurrent requests from hoist client (100 by default, --max-concurrent lets you set the value). It also shows how many requests failed at the end.
* Ran against local client with no max, max=1, and max=2000. Observed concurrency and failure printing.
=> chore(clover): Add throttling to hoist

deno.lock, lib/yjs-codemirror-plugin/package.json, lib/yjs-codemirror-plugin/rollup.config.js, pnpm-lock.yaml
Migrate off `rollup-plugin-terser` -> `@rollup/plugin-terser` to mitigate `CVE-2024-11831`
Tested locally, looks like terser was just used in some of the codemirror functionality, so I've tested that code saves/reloads/can be minimised in the authoring part of the product.
=> fix:CVE-2024-11831 - rollup

lib/sdf-server/tests/service_tests/change_set_apply.rs, lib/sdf-server/tests/service_tests/change_set_approval.rs
This PR fixes two flake-y tests by waiting for actions to run related to "Starfield". Interestingly, this should have only started happening after #5451, which was reverted by #5478 and is intended to come back on "main" after #5485 is approved and merged.
That being said, this can happen for a number of reasons, but the key takeaway is that we should be waiting for actions to run whenver possible in our tests.
=> Fix two flake-y tests by waiting for actions

flake.lock, flake.nix
Upgrade the versions of whats in our nix flake, in particular to catch an updated version of cfn-lint
=> chore: nix flake update

lib/dal/src/pkg.rs, lib/dal/src/pkg/import.rs
This PR creates the resource payload to value intrinsic func (new version) if it wasn't specified in the package spec, which would have handled installation.
=> Create resource payload intrinsic if not in spec

bin/clover/src/cfDb.ts, bin/clover/src/cli.ts, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/ignoreSpecsWithoutHandlers.ts, bin/clover/src/spec/pkgs.ts, bin/clover/src/specPipeline.ts, bin/clover/src/specUpdates.ts
Some AWS resources (such as Route53 RecordSet) cannot be successfully used with cloudformation. This is inferrable by what types of `handlers` they have, showing what sort of actions you can do with them.
This PR:
* Makes it so we don't generate specs for types without create, read, update, delete or list handlers.
* Processes specs in alphabetical order so we can see what is happening
* Keeps the cfSchema around in ExpandedPkgSpec so that it can be used (but removes it at the end of generation so it doesn't bulk up the PkgSpec
* Some types have some handlers but not others. This only handles types where we don't want to generate the asset *at all*. We will handle selectively turning off various actions / management functions based on the handlers in a separate PR.
* During this, we …
=> feat(clover): Do not generate specs for types without handlers

bin/clover/BUCK, bin/clover/src/pipeline-steps/prettifySocketNames.ts, bin/clover/test/cfdb_test.ts, bin/clover/test/spec_test.ts
We needed to include the entirety of the source in order for the tests to be bubbled up when we figure out what changed. Also, we exclude the cc func code so we don't have to bring the types into them.
=> fix: make clover tests run in CI

component/init/configs/pgbouncer.ini
Moves the pgbouncer configuration off the default database which is grouped together, into another param to allow me to test out moving the layer-cache into another RDS/db
In tools I've seeded this param + will seed in prod if it works or will revert
=> feat: move layer cache to external db param

lib/dal/src/component.rs, lib/dal/tests/integration_test/action.rs, lib/sdf-server/src/service/component.rs, lib/sdf-server/src/service/component/update_property_editor_value.rs, lib/si-posthog-rs/src/api.rs
For now, this is behind a feature flag as we work out the various permutations and behavior we want to see.  
When an attribute value is updated for a component, and the component has a resource AND an update function exists, enqueue it. Then, build a dependency graph, and if any downstream components with resources also have update functions, enqueue them as well.
<div><img src="https://media3.giphy.com/media/3rgXBGYrye5vSfhMdO/giphy.gif?cid=5a38a5a2g5yqf5ny33avmf698cav7iwx3pp3mb0dr1v7rvc2&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:207px;width:300px"/><br/>via <a href="https://giphy.com/thecomebackhbo/">The Comeback HBO</a> on <a href="https://giphy.com/gifs/thecomebackhbo-change-changes-ch-3rgXBGYrye5vSfhMdO">GIPHY</a></div>
=> feat(dal,sdf): Auto-enqueue update functions for impacted components

bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/pipeline-steps/generateIntrinsicFuncs.ts, bin/clover/src/spec/props.ts, bin/clover/src/spec/siFuncs.ts, bin/clover/src/specPipeline.ts, lib/si-pkg/bindings/PropSpec.ts
We are going to take JSON Numbers as Float. This will allow us to support their precision. We need to ensure we add the setFloat intrinsic for this
We have the new intrinsics for resourcePayloadToValue and NormalizeToArray so we need to use those in the pkgSpecs
We are also changing to use the AWS Colour pallet - #FF9900
=> feat(clover): Change how JSON Numbers are represented in assets

lib/sdf-server/src/service/v2/fs.rs, lib/sdf-server/src/service/v2/fs/bindings.rs, lib/si-filesystem/src/async_wrapper.rs, lib/si-filesystem/src/client.rs, lib/si-filesystem/src/command.rs, lib/si-filesystem/src/inode_table.rs, lib/si-filesystem/src/lib.rs, lib/si-frontend-types-rs/src/fs.rs, lib/si-frontend-types-rs/src/func.rs
Supports deno by configuring a workspace root deno.json and a .vscode/settings.json with "deno: enable". In order to support deno we prefetch every function so we can fill out the deno.json workspaces list.
If new functions come in, or are created, *you will have to reload your deno workspace to get them parsed by the deno language server*.
`node_modules` for deno are not yet supported. They can be! But a passthrough will have to be implemented so that the node module tree can be written to disk in another folder, and mirrored in the si-filesystem system.
=> feat(si-fs): support deno

bin/clover/src/cfDb.ts, bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/generateAssetFuncs.ts, bin/clover/src/pipeline-steps/generateSubAssets.ts, bin/clover/src/spec/props.ts, bin/clover/src/specPipeline.ts
This fixes the doc links we create for props that are part of nested definitions. In Cloud Formation, nested object definitions are placed in their own pages.
We had code trying to make this work, but it relied on `$ref`, which is stripped from most props during dereferencing. This code populates a "defName" into every prop with the name of its containing definition before the dereferencing happens.
* Diffed output, verified that only docLink changed
* Spot checked modified docLink, verified that old link failed and new link succeeded
=> fix(clover): fix doc links for nested props

bin/clover/src/pcre.ts, bin/clover/src/spec/props.ts
Cloud Formation uses JSON Schema, where regexes are in Java format. We need Joi validation to check the patterns, which means converting them. This PR does enough conversion to get the Cloud Formation regexes working:
* Works around JS's lack of support for `(?<flags>)`
* Reads the flags s, i and m if you put them at the beginning of the regex, and translates them to flags: `(?sm)`
* Translates `(?-s:.*)` to `[^\r\n]*` (generally turning flags on and off inside the regex is not supported, but this is the only place it is done)
* Translates `\A` -> `^` and `\Z` -> `$`
* Supports `\p{UnicodeClass}` by enabling the `u` flag when it is seen
* Flips on several previously-ignored patterns which now work
It also carves out a small number of exceptions for what appears to be actually broken …
=> fix(clover): translate Java regexes to JS syntax

bin/clover/src/cloud-control-funcs/actions/awsCloudControlCreate.ts, bin/clover/src/cloud-control-funcs/actions/awsCloudControlUpdate.ts, bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenCreate.ts, bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenUpdate.ts, bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
This is the first part of this work. We now need to ensure that we can use this prop as part of the payload we send to AWS
This isn't specific to SecretManager:;Secret, this is a pattern that we will need to replicate with other assets like KmsKey and RDS DBInstance USername/Password
=> feat(clover): Adding an override for the secrets manager secret

app/web/src/components/ModelingDiagram/DiagramGroup.vue, app/web/src/components/ModelingDiagram/DiagramHelpModal.vue, app/web/src/components/ModelingDiagram/DiagramNode.vue, app/web/src/components/ModelingDiagram/DiagramView.vue, app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/components/ModelingDiagram/diagram_constants.ts
https://github.com/user-attachments/assets/fe54b077-390c-4e53-a0c6-6bad96efa483
- Rendering occlusion for nodes, groups, and views which are not visible to the user
- Text adjusts/hides based on zoom level for nodes, groups, and views
- Also some improvements to the `ModelingDiagram` debug tools
=> diagram rendering occlusion and dynamic text hiding based on zoom

bin/sdf/src/main.rs, lib/dal/src/change_set/status.rs, lib/dal/src/lib.rs, lib/sdf-server/src/garbage_collection.rs, lib/sdf-server/src/lib.rs
While we do evict snapshots when a change set pointer moves, we don't do anything when a change set's status is no longer one of the "active" statuses. We also do not currently allow setting the status of a change set back to one of the "active" statuses once it has been moved out of being "active".
Because a change set is forever "inactive" once it has become inactive, it is not necessary to keep the snapshot around, unless it is also being used by an "active" change set.
This new migration-mode (`garbageCollectSnapshots`) queries all "active" change sets to gather their workspace snapshot addresses, and all of the workspace snapshot addresses in the LayerDb. Any workspace snapshot that is at least an hour old, and is _NOT_ referenced by an "active" change set is removed. We only …
=> Add "migration-mode" to remove workspace snapshots unused by any active change sets

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/reportDeprecatedAssets.ts, bin/clover/src/specPipeline.ts
Adds "::" to category names and adds a warning log on the clover generator when it notices that the module index has specs that are not generated anymore, meaning they've probably been removed by AWS
=> feat(clover): Colons on category names and deprecation reporting

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/removeUnneededAssets.ts, bin/clover/src/pipeline-steps/reportDeprecatedAssets.ts, bin/hoist/src/main.rs
Remove quicksight modules since they were huge. Also hoist gives you the option of listing the modules before pushing
=> feat(clover, hoist): Ignore quicksight, module listing on hoist

app/web/src/components/modules/ModuleListPanel.vue, app/web/src/store/module.store.ts
We do want to it in in our module management tab though, so moving this to only run when that tab is activated
I tested this by ensuring the asset list still includes uninstalled modules that have been cached and I don't see unnecessary calls to list builtins, and seeing that we only call out to the module index when loading the internal only module management tab
<div><img src="https://media4.giphy.com/media/ZEHkIJQXaRG5YohwpS/giphy.gif?cid=5a38a5a2cfbyyavq1ylm00gbp5q8fri5k8i8s8gmi0m374i4&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/tvland/">TV Land</a> on <a href="https://giphy.com/gifs/tvland-gg-golden-girls-goldengirls-ZEHkIJQXaRG5YohwpS">GIPHY</a></div>
=> fix(web): as the builtins are cached and returned when we list variants, we don't need to hit the module index directly anymore.

lib/dal/src/component.rs
Saw this live in Tools Prod, autoconnect returned a graph cycle error because it matched on it's own output socket, whoops! This fixes that!
=> fix(dal): Don't attempt to autoconnect to the component to itself

bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
This generates:
```
{
624   │                 "name": "UserData",
625   │                 "data": {
626   │                   "name": "UserData",
627   │                   "validationFormat": null,
628   │                   "defaultValue": null,
629   │                   "funcUniqueId": null,
630   │                   "inputs": [],
631   │                   "widgetKind": "textarea",
632   │                   "widgetOptions": [],
633   │                   "hidden": false,
634   │                   "docLink": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#cfn-ec2-instance-userdata",
635   │                   "documentation": "The user data to make available to the instance."
636   │                 },
637   │                 "uniqueId": …
```
=> fix(clover): Adding a text Widget override for EC2 Instance UserData

bin/clover/src/pipeline-steps/removeUnneededAssets.ts
~~We have the manually curated cloudformation assets that we created to bring together the end to end scenarios~~
We are going to remove AWS::Cloudformation::Stack and replace it with our own implementation
=> fix(clover): Remove the cloudformation spec generated cloudformation 

component/toolbox/scripts/supporting-funcs/cloudfront-funcs.sh
We are failing to exit if an invalidation has never happened on a new CDN.
This handles that case.
<hr/>
Tested against tools prod, which is in the same situation. Two CDNs one of which is a spike CDN that has never had an invalidation.
=> fix: amend logic in toolbox to handle situation where CDN has zero invalidations so far

app/auth-portal/src/pages/BillingPage.vue, app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue, app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/auth-portal/src/pages/WorkspacesPage.vue, bin/auth-api/src/routes/index.ts, bin/auth-api/src/routes/workspace.routes.ts
Before this commit, if you were an unverified email user you could bypass the check for email verification and create a new workspace. This prevents this.
We redirect an unverified user to the profile page if they try and hit workspaces, workspace details or billing
We also prevent these API calls in the UI by checking that the email is verified on specific routes we want to protect
=> fix(auth-portal): Ensure a user must be email verified before proceeding

app/auth-portal/src/pages/WorkspaceDetailsPage.vue, app/auth-portal/src/store/workspaces.store.ts, bin/auth-api/prisma/migrations/20250224195419_add_is_hidden/migration.sql, bin/auth-api/prisma/schema.prisma, bin/auth-api/src/routes/admin.routes.ts, bin/auth-api/src/routes/workspace.routes.ts, bin/auth-api/src/services/workspaces.service.ts
This is going to be useful for when you've been invited to a workspace and it's not a workspace you visit often
=> feat(auth-stack): Add ability to hide a workspace from app workspace list

bin/hoist/src/commands.rs, bin/hoist/src/main.rs, lib/si-pkg/src/spec.rs, lib/si-pkg/src/spec/action_func.rs, lib/si-pkg/src/spec/attr_func_input.rs, lib/si-pkg/src/spec/authentication_func.rs, lib/si-pkg/src/spec/func.rs, lib/si-pkg/src/spec/leaf_function.rs, lib/si-pkg/src/spec/management_func.rs, lib/si-pkg/src/spec/prop.rs, lib/si-pkg/src/spec/schema.rs, lib/si-pkg/src/spec/socket.rs, lib/si-pkg/src/spec/variant.rs
* makes it so a PkgSpec can anonymize itself, i.e. set all unique info (dates, ids, etc.) to an empty or known value
* adds a command to hoist to let it transform specs into anonymous specs
these anonymous specs will be used for 
* generating hashes that don't include ids that can be stored in the module index to make comparison of specs more accurate
* generating diffs that ignore redundant information
```
buck2 run //bin/hoist:hoist -- anonymize-specs -t ./bin/clover/si-specs -o ./test
```
=> feat(si-pkg): allow generation of a spec without any unique info

Cargo.lock, lib/naxum/src/middleware/ack/on_failure.rs, lib/naxum/src/middleware/ack/on_success.rs, lib/naxum/src/serve.rs, lib/si-data-nats/BUCK, lib/si-data-nats/Cargo.toml, lib/si-data-nats/src/lib.rs, lib/veritech-server/src/handlers.rs, lib/veritech-server/src/server.rs
This PR adds NATS event callback metrics and other logging during events callback. This allows us to detect issues upon reconnection, sending messages after "publishing" them (i.e. sent in an internal channel to be sent to the server later), etc.
As part of these changes, we also fix some "si.error.message" locations.
=> Add NATS event callback metrics

app/web/src/components/AssetCard.vue, app/web/src/components/AssetListPanel.vue, app/web/src/store/module.store.ts, lib/sdf-server/src/service/module.rs, lib/sdf-server/src/service/module/upgrade_modules.rs, lib/sdf-server/src/service/v2/module/sync.rs
This PR adds the ability to upgrade modules from the cached modules table. This fixes an error when the "install remote module" logic was used from synced modules using the local cache (introduced by #5524).
=> Upgrade modules from cached modules

app/web/src/api/sdf/dal/property_editor.ts, app/web/src/assets/static/editor_typescript.txt, app/web/src/components/AttributesPanel/TreeFormItem.vue, app/web/src/store/component_attributes.store.ts, bin/lang-js/src/asset_builder.ts
Testing carried out:
Interacted with current VPC How-to guide and no changes to any of the existing attributes panel items
Added a schema variant with a json / codeeditor prop and was able to get the new behaviour
Even when a prop had json type and an empty string, we still handled that correctly
Update scope is correct to just JSON types
=> fix(web): Ensuring that we can deal with JSON.Objects in propSpecs

Cargo.lock, lib/dal-test/src/expected.rs, lib/dal/src/pkg/export.rs, lib/dal/src/prop.rs, lib/dal/tests/integration_test/pkg/mod.rs, lib/si-pkg/BUCK, lib/si-pkg/Cargo.toml, lib/si-pkg/src/node/mod.rs, lib/si-pkg/src/node/prop.rs, lib/si-pkg/src/pkg/prop.rs, lib/si-pkg/src/pkg/variant.rs, lib/si-pkg/src/spec/prop.rs
Right now, packages contributed or uploaded to the module index have their props re-sorted alphabetically. This PR modifies SiPkg and SiPkgNodeit so that going from PkgSpec -> SiPkg -> bytes -> SiPkg -> PackageNode -> dal preserves ordering.
* Tested that round-tripping from PkgSpec -> SiPkg -> bytes -> SiPkg -> PksSpec preserves order (it didn't before)
* Added integration test with round tripping that checks the underlying dal functions for:
- Regenerate (asset func -> dal variant/component)
- Install Module (bytes -> SiPkg -> dal variant/component)
- Contribute (dal -> SiPkg -> bytes)
- Hoist Upload (PkgSpec -> SiPkg)
- SiPkg -> PkgSpec (prop order not used anywhere except tests at the moment)
* Manual tests:
* Test that existing uploaded modules still load and are gracefully loaded …
=> feat(sdf): Preserve prop order when uploading packages to the module index

bin/clover/src/cloud-control-funcs/attribute/awsCloudControlCfAssetAttr.ts, bin/clover/src/pipeline-steps/removeUnneededAssets.ts
We don't want a string - we want the object
Also removes StackSet to go with Stack - neither work with our templates and we will remove them for now
=> fix(clover): ensure that we send an object out of CloudFormation Resource Socket

app/web/src/components/ModelingDiagram/DiagramEdge.vue
=> All edges should behave like mgmt edges (only show when components/props are selected)

Cargo.lock, Cargo.toml, lib/dal/BUCK, lib/dal/Cargo.toml, lib/dal/src/validation.rs, lib/joi-validator/BUCK, lib/joi-validator/Cargo.toml, lib/joi-validator/src/alternatives.rs, lib/joi-validator/src/boolean.rs, lib/joi-validator/src/date.rs, lib/joi-validator/src/generic.rs, lib/joi-validator/src/lib.rs, lib/joi-validator/src/number.rs, lib/joi-validator/src/string.rs, lib/joi-validator/src/test.rs
This PR intercepts the simplest Joi validations and runs them in Rust instead of dispatching to Veritech:
- [boolean/string/number].required/valid(a,b,c)/invalid(a,b,c)
- number.integer/min/max/less/greater/unsafe
- string.min/max/length
Any validation not supported on that list, or with any unexpected options, is dispatched to Veritech instead and runs and returns exactly as before.
We produce the same results, as well as the same error message, for all of these, so user experience should be identical.
Once Clover added automated validations to lots of fields on many assets, Veritech is under heavy load because every time you drag out a new asset, many Joi validations are run. All of the Clover validations are very straightforward, however, and encompass a very small subset of what is …
=> perf(veritech): Run simple Joi validations in Rust instead of JS

app/web/src/components/InsetApprovalModal.vue
=> feat(web): Expose the audit log link on the new approval modal

app/web/src/components/Actions/ConfirmHoldModal.vue
=> fix(web): Ensure we handle the hold action modal for light theme

app/web/src/components/ModelingDiagram/ModelingDiagram.vue, app/web/src/store/change_sets.store.ts, app/web/src/store/router.store.ts
Also, it seems we had a URL bug where the viewId was not getting into the URL (we were redirected back to workspace-compose).
I wanted to do this months ago 😉
=> BUG-791: remember the last grid origin per view, and load it when you look at that view

lib/dal/src/management/generator.rs
This ensures that props that contain their default value are not set in mgmt func templates, otherwise updates to the default value will not propagate as the prop will have a set value already.
=> fix: strip default values from templates

app/auth-portal/src/lib/validations.ts, app/auth-portal/src/pages/WorkspaceDetailsPage.vue, bin/auth-api/src/lib/validation-helpers.ts, bin/auth-api/src/routes/workspace.routes.ts
I also protect this in AuthAPI
```
{"kind":"ValidationError","message":"Invalid `instanceUrl` - Invalid"}
```
When sending this request:
```
{"instanceUrl":"javascript:alert(document.cookie)/","displayName":"test13","isDefault":false,"description":"","isFavourite":false,"isHidden":false,"requestUlid":"01JNHA959NB99A17RP8YR9P7G6"}
```
=> fix(auth-portal): Ensure we validate Remote URLs correctly

bin/clover/src/cloud-control-funcs/management/awsCloudControlDiscover.ts
For EC2::LaunchTemplate (and some others we've probably not found yet), object children may exist as null and should be skipped during refinement:
```
Skipping import of lt-026952649cf076dbc; it did not match refinement {
"LaunchTemplateData": {
"SecurityGroups": []
}
}
```
Currently, these aren't skipped as a refinement, as we are looking for any nested key or value regardless of value or content. 
This PR now handles the case where an object may have children, but they're also empty.
=> fix: handle the case where object children do exist, but they are also empty so are not valid refinements

bin/clover/src/commands/generateSiSpecs.ts, bin/clover/src/pipeline-steps/annotateCommonOutputSockets.ts, bin/clover/src/pipeline-steps/assetSpecificOverrides.ts, bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts, bin/clover/src/pipeline-steps/generateOutputSocketsFromProps.ts, bin/clover/src/pipeline-steps/prettifySocketNames.ts
Various fixes for socket annotations ids and names, including splatting id into identifier where appropriate.
```javascript
[
`${variantName}${propName}`,
`${category}${variantName}${propName}`,
`${category}${propName}`,
`${variantName}${propName}entifier`,
`${category}${propName}entifier`,
`${variantName}${propName}entifier`,
`${category}${variantName}${propName}entifer`,
`${variantName} ${propName}`,
`${category} ${variantName} ${propName}`,
`${category} ${propName}`,
`${variantName} ${propName}entifier`,
`${category} ${propName}entifier`,
`${variantName} ${propName}entifier`,
`${category} ${variantName} ${propName}entifer`,
]
```
Results in 
```
KeyId
KeyId<string<scalar>>
KeyKeyId<string<scalar>>
KMSKeyKeyId<string<scalar>>
KMSKeyId<string<scalar>>
KeyKeyIdentifier<string<scalar>> …
```
=> feat: expanded socket annotations

Cargo.lock, lib/dal-test/src/helpers.rs, lib/dal/BUCK, lib/dal/Cargo.toml, lib/dal/src/component.rs, lib/dal/src/diagram.rs, lib/dal/src/management/mod.rs, lib/dal/src/workspace_snapshot.rs, lib/dal/tests/integration_test/component.rs, lib/dal/tests/integration_test/component/paste.rs, lib/dal/tests/integration_test/component/property_order.rs, lib/dal/tests/integration_test/func/authoring/binding/attribute.rs, lib/dal/tests/integration_test/management.rs, lib/dal/tests/integration_test/secret.rs, lib/sdf-server/BUCK, lib/sdf-server/Cargo.toml, lib/sdf-server/src/service/diagram/set_component_position.rs, lib/sdf-server/src/service/v2/view.rs, lib/sdf-server/src/service/v2/view/paste_component.rs
When you paste multiple things, we already restore connections between the components you copied--but we don't copy connections to things *outside* the pasted subgraph. This PR preserves connections to non-copied components when you copy/paste.
This PR:
* Copies incoming connections from components not being pasted.
* Copies "managed by" connection from components not being pasted.
* Now sends an event to let the frontend know when the pasted component has a parent--this makes inferred connections show up in the UI.
* Continues to "mirror" incoming and management connections from components being pasted
* Continues to "mirror" parentage for elements where both parent and child are pasted
* Centralizes the copy/paste logic into Component::batch_copy, so it can be tested in the dal; SDF now …
=> feat(sdf): Keep external connections on paste

bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenCreate.ts, bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenUpdate.ts, bin/clover/src/cloud-control-funcs/code-gen/awsCloudFormationLint.ts
We've added sockets that are more deeply nested in some schemas than we have before. The side effect is that we can fail to remove some empty objects or arrays from the tree, resulting in invalid CloudFormation.
This PR fixes it by rewriting that function to handle deeply nested cases, and to remove its use of recursion (so we don't blow the stack on huge objects).
=> bug: improve removeEmtpy in clover assets
