systeminit/si

- component/lambda/functions/si_lago_api.py
- component/lambda/functions/upload_billing_resource_hours_to_lago.py
We are hitting the (admittedly small) timeout on the lambda that uploads hourly billing data for each customer to Lago. This is because we were loading *all* events from the beginning of time, which is nice because it backfills if anything ever got missed, but is unnecessary 99% of the time.
This PR limits upload to 6 hours' worth of events at a time (configurable).
* We still fill in gaps from previous hours (up to the batch size, which defaults to 6 hours)
* We still recover when we have not run for a long time, even days or weeks (we keep uploading more batches back further in time, until we find a batch where everything has already uploaded).
* We still backfill when there were problems preventing *partial* upload of some events:  for example new customers whose data had not yet come …
> Upload billing events in smaller batches

- component/otelcol/config.yaml
- component/otelcol/honeycomb-config.yaml
<div><img src="https://media2.giphy.com/media/xUOxfbAOLZmR356YgM/giphy.gif?cid=5a38a5a2394vget4ux9cpqtmmdx3561qrcqe55ydcut35lqz&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/jakewilliams/">Jake</a> on <a href="https://giphy.com/gifs/loop-character-walk-xUOxfbAOLZmR356YgM">GIPHY</a></div>
> Add config to export logs via otelcol

- lib/sdf-server/src/service/component.rs
> fix(sdf): Make component not found to be 404 not 500

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- lib/dal-test/src/helpers.rs
- lib/dal/src/action/dependency_graph.rs
- lib/dal/tests/integration_test/action.rs
Also restore right click context menu for edges.
<div><img src="https://media2.giphy.com/media/Xm3b41ZkDH5nOYueh6/200.gif?cid=5a38a5a20yvye8t6whhqt1eyesvuhyzpossknlpoqm97zz40&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/travisband/">Travis</a> on <a href="https://giphy.com/gifs/travisband-travis-fran-healy-guys-wait-for-me-Xm3b41ZkDH5nOYueh6">GIPHY</a></div>
> Add edges between dependent components in the actions dependencies graph for both frames and edges.

- lib/si-firecracker/src/scripts/firecracker-setup.sh
- lib/si-firecracker/src/scripts/prepare_jailer.sh
- prelude-si/rootfs/rootfs_build.sh
> fix: increase overlay image size

- app/web/src/store/components.store.ts
> Clear out processed store data on fetch (removes deletes)

- app/web/src/store/asset.store.ts
- app/web/src/store/components.store.ts
Views "chainsaw" cut too deep, and removed the ability to install assets on demand.
> fix: restore on demand asset installation

- app/web/src/store/components.store.ts
> Fix: old component type remained when switching to different type

- Cargo.toml
- flake.lock
- lib/dal-macros/tests/ui/07-node_weight-no-discriminant-specified-fail.stderr
- lib/dal-macros/tests/ui/08-node_weight-bad-node_hash-custom-code-fail.stderr
- lib/dal/src/func/backend.rs
- lib/dal/src/job/definition/action.rs
- lib/dal/src/job/producer.rs
- lib/dal/src/pkg/export.rs
- lib/dal/src/schema/variant/authoring.rs
- lib/object-tree/src/lib.rs
- lib/sdf-server/src/service/ws/workspace_updates.rs
- lib/si-layer-cache/src/lib.rs
- lib/si-pkg/src/node/package.rs
- third-party/rust/Cargo.toml
The magic `nix flake lock --update-input rust-overlay`
> chore: upgrade rust to version 1.82

- lib/dal/src/diagram/view.rs
- lib/sdf-server/src/service/diagram.rs
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/create_view.rs
- lib/sdf-server/src/service/v2/view/list_views.rs
- lib/sdf-server/src/service/v2/view/update_view.rs
> feat: Create update and list endpoints for views

- component/spicedb/entrypoint.sh
> fix: remove log redirection for spicedb

- .ci/docker-compose.test-integration.yml
- Cargo.lock
- component/spicedb/schema.zed
- lib/permissions/BUCK
- lib/permissions/Cargo.toml
- lib/permissions/src/lib.rs
- lib/permissions/src/schema/schema.zed
- lib/permissions/tests/integration_test/mod.rs
- lib/sdf-server/src/app_state.rs
- lib/sdf-server/src/extract.rs
- lib/sdf-server/src/lib.rs
- lib/sdf-server/src/middleware.rs
- lib/sdf-server/src/middleware/workspace_permission.rs
- lib/sdf-server/src/routes.rs
- lib/sdf-server/src/service/session.rs
- lib/sdf-server/src/service/session/auth_connect.rs
- lib/sdf-server/src/service/session/refresh_workspace_members.rs
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/apply.rs
- lib/si-events-rs/src/actor.rs
> feat: add `WorkspacePermission` axum middleware & v2 change set apply

- bin/si-api-test/tests/1-create_and_apply_across_change_sets.ts
Make the test always attempt to clean up the changesets even if DVU times out or some middle-level interaction fails. This prevents changeset number runaway if the environment is unable to execute dvu for a period of time while the crons are still running.
<div><img src="https://media2.giphy.com/media/2dbnhlCH2JhwdI2gHp/200.gif?cid=5a38a5a2f0tz80po2cm2snd6066dyxge2s80io9ocba8vjy6&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/></div>
> fix: make sure the apply changeset always cleans up

- app/web/src/components/Actions/ActionsList.vue
- app/web/src/components/ApplyChangeSetButton.vue
- app/web/src/components/ApprovalFlowModal2.vue
- app/web/src/components/ApprovalPendingModal.vue
- app/web/src/components/InsetApprovalModal.vue
- app/web/src/components/NoSelectionDetailsPanel.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/store/feature_flags.store.ts
- lib/sdf-server/src/service/v2/change_set/list.rs
- lib/vue-lib/src/design-system/general/ErrorMessage.vue
> Mock ReBAC Approval Modals

- app/web/src/components/AuditLogHeader.vue
- app/web/src/components/Workspace/WorkspaceAuditLog.vue
- lib/dal/src/audit_logging.rs
- lib/dal/src/context.rs
- lib/dal/src/job/consumer.rs
- lib/dal/src/job/definition/action.rs
- lib/sdf-server/src/service/action/cancel.rs
- lib/sdf-server/src/service/action/put_on_hold.rs
- lib/sdf-server/src/service/change_set/abandon_change_set.rs
- lib/sdf-server/src/service/change_set/add_action.rs
- lib/sdf-server/src/service/change_set/apply_change_set.rs
- lib/sdf-server/src/service/change_set/create_change_set.rs
- lib/si-events-rs/src/audit_log/v2.rs
- lib/si-frontend-types-rs/src/audit_log.rs
Including things like RunAction and ChangeSet manipulation in the audidt logs
> feat(audit-logs): Extending the audit logs api

- app/web/src/components/Workspace/CommandModal.vue
- app/web/src/shared/CommandBar.vue
- app/web/src/shared/command.ts
> Abstract the commandbar from the modal itself so the bar can be used elsewhere

- Cargo.lock
- Cargo.toml
- lib/module-index-server/src/models/si_module.rs
- lib/module-index-server/src/models/si_module/module_id.rs
- lib/module-index-server/src/models/si_module/schema_id.rs
- lib/module-index-server/src/models/si_module/schema_variant_id.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
- third-party/rust/fixups/bigdecimal/fixups.toml
- third-party/rust/fixups/quinn-udp/fixups.toml
This was required to protect against a dependabot reported vulnerability https://github.com/systeminit/si/security/dependabot/325
> chore(module-index): Update sea-orm

- app/web/src/store/presence.store.ts
- app/web/src/store/realtime/realtime_events.ts
- app/web/src/store/views.store.ts
- lib/dal/src/user.rs
- lib/sdf-server/src/service/ws/workspace_updates.rs
> Separate cursors on the diagram according to viewId

- component/lambda/functions/billing-set-prices.py
- component/lambda/functions/github_lambda_loader.py
- component/lambda/functions/si_auth_api.py
- component/lambda/functions/si_lago_api.py
- component/lambda/functions/si_lambda.py
- component/lambda/functions/si_redshift.py
- component/lambda/functions/si_types.py
- component/lambda/functions/upload-billing-hours.py
- component/lambda/functions/workspace_delegations_population.py
- component/lambda/sql/workspace_operations.sql
- component/lambda/sql/workspace_verifications.sql
This checks for subscription changes in Lago and syncs them to SI when they change or new ones are added.
It also switches workspace_delegations_population.py to use the shared libraries, and moves the Auth API stuff to its own module.
> Sync subscriptions from Lago when they change

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
> Fix diagram selection rect

- app/web/src/components/Actions/ActionCard.vue
- app/web/src/components/Actions/FuncRunTabGroup.vue
- app/web/src/components/ChangesPanelHistory.vue
- app/web/src/components/ChangesPanelProposed.vue
- app/web/src/components/ComponentDetailsManagement.vue
- app/web/src/components/FuncRunTabDropdown.vue
- app/web/src/components/Management/ManagementHistoryCard.vue
- app/web/src/components/Management/ManagementHistoryList.vue
- app/web/src/components/ManagementRunPrototype.vue
- app/web/src/components/StatusIndicatorIcon.vue
- app/web/src/store/func/funcs.store.ts
- app/web/src/store/func_runs.store.ts
- app/web/src/store/realtime/realtime_events.ts
- lib/dal/src/func/runner.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/ws_event.rs
- lib/sdf-server/src/service/v2/func/get_func_run.rs
- lib/sdf-server/src/service/v2/management.rs
- lib/sdf-server/src/service/v2/management/history.rs
- lib/sdf-server/src/service/v2/management/latest.rs
- lib/si-events-rs/src/func_run.rs
- lib/si-layer-cache/src/db/func_run.rs
- lib/veritech-core/src/lib.rs
- lib/veritech-server/src/handlers.rs
- lib/vue-lib/src/design-system/tree/TreeNode.vue
Shows a history of all management function executions for the change set
in the history tab, and allows you to see the latest execution logs via
the component's management function panel.
> Mgmt func history

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
Clearly i was thinking about it wrong, cleaned up the code too
> Fix child geometry detection

- lib/dal/src/standard_id.rs
- lib/sdf-server/src/service/session/auth_connect.rs
> chore(sdf): ensure owner relation is created for wksp creator on login

- .github/workflows/deploy-module-index.yml
- .github/workflows/down-service.yml
- .github/workflows/instance-refresh.yml
- .github/workflows/invoke-and-check-invalidations.yml
- .github/workflows/migrate-sdf.yml
- .github/workflows/set-maintenance-mode.yml
- .github/workflows/set-service-version.yml
- .github/workflows/up-service.yml
- .github/workflows/upgrade-service.yml
- .github/workflows/upgrade-web.yml
To remove static tokens from AWS, I've implemented a web identity / IDP assume-role into each of our AWS accounts.
Rotation is king
<div><img src="https://media0.giphy.com/media/pzTFWbiWjqpLiC8U3G/giphy.gif?cid=5a38a5a2taxn34q7xpmvn8ex84kkhfecc5hd1nok2qszmq5l&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:348px;width:300px"/></div>
> chore: implementing web-identity via github into aws

- lib/dal/src/diagram/view.rs
- lib/dal/src/ws_event.rs
- lib/sdf-server/src/service/diagram/add_components_to_view.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/create_view.rs
- lib/sdf-server/src/service/v2/view/erase_components.rs
- lib/sdf-server/src/service/v2/view/get_diagram.rs
- lib/sdf-server/src/service/v2/view/list_views.rs
- lib/sdf-server/src/service/v2/view/update_view.rs
Also adds websocket events for the view CRU
> feat: erase components from view endpoint

- component/lambda/functions/si_auth_api.py
- component/lambda/functions/si_lambda.py
- component/lambda/functions/si_types.py
- component/lambda/functions/upload-billing-hours.py
- component/lambda/functions/workspace_delegations_population.py
This fixes an issue where workspace_delegations_population is failing when it tries to query the owners of new workspaces.
It also sprinkles a little typing into the Python Auth API to make it easier to work with the results.
> Fix workspace loading in workspace_delegations_population (billing lambda)

- app/auth-portal/src/components/MemberListItem.vue
- app/auth-portal/src/components/WorkspaceLinkWidget.vue
> fix(auth-portal): Set editor label to be collaborator

- component/lambda/functions/billing-data-check-errors.py
- component/lambda/functions/billing-set-prices.py
- component/lambda/functions/si_lambda.py
- component/lambda/functions/upload-billing-hours.py
- component/lambda/functions/workspace_delegations_population.py
- component/lambda/sql/workspace_operations.sql
- component/lambda/sql/workspace_update_events.sql
- component/lambda/sql/workspace_verifications.sql
This runs the workspace_verifications SQL queries in a lambda, so that we can run it periodically and create alerts to let us know when things have gone weird.
(It's been sitting in my tree and needs a-flushin'.)
> Lambda that runs verification scripts to check for errors in billing data

- lib/dal/src/diagram.rs
- lib/dal/src/diagram/view.rs
- lib/dal/tests/integration_test/view.rs
- lib/sdf-server/src/service/component.rs
- lib/sdf-server/src/service/diagram.rs
- lib/sdf-server/src/service/diagram/add_components_to_view.rs
- lib/sdf-server/src/service/diagram/get_all_components_and_edges.rs
- lib/sdf-server/src/service/v2/view/create_view.rs
- lib/sdf-server/src/service/v2/view/erase_components.rs
- lib/sdf-server/src/service/v2/view/get_diagram.rs
- lib/sdf-server/src/service/v2/view/update_view.rs
also removes unnecessary clietUlids being sent
> feat: get all components endpoint

- app/web/src/components/ModelingView/ModelingRightClickMenu.vue
> added management funcs to ModelingRightClickMenu

- app/web/src/components/DiagramOutline/DiagramOutline.vue
- app/web/src/components/DiagramOutline/DiagramOutlineNode.vue
- app/web/src/components/LeftPanelDrawer.vue
- app/web/src/components/ModelingDiagram/DiagramControls.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingView/DeleteSelectionModal.vue
- app/web/src/components/ModelingView/ModelingRightClickMenu.vue
- app/web/src/components/SidebarSubpanelTitle.vue
- app/web/src/components/ViewCard.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/components/layout/navbar/NavbarPanelCenter.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/store/components.store.ts
- app/web/src/store/presence.store.ts
- app/web/src/store/realtime/realtime_events.ts
- app/web/src/store/views.store.ts
- lib/dal/src/diagram/view.rs
- lib/sdf-server/src/service/diagram/add_components_to_view.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/create_view.rs
- lib/sdf-server/src/service/v2/view/erase_components.rs
- lib/sdf-server/src/service/v2/view/get_diagram.rs
- lib/sdf-server/src/service/v2/view/update_view.rs
- lib/vue-lib/src/design-system/icons/Icon.vue
- lib/vue-lib/src/design-system/panels/ResizablePanel.vue
> Multiple Views

- lib/dal/src/func/authoring/create.rs
- lib/dal/src/func/binding/management.rs
- lib/sdf-server/src/service/v2/func/binding/create_binding.rs
> fix: copy managed schemas when unlocking a management function

- app/web/src/components/DiagramOutline/DiagramOutlineNode.vue
- app/web/src/components/ModelingView/DeleteSelectionModal.vue
> Diagram outliner fix & delete edge fix

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_types.ts
> fix for sockets going off the frame boundary

- component/init/configs/pgbouncer.ini
This PR adds the audit database to "pgbouncer.ini".
> Add audit to "pgbouncer.ini"

- component/init/configs/service.toml
This PR adds a parameter to toggle the audit logs app in forklift.
> Add parameter to toggle audit logs app in forklift

- bin/forklift/src/args.rs
- bin/forklift/src/main.rs
- lib/forklift-server/src/config.rs
This change also adds a debug level log event showing the computed config.
> fix(forklift): ensure that config file defaults work

- app/web/src/components/AttributesPanel/TreeForm.vue
- app/web/src/components/AttributesPanel/TreeFormItem.vue
- app/web/src/components/ComponentConnectionsPanel.vue
- app/web/src/store/views.store.ts
- lib/sdf-server/src/service/v2/view/set_component_parent.rs
- lib/vue-lib/src/design-system/forms/VormInput.vue
> connections panel parent field working!

- app/web/src/App.vue
- app/web/src/components/AttributesPanel/TreeFormItem.vue
- lib/vue-lib/src/design-system/forms/VormInput.vue
- lib/vue-lib/src/tailwind/main.css
> refactoring to replace CSS with Tailwind

- lib/module-index-server/src/server.rs
Expands the AWS Credential Chain in Module Index to support IMDS/metadata endpoint credentials (i.e. instance/ecs task role)
The chain is now as follows:
- Try and pull from env vars
- Try from ~/.aws/profile
- Try from instance metadata/IMDS
> feat: expand AWS Credentials chain for Module Index

- app/auth-portal/src/components/WorkspaceLinkWidget.vue
- app/auth-portal/src/pages/WorkspaceDetailsPage.vue
- app/auth-portal/src/pages/WorkspacesPage.vue
- app/auth-portal/src/store/workspaces.store.ts
- bin/auth-api/src/routes/workspace.routes.ts
- bin/auth-api/src/services/workspaces.service.ts
This will set all of the other workspaces for that user to not be the default because we can only have 1 default
> feat(auth-portal, auth-api): Set ability to make a workspace the default

- .github/workflows/deploy-auth-api.yml
- .github/workflows/deploy-module-index.yml
- .github/workflows/down-service.yml
- .github/workflows/instance-refresh.yml
- .github/workflows/migrate-sdf.yml
- .github/workflows/set-maintenance-mode.yml
- .github/workflows/up-service.yml
- .github/workflows/upgrade-service.yml
- .github/workflows/upgrade-web.yml
> chore(ci): Upgrade version of aws configure-credentials GHA

- app/web/src/components/AttributesPanel/TreeFormItem.vue
> fix(web): Fix Edit Prop modal

- lib/dal-test/src/test_exclusive_schemas/legos/small.rs
- lib/dal/src/management/mod.rs
- lib/dal/tests/integration_test/management.rs
To ensure that parent info is reported before child info, construct a dependency graph based on parentage changes in the management updates, and use that graph to issue ws events in order from parent to child.
> fix(dal): issue management component ws events in parentage order

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
> Fix: children that leave a parent were not re-processing their former parents

- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
- lib/sdf-server/src/service/component/set_type.rs
> Unify view logic in one place

- app/web/src/store/views.store.ts
> Fix: dont use FETCH_VIEW, use FETCH_VIEW_GEOMETRY, when views are created

- app/web/package.json
- app/web/src/components/AdminDashboard/PromptEditor.vue
- app/web/src/components/CodeEditor.vue
- app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
- app/web/src/store/prompt.store.ts
- bin/asset-sprayer-prompts/src/main.rs
- lib/asset-sprayer/src/lib.rs
- lib/asset-sprayer/src/prompt.rs
- lib/dal/src/prompt_override.rs
- lib/sdf-server/src/service/v2/admin/prompts/prompt.rs
- lib/sdf-server/src/service/v2/func.rs
- lib/sdf-server/src/service/v2/func/generate_aws_function.rs
- pnpm-lock.yaml
This allows AI function generation prompts to be edited in the admin panel. Clicking `Override` overwrites the prompt; `Reset` sets it back to its default. You can always tell if the prompt is overridden or not by whether or not the `Reset` button is enabled.
This PR fixes it so the overridden prompts are *used* by AI generation, as well.
> Make AI prompts overrideable in admin panel

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- lib/vue-lib/src/design-system/forms/VormInput.vue
> fix to rename on diagram for frames

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
> Fix: remove dead code, use view store location data

- app/web/src/components/ModelingDiagram/DiagramView.vue
> Fix: make the view hex colors look like the rest of components color scheme

- app/web/src/components/ModelingDiagram/DiagramView.vue
> ENG-2874: Adding icons for view stats in the hexagon

- app/web/src/components/NoSelectionDetailsPanel.vue
- app/web/src/components/SidebarSubpanelTitle.vue
- app/web/src/components/ViewCard.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/store/realtime/realtime_events.ts
- lib/dal/src/change_set.rs
- lib/dal/src/change_set/event.rs
- lib/dal/src/ws_event.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/rename.rs
- lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
https://github.com/user-attachments/assets/cce7a1a2-24a4-423c-83aa-d04b8187a061
> renaming change sets! also some bug fixes and UI improvements

- app/docs/src/roadmap/index.md
> road-map-date

- app/docs/src/reference/asset/function.md
In addition to the changes in the pr, line 868 looks funky, but wasn't sure how to update it. Whomever approves this should take a look at that line and make an adjustment or talk to @stack72
> management-functions

- app/web/src/components/Ai/GenerateAwsFunctionPanel.vue
- app/web/src/components/AssetEditorHeader.vue
- app/web/src/store/func/funcs.store.ts
- lib/asset-sprayer/prompts/aws/import.yaml
- lib/asset-sprayer/src/prompt.rs
- lib/sdf-server/src/service/v2/func/generate_aws_function.rs
This adds a basic prompt for import function generation. It is editable in the prompts UI and generates an import function anytime you are editing a management function.
It also adds a few quality-of-life improvements:
* The text of the button shows exactly what kind of function you are generating.
* The AI panel stays open across reloads and assets (since you're likely to be using it for many things in a single session)
* The sqs example command changes depending on what type of function you are generating.
* The AI panel will no longer close itself when generation completes
* The AI panel becomes disabled if the function is locked, and explains that it needs to be unlocked
Example import function:
```typescript
async function main({ thisComponent }: Input): Promise<Output> {
const …
```
> Add import function generation

- component/init/configs/service.toml
- lib/si-layer-cache/src/hybrid_cache.rs
> feat: make disk admission rate limit configurable

- lib/sdf-server/BUCK
> Remove unnecessary deps in sdf-server's tests

- BUG BOUNTY
- BUG BOUNTY.md
Adds bug bounty to System Initiative's Production Stack
> feat: add bug bounty program

- app/web/src/components/Workspace/CommandModal.vue
- app/web/src/shared/CommandBar.vue
- app/web/src/shared/command.ts
Adding:
- Go to View (by name)
- New View (type the name)
> Feat: adding some view operations to command bar

- .github/workflows/e2e-validation.yml
- .github/workflows/run-api-test.yml
> fixup: API tests failure methods

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
> Fix: don't allow fromBaseChangeSet=true (i.e. deleted) components to move either

- app/docs/src/reference/audit-trail.md
- app/docs/src/reference/index.md
- app/docs/src/reference/vocabulary.md
This PR adds an audit trail reference document and entity-based vocabulary words.
> Add audit trail reference and entity vocab

- app/web/src/components/ComponentConnectionsPanel.vue
> Fix: add schema name to parent dropdown to help differentiate

- app/web/src/components/layout/navbar/Collaborators.vue
- app/web/src/store/views.store.ts
thank you @jobelenus for your help!
> fix(web) - actually navigate to the view a user is on

- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
> BUG-698: re-process children when a component updates, fixes when parentage changes

- app/web/src/store/views.store.ts
> Hotfix: watcher is too aggressive

- lib/si-layer-cache/src/db.rs
This is to help improve the speed at which we start the application when the disk caches are relatively full.
> feat: start all layer_caches in parallel

- app/web/src/api/sdf/dal/views.ts
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/store/views.store.ts
> BUG-697: z-index frames based on size, not parentage. resize parents to contain a larger child

- lib/sdf-server/src/service/v2/management/generate_template.rs
Also ensures we use the func_name in the request.
> feat: format generated code correctly

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramView.vue
- app/web/src/components/ViewCard.vue
- app/web/src/components/layout/navbar/Collaborators.vue
- app/web/src/store/views.store.ts
fixes for BUG-714 and BUG-712
thank you @jobelenus for your help!
> fix(web) - selectView and selection outline bug fixes

- app/web/src/components/layout/navbar/NavbarPanelCenter.vue
> Fix: navbar remembers what view you're in

- app/web/src/store/views.store.ts
> Fix: dont pull people out of the authoring screen because a changeset applies

- app/web/src/store/views.store.ts
> BUG-715: Fix to view initialization that causes missing view nodes and old component nodes

- app/web/src/components/ModelingView/DeleteSelectionModal.vue
> BUG-703: hitting backspace with no selections wrongly pops the delete modal

- app/web/src/components/Ai/GenerateAwsFunctionPanel.vue
- app/web/src/components/AssetCard.vue
- app/web/src/components/AssetEditorHeader.vue
- app/web/src/components/EditingPill.vue
- app/web/src/store/func/funcs.store.ts
> UI improvements to the generate panel

- lib/dal/src/diagram.rs
- lib/sdf-server/src/service/diagram.rs
- lib/sdf-server/src/service/diagram/create_component.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/create_component.rs
We were correctly calling these events in `install_module.rs`, just didn't have them here
> BUG-700: adding WsEvent::FuncUpdated to component created endpoints

- app/web/src/components/ModelingView/TemplateSelectionModal.vue
- app/web/src/components/toasts/CreatingTemplate.vue
- app/web/src/store/components.store.ts
- lib/sdf-server/src/service/v2/management/generate_template.rs
> button on template generated toast to view func code

- app/web/src/App.vue
- app/web/src/store/actions.store.ts
it has served us well but it's the time to remove it
> rip: confetti 

- app/web/src/store/components.store.ts
- app/web/src/store/realtime/realtime_events.ts
- lib/dal-test/src/expected.rs
- lib/dal/src/component.rs
- lib/dal/src/component/frame.rs
- lib/dal/tests/integration_test/frame.rs
- lib/sdf-server/src/service/v2/view/create_component.rs
> BUG-652: send inferred edges along with created component

- lib/dal/src/management/mod.rs
Noticed during the demo that BUG-652 (where the components were not filling in sockets for inferred edges) applied to components created by management funcs as well.
Fixes BUG-705
> fix: send inferred edges on mgmt fn component create

- app/web/src/components/ApprovalPendingModalCard.vue
- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/store/apis.ts
- app/web/src/store/change_sets.store.ts
> Fix: when creating a new change set stay on the view you're on

- app/web/src/components/InsetApprovalModal.vue
> Revert: aggressive window reloading

- app/docs/src/reference/vocabulary.md
> feat(vocab): add *Workspace* to vocabulary

- app/web/src/store/views.store.ts
> Fix: ensure z-index for frames when deleting/updating/adding components

- app/web/src/store/views.store.ts
> fix: must set z-index after view assignment

- .github/workflows/dependency-pr-check.yml
Add a friendly dependency checker to all PR's in si.git repository PRs to keep us squeaky clean.
<div><img src="https://media2.giphy.com/media/fIrbAgjX4Gjqo/200w.gif?cid=5a38a5a2804t1sk90zboam1609uv0jir8aim5arjpui0l2v0&amp;ep=v1_gifs_search&amp;rid=200w.gif&amp;ct=g" style="border:0;height:300px;width:300px"/></div>
> feat: add dependabot on all pull requests

- app/auth-portal/src/components/WorkspaceLinkWidget.vue
- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
Also show workspace URL on a tooltip on the workspaces list
> fix: Auth tokens list on dropdown

- app/web/src/App.vue
- app/web/src/components/AuditLogCell.vue
- app/web/src/components/AuditLogHeader.vue
- app/web/src/components/NoSelectionDetailsPanel.vue
- app/web/src/components/layout/navbar/Collaborators.vue
- app/web/src/components/layout/navbar/Navbar.vue
- app/web/src/components/layout/navbar/NavbarButton.vue
- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/components/layout/navbar/Notifications.vue
- app/web/src/main.ts
- lib/vue-lib/src/design-system/general/Timestamp.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
- lib/vue-lib/src/design-system/panels/ResizablePanel.vue
> feat(web) - moved the pending approvals to the navbar

- third-party/node/turbo/package.json
- third-party/node/turbo/pnpm-lock.yaml
Upgraded via:
```sh
cd third-party/node/turbo
pnpm update turbo --latest
```
> build(deps): upgrade to turbo 2.3.3

- app/auth-portal/src/components/AuthTokenListItem.vue
- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
- bin/auth-api/src/routes/admin.routes.ts
- bin/auth-api/src/routes/auth_token.routes.ts
- bin/auth-api/src/routes/workspace.routes.ts
> fix: Allow non owners to see tokens

- app/web/src/components/ApprovalPendingModalCard.vue
- app/web/src/components/AssetCard.vue
- app/web/src/components/AssetListItem.vue
- app/web/src/components/AuditLogCell.vue
- app/web/src/components/ComponentCard.vue
- app/web/src/components/EditingPill.vue
- app/web/src/components/InsetApprovalModal.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
> various truncation fixes!

- CONTRIBUTORS.md
- app/docs/src/tutorials/creating-components.md
- app/docs/src/tutorials/editing-components-and-contributing.md
- app/docs/src/tutorials/working-with-components.md
> Fix components

- lib/dal-test/src/test_exclusive_schemas/legos/small.rs
- lib/dal/src/func/binding/management.rs
- lib/dal/src/management/mod.rs
- lib/dal/tests/integration_test/management.rs
Adds the ability to remove a view with a management func, and to remove a component from a view with a management func.
> feat: remove views and components from views in mgmt fns

- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
- app/auth-portal/src/store/authTokens.store.ts
- bin/auth-api/src/routes/auth_token.routes.ts
- lib/vue-lib/package.json
- lib/vue-lib/src/design-system/forms/VormInput.vue
- lib/vue-lib/src/design-system/forms/helpers/form-validation.ts
- pnpm-lock.yaml
> form to create API token now requires an expiration time string

- app/docs/src/roadmap/index.md
Fuse FS isn't in this list until I blog post it next week
> chore(docs): Updating the roadmap based on current opportunities

- app/web/src/components/Actions/ActionsList.vue
- app/web/src/components/ChangesPanelHistory.vue
- app/web/src/components/ChangesPanelProposed.vue
- app/web/src/store/actions.store.ts
> Feat: users can see actions queue'd on HEAD while in a changeset

- app/web/src/store/views.store.ts
> Tidy: small bit of views cleanup

- app/web/src/components/ModelingDiagram/DiagramView.vue
> Upgrade to Diagram View Objects font size stepping

- app/auth-portal/src/components/MemberListItem.vue
- app/auth-portal/src/pages/WorkspaceDetailsPage.vue
- bin/auth-api/src/routes/auth_token.routes.ts
- bin/auth-api/src/routes/workspace.routes.ts
Without this, the workspace owner becomes the single point of failure
> fix(auth-portal): Allow workspace approvers to invite users

- app/web/src/components/AssetDetailIntrinsicInput.vue
- app/web/src/components/DetailsPanelMenuIcon.vue
- app/web/src/store/func/funcs.store.ts
> FuncUpdated should not navigate. Also icon menu button disabling when locked

- app/web/src/store/asset.store.ts
- app/web/src/store/components.store.ts
- app/web/src/store/func/funcs.store.ts
- app/web/src/store/realtime/realtime.store.ts
- app/web/src/store/views.store.ts
> Fix: to metadata request_ulid coming over the wire

- bin/auth-api/src/routes/workspace.routes.ts
- bin/auth-api/src/services/workspaces.service.ts
This is the format of the new posthog event so that we can send a transactional email
> feat(auth-api): Deploy new posthog event for emails

- bin/si-fs/src/main.rs
- lib/dal/src/change_set/status.rs
- lib/sdf-server/src/service/change_set/create_change_set.rs
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/fs.rs
- lib/si-filesystem/src/client.rs
- lib/si-filesystem/src/inode_table.rs
- lib/si-filesystem/src/lib.rs
- lib/si-frontend-types-rs/src/fs.rs
- lib/si-frontend-types-rs/src/lib.rs
Also adds the /api/v2/workspaces/:workspace_id/fs API route.
> feat: si-fs can list all schemas, locked & unlocked variants

- app/web/src/components/AssetDetailIntrinsicInput.vue
- app/web/src/components/AssetDetailsPanel.vue
> fix(web) - BUG-729, multiple clicks, recomputing unmounting

- app/web/src/components/ChangesPanelProposed.vue
> BUG-744: logs show on head

- app/web/src/components/ComponentDetails.vue
> BUG-743: adding a message for a selected component that is about to delete on HEAD

- .github/workflows/run-api-test.yml
[Working run](https://github.com/systeminit/si/actions/runs/12832498103)
> fix: api tests need to use latest deno

- bin/si-gen-cloud-control/src/cfDb.ts
- bin/si-gen-cloud-control/src/commands/generateSiSpecDatabase.ts
- bin/si-gen-cloud-control/src/errors.ts
- bin/si-gen-cloud-control/src/spec/props.ts
- bin/si-gen-cloud-control/src/spec/sockets.ts
- bin/si-gen-cloud-control/test/cfdb_test.ts
- bin/si-gen-cloud-control/test/spec_test.ts
> [wip]: add basic socket generation from cf

- app/web/src/components/AssetFuncAttachModal.vue
> BUG-740: attach new func closes modal

- lib/si-layer-cache/tests/integration_test/db/workspace_snapshot.rs
> fix: increase sleep for flakey test in CI

- bin/lang-js/BUCK
- bin/si-gen-cloud-control/BUCK
- bin/si-gen-cloud-control/cloud-control-funcs/aws::ec2::vpcScaffold_20250110040411661264418.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlCodeGenUpdate.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlCreate.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlCreateAction.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlDelete.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlEc2VpcFieldMap.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlImport.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlRead.ts
- bin/si-gen-cloud-control/cloud-control-funcs/awsCloudControlResourceupdate.ts
- bin/si-gen-cloud-control/cloud-control-funcs/discover.ts
- bin/si-gen-cloud-control/src/cfDb.ts
- bin/si-gen-cloud-control/test/cfdb_test.ts
- bin/si-gen-cloud-control/test/spec_test.ts
- bin/si-gen-cloud-control/test/test-files/aws-ec2-vpc.json
- bin/si-gen-cloud-control/test/test-files/aws-waf-webacl.json
- deno.json
> feat: add buck2 to the generator

- bin/si-gen-cloud-control/src/pipeline-steps/generateAssetFuncs.ts
- bin/si-gen-cloud-control/src/spec/siFuncs.ts
- bin/si-gen-cloud-control/src/specPipeline.ts
> Generate subprops on asset func

- bin/si-gen-cloud-control/src/pipeline-steps/generateAssetFuncs.ts
> Generate sockets and resource value on asset func

- bin/si-gen-cloud-control/src/commands/generateSiSpecs.ts
- bin/si-gen-cloud-control/src/pipeline-steps/generateLeafFuncs.ts
- bin/si-gen-cloud-control/src/spec/funcs.ts
> feat: add code generation funcs

- bin/si-gen-cloud-control/src/cfDb.ts
- bin/si-gen-cloud-control/src/commands/generateSiSpecs.ts
- bin/si-gen-cloud-control/src/pipeline-steps/generateManagementFuncs.ts
- bin/si-gen-cloud-control/src/spec/funcs.ts
> feat: add default mgmt funcs

- bin/si-gen-cloud-control/src/pipeline-steps/generateAssetFuncs.ts
- bin/si-gen-cloud-control/src/spec/props.ts
> feat: set create only flag on relavent props

- lib/sdf-server/src/service/v2/fs.rs
- lib/si-filesystem/src/async_wrapper.rs
- lib/si-filesystem/src/client.rs
- lib/si-filesystem/src/command.rs
- lib/si-filesystem/src/inode_table.rs
- lib/si-filesystem/src/lib.rs
Uninstalled schemas can now be installed by touching the INSTALLED file in the schema folder
> feat: install schemas by touching INSTALLED

- app/web/src/components/ModelingDiagram/diagram_constants.ts
- app/web/src/components/ModelingDiagram/diagram_types.ts
- bin/lang-js/deno.json
- bin/lang-js/src/function_kinds/management.ts
- bin/lang-js/src/sandbox.ts
- bin/lang-js/src/sandbox/diagram_constants.ts
- bin/lang-js/src/sandbox/layout.ts
- bin/lang-js/src/sandbox/template.ts
- bin/lang-js/tests/sandbox/layout_test.ts
- deno.lock
- lib/cyclone-client/src/client.rs
- lib/cyclone-core/src/management.rs
- lib/dal/src/func/backend/management.rs
- lib/dal/src/func/binding/management.rs
- lib/dal/src/management/prototype.rs
- lib/veritech-client/tests/integration.rs
Users can write management functions with logical layouts by specifying frames and rows.
You can write a management function like this! **Note**: we know the number of sockets for a given variant, too!
```
async function main({
currentView,
thisComponent,
components,
variantSocketMap,
}: Input): Promise < Output > {
const templateName = _.get(
thisComponent,
["properties", "si", "name"],
"unknown",
);
const numVPC = parseInt(_.get(thisComponent, ["properties", "domain", "# VPC"]))
const numSubnet = parseInt(_.get(thisComponent, ["properties", "domain", "# Subnet"]))
const vpcs = new Array(numVPC)
const NUM_PER_ROW = 3;
const vars = template.variables(thisComponent);
const specs: Output["ops"]["create"][string][] = [];
const frame = layout.initialFrame("root", 25, 200);
for (const [idx, _] …
```
> feat: add layout and template helpers to lang-js

- bin/si-gen-cloud-control/src/cfDb.ts
- bin/si-gen-cloud-control/src/commands/generateSiSpecs.ts
- bin/si-gen-cloud-control/src/pipeline-steps/addDefaultPropsAndSockets.ts
- bin/si-gen-cloud-control/src/pipeline-steps/generateSocketsFromDomainProps.ts
- bin/si-gen-cloud-control/src/spec/props.ts
- bin/si-gen-cloud-control/src/spec/sockets.ts
- bin/si-gen-cloud-control/src/specPipeline.ts
> Generate region socket

- app/web/src/components/ComponentDetailsManagement.vue
- app/web/src/components/Management/ManagementHistoryCard.vue
- app/web/src/components/ManagementRunPrototype.vue
- app/web/src/components/StatusIndicatorIcon.vue
- app/web/src/store/func_runs.store.ts
- app/web/src/store/management_runs.store.ts
> Feat: show the mgmt history in the panel where you can run mgmt functions

- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/generateAssetFuncs.ts
- bin/clover/src/pipeline-steps/generateIntrinsicFuncs.ts
- bin/clover/src/pipeline-steps/generateSocketsFromDomainProps.ts
- bin/clover/src/pipeline-steps/generateSubAssets.ts
- bin/clover/src/spec/props.ts
- bin/clover/src/spec/siFuncs.ts
- bin/clover/src/spec/sockets.ts
- bin/clover/src/specPipeline.ts
- deno.lock
> feat: generate sub-assets from specs

- lib/sdf-server/src/service/v2/management/generate_template.rs
This upgrades the template generation to create templates that follow the new idempotent template and view variables patterns.
* Each component gets broken out into its own variable
* Pushed to a spec array
* Synced with `component sync`
* Each component gets an additional 'Push Vars to Views' mgmt function that does variable push-down
> feat: update template generator to new pattern

- lib/sdf-server/src/service/v2/fs.rs
- lib/si-filesystem/src/client.rs
- lib/si-filesystem/src/lib.rs
- lib/si-frontend-types-rs/src/fs.rs
`mdkir schema-name` in the schemas folder will create a new schema
> feat(si-fs): create schemas with mkdir

- bin/clover/existing-packages/.gitignore
- bin/clover/src/cli.ts
- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/updateSchemaIdsForExistingSpecs.ts
- bin/clover/src/spec/props.ts
- bin/clover/src/specPipeline.ts
- bin/clover/src/specUpdates.ts
- deno.lock
> feat: if a schema exists, new specs use existing schema ids

- lib/sdf-server/src/service/v2/view/paste_component.rs
> Fix: copy and paste will now work on non-default views

- bin/clover/src/cfDb.ts
- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/generateSubAssets.ts
- bin/clover/src/spec/props.ts
- bin/clover/src/specPipeline.ts
- Deal with OneOf properties
- Deal with anyOf properties
- Deal with empty properties from CF
> fix(clover): Build all assets

- app/web/src/components/DiagramOutline/DiagramOutline.vue
- app/web/src/store/views.store.ts
Been trying to recreate BUG-720 for a fix, haven't been able to yet. But these are still solid changes
Testing steps:
- Create changeset and make a new view
- Add Cred, Region, Key Pair, and EC 2 Instance.
- Apply to HEAD and make sure resources are created
- Created a changeset, move the 4 components to DEFAULT
- Delete the View (left rail, ellipsis, delete)
- Apply to HEAD
> Tidying: some less than ideal patterns around diagram outliner and view deletion

- lib/dal/src/workspace_snapshot/node_weight/view_node_weight/v1.rs
- lib/dal/tests/integration_test/node_weight/view.rs
When removing a View, we make sure that it isn't the only View that has Geometry for any of the Components in it. We weren't taking into account that a Component might be moved from only being in the View we're removing to being in another View (or multiple other views).
We now track which Components got new Geometry for Views other than the one being removed, and if we see that the View being removed had the only Geometry for the Component, we see if it is in the list of Components that are getting new Geomerty. If it is in that list, then we allow the removal to proceed as we won't be orphaning the Component from all Views.
> Check to see if Components have been moved to other Views when removing a View

- app/web/src/store/components.store.ts
> Fix: add a timeout for the template creation toast

- app/web/src/store/components.store.ts
> Fix: a better toast fix for never-ending spinner

- app/web/src/components/AssetListPanel.vue
- app/web/src/store/components.store.ts
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/module.store.ts
- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/addSignatureToCategoryName.ts
> feat(clover): Hide assets behind feature flag

- lib/dal/src/management/mod.rs
Testing steps:
- brit's remove edge fn on the VPC Template
> Fix: actually publish edge removal ws event

- lib/dal/src/cached_module.rs
- lib/sdf-server/src/migrations.rs
Batch cached module loading to try to put less pressure on the module index on startup
> feat: batch cached module installs

- app/web/src/components/Actions/ActionCard.vue
- app/web/src/components/ApplyChangeSetButton.vue
- app/web/src/components/ApprovalFlowModal.vue
- app/web/src/components/InsetApprovalModal.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/auth.store.ts
- lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
> InsetApprovalModal improvements/fixes!

- bin/clover/src/cfDb.ts
- bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenCreate.ts
- bin/clover/src/cloud-control-funcs/code-gen/awsCloudControlCodeGenUpdate.ts
- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/addSignatureToCategoryName.ts
- bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts
- bin/clover/src/pipeline-steps/generateSocketsFromResourceProps.ts
- bin/clover/src/spec/sockets.ts
> feat: arn sockets, code gen, normalizeArrays

- bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts
- bin/clover/src/pipeline-steps/updateSchemaIdsForExistingSpecs.ts
Catches cases where we were creating duplicate sockets
> fix: duplicate sockets

- app/web/src/components/FuncEditor/ManagementDetails.vue
> fix(web): Ensure that we can search the managed assets panel

- bin/clover/src/pipeline-steps/generateAssetFuncs.ts
When we create the schema spec, for schemas that consume secrets, we must add a prop and socket with the correct configuration.  However, we provide abstraction over this in the asset definition function, so we must detect when secret props are being used, build a `SecretProp`, ensuring we don't add the corresponding `InputSocket` as the `SecretProp` handles adding both the prop and the socket.
> fix(clover): add secret props in asset definition func

- bin/hoist/src/main.rs
```
Building modules list...
🟰 1 modules have matching hashes and will be skipped
🔼 63 modules exist and will be updated
➕ 6 new modules will be uploaded
Would you like to continue? (y/n)
```
```
🟰 1 modules have matching hashes and will be skipped
🔼 0 modules exist and will be updated
➕ 0 new modules will be uploaded
No new modules or update, nothing to do!
```
```
Building modules list...
🟰 0 modules have matching hashes and will be skipped
🔼 1 modules exist and will be updated
➕ 0 new modules will be uploaded
Would you like to continue? (y/n)
y
[▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸] 1/1 (0s)
✨ All uploads complete!  
```
> feat(hoist): friendly output, pre-compute module state

- app/web/src/App.vue
- app/web/src/components/AttributesPanel/TreeFormItem.vue
- app/web/src/components/ComponentConnectionsPanel.vue
- app/web/src/components/InsetApprovalModal.vue
- app/web/src/components/ModelingDiagram/DiagramCursor.vue
- app/web/src/components/UserSelectMenu.vue
- lib/vue-lib/src/design-system/general/Toggle.vue
- lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue
- lib/vue-lib/src/design-system/modals/Modal.vue
- lib/vue-lib/src/design-system/utils/floating_vue_utils.ts
https://github.com/user-attachments/assets/08e4b5f9-8569-44de-a35b-481a6711b952
- InsetApprovalModal overflow issues fixed
- TruncateWithTooltip bug fixed, minor improvements
- Better prop documentation tooltips
- `DropdownMenuButton` replaces `<select>` in the AttributesPanel, now you can search options
- Diagram cursor truncation fix
- Connections panel parent dropdown check fix, wider input option added
- `DropdownMenuButton` can now align on the right edge of an anchor
- Fixed Toggle getting squished by flex
- Modal title line limit to prevent long dynamic Modal titles from breaking Modal
> many small UI fixes and improvements!

- lib/sdf-server/src/service/v2/fs.rs
Errors in the regen will not fail the route now, so saves will succeed even if the asset func is invalid.
> fix(si-fs): don't fail asset def save if regen fails

- lib/dal/src/func/binding/management.rs
The incoming connections changes broke the generated typescript type for management functions whenever that function manages a schema with a space in the name. This fixes that
> fix(dal): keys in type map must be quoted and escaped

- lib/dal/src/job/definition/compute_validation.rs
- lib/dal/src/job/definition/dependent_values_update.rs
- lib/pinga-server/src/handlers.rs
<div><img src="https://media1.giphy.com/media/IokAQCByJS254Dmw6f/200w.gif?cid=5a38a5a25vubie6ay78djde9i4dtii4rzul7h2gr2pkxarjj&amp;ep=v1_gifs_search&amp;rid=200w.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/channel/BenJammins/">BenJammins</a> on <a href="https://giphy.com/gifs/calculator-calculating-calculated-IokAQCByJS254Dmw6f">GIPHY</a></div>
> fix(pinga): This fixes up metrics so it doesn't look like we've got runaway jobs/unexecuted funcs by inc/dec counters in the right spots

- bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts
- bin/clover/src/spec/sockets.ts
Fixes the bug cloudlife saw today when trying to connect bucket name
> fix(Clover): output sockets were not getting extra annotations

- bin/clover/src/cfDb.ts
- bin/clover/src/spec/props.ts
- bin/clover/src/specPipeline.ts
Also added some comments  document some obscure code
> fix(Clover): make json objects use textarea widgets

- app/auth-portal/src/components/MemberListItem.vue
- app/auth-portal/src/pages/WorkspaceDetailsPage.vue
- app/auth-portal/src/store/feature_flags.store.ts
These are currently available to all users
> chore(auth-portal): Cleanup AuthPortal feature flags

- Cargo.lock
- Cargo.toml
- bin/si-fs/src/main.rs
- lib/sdf-server/src/service/v2/fs.rs
- lib/sdf-server/src/service/v2/fs/bindings.rs
- lib/si-filesystem/BUCK
- lib/si-filesystem/Cargo.toml
- lib/si-filesystem/src/client.rs
- lib/si-filesystem/src/command.rs
- lib/si-filesystem/src/inode_table.rs
- lib/si-filesystem/src/lib.rs
- lib/si-frontend-types-rs/src/fs.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
Types for all functions!
Uses a tsconfig.json to ensure that types are compiled per-function,
instead of across the entire fuse filesytem.
With dashmap, type compilation is much faster for the whole workspace
> feat(si-fs): types for all functions!

- lib/dal/src/change_set.rs
- lib/dal/src/context.rs
- lib/dal/src/workspace_snapshot.rs
- lib/rebaser-server/src/rebase.rs
<div><img src="https://media4.giphy.com/media/xT5LMRDKQ6P7GTKnDO/giphy.gif?cid=5a38a5a2zhpgcmrrq7ntf38jwscznzbr2xbxs84qlj4p4bd6&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:226px;width:300px"/><br/>via <a href="https://giphy.com/gifs/season-7-the-simpsons-7x13-xT5LMRDKQ6P7GTKnDO">GIPHY</a></div>
> chore(dal,rebaser): add some tracing to see what's going on when rebases get slower

- lib/dal/src/component.rs
I noticed during load testing that we enqueue validations jobs for every attribute value on a newly created component, which most end up being no-ops and a bunch of work to ultimately do nothing. Just adding a check to see if they exist before enqueuing them. 
<div><img src="https://media2.giphy.com/media/fVPMdBImgrC1SueRCS/200w.gif?cid=5a38a5a2yvm7s1nin2ik5j5e4psg72t839zw5t9b53id30ke&amp;ep=v1_gifs_search&amp;rid=200w.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/cbc/">CBC</a> on <a href="https://giphy.com/gifs/cbc-schitts-creek-fVPMdBImgrC1SueRCS">GIPHY</a></div>
> fix(dal): when creating new attribute values for a new component, only enqueue validations if they're configured for that value

- bin/auth-api/package.json
- pnpm-lock.yaml
Fixes critical vuln in Koa, used within the auth api https://github.com/systeminit/si/security/dependabot/380
> fix: koa CVE-2025-25200

- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/prettifySocketNames.ts
Make sure socket names have spaces instead of being pascal case
> feat(clover): Prettify socket names

- app/web/src/components/modules/ModuleListPanel.vue
- app/web/src/store/module.store.ts
- lib/sdf-server/src/service/module.rs
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/module.rs
- lib/sdf-server/src/service/v2/module/install_from_file.rs
> feat(sdf, web): Allow devs to install specs directly

- bin/clover/src/pipeline-steps/prettifySocketNames.ts
Packages aren't uploading right now, so we can't see the beautiful new socket names! The issue was that props that hook up to an input socket were referencing the old names without spaces, while the sockets themselves had spaces added.
Test: uploaded a couple of assets with @vbustamante 's beautiful new module uploader and dragged them onto the canvas. Spaces galore!
> fix(clover): Hook up inputs to proper space-separated socket names

- app/web/src/components/DiagramOutline/DiagramOutlineNode.vue
- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramHelpModal.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/DiagramView.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/store/feature_flags.store.ts
https://github.com/user-attachments/assets/6ecc5239-d0c4-47b7-b6e6-4a12184c5e52
> toggle the diagram details by pressing Z

- bin/lang-js/src/execution.ts
stream `console.log` and `console.error` from lang-js as they occur in the function execution. This should resolve issues with logs not being displayed correctly in the web client as it more closely matches the pre-deno behavior.
I confirmed that this results in us pushing the console.log lines one by one across nats to whomever is listening on the otherside and that long function executions result in the entirety of the log being present on first glance
> feat: stream console messages from func executions

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/DiagramView.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_constants.ts
https://github.com/user-attachments/assets/56fd3551-a33a-4dd3-a0a9-f7f45bca1359
> 3 modes for toggling details on diagram

- bin/clover/inferred.json
- bin/clover/src/pipeline-steps/addInferredEnums.ts
- bin/clover/src/spec/inferred.ts
Intended to add as part of the last one.
Also adds two files that appear not to have been added in the original PR :/
> feat(clover): Add inferred.json so it doesn't need to be generated

- app/web/src/api/sdf/dal/component.ts
- app/web/src/api/sdf/dal/schema.ts
- app/web/src/components/ComponentCard.vue
- app/web/src/components/ModelingDiagram/diagram_types.ts
- lib/dal/src/component.rs
- lib/si-frontend-types-rs/src/component.rs
- lib/vue-lib/src/design-system/icons/icon_set.ts
https://github.com/user-attachments/assets/e8729a76-c3b0-43a1-a5b2-0f7906526c24
> feat(web): Add a link to the schema docs for an asset

- app/auth-portal/src/lib/validations.ts
- app/auth-portal/src/pages/BillingPage.vue
- app/auth-portal/src/pages/ProfilePage.vue
- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
- app/auth-portal/src/pages/WorkspaceDetailsPage.vue
- bin/auth-api/src/lib/validation-helpers.ts
- bin/auth-api/src/routes/auth_token.routes.ts
- bin/auth-api/src/routes/user.routes.ts
- bin/auth-api/src/routes/workspace.routes.ts
This also prevents by passing the UI and going straight to the API
> feat(auth-stack): Prevent XSS based attacks on text inputs 

- bin/si-fs/src/main.rs
Also adds env var options for the parameters
> feat(si-fs): Add a default for the endpoint url

- prelude-si/artifact/promote.py
> fix(ci): add `binary` as an artifact variant in `promote.py`

- bin/clover/src/cloud-control-funcs/management/awsCloudControlDiscover.ts
This updates the discovery function to allow for refining the discovered resources by pre-configuring the component before you call discovery. It does a relatively naive deep equality match. For example, if you configure a VPC ID for a Subnet, then discover all subnets, it will return only the VPC IDs for that subnet.
In addition, it will replicate all connections the component you ran discovery from to the discovered assets - so they will get credentials, regions, etc.
Note that this doesn't currently work well if the component uses a parent to infer the connections, because that data is not available yet in management functions.
> feat: allow for refining discovery operations

- .github/workflows/run-garbage-collection.yml
- component/toolbox/scripts/snapshot-garbage-collection
- component/toolbox/scripts/supporting-funcs/ssm-funcs.sh
Adds the github workflow and toolbox item for running the garbage collection on a real SDF environment
> feat: add CI + toolbox for garbage collection

- app/auth-portal/src/pages/WorkspaceDetailsPage.vue
This is causing issues for other users of the workspace so we need to relook at this
> fix(auth-portal): Temp stop being able to set favourite, default and hidden

- app/web/package.json
- app/web/src/main.ts
- pnpm-lock.yaml
> FE: Turning on source maps and decoding them in error reporting

- Cargo.lock
- lib/naxum/BUCK
- lib/naxum/Cargo.toml
- lib/naxum/src/middleware/ack/maintain_progress.rs
- lib/naxum/src/serve.rs
<div><img src="https://media4.giphy.com/media/YS8c0Z7in21AM4A2AR/giphy.gif?cid=5a38a5a2ybs854k8e31359k6o2r7y373hgea1nbtb7raeior&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/abcnetwork/">ABC Network</a> on <a href="https://giphy.com/gifs/abcnetwork-the-good-doctor-abc-doctorabc-YS8c0Z7in21AM4A2AR">GIPHY</a></div>
> chore(naxum): Bump some events from trace to info and add metrics for messages being pulled/processed

- app/web/src/api/sdf/dal/property_editor.ts
- app/web/src/assets/static/editor_typescript.txt
- app/web/src/components/AttributesPanel/TreeFormItem.vue
- app/web/src/store/component_attributes.store.ts
- bin/lang-js/src/asset_builder.ts
> Revert "fix(web): Ensuring that we can deal with JSON.Objects in propSpecs"

- lib/dal/tests/integration_test/pkg/mod.rs
This adds a second level object to the prop order round trip test. There are some codepaths that treat top-level and nested props differently.
> chore(sdf): test round-trip prop order for nested objects

- app/web/vite.config.ts
> Turn on source maps

- bin/clover/inferred.json
- bin/hoist/src/main.rs
> fix: matching logic for new modules

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
The ELBv2 Target needs to accept an instance ID
> bug: lb target needs ec2 instance ids

- bin/hoist/src/commands.rs
- bin/hoist/src/diff.rs
- bin/hoist/src/main.rs
> feat(hoist): Generate changelogs!

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts
- bin/clover/src/pipeline-steps/generateSubAssets.ts
- bin/clover/src/spec/sockets.ts
- bin/hoist/src/diff.rs
> feat(clover): extend sockets to include type definitions

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/pipeline-steps/createInputSocketsAcrossAssets.ts
Ensure arns nested in objects get arn sockets
> fix(clover): create arn sockets for object members

- app/web/src/main.ts
- app/web/vite.config.ts
> Functional (but not great) source map following, and some vue internal component data

- lib/sdf-server/src/service/v2/func/binding/create_binding.rs
> fix(sdf): Add a WsEvent when attaching an attribute function to a schema

- lib/dal/src/component.rs
> BUG-778: upgrade component wsevent missing parent, b/c we send it too soon

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
> fix(clover): Add specific override for AWS::EC2::VPCEndpoint

- lib/si-data-nats/src/lib.rs
This PR calms down NATS event callback logging to trace level or metrics at most. The logs can be spammed in the millions depending on the scenario, so we should only trace log these (or not at all). The metrics also reset to 0 upon client creation.
Relevant PR: #5566
> Calm down NATS event callback logging

- bin/clover/src/cloud-control-funcs/qualifications/awsPermissionsSimulation.ts
- bin/clover/src/pipeline-steps/addDefaultPropsAndSockets.ts
- bin/clover/src/spec/funcs.ts
Check the permissions defined by the spec and warn if the cred lacks permissions.
```
read: [OK] All granted!
create: [WARN] Missing permissions:
ec2:CreateSecurityGroup
ec2:RevokeSecurityGroupEgress
ec2:AuthorizeSecurityGroupEgress
ec2:AuthorizeSecurityGroupIngress
ec2:CreateTags
update: [WARN] Missing permissions:
ec2:RevokeSecurityGroupEgress
ec2:RevokeSecurityGroupIngress
ec2:AuthorizeSecurityGroupEgress
ec2:AuthorizeSecurityGroupIngress
ec2:CreateTags
ec2:DeleteTags
list: [OK] All granted!
delete: [WARN] Missing permissions:
ec2:DeleteSecurityGroup
Output: {
"protocol": "result",
"status": "success",
"executionId": "01JNHCP84WDKF5E9N8ZEXKK29F",
"data": {
"result": "warning",
"message": "Missing permissions: ec2:CreateSecurityGroup, ec2:RevokeSecurityGroupEgress, …
```
> feat(clover): add qualification for checking permissions.

- lib/dal/src/component.rs
Currently, autoconnect only succeeds if all connections that could be created get created successfully. However, there are times when creating a connection fails (for example if it would create a graph cycle). This change ensures a failure like that doesn't prevent the other connections from being created.
<div><img src="https://media2.giphy.com/media/8PjBOhjHqH9t9eqkdh/200.gif?cid=5a38a5a2f6cms2pt8flevrbtdskcqdqd6cig5g5nr3rpw6yz&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:128px;width:300px"/><br/>via <a href="https://giphy.com/1091/">1091</a> on <a href="https://giphy.com/gifs/1091-movie-zoo-8PjBOhjHqH9t9eqkdh">GIPHY</a></div>
> fix(dal): Failing to create a connection shouldn't fail creating any connections

- bin/clover/src/cloud-control-funcs/overrides/AWS::EC2::LaunchTemplate/import.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/spec/funcs.ts
> Revert "feat(clover): allow overriding funcs per spec"

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
> more diagram render cache fixes

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Adds input sockets for VPCCidrBlock to work with IPAM Pools.
* Ipv4IpamPoolId
* Ipv6IpamPoolId
> feat: VPCCidrBlock updates

- .github/workflows/asset-compare.yml
- .github/workflows/asset-push.yml
> feat: /diff asset changes in a PR

- .github/workflows/asset-compare.yml
These things are basically untestable
> fix: /diff comment body incorrect

- Cargo.lock
- Cargo.toml
- component/nats/BUCK
- lib/si-data-nats/src/lib.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
> build(deps): upgrade async-nats client & NATS server

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Adds the ability to set KMS keys for EBS Volumes and Fargate tasks with a socket.
> feat: asset updates for ECS

- .github/workflows/asset-push.yml
- Cargo.lock
- bin/hoist/BUCK
- bin/hoist/Cargo.toml
- bin/hoist/src/main.rs
> feat(hoist): add retry with backoff to uploads

- .github/workflows/asset-diff.yml
- .github/workflows/asset-push.yml
- lib/si-pkg/src/pkg/socket.rs
> fix(si-pkg): Don't delete socket data when converting siPkg to spec

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
> fix(web) - bug 817, rename view cache bug

- bin/auth-api/src/services/workspaces.service.ts
Fixes CVE report of privilege escalation
> fix(auth-api): Prevent an owner being removed from the workspace by the API

- .github/workflows/asset-compare.yml
- .github/workflows/asset-push.yml
Also don't auto push on changes to si-pkg, since we may need to redeploy module index
> fix(hoist): use right branch for /diff on PR

- app/web/src/components/AttributesPanel/AttributesPanel.vue
- app/web/src/components/AttributesPanel/TreeFormItem.vue
> fix(web) - UI fixes to AttributesPanel, bug 784

- bin/clover/inferred.json
> fix(clover): AI added incorrect ACL entries to S3::Bucket

- lib/si-pool-noodle/src/instance/cyclone/local_uds.rs
> chore(cyclone): add a named prefix to all cyclone server domain sockets

- lib/si-firecracker/src/firecracker.rs
- prelude-si/rootfs/rootfs_build.sh
> wip(cyclone): disable vsock forwarder

- app/docs/src/tutorials/getting-started.md
a minor correction to fix a broken link to the vocabulary page.
> link-update

- lib/si-firecracker/src/scripts/firecracker-setup.sh
<div><img src="https://media2.giphy.com/media/gVeHZmgpGWAcltpDO6/giphy.gif?cid=5a38a5a249hg0msdhr4zyamwjr1thiggbhdz9ay3hihz3uss&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/></div>
> fix: make cpu quota across all cpus

- lib/si-firecracker/src/firecracker.rs
- lib/si-firecracker/src/scripts/firecracker-setup.sh
<div><img src="https://media1.giphy.com/media/LUTttH88jx5Fr4gHfz/giphy.gif?cid=5a38a5a2a78dzihntq34rjbmefvnni3d307pd6kn4h3mnivh&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:249px;width:300px"/></div>
> fix: adopt children of veritech

- lib/dal/src/component.rs
<div><img src="https://media1.giphy.com/media/BRB7gSOKtQpbRbYUZ1/giphy.gif?cid=5a38a5a2hc0qoj4yn0ojh7q0km2lkxxzf8ykfrks51y10f4v&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:251px;width:300px"/><br/>via <a href="https://giphy.com/theoffice/">The Office</a> on <a href="https://giphy.com/gifs/theoffice-episode-18-the-office-tv-BRB7gSOKtQpbRbYUZ1">GIPHY</a></div>
> hotfix(dal): Return management sockets for components

- .github/workflows/deploy-stack.yml
We are in the middle of some cgoup changes that we want to soak in other environments before deploying to prod
> chore(ci): Temp prevent veritech from deployment

- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
> feat(web): Filter out connections on connections menu

- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
> feat(web): Show socket paths on connections menu

- app/web/cypress.config.ts
- app/web/vite.cypress.ts
`npx cypress run --spec "cypress/e2e/workspace-management/**"` now works
> Cypress isnt working with vite config changes, using older config values

- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
> feat(web): Add codeviewer to connections menu

- lib/dal/src/prop.rs
- lib/dal/src/workspace_snapshot/traits/prop.rs
Let's see if the tokio reactor blocking is an issue for us here ...
> fix(sdf): Move ts_type() to slow_rt

- lib/dal/src/func/runner.rs
- lib/si-layer-cache/src/db/workspace_snapshot.rs
Reverting some of the noise from
https://github.com/systeminit/si/pull/5643/files
Ref for usage uplift from 12th March:
https://ui.honeycomb.io/system-initiative/environments/production/datasets/rebaser/overview
> chore: tone down some spans bumped by PR-5642

- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/workers/webworker.ts
> Put the whole bifrost behind the feature flag

- app/web/src/components/AssetPalette.vue
- app/web/src/store/components.store.ts
- lib/dal/src/materialized_view.rs
- lib/dal/src/schema/variant.rs
- lib/dal/src/schema/variant/leaves.rs
- lib/si-frontend-types-rs/src/checksum.rs
- lib/si-frontend-types-rs/src/lib.rs
- lib/si-frontend-types-rs/src/reference.rs
- lib/si-frontend-types-rs/src/schema_variant.rs
- lib/si-frontend-types-rs/src/view.rs
> Asset List on Modeling Diagram now uses the bifrost

- app/auth-portal/package.json
- app/web/package.json
- lib/vue-lib/package.json
- pnpm-lock.yaml
Fixes: https://github.com/systeminit/si/security/dependabot/391
Fixes: https://github.com/systeminit/si/security/dependabot/395
> chore(deps): Upgrade Vite version

- app/web/package.json
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- pnpm-lock.yaml
> Performance improvements for the floating connections menu

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Tested by importing updated AWS::EC2::Instance.json spec:
> fix: add user data input socket to ec2 instance

- lib/dal/src/job/definition/dependent_values_update.rs
This fixes a bug where the component's metadata gets stale in the pinia stores (namely, the values for component's sockets, which were seemingly never reactively updated).
The core need here is to ensure the new connections panel is reactive, and this ensures the data is accurate HOWEVER there's still something up with the component, so while we don't need to reload to see the updated values, we do need to close/re-open the menu. Spinning that off as a separate PR. 
Tested this by creating components/modifying them and seeing the new WS Event fire after DVU completes, and seeing we don't need to reload to get the latest data. 
<div><img src="https://media3.giphy.com/media/UTAOQSxyppPneBswyu/giphy.gif?cid=5a38a5a2ldrfvx2r0dg0vobrtwuky8iooswhgba25rms6560&amp;ep=v1_gifs_search&amp;rid=giphy.g …
> fix(dal): Fire component updated during dependent values update so clients are aware

- app/web/src/components/AssetFuncAttachModal.vue
- app/web/src/components/FuncEditor/ActionDetails.vue
Also allow a user the ability to build an update function rather than always specifying a function is a manual function
> feat(web): Expose when a function is an update function

- lib/edda-server/src/change_set_processor_task.rs
This PR standardizes edda request spans based on what works it needs to do.
> Standardize edda request spans

- lib/veritech-client/src/lib.rs
Integration tests are timing out sometimes right now, because we don't close out the output-forwarding tasks when we try to shut down. This causes output forwarders to shut down when the one receiving the output shuts down (because they will drop the `Receiver`).
> fix(sdf): Close output forwarder tasks when callers stop listening

- lib/veritech-server/src/server.rs
Splits the nats client in twain, making one for jetstream and one for replying inside of function handlers. This is a workaround for our friend VERIDEATH. Tests have shown that we no longer lockup when the nats client is spamming trace logs, implying that the slowdown is allowing whatever internals to drain correctly. Splitting into two clients helps ensure that we aren't crushing the client under the weight of logs and function executions.
It should be noted that this is  ultimately a workaround. Given the right conditions and under the right amount of load, I suspect that this issue will once again rear its ugly head. A change to the nats client itself feels like the more correct fix. That said, there are no obvious downsides to this approach, so it seems safe enough to try.
> feat(veritech): split jetstream and reply into two nats clients

- app/web/vite.config.ts
I think maybe heimdall also needs to have the headers
> One more attempt to get the coop/coep headers right

- app/web/vite.config.ts
> Fix: I did the rollup chunks wrong

- app/web/vite.config.ts
> Build chunks no longer needed

- app/web/vite.config.ts
> Make headers match what we set in tools & prod

- .github/workflows/asset-update.yml
* update cron to daily
* use the systeminit bot pat token so pipelines run correctly
> chore: use a pat token for the clover pipeline

- bin/lang-js/src/component.ts
- bin/lang-js/src/function_kinds/management.ts
- lib/cyclone-client/src/client.rs
- lib/cyclone-core/src/component_view.rs
- lib/cyclone-core/src/lib.rs
- lib/cyclone-core/src/management.rs
- lib/dal/src/func/backend/management.rs
- lib/dal/src/func/binding/management.rs
- lib/dal/src/management/prototype.rs
- lib/dal/tests/integration_test/management.rs
- lib/veritech-client/src/lib.rs
- lib/veritech-client/tests/integration.rs
> Revert "feat: add incoming connections to mgmt functions components"

- CONTRIBUTORS.md
- bin/clover/inferred.json
Update for clover schemas. Check the diff comment to understand what has changed.
> chore: clover schema update

- app/auth-portal/package.json
- app/web/package.json
- lib/vue-lib/package.json
- pnpm-lock.yaml
Fixes https://github.com/systeminit/si/security/dependabot/396
> chore(deps): Upgrade Vite to 5.4.17

- bin/lang-js/src/component.ts
- bin/lang-js/src/function_kinds/management.ts
- lib/cyclone-client/src/client.rs
- lib/cyclone-core/src/component_view.rs
- lib/cyclone-core/src/lib.rs
- lib/cyclone-core/src/management.rs
- lib/dal/src/func/backend/management.rs
- lib/dal/src/func/binding/management.rs
- lib/dal/src/management/prototype.rs
- lib/dal/tests/integration_test/management.rs
- lib/veritech-client/src/lib.rs
- lib/veritech-client/tests/integration.rs
> feat: add incoming connections to mgmt functions components

- pnpm-lock.yaml
Fixes: https://github.com/systeminit/si/security/dependabot/390
> chore(deps): Upgrade @babel/helpers to 7.26.10

- lib/edda-server/src/change_set_processor_task.rs
This PR polishes spans for the edda change set processor task. It ensures that the request ID will always have a home to be recorded and it co-locates request handling into an inner function.
Finding the current span and recording fields are now protected too.
> Polish spans for edda change set processor task

- component/toolbox/Dockerfile
- component/toolbox/scripts/nats-cli
Toolbox tool for connecting to our nats cluster from localhost via tailscale.
```
❯ ./awsi.sh nats-cli -p tools-prod -r us-east-1 -n tools-prod 
NATS Configuration Context "tools-prod"
Server URLs: [redacted]
Credentials: ./nats-creds (OK)
Path: /root/.config/nats/context/tools-prod.json
Connection: OK
🚀 Welcome to NATS CLI Interactive Shell 🚀
----------------------------------------
Connected to: [redacted]
NATS Context: tools-prod
AWS Region:   us-east-1
AWS Profile:  tools-prod
Type 'nats --help' for more commands
----------------------------------------
[NATS:tools-prod] / $ nats account info
Account Information
User: [redacted]
Account: [redacted]
Expires: never
Client ID: 39,000
Client IP: [redacted]
RTT: 19ms
Headers Supported: true
Maximum Payload: 8.0 MiB
Connected Cluster: …
```
> feat: tool for connecting to nats clusters from localhost

- .github/workflows/webworker-validation.yml
- app/web/cypress/e2e/webworker.cy.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
- app/web/webworkertest.html
And it builds a new webworker html page for use within CI.
> From cypress, load new html page, invoke web worker, run tests, log output, assert.

- lib/edda-server/src/handlers.rs
This change fixes a bug where each processor task stays around forever, despite correctly detecting a quiet period. This was logic ported from Rebaser and the quiet shutdown logic was shared between 2 spawned tasks.
> fix(edda): shutdown processor tasks after quiescent period

- app/web/src/workers/webworker.ts
> Adding the checksum in mjolnir get requests, for the sake of clarity & understanding

- lib/rebaser-server/src/rebase.rs
> fix(rebaser): fix edda request data & rebaser/edda race condition

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/DiagramView.vue
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
> feat(web) - simple sockets ui wrap up with caching fixes

- app/auth-portal/package.json
- app/web/package.json
- lib/vue-lib/package.json
- pnpm-lock.yaml
Fixes: https://github.com/systeminit/si/security/dependabot/399
> chore(deps): Upgrade vite to 5.4.18

- component/lambda/functions/billing-fire-posthog-events.py
- component/lambda/sql/workspace_operations.sql
Remnants of the test schema I used to test the updated views without modifying the production ones.
Also removes a line to call the lambda handler when testing locally.
> fix(billing): Use correct schema name in canonical SQL

- app/web/src/components/ViewCard.vue
> fix(web): Ensure that we capture 409 in a rename of view

- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/ConnectionMenuSocketListItem.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/components/ModelingView/FloatingConnectionMenuInput.vue
- app/web/src/store/feature_flags.store.ts
- lib/vue-lib/src/design-system/forms/VormInput.vue
- lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
> feat(web) - fuzzy search highlighting and other connections menu improvements

- component/init/docker-entrypoint.sh
basic retry in case we hit ssm rate limits. Manually built and tested in tools prod
> feat: add basic retries to the init container

- app/web/src/store/feature_flags.store.ts
> fix(web) - remove forced feature flag

- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/README.md
- app/web/src/newhotness/Setup.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/layout_components/Breadcrumbs.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- app/web/src/newhotness/layout_components/DetailsPanelMenuIcon.vue
- app/web/src/newhotness/layout_components/InstructiveVormInput.vue
- app/web/src/newhotness/logic_composables/key_emitter.ts
- app/web/src/newhotness/logic_composables/navigation_stack.ts
- app/web/src/newhotness/logic_composables/toggle_containers.ts
- app/web/src/newhotness/types.ts
- app/web/src/newhotness/util.ts
- app/web/src/router.ts
- app/web/src/store/feature_flags.store.ts
- lib/vue-lib/src/design-system/general/TextPill.vue
- lib/vue-lib/src/design-system/general/VButton.vue
First and foremost, I want to be very clear that @jobelenus wrote all of this. Wendy and I mainly polished it up.
This PR adds the "big boom, foundational pieces and solves some problems" for the new UI. In addition, it showcases a README with lines of achievement for the new UI... all written by @jobelenus.
This PR also adds a feature flag for the new UI and uses router re-direction for gating the feature.
> Add base contents for job-specific UI

- lib/sdf-server/src/service/v2/management/generate_template.rs
We are removing the complexity of the generate_template function and are now keeping overrides and defaults anymore as well as the views array
We are also removing thesync to views function as well
> fix(sdf): Change how generate_template works

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/schema/list_schema.rs
- lib/luminork-server/src/service/v1/schema/mod.rs
- lib/luminork-server/src/service/v1/workspaces.rs
This will use the module cache and then determine if the schema is installed or not in the change set
---
⧓ Review in [Butler Review `#3w8gN7wOa`](https://gitbutler.com/stack72/si5a2d/reviews/3w8gN7wOa)
**feat(luminork): Add support for list_schema endpoint**
This will use the module cache and then determine if the schema is installed or not in the change set
1 commit series (version 3)
| Series | Commit Title | Status | Reviewers | 
| --- | --- | --- | --- |
| 1/1 | [feat(luminork): Add support for list_schema endpoint](https://gitbutler.com/stack72/si5a2d/reviews/3w8gN7wOa/commit/83b99873-0c6a-4632-b759-888ce61879b9) | ⏳ |  |
_Please leave review feedback in the [Butler Review](https://gitbutler.com/stack72/si5a2d/reviews/3w8gN7wOa)_
> feat(luminork): Add support for list_schema endpoint

- app/web/src/components/layout/navbar/WorkspaceSettingsMenuItems.vue
- app/web/src/store/feature_flags.store.ts
This has been enabled for all users for a while now
> chore(web): Cleanup SLACK_WEBHOOK feature flag

- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/store/components.store.ts
- Cache possible peer sockets calculations
- Show loading status when data from non active views hasn't loaded yet
- Don't freeze UI on long running peer calculations
> fix(web): Better UX for the connections menu with a lot of data

- app/web/src/components/AssetPalette.vue
- app/web/src/mead-hall/ApprovalFlowModal.vue
- app/web/src/mead-hall/AssetActionsDetails.vue
- app/web/src/mead-hall/ChangesPanelProposed.vue
- app/web/src/mead-hall/InsetApprovalModal.vue
- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/router.ts
- app/web/src/store/feature_flags.store.ts
- app/web/src/workers/types/dbinterface.ts
- lib/dal/src/component.rs
- lib/dal/src/qualification.rs
- lib/dal/src/socket/output.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-types-rs/src/checksum.rs
- lib/si-frontend-types-rs/src/lib.rs
- lib/si-frontend-types-rs/src/newhotness.rs
- lib/si-frontend-types-rs/src/newhotness/component.rs
- lib/si-frontend-types-rs/src/reference.rs
> feat(web) - component mv for newhotness

- app/web/Dockerfile
- bin/cyclone/Dockerfile
- bin/edda/Dockerfile
- bin/forklift/Dockerfile
- bin/innit/Dockerfile
- bin/luminork/Dockerfile
- bin/module-index/Dockerfile
- bin/pinga/Dockerfile
- bin/rebaser/Dockerfile
- bin/sdf/Dockerfile
- bin/veritech/Dockerfile
> Upgrade nixos/nix builders from 2.21.2 to 2.28.2

- lib/jsr-systeminit/cf-db/cfDb.ts
Array props take precedence over JSON props as well as explicit array props,
because we are assuming that props that can be either object or array are really just a
"one or many", i.e. T or T[]
Thank you @jkeiser for the help to fix this up!
> fix(clover): Ensure that we can hand;e the different between objects and arrays in oneOf prop types

- lib/innit-client/BUCK
- lib/innit-client/src/lib.rs
- lib/innit-server/src/server.rs
> fix(innit): buck2 config and logs

- app/web/src/components/layout/navbar/WorkspaceSettingsMenuItems.vue
> feat(Web): Add a way to open Workspace Tokens menu

- app/web/src/components/AdminDashboard/WorkspaceAdmin.vue
- app/web/src/store/admin.store.ts
- lib/sdf-server/src/service/v2/admin.rs
- lib/sdf-server/src/service/v2/admin/get_cas_data.rs
- lib/sdf-server/src/service/v2/admin/upload_cas_data.rs
- lib/si-layer-cache/src/db/cas.rs
- lib/si-layer-cache/src/db/workspace_snapshot.rs
Combined with snapshot fetching, this will allow us to debug remote workspaces better locally.
> feat(sdf): fetch and set cas data in admin panel

- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- app/web/src/newhotness/layout_components/InstructiveVormInput.vue
- app/web/src/newhotness/util.ts
- lib/vue-lib/src/design-system/general/PillCounter.vue
- lib/vue-lib/src/tailwind/less_vars.less
> feat(web) - virtualization for component tiles + improved newhotness UI

- lib/innit-client/src/lib.rs
Setting the identity and using the key are not needed when are doing tls termination
> fix: remove key and identity as we are doing termination

- app/web/src/store/components.store.ts
- app/web/src/store/feature_flags.store.ts
- lib/sdf-v1-routes-session/src/auth_connect.rs
On demand has been at 100% for a while. No reason to keep branching on the flag.
> chore(web,sdf): remove on demand flag, default to on demand

- .gitignore
- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/FuncRunCard.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/FuncRunList.vue
- app/web/src/newhotness/FuncRunStatusBadge.vue
- app/web/src/newhotness/LatestFuncRunDetails.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/layout_components/GridItemWithLiveHeader.vue
- app/web/src/newhotness/types.ts
- app/web/src/router.ts
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/func_runs.store.ts
- app/web/src/store/realtime/heimdall.ts
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/rebaser-server/src/rebase.rs
- lib/sdf-server/src/service/v2/func.rs
- lib/sdf-server/src/service/v2/func/get_func_run.rs
- lib/sdf-server/src/service/v2/func/get_func_run_logs.rs
- lib/sdf-server/src/service/v2/func/get_func_runs_paginated.rs
- lib/si-layer-cache/src/db/func_run.rs
- lib/si-layer-cache/tests/integration_test/db/func_run.rs
> Func Run List in Explore, and click into to navigate to a specific func run

- app/web/src/components/CodeEditor.vue
- app/web/src/components/FuncEditor/FuncEditor.vue
- app/web/src/store/func/funcs.store.ts
Comments explain the fixes - hopefully this is squashed for good @keeb!
> fix(web) - no more reload bugs in FuncEditor

- lib/dal/src/property_editor/values.rs
This makes the little yellow socket button light up when an attribute has a subscription to another component. It ends up looking the same as when there is an actual socket connection. It does this by marking the property as `is_from_external_source` (which is also set if there is a socket connection).
It does not (or should not) change behavior for workspaces without subscriptions. In fact, the alt text on the lit-up button still talks about sockets; but we don't want to change that text until subscriptions are broadly rolled out to users.
<IMG SRC="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHV3ZTAwZ3hraGo5aGl4OTR0cTNsY3RhZWswbjJxZjJudXNhc2huZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/p7SwW3XbdSY0g/giphy.gif">
> feat: Light up socket button when attributes have subscriptions

- Cargo.lock
- bin/edda/BUCK
- bin/edda/Cargo.toml
- bin/edda/src/args.rs
- bin/edda/src/main.rs
- bin/forklift/BUCK
- bin/forklift/Cargo.toml
- bin/forklift/src/args.rs
- bin/forklift/src/main.rs
- bin/pinga/BUCK
- bin/pinga/Cargo.toml
- bin/pinga/src/args.rs
- bin/pinga/src/main.rs
- bin/rebaser/BUCK
- bin/rebaser/Cargo.toml
- bin/rebaser/src/args.rs
- bin/rebaser/src/main.rs
- bin/sdf/BUCK
- bin/sdf/Cargo.toml
- bin/sdf/src/args.rs
- bin/sdf/src/main.rs
- lib/edda-server/src/lib.rs
- lib/forklift-server/src/lib.rs
- lib/pinga-server/src/lib.rs
- lib/rebaser-server/src/lib.rs
- lib/sdf-server/src/lib.rs
Integrates innit into the remaining services
> feat(edda, forklift, pinga, rebaser, sdf): use innit

- Cargo.lock
- app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
- app/web/src/store/admin.store.ts
- lib/sdf-server/BUCK
- lib/sdf-server/Cargo.toml
- lib/sdf-server/src/service/v2/admin.rs
- lib/sdf-server/src/service/v2/admin/innit.rs
Just a simple button so we can manually clear the innit cache when necessary
> feat(sdf, web): add admin button for clearing the innit cache

- app/web/src/components/ModelingView/ConnectionMenuCandidateList.vue
- app/web/src/components/ModelingView/ConnectionMenuCandidateListItem.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/store/component_attributes.store.ts
- app/web/src/store/components.store.ts
- app/web/src/store/feature_flags.store.ts
- lib/vue-lib/src/pinia/pinia_api_tools.ts
- Show props of the selected component on the connections menu list
- Add an option to skip the requestUlid on the payload
> feat(web): Show props on the floating connections menu

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/logic_composables/emitters.ts
- app/web/src/workers/types/dbinterface.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal/tests/integration_test/newhotness.rs
- lib/si-frontend-types-rs/src/newhotness/component.rs
> Adjust layout, add docs, add fuzzy search to prop options and attribute tree

- component/init/docker-entrypoint.sh
This is slop. It should reduce the number of calls to ssm by batching requests. I've tested this manually in a few places and it works correctly. This is temporary as we should be drastically reducing the number of ssm params this needs to interact with.
> fix: reduce individual calls to ssm

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
This PR requires #6041.
Rather than allowing unlimited parallelism (until we overwhelm the machine the code is running on), we now have a queue of MV build triggers that _would_ have spawned new tasks, but didn't because it would have exceeded the max concurrency we've defined.
Once MV build triggers have been queued, we skip processing the changes with the ready to start MV kinds until we have spawned tasks for every queued trigger.
When determining whether we have finished all of the work necessary, we also now check to make sure that there aren't any queued triggers, in addition to making sure that there are not any ready to start MV kinds, and no currently outstanding build MV tasks that need to finish.
> Limit concurrency of parallel MV building in edda

- bin/clover/doc-link-cache.json
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Removed input socket for BucketName (set in the S3 Bucket asset) 
BucketName after socket removal:
> fix: remove bucketname and pbaccessblckconfig s3 input sockets

- lib/innit-client/src/lib.rs
> fix: create cert parent directory

- app/web/src/components/CodeViewer.vue
- app/web/src/newhotness/CodePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/ResourcePanel.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
> feat(web) - resource/code panels for newhotness

- app/auth-portal/vite.config.ts
We need to see a stack trace in prod
> Auth portal minification off

- app/auth-portal/vite.config.ts
> Trying this to resolve the auth portal problem

- lib/frigg/src/lib.rs
This change prevents a panic in the implementation of Frigg where the remote nats server nats kv configuration for the given name doesn't match the one given to the client. This also matches the behaviour we have with other NATS Jetstream streams if for example the replication count doesn't match what the client was expecting (Which is ok!)
Now the `frigg_kv` function will use the existing stream if it finds a stream with the correct name, otherwise it'll create it with the given client configuration.
<div><img src="https://media2.giphy.com/media/555BqS4qxrvwJmib49/giphy.gif?cid=5a38a5a22jv0utg5whhsvnss2wtyyt7t1zt94xa5aa4vfrex&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/></div>
> feat: use-or-create kv store FRIGG

- app/web/src/mead-hall/ActionWidget.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/DiffPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/FuncRunCard.vue
- app/web/src/newhotness/FuncRunList.vue
- app/web/src/newhotness/FuncRunStatusBadge.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/layout_components/GridItemWithLiveHeader.vue
- app/web/src/workers/types/dbinterface.ts
Also various styling fixes across the newhotness UI.
> feat(web) - newhotness component actions and diff panels

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/CodePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/QualificationView.vue
- app/web/src/newhotness/ResourcePanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/util.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
Nick removed the AttributeTree. Jacob brought it back in a different structure. Updating the front end to match the new structure.
> Changed AttributeTree structure is working again

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/change_sets/mod.rs
- lib/luminork-server/src/service/v1/change_sets/purge_open.rs
- lib/luminork-server/src/service/v1/workspaces.rs
- lib/si-events-rs/src/audit_log/v1.rs
Add the ability to purge all open change sets
> feat(luminork): Add ability to purge open change sets

- lib/dal/examples/snapshot-fixer/main.rs
<div><img src="https://media4.giphy.com/media/UxNTT095uL0go/200.gif?cid=5a38a5a2jdl9bcxe3irb7mlpd2csboil0b11tv3l4800natt&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:168px;width:300px"/><br/>via <a href="https://giphy.com/gifs/bob-the-builder-yes-we-can-UxNTT095uL0go">GIPHY</a></div>
> feat(dal): Add snapshot-fixer with notes on how to use it and an example

- app/web/src/api/sdf/dal/component.ts
- app/web/src/components/ComponentConnectionsPanel.vue
- app/web/src/components/Connection.vue
- app/web/src/components/ConnectionEndCard.vue
- app/web/src/components/DetailsPanelTimestamps.vue
- app/web/src/components/EdgeDetailsPanel.vue
- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/components/ModelingView/DeleteSelectionModal.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/components/ModelingView/RestoreSelectionModal.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/newhotness/Component.vue
- app/web/src/store/components.store.ts
- app/web/src/store/realtime/realtime_events.ts
- app/web/src/store/views.store.ts
- lib/dal/src/diagram.rs
- lib/sdf-server/src/service/v2/component.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
> Show prop-to-prop connections on diagram and edge details panel

- app/web/src/newhotness/Component.vue
Follow on from the [previous PR](https://github.com/systeminit/si/pull/6116) to make the MV data!
> Add the management functions list to the component's panel

- app/web/src/components/AssetPalette.vue
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/ComponentFilterTile.vue
- app/web/src/newhotness/Explore.vue
- lib/vue-lib/src/design-system/general/SiSearch.vue
- lib/vue-lib/src/design-system/general/TextPill.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/index.ts
- lib/vue-lib/src/design-system/layout/HorizontalScrollArea.vue
- lib/vue-lib/src/design-system/layout/ScrollArea.vue
- lib/vue-lib/src/design-system/modals/Modal.vue
- lib/vue-lib/src/design-system/utils/color_utils.ts
- lib/vue-lib/src/tailwind/tailwind.css
Stuff that still needs to be done -
- Implement the icons for each of the AssetFilters
- Apply fuzzy search to the list of categories and their assets
- Apply highlight styles to the asset elements in the list
- Make sure that the onHead check works properly
- Build and populate the panels for Documentation and Attributes
- Implement selection and creation of the component
- Add a banner to the Component element for when a new change set was made from Head
> feat(web) - partially complete add component newhotness

- .github/workflows/run-api-test.yml
- .gitignore
- bin/si-luminork-api-tests/.env
- bin/si-luminork-api-tests/scripts/run-tests.sh
- bin/si-luminork-api-tests/tests/schemas.test.ts
There is no provision to see artifacts at this time - this is the basics that we will build upon
An example of the tests - https://github.com/systeminit/si/actions/runs/15048538868/job/42297233768#step:4:248
> chore(ci): Adding Luminork API Tests to CI

- app/web/src/components/LeftPanelDrawer.vue
- app/web/src/components/ViewCard.vue
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/FilterTile.vue
- app/web/src/newhotness/layout_components/InstructiveVormInput.vue
- app/web/src/newhotness/types.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
From Wendy's list:
- Implement the icons for each of the AssetFilters
- just havent gotten to it
- ~~Apply fuzzy search to the list of categories and their assets~~
- Apply highlight styles to the asset elements in the list
- we don't want to do the "span for every character" here.. so we'll revisit this in the future
- ~~Make sure that the onHead check works properly~~
- ~~Build and populate the panels for Documentation and Attributes~~
- ~~Implement selection and creation of the component~~
- Add a banner to the Component element for when a new change set was made from Head
- TODO, still no "force change set" on head
> Creating components!

- app/web/src/api/sdf/dal/component.ts
- app/web/src/components/AttributesPanel/SourceIconWithTooltip.vue
- app/web/src/components/AttributesPanel/TreeFormItem.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/store/components.store.ts
- lib/sdf-server/src/service/v2/component/attributes.rs
> feat(web, sdf): Add subscription button to arrays

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/logic_composables/navigation_stack.ts
Fixing up the navigation / back button logic
> New hotness nav stack fixes

- lib/luminork-server/src/service/v1/components/create_component.rs
This will use locally installed Schemas not just schemas in the Module Cache and it will create a view if it doesn’t exist already:
```
curl -X 'POST' \
'http://localhost:5380/v1/w/01HPJ3K7RC486W9RPR3T0B6HS2/change-sets/01JVD2HT6P5QFK2A4MNZRZX72Q/components' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer ….' \
-d '{
"name": "Test",
"schemaName": "TestSchema",
"viewName": "MyView"
}'
```
```
{
"component": {
"id": "01JVD2XBH7V569SGB93FRJZYJ9",
"schemaId": "01JVD2J26CV2YQ6RVF0TM40D3J",
"schemaVariantId": "01JVD2J26CMMGAT1CJM89N31KW",
"sockets": [],
"domainProps": [],
"resourceProps": [],
"name": "Test",
"resourceId": "",
"toDelete": false,
"canBeUpgraded": false,
"connections": [],
"views": [
{
"id": "01JVD2XBH6S782W6AZ2YE4GNWC",
"name": …
```
> fix(luminork): Update create_component to not rely only on module cache

- app/web/src/main.ts
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/CodePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/ResourcePanel.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/AttributeChildLayout.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/logic_composables/emitters.ts
- app/web/src/newhotness/util.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
First commit: Array and Map "add/remove" is now working! PSA for @vbustamante and @jkeiser when I delete one element of an array, they all get deleted, seems to be an API bug?
Second commit: Big stabilization of web worker reference checking and returning
> Component Props Array & Map. Stabilize reference fetching

- .github/workflows/publish-pip-package.yml
- bin/openapi-extractor/sdk-generators/generate-python-sdk.sh
- generated-sdks/python/pyproject.toml
- generated-sdks/python/setup.py
Fix the doc links + requirements and removing some incorrect keywords
> chore(sdk): Small tweaks to python SDK

- app/web/package.json
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AddViewModal.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/PropsAsTree.vue
- app/web/src/newhotness/logic_composables/watched_form.ts
- app/web/src/router.ts
- app/web/src/workers/types/dbinterface.ts
- pnpm-lock.yaml
> Add View! Add Component props in a tree! Markdown rendering!

- lib/dal-materialized-views/src/component/attribute_tree.rs
> Fix: attribute value MV needs to account for prop-to-prop when setting "is_external"

- lib/dal/src/func/runner.rs
Intrinsic functions are never dispatched to veritech/cyclone which means that before functions will never run, as they are only run by veritech/cyclone in order to modify the environment that the function will run in.
While it is very unlikely that there will be intrinsic functions in all the places where `FuncRunner::before_funcs` is being called, there's much less of a chance for needlessly looking up the before funcs if the short-circuit logic is centralized there.
> Do not collect before functions when running intrinsic functions

- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/LatestFuncRunDetails.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
> Type safety; stop passing strings, make an EntityKind. Fix incorrect uses of makeArgs/makeKey

- app/docs/src/roadmap/index.md
Setting the correct status on the projects in the roadmap
> docs: Updating our roadmap

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/layout_components/AttributeChildLayout.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- lib/vue-lib/src/design-system/general/SiSearch.vue
UI is partially functional, will continue to work on this!
Also some fixes/improvements to various other parts of the newhotness UI!
> feat(web) - newhotness attribute input new UI

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/layout_components/AttributeChildLayout.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/logic_composables/emitters.ts
- lib/vue-lib/src/design-system/general/SiSearch.vue
- lib/vue-lib/src/design-system/general/VButton.vue
https://github.com/user-attachments/assets/72ae3407-ae09-406d-93a5-eb739c798261
https://github.com/user-attachments/assets/b235b0ed-b166-4d35-b9e2-3288bb7c65aa
> feat(web) - newhotness UI mostly done, prop to prop!

- BUG BOUNTY.md
Set correct updated date on bug bounty document
> Update BUG BOUNTY.md

- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/ActionWidget.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/api_composables/index.ts
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/action.rs
> Make all the actions API calls v2, no more stores

- .github/workflows/publish-typescript-sdk.yml
- bin/openapi-extractor/sdk-generators/generate-typescript-sdk.sh
- generated-sdks/typescript/deno.json
The small changes to the deno.json file are to improve our jsr.io score :D
> chore(ci): Add npm to the mix now that jsr is deploying

- app/web/src/newhotness/Workspace.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/webworker.ts
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/create.rs
- lib/sdf-server/src/service/v2/index.rs
I'm seeing lots of hammers on the new change set... some are explainable, others aren't... again, waiting on the inflight work before diving in.
> New create change set endpoint blocks on index MV

- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/FuncRunList.vue
> Fix: func queries need the changeSetId in the key to re-query when you switch change sets

- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/logic_composables/watched_form.ts
https://github.com/user-attachments/assets/e094b43c-6f1d-4068-bc3c-08bc43b3bea2
> feat(web) - inline attribute input window, show value for connection, flow for arrays and maps

- app/web/src/newhotness/AddComponentModal.vue
This improves the perceived performance of the add component modal by debouncing the fuzzySearchString, so we don't run the expensive computation (and pay the tax on re-rendering) while the user is still typing.
> chore: speed up new component search filtering

- bin/bedrock/BUCK
- flake.nix
Need a bedrock omnibus binary to be published to allow testing on remote machines
> feat: add bedrock omnibus

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
- lib/si-frontend-mv-types-rs/src/component/attribute_tree.rs
> feat(web): Ensure we show when an external subscription is in place between props

- app/web/src/workers/webworker.ts
> fix(web): In the new prop to prop world, allow connecting to props that don't have values yet

- lib/dal/src/attribute/value.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
> fix(sdf): Remove printlns, doh!

- bin/si-luminork-api-tests/tests/components.test.ts
To keep the tests green, changing to VPC - will fix the EC2 Instance when this goes green
> fix(luminork-tests): Luminork workspace has an issue with EC2 Instance schema

- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/logic_composables/watched_form.ts
And one final tweak to that counter.
> Debounce func run cache busting

- lib/dal-materialized-views/src/component.rs
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/si-frontend-mv-types-rs/src/component.rs
In order to upgrade a Component, we need to know if it's upgradeable!
> feat(dal): add component upgraded to Component MV

- dev/Tiltfile
- dev/docker-compose.platform.yml
- dev/prometheus-config/config.yml
ALL THE HOST METRICS PLEASE
<div><img src="https://media4.giphy.com/media/H0kxiS2RJF2HC/giphy.gif?cid=5a38a5a2do5i8neeytwlz6mzwbtfyjge6x9jx2fra9kf2jrs&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:233px;width:300px"/></div>
> feat: add node_exporter to our tiltfile so we can access host metrics in grafana

- app/web/src/newhotness/AddComponentModal.vue
> Fix: when making a new change set we need to change the optimistic query key accordingly

- app/web/src/newhotness/layout_components/AttributeInput.vue
> Fix: av spinner needs to stop on subscription too

- lib/dal/src/workspace_snapshot/graph/validator.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
There are a bunch of custom socket transform functions in IAM resources that do the same thing as si:identity or si:normalizeToArray. This treats those functions the same way during migration, allowing us to migrate a bunch more connections.
It also handles when you connect multiple AWS ARN resources to an array of ARNs--the ARN socket outputs a single value, even though it's not the identity function, so when you use normalizeToArray on the other side, we can create a separate element for each subscription to the ARN socket.
This should finish out migration of Production SaaS Workspace as well as most (if not all) of some of our other big workspaces.
> feat(sdf): Migrate connections IAM/ARN sockets

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
If it’s a bool, we need to coerce to a bool. 
Also adds a keyboard shortcut for closing the FuncRunDetails with the Escape key
> fix(web): Ensure we can save the correct value state in the attribute inputs

- app/web/src/store/views.store.ts
- lib/sdf-server/src/service/v2/component.rs
- lib/sdf-server/src/service/v2/component/delete_components.rs
- lib/sdf-server/src/service/v2/component/upgrade_components.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/duplicate_components.rs
Also renamed paste_components to duplicate components
> feat(sdf): Move upgrade component to a v2 endpoint

- app/web/src/workers/webworker.ts
`db.exec` is not a promise, and does not need to be awaited. Awaiting it was causing artifically inflated timings in the debug `sql get` logging, but did not appear to be affecting the overall performance in testing with change sets having large numbers of components (500+).
> Do not await db.exec in webworker

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/EraseModal.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ConfirmModal.vue
- app/web/src/newhotness/layout_components/TextPill.vue
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
- lib/vue-lib/src/design-system/modals/Modal.vue
Still very much in progress, the menu is not styled right yet, does not work in Map view yet, and the Erase endpoint is not yet wired up.
> feat(web) - component context menu in newhotness

- bin/si-discord-bot/package-lock.json
- bin/si-discord-bot/package.json
- pnpm-lock.yaml
Also re-run the install for si-discord-bot to try and pull the latest packages from there
Fixes: https://github.com/systeminit/si/security/dependabot/413
Fixes: https://github.com/systeminit/si/security/dependabot/412
Fixes: https://github.com/systeminit/si/security/dependabot/411
> chore(deps): ensure tar-fs is at a patched version

- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/compressing_stream.rs
This change fixes an issue where the `ChangeSetProcessorTask` didn't detect its quiescent period and would shut down. Prior to this change, the last heartbeat `Instant` was updated on every `match state` in the `loop {}` of the `CompressingStream`. This had the side effect of updating the `Instant` far too regularly.
This change only updates the last heartbeat `Instant` when it has just performed some work, such as parsing an API message, reading a NATS message, yielding a compressed request, etc. The quiet period, therefore is the gap between just having done some nontrivial work in the `CompressingStream`.
Testing of this involved running the api-load-test with 1024 component creates and an aggresively short `10s` quiescent_period (by exporting `SI_EDDA__QUIESCENT_PERIOD_SECS=10` before …
> fix(edda): update "last heartbeat" logic to ensure tasks shut down

- app/web/src/newhotness/Workspace.vue
> Set global tanstack stale time to infinity, since we invalidate everything manually

- app/web/src/store/apis.web.ts
> fix(web) - token fix

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
> fix(new ui): Don't show connection candidates from the same component

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/logic_composables/window_info_reactive.ts
- lib/vue-lib/src/design-system/general/PillCounter.vue
- lib/vue-lib/src/design-system/general/TextPill.vue
- lib/vue-lib/src/design-system/general/VButton.vue
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
> fix(web) - many newhotness controls fixes!

- app/web/src/workers/mjolnir_queue.ts
This will keep the UI more up-to-date for the user more of the time.
We were holding these back initially because we thought we saw slow sql query times, But those timings were a red-herring, and we were't causing a sql slow down with too many queries
> We dont need to hold off on cache busting (which causes more queries) while patching is happening

- app/web/src/newhotness/Map.vue
- Menu closes when hitting Esc
- Menu persists when refreshing with it open
- Menu opens on the component selected
> fix: move action menu to component on map click

- lib/luminork-server/src/routes.rs
- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/management_funcs/get_management_func_run_state.rs
- lib/luminork-server/src/service/v1/management_funcs/mod.rs
- lib/luminork-server/src/service/v1/workspaces.rs
- lib/si-db/src/management_func_execution.rs
> feat(luminork): Add ability to get the status of a management function run

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
> feat(web) - many newhotness UI improvements!

- app/web/src/newhotness/ComponentGridTile.vue
- lib/vue-lib/src/design-system/index.ts
> feat(web): Make qualification numbers more actionable when failed

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/api_composables/index.ts
- lib/sdf-server/src/service/v2/management.rs
> feat(new ui): Set resourceId and run import funcs

- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
> fix(web): Ensure we treat secrets as secret input in the new UX

- app/web/src/newhotness/layout_components/AttributeInput.vue
Debouncing this input to relieve some of the stress on this lookup.
> fix(web): debounce attribute input panel

- pnpm-lock.yaml
Fixes https://github.com/systeminit/si/security/dependabot/415
Fixes https://github.com/systeminit/si/security/dependabot/416
Fixes https://github.com/systeminit/si/security/dependabot/417
> chore(deps): Upgrade brace-expansion

- app/web/src/newhotness/AttributeValueBox.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/FuncRunCard.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
- app/web/src/newhotness/layout_components/SecretInput.vue
- lib/vue-lib/src/design-system/general/TruncateWithTooltip.vue
- lib/vue-lib/src/design-system/general/VButton.vue
This PR fixes a number of truncation bugs, and also adds the ability to show/hide secret fields.
> feat(web) - truncation and other UI fixes newhotness

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/workers/webworker.ts
Upgrade:
1. Unlock an asset for a component in the list
2. See the upgrade icon pop in
Change Sets:
1. copy the URL to a change set
2. abandon that change set (you get redirected to HEAD)
3. paste the URL in your copy buffer and go to it
4. app redirects you to HEAD
> Upgrade Component Reactivity & Don't Show Closed Change Sets

- app/web/src/workers/webworker.ts
When we cold start and the index doesn't exist yet, we need to insert the index before inserting MTMs (because they depend on it). We *believe* it's the issue preventing @aaron-dernley from loading his workspace, but are not sure, so this is partly just "if @aaron-dernley reloads and his workspace works again, then we have confirmed this is the bug we think it is." Either way though, the index must exist before you can insert atoms into it :)
This PR tries to be minimal and targeted, to fix this reload issue. It does *not* address the bug where the UI can't update anymore, which is why the system got into the bad state in the first place.
> fix(bifrost): Handle missing index on cold start

- app/web/src/newhotness/Explore.vue
> Fix: vue reactivity couldn't track an unassigned computed like this

- app/web/src/store/realtime/heimdall.ts
Folks saw intermittent problems when loading the app. The problem was that the URL to fetch change sets had no `workspacePk` The stack trace went through heimdall and the cold start. That cold start uses the change set and workspace store. Those stores have "activation" steps that are async, which we cannot await. Even though the stores pull the workspace from the URL, other activities must have been getting in the way and slowing activation.
We don't need to use the store to get the change set data we're looking for. So lets just avoid the problem
Lobby still works!
> Fix: dont use stores to find the list of open change sets

- app/docs/src/reference/public-api.md
- generated-sdks/python/system_initiative_api_client/models/create_component_v1_request.py
- generated-sdks/python/test/test_create_component_v1_request.py
- generated-sdks/typescript/api.ts
This is to reflect the addition of `managedBy` to the create call
This is an autogenerated set of changes
> chore(docs): Update API docs + SDKs

- app/web/src/newhotness/Workspace.vue
If there are a ton of functions running (which happens frequently), we never show func run status because we keep cancelling the current query each time we get a FuncRunLogUpdated event.
This PR:
* Don't send a trillion fetches to SDF--only once every 500ms
* If status updates during a fetch, refetch *after* the current request finishes instead of cancelling
* There is still a delay of 500ms when we first. We can't get rid of that until we fix the fact that FuncRunLogUpdated comes in *before* the func run status is available (we may need to create--or listen to--a different event).
* Does not fix the fact that the "5s ago" text in the func run status never updates over time
> fix(web): Show func run status even under heavy load

- app/web/src/newhotness/Explore.vue
This change fixes the qualification group title for passed qualifications. Caused by me in PR #6528.
> Fix passed qualification group title

- app/web/src/newhotness/ApprovalFlowModal.vue
Wait for apply endpoint to succeed before router push
> Fix: wait for apply endpoint to succeed before router push

- app/web/src/newhotness/explore_grid/ExploreGrid.vue
Adds a data-testid to the tiles for me to test against in cypress
> feat(cypress): add data-testid to tiles

- app/web/src/workers/webworker.ts
We need to improve the implementation to realize when we are holding onto a specific AV that no longer exists on its `IncomingConnectionMV`.
This can happen as a result of:
- OTs can remove and add an AV which results in a new ID
- Array / map users can remove AV
1. Have two key pairs
2. Add a tag to one key pay
3. Go to the other key pair, and search the possible connections for the tag
4. See the tag
5. Go back to the other key pair
6. Delete the tag
3. Go to the other key pair, and search the possible connections for the tag
4. No tag
> ENG-3098: individual AVs can be removed via user & system operations, stay up to date

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/skeletons/DelayedSkeleton.vue
- app/web/src/newhotness/skeletons/ExploreGridSkeleton.vue
- app/web/src/newhotness/skeletons/GridTileSkeleton.vue
Shimmering "skeletons!".
Currently only mimics the component grid.
> feat(web): replace delayed loader with an animated skeleton

- app/web/src/newhotness/CodeEditorModal.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/SecretInput.vue
- app/web/src/newhotness/skeletons/ExploreGridSkeleton.vue
- Create only props now get disabled for editing after they have a resource.
- Fixed a bug with the add item form for maps/arrays.
- Attributes panel and secrets form now supports textarea and code editor inputs
> feat(web) - a few more UI improvements

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/skeletons/DelayedSkeleton.vue
- app/web/src/newhotness/skeletons/ExploreGridSkeleton.vue
- app/web/src/newhotness/skeletons/ExploreMapSkeleton.vue
If the user is loading the map view, show a map skeleton.
> feat(web): skeleton for map view

- app/web/src/store/realtime/heimdall.ts
Legacy workspaces will never have a change set that has no base change set. Just grab the base change set off the workspace metadata.
> fix(web): get base change set id correctly

- lib/dal/src/change_set.rs
Block merging a changeset if it is the same as the base changeset on ctx. This is meant to prevent occurrences where rogue API requests try to apply HEAD, which if no other changesets exist in the workspace leaves the system unusable
> fix: Fail on self rebases everywhere

- app/web/src/newhotness/Explore.vue
https://jam.dev/c/0f30af5a-ec50-4c58-94a5-3c5dbb62f9ce
https://jam.dev/c/d604ef7f-213e-4f3e-8303-49fd75b5651c
> feat(web): Add ability to group by SchemaName

- app/web/src/newhotness/AddComponentModal.vue
This doesn’t quite work as we expected so we can revist this at a later date
> fix(web): Remove PropTree from AddComponentModal

- app/web/src/newhotness/Lobby.vue
- app/web/src/newhotness/LobbyTerminalOutputLine.vue
Add a css only spinner around the terminal on the lobby
https://github.com/user-attachments/assets/c60c6991-3a09-4696-b374-a20ba3b81cc0
> feat: Add spinner to the lobby terminal

- app/web/src/newhotness/Map.vue
https://jam.dev/c/8efe4d5d-e93b-44ed-869a-880ed4785324
> feat(web): Add the work to support highlighting

- app/web/src/newhotness/FuncRunDetails.vue
They were always being streated like strings not numbers - yet it was parsing it incorrectly
Treating it like numbers means that we can ensure that the timestamps are formatted correctly not `Wed, 21 Jan 1970 06:34:12 GMT`
> fix(web): ensure FuncRunDetails timestamps are formatted correctly

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/ShortcutModal.vue
This ensures consistency where no cmd keys are used - except cmd + a :)
> fix(web): Change the duplicate shortcut key

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal/src/component.rs
- lib/dal/src/component/delete.rs
- lib/dal/src/component/diff.rs
- lib/dal/tests/integration_test/component/delete.rs
- lib/dal/tests/integration_test/management.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/luminork-server/src/service/v1/components/delete_component.rs
- lib/si-frontend-mv-types-rs/src/component.rs
> chore(edda): drop diff_count from component mv in favor of faster check

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/ExploreModeTile.vue
- app/web/src/newhotness/layout_components/TabGroupToggle.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
Also added arrow key handlers to select the context menu on left/right arrow.
> feat(web) - Explore improvements

- app/web/src/newhotness/Workspace.vue
What it says on the tin. Console was giving us an error
> Fix: out of order instantiation

- app/web/src/components/SecretCard.vue
- app/web/src/newhotness/ActionQueueList.vue
- app/web/src/newhotness/EmptyState.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/FuncRunList.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
> feat(web) - improved empty states, UI fixes

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
We were redoing filtering on the map, so when updating the search code it broke filtering on map since it was not updated.  Now all the explore filtering is centralized in the Explore component
> fix: Attribute search on map works!

- component/lambda/functions/billing-data-check-errors.py
We were getting a set of alerts for billing errors for 1) a terminated account and 2) an account with special billing rules. Both of these are gonna take some times to fix and we want to silence alerts for them while we implement the fixes, so we added the ability to pass in a list of user_pks on the `billing-data-check-errors` lambda that ignores whatever users we decide. The user pks are already set on the lambda's environment so it will take effect as soon as these changes are deployed.
> feat: Allow ignoring users on billing errors lambda

- app/web/src/newhotness/ComponentContextMenu.vue
The only option currently available is `restore`
> feat(web): Allow erasing a deleted component

- app/web/src/components/layout/navbar/NavbarPanelCenter.vue
- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/store/feature_flags.store.ts
This combines the ability to have a user be able to enable / disable the new UX. This is in preparation for releasing this to our first set of specific users
> feat(web): Changing new UX feature flag

- app/web/src/newhotness/ComponentContextMenu.vue
https://jam.dev/c/bbc9fbad-e634-4406-8fe2-fb61fe2a852a
> feat(web): Add ability to multi-upgrade components

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
Changes to the AttributePanel in slices C & D for ENG-3120. Also some other minor UI fixes.
> feat(web) - adjustments to the AttributePanel newhotness

- app/web/src/newhotness/FuncRunList.vue
https://jam.dev/c/a9152d2f-adad-4cfd-b7b5-28a09e7018b7
> feat(web): Add the ability to filter the func run history panel

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
When an array was subscribed to another array, we didn’t let the user 
know and we allowed them to change individual properties or remove itmes
from the array. The api calls ultimately failed and it was confusing to 
a user
Now if an array or a map is a subscription to another array or map the 
we remove the ability to delete array items, add new items OR change any
of the values
https://jam.dev/c/8fdbebd9-212c-412a-83f0-33c73c986561
> fix(web): Ensure no confusion around array and map subscriptions

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- lib/vue-lib/src/design-system/general/IconButton.vue
These were not possible to add before and we added the correct UX 
interaction to feel more like the subscriptions flow
https://jam.dev/c/ddcb4b27-4e08-45bd-a9cc-e8d1eb4f2011
> feat(web): Allow ArrayItem subscriptions

- pnpm-lock.yaml
https://github.com/systeminit/si/security/dependabot/421
https://github.com/systeminit/si/security/dependabot/420
https://github.com/systeminit/si/security/dependabot/419
> chore(deps): Upgrade form-data deps

- pnpm-lock.yaml
Remove any non-patched versions of the library
> chore(deps): Cleanup old versions of form-data

- app/web/src/newhotness/ComponentDetails.vue
This is a WIP but has a fix in place for the page when embedding the 
AddComponentModal in the page
> fix(web): First small turn of the Component Detaills right hand panel

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
This button will need styled as part of the work to take action on a 
component
https://jam.dev/c/e5d7fe52-3ce8-4105-bc50-9f7e2f2b944c
> feat(web): Add an ability to visualize connections from a component page

- .ci/docker-compose.test-integration.yml
- .ci/generate-creds-from-iam-role.sh
Really a revert of https://github.com/systeminit/si/pull/5646/files
[Relevant thread](https://systeminit.slack.com/archives/CM0GA003G/p1753141673429289)
> fix: remove pull-through cache

- app/web/src/newhotness/Explore.vue
Fixes the following type error:
> fix(web): handle filteredComponents.value === undefined

- support/buck2/buck2-sync-cargo-deps.py
There was an invocation of this script that failed due to non-ascii characters showing up.
> fix(deps): decode stream output as UTF-8 in buck2-sync-cargo-deps.py

- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/skeletons/ExploreMapSkeleton.vue
Also fixed a small issue where the right hand panel was too small for 
the connections panel and when the component card was too small the 
elipsis overlapped it so we make the card slightly bigger to deal with 
that and in the skeletons for the map
> fix(web): Ensure multi-select actions work on the map

- app/web/src/components/StatusIndicatorIcon.vue
- app/web/src/mead-hall/ActionCardLayout.vue
- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/ActionWidget.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ComponentTileQualificationStatus.vue
- app/web/src/newhotness/DocumentationPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/ExploreModeTile.vue
- app/web/src/newhotness/FuncRunCard.vue
- app/web/src/newhotness/FuncRunList.vue
- app/web/src/newhotness/ManagementConnectionInput.vue
- app/web/src/newhotness/ManagementConnectionsList.vue
- app/web/src/newhotness/ManagementFuncCard.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/QualificationView.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/layout_components/GridItemWithLiveHeader.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue
> fix(web): Update the styling of the Grid page + ensure that text is styled correctly

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/actions/get_actions.rs
- lib/luminork-server/src/service/v1/components/list_components.rs
We have deprecated the old components parameter in favour of this new 
parameter
> feat(luminork): Extend list_components to return component name and schema name

- deno.lock
the lockfile somehow got generated with a newer version of deno than the one we are shipping. this PR regenerates the lockfile with the correct version.
> bug: fix the deno lockfile

- app/web/src/newhotness/Explore.vue
> Make a new changeset when you start a bulk edit on HEAD

- app/web/src/newhotness/Explore.vue
> fix(web): Ensure we groupBy diffs correctly

- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
Look for both `domain/` and `secrets/` AV paths when finding common paths that can be bulk edited.
> Add secrets/ path in with domain/ for bulk editing

- app/web/src/newhotness/QualificationView.vue
- app/web/src/newhotness/nav/ChangeSetPanel.vue
> fix(web): Ensure styling of Rerun qualification and create change set is consistent

- app/web/src/newhotness/AddViewModal.vue
> feat(web): Update create view button to a consistent button styling

- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
> Fix: Bulk Edit Secrets wasn't getting the right suggestions, was using the wrong component

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Lobby.vue
> On page load for bulk edit, show the context menu if selected components are in the URL

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/composables/useComponentDeletion.ts
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal/src/component/diff.rs
- lib/si-frontend-mv-types-rs/src/component.rs
We just showed hasDiff or not. Now we show if it’s added or modified or 
default to nothing
> feat(web): Expose the actual component diffStatus in the Grid

- app/web/src/newhotness/AddComponentModal.vue
Recreating the fuzzy search instance each time was proving to be 
expensive. So we memoize it so we can reuse it
> fix(web): Optimise the performance of the AddComponentModal

- app/docs/src/reference/vocabulary.md
Add new vocabulary terms:
- Grid
- Map
- Subscription
- Context Menu
Removed
- SOCKETS
> docs: update vocab terms

- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
This will hopefully associate the migrations with the actual GET or POST request that spawned it.
> fix: Associate the migration span with the http request

- .github/workflows/run-api-test.yml
> chore(ci): These tests are flakey due to deno

- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/logic_composables/tokens.ts
- app/web/src/pages/auth/AuthConnectPage.vue
Brand new workspace's were failing to read their tokens correctly
1. create a new local dev workspace
2. hit `go to workspace`
3. get stuck on a blank UI — now this works 😄
> Re-read the workspace tokens after you write them

- app/web/cypress/archive/authentication/logout.cy.ts
- app/web/cypress/e2e/authentication/login.cy.ts
- app/web/cypress/e2e/web-functionality/get-summary.cy.ts
- app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts
- app/web/cypress/support/commands.ts
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/nav/ChangeSetPanel.vue
Less edits than I expected to get these working! Next turn is to get some new tests written.
> updating cypress tests for new UI

- app/web/cypress/archive/authentication/logout.cy.ts
- app/web/cypress/support/commands.ts
> test fix for appModelPageLoaded

- app/web/src/components/ChangesetRenameModal.vue
Forgot to remove this with a previous PR
Rename a change set
> Remove a sponge: dont need this argument anymore

- app/web/src/newhotness/DiffPanel.vue
Old: No diff information yet
New: No changes
> Copy change: no changes, not "not yet"

- app/web/src/newhotness/CodeEditorModal.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
https://jam.dev/c/68c7c179-1ae8-4531-9be2-3db3a0cea3d0
> fix(web): Ensure we can save from the CodeEditorModal

- app/web/src/store/realtime/heimdall.ts
Currently, we don't retry until Edda fires us an IndexUpdate WsEvent representing "we are done building the index". In case that message fails to be sent or received, the client ought to continue to retry the index endpoint as a backup.
I also added a console log for the muspelheim statuses, so we can see when they change, and if any are left.
> When MV index gives us a 202, re-queue that change set

- app/web/cypress/e2e/web-functionality/web.cy.ts
> removing the beforeEach section for web tests

- app/web/cypress/e2e/authentication/auth.cy.ts
> removing the beforeEach for auth as well

- app/web/src/newhotness/ApplyChangeSetButton.vue
- app/web/src/newhotness/ApplyChangeSetModal.vue
- app/web/src/newhotness/ApprovalFlow.vue
- app/web/src/newhotness/nav/ApprovalPendingModalCard.vue
As an approver, the flow wasn’t quite working. Clicking on the buttons 
didn’t give them any feedback. And taking them to the change set didn’t 
pop the modal
https://jam.dev/c/1ae16b62-22c0-49ff-b59e-0b4d94fb1f6d
Light theme is collaborator, dark theme is approver
> fix(web): Fixup the approvals flow

- app/web/cypress/e2e/web-functionality/web.cy.ts
- app/web/cypress/support/commands.ts
The tests are not actually broken but the test envs are dirty so they have issues. Turning all but the most essential bits off for now to avoid test failures caused by dirty test envs.
> temporarily ripping out tests for now

- app/web/cypress/e2e/authentication/auth.cy.ts
- app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts
> removing appModelPageLoaded again, dang it

- app/web/src/newhotness/Workspace.vue
> Fix: correctly determine head or not, so apply button doesnt show on head

- app/web/src/newhotness/ActionCard.vue
This aligns with the recent pinga changes
YOLO
> Change: action status never hits running now, only dispatched

- lib/audit-database/src/lib.rs
- lib/dal/src/audit_logging.rs
- lib/dal/tests/integration_test/audit_logging.rs
This change adds the ability to list audit logs for a component. It uses the existing audit logs infrastructure to do so and is a direct pull from @johnrwatson's work.
> Add ability to list audit logs for a component

- app/web/src/newhotness/StatusPanel.vue
This change debounces moving to "synced" state for the status indicator. This limits scenarios where the apply button can "flash".
- Open two change sets
- Create 20+ components with create actions and apply in one change set
- Quickly switch to the other change set
- Open the apply modal
- Observe the apply button remain blocked without flashing
- Once all actions complete, observe that you can apply
- Apply the second change set
> Debounce moving to "synced" state

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/layout_components/DefaultSubscriptionsEmptyState.vue
> feat(web): Adding empty state for default subscriptions

- bin/si-mcp-server/src/tools/componentDiscover.ts
When we create a component as te basis for discovery, we are going to do
the following:
1. Dequeue any actions for that component
2. If the managemenet function is successful then we cleanup the 
component
3. If the management function somehow fails, we leave the component 
available to re-run the function
https://jam.dev/c/37ca6357-90b8-4543-a03d-3d34865e8038
> feat(si-mcp-server): Enhance discovery prompt to cleanup after itself

- lib/dal/src/context.rs
Every other audit-involved location in the rebaser is spawned in a task EXCEPT for the ONE line where we write the final message. This has worked for ~10 months, so of course NOW, we hit an issue. Great day.
The compiler and integration test suite covers any possible failure this would cause.
> Make audit log flushing infallible in the rebaser

- app/web/src/newhotness/Review.vue
That header will have left and right buttons and show the selected 
component number
That header will have left and right buttons and show the selected 
component number
Also ensure that we bind the left and right arrow keys to navigate 
between the components and then that we can deselect the components and 
remove from the url
> feat(web): Add a header to the reviews page

- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- lib/vue-lib/src/tailwind/tailwind_customization/colors.json
> UI changes to get closer to Figma

- app/web/src/newhotness/ComponentHistory.vue
> feat(web): Style the Component History panel

- app/web/src/workers/webworker.ts
Did a quick pass in order to make sure that we have everything we might need for go live
> Add missing observability values

- component/toolbox/awsi.sh
- component/toolbox/scripts/check-invalidation
- component/toolbox/scripts/info
- component/toolbox/scripts/migrate
- component/toolbox/scripts/nats-cli
- component/toolbox/scripts/service-state
- component/toolbox/scripts/snapshot-garbage-collection
- component/toolbox/scripts/ssm
- component/toolbox/scripts/supporting-funcs/color-funcs.sh
- component/toolbox/scripts/toggle-maintenance
- component/toolbox/scripts/upgrade
- component/toolbox/scripts/zed-cli
Small QoL improvements for the toolbox.
* Get mad if you try to use an unsupported command
* Ensure all usages() print with `info`
* Add some color to your life
Calling invalid commands will yell
individual usage commands print
Calling `info` will print out all of the commands and their related help
> feat: toolbox cleanup and helpers

- lib/dal/src/attribute/attributes.rs
This will allow us to use not just scalars
> fix(dal): Be more explicit about the before_value in attributes audit logs

- app/web/src/workers/webworker.ts
> Adding a few more obs fields

- app/web/src/newhotness/Review.vue
Don't show object fields with object values (such as `extra` or `LaunchTemplate` in EC2::Instance). Right now we show these and they create some real noise.
If there is a *child* value in the object, it will be shown; we just don't want to show `+{}` or `+{ <bunch of defaults> }` for the object itself.
This will still show a diff for object *values* if they are items in an array or map, because even if no values were set, you need to see that there is a new item.
This does not handle deeply-nested objects (like /domain/Foo/Bar/Baz)--only top-level fields like /domain/extra. But that's most of them. Anything more will have to come when we have more schema/prop information in the diff MV.
> feat: don't show a diff for object fields

- lib/edda-server/src/materialized_view.rs
lace the future we send to `build_mv` that does the computational work
of construction a materialized view on the alternative reactor.
> fix(edda-server): put all mv build futures on slow rt

- lib/pending-events/src/lib.rs
> Add full subject for pending events

- lib/dal-test/src/lib.rs
- lib/edda-server/src/server.rs
> chore(edda): use a dedicated NATS client for frigg calls

- app/web/src/newhotness/WelcomeBanner.vue
These are the prompts that Watson has been testing and worked through
> feat(web): Chosing 3 prompts for the welcome banner

- app/web/src/components/layout/navbar/Collaborators.vue
- app/web/src/components/layout/navbar/NavbarPanelCenter.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/pages/HomePage.vue
- app/web/src/pages/auth/AuthConnectPage.vue
- app/web/src/store/change_sets.store.ts
Remove new UI feature flag.
Remove the old nav Collaborators "go to user" that would bring people into the old UI
> Remove new UI FF, and some other bits

- scripts/lago-migration/lago-migration.ts
Storing the script we used to migrate subscriptions!
> Add a script for migrating subscriptions

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/WelcomeBanner.vue
- app/web/src/newhotness/Workspace.vue
- bin/si-mcp-server/src/cli.ts
- bin/si-mcp-server/src/data/schemaAttributes.ts
- bin/si-mcp-server/src/user_state.ts
- deno.lock
Adds a banner to the web UI that only goes UI after user has started the AI Agent
> feat: Set "Executed AI Agent" flag from MCP and add warning to web

- bin/si-sdf-api-test/test_helpers.ts
- bin/si-sdf-api-test/tests/1-create_and_apply_across_change_sets.ts
Fixes the tests - https://github.com/systeminit/si/actions/runs/17384630892
> fix(sdf-api-tests): Fixup the SDF API tests to pass a change set name

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/layout_components/ShimmeringTextLine.vue
- app/web/src/newhotness/skeletons/ComponentDetailsSkeleton.vue
Skeleton will be show until the component query and the attribute tree query have completed loading
> feat: Component Details skeleton

- DEV_DOCS.md
This change adds instructions on how to update crates to the dev docs. It is based on PR #7226.
> Add instructions on how to update crates

- .github/workflows/prod-test-cron.yml
Commenting back in the e2e tests for the prod crons
> re-enabling the e2e tests in prod

- lib/luminork-server/src/service/v1/components/upgrade_component.rs
We need this for the review screen!
> fix(luminork): Adding an audit trail event for upgrade component

- component/ci-light/Dockerfile
adds docker to the ci-light image so it can be used in place of ci-base in a few places
ci will build this and that should be enough
> feat: add docker to the ci-light image

- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
> IndexUpdate: patch is optional (when index is created)

- bin/si-mcp-server/src/server.ts
- bin/si-mcp-server/src/tools/changeSetForceApply.ts
- bin/si-mcp-server/src/tools/changeSetUpdateStatus.ts
These are very distinct operations that need to happen under different circumstances and should be treated as different tools
> feat(mcp-server): Split apply change set and force-apply change set

- app/docs/src/.vitepress/config.ts
- app/docs/src/architecture/digital-twin.md
- app/docs/src/index.md
- app/docs/src/reference/architecture/ai.md
- app/docs/src/reference/architecture/change-control.md
- app/docs/src/reference/architecture/digital-twin.md
- app/docs/src/reference/architecture/engine.md
- app/docs/src/reference/architecture/functions.md
- app/docs/src/reference/architecture/index.md
- app/docs/src/reference/architecture/snapshot.md
- app/docs/src/reference/architecture/tenancy.md
- app/docs/src/reference/iac-comparison.md
- app/docs/src/reference/index.md
Adds initial set of technical docs to our docs site
Ran it locally and ensured everything looks right
<div><img src="https://media0.giphy.com/media/tTc43DeTm2kkJTrI2G/giphy.gif?cid=5a38a5a2t3dc3ebwnjlhqv05jyjdkdx08wx2pincg1srogt1&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:249px;width:300px"/><br/>via <a href="https://giphy.com/theoffice/">The Office</a> on <a href="https://giphy.com/gifs/theoffice-the-office-tv-episode-9-season-tTc43DeTm2kkJTrI2G">GIPHY</a></div>
> feat(docs): Add initial set of technical docs

- app/web/src/newhotness/Workspace.vue
the old logic was that if it didn’t get a response then it defaulted to showing the agent. Now we check to see if there’s an error in the API and if so, we hide it by default
> fix(web): Ensure we don't unnecessarily show the aiAgent banner

- scripts/lago-migration/lago-migration-fixup.ts
Checks each customer if their CURRENT active subscription is a trial and then have a pending pay_as_you_go sub, if they do not, then we need to create one
> chore(lago-script): Adding a script to update customer plans

- Cargo.lock
- Cargo.toml
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
Fixes: https://github.com/systeminit/si/security/dependabot/434
> chore(deps): Upgrade fuser to 0.16.0 to fix CVE

- app/docs/src/changelog/index.md
Also renamed Luminork to Public API as luminork is a codename
> chore(changelog): Updating changelog for previous week

- app/docs/src/what-is-si.md
> nits-for-what-is-si

- lib/edda-server/src/materialized_view/change_set.rs
This will be helpful to correlate webworker activity with edda activity and track when edda finished processing patches to when the front end processes them
Ran it locally and saw the fields in the correct spans!
<div><img src="https://media1.giphy.com/media/D3OdaKTGlpTBC/giphy.gif?cid=5a38a5a2ovxd1tvbcmbhg4akjcfoguhkrtky5o26h9njmmwl&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/><br/>via <a href="https://giphy.com/gifs/D3OdaKTGlpTBC">GIPHY</a></div>
> chore(edda): Add to/from index checksum to edda spans

- app/auth-portal/package.json
- app/web/package.json
- lib/vue-lib/package.json
- pnpm-lock.yaml
Fixes: https://github.com/systeminit/si/security/dependabot/431
Fixes: https://github.com/systeminit/si/security/dependabot/430
> chore(deps): Upgrade vite to 5.4.20

- app/web/src/newhotness/Explore.vue
> fix(web): Ensure that when bulk editing on HEAD we can create a new change set

- Cargo.lock
- Cargo.toml
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
Fixes: https://github.com/systeminit/si/security/dependabot/429
> chore(deps): Upgrade tracing-subscriber to 0.3.20

- bin/clover/src/pipelines/hetzner/funcs/management/import.ts
Fixes up the Hetzner import func so it actually works
Manually imported an ssh_key successfully.
> fix(clover): working hetzner import func

- lib/si-data-pg/src/lib.rs
Whenever the old and idle pool connection eviction runs, we're now including how long ago the oldest connection in the pool was created, and how long ago the least recently used connection is in the log message that shows how many connections were checked, and how many were evicted. This should help with investigations around dropped connections due to server-side lifetime limits.
> Add additional timing information to PgPool connection eviction logging

- bin/clover/src/pipelines/aws/pipeline-steps/specPipeline.ts
- bin/clover/src/pipelines/hetzner/pipeline-steps/createCredential.ts
- bin/clover/src/pipelines/hetzner/prop.ts
- bin/clover/src/pipelines/hetzner/spec.ts
- bin/clover/src/spec/props.ts
Gathers the correct doclinks and descriptions for hetzner assets.
See the screenshot!
> feat(clover): add correct doclinks and description for hetzner

- bin/si-mcp-server/src/tools/schemaUpsert.ts
- Refactoring to give response variables better identifiers.
- `findSchema` after `createSchema` is no longer necessary since `createSchema` now returns the schemaId
> minor improvements to schemaUpsert

- bin/clover/src/pipelines/hetzner/pipeline.ts
This generated module does not work. We will deploy this manually.
> chore(clover): remove the not-working Hetzner credential

- bin/si-mcp-server/src/server.ts
- bin/si-mcp-server/src/tools/funcUpsert.ts
This PR focusses on the correctness of creating qualification functions on schemas, it doesn't currently focus on edits.
- Edits
> feat: qualification functionating schemas new and old

- bin/clover/src/pipelines/aws/funcs/actions/awsCloudControlRefresh.ts
Removes the resource from the component if the upstream is not found via a ResourceNotFoundException during Refresh funcs. 
Tested against 5 SG's, which it correctly removes the resource when I deleted it out of the console separately from the model like a savage.
> feat: remove resource if remote resource is not found

- bin/si-mcp-server/deno.json
- bin/si-mcp-server/src/tools/funcUpsert.ts
- bin/si-mcp-server/src/validators/funcValidator.ts
- deno.lock
Additional improvements to the MCP function authoring tool as follows -
- Full upsert functionality - the tool can create new or edit existing functions
- Iterative editing is enabled by the tool returning the funcId each time it touches a function
- Forced validation of function code to ensure it is valid Typecript and in the shape of its function kind
- Code examples and context for all function kinds except action functions
- Upgrade the version of the `systeminit/api-client` used by the MCP server.
- Context improvements and adjustments for smoother usage, better error handling
This work is for [ENG-3243](https://linear.app/system-initiative/issue/ENG-3243/mcp-func-attachment
) but does not complete it yet.
Action functions are next to do and the last work left to finish …
> codegen, management, upsert, oh my!

- app/web/src/newhotness/ApplyChangeSetModal.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/nav/ChangeSetPanel.vue
- app/web/src/newhotness/nav/NavbarPanelLeft.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
Give the patching queue a priority based on the user's activity on what change sets they've selected.
Also we needed a type fix to the last PR
> Web worker patching priority

- lib/edda-server/src/materialized_view/change_set.rs
`reuse_or_rebuild_index_for_new_change_set` has not been used since the `CompressingStream` refactoring. Since the refactor, we've been calling `try_reuse_mv_index_for_new_change_set` directly, and not going through `reuse_or_rebuild_index_for_new_change_set` at all.
The only mention of this method was the definition itself:
```
❯ rg reuse_or_rebuild_index_for_new_change_set
lib/edda-server/src/materialized_view/change_set.rs
127:pub async fn reuse_or_rebuild_index_for_new_change_set(
```
> Remove unused reuse_or_rebuild_index_for_new_change_set

- bin/si-mcp-server/src/tools/funcCreateOrEdit.ts
> "function" not "functino"
