- lib/dal/src/billing_publish.rs
- lib/dal/src/change_set.rs
- lib/rebaser-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
This broke updating the head snapshot in the Admin panel. In general we shouldn't fail to update a pointer row if the billing publish fails.
This moves the billing_publish calls to the points where the rebaser
updates the pointer, which are the only two instances where the update
is relevant for billing.
> fix(dal): don't allow billing publish errors to block pointer update

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/DiagramView.vue
- app/web/src/store/feature_flags.store.ts
Basic caching to improve performance - for now, `DiagramNode` and `DiagramGroup` only cache their sockets, while `DiagramView` caches everything except the hover outline.
> basic caching for sockets and views

- lib/module-index-server/src/migrations/U0011__modules__is_private.sql
- lib/module-index-server/src/models/si_module.rs
- lib/module-index-server/src/routes/list_modules_route.rs
This is the precursor to be able to.mark a module as a private module and thus not being able to be returned in any public module searches
This doesn't change ANY of the module upload scenarios right now so this will always default to false at this stage when uploading a module thanks to:
```
let new_module = si_module::ActiveModel {
name: Set(module_metadata.name().to_owned()),
........ items here
schema_variant_id: Set(schema_variant_id),
schema_variant_version: Set(multi_part_data.schema_variant_version),
..Default::default() // all other attributes are `NotSet` <------ this is what allows things to work as normal!
};
```
> feat(module-index): Add support for private_scoped_modules

- bin/clover/src/spec/sockets.ts
When we restricted single-valued input sockets to arity=one, we inadvertently did the same for output sockets, which are often IDs that can and should be reused in multiple places.
This PR sets all output sockets to arity=many, even if they are strings or objects.
* Diffed the clover assets and verified that output socket arities were the only thing that changed
* The product doesn't presently respect this (you can connect an output socket to as many input sockets as you want), so the risk of the actual change is low.
* Loaded up the VPC asset in a local workspace and checked that I could connect its output socket to subnet input sockets.
> feat(clover): Make all AWS output sockets arity=many

- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/views.store.ts
Here is how we tested the changes in `WorkspaceModelAndView`.
First, I put the rest of the endpoint calls into a setTimeout, in order to know the diagram would load without those being called. And it does load.
Second, I removed the setTimeout and instead awaited a sleep to prevent those from calling. I wanted to know if `await` inside `onBeforeMount` would prevent the diagram from drawing. It does not.
Third; watching the network tab, `get_diagram` is the only endpoint waiting to return, and once it returns we get a diagram painted, as other calls fire.
The main culprit was the other calls inside the success handler for LIST_VIEWS, due to the nature of the ApiRequest object awaiting on the success handler. This is why nothing would load until `get_all_components_and_edges` would finish …
> Perf: fix first paint to only wait on what it needs

- app/web/src/components/ModelingDiagram/DiagramView.vue
For now, let's just not cache the icons for DiagramView to avoid having to sort out busting the cache.
> don't cache the icons for DiagramView

- bin/clover/src/specUpdates.ts
Calling buck2 in clover was always meant to be a stopgap. This removes the dependency on hoist and just calls the module index directly.
> feat(clover): call module-index directly instead of using hoist

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
Select the stuff you want to select via a drag select. Previously we'd miss or over-select the components, frames or view nodes.
> fix: hitbox calculation like a professional

- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/job/definition/compute_validation.rs
- lib/dal/src/property_editor/values.rs
- lib/dal/src/validation.rs
- lib/dal/tests/integration_test/validations.rs
This PR makes sure we correctly validate fields with default values and Joi.required(). If the field was unset (meaning it has a default), we were marking it invalid ("field is required") before.
Fixes BUG-808.
> fix(dal): Validate default values if present

- bin/clover/src/cloud-control-funcs/overrides/AWS::EC2::LaunchTemplate/import.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/pipeline-steps/attachDefaultActionFuncs.ts
- bin/clover/src/pipeline-steps/attachDefaultManagementFuncs.ts
- bin/clover/src/pipeline-steps/generateDefaultLeafFuncs.ts
- bin/clover/src/pipeline-steps/generateQualificationFuncs.ts
- bin/clover/src/spec/funcs.ts
Reverts systeminit/si#5626
Adds cloning the funcs we generate to ensure we don't modify them unexpectedly.
> Revert "Revert "feat(clover): allow overriding funcs per spec""

- app/web/src/api/sdf/dal/module.ts
- app/web/src/components/AssetCard.vue
- app/web/src/components/AssetContributeModal.vue
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/module.store.ts
- lib/dal/src/cached_module.rs
- lib/dal/src/migrations/U3600__scoped_cached_modules.sql
- lib/module-index-client/src/lib.rs
- lib/sdf-server/src/service/v2/module.rs
- lib/sdf-server/src/service/v2/module/contribute.rs
- lib/sdf-server/src/service/v2/variant.rs
- lib/sdf-server/src/service/v2/variant/list_variants.rs
- lib/si-frontend-types-rs/src/module.rs
This means that when we won't show this module in module listings and it will be available for you on all workspaces you log into
This is feature flagged and will not yet be available to users
> feat(sdf): Add ability to set a module as private when contributing

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/spec/sockets.ts
Adds the following input sockets:
* Launch Template Name
* Launch Template Id
* Launch Template Version
All of which can be driven by a launch template correctly!
Also adds a sneaky feature to createInpuytSocketFromProp that allows you to pass along a name for the resulting socket.
> chore: update AWS::AutoScalingGroup::AutoScalingGroup

- component/lambda/sql/workspace_verifications.sql
We had an alert firing because we deleted a user's free trial subscription when we added their free trial coupon. We maybe shouldn't have, but his makes the alert disappear now that we no longer care about whether therre *is* such a subscription.
> fix(billing): Don't alert when people delete expired free trial subscriptions

- bin/clover/src/cloud-control-funcs/overrides/AWS::EC2::LaunchTemplate/discover.ts
- bin/clover/src/cloud-control-funcs/overrides/AWS::EC2::LaunchTemplate/import.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Add more in depth discovery/import for EC2::LaunchTemplate to ensure we pull back in as much data as possible for the objects we find.
I've tested both funcs against existing objects in prod.
> feat: add custom discovery for EC2::LaunchTemplate

- component/lambda/sql/workspace_verifications.sql
The billing data quality alert double counts "no free trial subscription" by saying `free_trial_not_first` on the non-free-trial subscription. If there is a free trial that is not first, this will still fire. If there is no free trial at all, `no_free_trial` will fire from `subscription_count_issues`.
> fix(billing): Don't double-count "no free trial subscription"

- component/init/configs/vector.yaml
Some remapping to get the level out for handy categorization later. You can see this in action [here](https://ui.honeycomb.io/system-initiative/environments/validating-telemetry-volume/datasets/veritech3/home?tab=logs)
> feat: ship logs to honeycomb

- lib/vue-lib/src/design-system/general/SiSearch.vue
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
When a search was enabled by default on a large dropdown list, it needed a user to click to enable the search, this makes it enabled by default
So when a user clicks a dropdown list, they can immediately type
> fix(web): Set the dropdown search to be active by default

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
- bin/clover/src/spec/props.ts
* fixes the LaunchTemplate override (UserData was one prop lower than the domain and it was failing silently)
* adds propForOverride to normalize how we get props from object props, including errors and warnings
> feat: prop override convenience func

- .github/workflows/asset-push.yml
- bin/hoist/src/commands.rs
- bin/hoist/src/main.rs
- lib/si-pkg/src/spec/socket.rs
This will cause an upload of all assets.
We added socket data to to_specm but were not calling anonymize on it so the structural hash that was just upload is incorrect.
This also adds logging when using hoist non-interactively
> fix: anonymize socket data

- Cargo.lock
- Cargo.toml
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
This change pins the AWS-related crates, only used in the `lib/data-warehouse-stream-client` crate, used by Forklift. The next versions of `aws-config` (i.e. [1.6.0][aws-config-1.6.0]) and `aws-sdk-firehose` (i.e. [1.69.0][aws-sdk-firehose-1.69.0]) pull in HTTP clients that use the [aws-lc-rs] crate which contains native C code which would need to be built via Buck2.
Porting the 900-line [build script] is going to take some effort and won't be a quick solve...
[aws-config-1.6.0]: https://crates.io/crates/aws-config/1.6.0
[aws-sdk-firehose-1.69.0]: https://crates.io/crates/aws-sdk-firehose/1.69.0
[aws-lc-rs]: https://github.com/aws/aws-lc-rs
[build script]: https://github.com/aws/aws-lc-rs/blob/main/aws-lc-sys/builder/main.rs
> build(deps): pin `aws-config`/`aws-sdk-firehose` to prevent native code

- bin/auth-api/src/routes/workspace.routes.ts
The tracking event was happening in the for list for the users so removing a user from a workspace with 5 emails - 4 emails to the user being removed
> fix(auth-api): Prevent sending multiple transactional emails when removing a user

- bin/clover/src/spec/props.ts
- bin/clover/src/specPipeline.ts
- bin/hoist/src/diff.rs
- bin/hoist/src/main.rs
- Correct the way in which hoist is hashing modules locally
- Prop inputs and widgetOptions for root props now start as null instead of empty arrays
- Added a new diffing strategies to take schema changes
> feat(hoist, clover): Make props more similar to the shapes the take when created by rust

- bin/auth-api/src/routes/workspace.routes.ts
- bin/auth-api/src/services/workspaces.service.ts
In the old way, we would look up a user by email - we already have the users for the workspace so we can use that workspace membership and find the correct userPk to remove based on that membership list + then safely remove that user
We no longer generate transactional emails when a request to remove happens but the user doesn't get removed - lets say for something like multiple emails in the database for the same person
> fix(auth-api): More elegant solution for removing a user from a workspace

- lib/dal/src/component.rs
- lib/dal/tests/integration_test/component/delete.rs
To clean up frames during destroy actions, we check to see if the frame has a resource by finding the attribute value for `root/resource` by prop path. If there are multiple components for the same schema variant, and one has been deleted, but the snapshot hasn't been cleaned up, we'll stumble on the attribute value for that deleted component and returning an error, causing the component we're trying to delete to remain, leaving ghosted frames incorrectly.
I debated cleaning up the snapshot when the component is deleted, but figured there are other sneaky instances where we're looking for a specific attribute value for a component and there could be deleted components in that snapshot of the same kind. 
<div><img src="https://media2.giphy.com/media/uUJdyR6h1zPHvPROSC/giphy.gif?cid=5a38a5a2 …
> fix(dal): Don't error when finding Attribute Values for components that are being deleted

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
I need:
1. AWS::EC2::SecurityGroup
a. createOutputSocketFromProp(GroupName)
2. AWS::EC2::SecurityGroupEgress
a. createOutputSocketFromProp(DestinationSecurityGroupId)
3. AWS::EC2::SecurityGroupIngress
a. createInputSocketFromProp(SourceSecurityGroupId)
b. createInputSocketFromProp(SourceSecurityGroupName)
> feat: add appropriate input and output sockets to sg schemas

- .cargo/config.toml
- .envrc
- Cargo.lock
- Cargo.toml
- flake.nix
- lib/telemetry-application-rs/BUCK
- lib/telemetry-application-rs/Cargo.toml
- lib/telemetry-application-rs/src/lib.rs
- lib/telemetry-rs/src/lib.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
- third-party/rust/fixups/tokio/fixups.toml
- toolchains/BUCK
This change adds a signal listener to all Rust `bin/*` binaries, that upon receiving a `SIGQUIT` signal, will write a "process report" file to the temp file system, named with the service name and second-resolution timestamp. This report currently prints a trace for every currently spawned task on the main Tokio runtime.
The file looks something like this (appologies for the Markdown escapes, it's the only way to render in a Git commit message *and* GitHub PR message without being dropped):
```
\# veritech Report (2025-03-12T16:59:18Z)
\## Tokio Task Traces
\### Task 0 Trace
\```
╼ <core::pin::Pin<P> as core::future::future::Future>::poll at /nix/store/yxdqfnnr48j8m5h00806i4l2vqi4fiyr-rust-default-1.84.1/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9 …
> feat: add a `SIGQUIT` listener that writes a Tokio tasks report file

- lib/dal-test/src/expected.rs
- lib/dal-test/src/test_exclusive_schemas/legos/small.rs
- lib/dal/src/attribute/prototype/debug.rs
- lib/dal/src/component/socket.rs
- lib/dal/src/func/runner.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/socket/debug.rs
- lib/dal/tests/integration_test/frame.rs
- lib/dal/tests/integration_test/management.rs
This adds inferred connections to `thisComponent.incomingConnections` when running a management func. This means that if your management component lives inside an AWS Credential and Region (and has inferred connections to them because of parentage), your component will get those connections and be able to pass them on to components it creates or manages.
Refactor budget: updated paste.rs and management.rs tests to use `Result<>`
* Tested manually with components in the UI
* Created management function in Subnet and verified it received AWS Credential and Region inferred connections
* Integration tests
> feat(sdf): Add inferred connections to incomingConnections in management funcs

- lib/dal/src/actor_view.rs
- lib/dal/src/change_set.rs
- lib/dal/src/context.rs
- lib/dal/src/diagram.rs
- lib/dal/src/history_event.rs
- lib/dal/src/key_pair.rs
- lib/dal/src/module.rs
- lib/dal/src/pkg.rs
- lib/dal/src/pkg/export.rs
- lib/dal/src/standard_model.rs
- lib/dal/src/user.rs
- lib/dal/src/workspace.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/tests/integration_test/resource_metadata.rs
- lib/dal/tests/integration_test/secret/with_actions.rs
- lib/dal/tests/integration_test/workspace.rs
- lib/rebaser-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
- lib/sdf-server/src/service/module.rs
- lib/sdf-server/src/service/module/approval_process.rs
- lib/sdf-server/src/service/module/import_workspace_vote.rs
- lib/sdf-server/src/service/session.rs
- lib/sdf-server/src/service/session/auth_connect.rs
- lib/sdf-server/src/service/session/restore_authentication.rs
- lib/sdf-server/src/service/v2/admin/set_concurrency_limit.rs
- lib/sdf-server/src/service/v2/audit_log.rs
- lib/sdf-server/src/service/v2/audit_log/list_audit_logs.rs
- lib/sdf-server/src/service/v2/module/builtins.rs
- lib/sdf-server/src/service/v2/workspace.rs
- lib/sdf-server/src/service/v2/workspace/install_workspace.rs
This does the same thing as get_by_id, for the two things with _pk. I did not rename to _id because I didn't want to take on the work of renaming the type (WorkspacePk -> WorkspaceId) here.
This removes a few unnecessary Workspace/UserNotFound error types and relies on WorkspaceError::WorkspaceNotFound/UserError::UsernotFound instead, but there are no real logic changes, just rename / use underlying error.
* Integration tests
* Dragged out a component in the diagram
> chore(dal): User/Workspace::get_by_pk_or_error -> get_by_pk

- Cargo.lock
- Cargo.toml
- bin/cyclone/src/args.rs
- bin/cyclone/src/main.rs
- bin/forklift/src/args.rs
- bin/forklift/src/main.rs
- bin/module-index/src/args.rs
- bin/module-index/src/main.rs
- bin/pinga/src/args.rs
- bin/pinga/src/main.rs
- bin/rebaser/src/args.rs
- bin/rebaser/src/main.rs
- bin/sdf/src/args.rs
- bin/sdf/src/main.rs
- bin/veritech/src/args.rs
- bin/veritech/src/main.rs
- flake.nix
- lib/telemetry-application-rs/BUCK
- lib/telemetry-application-rs/Cargo.toml
- lib/telemetry-application-rs/src/lib.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
- third-party/rust/fixups/console-subscriber/fixups.toml
This change adds a new CLI flag of `--tokio-console` which will enable collection and transmission of Tokio runtime telemetry for use with the [tokio-console] debugging tool.
By default, the responsible subscriber will not be active as there is a potential for performance impact.
To enable this mode in any of the Rust services there are 2 ways to do this:
- Add a `--tokio-console` flag to the CLI when starting
- Export `SI_TOKIO_CONSOLE=true` when running a service
[tokio-console]: https://github.com/tokio-rs/console
> feat: add optional support for tokio-console in all Rust services

- Cargo.lock
- Cargo.toml
- lib/cyclone-server/src/vsock.rs
- lib/si-firecracker/src/stream.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
We've been using the 0.4.0 release which came out in January 2023, so we're over 2 years behind. Not a ton of updates but a few appear to be useful:
- [feat!: Mirror tokio Stream Api with split and into_split](https://github.com/rust-vsock/tokio-vsock/commit/010b9656304572cc99002bdefffadf04e3c40a85)
- [feat(split): Rely on tokio's sync primitives](https://github.com/rust-vsock/tokio-vsock/commit/428289902789c40968068dec4599dcb20cf711e8)
- [fix: Use VsockAddr instead of cid and port where appropiate](https://github.com/rust-vsock/tokio-vsock/commit/d4111939599f82ee91cf12a875f0d94f92333657)
Additionally, this transitively updates the `vsock` crate from 0.3.0 to 0.5.1 with several update of note:
- [Timeouts: SendTimeout/write ReadTimeout/read](https://github.com/rust-vsock/vsock-rs/commit/68 …
> build(deps): upgrade tokio-vsock from 0.4.0 to 0.7.0

- bin/veritech/src/args.rs
- component/init/configs/service.toml
- lib/si-firecracker/src/errors.rs
- lib/si-firecracker/src/firecracker.rs
- lib/si-pool-noodle/src/instance/cyclone/local_uds.rs
- lib/veritech-server/src/config.rs
- lib/veritech-server/src/server.rs
This PR allows firecracker setup script creation to be skipped. This is useful for a variety of reasons: getting a new rootfs, changing the script itself, and more.
This PR also fixes a config mismatch in veritech where pinga's concurrency limit will be derived for all global merged configurations. Until we fix the "pool exhausted == NACK counting towards max failed message count" problem, we cannot afford the concurrency limit to be higher than the pool size. Now, we will be able to individual customize.
Why not pursue a dynamic solution where the concurrency limit is equal to the pool size by default? A bit of magic lies in there as well as a potential side effect to the other runtime strategies (local process and docker). We are really only trying to target the use of concurrency limit …
> Allow firecracker creation skip and fix config mismatch in veritech

- app/web/src/components/WorkspaceIntegrationsModal.vue
- app/web/src/store/workspaces.store.ts
- lib/sdf-server/src/service/v2/change_set/approve_v2.rs
- lib/sdf-server/src/service/v2/integrations.rs
- lib/sdf-server/src/service/v2/integrations/update_integration.rs
- lib/si-events-rs/src/audit_log/v1.rs
Also includes an audit trail event for the change of webhook url
> fix(sdf): Ensure that only workspace approvers can change Slack Webhook URL

- lib/si-firecracker/src/firecracker.rs
- lib/si-firecracker/src/scripts/firecracker-setup.sh
I've tested this on a duplicate Veritech node in terms of resolving the configuration and it all looks good/runs through successfully, see output below:
```
[root@ip-12-0-10-131 ~]# cat $VERITECH_CGROUP/cpuset.cpus.partition
root
[root@ip-12-0-10-131 ~]# cat $VERITECH_CGROUP/cpuset.cpus
0-15
[root@ip-12-0-10-131 ~]# cat $VERITECH_CGROUP/cpuset.mems
0
[root@ip-12-0-10-131 ~]# cat /sys/fs/cgroup/veritech/cgroup.subtree_control
cpuset
[root@ip-12-0-10-131 ~]# cat "$FIRECRACKER_CGROUP/cpuset.cpus.partition"
member
[root@ip-12-0-10-131 ~]# cat  "$FIRECRACKER_CGROUP/cpuset.cpus"
16-63
[root@ip-12-0-10-131 ~]# cat "$FIRECRACKER_CGROUP/cpuset.mems"
0
``` 
These are extremely difficult to test without merging, I believe I have done best effort here.
> Properly configure cgroups for Veritech & Firecracker

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/components/ModelingView/ModelingRightClickMenu.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/components.store.ts
- app/web/src/store/feature_flags.store.ts
- lib/vue-lib/src/design-system/modals/Modal.vue
- Type `C` when interacting the diagram to open the connections menu
- Choose a pair of sockets and it should connect
- Stills allows for bad connections to be attempted, this will come in a future PR
- Can be opened up via a commandBuffer event
- Unlocks the diagram changes we need to do for the connections work
- Behind `floating-connection-menu` feature flag
> feat(web): Initial floating connections menu

- lib/si-firecracker/src/scripts/firecracker-setup.sh
If Veritech paniced, or otherwise didn't sigterm correctly sometimes lingering jails and devices can be left behind, preventing veritech restarting as it can't attach to the devices.
This ensures that on startup there are definitely no firecracker processes running.
I've tested this on a veritech replica in tools.
> fix: clear up lingering jails which can be present after upgrade

- app/web/src/api/sdf/dal/component.ts
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/components/ModelingView/AutoconnectMenu.vue
- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/components.store.ts
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/component.rs
- lib/dal/tests/integration_test/component/autoconnect.rs
- lib/sdf-server/src/service/component.rs
- lib/sdf-server/src/service/component/autoconnect.rs
- lib/sdf-server/src/service/component/override_with_connection.rs
- lib/sdf-server/src/service/component/restore_default_function.rs
- lib/sdf-server/src/service/diagram/create_connection.rs
- lib/si-frontend-types-rs/src/component.rs
- lib/si-frontend-types-rs/src/lib.rs
This PR modifies the 'Autoconnect' logic and adds a user experience to accomodate.  Currently, when a user triggers autoconnect, if we find that there are multiple components/output sockets that could replace a manually set value, we do nothing and say 'No connections found'.  With this PR, we will accumulate the possible connections that *could* be made, and display those options so that the user can decide for themselves without having to manually go figure out where the options are in their workspace.
The UI also helps ensure the user doesn't accidentally do the wrong thing. For example, if the input socket in question is multi-arity, there are two 'flavors' of connections that can work: 
1. There could be an output socket somewhere that has that whole array (called "bulk" mode). There …
> feat(dal,web): Enable users to select which connections they want to create if Autoconnect detects too many options

- lib/si-firecracker/src/scripts/firecracker-setup.sh
We run the script with pipefail. Under the condition there are no jails to cleanup, we must still return 0 otherwise the orchestration will fail.
NB: there are probably 6-7 million better ways of doing this, but this is perfectly acceptable.
> fix: this must continue on failure if there are no jails

- bin/veritech/veritech.service
Okay. Last one. I promise.
When we Veritech run via systemd, the pkill doesn't catch the jails when running in the firecracker-setup.sh but it does when running firecracker via buck2 locally. Honestly? I'm not sure why this is the case at all, as when running the pkill on the host directly when veritech is running it `does` clean the pids up correctly. I imagine this might be something to do with cgroup inference/parental tree. Nevertheless, this sticks the cleanup as a pre-req and post-req in the systemd unit file definition for veritech so that:
- Before veritech even starts, there are no jails
- After veritech stops, any jails lingering are terminated
This explicitly ensures we issue a pkill when both starting and stopping  veritech via the systemd service. I'm leaving the original …
> fix: when running via systemd, ensure we clean up lingering jails

- Cargo.lock
- bin/cyclone/src/main.rs
- bin/forklift/src/main.rs
- bin/pinga/src/main.rs
- bin/rebaser/src/main.rs
- bin/sdf/src/main.rs
- bin/veritech/src/main.rs
- lib/si-service/BUCK
- lib/si-service/Cargo.toml
- lib/si-service/src/lib.rs
This PR disables our tokio watchdog in si-service apps. This was useful in earlier verideath investigation sessions, but we no longer need it. Not only that, but the data returned was not entirely helpful nor could we verify its accuracy. Given that this is spawned with every backend service and sends INFO level logs to Honeycomb, we have decided to remove it from "si-service". This will also slightly speed up compile times for all services due to its removal from the "si-service" crate.
> Disable tokio watchdog in si-service apps

- bin/veritech/src/args.rs
- lib/veritech-server/src/config.rs
- lib/veritech-server/src/heartbeat.rs
- lib/veritech-server/src/server.rs
This PR removes force reconnect logic and metrics from the veritech heartbeat app. This was useful during earlier verideath investigation efforts, but having a side effect force reconnection in the heartbeat app is unnecessary nor a great idea in a long term.
> Remove force reconnect from heartbeat app

- lib/veritech-server/src/publisher.rs
- lib/veritech-server/src/server.rs
This metric was used for earlier verideath investigation and is too rapid to be reliable and can be generally spammy.
> Remove publisher in progress metric

- lib/si-filesystem/src/inode_table.rs
- lib/si-filesystem/src/lib.rs
Removes the typescript config that triggers the native typescript LSP, in favor of only supporting Deno. The TypeScript LSP will always be wrong-er than the Deno LSP.
It also relaxes some settings to reflect the values we have in the browser (which does not use the Deno LSP, so now it will be wrong sometimes, but.. that is a problem for another PR).
> bug: fixing the deno lsp with the si-fs

- bin/si-api-test/benchmark/func_stampede.ts
- bin/si-api-test/run.py
- bin/si-api-test/sdf_api_client.ts
- bin/si-api-test/test_helpers.ts
- bin/si-api-test/tests/7-emulate_authoring.ts
To aid in testing/measuring the performance of function execution, this new test takes advantage of the ability to test function executions, where SDF dispatches functions directly to veritech without a Pinga Job.  
I've also included a helpful python script we've been using to execute these tests and some instructions on how to use it!
<div><img src="https://media3.giphy.com/media/3oEjI1erPMTMBFmNHi/200.gif?cid=5a38a5a22pcxzyj1eo4i82sosoey5mrevvpxnv2egzu5t355&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:171px;width:300px"/><br/>via <a href="https://giphy.com/gameofthrones/">Game of Thrones</a> on <a href="https://giphy.com/gifs/game-of-thrones-3oEjI1erPMTMBFmNHi">GIPHY</a></div>
> feat(si-api-test): Add a new benchmarking test to trigger a stampede of func executions bypassing DVU

- .github/workflows/jsr-publish.yml
Takes the name of a library based on lib/jsr-systeminit and then runs a publish inside that library
> chore(ci): Add workflow dispatch for jsr publish

- lib/dal/src/action/dependency_graph.rs
- lib/dal/tests/integration_test/action.rs
Before this change, we were calculating the order for actions based only on the components with actions enqueued and their direct dependencies. This meant if you had Component A (with action) ---edge to --> Component B (no action) -- edge to --> Component C (with action), we would not detect that Action C should depend on Action A.  
With this change we now build a more full tree of component dependencies, and use petgraph's depth_first_search to find the closest dependency for a given component's action, which allows us to capture these transitive dependencies. 
TESTING
I added an integration test covering both forwards and backwards transitive dependencies (forwards applies to create/update/manual actions, backwards applies to destroy actions)
<div><img …
> fix(dal): Calculate Action Dependencies using DFS to capture transitive dependencies between components

- lib/sdf-server/src/service/action.rs
If you hit cancel multiple times fast, there's a chance the second request could have thrown a 500 as the node is now gone from the snapshot
We now throw a 410 when that's the case on cancel
Before:
After:
> fix(sdf): Catch Node Not Found error on action cancel

- Cargo.lock
- Cargo.toml
- lib/dal/src/approval_requirement.rs
- lib/dal/src/entity_kind.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/graph/detector.rs
- lib/dal/src/workspace_snapshot/graph/traits/approval_requirement.rs
- lib/dal/src/workspace_snapshot/graph/v4.rs
- lib/dal/src/workspace_snapshot/graph/v4/approval_requirement.rs
- lib/dal/src/workspace_snapshot/traits/approval_requirement.rs
- lib/si-events-rs/src/workspace_snapshot.rs
- lib/si-split-graph/BUCK
- lib/si-split-graph/Cargo.toml
- lib/si-split-graph/src/lib.rs
- lib/si-split-graph/src/opt_zip.rs
- lib/si-split-graph/src/subgraph.rs
- lib/si-split-graph/src/subgraph_address.rs
- lib/si-split-graph/src/tests/mod.rs
- lib/si-split-graph/src/updates.rs
A new crate, lib/si-split-graph, containing an initial, generic implementation of a merkle tree hashed graph which can be split into multiple "subgraphs" but allows edges between nodes in different subgraphs. Calculates updates, performs them, and handles the "ordering" concept internally.
This is not yet integrated with the si "dal", and will likely require more changes before that is possible.
> feat: si-split-graph

- app/web/src/components/FuncEditor/FuncTest.vue
- app/web/src/components/FuncEditor/FuncTestSelector.vue
This PR sanitizes attribute func test options for output locations. Specifically, it makes sure all options are available _and_ selectable. It intentionally leaves the func test experience alone.
> Sanitize attribute func test options

- Cargo.lock
When I open the site in my local dev environment, cargo makes this lockfile update - this feels like it was missing from an older PR
> chore(build): Cargo lockfile update

- lib/dal/src/func/runner.rs
This PR adds the code in plaintext to existing info spans for funcs executed via the func runner. This does not increase the number of spans. It adds metadata to existing ones.
> Add code body to info span for func runner

- .github/workflows/asset-update.yml
https://github.com/systeminit/si/actions/runs/14013774191/job/39236797092
```
Task run deno run --allow-all main.ts "infer-ai"
error: Missing required environment variable "OPENAI_API_KEY".
```
> fix(clover): add missing api key for asset update

- lib/dal/src/cached_module.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/migrations/U3700__scoped_cached_modules.sql
- lib/sdf-server/src/migrations.rs
- lib/si-pkg/src/pkg/schema.rs
- lib/si-pkg/src/pkg/variant.rs
Now that management functions can create components for any known asset (including ones that are not yet installed), we need to send the socket count for uninstalled assets in `variantSocketMap`. This PR:
* Caches socket count in sdf cache for uninstalled assets
- automatically cached when downloading new modules/versions from the module index
- automatically added when contributing a private module
- automatically fills in missing socket counts for existing modules when sdf first starts up after upgrade
* Includes socket count for both installed and uninstalled assets in variantSocketMap
**Guide:** this PR has comments throughout pointing out the salient bits.
> feat(sdf): Include socket count for uninstalled modules in variantSocketMap

- BUCK
- deno.json
- deno.lock
- lib/jsr-systeminit/ecs-template-qualification/BUCK
- lib/jsr-systeminit/ecs-template-qualification/DEV.md
- lib/jsr-systeminit/ecs-template-qualification/deno.json
- lib/jsr-systeminit/ecs-template-qualification/mod.ts
- lib/jsr-systeminit/ecs-template-qualification/mod_test.ts
Adds a JSR library to help manages ECS task validation when Fargate is in use. Has every valid combination of CPU and Memory!
Hooray for test coverage.
> feat: add library for validating CPU/memory configurations for fargate

- lib/dal/src/change_set.rs
- lib/dal/src/component.rs
- lib/dal/src/context.rs
- lib/dal/src/diagram.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/selector/mod.rs
- lib/sdf-server/src/dal_wrapper/change_set.rs
This enum will make it possible for us to swap in the split graph for
the current and soon-to-be-legacy graph seamlessly without massive
changes to the DAL code. Only has one variant now, for the current
WorkspaceSnapshotGraph.
> chore: WorkspaceSnapshotSelector enum for split-graph integration

- .ci/docker-compose.test-integration.yml
- .ci/generate-creds-from-iam-role.sh
Sets the ci-base to the ecr pull-through target. Here is a working try
https://buildkite.com/system-initiative/si-merge-queue/builds/5158#0195d7f6-7690-42ca-83b1-1fc1c782a8e1
that shows
> :docker: Running command in 179845983369.dkr.ecr.us-east-2.amazonaws.com/docker-hub/systeminit/ci-base:stable
> feat: pull ci-base from ecr

- app/web/package.json
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/store/components.store.ts
- pnpm-lock.yaml
- Options are now filtered via fuzzy search
- tab now selects the highlighted socket (enter key does the same thing, shift+tab undoes selection)
- the active side of the connections menu is highlighted too
- Fixes a bug on the peer socket calculations that would count unary connected sockets as possible connection candidate
> feat(web): Add fuzzy search to floating connections menu

- component/init/configs/service.toml
Added to prod [here](https://systeminit.slack.com/archives/C084J3EJABG/p1743104458788359)
Gives us a separate value so we can configure a separate proxy host for the layer cache
> chore: create separate config value for layer db host

- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/utils/childrenByBoundingBox.ts
- app/web/src/components/ModelingView/ModelingRightClickMenu.vue
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/views.store.ts
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/convert_to_view.rs
This takes all of the contents of a generic frame, reparents the contents of the frame, if necessary, and creates a new view with a view diagram object in it's place
If the user does this on a up or down frae, it will move the items directly and not delete or reparent
> feat(web, sdf): Add ability to convert a frame to a view

- lib/dal/src/func/runner.rs
Undoes (not reverts) changes from d6e343b (https://github.com/systeminit/si/pull/5747) to remove code plaintext span metadata. This wasn't being used at all and could prove to be expensive (with time) to populate.
> Remove code plaintext span metadata

- app/web/src/store/apis.web.ts
Using an ID with a toast means a new toast should replace an old toast. Which will appear as a "toast that never goes away"... but not one million toasts that take up the entire screen.
> Prevent: one million toasts for maintenance or downtime mode

- app/web/src/components/ModelingDiagram/DiagramGroup.vue
- app/web/src/components/ModelingDiagram/DiagramNode.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_constants.ts
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/store/components.store.ts
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/views.store.ts
https://github.com/user-attachments/assets/442eb3cc-dc2c-4583-a61b-32f3504ad06b
This turn does not allow for edges to be properly edited on the diagram or viewed in the EdgeDetailsPanel yet. That will be added in the next turn, so for now the feature flag should be kept off unless working on this feature.
Huge thank you to @jobelenus for his help on this beast of a PR 😅
> feat(web) - simpler sockets UI with just one input and one output socket

- lib/dal/src/schema/variant.rs
- lib/dal/src/secret.rs
- lib/dal/src/secret/definition_view.rs
- lib/dal/src/secret/view.rs
- lib/sdf-server/src/service/secret.rs
- lib/sdf-server/src/service/secret/create_secret.rs
- lib/sdf-server/src/service/secret/delete_secret.rs
- lib/sdf-server/src/service/secret/list_secrets.rs
- lib/sdf-server/src/service/secret/update_secret.rs
Two big changes here:
1. Don't use `list_user_facing` which does a ton of extra work when all we want is the active variants.
2. Prefetch all the secret prop ids in one query, instead of doing it for every secret
> fix(dal): make secrets list fast

- lib/dal/src/materialized_view.rs
- lib/sdf-server/src/service/v2/index.rs
- lib/si-frontend-types-rs/src/reference.rs
For the new frontend architecture, this PR updates the index if reference kinds found in the existing index do not match what is currently available. This is useful when new types are added to the system, but an existing system needs a new index to know that they exist.
This takes about ~200ms when it happens, which we should keep an eye on when equivalent functionality moves to "edda".
In the case of a rolling update with multiple SDF instances, it is possible for both SDF instances to update the index. This is unlikely given that a tenant will likely be "speaking" to one SDF _and_ that this is a stop-gap solution until "edda" takes on this behavior. However, it is worth calling out.
> Update index if reference kinds do not match

- lib/sdf-server/src/service/component/update_property_editor_value.rs
We enqueue an update action downstream even if the value hasn't changed
> fix(sdf): Only enqueue update functions if the values have changed

- app/web/vite.config.ts
Moves the `manifest.json` to the root of the dist when building via vite. This ensure we don't need to do any redirect hopping prone to cors and content blocking issues.
> fix(web): move manifest to the root of the dist

- app/web/src/components/ComponentDetailsManagement.vue
- app/web/src/components/ManagementRunPrototype.vue
- app/web/src/store/func_runs.store.ts
If you look at the logs for a running function, they stay static forever until you reload. This PR makes it so that we stream new logs whenever they become available, by calling GET_FUNC_RUN when we see FuncRunLogUpdated. We only do this if the func run is cached, to prevent unnecessary network usage.
> feat(web): Stream management function logs while they are running

- lib/si-data-nats/src/subscriber.rs
- lib/veritech-client/src/lib.rs
When there are a lot of logs for a function, we don't upload or report them.
This PR fixes this by leaving the output processor running until all logs have been processed.
Fixes BUG-811.
> fix(sdf): Don't truncate logs

- app/web/src/components/CodeEditor.vue
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
Fixes:
- CodeEditor displaying the updated socket values
- The highlightedSocket wasn't reactive to ComponentUpdated
- Socket list re-drawing with virtualization as connections are created/deleted
- Virtualization options needed to be computed (wasn't intuitive), and with the height changing we needed to specify it (the HTML diff is garbled, its just adding a single containing div)
> Fix: reactivity for code editor & virtualization in the new connections palette

- app/web/src/components/ComponentDetailsManagement.vue
- app/web/src/components/ManagementRunPrototype.vue
- app/web/src/components/ModelingView/ModelingRightClickMenu.vue
This PR is a bit of a stop gap, while we don't have coordination between Management Functions and DVU yet, we do have the data on the front end to know if a Component is currently being impacted by DVU.  Use this data to block the ability for users to trigger a management function while a component is being updated to reduce the risk of management functions executing on stale data.
Tested by creating a qualification with a sleep, and seeing that the right click menu and management functions panel are reactive to the Component status changing as DVU starts/stops. 
<div><img src="https://media3.giphy.com/media/htVOLW8TStuLFlUAvG/200.gif?cid=5a38a5a2t3qpxzeada3ccuiww2kag2nsrggc92ie5q089dkn&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:170px;width:300px"/><br/>via <a …
> fix(web): Prevent users from triggering management functions for a component currently being updated

- bin/clover/src/cloud-control-funcs/overrides/AWS::ECS::TaskDefinition/actions/update.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
This overrides the update function on AWS::ECS::TaskDefinition with a new one, which registers a new task definition via the same process as 'create' instead, and then runs the refresh function inline.
> feat: override update on AWS::ECS::TaskDefinition

- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- lib/vue-lib/src/design-system/modals/Modal.vue
Repro steps:
1. select a component
2. hit `c`
3. see the input has focus ✅ 
4. click the modal title bar
5. hit backspace/del ❌ 
the Modal "chrome" clicks were removing focus
I also got rid of the "read only" code editor in the display
> Fix: force "teleport" input to always have focus

- app/web/vite.config.ts
Currently `build` already produces a `comlink` chunk. But that may not always happen in the future. So I added it to `manualChunks`
I tested this by running build with "myspecialcomlink" (rather than "comlink") to ensure that the built file would match mine. 
I don't see `projectEnvVariables` as an output, or `dynamicEnvVars.ts` as an input during the build process.. so I removed that.. happy to add that back if it was incorrect.
And the header changes for this file are in this SI changeset on tools:
> During app/web `pnpm build` force a comlink chunk

- app/web/src/components/LeftPanelDrawer.vue
here is the error from Jacob:
here is the built code:
```
return ee.setQueryData(he, Ae => (Ae || (Ae = {
id: sl("new list id"),
views: []
}),
Ae.views = [...Ae.views, {
id: sl("new-view-id"),
name: oe,
isDefault: !1,
created_at: new Date().toLocaleString(),
updated_at: new Date().toLocaleString()
}],
```
Here is the code I wrote:
```
if (!old) {
old = {
id: _.uniqueId("new list id"),
views: [],
};
}
old.views = [
...old.views,
{
id: _.uniqueId("new-view-id"),
name: newName,
isDefault: false,
created_at: new Date().toLocaleString(),
updated_at: new Date().toLocaleString(),
},
];
```
Which means... that `old` exists as something?! but it doesn't have a views property as an array like we expect. So I'm gonna slam this in here
> Fix: unexpected type mismatch or bad data

- Cargo.lock
- Cargo.toml
- bin/pinga/src/args.rs
- bin/rebaser/src/args.rs
- bin/sdf/src/args.rs
- lib/si-data-pg/src/lib.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
These settings were changed when we added pgbouncer to better handle migrations. Pgbouncer recommends sending a `RECONNECT` after DDL changes to reset the open transactions and `RESET ALL` in order to clear the prepared statement cache. Without doing these, we were seeing open connections serving the incorrect schema.
We have now switched to using RDS Proxy, which, after DDL changes, purports to close the transaction and clear the prepared statement cache. Because of this, I believe it is safe to change back to using Fast recycles here.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.howitworks.html
Unfortunately, the only way to test this is to create a new database migration and see how it handles.
This PR allows us the configure the recycle method. Setting `Custom` …
> chore: make pg recycle method configurable

- lib/edda-client/src/lib.rs
- lib/edda-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
- lib/sdf-server/src/service/v2/index.rs
This PR instruments the lifecycle of an edda request. Specifically, it ensures that we can start from a span of another service and use either child spans or an edda request ID to discern what happened during the life of an edda request.
> Instrument the lifecycle of an edda request

- component/lambda/sql/workspace_operations.sql
- component/lambda/sql/workspace_verifications.sql
PostgreSQL (or maybe Redshift's version of it) throws a parse exception when you try to parse `2025-04-03T22:19:42.999999945Z` as a timestamp.
This is because it rounds the fractional seconds to microseconds, and then throws an exception if it's >= 1 (because fractional seconds can't be 1!). While PostgreSQL should handle this, we need our billing pipeline not to break :)
The fix here is to truncate our timestamps to microseconds before parsing them. The original data in forklift still contains all the precision you could ever want.
> fix(billing): Work around SQL being unable to parse nanoseconds >= .9999995

- bin/clover/src/cloud-control-funcs/overrides/Listener DefaultActions/attribute/setTargetGroupArns.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
When a new TargetGroupArn was created via a AWS::ElasticLoadBalancingV2::TargetGroup the previous entry on Listener DefaultActions wasn't overwritten, instead a new value was added to the array causing an error.
> fix: fix dupe targetgrouparn bug

- app/web/src/components/CodeEditor.vue
Testing steps:
1. I can type in the code editor for an unlocked function without it remounting and taking the cursor focus away
2. I can see the code editor values update in the connections panel between a butane and docker images when i change values/make connections
> Fix: dont watch on modelValue unless the Editor is disabled

- app/web/vite.config.ts
Test: `pnpm build` the dist/index.html file uses a main.js file with a hash on it
> Update: main.js should always have a hash on it

- lib/module-index-server/src/extract.rs
- lib/module-index-server/src/routes/download_builtin_route.rs
- lib/module-index-server/src/routes/download_module_route.rs
- lib/module-index-server/src/routes/download_workspace_route.rs
- lib/module-index-server/src/routes/promote_builtin_route.rs
- lib/module-index-server/src/routes/reject_module_route.rs
- lib/module-index-server/src/routes/upsert_builtin_route.rs
- lib/module-index-server/src/routes/upsert_module_route.rs
- lib/module-index-server/src/routes/upsert_workspace_route.rs
- lib/module-index-server/src/s3.rs
Allows the module-index to generate urls for either s3 directly or cloudfront. If the cloudfront config is empty (the default), we behave exactly the same as we do now, so this should not cause any behavioral changes until config changes happen.
If the cloudfront domain is set, gets for modules or exports will go through cloudfront, leveraging the cdn. This should allow for cache rebuilds to be faster and generate less overall traffic it to S3. This will likely make the biggest difference in local development, but only if the cloudfront url is configured. We can configure this by default after the production instance is deployed successfully.
> feat(module-index): allow specifying a cloudfront domain

- app/web/src/components/CachedAppNotification.vue
Local testing steps: 
1. as is, you'll never get the notification (makes total sense locally)
2. load the app, view source, grab the src of the script module with "main"
3. comment out the line `const latestAppFileWithHash`
4. add a line setting that variable with the value from html (e.g. `const latestAppFileWithHash = "/src/main.ts?t=174413768944";`)
5. refresh the app--no notification
6. change a number on that string.. you get the refresh
> Fix: cached app notification

- bin/lang-js/src/component.ts
- bin/lang-js/src/function_kinds/management.ts
- lib/cyclone-client/src/client.rs
- lib/cyclone-core/src/component_view.rs
- lib/cyclone-core/src/lib.rs
- lib/cyclone-core/src/management.rs
- lib/dal/src/func/backend/management.rs
- lib/dal/src/func/binding/management.rs
- lib/dal/src/management/prototype.rs
- lib/dal/tests/integration_test/management.rs
- lib/veritech-client/src/lib.rs
- lib/veritech-client/tests/integration.rs
Adding an `incomingConnections` field to every component, rather than just the input component.
> feat: add incoming connections to mgmt functions components

- component/lambda/functions/si_lambda.py
- component/lambda/functions/si_posthog_api.py
- component/lambda/functions/si_types.py
- component/lambda/functions/upload-billing-hours.py
- component/lambda/functions/upload-posthog-billing-data.py
- component/lambda/functions/workspace_delegations_population.py
- component/lambda/sql/workspace_operations.sql
This uploads one event per hour per workspace showing the workspace's resource count. The value is chosen such that SUM(resource_count) for a given owner_pk is the same as the billing resource hours for that user (and thus if it is over 100, the user has crossed to paid tier).
The progress table is particularly nasty to work with, but it seems to be working at this point.
> feat(billing): Upload Posthog billing data

- app/web/src/components/FuncEditor/FuncEditor.vue
- app/web/src/store/func/funcs.store.ts
Testing steps:
1. unlock a function
2. open two tabs
3. make changes in one tab
4. see the other tab reload the editor
5. your tab did not reload the editor and you can keep typing
This will work against `sifs` too, your code will always reload.
PSA: I went down a _loooooong_ rabbit hole before landing on this specific fix. I was trying to have my cake and eat it too—always update the store, but not remount the component. And, this part scares me, _I couldn't do it to save my life_.
I literally took out every piece of the puzzle I could so that none of the props to `<CodeEditor>` changed, which means it shouldn't have re-mounted. But it kept remounting. (My thought process was to not remount it, and instead edit the `yDoc` to have the new code as its contents, but I couldn't pull that …
> Fix: code editor reloads text when saved unless you were the client that saved it

- lib/dal/src/change_set.rs
- lib/dal/src/workspace_snapshot.rs
- lib/naxum/src/serve.rs
- lib/rebaser-server/src/rebase.rs
I also moved some of the timings to fields in the main rebaser loop, as we want to measure this over time but no need to send a full event for each one.
<div><img src="https://media4.giphy.com/media/fQoIDlLW6A6BAhyev8/giphy.gif?cid=5a38a5a24boi5wk428owtrkfsx8weecdkorm3i4gggcgl2se&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/cbc/">CBC</a> on <a href="https://giphy.com/gifs/cbc-schittscreek-schitts-creek-fQoIDlLW6A6BAhyev8">GIPHY</a></div>
> fix(dal,naxum,rebaser): Cleaning up some traces that are not adding value

- lib/edda-server/src/change_set_processor_task.rs
- lib/naxum/src/middleware/post_process/on_failure.rs
This change alters the middleware stack for the change set processor task in Edda. Prior to this change, when a message is processed that results in an error, it is left in place in the stream and *not* deleted, but rather skipped over. If at a later point in time a new task is spun up to process more messages for that change set, the change set processor task will re-visit this failed request message and potentially result in the exact same behavior (i.e. result in a failure and not delete that message).
This change will log an `error` making it clear that the request failed in some way and will delete the message so that future change set NATS consumers will not re-process this message. A future change may consider re-publishing this message to a "failed requests" stream for later …
> fix(edda): delete (and log) the request when it fails

- app/web/src/components/Connection.vue
- app/web/src/components/DetailsPanelTimestamps.vue
- app/web/src/components/EdgeDetailsPanel.vue
- app/web/src/components/ModelingDiagram/DiagramEdge.vue
- app/web/src/components/ModelingDiagram/DiagramHelpModal.vue
- app/web/src/components/ModelingDiagram/ModelingDiagram.vue
- app/web/src/components/ModelingDiagram/diagram_types.ts
- app/web/src/components/ModelingView/ConnectionMenuSocketList.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- app/web/src/components/SocketCard.vue
Components can now have their data sockets connected via the diagram. Dragging an edge between components will open up the connections panel to create a connection. A new connection can also be added to two components which are already connected by selecting the edge between them and clicking the button on the `EdgeDetailsPanel`.
Currently the empty states for the connections panel could be improved and the user cannot add multiple connections at once.
> feat(web) - simple socket UI connecting edges on the diagram

- component/deploy/docker-compose.yaml
Vector's latest release is having issues. We're pinning to a more specific version until the issue is resolved.
https://github.com/vectordotdev/vector/issues/22840#issuecomment-2789929247
> chore: pin vector to 0.45

- bin/auth-api/package.json
- pnpm-lock.yaml
Fixes: https://github.com/systeminit/si/security/dependabot/398
I verified that the auth portal works as normal for Workspace interactions and login / logout with this PR
> chore(deps): Upgrade koa to 2.16.1

- component/lambda/functions/si_posthog_api.py
- component/lambda/functions/upload-posthog-billing-data.py
- component/lambda/sql/workspace_operations.sql
Typo that was never deployed. I fixed it when I "deployed," this is just a record of what is actually in Redshift.
(This is what happens when your deployment method is "wait until it's merged, then paste the SQL into Redshift." This is also why our database is almost entirely *views*: repairing them is literally just redefining the view to the old version.)
Also removed some unused imports and an unused method from the Python.
> fix(billing): Remove extraneous semicolons from view definitions

- lib/edda-server/src/config.rs
This change updates the TOML value for Edda's concurrency limit from `concurrency_limit` to `edda_concurrency_limit`. See our issues with configuring services with a single `service.toml` template...
> fix(edda): use a unique edda_concurrency_limit config value

- lib/sdf-server/src/service/v2/admin/update_module_cache.rs
Wehave a check that the user POSTing to this API is locked down to system initiative users but welocked it down too far to be a web token only - we now can make this either web or automation which means I can hit this endpoint after an asset update of the AWS generated assets to clear the cache
Testing:
Works from API using an automation token:
```
▶ curl -vX POST "http://localhost:8080/api/v2/admin/update_module_cache" -H "Authorization: Bearer ${SI_BEARER_TOKEN}"
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 62152 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> POST /api/v2/admin/update_module_cache HTTP/1.1
> Host: localhost:8080
> User-Agent: …
```
> fix(sdf): Allow hitting the update_module_cache endpoint with an automation token

- component/ci-base/Dockerfile
```
docker run -it  --entrypoint sh systeminit/ci-base:20250411.204011.0-sha.720d2a8d1-amd64
$ buildevents
The buildevents executable creates Honeycomb events and tracing information
about your Continuous Integration builds.
Usage:
buildevents [command]
Available Commands:
build       Sends the root span for the entire build
cmd         Invoke an individual command that is part of the build.
completion  Generate the autocompletion script for the specified shell
help        Help about any command
step        Joins a collection of individual commands
watch       Polls the CircleCI API and waits until all jobs have finished.
Flags:
-a, --apihost string        [env.BUILDEVENT_APIHOST] the hostname for the Honeycomb API server to which to send this event (default "https://api.honeycomb.io") …
```
> feat: add buildevents to ci-base

- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
- lib/sdf-server/src/service/v2/index/get_front_end_object.rs
- lib/sdf-server/src/service/v2/index/get_workspace_index.rs
- lib/sdf-server/src/service/v2/index/rebuild_change_set_index.rs
This PR adds the rebuild change set index route. There is no corresponding button or action that can trigger it in the frontend yet, but it is available.
This PR also standardizes the two rebuild functions' trace naming schemes and moves them to the root index module. In addition to these changes, all routes are now in their own submodules.
> Add rebuild change set index route

- component/init/configs/vector.yaml
regex schmegex
The Tools Production and Production environments in honeycomb have been updated to show the logs we have been sending. This PR better matches the log level to what Honeycomb expects.
> fix: vector log level matching

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
The `MaterializedView` trait already provided a method to get the `ReferenceKind` for the MV in question. Rather than manually specifying what the `ReferenceKind` is for the MV you want to add the dependencies for, the helper macro now uses the `MaterializedView` trait method generated from the derive macro.
> Use trait kind method when building MV dependency graph

- .github/workflows/upgrade-web.yml
This ensures we read from the correct `.env` file as part of the build
> feat: set the deploy mode when building web

- app/web/src/components/LeftPanelDrawer.vue
- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/store/feature_flags.store.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- lib/vue-lib/src/design-system/icons/custom-icons/mjolnir.svg
- lib/vue-lib/src/design-system/icons/custom-icons/odin.svg
- lib/vue-lib/src/design-system/icons/custom-icons/snowflake.svg
- lib/vue-lib/src/design-system/icons/icon_set.ts
Scott made sure the the `.env.production` and `.env.staging` are loaded _during_ vite build, which means we can lean on them to know if the file is being built for prod, or its local dev. This allows us to namespace the sqlite DBs, so that, if we were to alter the tables during local dev, it wouldn't break prod execution in our browsers.
Also, opening up some tooling to interacting with SQLite which can make testing & discovery easier. [These are behind a flag for only the SI cohort](https://us.posthog.com/project/20369/feature_flags/126595).
> Namespace sqlite db, and create dev-only tooling to trigger things

- component/ci-light/Dockerfile
way easier to just add bash rather than try to flip between sh and bash when injecting buldevents
> chore: bash

- app/web/src/store/change_sets.store.ts
- lib/sdf-server/src/service/v2/change_set.rs
This PR returns a user-friendly error when applying a change set with a de-synced local state (spicedb, users table in PG, graph requirements, etc.).
Why not solve the de-sync issue? This is not easily reproducible (words, oh do not bite me) and would require a non-trivial amount of investigation into syncing auth with local state.
Why use a toast? The current UX involves the change set button to remain "clickable" and we use the "success" state to imply that. On the "InsetApprovalModal", the space can get crowded with several reviewers without a further look at its overall shape. Finally, for the standard apply modal (used mostly when in a single user workspace), the current UX involves the modal immediately closing due to the length of an apply call to produce a response.
Is there a way …
> Return better error for de-synced change set apply

- app/web/src/api/sdf/dal/action.ts
- app/web/src/components/ChangesPanelHistory.vue
- app/web/src/components/ComponentDetailsManagement.vue
- app/web/src/components/Management/ManagementHistoryCard.vue
- app/web/src/components/Management/ManagementHistoryList.vue
- app/web/src/components/ManagementRunPrototype.vue
- app/web/src/components/StatusIndicatorIcon.vue
- app/web/src/store/func_runs.store.ts
- app/web/src/store/management_runs.store.ts
- lib/sdf-server/src/service/v2/management/history.rs
When management functions have errors, we report their status differently depending on whether it's in History or is the latest management function run. This PR makes them uniform and shows the correct success / error icon depending on what is reported.
* Makes manage/history and manage/latest APIs return the same shape, including both execution state and actionResultState.
* Calculates the status icon using a common funcRunStatus() function, treating these cases as errors:
* Function throws exception
* Function returns `{ status: "error", message: "message" }`
* Function returns `{ schtatus: "ok" }`
* Uses appropriate icons (similar to other status indicators). In particular, "running" states now show a spinner, just like other running status indicators.
Fixes BUG-792.
**Factor Budget:** …
> fix(sdf): Report errors from management functions correctly

- BUCK
- support/buck2/BUCK
- support/buck2/buck2-all-rust-targets.sh
This PR adds the "all-rust-targets" BUCK target to perform "buck2" commands on all targets in the repository from any directory. It also adds an alias in the root BUCK file for the new script as well as adds an alias for the "sync-cargo-deps" target.
```bash
buck2 run :sync-cargo-deps
buck2 run :all-rust-targets
buck2 run :all-rust-targets build
buck2 run :all-rust-targets build @//mode/debug
```
> Add "all-rust-targets" BUCK target and two aliases

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Raw strings for RDS DBCluster goes bye bye. This is what we do for SecretsManager::Secrets
> fix(clover): Allow Clover to read RDS DBCluster passwords from SI Secrets

- app/web/src/components/ComponentDetails.vue
- app/web/src/mead-hall/ActionWidget.vue
- app/web/src/mead-hall/AssetActionsDetails.vue
- lib/dal/src/action/prototype.rs
- lib/dal/tests/integration_test/materialized_view.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-types-rs/src/action.rs
- lib/si-frontend-types-rs/src/action/prototype.rs
- lib/si-frontend-types-rs/src/reference.rs
This PR ensures that we only build MVs where the MV ID is the same as the trigger's change ID or is the change set ID. This ensures that we do not run into situations where deleted nodes cannot be found when "hopping" to the desired MV ID from a change ID.
As a result of these changes, this is the first commit where we have removed an existing MV. It is no longer in use. We are not concerned about backwards compatibility here since it is not deserialized anywhere.
This PR also fixes the issue where the icons for action prototypes were all question marks.
> Only build MVs where the MV ID is immediate

- bin/lang-js/src/function_kinds/action_run.ts
This PR fixes dynamic imports for action funcs by ensuring that the code is declared outside of the func that calls and awaits it.
> Fix dynamic imports for action funcs

- component/init/configs/vector.yaml
Ship the logs from the docker containers so we can try to identify init errors in grafana
> feat: ship docker logs to cloudwatch

- app/web/src/components/ChangesPanelHistory.vue
This fixes a regression where users could no longer view the logs/arguments/etc. for actions. This is because we were fetching the func runs details using the `actionId` and not the `funcRunId`.
Tested manually by running actions and seeing their details both when the action is still enqueued, and when it's no longer enqueued. 
<div><img src="https://media4.giphy.com/media/VL5JGMwlSOFsIuc8z0/giphy.gif?cid=5a38a5a2j5umfmj9b5tfn07nzelznxznomwhbvut4b846dhu&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/gerbert/">Gerbert!</a> on <a href="https://giphy.com/gifs/gerbert-puppet-VL5JGMwlSOFsIuc8z0">GIPHY</a></div>
> fix(web): Restore showing action details when selecting an Action

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
This keeps on par with AWS::RDS::DBCluster
> fix(clover): Ensure that MasterPassword is set as a secret in AWS::RDS::DBInstance rather than a string

- dev/Tiltfile
- lib/dal/src/component.rs
- lib/luminork-server/src/api_types.rs
- lib/luminork-server/src/api_types/component.rs
- lib/luminork-server/src/api_types/component/v1.rs
- lib/luminork-server/src/lib.rs
- lib/luminork-server/src/routes.rs
- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/components/connections.rs
- lib/luminork-server/src/service/v1/components/create_component.rs
- lib/luminork-server/src/service/v1/components/find_component.rs
- lib/luminork-server/src/service/v1/components/list_components.rs
- lib/luminork-server/src/service/v1/components/mod.rs
- lib/luminork-server/src/service/v1/components/update_component.rs
This adds some initial functionality for listing component Ids, getting a component by Id, and finding a component by name. 
I also added Workpace Id and ChangeSet Id to the params for the swagger UI, mimicing what we had for the jwt, because I was sick of having to copy them in each time across each route.  Claude helped here, we needed to inject these as global parameters so that we have access to them, doing this in the interceptor didn't work as the OpenAI spec validates the request before it gets there and the validation was failing when workspace Id and change set Id were empty. 
I'm also experimenting with versioned API types in luminork itself, we can rip this into a separate crate once we get further and see the shapes of these things - we'll have to see how this feels.
Expect …
> feat(luminork): Ability to get a component by Id, find by name, and list all Component Ids for a workspace

- Cargo.lock
- bin/luminork/BUCK
- bin/luminork/Cargo.toml
- bin/luminork/src/args.rs
- bin/luminork/src/main.rs
- dev/Tiltfile
- lib/config-file/BUCK
- lib/config-file/Cargo.toml
- lib/config-file/src/layered_load.rs
- lib/config-file/src/lib.rs
- lib/config-file/src/parameter_provider.rs
- lib/dal/examples/rebase/main.rs
- lib/innit-client/BUCK
- lib/innit-client/Cargo.toml
- lib/innit-client/src/config.rs
- lib/innit-client/src/lib.rs
- lib/innit-core/BUCK
- lib/innit-core/Cargo.toml
- lib/innit-core/src/lib.rs
- lib/innit-server/src/routes/get_parameter.rs
- lib/innit-server/src/routes/list_parameters.rs
- lib/luminork-server/src/lib.rs
- lib/si-settings/BUCK
- lib/si-settings/Cargo.toml
- lib/si-settings/src/lib.rs
* add generic provider for getting parameters into layered_load
* thread that sucker through to si_settings and up to the bins
* do so using divergent (copy paste) implementations to avoid blast radius
* get from global path `/si/${env}/global` and `/si/${env}/${service}` to layer global and service-specific configs
* tell luminork to use the layered_load that gets from parameter store, passing in innit-client
```bash
❯ curl http://localhost:5166/parameters/si/tools/ | jq
{
"parameters": [
{
"name": "/si/tools/global/pg/user",
"value": "si"
},
{
"name": "/si/tools/global/pg/hostname",
"value": "abc"
},
{
"name": "/si/tools/global/pg/dbname",
"value": "butt"
},
{
"name": "/si/tools/sdf/pg/hostname",
"value": "derpdoop"
},
{
"name": "/si/tools/luminork/pg/hostname",
"value": "def"
}
]
}
``` …
> feat: use innit-client in layered load

- Cargo.lock
- lib/innit-client/src/lib.rs
- lib/innit-client/tests/integration_test/mod.rs
- lib/innit-core/src/lib.rs
- lib/innit-server/BUCK
- lib/innit-server/Cargo.toml
- lib/innit-server/src/app_state.rs
- lib/innit-server/src/config.rs
- lib/innit-server/src/lib.rs
- lib/innit-server/src/parameter_cache.rs
- lib/innit-server/src/routes.rs
- lib/innit-server/src/routes/clear_cache.rs
- lib/innit-server/src/routes/create_parameter.rs
- lib/innit-server/src/routes/get_parameter.rs
- lib/innit-server/src/routes/list_parameters.rs
- lib/innit-server/src/server.rs
- lib/si-data-ssm/src/lib.rs
- lib/si-data-ssm/tests/integration_test/mod.rs
Adds an in-memory cache for parameter values to manage backend pressure. There are separate caches for individual params and lists just for simplicity. By default, cache items expire after 24 hours. 
Also adds a create endpoint to facilitate testing.
> feat(innit): in-memory cache

- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
This PR ensures invalid reference kinds trigger rebuilds. Removed or deprecated reference kinds are a-okay, but we need to make sure sdf rebuilds the index accordingly.
> Ensure invalid reference kinds trigger rebuilds

- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Props:
Connected:
Output Socket:
> fix: add transitgatewayattachmentid prop and output socket to vpnconnection asset

- app/web/src/newhotness/Workspace.vue
- app/web/src/store/realtime/heimdall.ts
1. Heimdall looks for the injection of change set and workspace.
2. Heimdall inits before mount (before children) not onmount
> Fix: initialization of the bifrost on the new hotness

- bin/innit/Dockerfile
- bin/innit/src/args.rs
- lib/innit-client/tests/integration_test/mod.rs
- lib/innit-server/src/config.rs
- lib/innit-server/src/server.rs
- lib/si-tls/src/lib.rs
Allow validation against multiple CAs so we can host a single instance of innit and have both tools and prod validate against it
> feat(innit): allow setting multiple CAs for validation

- bin/clover/src/specPipeline.ts
Specifically allow things that don't have a type, but do have a oneOf or anyOf.
This fixes an issue with (at least) AWS::DynamoDB::Table
> bug: include objects that don't have a type in clover

- lib/luminork-server/src/service/v1/components/update_component.rs
We will be able to pass a list of props to unset as follows:
```
{
"unset": [
"region",
"path/to/another/prop"
]
}
```
> feat(luminork): Add support for updating a component to unset a property

- app/web/src/components/AssetFuncAttachDropdown.vue
When first playing around with the asset panel, it took me longer than I'd like to admit to find now to add a new function. 
The chain icon feels unintuitive to click on to create a new function. So I've changed the icon to the +, then new continues to have the + and the chain icon is used to add an existing.
Before:
After:
> Switched icons around to make it clearer you can create a new function

- component/init/configs/vector.yaml
Log shipping is broken until this is merged.
> fix: duplicate key in cloudwatch config

- lib/dal/src/action.rs
- lib/dal/src/change_set.rs
- lib/dal/src/component/delete.rs
- lib/dal/src/management/prototype.rs
- lib/luminork-server/src/service/v1/components/connections.rs
- lib/luminork-server/src/service/v1/components/delete_component.rs
With this PR - all Luminork endpoints should have the same coverage in WSEvents as SDF. I added some comments to where the WSEvent is fired from lower in the dal to be clear, but I can't wait to rip all of this out 
<div><img src="https://media1.giphy.com/media/xT8qB7GQDfnldWTFhS/giphy.gif?cid=5a38a5a29u25egrksw062dq102pq5ctj3n0uvkzp8papb656&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/bobs-burgers/">Bob&#x27;s Burgers</a> on <a href="https://giphy.com/gifs/bobs-burgers-fox-bobs-burgers-tv-xT8qB7GQDfnldWTFhS">GIPHY</a></div>
> fix(luminork): Adding WSEvents for reactivity from luminork.

- lib/config-file/src/parameter_provider.rs
- lib/innit-client/src/config.rs
- lib/innit-core/src/lib.rs
- lib/innit-server/src/routes/create_parameter.rs
- lib/innit-server/src/routes/get_parameter.rs
- lib/si-data-ssm/src/lib.rs
We need to handle `StringList` types correctly so ensure we can parse lists into `Vec<String>`.
Also ensures we get all parameters from parameter store as it only returns 10 by default.
> fix(innit): handle list types correctly

- bin/clover/doc-link-cache.json
- bin/clover/src/cloud-control-funcs/overrides/VPNConnection VpnTunnelOptionsSpecifications/qualifications/presharedKeyValidations.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
1. Cannot start with 0
2. Alphanumeric, periods, underscores only
3. Between 8 and 64 chars
> fix: add presharedkey prop validation for vpntunneloptionsspecs

- component/deploy/docker-compose.yaml
These were used to toggle pgbouncer, but are no longer needed.
> chore: remove unused init profiles

- lib/innit-client/tests/integration_test/mod.rs
- lib/innit-server/src/routes.rs
- lib/innit-server/src/server.rs
Ensure we can ping the health endpoint without needing a client cert
> fix(innit): serve health without requiring auth

- app/web/src/store/component_attributes.store.ts
- lib/dal/src/attribute.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/subscription.rs
- lib/dal/src/prop.rs
- lib/dal/src/workspace_snapshot/edge_weight.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/dal/tests/integration_test/deserialize/mod.rs
- lib/sdf-server/src/service/v2/component.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
This modifies the `PUT /attributes` API to support creation of arrays/maps that do not exist, removal of array and map items when desired, and validation of subscription paths.
1. Creates map/array elements that do not exist when setting a value at a path.
- `{ "/domain/Tags/Environment": "prod" }` will create the map element Environment if it does not exist.
- `{ "/domain/IpAddresses/0": "10.0.0.1", "/domain/IpAddresses/1": "10.0.0.2" }` will create elements 0 and 1 if they do not exist.
2. Append: supports JSON pointer array index `-`, which means "append"
-  `{ "/domain/IpAddresses/-": "127.0.0.1" }` will append that value to the end of the array
3. Recursive: a map in a map in an array will auto-vivify all the things
- `{ "/domain/TLDs/blah.com/Subdomains/foo/TTL": 100 }` will create …
> feat(sdf): API to create map/array elements that do not exist

- lib/config-file/src/layered_load.rs
order these first so they can be overridden by command line flags (like the SDF migrate pipeline)
> fix: config ordering to ensure we can override settings at the cli

- Cargo.lock
- Cargo.toml
- lib/dal/src/pkg/import.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
- third-party/rust/fixups/color-spantrace/fixups.toml
- third-party/rust/fixups/object/fixups.toml
- third-party/rust/fixups/owo-colors/fixups.toml
This PR upgrades color-eyre from 0.6.3 to 0.6.4 and generally updates all other dependencies (no other changes to the root "Cargo.toml") before running "sync-cargo-deps".
> Update color-eyre patch version and rust deps

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
Also, something we forgot—on the attribute input, when the input is focused, use the same background as the menu below to indicate that the menu controls are related to the input
> Ability to use the keyboard to select components on the Explore page

- app/web/src/newhotness/Component.vue
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component_connections.rs
- lib/dal-materialized-views/src/component_connections_list.rs
- lib/dal-materialized-views/src/lib.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-types-macros/src/lib.rs
- lib/si-frontend-types-rs/src/action.rs
- lib/si-frontend-types-rs/src/action/prototype.rs
- lib/si-frontend-types-rs/src/change_set.rs
- lib/si-frontend-types-rs/src/checksum.rs
- lib/si-frontend-types-rs/src/index.rs
- lib/si-frontend-types-rs/src/lib.rs
- lib/si-frontend-types-rs/src/newhotness.rs
- lib/si-frontend-types-rs/src/newhotness/component.rs
- lib/si-frontend-types-rs/src/newhotness/component_connections.rs
- lib/si-frontend-types-rs/src/reference.rs
- lib/si-frontend-types-rs/src/schema_variant.rs
- lib/si-frontend-types-rs/src/view.rs
This change adds MVs for incoming socket-to-socket connections. The MVs have a "Beta" suffix for easy invalidations once we test all four kinds of connections needed in the new UI.
As a consequence of these changes, the macro(s) used for MVs have been adjusted to handle enums with struct variants.
For the record, @fnichol architected the vast majority of this. I just wired it up to the frontend and drove it home. Go Fletcher!
> Add MVs for incoming socket-to-socket connections

- app/web/src/store/feature_flags.store.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/si-frontend-types-rs/src/newhotness/component.rs
I'm not making a separate Mv to keep a lid on total number of mvs, given everything that is going on. Maybe in the future we have a better place for this to live. But for now, it functions and stays up to date.
Also—please give me the more correct rust way to do the if-let-some nonsense I did hear 😇 ... it works, but obviously its not pretty.
> Add "diff" content to the component mv. Also, fix the feature flag sponge we keep messing up

- lib/innit-client/src/config.rs
- lib/innit-client/src/lib.rs
We accidentally generated ~40k certs in tools prod. This introduces a basic form of caching the generated cert to ensure we don't do this anymore. I want to take another pass at this to do it more correctly once we are protected from this issue.
> fix: cache generated certs to ensure we aren't spamming issue requests.

- bin/auth-api/package.json
- pnpm-lock.yaml
Last one that's active, hurrah!
<div><img src="https://media3.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif?cid=5a38a5a2m1cjpce4p3lbws1qdwp425az7g3dlskuq834qitb&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/></div>
**Authors note:** Just test helpers changed here so if CI is green we are good to go
> chore: bump supertest for CVE-2025-46653

- app/web/src/components/AttributesPanel/TreeFormItem.vue
- app/web/src/components/ModelingView/FloatingConnectionMenu.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- Add links on the attribute editor to allow opening the connections menu
- Allow selecting direction on the connections menu when dealing with sockets
> feat(web): Pop up connections menu from attribute tree

- lib/dal-macros/tests/trybuild.rs
- lib/innit-client/src/config.rs
- lib/innit-client/src/lib.rs
- lib/si-tls/src/lib.rs
Since we are caching the cert and they are short-lived we will eventually find out they are expired. This ensures we regenerate expired certs.
> feat: ensure we rotate expired certs

- bin/innitctl/Dockerfile
- component/deploy/docker-compose.yaml
Innitctl needs to be able to interact with the host disk to find cached certs
> chore: ensure innitctl can reach cert cache

- lib/dal-test/src/lib.rs
- lib/dal-test/src/signup.rs
- lib/dal-test/src/test_exclusive_schemas/mod.rs
- lib/dal/examples/rebase/main.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
- lib/si-split-graph/src/lib.rs
- lib/si-split-graph/src/subgraph.rs
- lib/si-split-graph/src/tests/mod.rs
- lib/si-split-graph/src/updates.rs
Cycle detection was failing because the cleanup of the graph did not
fully remove nodes when they were the children of an external source
which was removed.
Removal of "orphaned" nodes (nodes with no incoming edges) must proceed
in tandem with the removal of external source edges whose "tail" is the
orphaned node. That will orphan new nodes, so the process has to be
repeated until there are no more orphaned nodes left. Previously the
split graph cleanup would only remove the first layer if there were
children of the orphaned node pointed to by an external source edge.
The result would be weird walks of the graph during the cross-graph dfs
searching for cycles, reporting cycles on acyclic graphs.
> fix(si-split-graph): cycle detection

- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-types-rs/src/checksum.rs
- lib/si-frontend-types-rs/src/newhotness/component.rs
- lib/si-frontend-types-rs/src/newhotness/component/attribute_tree.rs
- lib/si-frontend-types-rs/src/reference.rs
The prior version of this created a MV per `AttributeValue` across the entire change set. This could be... a very large number of MV instances.
Rather than creating hundreds of thousands of MVs for moderately sized workspaces & change sets, we now collate the `AttributeValue` information into a single MV per Component. While this does mean that we will rebuild the MV to see if it has changed when there have been unrelated changes to the Component, it also means that we will always do this once per Component at most, and are able to cache more information used in the MV across all `AttributeValue`s in the Component.
Co-authored-by: Nick Gerace <nick@systeminit.com>
> Restructure AttributeTree MV to be keyed on ComponentId

- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
- lib/dal/src/workspace_snapshot/split_snapshot/corrections.rs
- lib/rebaser-server/src/rebase.rs
- lib/si-split-graph/src/lib.rs
- lib/si-split-graph/src/petgraph_traits.rs
Ports the ordering node corrections to the split graph. All correction tests for ordering nodes pass under the split graph now.
> feat(split-snapshot): ordering corrections

- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/dependent_value_graph.rs
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/attribute_value.rs
- lib/dal/tests/integration_test/component/debug.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
This adds a dal API to get the JSON pointer to the given AttributeValue, relative to its root (e.g. `/domain/IpAddresses/0`). There are several upcoming APIs that need this, and since it's shared infrastructure I split it into its own thing so people could use it sooner.
<IMG SRC="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExb2JyNDM4eWtuN3Fmc2ZlbzhkeDl4OGxzZjJ2ODY5MmFvc3R0czkweCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RR8nZxUvng5a12X322/giphy.gif">
* Renamed AttributeValue::parent_attribute_value_id() to AttributeValue::parent_id()
* Removed get_key_of_child_entry() in favor of parent_and_map_key()
* Renamed get_index_or_key_of_child_entry() to get_key_or_index_of_child_entry() to match the type name (KeyOrIndex)
get_path_by_id() can likely be replaced with path_from_root() at this …
> dal: API to get attribute path to an AV

- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal/tests/integration_test/materialized_views.rs
This matches the path expected by the socketless connections API,
which is the reason the path is included in this MV.
> Use JSON Pointer as the AttributeValue path in AttributeTree MV

- app/web/src/api/sdf/dal/component.ts
- app/web/src/store/components.store.ts
- app/web/src/store/views.store.ts
- lib/dal-test/src/expected.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/attribute/value/dependent_value_graph.rs
- lib/dal/src/component.rs
- lib/dal/src/diagram.rs
- lib/dal/src/func/authoring.rs
- lib/dal/src/func/binding.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/schema/variant.rs
- lib/dal/src/secret.rs
- lib/dal/tests/integration_test/func/argument.rs
- lib/dal/tests/integration_test/pkg/mod.rs
- lib/luminork-server/src/api_types/component/v1.rs
- lib/sdf-server/src/service/v2/fs/bindings.rs
- lib/sdf-server/src/service/v2/func/binding/attribute/reset_attribute_binding.rs
- lib/sdf-server/src/service/v2/func/binding/create_binding.rs
- lib/sdf-server/src/service/v2/func/binding/delete_binding.rs
- lib/sdf-server/src/service/v2/func/create_func.rs
- lib/sdf-server/src/service/v2/func/list_funcs.rs
- lib/sdf-server/src/service/v2/management/generate_template.rs
- lib/sdf-server/src/service/v2/variant/get_variant.rs
- lib/sdf-v1-routes-variant/src/regenerate_variant.rs
This adds subscription edges to the get_diagram API. Critically, it just adds a new property to the two diagram endpoints; it does not change the existing 
I removed the `self` variant of two methods (SchemaVariant.schema_id() and AttributePrototypeArgument.prototype_id()) since they just call the ID version (do not need content of the AV or APA, just ID). This is part of a continuing effort to have fewer variants of the same method and stop assembling DAL content objects when we're just walking the graph.
This does not:
* Show the new edges in the UI. It only reports the edges via the API.
* Report attribute subscription edges to/from deleted components. That code is stubbed.
> feat(sdf): Add subscription edges to get_diagram API

- lib/dal/src/component.rs
- lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
Ensures we remove the root attribute value from a component when deleting. Additionally adds a correction which deletes all edges incoming to the root attribute value if the component will be deleted, ensuring deletion holds across change sets, even if a new value subscription has been added in the change set.
> fix(dal): correctly delete components with incoming ValueSubscription edges

- lib/dal-materialized-views/src/incoming_connections.rs
- lib/si-frontend-mv-types-rs/src/incoming_connections.rs
- lib/si-frontend-mv-types-rs/src/reference/weak.rs
Before this change, the only weak reference for incoming connections was on the "from" side of a "socket-to-socket" connection. Now, the components for both sides of both connection kinds are weak references.
This change also fixes the "from" side of the "socket-to-socket" connection to ensure that the component is correct.
All weak references are now created using a "From" impl too for ease of use.
> Add all weak references for incoming connections

- app/web/src/router.ts
Right now, if this code runs too early, it clears the matched route before we can load the child route in WorkspaceSinglePage.vue, so WorkspaceModelAndView isn't matched and doesn't load.
This fixes the blank page problem.
> fix(dal): Don't mutate the route when changing routes

- lib/dal-test/src/helpers/component.rs
- lib/dal/src/action.rs
- lib/dal/src/action/dependency_graph.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/action.rs
This causes actions to run in the proper order when components depend on each other via subscription.
Fixes ENG-3019.
<IMG SRC="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExenEydHI0aWhlM2xkYW94OHk2N2FnYjlwbXp1cjAxNDJnYmpqcnpzaSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/XxR9qcIwcf5Jq404Sx/giphy.gif" />
> feat(dal): Respect subscriptions when calculating action dependencies

- lib/si-frontend-mv-types-rs/src/schema_variant.rs
This makes it possible to drag components onto the canvas again in environments using bifrost for the old UI (localdev).
> fix(bifrost): Make components draggable to canvas again

- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal-materialized-views/src/lib.rs
- lib/dal-test/src/expected.rs
- lib/dal-test/src/helpers.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/component/frame.rs
- lib/dal/src/component/socket.rs
- lib/dal/src/func/binding/attribute.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/socket/input.rs
- lib/dal/src/socket/output.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/dal/tests/integration_test/materialized_views.rs
This change fixes two bugs with incoming connections:
1) Fix duplicate incoming connections by ensuring we do not accidentally process outgoing connections during MV generation.
2) Fix incorrect prop IDs for prop-to-prop connections on the "from" side by using the correct ID.
This change was tested with an included integration test and includes the following misc changes:
- Rename the attribute value ID for socket functions to be shorthand
- Move the "make_subscription" helper to the helpers module
> Fix duplicate incoming connections and wrong prop

- app/web/src/mead-hall/ActionWidget.vue
- app/web/src/mead-hall/AssetActionsDetails.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/CodePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/DiffPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/ResourcePanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- app/web/src/newhotness/logic_composables/navigation_stack.ts
- app/web/src/newhotness/util.ts
- app/web/src/router.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
We now have a codified pattern: `get` -> `getReferences` -> `getComputed`. This is how we string together strong and weak references. However, it comes with a limitation; circular references/infinite loops/cycles, call it what you will, but its bad 😈 .
This implication of this is that, we can do all the things we want—except compute the outgoing connections when looking up input connections. Thats the cycle. (There is probably a clever way around this... but my brain has been bashing on this its starting to turn into mush... so, we can figure that out another day).
What does this mean for you?! When you are looking up connections and want outgoing connections—you need to make a separate call. Thats it, for now. You'll see this example in the `ConnectionsPanel`. When you're asking for a …
> Connections panel, outgoing connections, weak_references & naming scheme

- app/web/src/api/sdf/dal/schema.ts
- app/web/src/mead-hall/ActionWidget.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/DiffPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/lib.rs
- lib/dal-materialized-views/src/mgmt_prototype_view_list.rs
- lib/dal-materialized-views/src/schema_variant.rs
- lib/dal/src/socket/connection_annotation.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/checksum.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/lib.rs
- lib/si-frontend-mv-types-rs/src/management.rs
- lib/si-frontend-mv-types-rs/src/reference.rs
- lib/si-frontend-mv-types-rs/src/schema_variant.rs
- lib/si-frontend-mv-types-rs/src/temporary_conversion_impls.rs
The `Component` has a `SchemaVariant` reference now! That reference already has the props and sockets. And we added the socket annotations & arity to the sockets. That clears @nickgerace from any work on annotations! :D 
@nickgerace and I talked about some clean up in the `into()` bits, and getting the big `SchemaVariantCategories` MV to have references to installed MVs (obviously not modules that haven't been installed)
> Adding the SchemaVariant as a Reference on Component

- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
- bin/auth-api/src/routes/auth_token.routes.ts
A workspace token is more like a PAT so we are going to allow all users of a workspace to be able to create a token. This means that individual users of a workspace can create a workspace token and use it with the public API for that workspace
> feat(auth-stack): Ensure all members of a workspace can create a token

- app/web/src/store/components.store.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal-test/src/helpers.rs
- lib/dal-test/src/helpers/attribute.rs
- lib/dal-test/src/helpers/attribute/value.rs
- lib/dal-test/src/helpers/change_set.rs
- lib/dal-test/src/helpers/component.rs
- lib/dal-test/src/helpers/schema.rs
- lib/dal-test/src/helpers/schema/variant.rs
- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/subscription.rs
- lib/dal/src/component.rs
- lib/dal/src/property_editor/values.rs
- lib/dal/tests/integration_test/action.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
This PR allows you to subscribe to multiple values from a single array, and will put them together into a single array. It has two specific changes:
1. Allows multiple subscriptions to array values
- Changes `AttributeValue::subscribe()` to `AttributeValue::set_to_subscriptions()`, setting multiple subscriptions at once
- Adds `keepExistingSubscriptions` option to `PUT /component/:componentId/attributes` to make it easier for the "add subscription" button to be built for arrays
2. Uses `si:normalizeToArray` instead of `si:identity` when the subscriber is an array, to uplevel single values
It will return an error if you attempt to assign multiple subscriptions to a non-array value.
* Made the tests super ergonomic with some attribute::value::set/subscribe/get helpers, letting you pass …
> feat(dal): Allow arrays to subscribe to multiple values

- flake.lock
- flake.nix
Specifically to get the latest buck2. Needed to pull in a later nodejs as 18 is deprecated. I will confirm this locally to ensure we have no breakages.
> chore: flake update

- lib/dal-materialized-views/src/component/attribute_tree.rs
This change protects against null secret values in the attribute tree MV.
> Protect against null secret value in tree MV

- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/attribute/prototype/argument/value_source.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/func/binding/attribute.rs
- lib/dal/src/pkg/import.rs
- lib/dal/src/prop.rs
- lib/dal/src/schema/variant.rs
- lib/dal/src/schema/variant/leaves.rs
- lib/dal/src/secret.rs
- lib/sdf-server/src/service/v2/fs/bindings.rs
Breaking out this factoring from a feature PR I'm working on, so it and the original can be reviewed easily and quickly. This PR simplifies the creation of AttributePrototypeArguments in two ways:
1. Adds the ValueSource directly as an argument to new(), since in 10 out of 11 places, we set the ValueSource immediately after .
- The existing source-less function is now new_without_source(), and is called in two places in si-fs.
2. Makes set_value_source() take impl Into<ValueSource>, and removing the named variants like set_value_source_from_input_socket() (so you can just call `set_value_source(<input socket id>)`)
- Also uses derive_more::From to derive the ValueSource::from() impls, since the variants are (currently) fully discriminated by type
> chore(dal): simplify APA creation

- Cargo.lock
- Cargo.toml
- dev/Tiltfile
- lib/data-warehouse-stream-client/src/lib.rs
- lib/forklift-server/src/server/app/billing_events.rs
- lib/innit-client/src/lib.rs
- lib/innit-server/src/server.rs
- lib/si-aws-config/BUCK
- lib/si-aws-config/Cargo.toml
- lib/si-aws-config/src/lib.rs
- lib/si-data-acmpca/BUCK
- lib/si-data-acmpca/Cargo.toml
- lib/si-data-acmpca/src/lib.rs
- lib/si-data-ssm/BUCK
- lib/si-data-ssm/Cargo.toml
- lib/si-data-ssm/src/lib.rs
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
Adds a wrapper for the aws_config crate so we can supply different defaults (adaptive retry, more attempts, fallback region) and so we can validate the credentials are good as soon as we create them (rather than waiting until they are first used).
> feat: create wrapper client for aws config for customizable defaults

- lib/dal-materialized-views/src/component_list.rs
- lib/dal-materialized-views/src/schema_variant_categories.rs
- lib/dal/src/schema/variant.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
The driving factor here is that the `MvIndex` was not always including all of the MVs that had been built. The rest are things that were discovered along the journey to find the cause behind the missing MVs.
Previously we were skipping returning both the patch from the previous version, and the new version of the FrontendObject if the new & old versions had the same checksum to cut down on the number of "empty" patches we would send to listening clients. However, this resulted in an unstable MvIndex if any of the MVs had been previously built and we were doing a full rebuild for any reason. The full rebuild only includes the FrontendObjects that are returned from building the MVs without includeing anything from the old/current MvIndex, and when individual MVs are built, they always check …
> Don't lose track of MVs when rebuilding, and ensure MVs have stable output

- lib/vue-lib/src/pinia/pinia_api_tools.ts
This change ensures we don't add the request Ulid to get requests, so that we can take advantage of the deduplication logic. By adding the request Ulid, it guarantees each api request is unique, so we never find a match in the state of active/pending requests and we end up spawning many many parallel API requests for the same list calls. 
JAM On Main: https://jam.dev/c/ea2a70aa-3671-414c-b441-9fa845134829 
JAM On this Branch in tools: https://jam.dev/c/596c214e-edd1-4b97-8c3e-6cea3a68d851 
<div><img src="https://media2.giphy.com/media/fQoIDlLW6A6BAhyev8/giphy.gif?cid=5a38a5a2b051qfkk4kcf468m9zdo8ukx2g3473j4yodw9p78&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/cbc/">CBC</a> on <a …
> fix(web): Don't add requestUlid for list calls

- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/layout_components/DelayedLoader.vue
The idea of this component is that, we only want to show a big loader when folks are actually waiting a significant amount of time. We don't want to "flash" a loader at them for a few frames bc the tanstack query took ~90ms to return...
> Prevent flash of `loading` state with a generalized solution

- bin/si-sdf-api-test/README.md
- bin/si-sdf-api-test/sdf_api_client.ts
- bin/si-sdf-api-test/tests/8-check_mjolnir.ts
This change adds a mjolnir smoke test for tools crons and general testing. This will be in the prod tests too.
Why use diagram calls for the test if it is likely going away in favor of the new map view? The test that was copied (the "2" API test) uses the same routes.
The README for the sdf API tests has been adjusted too for present day usage.
> Add mjolnir smoke test for tools tests

- app/web/src/components/FuncEditor/FuncEditor.vue
When changing Funcs, we were saving an old copy of the as we switched, overwriting any changes that were made. This ensures we only save the code when the funcId matches the currently selected FuncId
> fix(web): Don't save code when switching between functions

- app/web/src/components/AssetPalette.vue
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/workers/types/dbinterface.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal-materialized-views/src/mgmt_prototype_view_list.rs
- lib/dal-materialized-views/src/schema_variant.rs
- lib/dal-materialized-views/src/schema_variant/prop_tree.rs
- lib/dal-materialized-views/src/schema_variant_categories.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/checksum.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/component/attribute_tree.rs
- lib/si-frontend-mv-types-rs/src/lib.rs
- lib/si-frontend-mv-types-rs/src/management.rs
- lib/si-frontend-mv-types-rs/src/reference.rs
- lib/si-frontend-mv-types-rs/src/schema_variant.rs
- lib/si-frontend-mv-types-rs/src/schema_variant/prop_tree.rs
- lib/si-frontend-mv-types-rs/src/temporary_conversion_impls.rs
This PR includes the following updates: 
- AttributeTree is no longer a separate MV and is now included in the Component MV
- Removed the pointers to the Root AV's children as we can use the path to get what we need
- Created PropTree structure, similar to the AttributeTree, which is included with the SchemaVariant MV
- Added ManagementFuncKind as a stop gap until we support actual kinds. Note: this is hardcoded to match our Clover Discover/Import Mgmt Functions
- Return the Socket Name for the attribute path 
- Aligned the Prop structure returned in Components and Schema Variants, combining what each was using
- Return the same Schema Variant object when listing by category as with the reference to Component
> fix: Update MVs to meet UX Needs

- app/web/src/api/sdf/dal/schema.ts
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- Right now, this only goes over the props within component attributeValue trees.
- It does not include components sockets
- Sockets are going the way of the dodo
- The new prop <-> prop connection API doesn't support sockets at all
- This work does not give us parity with "edges" on the old system
- The docker / butane relationship basically doesn't work in this world
- Right now, we don't yet have secrets, which means you cannot connect an AWS cred to any component that needs it
On attribute input focus use the key `PossibleConnections` and make the call for `getPossibleConnections` for the annotation type you have on your prop, and the direction (when looking to fill a prop, you're looking for output sockets and other props)
There are three pieces of the return:
- `exactMatches`: this …
> Caching possible connections for the fuzzy filter search

- lib/edda-server/src/data_cache.rs
We already suppress individual empty patches to prevent needless messaging, but if the entire PatchBatch has no patches, we were still sending it. We now make sure that there are patches in the PatchBatch before sending the batch out to listening clients.
> Do not send empty PatchBatch

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
- lib/sdf-server/src/service/v2/index/get_front_end_object.rs
<div><img src="https://media2.giphy.com/media/U7isUDZ6VPWJW/200.gif?cid=5a38a5a2nmc2kugwe1tl1stj3fwtrnhqui6j2rn0tnqhsvz4&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:243px;width:300px"/><br/>via <a href="https://giphy.com/gifs/comedy-tim-and-eric-U7isUDZ6VPWJW">GIPHY</a></div>
> fix(edda,sdf): Flip some events to debug level, and return more accurate errors on mjlonir endpoints

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/types.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/store/realtime/realtime.store.ts
- app/web/src/store/realtime/realtime_events.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- lib/dal/src/change_set.rs
- lib/dal/src/change_set/event.rs
- lib/dal/src/ws_event.rs
- lib/luminork-server/src/service/v1/change_sets/create.rs
- lib/sdf-server/src/service/public/change_sets.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/create.rs
- lib/sdf-server/src/service/v2/fs.rs
1. Before we make API calls, detect when we are on HEAD and create a new change set
2. Once that is complete, send the API POST/PUT/DELETE against the new change set
3. Tell the caller about the new change set
4. router.push appropriately
1. Listen for new change sets on the OG web socket.
2. Get the HEAD snapshot in sqlite
3. Insert the snapshot record
4. create MTM links based on the HEAD snapshot
5. insert the change set record
6. ping the `/index` endpoint to create the index MV in frigg
The current behavior leaves a lot to be desired:
- I have two open tabs, both sitting on HEAD.
- Tab 1, I make the new change set
- Tab 2, is pristine, it receives the WsEvent, creates the MTM behind the scenes ✅ no errors
- Tab 1, creates a race condition because...
- it redirects you to the new …
> New Arch, New ChangeSet

- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/component/upgrade.rs
Right now we drop subscriptions to a component when we upgrade it. This fixes that.
<IMG SRC="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExb2NoNHR6ZTMwOHI4dW51ZjJ3bWZqaHE5bzV0aTF2bHR3bmJ3YnhieCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7vfhdCIn13zm8/giphy.gif" />
> feat(dal): preserve attribute subscriptions on upgrade

- lib/dal/src/workspace_snapshot/edge_weight.rs
- lib/dal/src/workspace_snapshot/node_weight.rs
This adds a unit test which will fail if NodeWeight or EdgeWeight gets bigger. It also checks individual NodeWeight sizes so we can get a sense of what's impacting node size.
If you increase the size of one of the individual NodeWeight variants, it can have multiplicative effects beyond just the type you modified: increasing the biggest variants will increase the size of NodeWeight itself, which effectively increases *all* node sizes (since petgraph reserves space for a NodeWeight, not an individual variant). Increasing smaller node weights will have minimal impact on runtime space requirements.
> chore(dal): Test if we unintentionally regress node/edge size

- app/web/src/newhotness/layout_components/AttributeInput.vue
Steps to repro:
1. go to an AWS Region component
2. open the `Diff` panel
3. change the region dropdown to a different value by picking from the list
4. see the full label value in the text box
5. see the value of region change in the diff panel (you may need to rebuild the index if patches aren't working)
> Fix: send the right option value, and display the label of the chosen option

- lib/dal-materialized-views/src/action_view_list.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/sdf-server/src/service/v2/index.rs
This includes the following: 
1. Ensure that within an Action MV, the list of cross action dependencies is stably ordered
2. Return 404 on the other custom error kind I added (I just missed this yesterday)
3. (main fix!) After we loop through the ready to process MV kinds, we need to see if any of those kinds actually had build tasks spawned/queued, and if not, remove it from the dep graph. Otherwise, downstream MV Kinds will never become ready because we were only removing the kind from the graph when the build tasks finished, so if one was never spawned we'd wait forever
> wip(edda): Various fixes to Edda and MVs

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
The MV ID for the ComponentList was accidentally the entity ID instead of the change set ID. This could cause an incredible number of rebuilds since the MV ID could change based on any affected Component.
> Fix MV ID population for ComponentList

- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/component.rs
- lib/dal/src/func/authoring/save.rs
- lib/dal/src/pkg/import.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/selector.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
- lib/dal/tests/integration_test/component/paste.rs
Right now, when you copy/paste two components with subscriptions to one another (e.g. a VPC and a Subnet), the subscription is not mirrored the same way as connections: Subnet' is connected to VPC (the original). Socket connections are "mirrored" so that VPC' and Subnet' are connected; subscriptions should do the same!
Fixes ENG-3026.
- Removed AttributePrototypeArgument::set_value_from_xxx() methods, most of which are now unused.
- Reduced usage of AttributePrototypeArgument::set_value_source() as well in places where new() can be used instead.
> feat(dal): Mirror connections between copy/pasted components

- app/web/src/newhotness/AddViewModal.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/logic_composables/watched_form.ts
- app/web/src/router.ts
- app/web/src/workers/webworker.ts
Adding honeycomb timings that represent the "lived user experience" of how long it takes to submit a form and see your data change out the other end.
Also, fixed the vanity `head` URL to redirect properly.
> Timings on bifrosting and getReferences, Fix `head` router

- lib/dal/examples/snapshot-surfer/main.rs
This is a rudimentary CLI that lets you open a snapshot and print out a node (and/or edges). It could be tons better, but was super useful in our debugging just now!
```
~/si/lib/dal/examples$ cargo run --example snapshot-surfer ~/my.snapshot 01JVQZD3480HFAV52Y7J2X6Q05 01JQ1XD6MM993AQP3W3X248K96`
snap bytes compressed: 5824912
decompressed: 8633340
deserialization took: 362.178364ms
==================================================================================
AttributeValue 01JVQZD3480HFAV52Y7J2X6Q05 (prop 01JQ1XD6MM993AQP3W3X248K96 - code)
AttributeValue(AttributeValueNodeWeight { id: "01JVQZD3480HFAV52Y7J2X6Q05", lineage_id: "01JVQZD3480HFAV52Y7J2X6Q06", value: Some(JsonValue(ContentHash(9afc404c867338ec6cd499708784b339))), unprocessed_value: …
```
> chore(dal): snapshot node viewer for debugging

- lib/edda-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
Let's not overwork. Skip processing in Edda for abandoned Change Sets.
<div><img src="https://media2.giphy.com/media/TlK63Euc9KArc2a0kEw/giphy.gif?cid=5a38a5a2snxpuc2p91y5wsh8rlm9fixmf15x3s6xx7fy6hdr&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:306px;width:300px"/></div>
> fix(edda): skip processing abandonned change sets

- bin/si-sdf-api-test/tests/8-check_mjolnir.ts
Re-enables this now Edda is back and active in Prod.
Working test run here:
https://github.com/systeminit/si/actions/runs/15174109790/job/42670827693
> chore: re-enable mjolnir test

- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/workspace_snapshot/node_weight/attribute_prototype_argument_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
This adds a general graph validator (which only validates object AV children and socket connection validity issues right now) along with a way to fix many (but not all) of the issues it finds. Added into snapshot-fixer. We'll probably eventually want to move this out and use it more places, but this gets us where we need to go for fixing some current production problems.
```
cargo run --example snapshot-fixer ~/my.snapshot
snap bytes compressed: 5824912
decompressed: 8633340
deserialization took: 384.473895ms
Connection from APA 01JQ1XT60ZSK1SFQ93J9YZGW8W to unknown socket 01JP40FPPQBGR31K6K4WT896P4 on component 01JPT6SHX1X43GTM8XHQ6VJRTM
Removing APA 01JQ1XT60ZSK1SFQ93J9YZGW8W
Missing child attribute values for object codeItem (01JQ1XT57NHDVVE3G0RD9CH3TB): missing format …
```
> chore(dal): Validate and/or fix snapshot AV and connection issues

- .buckconfig
- lib/dal-test/src/lib.rs
- lib/si-layer-cache/src/hybrid_cache.rs
This change disables the disk caching layer in Foyer when running the DAL (and SDF) integration tests. The si-layer-cache test suite still enables full disk caching to ensure it continues to operate as before.
Without this configuration update the amount of data written to the `/tmp` filesystem is enourmous, grows with each new `Cache` entry and consumes a high number of open file handles in the process. It makes having the `/tmp` filesystem on `tmpfs` almost unusable (due to disk consumption needs of the test suites) and cleanup on disk-backed `/tmp` filesystems takes an incredibly long time due to the large number of inode records.
Addditonally, the default location for the disk cache was hardcoded to by under `/tmp` which means that no usage of `$TMPDIR` could override this decision. …
> chore(si-layer-cache): skip disk caching in DAL integration tests

- lib/dal-test/src/helpers.rs
- lib/dal-test/src/helpers/secret.rs
- lib/dal-test/src/test_exclusive_schemas/dummy_double_secret.rs
- lib/dal-test/src/test_exclusive_schemas/fallout.rs
- lib/dal-test/src/test_exclusive_schemas/mod.rs
- lib/dal/src/func/runner.rs
- lib/dal/tests/integration_test/module.rs
- lib/dal/tests/integration_test/secret.rs
This PR adapts gathering before functions to work with attribute value subscriptions.  
To test, I added a new test exclusive schema aptly named `double-dummy-secret` which is similar to the `dummy-secret` except that it also accepts an secret itself (from `dummy-secret`) to ensure we chain the before funcs appropriately.  
We didn't have coverage of chaining before funcs already, so this first tests the existing functionality that relies on socket connections, as well as ensures that adding an attribute subscription (prop to prop connection) for secrets works exactly as socket connections do. 
I pulled out some helper functions into a common place for this, so a bit more code churn than I'd like considering the actual change is only a few lines, but so it goes. 
<div><img …
> feat(dal): Support chaining before funcs when using attribute value subscriptions

- bin/clover/doc-link-cache.json
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
User reported issue where Launch Template Id from AWS::EC2::LaunchTemplate component could not connect to AWS::EC2::Instance (no input socket)
> fix: add launchtemplateid socket to ec2 instance

- bin/clover/src/cloud-control-funcs/overrides/AWS::AutoScaling::AutoScalingGroup/actions/awsCloudControlUpdate.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
Override Update Asset action function for the AWS::AutoScaling::AutoScalingGroup component. Currently this does not work when a connected AWS::EC2::LaunchTemplate has a new version, the call to the CloudControl API only passes the LaunchTemplate version, the API expects the Launch Template Id too.
> fix: override update asset func for asg component

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/workers/types/entity_kind_types.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/schema_variant_categories.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/lib.rs
- lib/si-frontend-mv-types-rs/src/reference/weak.rs
- lib/si-frontend-mv-types-rs/src/schema_variant.rs
- lib/si-frontend-mv-types-rs/src/temporary_conversion_impls.rs
This PR refactors the `SchemaVariantCategories` MV to have a `WeakReference` via the `SchemaVariantId` in line with the new pattern we're starting to follow where if MV A --- references --> MV B, but both MVs share a trigger ancestor (in this case, the Schema Category node), we can use WeakRefs and not need to build MV B twice (once when MV A is triggered, then again when MV B is triggered).
> fix(edda,web): Refactor Schema Variant Categories to do less work

- app/web/src/components/layout/navbar/NavbarPanelLeft.vue
- app/web/src/newhotness/ActionWidget.vue
- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/AddViewModal.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/Component.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/logic_composables/rainbow_counter.ts
- app/web/src/newhotness/logic_composables/watched_form.ts
- app/web/src/store/realtime/heimdall.ts
Add-on: fix the inject warnings from the counter I added.
I am seeing more "create MTM" failures with this approach because MTM linking exists while patch info comes over the wire. Notably the patch info is sending `fromChecksum=0`on a component that _absolutely exists_ on HEAD. There's no way it should be "from zero" indicating we need to create it.
I believe the in-flight work will fix that problem... but we need to check.
> Block new change set navigation until we've completed MTM linking

- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
This change does two things and is a small turn forward. 
1. If the rebuild request is a reaction to Edda getting out of date, we will propagate the `fromSnapshotAddress` on the update request, as until we're compressing these, the front end can better serially handle the patches even if it took a rebuild to generate them
2. If the rebuild request was triggered manually (via SDF `/rebuild` or as a reaction to fetching an index and detecting it needed to be rebuilt, fromSnapshot will be the same as the toSnapshot. This allows the front end to determine if it's seen this snapshot before in the first place, if it has, it'll accept the patches as normal. If it hasn't, it can refetch what it needs.
<div><img src="https://media2.giphy.com/media/m9MaXtasxTu82sCrYW/giphy.gif?cid=5a38a5a2mv2vcjprlq …
> fix(edda): Improve handling of rebuild requests

- app/web/src/workers/webworker.ts
Fixes intermittent problems where reads return null
> Fix: silly rabbit, bust the cache at the end of all the operations

- app/web/src/store/components.store.ts
- lib/dal-test/src/helpers/attribute/value.rs
- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/func/authoring.rs
- lib/dal/src/func/authoring/create.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/sdf-server/src/service/v2/component.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
- Allow setting a func ID in the subscriptions API
- feature is partly mocked: If a func ID is passed, we use a hardcoded transformation function, since we don't have a consolidated authoring path for those (they're attribute funcs with single argument and no innate bindings)
Validations: 
-  Added an integration test to validate that we could use the attribute funcs for prop to prop connections
- Live tested with direct API calls, values get set on the UI responsively
> feat: Set custom funcs on prop to prop connections

- app/web/src/newhotness/layout_components/ComponentAttribute.vue
> fix(web): Hide hidden props from the attributes panel inputs

- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/workspace_snapshot/graph.rs
- lib/dal/src/workspace_snapshot/graph/validator.rs
This moves the validator from snapshot-fixer to DAL in anticipation of using it for other purposes (including admin endpoints that can run validation and down the road, migrations).
Also improved the display of said attributes, showing the actual AV path rather than prop path.
> chore(dal): Move snapshot validator to dal for use in sdf endpoints

- app/web/src/newhotness/FuncRunCard.vue
- app/web/src/newhotness/FuncRunList.vue
- lib/dal/src/func/runner.rs
Few fixes: 
1. Need to use the computed change set Id so tanstack knows to refetch functions when switching change sets
2. Only show the Action icon if the function was an action
3. For some reason we weren't recording the component name when executing attribute functions. Now that we are, the component name can be displayed correctly going forward
> fix(web, dal): various fixes to listing func runs

- app/web/src/newhotness/Workspace.vue
- app/web/src/router.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
This PR adds an initial "lobby" for users to be sent to if their front end state is stale or otherwise needs rebuilt, as the rebuild time will be dependent on the size of the workspace, we should no longer block on this and instead, detect and handle accordingly. 
Instead of removing the blocking call entirely, I reduced the wait to 4 seconds (down from 30), thinking if the rebuild is fast enough, no reason to send you to the lobby for a split second. 
Todo: I didn't yet account for this in the create change set flow, tackling that in a follow up.
> feat(web,sdf): Initial implementation of a lobby for when the change set has gotten out of date and needs to rebuild

- app/web/src/components/AdminDashboard/WorkspaceAdmin.vue
- app/web/src/store/admin.store.ts
- lib/dal/examples/.gitignore
- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/graph/validator.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/dal/src/workspace_snapshot/node_weight/prop_node_weight.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
- lib/sdf-server/src/service/v2/change_set/validate_snapshot.rs
This PR implements an admin button to "migrate connections", which gives migrateability status of connections in a changeset:
* Finds all socket connections in your changeset
* Reports the equivalent prop subscription that it will be migrated to.
* Reports if there are any connections that we are unable to safely migrate.
<IMG SRC="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDcxdmE1eWI1eDVjNGFyMHNrbzFnYnJnZ28xMTd2eTBxNmR3bzU3YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ds9VVID0WdIqzBgLUT/giphy.gif">
The algorithm to find a corresponding prop is basically, find the prop associated with each socket (if there is exactly one), and if one side or the other has a non-identity transformation, use that as the transformation function instead of si:identity). 
We try to be as safe as possible: …
> feat(sdf): socket -> prop migration report

- lib/dal-test/src/helpers/change_set.rs
- lib/dal/src/workspace_snapshot/node_weight/action_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/attribute_value_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/component_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/component_node_weight/split_corrections.rs
- lib/dal/src/workspace_snapshot/node_weight/content_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/diagram_object_node_weight/v1.rs
- lib/dal/src/workspace_snapshot/node_weight/geometry_node_weight/v1.rs
- lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1.rs
- lib/dal/src/workspace_snapshot/node_weight/schema_variant_node_weight/v1/split_corrections.rs
- lib/dal/src/workspace_snapshot/node_weight/secret_node_weight.rs
- lib/dal/src/workspace_snapshot/node_weight/view_node_weight/v1.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
- lib/dal/src/workspace_snapshot/split_snapshot/corrections.rs
- lib/dal/tests/integration_test/node_weight.rs
- lib/dal/tests/integration_test/node_weight/diagram_object.rs
- lib/dal/tests/integration_test/node_weight/schema_variant.rs
- lib/dal/tests/integration_test/node_weight/view.rs
- lib/si-split-graph/src/lib.rs
- lib/si-split-graph/src/petgraph_traits.rs
- lib/si-split-graph/src/tests/mod.rs
- lib/si-split-graph/src/updates.rs
All correction tests pass with this on the split graph, including some new ones.
Includes a working schema variant unlock correction test (just a few tweaks were necessary).
> feat(dal,si-split-graph): port all remaining corrections to split graph

- app/web/src/components/AdminDashboard/MigrateConnections.vue
- app/web/src/components/AdminDashboard/ValidateSnapshot.vue
- app/web/src/components/AdminDashboard/WorkspaceAdmin.vue
- app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
- app/web/src/store/admin.store.ts
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
This brings inferred connections into the connection migration reporter, and shows the report in the admin dashboard (it is not pretty at all, but it's there).
> feat(sdf): Add inferred connection migration to report

- app/web/src/components/AdminDashboard/MigrateConnections.vue
- app/web/src/components/AdminDashboard/ValidateSnapshot.vue
- app/web/src/components/AdminDashboard/WorkspaceAdmin.vue
- app/web/src/store/admin.store.ts
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
This flips the socket connection migration endpoint to actually perform the migration. In this PR:
* Adds POST endpoint that does the migration: forces changeset, removes socket connections, creates equivalent prop connections and sends WsEvents, then returns a report of what was migrated and what was not
* Anything that *can* be migrated, *will* (even if there were some we couldn't)
* Only does this for migrateable connections where it is safe--where we didn't detect an issue
* Displays already-migrated inferred connections as "already has a value" so they don't continuously get re-migrated
* Adds a "Dry Run" button with a GET request that tells you what would have been migrated, without migrating
* Groups the displayed issues better and makes them a tiny bit easier on the eyes (still …
> feat(sdf): migrate socket connections

- component/nats/BUCK
Update to track environment deployments.
See: https://github.com/nats-io/nats-server/releases/tag/v2.11.4
> build(deps): upgrade to NATS server 2.11.4

- app/web/vite.config.ts
When developing from a machine that is not running the system, one needs to add the external host to the Vite config. This makes sense for production systems, but since we only use vite for development, it's kind of a hassle to have to do it for every external host.
This change allows us use any host to access a web system running with vite
> chore: Allow any host for web, on dev

- app/web/src/newhotness/FuncRunList.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/frigg/src/lib.rs
- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
- lib/sdf-server/src/service/v2/index/get_front_end_object.rs
- lib/si-frontend-mv-types-rs/src/index.rs
- lib/si-frontend-mv-types-rs/src/object/patch.rs
Thats the main fix. This includes update the table structure, updating the PatchBatch and IndexUpdate messages to return the `fromChecksum` and `toChecksum`, updated the `IndexPointer` in Frigg to include the Checksum (so we don't need to fetch the whole `MvIndex` to get this) and updating the responses for mjolnir requests to include the index checksum. 
Other fixes include: 
Fixed Func history reactivity 
Fixed handling deleted MVs by returning the previous checksum for that object
When querying sometimes you want to query the "completed" change set, and sometimes you want the "in progress" checksum we're processing
When we call `updateComputed` within the `applyPatch` process, we need to query data off the indexChecksum. So we need to pipe that through the computed, references, and …
> Cannot use snapshot addresses as markers. Using the checksum of the indexMV instead.

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
If we're unable to get the index pointer value for an existing index pointer then we should ignore it and move on to trying the next one. The read could fail if we have changed the format of the pointer value, and this should not cause the entire operation to fail. We should move on, and act as though the index pointer didn't exist in the first place to give us a chance of finding an index pointer value that is appropriate for us to reuse.
> Ignore errors retrieving index pointer values when attempting to re-use existing MvIndex for a new change set

- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/workspace_snapshot/graph/validator.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
This handles multiple connections to a single array, which was previously a migration error. It also makes the migrated connections to array sockets look more like what you would get from the new UI (with single -> array subscriptions hooking directly to explicit array elements instead of to the parent array).
* scalar -> array: We make the array a manual array, create an array element, and subscribe to the single from the array element using si:identity.
* array -> array: The subscription uses si:identity instead of si:normalizeToArray (since that's what si:normalizeToArray would do in the first place and is also the kind of subscription we create through the UI).
<IMG SRC="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2RyZ3h4dG1pd3Q5anZ3Z3QxeXJuMXlib2I4anV6c2hpN3B2M3ZwMyZlcD12MV9pbn …
> feat(sdf): migrate multiple connections to one array

- app/web/src/components/AdminDashboard/WorkspaceAdmin.vue
- app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/workspace_snapshot/graph/validator.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
This makes the Admin page a bit more pleasant when it comes to workspaces and change sets, now that we're using it a bit more:
* Reduces scrolling:
- Moves all workspace admin into the (currently unused) main panel
- Puts more information side by side rather than top to bottom
* Defaults to the current workspace when you load it up
* Selects the HEAD changeset for a workspace by default, so something is loaded up on first load
* Sorts change sets so that open and active changesets come first
It's definitely not what I'd class as *wonderful*, but it gets the most annoying things out of the way!
> feat(admin): Make workspace admin a bit more pleasant

- lib/si-frontend-mv-types-macros/src/frontend_checksum.rs
- lib/si-frontend-mv-types-macros/src/frontend_object.rs
- lib/si-frontend-mv-types-macros/src/lib.rs
- lib/si-frontend-mv-types-macros/src/materialized_view.rs
- lib/si-frontend-mv-types-macros/src/refer.rs
- lib/si-frontend-mv-types-rs/src/checksum.rs
- lib/si-frontend-mv-types-rs/src/materialized_view.rs
Previously, we were not detecting if the structure of a type used by a materialized view changed, if the type being used was not also deriving `MV`.
All types included in a materialized view (at any depth) must also implement `FrontendChecksum`, so the derive macro for `FrontendChecksum` now also provides the same kind of "definition checksum" registration as we do when deriving `MV`.
Whenever possible, the implementation of `FrontendChecksum` for a type should be derived, instead of manually implemented, so that it is also automatically included in the overall definition checksum of all types used by materialized views.
This also sets up a static `LazyLock` around `materialized_view_definitions_checksum()` to memoize the result so we only have to calculate it once for the lifetime of the …
> Create definition checksums for types that derive FrontendChecksum; include them in overall MV definition checksum

- app/web/src/newhotness/logic_composables/rainbow_counter.ts
- app/web/src/workers/mjolnir_queue.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
If we are in "true cold start state" where we don't have the data and we need to fetch it, we want to make ONE request. However, while we do a cold start, the app is rendering and making queries, that are missing and firing their own hammers.
So, we need to stick a queue in there, that collects hammers that _would_ fire, and prevent them from firing. Once the cold start is done, if we were successful, drop those hammers and ignore it — we're fully up to date. If something really weird happens, and the bulk fails (honestly, the only thing I could imagine is a timeout, but 🤷 ), let those hammers fly as a backup to get out of a broken situation.
Testing steps:
1. Go to a change set.
2. Clear your network tab
3. Hit the Ragnarok button (which drops only this change set data)
4. Watch your …
> All the hammers at the same time!

- lib/dal/src/attribute/value.rs
This is flooding our logs and causing honeycomb rate limiting, we think. Now that we have a validator that can see when this is happening, we don't need these for diagnosis; and our code has proven largely resilient against both of these issues, so while it indicates a real problem it's been noise for the kind of bugs we're solving right now.
We have fixes for most of the causes for these going forward, and the remaining causes are known and will be fixed soon. And we have a tool that can fix the issue on existing changesets, which we plan to run everywhere at some undetermined point in the future.
> fix(dal): Remove duplicate AV and missing AV warnings, replace with debug

- lib/dal-materialized-views/src/view_component_list.rs
The lack of stable ordering of the `Component`s was causing patches to be unnecessarily large, and for there to be unnecessary patches in the first place.
> Ensure Components in ViewComponentList have stable ordering

- app/web/src/newhotness/ActionCard.vue
This change disallows func run selection for enqueued actions without history of there ever being a func run. Specifically, both the click action and the "view details" option will be disabled when there is no func run for the action.
> Disallow func run selection for enqueued actions

- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
I may have switched a sign on that last PR, making multi-arity connections not migrate. This is why we have dry run, I guess :)
<IMG SRC="https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3OXppZTVwM2ZscDlvbTY3YW5wemNuZXl2NDYzNzFwMjltMjMyMjc2ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/M8cGrJFXyJMKTEfam2/giphy.gif">
> fix(dal): Fix normalize to array migration

- app/web/src/store/admin.store.ts
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
This adds the ability to migrate a single socket connection to multiple prop subscriptions, if the input socket is bound to multiple props. AWS ARN in particular uses this: you hook an ARN to its input socket, and 5 attribute functions run, splitting it up into pieces and putting it into five input props. This will create a subscription for each such prop, to the same target ARN, each one using its own attribute function.
<IMG SRC="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjhzemRmc3dhOWE0ZmR4NW9ua216MWQ3M3p3NDdiZDR4cHo4amNiciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/YBbiSlb0IzC24/giphy.gif">
> feat(sdf): Migrate ARN connections with multiple props

- lib/frigg/src/lib.rs
If we expect that the `IndexPointerValue` could fail to deserialize, and we remediate this, it isn't a `warn` level. We clearly fire this event way too often which either means we should purge Frigg stores, or live with the "un-deserializable" index value (and therefore it's not an unexpected state).
> chore(frigg): demote index key deserialize `warn` msgs to `debug`

- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
The context wasn't always reliably due to the vue lifecycle (we see warnings in the console). The IndexUpdate knows what it was for, so just pass that along and make sure it applies to that user
> Fix to exiting the lobby

- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/edda-server/src/compressed_request.rs
- lib/edda-server/src/compressing_stream.rs
This change adds a `Span` for each call to `CompressingStream.next()`, which pulls a `CompressedRequest` into a Naxum app.
Note that the time a span is open involves sitting and waiting for NATS messages on its subscription and possibly waiting for the Naxum app to poll the future to pull in the next unit of work (remember that Edda only performs one request at a time per-change set). There's also a quiescent period shutdown for this change set processing task, so some of these spans last for ~60 seconds and then close without yielding work (the task is being shutdown and so this stream is also being dropped and closes any spans in-flight).
chore(edda): remove extra instrument calls producing extra spans
-------------------------------------------------------------------------------------- …
> chore(edda): add `CompressingStream` telemetry

- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/workers/types/entity_kind_types.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal-materialized-views/src/lib.rs
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/si-frontend-mv-types-rs/src/incoming_connections.rs
This change replaces socket-to-socket connections with management connections. In addition, the input counts have been fixed for components by evaluating the "emptiness" and existence of external sources. As a result of this change, sockets have been removed from the "dal-materialized-views" crate and from the frontend's known entity types.
> Replace socket connections with management ones

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/edda-server/src/compressing_stream.rs
This change alters the strategy that the `CompressingStream` takes when
determining how many messages are currently on the tasks's subscription
(that is, the change set subject).
Prior to this change, the message's [`Info`] struct was used and
determined `read_window` from the `pending` field (and added one for the
current message). In practice, the `pending` value was always being read
as `0`, thus a `read_window` of size `1` was calculated.
This version calls the [`Stream.info_with_subjects()`] method instead to
determine how many messages on on the change set subject.
Running a load test creating 128 components, the `CompressingStream`
found the following `Info.pending` and stream subject counts:
```
edda_server::compressing_stream: first_message_info_pending=0 …
```
> fix(edda): compute compressing read window by querying stream info

- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/compressing_stream.rs
- lib/edda-server/src/config.rs
- lib/edda-server/src/handlers.rs
- lib/edda-server/tests/integration.rs
This change alters the "quiescent_period" timeout on
`ChangeSetProcessorTask`s by basing the quiet period on the last time
the `CompressingStream`'s state machine was updated. This way, if there
is still work to be done inside the compressing stream, a quiet period
will *not* be detected until we are waiting for another "first message"
(or if it stalls on another intermediate state).
Additionally, the current value of the stream's `State` is recorded as
a `task.state` attribute on the `compressing_stream.next` span. This
would allow us to alert on the compressing stream closing in unexpected
states.
chore(edda): increase default quiescent period to `10m`
------------------------
Yep, we're upping this for now!
> fix(edda): impl a liveness-aware quiescent period for compressing stream

- lib/edda-server/src/compressing_stream.rs
Prior to this change, the repeated calls to `span.record("task.state", this.state.as_ref())` would cause multiple instances of the attribute appearing in the span. This change only records the attribute once, just before the span closes.
> fix(edda): only record `task.state` span attr once in span

- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/ApplyChangeSetButton.vue
- app/web/src/newhotness/ApprovalFlowModal.vue
- lib/vue-lib/src/design-system/general/PillCounter.vue
This change adds the ability to apply change sets in the new UI. This does not include approvals, but leaves the door open to them. The apply button follows the same design style as "Add a component".
The modal supports keyboard input, including "ESC" for exiting the modal and "CMD + ENTER" for applying the change set. The modal also follows a similar style to the rest of the new UI, trading icons for keyboard shortcut suggestions.
The actions list within the modal is now driven by props and contains pill counters for each kind of action seen in the list. The pill counter building block component has been extended to allow slotted-in icons.
> Add apply change set to new UI

- app/web/src/newhotness/Map.vue
A suggested change to the default zoom/scroll behaviour when on the Map view. Instead of scroll by default being zoom in and out, make it pan around (using a touch mouse with up, down, left and right scroll this is lovely) and then alter the arrow key movements to match the scroll direction. To zoom in and out cmd/ctrl + scroll up and down. No other behaviour should be affected here, this matches the current UI Model screen.
> fix: tweak scroll and zoom behaviour when on map view

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/logic_composables/emitters.ts
- app/web/src/store/views.store.ts
- lib/dal/src/component.rs
- lib/dal/tests/integration_test/component/paste.rs
- lib/dal/tests/integration_test/component/property_order.rs
- lib/dal/tests/integration_test/secret.rs
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/duplicate_components.rs
- lib/sdf-server/src/service/v2/view/paste_component.rs
- Changes the old paste endpoint back to paste
- Implements a duplicate sdf endpoint that takes in multiple component ids, clones them and retains subscriptions and mgmt relationships
- Adds and option to the component context menu and a keyboard shortcut (cmd/ctrl+d) to duplicate
- Adds a flag to avoid us creating multiple keydown listeners
- Doesn't implement optimistic creation of copies (and feels somewhat slow, but it's reactive)
> feat: Duplicate Components on new UI

- bin/hoist/src/main.rs
- lib/dal/src/cached_module.rs
- lib/module-index-client/src/lib.rs
- lib/sdf-server/src/migrations.rs
- lib/sdf-server/src/service/v2/module/builtins.rs
- lib/sdf-server/src/service/v2/module/contribute.rs
- lib/sdf-server/src/service/v2/module/module_by_id.rs
- lib/sdf-server/src/service/v2/workspace/install_workspace.rs
- lib/sdf-v1-routes-module/src/approval_process.rs
- lib/sdf-v1-routes-module/src/install_module.rs
This change forces the `ModuleIndexClient` to re-use a once-built `reqwest::Client` to reuse underlying connection pooling, DNS lookups, etc. The bearer auth is replicated using the underlying associated header and is marked as `sensitive` so that any debug logging doesn't accidentally leak credentials (which is what that
`RequestBuilder.bearer_auth` does in its impl).
Prior to this change, every fresh `reqwest::Client` is forced to DNS-resolve its URLs, re-establish any persistent TCP connections, etc.
> fix(module-index-client): re-use `reqwest::Client` across calls

- lib/edda-server/src/change_set_processor_task.rs
- lib/edda-server/src/compressed_request.rs
- lib/edda-server/tests/integration.rs
This change adds an `si.edda.src_requests.count` attribute on each `edda.change_set_processor_task.handle_request` span so that it's easier to track how many API requests were compressed.
> chore(edda): record `src_requests.count` in `handle_task` span

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/types.ts
> ViewId doesn't have to be a prop everywhere. We can use provide/inject context instead, which can go to all children

- app/web/src/router.ts
We previously had:
```
http://localhost:8080/n/01HRFEV0S23R1G23RP75QQDCA7/head/h
```
I've added:
```
http://localhost:8080/n/01HRFEV0S23R1G23RP75QQDCA7
http://localhost:8080/n/01HRFEV0S23R1G23RP75QQDCA7/auto
```
> Adding two more routes: workspace and auto

- app/web/src/newhotness/logic_composables/emitters.ts
This change ensures that when on Grid view the cmd + a, k, e and d shortcuts work with caps lock on.
> fix: ensure key commands work with caps lock

- app/web/src/components/layout/navbar/NavbarPanelCenter.vue
- app/web/src/newhotness/ComponentGridTile.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/entity_kind_types.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component_list.rs
- lib/dal-materialized-views/src/view_component_list.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/view.rs
When looking up an EntityKind that is a List of References, call `getMany`. This does not perform a recursive "getReferences", it only looks for the single reference from the list.
This covers off our functionality for all but ONE thing: `IncomingConnectionsList`. We need the "second level" reference from the connection itself to the components. So we special case that and call `getMany` again.
- a lot of the changes here are making sure that the right types are being sent back. For example the "BifrostComponent" that is in the "ComponentList" doesn't have "SchemaVariant" b/c we don't do that "second level" reference lookup. While looking that component up directly WILL have that data. So we need different types.
- we need to massage the types in the one-off getMany call for …
> Remove N+1 from bifrost get calls

- lib/edda-server/src/compressing_stream.rs
This change demotes an `info!` line and the span for each compressing process in the `CompressingStream` struct.
Note that this means the `compressing_stream.next` `info` span will no longer be reported by default.
> chore(edda): demote `info` event & span in `CompressingStream`

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/types/entity_kind_types.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/schema_variant/prop_tree.rs
- lib/si-frontend-mv-types-rs/src/schema_variant/prop_tree.rs
This sorts suggested props *first* in the prop connections UI:
* Sorts suggested schema/props first, both for suggestSource() and suggestAsSourceFor()
* Adds suggestSources and suggestAsSourceFor to PropTree MV (and by extension, the AttributeTree MV)
> feat(web): Sort suggested prop connections first in UI

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
This makes the frontend automatically suggest props with the same name as possible sources, making many suggestions unnecessary to add.
The sort order is now:
* Explicit suggestions first
* Name+type matches next (except if they come from the same schema)
* Type matches next
This PR also makes the useQuery reactive, and fixes a performance issue introduced in the last round where we were preloading suggestions for all props even if you never selected any.
Reactivity and stability issues that appear to already exist. PotentialConnections doesn't seem to get updated when component names update; and when I switch from component to component, they don't always load until I hit reload. Doesn't seem to be new to this PR, though.
> feat(web): Automatically suggest props with the same name and type

- app/docs/src/how-tos/use-public-api.md
We have removed the need for sleeps when ensuring that values are set through to a management function. This updates the example code to demonstrate that
> chore(docs): Update Public API How-to to remove sleeps

- app/web/src/newhotness/Explore.vue
The `Map`'s incoming connection list query was firing when we didn't want it to
Refresh grid page, see no incoming connections list query
> Fix: during mounting the ? returns false, which is actually undesirable because it fires the map query, enforce the default/undefined state better

- app/web/src/newhotness/layout_components/AttributeInput.vue
This speeds up the prop connections dropdown list initialization and scrolling. Because there are so many possible connections (10-20x the number of components you have), the dropdown currently creates HTML elements for all of them, which overwhelms the browser's layout engine and takes forever. This uses virtualization to only create HTML elements for the items that will be displayed.
1. Makes the size of the list constant so that the virtualizer knows how big it is. There will basically always be more than 5 suggestions as long as there is at least one component.
2. If there are no possible connections (such as when there is only one component), we will not show possible connections at all. We added this because the previous code used `max-height` instead of a fixed `height`, which …
> feat(web): Virtualize the prop connections select list

- app/web/src/components/Workspace/WorkspaceModelAndView.vue
- app/web/src/store/change_sets.store.ts
- app/web/src/store/feature_flags.store.ts
We had previously exposed some data to the existing user experience using the new architectural pattern, behind feature flags. The flags have since been disabled with no intention of reenabling them, but they're a bit coupled, so when navigating from the diagram to the grid view, it was causing bifrost to initialize twice (and multiple cold starts) - one is enough!
I also removed the dependency between `NEW_HOTNESS` and `FRONTEND_ARCH_VIEWS` feature flags, as mixed mode was causing issues with views in the old UI when `NEW_HOTNESS` was flagged on. 
I am not going as far as ripping out _all_ of the unexercised code behind those flags - not worth it right now. Also, I think we need to move where bifrost is initialized, but that can come with future improvements. 
Manually Tested Old UI: 
- …
> fix(web): Skip initializing bifrost in modeling diagram to prevent multiple cold starts when switching between old and new experience

- lib/dal-materialized-views/src/incoming_connections_list.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-macros/src/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/incoming_connections.rs
- lib/si-frontend-mv-types-rs/src/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/reference/weak.rs
- lib/si-frontend-mv-types-rs/src/view.rs
The intent of having strong references determine the build ordering of MVs was that MVs were going to have access to other MVs that had been built earlier within the same batch. This would have allowed them to know the checksum of the other MVs without having to build it for itself, which would duplicate the amount of work performed by edda.
Instead, we have been moving towards using weak references (only the kind & ID, with no checksum), which do not require either having access to MVs that may have been built within the same batch, or to re-built the MV every time it is going to be referenced from another MV.
Rather than limiting which MVs can be built at the same time in preparation for a direction we are moving away from, the only limit to the parallelism is now the …
> Remove cross-MV dependency ordering when building MVs

- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/dependent_value_graph.rs
- lib/dal/src/component.rs
- lib/dal/src/prop.rs
- lib/luminork-server/src/service/v1/components/connections.rs
- lib/luminork-server/src/service/v1/components/create_component.rs
This PR makes some chanes that improve performance of component create specifically in luminork, but likely across the board. It does the following:
* Removes the extra DVU Graph calculation in component.rs, as it is no longer needed
* Updates the input_socket_attribute_values function so that it no  longer is linear with the number of components of a given schema  variant that are present in the graph. 
* Updates the 'connections' code in luminork to no longer error if  a connection is proposed but there are multiple components whose names match. It instead returns the first match. If the user wants to disambiguate, they can use the component id.
> chore: improve performance of component create in luminork

- component/ci-base/Dockerfile
Adds the ci user to the docker group so the user in buildkite CI can use the docker daemon directly
**_NB:_** I had to remove some of the google chrome deps but I'm fairly certain we aren't even using them as they were added for cypress in buildkite, which we don't do at the minute (I'm trying to add this back in as part of my normal work + will come back to it if I need it)
> feat: add ci to docker group

- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- app/web/vite.config.ts
Uses weblocks to ensure that only one tab's worker task has access to the sqlite3 database at a time. Proxies requests through a SharedWorker to the worker that holds the lock. As soon as a tab closes, all tabs will race for the lock, and the one that acquires it first will send a proxy of itself to the SharedWorker.
Requires all DBInterface methods that hit the database to be async (so they can wait for a tab remote to be ready)
> feat(web): use a shared webworker to enable sqlite3 shared access pool

- DOCS.md
- README.md
- app/web/src/newhotness/EditViewModal.vue
- app/web/src/newhotness/Explore.vue
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/graph.rs
- lib/dal/src/workspace_snapshot/graph/v4/diagram/view.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
This change protects the default view from deletion at the graph level as well as provides tooltip text for default views in the edit modal in the new UI.
In addition to that change, the local development docs have been edited to mention the SSL requirement when not using localhost. This was already recommended, but is now required with the recent webworker changes and its lock acquisition code.
> Protect the default view from deletion

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/components/connections.rs
- lib/luminork-server/src/service/v1/components/create_component.rs
- lib/luminork-server/src/service/v1/components/find_component.rs
- lib/luminork-server/src/service/v1/components/mod.rs
- lib/luminork-server/src/service/v1/components/subscriptions.rs
- lib/luminork-server/src/service/v1/components/update_component.rs
This will allow a user to set subscriptions from a prop on a component to another prop. We can do this as follows:
```
{
"domain": {
"propId1": "value1",
"path/to/prop": "value2"
},
"name": "MyComponentName",
"schemaName": "AWS::EC2::Instance",
"secrets": {
"secretDefinitionName": "secretName"
},
"subscriptions": {
"/prop/path/on/this/component": {
"component": "OtherComponentName",
"propPath": "/prop/path/on/other/component"
}
}
}
```
Please Note: I will refactor this to remove the duplication from the new dal constructs - I need this to get out there!
> feat(luminork): Add support for setting prop subscriptions

- app/web/src/newhotness/ComponentCard.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/DeleteModal.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/ShortcutModal.vue
- app/web/src/newhotness/layout_components/ConnectionLayout.vue
- app/web/src/newhotness/logic_composables/string_funcs.ts
- truncation on the Map view
- fixed some various bugs in the Map
- fixed whole map moves/scales when selected component
- fixed the context menu in the Map so that all options are functional by click or hotkey
- zoom number on Map now has a background and border
- second click on component on Map enters, deselect by clicking on empty space, but no deselect on Pan
- fixed unfocusing the search bar in Map, change of search on Map now deselects components
- new keyboard shortcut modal accessible from the grid view, need to finish adding shortcuts to it
> feat(web) - continuing newhotness UI improvements

- app/web/src/newhotness/Workspace.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/webworker.ts
`heimdall.init` cannot wait on `tabDb.initBifrost` due to the locking scheme. And the `setRemote` call is asnyc. This introduced a race in the `Workspace.vue` where the `watch` to reconnect the web socket was firing _before_ the web socket was initialized. 
- Seeing the bifrost web socket in the dev tool
- Changing component name seeing a patch come through
> Fix: shared web worker initialization needs to be awaited/watched diferently now that its doing the lock dance

- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
Ensures that if the database lock is acquired by one tab, every tab knows about it.
Tested by opening lots of tabs and seeing that they all render the change set eventually.
> fix(web): ensure we set lockAcquired = true on other tabs

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/ComponentDetails.vue
- lib/sdf-server/src/service/v2/view.rs
- lib/sdf-server/src/service/v2/view/create_component.rs
Right now, we wait for edda to finish indexing new components before we show their attributes. With this change, we display new components as soon as they are created.
This PR:
* Adds the attribute tree to the create_component response
* Caches the attribute tree MV from the response so that it can be used in the absence of a true updated index
* Uses the cached attribute tree MV when the index has not yet been updated
* Switches to use the real attribute tree MV when it becomes available
* This does not speed up the actual creation of the component (if anything, it slows it down, because it adds data to the response). This means that when you double click, there is still a long, perceptible pause (with no feedback) before the component is created and the new page opens.
* This will not …
> feat(web): Show new components instantly

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/reference.rs
The build all MVs & build for changes info spans now include the number of MVs built, how long each one took on average, which kind was the slowest to build, and how long the slowest took to build. This information should help when investigating slower than expected MV building, and give us metrics to use to monitor edda's performance over time.
Example screenshot of Jaeger from local testing:
> Add info about MV build timings to build all & build for changes info spans

- lib/dal-test/src/expected.rs
- lib/dal/src/attribute/attributes.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/func/binding/leaf.rs
- lib/dal/src/management/mod.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
- lib/dal/tests/integration_test/property_editor.rs
- lib/sdf-server/src/service/v2/change_set/validate_snapshot.rs
- lib/sdf-v1-routes-component/src/delete_property_editor_value.rs
Right now, when you remove a component, any subscribing components will get into an invalid graph state where the subscription APA has no value edge. This causes downstream errors with some operations that check for this.
This PR fixes this by removing subscriber APAs pointing directly at an AV when that AV is removed. Subscribers should have the same value they would have if the subscription to was to an array element and the array element was removed.
A couple of small factors here:
- AttributeValue::remove_by_id -> AttributeValue::remove (it is accepted and often preferred for DAL methods to take IDs instead of self, so more and more _by_id will go away in the coming months). This was a pure rename, no changes to callers or to the function itself.
- subscription tests use idiomatic …
> fix(dal): Remove subscriber APAs when removing components

- bin/clover/src/commands/generateSiSpecs.ts
- bin/clover/src/pipeline-steps/awsRegionSpecificSuggestions.ts
We are adding a specific prop suggestion for `domain/extra/Region` to point to `Region:/domain/region`
The VPC Component has no suggestion yet EC2 Instance does and you can see the suggestion sorting in the tree
> feat(clover): Add specific prop suggestion for region pros

- app/web/src/newhotness/EditViewModal.vue
- app/web/src/newhotness/Explore.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
This change makes the view switcher much easier to use, including aligned hover states with the options. Views are now alphabetically sorted and editing another view does not require the current view to be switched. The amalgamation of these changes results in a (hopefully) "badass" experience.
> Make the view switcher badass

- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal/src/component.rs
The IncomingConnections MV currently includes both management connections and prop to prop connections.  The management edges were backwards in this MV, which meant that when a new management edge was created (Component A -> Manages -> Component B), the component that gets triggered to rebuild is the one newly under management (Component B), only when building this MV, we're asking about the managed components (Component B -> Manages -> GO FIND THEM, SORRY NO NEW ONES SO NO PATCH), not the managing components (GO FIND THEM BECAUSE THERE IS A NEW ONE NOW -> Manages -> Component B).
After this change, when a new management connection (Component A -> Manages -> Component B) is created, when Component B is triggered to rebuild, the new management connection is included and a patch is sent!
- …
> fix(edda): Ensure new management edges propagate to the front end

- lib/sdf-server/src/service/v2/management.rs
When on a component page and the change set was abandoned then we were throwing a 500 toast
We now catch the 404 and redirect correctly to the grid view
> fix(sdf): Catch Component Not Found

- app/web/src/newhotness/api_composables/index.ts
This fixes the "on api error the spinner doesnt stop spinning" because the exception prevents the =false line.
The component which called the API ought to deal with the failure appropriately in the interface
> Fix: stop axios from throwing exceptions on 4/500s... let the caller deal with it

- app/web/src/newhotness/Explore.vue
When changing to a different change set, if the selected view doesn’t exist, then we default to `All Views`.
> fix(web): Ensure we default to the selected view

- bin/innitctl/configs/config.yaml.template
logging is deprecated as an exporter name in favour of "debug". This fixes all otel config deployments (including local)
ref: https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.111.0
> fix: otelcol updated exporter name to debug

- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/Lobby.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/router.ts
- app/web/src/store/change_sets.store.ts
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/webworker.ts
Starts the user in the lobby, and runs "muspelheim", which runs niflheim against every open change set. Only then does it exit the lobby.
Lobby is controlled by the status of the niflheim queries, not the route.
Also sends the user to the lobby / muspelheims if the tab has been idle for 12 hours+.
> feat(web): fetch all change sets on load, wait in the lobby

- app/web/src/App.vue
- app/web/src/newhotness/Workspace.vue
Don't do setup work twice
We can't figure out why Vue is loading this component twice in a row. We turned off HMR and local vue plugins. Only final guess is that we're doing async work in onBeforeMount, which we can't avoid at this moment
> Fix: add a loading guard so we dont re-do setup work

- app/web/src/newhotness/AddViewModal.vue
- app/web/src/newhotness/EditViewModal.vue
- app/web/src/newhotness/Explore.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue
- Creating a view closes the modal when clicking the Create button
- Creating a view closes the modal when hitting Enter after entering a value
- Editing a view name pulls in the name of the view to the input
https://jam.dev/c/93a78fec-3a94-4af1-9b2a-133e1105dee1
> fix: close modal on view creation

- app/web/src/newhotness/layout_components/GridItemWithLiveHeader.vue
This button didn’t do anything so I am removing it as it’s misleading
> fix(web): Remove expand-logs button on FuncRunDetails

- app/web/src/store/change_sets.store.ts
The new hotness endpoints expect a ulid in the params, not "head". This breaks some requests after applying.
> fix(web): don't redir to 'head', use the head id instead

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
Sometimes we end up with a `build_count` of `0`, and Rust gets very unhappy about this when doing `build_total_elapsed.as_millis() / build_count` (it panics).
In the case where we didn't build any MVs, we shouldn't log an "average time elapsed", "total time elapsed", or a "slowest MV kind to build" to avoid scewing any metrics.
> Protect against divide-by-zero in edda stats logging

- dev/Tiltfile
This includes Luminork in the initial "build everything" pass, so that we get everything compiled in parallel and started quicker when we first start Tilte.
When we don't do this, we often have to wait for Luminork to compile *anyway*, because only one of them can run the build at a time, and if Luminork gets the lock before sdf starts (for example), sdf has to wait for it to compile anyway!
> chore(dev): Include Luminork in initial build

- lib/edda-server/src/change_set_processor_task/materialized_view.rs
Previously, we were incorrectly logging the change set id of the new change set for both the source & target of the index reuse in edda.
> Correctly log change set id index was reused from

- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/newhotness/Workspace.vue
When transitioning to a new change set, we have to move to the lobby right away to prevent a failed call for the component mv list when Explore is mounted.
> fix(web): move to lobby optimistically on new change set

- app/web/src/newhotness/ApplyChangeSetButton.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/types.ts
This is the one case where we're rendering data before bifrost is initialized and before cold start finishes, which was causing a whole host of strange issues. Adding this flag to the context, allows the Apply button to render with a default 0 action count, and the action count updates when the query can finally run.
Manually tested to ensure that loading an empty change set succeeds, loading a change set with actions shows 0 actions initially and the correct count after cold start completes, and flipping between change sets shows the accurate count as well. 
<div><img src="https://media2.giphy.com/media/6rdMX8uL9NaawLhX96/200.gif?cid=5a38a5a29qr3z1jqhgo6hr8g773ans82tpjownh1ioi96maw&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g" style="border:0;height:171px;width:300px"/><br/>via <a …
> fix(web): Wait for bifrost to initialize before fetching the action view list from sqlite

- app/web/src/newhotness/Workspace.vue
- app/web/src/workers/mjolnir_queue.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
When the linking for the expected atom checksum exists, but not with our index checksum, we need to make the MTM link even though we don't need to patch any data, and we need to bust the cache when we add the MTM link.
Second fix, `enabledQueries` was being set to false by the "double mount" issue that we added the guard for.
Brit saw the first problem by:
- queue an action
- dequeue an action
The "new" checksum of the now _blank_ actions list exists linked to other changesets/index check sums... but not to this brand new index checksum
I saw the second problem by:
- starting on the modeling screen
- move to authoring
- edit an asset to turn `upgrade` on for existing components
- flip back to modeling
- enabled queries was false b/c the guard didn't let muspelheim run which sets it to …
> Fix: no-op patches may still need to create MTMs 

- app/web/src/store/realtime/heimdall.ts
Sometimes we are seeing logs that we're waiting for init but never completing; this will warn if the watch gets cancelled before completion so we can see if that's the cause.
> fix(sdf): Log if init complete is cancelled

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- Makes component groups collapsible by the user
- Stores the groupby criteria on the URL so a user can link to specific UI states
- Shows empty groups with the new design
> Add collapse, empty states and deep linking to group by

- .github/workflows/upgrade-web.yml
We were pushing up the default cache policy onto every object in S3 for web.
`Uploading s3://si-tools-web/assets/webworker.js | content-type=application/javascript; charset=utf-8 | cache-control=public,max-age=31536000,immutable`
We need the two webworker files to have a different caching strategy. This adds a custom cache policy to those two files at point of time of upload into S3, which should then be respected through the CDN.
> feat: add cache control specification to s3 upload for web

- app/web/vite.config.ts
sourcemap is part of the build object in vite.config.js, not the rollupOptions. This fixed sourcemapping for me in local production builds.
> fix(web): fix sourcemap

- app/web/src/api/sdf/dal/change_set.ts
- app/web/src/newhotness/Workspace.vue
- app/web/src/store/realtime/heimdall.ts
Load the HEAD snapshot first, which is likely to contain almost all the atoms for the other snapshots.
Also reduces concurrency in "muspelheim" to 1
> feat(web): load head first muspelheim

- lib/luminork-server/src/service/v1/components/create_component.rs
- lib/luminork-server/src/service/v1/components/mod.rs
API Usage:
Without managedBy (omit entirely):
```
{
"name": "MyComponent",
"schemaName": "AWS::EC2::Instance"
}
```
With managedBy:
```
{
"name": "MyComponent",
"schemaName": "AWS::EC2::Instance",
"managedBy": {"component": "ManagerComponentName"}
}
```
You can also use componentId rather than component
> feat(luminork): Add setting who a component is managed by at creation time

- app/web/src/newhotness/Lobby.vue
This makes the lobby blank (no spinner) for the first 400ms
> feat(web): delayed lobby

- app/web/src/components/layout/navbar/NavbarPanelLeft.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/logic_composables/rainbow_counter.ts
- app/web/src/newhotness/logic_composables/watched_form.ts
1. if you're on head the watched_form never adds a spinner (b/c you can't mutate head)
2. API index adds the label to the queue for the newly created change set
3. the useRainbow needed to return a computed for when change set changes
> Fix: editing AVs from HEAD work, but need spinner tweaks

- lib/luminork-server/src/service/v1/workspaces.rs
- lib/sdf-extract/src/change_set.rs
- lib/sdf-server/src/service/public/change_sets.rs
- lib/sdf-server/src/service/v2.rs
- lib/sdf-server/src/service/v2/fs.rs
This supports the word "head" in the luminork URL instead of a change set id. e.g. `GET /v1/w/<id>/change-sets/head/components`
It changes `ChangeSetDalContext` extractor; any endpoint that uses that will . The word "head" is matched case-insensitive, so HEAD works too.
Some SDF endpoints now support head, because it is in a common extractor. Not all do, however, because they don't all use that extractor yet. This does not try to change SDF, but it seems just fine to allow at least some endpoints to support the new pattern.
> fix(luminork): Support "HEAD" in luminork URLs

- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
When we created a component in the new UI, we checked for failing or warning qualifications and if not found then we defaulted to `all passed`.
For new components, there will be no passing, no failing and no warning. So if we find that seet of groups then we default to `unknown` as the status is actually calculating the results.
This makes the flow that when you create a component that te qualifications show unknown until they work as expected
https://jam.dev/c/d382da8c-b166-4508-bbbc-449c69966b0c
> fix(web): Remove incorrect default of all passing for qualifications

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
This change adds sort by functionality to the new UI. It uses the guts of the group by functionality to do so, but with some twists.
There are three sorts: latest to oldest, failed actions and running actions. By default, we will use latest to oldest, which sorts by each component's approximate creation time and uses their ULID-based IDs for sorting. That sort is performed before performing another sort so that we ensure relative ordering always makes sense.
Both the failed actions sort and the running actions sort leverage the pre-existing "actionViewList" in "Explore.vue". Originally, this change used an elaborate multi-point "component action state" that was summary of a component's actions. Not only was that complex and fragile, but it was nightmarish to read and arguably not …
> Add sort by functionality to new UI

- app/web/src/components/ChangesetRenameModal.vue
- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/api_composables/index.ts
- lib/sdf-server/src/service/v2/change_set/rename.rs
- lib/vue-lib/src/design-system/index.ts
- lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
- Add an option to rename change sets from the changeset dropdown
- Add a changeset rename modal with error checking 
- add helper to extract error message from api calls on the new tooling
- Allow overriding changesetId on any api route
- Refactor dropdown button to allow for a secondary action generically, specifying a custom icon
- Refactor dropdowns to only show the secondary action icon on the active item and the hovered item
> feat: Rename changesets

- app/web/src/store/realtime/heimdall.ts
The performance API is widely supported, and this will give us much more accurate timings.
> fix(web): use performance.now() instead of Date.now()

- app/web/src/api/sdf/dal/property_editor.ts
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/QualificationView.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal/src/qualification.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/temporary_conversion_impls.rs
This change removes running qualifications from the new UI. This is a very old concept that predates qualifications on the prop tree (late 2022!) and has been moved around over the years. DVU is the canonical source of prop tree functions in flight and qualification statuses are reflections of the result of DVU.
As a consequence of this work, the domain naming has been standardized across the newhotness Vue components.
An additional change here is that the two sets for action state for sort by functionality have been combined under one interface to only loop over the action list once.
Finally, there's now a comment clarifying why the "canUpgrade" variable was created in a previous PR for the grid.
> Remove running qualifications from new UI

- app/web/src/newhotness/Workspace.vue
We're seeing a mismatch between the token used and the workspace queried in some scenarios. I cannot reproduce it locally, but this may resolve it.
> fix(web): don't allow workspacePk to change in the middle of onBeforeMount

- bin/innitctl/configs/config.yaml.template
It would help if this red box was slightly bigger (or correct)
ref: https://opentelemetry.io/docs/collector/configuration/
It happened. We got stung. This fixes our metrics and spans publishing in Production.
> fix: endpoint needs specified on newer versions of otelcol

- Cargo.lock
- lib/dal-test/src/lib.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/edda-server/src/config.rs
- lib/edda-server/src/server.rs
- lib/edda-server/src/updates.rs
- lib/frigg/src/lib.rs
- lib/si-events-rs/src/lib.rs
- lib/si-events-rs/src/materialized_view.rs
- lib/si-events-rs/src/workspace_snapshot.rs
- lib/si-frontend-mv-types-macros/BUCK
- lib/si-frontend-mv-types-macros/Cargo.toml
- lib/si-frontend-mv-types-macros/src/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/action.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/incoming_connections.rs
- lib/si-frontend-mv-types-rs/src/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/object/patch.rs
- lib/si-frontend-mv-types-rs/src/schema_variant.rs
- lib/si-frontend-mv-types-rs/src/view.rs
The idea with streaming patches to the front end is that it will be able to start using the new MVs as soon as they are generated, before _all_ of the data is ready, and there will be a message with the MvIndex patch (message not created/sent yet) that will let the front end know that the stream of patches has finished, and which objects it should have by the end (fetching any it missed the patch for).
Right now, these streaming patches are sent in addition to the existing patch batches, but once we start using the streamed patches in the front end, we'll want to stop creating & sending the batched patches as it will be purely redundant from the streamed patches.
We will also want to figure out if the existing `IndexUpdate` message should be augmented to include both the from-checksum & …
> Stream patches to the front end from edda; try to reduce nats write load; priority queue for MV builds

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ConnectionsPanel.vue
- app/web/src/newhotness/ManagementConnectionsList.vue
- app/web/src/newhotness/ManagementPanel.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/types/entity_kind_types.ts
- app/web/src/workers/webworker.ts
- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/incoming_connections.rs
- lib/si-frontend-mv-types-rs/src/reference.rs
MGMT EDGES ARE OUTGOING, NOT INCOMING
1. Don't bundle them in with `IncomingConnections`
2. Give them their own MV, and their own "flipped" global map of `IncomingManagementConnections`.
3. Don't mutate the call to get outgoing connection data inside the useQuery.
4. Take the mgmt connection count off the count since it wont display in that box, its displays in the panel
> Fix: getting management edges right, and you can add a mgmt edge when there are zero existing edges

- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/store/realtime/heimdall.ts
- Wait for a change set to exist before pushing the new change set into the route when a change set is being created by the change set drop down.
- Don't go to the lobby when linking a new change set or getting a ChangeSetCreated.
- Still "cold start" on change set switch, but don't force lobby.
> feat(web): don't force lobby on new change set

- app/web/src/newhotness/Workspace.vue
Stores are dumb.
Watch the change set id in order to keep `WsEvent` subscription for `FuncRunLogUpdated` working to invalidate query.
> Fix: watch the change set id in order to keep WsEvent subscription for FuncRunLogUpdated working to invalidate query

- app/web/src/newhotness/ComponentCard.vue
- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/ComponentQualificationStatus.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/QualificationView.vue
- app/web/src/newhotness/ShortcutModal.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
This change adds the ability to pin a component. Pinning a component results in two groups being shown underneath it: its incoming and outgoing connecting components. The pinned component is placed at the top of the grid and can be focused.
There are two ways to interact with a pinned component via the keyboard. You can press "ENTER" to navigate to it or you can press "P" to unpin it. Conversely, pinning a component can be done by pressing "P" or using the component context menu. Note: the component context menu is disabled for pinned components and "group by" is disabled when pinning.
As a consequence of the primary change of this commit, component qualification status badging and iconography has been moved into its own Vue component. Not only does it make it reusable for the grid tile …
> Add ability to pin a component

- app/web/src/components/CodeViewer.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/Workspace.vue
- Workspace.vue is already listening for `FuncRunLogsUpdated`, so just bust query cache from there
- `CodeViewer` needs to re-mount on change, just like `CodeEditor` does
- Stop query polling (we can think of this as a back up) once logs are finalized, show "live" until then (don't stop polling on "Failed" just yet, we don't always have the logs, let the result of logs query "turn it off").
> Fix: bust single func run too, get CodeViewer to behave

- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- First, we can't add "extras" to `queryKey`—because the web worker has no way of knowing how to bust it
- Because we can't add extras, we cannot account for the last 2 arguments of "what do i want a suggestion for???"...
- send the full possible list over the boundary
- do the "what order ought things to be in" based on the prop, within the component itself.
- Third, we missed the web worker cache bust on the `PossibleConnections`, it was set to bust on `ChangeSetId`, needed to be `WorkspaceId`.
I screwed up what goes on what side of the boundary in my first WIP on this one... which led to folks adding "extras" to force it to work—which means busting fails.
1. On HEAD, I have Cred, Region, and EC2::Instance w/ resource all linked together
2. Create a change set
3. Make another …
> Fix: possible connections invalidations

- app/web/src/store/realtime/heimdall.ts
A race for the lock when reloading multiple tabs can cause one tab to stall forever, since it thinks the lock has been acquired too soon. Use a timeout to ensure there is time for the lock to be actually acquired.
Test this by having two or more tabs open to the new UI. Then reload them all one at a time. All tabs should finish the cold start.
> fix(web): fix reload of multiple tabs

- lib/dal-materialized-views/src/dependent_value_component_list.rs
- lib/dal-materialized-views/src/lib.rs
- lib/edda-server/src/change_set_processor_task/materialized_view.rs
- lib/si-frontend-mv-types-rs/src/dependent_values.rs
- lib/si-frontend-mv-types-rs/src/lib.rs
- lib/si-frontend-mv-types-rs/src/reference.rs
In order to provide feedback in the front end both for "data has not fully propigated yet", and "these are the components that have updates pending, because of their inputs" the `DependentValueComponentList` provides the list of all `ComponentId`s involved in the DVU graph of the current DVU Roots in the snapshot.
> Create MV listing all ComponentIds involved in unfinished DVU

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
We will not store the viewId if it’s default or all views - but we will if it’s a custom view and we will load the correct view from that queryString on deep linking
> feat(web): Ensuring we store the viewId in the queryString

- app/web/src/workers/webworker.ts
There are no defined `id` columns, and every table has `WITHOUT ROWID`, so I'm not exactly sure how SQLite was interpreting that `id as viewId`. In any case, it was wrong
> Fix: push ComponentInList to correct view

- Cargo.lock
- lib/sdf-core/BUCK
- lib/sdf-core/Cargo.toml
- lib/sdf-core/src/index.rs
- lib/sdf-core/src/lib.rs
- lib/sdf-core/src/nats_multiplexer.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/index.rs
- lib/sdf-server/src/service/v2/index/get_change_set_index.rs
- lib/sdf-server/src/service/v2/index/get_front_end_object.rs
- lib/sdf-v1-routes-ws/src/bifrost/mod.rs
- lib/sdf-v1-routes-ws/src/bifrost/proto.rs
- lib/si-frontend-types-rs/src/index.rs
- lib/si-frontend-types-rs/src/lib.rs
This change adds another request path for mjolnir requests over the bifrost web socket. The responses to these requests will stream back and interleave over this web socket.
> feat(sdf): accept object requests on web socket & stream responses

- app/web/src/newhotness/Explore.vue
The view selection watcher was deleting the map=1 from the query and forcing the grid. Unless there was a good reason for this, we should allow the user to navigate directly to the map
> fix(web): allow direct linking to map

- app/web/src/workers/webworker.ts
This was the cause of the "MVs don't update" most frequently seen with Action List. `Apply Changes` expresses a lot of the "no-op" behavior.. and it was the no-op on an AttributeTree that was causing the exception
When performing a no-op patch, we need the atom document for postProcessing. Without the document we ran into a `throw` that stopped a batch of patches from processing.
This _ought_ to prevent the `Atom is not removed, but no data for post processing` case... and changing that to not `throw` to a console error so it doesn't block other atoms
> Fix: when performing a no-op patch, we need the atom document for postProcessing

- app/web/src/newhotness/Lobby.vue
- app/web/src/newhotness/LobbyTerminalOutputLine.vue
- app/web/src/newhotness/Workspace.vue
- lib/ts-lib/src/async-sleep.ts
Changes lobby to overlay whole screen, fade in and out and show messages terminal style
> feat: Implement the lobby with messages

- app/web/src/newhotness/layout_components/AttributeInput.vue
If a prop subscription is a computed value we show `component name/` where it’s an empty string
We are going to default to `component name/<prop path>` to make it visible to a user that it’s a variable
> fix(web): Default subscriptions for computed values

- app/web/src/workers/mjolnir_queue.ts
1. When making a change on HEAD, patches and cold start are in flight at the same time. 
2. When cold start begins we let things build up in the bust queue
3. If there are no patches in the queue when the cold start ends, we let the bust queue process
4. If there are patches in there, we dont unpause
5. There was nothing in either the hammer or patch queues that turned on the bust queue
This is why the UI wasn't updating in certain circumstances. If cold start finished before any patches were generated, it would work just fine.
After processing we just need to ensure the bust queue is always running (e.g. calling start on a running queue is not a problem)
> Fix: ensure the bust queue is always running after we process data

- lib/edda-server/src/compressed_request.rs
This change demotes the orphaned span
`edda.compressed_request.from_requests` to `debug`.
This single span trace was captured over 856K times in production Honeycomb over the last 7 days.
> chore(edda): demote `edda.compressed_request.from_requests` to debug

- lib/dal/src/action.rs
- lib/dal/src/action/dependency_graph.rs
This change demotes the following spans to `debug`:
- `list_topologically`
- `action.dependency_graph.for_workspace`
The `list_topologically` is currently orphaned an always has a child of `action.dependency_graph.for_workspace` which accounts for 100% of the parent span.
This trace combination was captured over 1.67M times in production Honeycomb over the last 7 days. If future profiling is required in this area we can dial the level back up.
> chore(dal): demote dependency graph calculating orphaned spans

- app/web/src/newhotness/CodeEditorModal.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- lib/vue-lib/src/design-system/icons/custom-icons/code-pop-right.svg
- lib/vue-lib/src/design-system/icons/icon_set.ts
New and improved controls for the AttributePanel in the newhotness UI!
- Use tab to navigate and set values intuitively
- If you press tab without changing the input field tab will just move on
- If you touch the input for a value then tab will save your changes
- Unless you navigate up to the field to cancel your edits
- No more losing your place!
- Escape still cancels an edit, Enter still works as well
- I am pretty sure that now all actions can be done with the keyboard!
There are a few other improvements and bug fixes in here as well, will call them out in comments.
https://jam.dev/c/ec81c4e7-a3e4-485c-9394-06e4cb1425c9
I ran through a LOT of manual testing on a wide variety of components (the lego testing component was very helpful!), so hopefully there won't be any bugs left.
> feat(web) - better controls for newhotness AttributePanel

- app/web/src/newhotness/Lobby.vue
Somewhere in our frontend packaging process a number was being stripped out of the mask on the lobby terminal, making it show a black circle in it's middle on tools prod. This PR refactors the mask code so even if we strip out the same number, it's fully opaque always (ask me about content masks if you wanna know more but they're sort of like photoshop layer masks)
Here's what the bug looked like:
> fix: Mask lobby terminal correctly

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
https://jam.dev/c/adbc1f5b-2b5e-4cab-b266-b5d73d3824a9
This was in our original plans in Figma and we didn't implement it initially - this brings it back into play so we can easily identify what components need action taken on them
> feat(web): Highlight components on the grid with failed actions

- lib/dal-materialized-views/src/action_prototype_view_list.rs
- lib/dal-materialized-views/src/action_view_list.rs
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal-materialized-views/src/incoming_connections.rs
- lib/dal-materialized-views/src/mgmt_prototype_view_list.rs
- lib/dal-materialized-views/src/secret.rs
- lib/dal-materialized-views/src/view_component_list.rs
- lib/dal/src/action.rs
- lib/dal/src/change_set.rs
As we learned in 7084431ffa, extra allocations are a death by a thousand cuts for performance.
This focuses on the MV creation methods, specifically on uses `Vec::new()`, and `vec![]` to pre-allocate (at least) the required space, whenever possible using `Vec::with_capacity(final_entry_count)`.
In the case where we don't have a reasonable estimate of the final size of the `Vec`, and we do know how many entries we're about to add, reserve space for the batch before inserting using `vec.reserve(new_item_count)`. This reduces the number of allocations necessary to have space for all of the new entries down to a maximum of one, instead of possibly having multiple re-allocations.
> First pass at minimizing Vec (re)allocations

- app/web/src/api/sdf/dal/component.ts
- app/web/src/api/sdf/dal/prop.ts
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/api_composables/component.ts
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
- app/web/src/store/components.store.ts
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/value.rs
- lib/si-frontend-mv-types-rs/src/component/attribute_tree.rs
Presently, when you try to insert an array item underneath an array item, it fails with a 400 error.
The source of this bug was that we were using the prop path (munged to remove the initial "root") instead of the attribute path; because of this, we send the parent array item prop name instead of the actual array index.
This makes the frontend always use AttributePath instead of munging PropPath when editing / inserting / removing attributes.
It also fixes a bug where you can't insert map items when the map item is an array/object/map.
* Made AttributeTree.AttributeValue.path non-optional (which it already is)
* Stopped passing AttributeValueId around in the attribute panel; use path everywhere (which we mostly already were)
* Require "/" at the beginning of AttributePath. This gives nice …
> fix(web): Allow insertion of array items under array items

- app/web/src/newhotness/StatusPanel.vue
- app/web/src/store/realtime/realtime_events.ts
- lib/dal-test/src/helpers/component.rs
- lib/dal/src/context.rs
- lib/dal/src/job/definition/management_func.rs
- lib/dal/src/management/mod.rs
- lib/dal/src/management/prototype.rs
- lib/dal/src/ws_event.rs
- lib/dal/tests/integration_test/management.rs
- lib/luminork-server/src/service/v1/components/execute_management_function.rs
- lib/sdf-server/src/service/public/management.rs
- lib/sdf-server/src/service/v2/management.rs
This change adds management functions and operations to the status panel. Events are tracked from the first enqueued management function all the way until the downstream job is completed. This uses a simple request ID approach to keep track of every bucket item individually.
This change also removes unused management prototype code that was formerly used by luminork.
> Add management functions to status panel

- app/web/src/components/layout/navbar/ChangeSetPanel.vue
Actually uses the sleep time in the interval that waits for a change set to be ready in the new UI
> fix(web): use interval ms in ChangeSetPanel waitForChangeSetExists

- app/web/src/store/change_sets.store.ts
In the new ui if you're looking at an individual page while youre change set is merged to head we redirect you back to the explore page
1. Create a key pair
2. Open a second window that stays on the component page
3. In the first window navigate back to `Explore` and hit `Apply`
4. Watch both windows redirect to HEAD in the explore view
> Update new UI Change Set Applied To Head redirect

- app/web/src/workers/mjolnir_queue.ts
- app/web/src/workers/webworker.ts
This contains roughly all the data that is outputted via DEBUG. Turning DEBUG off for non-local!
We get a span for:
1. Each WS message received and added to a queue
2. Each element of the queue processed
3. Each patch applied.
We'll definitely have to keep our eyes on how these numbers affect the total budget. I can see us, after gaining more confidence, dropping the first one there...
Ensure that patches for new and modified components work, and that cold start works.
> Completed observability pass on the web worker

- app/web/src/newhotness/logic_composables/watched_form.ts
In the case of an api submission exception, reset the form so it can be submitted again
I was considering how to get a "universal boolean" for "did this submission succeed"... but there isnt a clean way to do it, it would essentially be a one-off check for each API call within the submission fn... not very universal. Note: this is because we've turned off the "anything except a 200 is an exception" behavior from axios, because exception handling is more annoying and detrimental to development and the user experience
> Small QOL watchedForm change

- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/LatestFuncRunDetails.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
1. Restore the ability to view the latest func run details for an action (note: as the `FuncRunId` for an action is not on the graph, and no longer in the MV, we're lazily loading it when a user clicks the action. This means we're back to letting you click an action and it might have a func run yet. We should consider if want to invest more in preventing this, or I recommend we surface information about the action that's about to run instead)
2. When a user hits retry, and the new func run starts, we will show the newest run including logs
3. Removed `FuncRunId` from the top
4. Only show the remove/retry buttons if the func run is for an action
No improvements to the experience when clicking an action that hasn't yet run. We can follow on with that after some discussion
Manual tests: 
1. …
> fix(web): Couple of fixes for action func run reactivity

- .github/workflows/e2e-validation.yml
- app/web/cypress.config.ts
- app/web/cypress/e2e/get-tiles.cy.ts
Adds tracer bullet test for the new UI, leveraging bedrock to seed the workspace.
Some work still needed to figure out how to avoid `cy.wait` but the fundamentals are there.
This test will not be executed via the crons due to where it lives in the folder structure. I'm going to write a new cron that executes this specifically on main.
> feat: only run bedrock into PG once, multiple times is not cool

- app/web/package.json
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- pnpm-lock.yaml
This adds `vpcId:vpc-1234` syntax to the search bar, allowing you to refine a search based on arbitrary attributes in a component.
* **Attribute matching:** `/domain/Foo/Bar:val` matches components where /domain/Foo/Bar = val
* **Partial attribute matching:** `Bar:val` and `Foo/Bar:val` will all match components where /domain/Foo/Bar = val.
* Partial matches will match partial *paths*, not partial attribute names: `Bar:val` will not match /domain/BarMaid or /domain/OpenBar.
* **Exact matches:** Bar:val will not match /domain/Bar = "evaluation"
* **Progressive matches:** Bar:val will match /domain/Bar = "valuation" so that it progressively refines the set of components as you continue typing each letter the word "Bar:valuation"
* Empty value does not match attributes with no value: …
> feat: Search for components by attribute

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/store/realtime/heimdall.ts
- Adds search string to URL, without adding each change to history
- Fix a watcher on explore that was trying to access data too quickly and throwing exceptions
> feat: Add search query to URL

- app/web/src/components/Workspace/WorkspaceAdminDashboard.vue
- app/web/src/pages/Hashes.vue
- app/web/src/router.ts
- app/web/src/vite-env.d.ts
- app/web/vite.config.ts
Adds two hashes to the frontend build:
`__COMMIT_HASH__`, the hash of HEAD when the frontend is built, and `__SHARED_WORKER_HASH__`, the git sha of the shared_webworker.js file when the frontend is built.
We can use the commit hash to confirm that a user is on the latest version of the frontend (they can go to `/hashes`) to see the hashes, and we will use the `__SHARED_WORKER_HASH__` to detect when the shared webworker that is resident in the browser is out of sync with the frontend code running in a tab.
> feat(web): add hashes to the frontend build

- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/MiniMap.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
When you've got more than a few tens of components, it can be easy when zoomed in to get lost in the sea of components. This adds a minimap feature to the bottom left of the map view! 
Couple neat things attempted: 
1. When zooming/panning around, ensure that the minimap always contains some portion of the nodes so even if you're zoomed into a blank area, you can easily find where everything is again
2. You can click on the minimap to pan directly to that area of the map
3. You can drag the viewbox on the minimap to pan that way (there's something laggy here that's driving me nuts, but you know, initial spike)
4. When there are more than 200 components on the map, render clusters that represent a group of components, to reduce the amount of dom elements and try and keep responsiveness …
> feat(web): Add a minimap to the map view!

- app/web/src/newhotness/AddComponentModal.vue
- app/web/src/newhotness/MarkdownRender.vue
- app/web/src/newhotness/layout_components/FilterTile.vue
- app/web/src/newhotness/logic_composables/fzf.ts
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/utils/color_utils.ts
Many small improvements to the add component modal, including -
- Improved fuzzy search!
- It starts with "All" selected and the component categories collapsed
- Reduced the amount of filters to just the useful ones, will add more later
- Better controls, including tab and shift + tab, shift + up or down to jump between categories, and left or right to switch filters
- Cleaner automatic scrolling
- Improved documentation panel with better styles and formatting
- Empty states
- It doesn't randomly change size anymore
We will definitely want to virtualize the component list eventually, the small amount of lag sometimes experienced in the panel is 100% due to the large amount of DOM elements and will only get worse with more components.
The improved fuzzy search should be ported to replace …
> feat(web) - better add component modal newhotness

- lib/dal/src/attribute/value.rs
- lib/dal/tests/integration_test/property_editor.rs
Whenever an attribute value is set by a subscription, or has any other component specific prototype, upon resetting to the schema variant defined (default) prototype, if the default prototype is a dynamic function, we enqueue it in DVU for it to get updated.  However this means that value is temporarily stale until DVU completes, leading to an unexpected user experience.
So we go from: 
1. Value Set By Subscription and value is "vpc-12345"
2. Subscription is removed but value is still "vpc-12345"
3. DVU Runs and finishes, value is removed (or updated depending on the variant)
To: 
1. Value Set by Subscription and value is "vpc-12345"
2. No subscription, value = unset 
3. DVU Runs and finishes, no change if it stays empty, or is updated.
Extended existing integration tests to ensure we …
> fix(dal): When resetting an attribute value to a default prototype, first clear the existing value

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/logic_composables/search.ts
This adds |, !, parens (), and "exact match" syntax to search.
* New `parseSearch()` reads the search string into individual terms and operators (an AST)
* `filteredComponents` recursively evaluates the search, doing individual searches for each term and then doing set operations (union for |, negate for ! ...) to figure out the results
* The order of results is preserved; for fuzzy searches, the result order is honored (though it doesn't show up yet due to Out of Scope).
* Search is *tolerant to partially-typed queries*: the goal is that as you type each character of a query, the results get closer and closer to what you want. Not having typed the end ) of a paren, or the close quote in a "exact match", should still show results matching the partial paren expression / exact match. (We …
> feat: Support boolean queries and exact matches

- .ci/delete-stacks.py
- .github/workflows/e2e-validation.yml
- .github/workflows/test-on-main.yml
- app/web/cypress.config.ts
- app/web/cypress/ux/tile-view/get-tiles.cy.ts
Tidy up nodes that are spun up and various fixes to the execution of the test variant. Make sure we only try and clean up once, and for the variants that run ec2-node type.
```
🔍 Creating a change set for deletion...
✅ Change set created: 01JZXTQYYPAWTF1DQJHX5WESRH
🔍 Searching for EC2 instance components...
⚠️ Found 1 EC2 components. Deleting...
🗑️ Deleting component: 01JZXSPY4DKEB6YYVE323AXPCH
Waiting for DVU
🚀 Applying change set to execute deletions...
✅ All EC2 components scheduled for deletion.
```
Chore: Extend the wait in the get-tiles test as the lobby is loading slower now with the same test conditions.
**Testing:**
Pass with tools / normal - https://github.com/systeminit/si/actions/runs/16231089952
Pass with ec2-node / new - …
> feat: clear down old machines, stablise tiles test

- app/web/src/components/layout/navbar/ChangeSetPanel.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/ManagementPanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/SecretInput.vue
- lib/vue-lib/src/design-system/general/SiSearch.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuButton.vue
- lib/vue-lib/src/design-system/menus/DropdownMenuItem.vue
Completes ENG-3117 - now users of the newhotness UI can see a read only ComponentDetails page for components marked for deletion.
There is a commented out restore button in the UI which we can wire up later.
Plenty of manual testing, aggressive blocking of any functions within ComponentDetails which should not run if a component has `toDelete` set to true.
> feat(web) - newhotness read only toDelete ComponentAttributes page

- bin/clover/src/cloud-control-funcs/actions/awsCloudControlDelete.ts
- bin/clover/src/cloud-control-funcs/actions/awsCloudControlUpdate.ts
If a user tries to queue an update or delete action when a resource 
doesn’t exist. This caused an error trying to get the value of payload:
```
Cannot read properties of undefined (reading 'payload')
```
This protects against using these actions and getting an unrecognisable 
Error
> fix(clover): Ensure we don't try to return a resource that doesn't exist

- app/auth-portal/package.json
- app/web/package.json
- app/web/src/newhotness/Explore.vue
- lib/vue-lib/package.json
- pnpm-lock.yaml
The library that we were using for the computedAsync filteredComponents depended on the vue version 13.5.13, and we're using vue 13.5.12. This caused typescript to get confused and not know vue would unwrap refs, giving a linting error on the Eplore.vue change we fixed here. This pr updates vue by a minor version, which didn't seem to cause any functional changes. 
We tested it manually, but had to run pnpm install on our system to get the correct linting
> fix: Update vue to 3.5.13 so we can use the vue-use library

- app/web/src/store/realtime/heimdall.ts
- app/web/src/vite-env.d.ts
- app/web/vite.config.ts
To prevent caching of old webworker code, fetch them with the hash appended.
> fix: add query string to webworker urls

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/util.ts
1. The data passed back in the arguments to `setQueryData` is a proxy which fails on the `structuredClone`.
2. We don't need to invalidate the cache in onSettled, since the patch operation is going to do that for us.
3. We don't need to track an optimistic value separately from the tan stack data, since we're mutating the tan stack data itself.
4. Re-use the findAV function, and check the AV path not the prop path (the prop path has `root/` on it, so the path was never being found correctly).
Comment out the `mutateFn` and set and/or remove the subscription to an EC2 instance Region to a /domain/extra/Region and watch the UI update without POSTing the to the API. This proves that the optimistic does something to the tanstack data and that the patch isn't the one performing the update. …
> Solidify optimistic AV operation

- app/web/src/components/AdminDashboard/MigrateConnections.vue
- app/web/src/store/admin.store.ts
- app/web/src/store/realtime/realtime_events.ts
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/dal/src/ws_event.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/migrate_connections.rs
- lib/vue-lib/src/design-system/utils/timestamp.ts
When migrations take longer than 60 seconds, we currently time out and don't complete the migration. This PR makes the migrate_connections endpoint kick off a background migration task, and sends WsEvents to communicate status to the Admin UI.
> fix: Make migrate connections endpoint async (communicates via WsEvent)

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ResourcePanel.vue
- app/web/src/newhotness/ResourceValuesPanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
- app/web/src/newhotness/logic_composables/attribute_tree.ts
This change adds the "ResourceValuesPanel" for looking at a read-only tree of values corresponding resource of a given component. There are three states for this panel: non-existence (the component will not have a resource), empty state (the component does not have a resource) and populated (the component has a resource). The empty state design is copied from "ResourcePanel".
At a nuts and bolts level, the new panel is a stripped down version of the "AttributePanel". In fact, so much has been re-used that some logic has been moved into a new composable library and likely more logic can be moved there in the near future.
Note: the empty state text has changed since this screenshot was taken!
> Add resource values panel

- app/web/src/newhotness/Workspace.vue
Don't mount other components if you're in the lobby. We don't want to issue any tan stack queries until the cold start & lobby is over.
> Don't mount other components if you're in the lobby

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
We want to highlight that there are pending actions and if they have 
failed. Also we highlight which components currently have running 
actions
We lastly want to ensure that we can get to the component that a 
function run is for
https://jam.dev/c/ec68b5bc-e84d-4a0e-8bf9-3cef00a43b94
> feat(web): Show pending actions for a component on the grid

- app/web/src/components/ComponentDetails.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/store/feature_flags.store.ts
If it takes more than 500ms to load feature flags (which can happen with posthog hiccups), we currently redirect you away from the new experience. Additionally, the redirect doesn't actually work when this happens.
This PR:
* Initializes all flags to undefined until they are loaded, so that you can tell whether it's false or "not loaded yet"
* Does not redirect until feature flags are loaded (check if featureFlag === false rather than if (!featureFlag))
* Redirects using window.location to make the redirect work
* Redirects to `/w/<workspaceId>/<changeSetId>` instead of `/w` so the link at least goes to the same change set
* Makes the redirect reactive (if the feature flag is removed in posthog while the new ui is loaded, we now redirect to the old ui). This is basically a side effect of …
> fix: don't redirect away from new experience until feature flags are loaded

- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal/src/attribute/attributes.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/func.rs
- lib/dal/src/job/definition/dependent_values_update.rs
- lib/dal/src/prop.rs
- lib/dal/tests/integration_test/attributes.rs
Right now, if an object or an array is subscribed to another object or array, we let you edit the child values in the subscriber. We should disallow this at the API level, as manually edited fields under a subscribed object will cause DVU nightmares. This PR:
* Disallows update/insert by making `vivify()` error if your path goes through a subscription (started with `/Path/To/Subscription/...`).
* Disallows remove/unset by making `attributes::update_attributes` check whether the path went through a subscription (started with `/Path/To/Subscription/...` before removing / unsetting it. This only happens if the path you looked for exists; otherwise, we've ensured our invariants fine (you told us the value shouldn't exist, and it doesn't).
* [factor] Changes `func.is_dynamic()` to …
> fix: Disallow changes to child values under subscriptions

- app/web/src/components/layout/navbar/NavbarPanelRight.vue
> fix: Show "Use Old UI" if you are on the new UI

- app/web/src/newhotness/ApplyChangeSetButton.vue
Filter out actions that were enqueued in other change sets so the count in the Apply Button and the list of actions displayed on Apply are reflected
<div><img src="https://media2.giphy.com/media/eFEmFLvVfvCFxyAG0Q/200w.gif?cid=5a38a5a2bmf30dlbqnlztu3ycf97dnpr19gjz69wtyfipomp&amp;ep=v1_gifs_trending&amp;tid=a487431853f7a6b0307f59f86930d46d637fdafdede5783dd8372561ebecf972&amp;rid=200w.gif&amp;ct=g&amp;ap=1" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/sanpellegrino/">Sanpellegrino</a> on <a href="https://giphy.com/gifs/sanpellegrino-eFEmFLvVfvCFxyAG0Q">GIPHY</a></div>
> fix(web): Only show proposed actions

- app/web/package.json
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/StatusPanel.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/webworker.ts
- pnpm-lock.yaml
Insert atoms, mtms, and do cleanup in single SQL queries to improve frontend performance.
Removes `coldStartComputed`. Handling of atoms is now entirely in `postProcess`.
Use QuickLRU for the decodedAtomCache to prevent runaway atom cache sizes.
Also included: use queriesEnabled from the context in more places to ensure we do not query before the database is ready
Load a big workspace. Ensure everything is as expected :).
Confirm management edges and possible connections are correct.
> feat(web): on cold start, do database operations in bulk

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ManagementFuncCard.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/mgmt_prototype_view_list.rs
- lib/si-frontend-mv-types-rs/src/management.rs
Adds another `ManagementFuncKind` to the system for our templates.  Eventually we'll want something better than name matching, but this is serving our needs for now. Also, when a component has a template function, we will expose it at the top of the attributes panel as we do for `Import` functions. 
Better interaction between this and the management panel. I temporarily disabled the ability to run this kind of management function from the Management Panel, but I didn't remove it entirely so we can continue to have a way to view the details of the run. 
Installed the new VPC template, confirmed that the management func kind is correct and clicking the button runs the func!
<div><img src="https://media0.giphy.com/media/gQm37vKLwkUVjOvVmp/200.gif?cid=5a38a5a29yfqe7o0um4bihw2lad4q7wxfiu5konmxa …
> feat(web,edda): Add RunTemplate management func kind and expose it at the top of the attributes panel

- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
We've seen a race condition in some circumstances where setRemote is being fired before the remote is registered. This will ensure that is impossible.
> fix(web): ensure we always register the remote before setting it

- app/web/src/newhotness/Explore.vue
The ability to find what components don’t have a resource helps when 
modelling and what has been missed so this adds that ability
> feat(web): Be able to group by hasResource on the grid

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ResourceValuesPanel.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/layout_components/AttributeChildLayout.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- lib/vue-lib/src/design-system/general/SiSearch.vue
- lib/vue-lib/src/design-system/icons/icon_set.ts
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
Fixes and improvements to the ComponentDetails page to more closely match designs in Figma.
> feat(web) - style the ComponentDetails page

- package.json
Stops this warning in our nix environment:
```
 WARN  Unsupported engine: wanted: {"node":">=18 <19"} (current: {"node":"v20.19.1","pnpm":"10.0.0"})
 ```
> chore(deps): Set the upper node engine to be <= 20

- app/web/src/newhotness/Workspace.vue
Fixes the following reference error:
> fix(web): move router above watcher that references it

- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/util.ts
We had no easy way to retrieve the filter, grouping and sorting  values when coming back to the explore page from inner pages. This PR caches those values so we can use a redirect from anywhere, using the query key `retainSessionState` to re use that cached value. This way any page can go to the last seen explore page without needing to know any details of the implementation.
The cache is only retained per tab, and goes away when it's closed so we don't have any clashes with other sessions
> feat: Retain the Explore page's filter and grouping options everywhere

- lib/dal-test/src/helpers/component.rs
- lib/dal/examples/snapshot-surfer/main.rs
- lib/dal/src/attribute/path.rs
- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/component.rs
- lib/dal/src/func.rs
- lib/dal/src/func/binding/attribute.rs
- lib/dal/src/func/intrinsics.rs
- lib/dal/src/prop.rs
- lib/dal/tests/integration_test/attributes.rs
- lib/dal/tests/integration_test/func/authoring/binding.rs
Migrating array socket connections creates duplicate values right now.
Specifically, when you have a item connected to an array via socket (and si:normalizeToArray), and try to migrate:
1. Initial state: `Foo: /domain/InstanceIds` is connected to `Bar: /resource_value/InstanceId` through a socket.
a. `/domain/InstanceIds` has no component-specific prototype. It gets its value from the "default" (the prop's prototype).
b. The prop's prototype is `si:normalizeToArray`, and the socket connection is its argument.
c. It has 1 child attribute value, created by DVU, representing the value at the other end of the socket connection.
2. Migration: first, we remove the socket connection.
a. We remove the socket connection argument from the prop's prototype.
b. This does *not* remove the actual child …
> fix: Remove old values when migrating subscriptions

- app/web/src/newhotness/Workspace.vue
Need both `deep=true`, as well as not botching the `const ids`
> Fix: erroneous redirect to HEAD

- app/web/src/workers/webworker.ts
The initIndexAndChangeSet call in handleHammer was below one of the places insertAtomMTM was called. It may also need to be called in applyPatch.
> fix(web): ensure index exists before insertAtomMTM calls

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ManagementPanel.vue
Fixes https://linear.app/system-initiative/issue/BUG-902/not-updating-attribute-tree-when-changing-between-components-in
I also did a pass at which query keys aren't reactive and updated ManagementPanel.vue as well.
<div><img src="https://media4.giphy.com/media/BYoRqTmcgzHcL9TCy1/giphy.gif?cid=5a38a5a25whss47z92v62tuzlqovrnjnnm7sc6dzdqb1kf6i&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:303px;width:300px"/><br/>via <a href="https://giphy.com/gifs/thank-you-thanks-thumbs-up-BYoRqTmcgzHcL9TCy1">GIPHY</a></div>
> fix(web): TanStack Query keys need to be reactive

- app/web/src/store/admin.store.ts
- lib/sdf-server/src/service/v2/admin.rs
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
- lib/sdf-server/src/service/v2/admin/validate_snapshot.rs
- lib/sdf-server/src/service/v2/change_set.rs
This creates 2 new routes nested under /admin for the dry run and the actual migration.  I'm using the same internals as the existing routes to limit the blast for now. During cleanup we can decide if the old routes need to stay around or not. 
Also updated the admin store to use these new routes
<div><img src="https://media0.giphy.com/media/S99uqwwvMY6Yw/giphy.gif?cid=5a38a5a2q2e9ep6mgfxt6zojf9yfk74neajitjpzg2c9lloe&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:225px;width:300px"/><br/>via <a href="https://giphy.com/challenger/">Challenger</a> on <a href="https://giphy.com/gifs/challenger-challenger23-government-fbi-S99uqwwvMY6Yw">GIPHY</a></div>
> Enable admins to trigger migrations and snapshot validations

- app/web/src/components/AdminDashboard/MigrateConnections.vue
- app/web/src/store/admin.store.ts
- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/attribute/prototype/argument/static_value.rs
- lib/dal/src/attribute/prototype/argument/value_source.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/subscription.rs
- lib/dal/src/component.rs
- lib/dal/src/func.rs
- lib/dal/src/func/intrinsics.rs
- lib/dal/src/prop.rs
- lib/dal/src/schema/variant.rs
- lib/dal/src/secret.rs
- lib/dal/src/socket/input.rs
- lib/dal/src/socket/output.rs
- lib/dal/src/workspace_snapshot.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/dal/src/workspace_snapshot/node_weight/func_node_weight.rs
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
- lib/sdf-server/src/service/v2/fs.rs
Right now, the migration output is messy for several reasons:
1. It forever shows all inferred connections, even if they are already set up as prop <-> prop subscriptions.
2. It leaves socket connections around if the corresponding prop already has a value (and forever shows them as "already migrated")
3. The actual output doesn't show socket names, making it hard to figure out what's going on
4. The output shows each socket connection and prop connection all on one bigass line, making it hard to see what is converting to what
* Migration removes socket connections even if all the corresponding props have values (since the socket connection cannot have any affect
* If there is nothing to do (i.e. already-migrated inferred socket connections), it does not report 
* Output includes …
> feat: Clean up migration output

- app/web/package.json
- app/web/src/newhotness/Workspace.vue
- app/web/src/pages/Hashes.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/shared_webworker.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
- pnpm-lock.yaml
This pr makes three changes that should increase the reliablity of the
multitab experience:
1. If lock acquisition has not been detected after 5 seconds, attempt
to force leader election.
2. If the leader changes in the middle of a request, that request will
likely hang. So detect this change using Promise.race and retry the
call in the case that leader election fails.
3. Additionally, we have given `sqlite` it's correct type (it's possibly undefined). If we run into an undefined sqlite during leader re-election, we will also retry (with a sleep).
Also upgrades sqlite-wasm to 3.50.3-build1, which was required to force
leader election by closing the database and pausing the VFS.
Test this: 
1. Open the same workspace in a lot of tabs, on the new UI.
2. Have the console open on them all. Go …
> fix(web): force leader election, restart queries if leader changed mid query

- app/web/src/components/AdminDashboard/MigrateConnections.vue
Unmigrateable connections are the more interesting information, and are also not showing in `<pre>`(so they look line one line instead of multiple).
> fix: migration: show unmigrateable connections first

- app/web/src/newhotness/ComponentDetails.vue
> feat(web): Style the buttons for taking action on ComponentDetails page

- lib/dal/src/component.rs
- lib/dal/tests/integration_test/component.rs
- lib/dal/tests/integration_test/component/connectable_test.rs
- lib/dal/tests/integration_test/component/duplicate.rs
- Modified handling of management edges to only create if they're between duplicated components
- Recreate subscriptions between duplicated components
<div><img src="https://media3.giphy.com/media/TlK63Eu0ViBklB4v5RK/200.gif?cid=5a38a5a2muwpukhhq8vk10u9vzpa4mwq0mdmgac8k1yy2s7j&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g&amp;epb=ad.kevel.71ae97c60457" style="border:0;height:170px;width:300px"/><br/>via <a href="https://giphy.com/alcrego/">A. L. Crego</a> on <a href="https://giphy.com/gifs/alcrego-loop-eternal-TlK63Eu0ViBklB4v5RK">GIPHY</a></div>
> fix(dal): When duplicating components, only retain internal management connections, recreate internal subscriptions, and retain external subscriptions

- Cargo.lock
- Cargo.toml
- lib/dal/BUCK
- lib/dal/Cargo.toml
- lib/dal/src/attribute/attributes.rs
- lib/dal/src/component.rs
- lib/dal/src/management/mod.rs
- lib/dal/src/management/prototype.rs
- lib/dal/tests/integration_test/attributes.rs
- lib/sdf-server/src/service/v2/component/attributes.rs
- lib/si-generate-template/BUCK
- lib/si-generate-template/Cargo.toml
- lib/si-generate-template/src/run_template_mgmt_func.rs
- lib/si-generate-template/templates/run_template_mgmt_func.ts
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
This makes the template generator output attributes in their original order (schema order + array order) rather than sorting them. On the other side, it honors that order in PUT /attributes. Before, templates would order `/domain/Array/10` before `/domain/Array/2`, which caused the PUT to fail.
As a side effect, it also means we can support what the docs say the API does, and do multiple appends:
```PUT /attributes
{
"/domain/Foo/-": 1,
"/domain/Foo/-": 2,
"/domain/Foo/-": 3,
}
```
This PR fixes the problem by serializing and deserializing the list of attribute updates using the `tuple_vec_crate` to preserve ordering and duplicates.
It might also be desirable to be *able* to handle attributes no matter what order they are specified in the template.
> fix: Maintain attribute order in templates and PUT /attributes

- app/web/src/newhotness/ManagementFuncCard.vue
- app/web/src/newhotness/layout_components/StatusBox.vue
This change moves the description right next to the management func name, which makes it visible without having to click it. This functionality is available for all StatusBox users, including new truncation support.
In addition to these changes, the func card now is light-theme compatible.
> Move description next to management func name

- app/web/src/newhotness/ActionWidget.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/logic_composables/component_actions.ts
- app/web/src/store/realtime/heimdall.ts
- lib/dal-materialized-views/src/mgmt_prototype_view_list.rs
- lib/dal-test/src/helpers/change_set.rs
- lib/dal-test/src/test_exclusive_schemas/legos/small.rs
- lib/dal-test/src/test_exclusive_schemas/mod.rs
- lib/dal/src/action.rs
- lib/dal/src/job/definition/management_func.rs
- lib/dal/src/management/prototype.rs
- lib/dal/tests/integration_test/action.rs
- lib/dal/tests/integration_test/management.rs
- lib/sdf-server/src/service/v2/action.rs
When importing resources, it is quite painful to have to apply a change set in order to propagate resource_values to use in downstream components. Similarly, if you know a resource has changed, it is unnecessary to have to force a new change set to get the updated values. 
Users get two key benefits from these changes: 
1. A user can import a full suite of resources, and create connections as they go, without having to do the apply/open new change set dance.
2. A user can trigger a refresh from their change set, and see the results flow back to the change set (as opposed to switching to head, hitting the button, then going back to your change set)
A new route was added to SDF that handles refresh actions **only** with the following logic: 
1. If refresh was triggered on head, enqueue the …
> Refresh actions can run in change sets

- app/web/src/newhotness/composables/useComponentDeletion.ts
When called inside async functions or callbacks, the Vue context is lost, causing the inject<Context>("CONTEXT") to return undefined
> fix(web): Ensure that we can restore a component queued for deletion

- app/web/src/newhotness/ActionCard.vue
An action link should be clickable from the list if it is failed or 
running.
> fix(web): Ensure that action links are clickable under the right circumstances

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/Workspace.vue
When navigating to the map as part of the vizualising of connections 
from the component details page, we want to behave similar to how pin 
Works. This means we will show the direct connections in and out of the 
Component and then hide everything else
https://jam.dev/c/03c9fe2c-e195-49ed-8d5d-3e0b3359b472
> feat(wb): Hide unconnected when visualizing connections

- app/web/src/newhotness/layout_components/AttributeInput.vue
Fixes: https://linear.app/system-initiative/issue/BUG-922
When on HEAD, we were seeing a new change set being created when going 
to the component details page and interacting with a readonly componemt.
the issue was because of the following chain of events:
1. Click on readonly field → openInput() called
2. openInput() → calls resetEverything()
3. resetEverything() → calls valueForm.reset()
4. valueForm.reset() → triggers form watchers/reactive updates
5. Form reactive updates → potentially emit "save" event
6. "save" event → bubbles to AttributePanel → calls save() function
7. save() function → makes API call to UpdateComponentAttributes
8. API call → triggers changeset creation if on HEAD
> fix(web): Prevent readonly field interaction causing a new change set on HEAD

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
If a user has a search that filters out a number of components on the 
grid, we want to tell them how many it filtered out so it’s more clear 
to the user
https://jam.dev/c/e373ac82-df13-477d-b433-40a0dad3e918
> feat(web): Show the number of hidden components on a search

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
When moving a component in/out of a view, we create a changeset, we just
don’t navigate to it
Also removes the word Model from the Map button
> fix(web): Navigate to created change set when moving a component

- lib/si-generate-template/templates/asset_schema.ts
- Adds a source suggestion of domain/region to the Region prop in the aws template generator code
> fix(template-gen): add region prop suggestion

- app/web/src/components/layout/navbar/NavbarPanelRight.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/nav/NavbarPanelRight.vue
There’s no turning back when we launch our new UX. This means when the 
flag goes on, it stays on :D A user can’t toggle between the old and new
UX - they are in or they are out!
> feat(web): Disable the ability for a use to toggle back and forward to the old UX

- lib/dal-materialized-views/src/component.rs
- lib/dal-materialized-views/src/component/attribute_tree.rs
- lib/dal/src/workspace_snapshot/graph/traits/component.rs
- lib/dal/src/workspace_snapshot/graph/v4/component.rs
- lib/dal/src/workspace_snapshot/selector.rs
- lib/dal/src/workspace_snapshot/split_snapshot.rs
- lib/dal/src/workspace_snapshot/split_snapshot/graph.rs
- lib/dal/src/workspace_snapshot/traits/component.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/si-frontend-mv-types-rs/src/component.rs
- lib/si-frontend-mv-types-rs/src/component/attribute_tree.rs
This change implements a method `has_socket_connections()` on `WorkspaceSnapshotSelector` which determines whether a component has at least one input socket with a connection, using lower level abstractions to reduce the performance hit of this work.
We include this data in the `ComponentInListMV` and, when true, for each `AttributeValue` we'll attempt to find if the attribute value is bein set by a socket. 
I've also removed `canBeSetBySocket` from the MV as we do not use this data in newhotness
While we have a process for migration from a socket world to a prop subscription world, some of our older Builtins and various assets authored are not able to be cleanly migrated automatically. This leaves us in a bit of a mixed state - the Component's data is correct in the new experience, but …
> Indicate whether Components (and attribute values) have socket connections so we can warn users migration wasn't cleanly possible

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
- app/web/src/newhotness/composables/useComponentDeletion.ts
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/util.ts
- app/web/src/workers/types/entity_kind_types.ts
- lib/vue-lib/src/design-system/icons/icon_set.ts
We are going to show a migration warning when a workspace has been 
migrated from socket connections to prop connections. This is going to 
be keyed off a hasSocketConnection property that will only show if they 
have an existing socket connection
the warning is going to link to a documentation page that we will add 
details to about what the new structure is and possible reasons why it 
didn’t migrate and what they would do about it
https://jam.dev/c/35174a28-b11e-442c-a7c3-8747315c6a02
> feat(web): Show workspace migration warning

- lib/dal-test/src/helpers/component.rs
- lib/dal-test/src/test_exclusive_schemas/category_validated.rs
- lib/dal/src/context.rs
- lib/dal/src/job/definition/management_func.rs
- lib/dal/tests/integration_test/management.rs
- lib/dal/tests/integration_test/validations.rs
By providing the management func state transitions with a fresh connection state, they should have an empty job queue, without impacting the "parent" context.
Without this change, when we would update the func state, we were also dispatching (in this case) validation jobs, but as we hadn't actually rebased the work resulting from the management operations, the validation job had the old value still. 
Also added an integration test for this scenario.
> fix(dal): give mgmt func state transitions a fresh connection state

- .github/workflows/run-api-test.yml
- bin/si-luminork-api-tests/run-tests.ts
This change restores the luminork API test suite, but ensures that we use the 53 error code the differentiate between actual test failures and transient ones.
> Restore luminork API tests with 53 error code

- app/web/cypress/e2e/workspace-management/workspace-dashboard.cy.ts
- app/web/cypress/support/commands.ts
Will figure out why the `appModelPageLoaded` test logic is not working in this one specific test eventually and fix it then. For now, just removing it from that one spot should get the test to pass.
> disable failing test logic for now

- app/web/src/components/ChangesetRenameModal.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/nav/ApprovalPendingModalCard.vue
- app/web/src/newhotness/nav/Notifications.vue
The API interface defaults to using the `changeSetId` from the `Context` which is based on the URL. But, there are a few times where thats not actually the change set you want to operate against! So lets add a helper to get you the data you want, and clean up the expected fields for the API context (since it doesn't need everything hanging on the `Context` object.
We can think of the `Context` like we think of the DAL Context.
1. have multiple change sets
2. go to HEAD
3. open change set dropdown
4. click to rename a changeset
5. submit the name change
6. see the URL match the chosen change set ID
> Helper to run API calls against change sets other than the one in your URL

- lib/dal/src/attribute/attributes.rs
- lib/dal/src/attribute/value.rs
- lib/dal/src/attribute/value/default_subscription.rs
- lib/dal/src/component.rs
- lib/dal/src/component/new.rs
- lib/dal/src/dependency_graph.rs
- lib/dal/src/prop.rs
- lib/dal/src/schema/variant.rs
- lib/dal/tests/integration_test/attribute_value/subscription/default_subscriptions.rs
Component::new will now create default subscriptions if a default subscription source is present that matches a prop suggestion for any prop in the component prop tree. No api routes create these default subscription sources yet, so no default subs will be created yet.
Default subs for maps do not currently make sense, since we need a way to specify the key for the value that has a default subscription.
> feat(dal): default subs for arrays and type checking

- app/web/src/newhotness/layout_components/AttributeInput.vue
This is part of our ongoing efforts to replace "connection" with "subscription" in the product.
> Update remove connection language to subscription

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ResourceValuesPanel.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
- app/web/src/newhotness/layout_components/AttrComponentList.vue
- app/web/src/newhotness/layout_components/AttrValue.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/AttributeValueBox.vue
- app/web/src/newhotness/logic_composables/attribute_tree.ts
- app/web/src/newhotness/logic_composables/watched_form.ts
- app/web/src/newhotness/types.ts
I updated some styles to match figma better. And I created some layout components to help encapsulate & reuse things. Two main things, History, and Errors.
In order to create the history, we're reading the AV trees *once*. It is in a watcher, because it comes through a query, so the data doesn't exist on mount. So we stop the watcher after the trees exist, and we process them. Then we never touch the history again. History represents the _initial_ values that you opened the bulk editing window with. It doesn't change as you save things.
In order to know when to display things, after each save, we note that the specific path we saved should now display history. We push the history value of the path into the placeholder variable the template references.
We watch the tree data (MV data) in …
> Bulk Edit History (and errors)

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/components/duplicate_components.rs
- lib/luminork-server/src/service/v1/components/mod.rs
you can use /componnets/duplicate and pass something like this:
```
{
"components": [
"01H9ZQD35JPMBGHH69BT0Q79AA",
"01H9ZQD35JPMBGHH69BT0Q79BB",
"01H9ZQD35JPMBGHH69BT0Q79CC"
],
"prefix": "copy-of-",
"viewName": "MyView"
}
```
> feat(luminork): Add duplicate components endpoint to luminork

- app/web/src/newhotness/ComponentContextMenu.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
- app/web/src/newhotness/explore_grid/ExploreGrid.vue
- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/types.ts
- lib/vue-lib/src/design-system/menus/DropdownMenu.vue
For [BUG-933](https://linear.app/system-initiative/issue/BUG-933/right-click-context-menu-bugs) leaving the bulk editing "mode" was causing the context modal to float at 0,0 because the template refs due to the show / hiding are getting lost. It seems the menu still has the _old_ template refs, which aren't in the DOM anymore, so the bounding box is all zeros (per spec).
The interdependent components (where `Explore` puts `ExploreGrid` into the Vue tree, but uses the `ExploreGrid` exposed functions in order for `Explore` to function correctly... became very trick because bulk editing _hides_ the `ExploreGrid`!
Unraveling the circular dependency and expanding the context object is a path to a resolution, both for the bug, and making this a bit easier to reason about.
Everything on the grid …
> Re-work grid dependencies

- .github/workflows/asset-update.yml
Removing the deno.lock pathspec as it’s no longer reqiored
> chore(ci): Adding a workflow dispatch to update clover assets

- app/web/src/workers/webworker.ts
A race condition is causing removeOldIndex to be called in the middle of cold start, removing foreign keys we expect to exist. Let's disable the garbage collection temporarily while we figure out the right fix.
> hotfix(web): disable atom garbage collection

- app/web/src/workers/webworker.test.ts
Remove and change some assertions to ensure the webworker test passes without removeOldIndex. These changes will have to be reverted / reworked when we restore garbage collection.
> fix(web): webworker test fixes

- app/web/src/components/StatusMessageBox.vue
- app/web/src/newhotness/QualificationPanel.vue
- app/web/src/newhotness/QualificationView.vue
The contrasts were poor in dark and light mode so we have a new design 
for that panel. We also sort the qualifications to be in the order:
* Failed
* Warning
* Passed
> fix(web): Change the colors of the QualificationPanel

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ShortcutModal.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/router.ts
- app/web/src/store/feature_flags.store.ts
- Add keyboard shortcut for opening the review screen behind a feature flag
- Refactor the messy keyboard shortcuts system in Explore (was in our way!)
- Add keyboard shortcut for opening the review screen to the ShortcutModal (behind feature flag)
We will actually implement the first iteration of the review screen in our next PR!
Checked every single shortcut to make sure that they were not broken by the refactor.
> feature flag, keyboard shortcut, organizing shortcuts

- bin/si-mcp-server/src/data/cfDb.ts
- bin/si-mcp-server/src/tools/schemaAttributesList.ts
- bin/si-mcp-server/src/tools/schemaFind.ts
- Updates the schemaFind MCP server to hard-code the IAM assets, Region, AWS Credential and String Template.
- Confirmed working for IAM assets and String Template, if you are explicit.
It hard codes the documentation for working with IAM, Region, Credential, and String Template, so the MCP server can work with them.
Adam, John and Aaron crushing it.
> feat: hardcode schema information for some things in the mcp server

- bin/si-mcp-server/src/data/cfDb.ts
- bin/si-mcp-server/src/tools/schemaAttributesList.ts
- bin/si-mcp-server/src/tools/schemaFind.ts
- updates the SI MCP server to be able to find the AWS Account asset
It hardcodes the AWS Account assets documentation and attributes so it can be used with the MCP server.
NEEDS TESTING
> feat: hardcode AWS Account schema in the SI MCP server

- app/web/src/workers/webworker.ts
Nick & Brit got into a state where:
1. browser made the new index checksum
1. browser wrote patch data for a new index
2. browser did not update the change set record to have the new index checksum
Because of the last bit, when they refreshed the page, or did a cold start, the change set wasn't getting set to the new index value. So the data that was being read was stale.
During a cold start, add the call to update the change set record to the new index checksum, even though in 99% of cases it will be a no-op.
1. browser A, make a new change set, make a change
2. open browser B (literally a different browser) load the change set.
3. see the change.
> Fix: if the index already exists but isnt on the change set, and its a valid move forward, push the change set forward to the existing index

- app/web/src/newhotness/Explore.vue
This fixes a bug that can be reproduced as follows: 
- Create a change set
- Create a component
- Type something into the search bar
- backspace and delete the query
- click on the grid
- duplicate the component
- See that the count increases, but the component doesn't show up
- See this error in the console: 
``` 
main.ts:137 TypeError: Cannot read properties of null (reading '0')
at SearchParser.consume (search.ts:380:26)
at SearchParser.parseTerm (search.ts:296:14)
at SearchParser.parseAndCondition (search.ts:281:30)
at SearchParser.parseOrCondition (search.ts:265:30)
at SearchParser.parseCondition (search.ts:254:17)
at SearchParser.parse (search.ts:228:30)
at parseSearchTerms (search.ts:189:35)
at search.ts:59:25
at async.ts:24:26
at async.ts:48:13
mapStackTrace.cacheGlobally	@ …
```
> fix(web): Normalize search string to prevent filterered components from losing reactivity

- app/web/src/newhotness/ApplyChangeSetModal.vue
- app/web/src/newhotness/ApprovalFlow.vue
When the actions list is too long, the apply button goes off screen for approvals. This wasn't caught because the list has to be ~20 actions long and the original PR restoring approvals tested this with ~10 actions.
Request with one action:
Awaiting approval with one action:
Awaiting approval with 72 actions:
> Fix apply button going off screen for approvals

- lib/dal/src/context.rs
- lib/si-db/src/transactions.rs
We're seeing panics in production in `txns`, which could only happen if the connection state is "invalid". We're investigating why the state is invalid after we try to run a transaction, but panicking is the wrong thing to do here, no matter what. So let's produce an error instead of panicking.
> fix(dal): if conn state is invalid, error instead of panicking

- app/web/src/api/sdf/dal/change_set.ts
- app/web/src/newhotness/ApplyChangeSetButton.vue
- app/web/src/newhotness/ApplyChangeSetModal.vue
- app/web/src/newhotness/ApprovalFlow.vue
- app/web/src/newhotness/StatusPanel.vue
- app/web/src/newhotness/logic_composables/change_set.ts
- app/web/src/newhotness/logic_composables/rainbow_counter.ts
- app/web/src/newhotness/logic_composables/status.ts
This change fixes the faded apply change set bug hopefully once and for all. I could not reproduce the bug locally, but it is now easy to see how (structurally) the bug could happen. In every instance of the bug happening, the spinner was not moving. We believe that because the status panel was not scoped to change sets, it would be very easy to get into a de-synced state.
- Make "status" a reactive record instead of a ref so that it can work for multiple change sets
- Make a super bucket that tracks the bucket of each change set
- Don't disable the button that brings up the modal pretty much ever (we already remove the button when on HEAD)
- Add deep=true for the rainbow watcher for increased UX
- Split the request approval and apply buttons in the modal to reduce confusion (the original …
> Fix faded apply change set

- app/web/src/newhotness/ComponentCard.vue
- app/web/src/newhotness/DiffPanel.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/composables/useComponentDeletion.ts
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/logic_composables/context.ts
- app/web/src/workers/types/entity_kind_types.ts
A first draft of the new review page - if the feature flag is on, it can be accessed by pressing "R" on the Explore page.
This version of the review page only populates its data based on the current change set context. To get totally accurate data we will need to also pull info about Head and then eventually also check the audit log.
> feat(web) - first draft of review page newhotness

- bin/si-sdf-api-test/test_helpers.ts
- bin/si-sdf-api-test/tests/4-create_two_components_connect_and_propagate.ts
We're getting sporadic timeouts across a few tests, seemingly more in Tools Prod than Prod. I'm increasing the timeout for now and can get more granular after more evidence. 
Also bumping some of the checks that need to wait for dvu to be 90 seconds
<div><img src="https://media0.giphy.com/media/2kWV5Xny049YX6kqts/200.gif?cid=5a38a5a2lnj5i5yhrf2zz2f6misz4527s1hy04lefts44h6b&amp;ep=v1_gifs_search&amp;rid=200.gif&amp;ct=g&amp;epb=ad.kevel.f7d8c18e9bba" style="border:0;height:149px;width:300px"/><br/>via <a href="https://giphy.com/teamcoco/">Team Coco</a> on <a href="https://giphy.com/gifs/teamcoco-conan-italy-2kWV5Xny049YX6kqts">GIPHY</a></div>
> fix(sdf-api-tests):let's bump the timeout to 60 seconds here for now

- DOCS.md
- app/docs/src/how-tos/use-public-api.md
This change makes the public API "how-to" use a real API test. In addition, the "DOCS" have been updated to reflect this change.
> Use an AWS account for the public API "how-to"

- lib/dal/src/schema/variant/root_prop.rs
- lib/dal/tests/integration_test/func/authoring/binding.rs
- lib/dal/tests/integration_test/schema/variant.rs
This enables us to build a tagging interface that sits agnostic of cloud
resource tagging and will work for any components
Putting this out there now so that as schema upgrades happen for users, they will be able to take advantage of this new prop that greats created on upgrade
enables us to do something like:
> feat(dal): Add the internals to create si/tags prop

- lib/dal/src/attribute/value.rs
- lib/dal/src/prop.rs
- lib/dal/tests/integration_test/attribute_value/subscription.rs
Right now, if you try to subscribe from ManagedPolicy's `PolicyDocument` to String Template `Value`, you get a "type mismatch" error. JSON is basically a specific kind of string; we don't want to disallow these subscriptions because they will in fact work.
Type mismatch rules now check that the *javascript* type is equivalent. This allows String Template to work with JSON, while still preventing the bad secret subscriptions that prompted us to check this in the first place.
> fix: Allow json -> string subscriptions (relax type mismatch error)

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
These errors are actually pretty rare!
`<AttributePanel>` provides a context with API failures against the `routes.UpdateComponentAttributes` endpoint
The right end "bump" is there for a failing validation, so I'm leaving it there for this error case as well. Can of course adjust it, but it seems we made a decision that errors display this way?
It's actually really hard to generate one of these errors, now that @jkeiser has closed the one error he had with the string template.
1. Mock error data with a hardcoded value (see screenshot)
2. See it display correctly
3. Submit a new value
4. Watch the error disappear on API success
> Display any errors from the component update attributes endpoint

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/OnboardModal.vue
- app/web/src/newhotness/api_composables/index.ts
- app/web/src/store/feature_flags.store.ts
- lib/dal-test/src/helpers/change_set.rs
- lib/dal/src/attribute/attributes.rs
- lib/dal/src/change_set.rs
- lib/dal/src/component.rs
- lib/dal/src/management/mod.rs
- lib/dal/src/property_editor/values.rs
- lib/dal/src/schema.rs
- lib/dal/tests/integration_test/action.rs
- lib/dal/tests/integration_test/attribute_value.rs
- lib/dal/tests/integration_test/attributes.rs
- lib/dal/tests/integration_test/component/upgrade.rs
- lib/dal/tests/integration_test/management.rs
- lib/dal/tests/integration_test/validations.rs
- lib/luminork-server/src/service/v1/components/mod.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/create.rs
- lib/sdf-server/src/service/v2/change_set/create_initialize_apply.rs
- lib/sdf-server/src/service/v2/component.rs
- lib/si-crypto/src/sensitive_strings.rs
Add the new endpoint so the onboarding flow can initialize the workspace with a region and a credential component, filled out and connected. Also adds a feature flagged modal for testing it out.
Extras: 
- move wait_for_dvu into dal code
- ignore empty secrets when redacting
For testing only:
- The real onboarding UI will be implemented on a further PR.
- The existing modal does not have polish. This is fine because this is only for testing. It only works for a happy path test.
- The CIA endpoint does not publish all the audit logs it needs to, this will be left for another PR.
> feat: Create change set CIA (create_initialize_apply) endpoint for onboarding flow

- lib/dal/src/component/delete.rs
- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/components/erase_component.rs
- lib/luminork-server/src/service/v1/components/mod.rs
- lib/sdf-server/src/service/v2/component/delete_components.rs
- lib/si-events-rs/src/audit_log/v1.rs
We need to be able to expose erase as a specific operation on component so that we can use it in our MCP server.
> feat(luminork): Exposing Erase component in Luminork

- app/web/src/newhotness/api_composables/index.ts
Both erase and delete components endpoints are the same, we just pass a 
different parameter. 
This means that creating a delete and erase change set will generate the
same name. That was difficult to understand for users. So we are going 
to call it “remove components” as a middle ground
> fix(web): Special case creating deleteComponents endpoint

- lib/dal/src/attribute/attributes.rs
We are being too restrictive on it’s processing so we are removing it 
and will re-add it later
> fix(dal): Remove the validate_user_can_set_directly from the attributes api

- app/web/src/newhotness/explore_grid/ExploreGridRow.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/store/realtime/heimdall.ts
- lib/vue-lib/src/design-system/icons/icon_set.ts
Ensure you can click the checkbox and don't scroll to focus the input if the blur event fires because of checking the box.
Matching as closely as I can the design of the default subscriptions grouping. Now shows the value of the source (as the design intends).
> fix(web): Ensure default subs box is checkable, style the grouping

- flake.lock
Updates the flake to get the latest buck2, which silences all those awful crates.io warnings!
Before:
After:
CI tests here will be sufficient
> chore: buck2 update

- lib/dal/src/pkg/export.rs
`ui_optionals` was not being copied onto the prop spec when exporting an existing asset. This meant prop suggestions would be dropped when editing a variant.
> fix(dal): ensure we export ui_optionals

- app/web/src/newhotness/Explore.vue
- lib/rebaser-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
2 Changes: 
1. We missed one of the places where the front end was looking for actions in the `Running` state which is no longer in use
2. We recently modified the Actions Job to no longer modify the graph to capture the action’s now-running state. We planned on exposing `Dispatched` as the user indicator that the action is in flight, however because the dispatch happens after the rebase request has been processed (and Edda has been informed), we need to again, tell Edda about the 
change to the graph that the Rebaser does directly in post processing.
- Also see that it successfully is removed on completion, and shows as failed when it fails
<div><img src="https://media0.giphy.com/media/h2OLfcSKKthRK/giphy.gif?cid=5a38a5a2y3ivgw9ly6mhlilq21jk03fy0supzcjendt2muw6&amp;ep=v1_gifs_trending&amp …
> Ensure Actions that are dispatched show as running 

- app/web/src/components/ApplyHistoryItem.vue
- app/web/src/components/SecretCard.vue
- app/web/src/components/Workspace/WorkspaceAuditLog.vue
- app/web/src/newhotness/ComponentHistory.vue
- lib/vue-lib/src/design-system/general/Timestamp.vue
- lib/vue-lib/src/design-system/utils/timestamp.ts
This change fixes an odd compiler error with the Timestamp component by using a string union for the "relative" prop on said component. All refactored locations have been tested.
> Fix odd compiler error by using string union type

- app/web/src/newhotness/AddComponentModal.vue
The scroll breaks double click by changing the element that is under the mouse.
Closes BUG-974
Test: open add component, confirm keyboard use still scrolls the list. Then using the mouse, scroll down some more and double click a component to add it. Double click should trigger new component and the list should not scroll from underneath the mouse.
> fix(web): don't scroll on click in add component

- app/web/src/newhotness/ComponentHistory.vue
- app/web/src/newhotness/Review.vue
- app/web/src/workers/types/entity_kind_types.ts
This change polishes the component history for the review screen. This includes "useInfiniteQuery" via "scrollend", correct box sizing for each entry, transitions when collapsing and expanding entries, as well as advanced filtering of audit logs and conditional display changes (e.g. setting attributes shows a cool "before and after" second line).
Collapsed and in the default view:
Expanded and in the expanded view:
There is more work to be done, like fixing query reactivity when changing components and ensuring "canLoadMore" is reactive too. However, this is a good check-in point for this work.
> Polish component history for review screen

- app/web/src/newhotness/ActionPills.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/explore_grid/ExploreGridTile.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
This change adds actions to the review screen. In addition to this change, the actions pills themselves have been split into a new component for both the review screen and grid tiles to use. This is an intentional port of the "ActionsPanel" without additional styling changes.
This change also adds icons to expand modals. This doesn't only add icons to the actions modal in the review screen, but also to all other expand modals, like qualifications in component details.
Actions in review (note that "zero" counts are included):
Explore grid tile:
Nothing is selected:
Actions expand modal:
Qualifications expand modal in component details:
- Toggle actions in review, component details AND component context menu for a given component
- Observe that grid tile, component details AND component …
> Add actions to review screen

- CONTRIBUTING.md
- DEV_DOCS.md
- README.md
This change brings repository documentation to the present. It does the following:
- Renames DOCS to DEV_DOCS to separate them more clearly from the docs site ("docs.systeminit.com")
- Align CONTRIBUTING and README step numbering schemes to be more clear about the total number of steps
- Add docs site to relevant locations
- Trim down supported development environments to match current paradigm
...and more!
> Bring repository documentation to the present

- app/web/src/newhotness/ActionWidget.vue
- app/web/src/newhotness/ActionsPanel.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/component/component_diff.rs
- lib/dal-materialized-views/src/component/erased_components.rs
- lib/dal/tests/integration_test/materialized_views.rs
- lib/si-frontend-mv-types-rs/src/component/component_diff.rs
- lib/si-frontend-mv-types-rs/src/component/erased_components.rs
Consolidates some of the data needed to hydrate this Review screen including: 
1. Include the json diff in the `ComponentDiff`
2. Include a `ComponentInList` MV for the erased components (Components that are only on head) 
3. Adds the necessary types to `entity_kind_types.ts` 
4. **Starts** to consume this on the Front End 
Here's an example component that does not exist in this Change Set being reviewed
Functional gaps:
1. The revert button does not show up at the right time (notice, we shouldn't see any of the fields for the erased component as revertible
2. Secrets information is not being propagated correctly - we now have the Secret Name in the DiffMV that we can use
3. Changes made to Secret subscriptions don't show at all
> Update some of the Mvs to give the front end what it needs and start support these new Mvs in the Review Screen

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Review.vue
When on HEAD, there are no changes to view so we should just disable 
opening the review screen.
We should also exit the reviews screen when someone is in it and 
changes to HEAD
> feat(web): Don't load reviews screen on HEAD

- app/web/src/newhotness/ReviewAttributeItem.vue
When a component subscribes to a credential, and the credential is replaced, we don't presently show it.
We always show a component diff if it shows up in the AttributeTree. Since Review.vue already excludes diffs it doesn't want in `shouldIncludeDiff()` while building the tree, we rely on that.
Moving shouldIncludeDiff() stuff into the MV itself: our concept of what we want is changing rapidly--we will consolidate the filtering into the ComponentDiff MV when we're done.
> fix: show secret changes in subscriber diffs

- app/web/src/components/StatusIndicatorIcon.vue
- app/web/src/newhotness/ComponentListItem.vue
- app/web/src/newhotness/Review.vue
Changes the review screen to have one unified component list instead of three separate ones.
> feat(web) - unified component list on the review screen

- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
- app/web/src/workers/types/entity_kind_types.ts
- lib/dal-materialized-views/src/component/component_diff.rs
- lib/si-frontend-mv-types-rs/src/component/component_diff.rs
Right now we show the revert button on attributes whether it works or not. We also don't handle the "reset" case correctly in all cases--you want to send `{ $source: null }` if the old value is not set.
* Does not show the revert button if:
- source is unchanged (i.e. subscription or dynamic thing whose value has changed)
- source is a parent subscription or dynamic value
- has children and does not want to show a diff (i.e. "extra" when extra/Region has changed)
* Reverts unset values using `{ $source: null }`
* Uses a "Revert" button on the title itself
* MV change: moves `secret` out of `$source` in the MV and into `$secret` at the top level, so that you can diff two `$source`s reliably and know whether the source has changed.
* MV change: fixes a bug where subscriptions didn't get …
> fix: show revert button on review screen only when it will work

- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
Shows secret names when you subscribe, and shows fewer defaults for added items
> fix: Show secret names, and don't show defaults for added items

- app/web/src/newhotness/Review.vue
This shows a header disclaiming that a component is set to be removed. It also sets the icon type on the side to "Removed."
* "Restore" button will follow, but likely not tonight.
* If the component is also ghosted on head (like, with a failed action), we still show the component, even though its "ghosted" state was not changed in the changeset. @britmyerss's upcoming mv will make this possible to show.
> fix: Show that a component is ghosted in review

- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/ComponentHistory.vue
- app/web/src/newhotness/ComponentListItem.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
- Values inside of each AV diff can now display on multiple lines instead of truncating
- ComponentHistory now has a loader and a better empty state
- Fixed consistency of headers across `Review` and `ComponentDetails`
- Added truncation to the header of the middle section of `Review`
- Fixed truncation balance in a few places
> review screen polish items pt 1

- app/web/src/newhotness/ComponentHistory.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- Less aggressive tooltips on the `ComponentHistory` items, more unified collapsing element styles
- First component on the `Review` screen is now selected by default (we can remove this later)
> unified collapsing styles, select first component on Review

- app/web/src/newhotness/Review.vue
This PR only adds the UI, the actual ability for components without AV diffs but with queued actions to appear on the Review screen is still in progress but will land soon.
> empty state for middle section of Review screen

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Onboarding.vue
- app/web/src/newhotness/ScrollingOutputLine.vue
- app/web/src/newhotness/WelcomeBanner.vue
- Don't navigate away from SI when onboarding is done.
- Include WelcomeBanner in empty Explore view
> fix(web): Fix onboarding style on light mode and update copy

- app/web/src/newhotness/Review.vue
- app/web/src/workers/types/entity_kind_types.ts
If you enqueue an action for a component but *don't* make any other changes, it doesn't currently show up. This uses the ActionDiffList MV to determine which components have action changes.
> fix: Show components with enequeued actions in review

- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/ReviewAttributeItem.vue
You can't revert values on erased components, and it's sort of confusing if we let you revert values on ghosted components. This PR removes the Revert buttons from attributes on both types, while keeping them for added/modified components.
> Disable the revert button on erased and ghosted components

- bin/si-mcp-server/src/tools/funcRunGet.ts
FIXES: BUG-986
We can make changeSetId optional to the fund-run-get so it prefers HEAD 
when dealing with actions.
If this was required and you prompted it to look for the details of why 
an action failed and didn’t specify HEAD but the component existed in 
Multiple change sets, you would get an error like this:
```
⏺ system-initiative - func-run-get (MCP)(funcRunId:
"01K3JR36X3KBP6YSEY70H8D4BX", logs:
true, result: true)
⎿  Error: MCP error -32602: MCP error -32602: Invalid arguments for tool 
func-run-get: [
{
"code": "invalid_type",
"expected": "string",
"received": "undefined",
"path": [
"changeSetId"
],
"message": "Required"
}
… +1 line (ctrl+r to see all)
⏺ system-initiative - func-run-get (MCP)(funcRunId:
"01K3JR36X3T4WWKCM4TRJAQKHG", logs:
true, result: true)
⎿  Error: MCP error …
```
> fix(si-mcp-server): Make change set id optional to func run get

- app/web/src/newhotness/AttributePanel.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/Explore.vue
The keyboard shortcuts on `ComponentDetails` were not set up properly so some of them just did not work. I fixed them, organized them like we do in `Explore`, and added the keyboard shortcut for going to the `Review` screen.
This PR also fixes a bug on the Grid view where the context menu would not be in the correct position when using the keyboard controls.
> fixed keyboard shortcuts and Grid tab context menu bug

- lib/dal/src/schema/variant.rs
HashSets don't have stable output, and were being used directly in the output of materialized views, resulting in unstable output. Particularly for the LuminorkSchemaVariant, and LuminorkDefaultVariant MVs.
This ensures that users of all_func_ids are always dealing with stable output.
> Ensure stable output from SchemaVariant::all_func_ids

- app/web/src/workers/mjolnir_queue.ts
- app/web/src/workers/webworker.ts
When cold starting many change sets, any one of them finishing doesn't mean we can start processing patches.
**PSA:** Putting all web worker logs behind the `_DEBUG` (false everywhere, true for local) flag so we don't flood users with information
General app usage
> Ensure patches wait for cold starts. Tighten up logging

- .ci/delete-stacks.py
- .ci/deploy-stack.py
- lib/luminork-server/src/service/v1/change_sets/force_apply.rs
- lib/luminork-server/src/service/v1/change_sets/mod.rs
We currently return a 500 if DVU roots exist when running force_apply. This changes so we return [428 Precondition Required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/428) instead (which is what we do in SDF). This implies that the client should try again later.
In addition, the `validate main` tests will now retry force applies if they encounter this error every five seconds for up to two minutes.
> feat: return 428 if dvu roots exist on force apply

- .ci/delete-stacks.py
Missed an import. 
Ran py_compile and it is good.
```
❯ python3 -m py_compile  .ci/deploy-stack.py .ci/delete-stacks.py  && echo GOOD
GOOD
```
> fix: missing import in delete-stacks

- app/web/src/newhotness/QualificationPanel.vue
In the QualificationPanel, if there were no qualifications found, we 
stopped calculating and didn’t calculate the number of validations
this meant we had a number to suggest a broken qualification but an 
empty panel. This makes it that we always calculate both
> fix(web): Ensure we don't hide validation outputs

- app/web/src/newhotness/Explore.vue
We have an amazing set of search query syntax and we need to start 
teaching users how to use it. This is the first turn to do that - future
turns can expose the examples better in the product directly
> feat(web): Show search hints on the search bar

- lib/sdf-server/src/service/v2/admin.rs
- lib/sdf-server/src/service/v2/admin/update_module_cache.rs
Ensure that we call rebuild_for_deployment when we update the cached modules via the admin paenl
> fix(dal): restore rebuild_for_deployment in cached_modules

- app/web/src/newhotness/Explore.vue
This change fixes the overflowing group selector bar. It keeps everything in the same DOM order to retain compatibility with tests.
Normal view:
Compressed view:
> Fix overflowing group selector bar

- Cargo.lock
- lib/sdf-core/BUCK
- lib/sdf-core/Cargo.toml
- lib/sdf-core/src/change_set_mvs.rs
- lib/sdf-core/src/lib.rs
- lib/sdf-server/src/service/v2/change_set.rs
- lib/sdf-server/src/service/v2/change_set/create.rs
- lib/sdf-v1-routes-change-sets/src/create_change_set.rs
- lib/sdf-v1-routes-change-sets/src/lib.rs
While the v1 endpoint was triggering the new change set message for Edda, only the v2 endpoint was actually waiting for the index update to happen.
The method used by v2 to do the trigger-and-wait is now in sdf-core where it can be used by both v1 and v2 endpoints.
> Ensure both v1 and v2 SDF API endpoints consistently trigger and wait for index update on change set creation

- app/web/src/newhotness/ComponentDebugPanel.vue
- app/web/src/newhotness/ComponentListItem.vue
- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/ManagementConnectionCard.vue
- app/web/src/newhotness/ReviewAttributeItemSourceAndValue.vue
- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
- app/web/src/newhotness/layout_components/AttrComponentList.vue
- app/web/src/newhotness/layout_components/AttrValue.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/AttributeInputPossibleConnection.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- lib/vue-lib/src/tailwind/tailwind_customization/colors.json
This PR does three things -
- Fixed colors for the newhotness UI - all new colors are inside of Tailwind now and we have light/dark mode versions for the colors which need them.
- Fixed spacing for the Explore page - the spacing was `xs` (8px) when it should've been `sm` (16px)
- Fixed menu flashing bugs for the Explore page (see comments)
> fixed newhotness colors, Explore spacing, menu bug

- lib/edda-server/src/materialized_view.rs
- lib/frigg/src/lib.rs
The MvIndex can get quite large, and isn't going to change between each MV build, so we can save a lot of network traffic by fetching the MvIndex once at the start of when we are going to build all of the MVs and feed this to each build task for it to re-use when it needs to look up what the prior version of that MV is.
> Only fetch change set MvIndex once at start of MV build

- app/web/src/newhotness/Workspace.vue
- app/web/src/newhotness/nav/NavbarPanelCenter.vue
- app/web/src/store/realtime/heimdall.ts
- app/web/src/workers/types/dbinterface.ts
- app/web/src/workers/webworker.ts
Note: it pulses to indicate retrying.
1. Mocked up a timeout after the WS connects, that closes the WS. Displays the message.
2. Open up two tabs, make sure the one web worker communicates to both tabs.
Unfortunately the dev tools "offline" doesn't close down WS connections 🤷
> Display disconnected WS status for a given workspace

- .github/workflows/run-api-test.yml
This change restores the luminork API tests, but does so with a retry loop with backoff semantics. This is not ideal as we would perfect to retry individual steps, but we've invested an abundance of time there to little effect. This retry loop may be a big hammer, but it should help the original spirit of the tests: "did we regress luminork" and "is it still online"?
> Restore luminork API tests with retry loop

- lib/sdf-server/src/service/v2/component.rs
- lib/sdf-server/src/service/v2/component/get_json.rs
There’s 1 route in func_test.vue that calls the JSON endpoint for a 
component. This is the last route for the v1-component-routes crate. 
We will migrate to this new route and delete the old crate
> feat(sdf-server): Adds a component json endpoint

- lib/dal/src/attribute/prototype.rs
- lib/dal/src/attribute/prototype/argument.rs
- lib/dal/src/workspace_snapshot/graph/validator/connections.rs
- lib/sdf-server/src/service/v2/admin.rs
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
This removes all remaining socket connections (if it can't migrate, it just sets its static value), as well as parents.
This is entirely local to the admin-only `/migrate_connections` endpoint, so it won't affect anything unless that's run. Plan currently is to test it in dry runs against workspaces that actually have parents and socket connections.
> feat: Remove all parents and socket connections in migration

- bin/hoist/src/diff.rs
We generate comments like this:
```
null
```
We need to avoid this as it causes pain in the PR review
> fix(hoist): Stop the github action from posting nulls in the diff

- bin/innit/BUCK
- flake.nix
Ensure we only build x86 for innit. Add git back to the flake for sanity's sake.
> fix: ensure git is on path and we promote the correct images for innit

- bin/cyclone/BUCK
- prelude-si/rootfs/rootfs_build.sh
lang-js is compiled with deno and runs deno so it needs deno in the rootfs
I will have to test this one manually after a try
> fix: we need deno in the rootfs

- app/web/src/newhotness/layout_components/ComponentSecretAttribute.vue
- app/web/src/newhotness/logic_composables/watched_form.ts
This change fixes an issue where the secret form is reset while the user is working within it. This solution is a bandage fix isolated to the secret form and not all forms.
> Fix issue with missing name on secret form

- bin/innitctl/Dockerfile
Innitctl needs permissions on the volumes it interacts with to create config files for other apps.
Pushed and manually tested on a tools instance
> fix: innitctl container permissions incorrect

- lib/edda-server/src/materialized_view.rs
Rather than potentially forgetting that there are any deployment-level MVs if there is something like a database connection problem while building MVs, we now treat any MV build errors as reason to not update the MV index at all.
This also means that we will short-circuit the build loop if we see an MV fail and exit early without attempting to build any further deployment-level MVs.
> Fail the entire deployment MV update if any of the individual MVs fails to build

- lib/luminork-server/src/service/v1.rs
- lib/luminork-server/src/service/v1/funcs/mod.rs
- lib/luminork-server/src/service/v1/funcs/update_func.rs
- lib/luminork-server/src/service/v1/schemas/create_action.rs
- lib/luminork-server/src/service/v1/schemas/create_attribute.rs
- lib/luminork-server/src/service/v1/schemas/create_authentication.rs
- lib/luminork-server/src/service/v1/schemas/create_codegen.rs
- lib/luminork-server/src/service/v1/schemas/create_management.rs
- lib/luminork-server/src/service/v1/schemas/create_qualification.rs
- lib/luminork-server/src/service/v1/schemas/create_schema.rs
- lib/luminork-server/src/service/v1/schemas/mod.rs
- lib/luminork-server/src/service/v1/schemas/unlock_schema.rs
- lib/luminork-server/src/service/v1/schemas/update_schema_variant.rs
The following endpoints are available:
* POST /schemas to create a schema and it's variant
* POST /schemas/{schema_id}/unlock
* POST /schemas/{schema_id}/variant/{schema_variant_id}/funcs/action
* POST /schemas/{schema_id}/variant/{schema_variant_id}/funcs/authentication
* POST /schemas/{schema_id}/variant/{schema_variant_id}/funcs/codegen
* POST /schemas/{schema_id}/variant/{schema_variant_id}/funcs/qualification 
* POST /schemas/{schema_id}/variant/{schema_variant_id}/funcs/management
* PUT /funcs/{func_id} to update a func contents
> feat(luminork): adding the authoring endpoints for Luminork

- bin/innitctl/configs/config.yaml.template
I am not sure how this got missed, but the timeout on the health_check here is adding like 90 seconds to our deploy times :(
Caught this when verifying log shipping in tools, made the change manually, and verified it
```
7b3ba1c89b1a   systeminit/otelcol:stable       "/app/docker-entrypo…"   13 minutes ago   Up 47 seconds (healthy)   0.0.0.0:4317->4317/tcp, :::4317->4317/tcp, 0.0.0.0:9090->9090/tcp, :::9090->9090/tcp, 0.0.0.0:55679->55679/tcp, :::55679->55679/tcp   otelcol
```
> fix: add health_check back to otelcol config

- app/web/src/newhotness/layout_components/AttributeInput.vue
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
Turns out the migration code for parents ran *after* the commit() :)
I also switched it out to explicitly iterate FrameContains edges, since removing all of those is one of the primary goals. Affects only migration.
> fix: Actually remove parents during migration

- app/docs/src/how-tos/use-public-api.md
- Removed an extra space in the AWS VPC Template schema name in the full python code block.
> fix: extra space typo in final python code block

- flake.lock
VS Code is showing clippy warnings from Rust 1.86, but no lint issues in RBE (because it uses a different Rust version). This fixes that by returning to pre-RBE rust in the nix flake. Thanks @sprutton1 for spoonfeeding me the exact lines to put in flake.lock :)
> fix: Return to ye olde rust to avoid clippy warnings

- bin/si-sdf-api-test/sdf_api_client.ts
- bin/si-sdf-api-test/test_helpers.ts
- bin/si-sdf-api-test/tests/3-create_and_use_variant.ts
- bin/si-sdf-api-test/tests/4-create_two_components_connect_and_propagate.ts
1. Increase timeouts basically across the board, as even if it takes a while, success is what we're looking for here
2. Add a credential and subscription to the create_two_components test 
3. Thread a helpful message when the timeout is due to the change set's index, `undefined`
Ran against prod and got consecutive passing runs! 
<div><img src="https://media2.giphy.com/media/I4Iv86mzxz4knUqiqo/giphy.gif?cid=5a38a5a2o9lefuplzjik483iohn57ubtbv6uko8uog2wxzj7&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/><br/>via <a href="https://giphy.com/inkygirl/">Debbie Ridpath Ohi</a> on <a href="https://giphy.com/gifs/fingers-crossed-I4Iv86mzxz4knUqiqo">GIPHY</a></div>
> Chore: Increase timeouts for SDF API Tests and a few other fixes

- bin/si-sdf-api-test/tests/3-create_and_use_variant.ts
This test is inconsistently passing, due to time outs when trying to fetch the SchemaVariant MV of the newly created variant.  Let’s adjust the assertion to skip the incremental step, as if we successfully create a component, we can assume the variant was created.
> Temporarily modify assertion to avoid timing issues

- app/web/src/components/AssetDetailsPanel.vue
This PR removes the options for Configuration Frame (down) and (up) from the Customize screen under 'Component Type' when creating a new Component, and hard codes the value to Component.
**Before**:
**After**:
> fix: remove frame options and hardcode component type to component

- bin/si-mcp-server/.dockerignore
- bin/si-mcp-server/.env.example
- bin/si-mcp-server/.gitignore
- bin/si-mcp-server/deno.json
- bin/si-mcp-server/package-lock.json
- bin/si-mcp-server/package.json
- bin/si-mcp-server/test/README-Testing.md
- bin/si-mcp-server/test/test-runner.js
- bin/si-mcp-server/test/test-server.sh
- deno.lock
We can now do the following in the root (after creating a .env based on .env.example)
```
npm run test
```
We introduced a .dockerignore to avoid copying any of the test infra to the container
> feat(si-mcp-server): Adding MCP Jest to our MCP server

- lib/dal/src/attribute/value.rs
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
The [previous PR](https://github.com/systeminit/si/pull/7192) was missing something important: that PR added the new method to avoid subscription typechecking, but this causes migration to actually *use* it.
> fix: allow migration to migrate subscriptions with wrong types (part deux)

- app/web/src/newhotness/ActionCard.vue
- app/web/src/newhotness/ComponentDetails.vue
- app/web/src/newhotness/DocumentationPanel.vue
- app/web/src/newhotness/Review.vue
- app/web/src/newhotness/explore_grid/AttributePanelBulk.vue
- app/web/src/newhotness/layout_components/AttributeInput.vue
- app/web/src/newhotness/layout_components/CollapsingFlexItem.vue
- app/web/src/newhotness/layout_components/ComponentAttribute.vue
- app/web/src/newhotness/layout_components/DetailsPanelMenuIcon.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/nav/ChangeSetPanel.vue
- app/web/src/newhotness/util.ts
- app/web/src/pages/auth/LogoutPage.vue
- lib/vue-lib/src/design-system/general/IconButton.vue
- lib/vue-lib/src/design-system/general/NewButton.vue
This PR replaces all instances of `IconButton` in the new UI with `NewButton`. From now on, we will only use the `NewButton` component for all buttons to ensure design consistency.
This PR does not remove `IconButton` from the auth-portal or the old UI. We will follow up to remove IconButton from the auth-portal in the future, and there's no reason to update the old UI when it will soon be gone!
Each button replaced was individually tested to ensure it works properly. Testing included confirming that keyboard controls still work properly when applicable.
> no more IconButton in the new UI

- Cargo.lock
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
Updated with:
```sh
cargo update -p slab --precise 0.4.11
buck2 run support/buck2:sync-cargo-deps
```
References: https://github.com/systeminit/si/security/dependabot/428
> build(deps): bump `slab` to 0.4.11

- app/web/src/newhotness/Explore.vue
Fixes: BUG-995
If you multi-select grid tiles, the context menu would have shown on the last tile. If you deselected the last tile, then it would have stayed connected to the last of the multi-selected tiles EVEN if it’s no longer selected
https://jam.dev/c/92db5ce8-d190-4c71-b3c6-9223ec3111f4
> fix(web): Ensure context menu shows in correct location during multi-select

- lib/sdf-server/BUCK
- lib/sdf-server/Cargo.toml
- lib/sdf-server/src/service/v2/fs.rs
- prelude-si/macros/rust.bzl
Kind of clunky, but this lets us have the symlinked typescript bits and the buck2 exported ones, meaning cargo check and buck2 builds should both work.
local cargo checks and builds
> fix: make typescript types symlink work in cargo and buck2

- lib/dal/examples/snapshot-fixer/main.rs
- lib/dal/src/workspace_snapshot/graph/validator.rs
- lib/sdf-server/src/service/v2/admin/migrate_connections.rs
- lib/sdf-server/src/service/v2/admin/validate_snapshot.rs
There are 4 invalid graphs in production workspaces with invalid connections that could not be migrated. This removes those.
The graph validator endpoint will now remove socket connections to missing components (of which there are 3 in production). This PR also makes it so migration will freeze a connection instead of migrating if the prop subscription could not be created for any reason (this handles exactly one invalid connection in production).
Finally, the validator endpoint will now report if there are any remaining parents or socket connections in the graph, as these are now illegal and gone from production.
This only affects the validation and migration endpoints.
The migration change will be tested live on the one affected workspace with the invalid connection. (Dry run first, …
> feat: remove/report invalid connections in validation/migration endpoints

- flake.nix
- prelude-si/git/git_info.py
This ensures that the hashes we generate are always 8 characters long. In some cases, we were generating 9 character long hashes, causing mismatched during promote vs. publish steps 
This also swaps out `git` for `gitMinimal` in the flake. This is what we used to use and this change was unintentional. It's possible the minimal version of git was less prone to generating 9 characters short hashes?
CI will be a good test for this. Locally, this works for me
> fix: git_info sha hash length not guarenteed

- app/web/src/newhotness/ApplyChangeSetButton.vue
- app/web/src/newhotness/ComponentHistory.vue
- app/web/src/newhotness/Onboarding2.vue
- app/web/src/pages/DebugPage.vue
- lib/vue-lib/src/design-system/general/NewButton.vue
- lib/vue-lib/src/design-system/index.ts
This PR fixes the spacing on NewButton so that it does not change size if it gains or loses an icon. The DebugPage has a button garden showing all the possible variations.
It also replaces the non-standard pill on the ChangeSetButton with the standard one.
This PR does not implement the secondary number pill shown in Figma as we are not using it anywhere yet.
This PR also does not finish eradicating VButton or IconButton from the few places it is left in the vue-lib and old UI.
Lots of manual testing, the DebugPage confirms that all possible variants match Figma.
> NewButton no longer changes size on loading

- bin/clover/src/cloud-control-funcs/overrides/AWS::AutoScaling::AutoScalingGroup/actions/instanceRefresh.ts
- bin/clover/src/pipeline-steps/assetSpecificOverrides.ts
We often have to rotate nodes in an AutoScaling group - this is the best way to do that as we have autoscaling groups we can ask to do it for us
HOLD BACK ON MERGING THIS! I WANT TO TEST A FEW MORE SCENARIOS!
> feat(clover): Adding an action we can use to trigger an instance refresh

- app/web/src/newhotness/Workspace.vue
Previously if we received a non-200 status for the `checkOnboardingCompleteApi` call we would assume it was a token issue and as a result a user could get stuck in the lobby.
Now we default to skipping onboarding if the `checkOnboardingCompleteApi` returns a non-200 status. Token issues should be handled properly elsewhere.
> don't get stuck in lobby if checkonboarding fails

- .ci/provision.sh
The validate main test needs an rbe token. This gets it from secrets manager.
I will run manual tests
> fix: frontend validate needs rbe token

- lib/luminork-server/src/service/v1/schemas/create_authentication.rs
This change fixes the luminork create auth endpoint by making sure that it calls the right authoring client function.
> Fix luminork create auth endpoint

- deno.lock
- lib/luminork-server/src/service/v1/common.rs
- lib/luminork-server/src/service/v1/components/list_components.rs
This is going to be used to allow us to get a generated cloudformation template for use in cost-exploration
This is a querySstring param and when set returns:
```
{
"componentDetails": [
{
"componentId": "01K5EYSC2QTZ49DVEPNQY2TGJH",
"name": "si-0070",
"schemaName": "AWS::EC2::VPC",
"codegen": {
"code": "{\n  \"AWSTemplateFormatVersion\": \"2010-09-09\",\n  \"Resources\": {\n    \"cfnResource\": {\n      \"Type\": \"AWS::EC2::VPC\",\n      \"Properties\": {\n        \"CidrBlock\": \"10.0.0.0/16\",\n        \"EnableDnsHostnames\": true,\n        \"EnableDnsSupport\": true\n      }\n    }\n  }\n}",
"format": "json"
}
}
],
"nextCursor": null
}
```
> feat(luminork): Adding the ability to return codegen from our list_components api

- app/web/src/newhotness/Explore.vue
- app/web/src/newhotness/Map.vue
When you've got a big map (like tools prod) most of the subscriptions you can't even see because they're not close in the layout to the selected component. In order to better navigate the map you ought to be able to hide unconnected components, so only connections get re-layout'd and come into view for.
Currently, this feature is hidden behind a one-time-only query string value set from pressing "Visualize Subscriptions". Now it is always accessible.
- Toggle the checkbox
- Toggle component selections
- Click on Visualize Subscriptions
> Map QOL: toggle checkbox for hiding components that aren't subscribed to the selected component

- app/web/src/newhotness/Workspace.vue
I can't repro the endpoint failure locally. However, I changed the check for "success"
```
if (status !== 300) {
```
- So when it succeeds with 200, it goes into this logic check.
- With that change, I am stuck in the lobby.
- Now I make my fix
- No longer stuck
> Hot fix: if the first time modal api call fails users are stuck in the lobby

- app/auth-portal/src/pages/DefaultWorkspacePage.vue
- app/auth-portal/src/pages/ProfilePage.vue
This PR fixes an issue where first time users were not being redirected to their default workspace after setting up their account.
It also updates the UI/UX so that users whose email has not been verified get better feedback and are redirected properly when they are locked on the user profile step.
Manually tested a bunch with the local auth stack for every possible scenario I could think of!
> fixed first time user default workspace redirect

- bin/auth-api/package.json
- deno.lock
- lib/tsconfig/tsconfig.node.json
The TSX/TypeScript 5.x upgrade in PR #7318 broke the production Docker container startup with this error:
` Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/dist/init-env' imported from /app/dist/main.js`
The upgrade introduced ES module resolution issues where:
1. The boot script pointed to `./dist/main.js` but TypeScript compiled to `./dist/src/main.js`
2. ES modules require explicit file extensions (.js) in imports, but the compiled output used extensionless imports
3. Workspace package resolution failed in the compiled JavaScript
This fixes that issue to make it use the moe common pattern
> fix(auth-api): Fix Docker container startup after TSX/TypeScript 5.x upgrade

- app/web/src/workers/webworker.ts
Immediately fire the callback for "exit the lobby". We don't need to patch the index with the data right away, the system will re-request the `/index` endpoint.
Note: This change I am fixing here never made it to users. It was merged today, but not deployed.
My local workspace with two change sets was stuck in the lobby because the 2nd change set didn't fire "exit lobby" because the queue is paused b/c we're cold starting.
In order to get an empty `frigg` I used this command `nats stream purge KV_FRIGG` so all change sets needed to rebuild when I hit my workspace.
> Lobby exit should not be within a queue

- bin/si-mcp-server/src/server.ts
- bin/si-mcp-server/src/tools/schemaCreate.ts
Creates a basic schema creator tool in the mcp server to be iterated on. Will not be made available externally YET.
Introduces a very basic schema creator tool - to be iterated on. This will not be available externally yet and is commented so in server.ts
> feat: introducing a basic schema creator in the si mcp server

- lib/luminork-server/src/service/v1/change_sets/create.rs
- lib/luminork-server/src/service/v1/change_sets/mod.rs
- lib/sdf-server/src/service/v2/change_set/create.rs
This change attempts to harmonize the code flows between SDF and Luminork's "create change set" handlers.
Importantly with this change:
- Luminork now waits the *same* 30 seconds for the Frigg index to be built and populated before return (same as SDF was doing)
- The timing of Luminork's `ctx.commit_no_rebase()` now happens *before* the call to Edda goes out. Prior to this change we published the Edda request before we commited the database change in Luminork meaning that Edda might process a message and not see the new change set in the `changeset_pointers` table (as Luminork may not have finished with its db txn commit).
- Luminork uses the workspace snapshot address from the `DalContext` when crafting the request to Edda. Prior to this change, the address comes back from the object …
> fix(sdf,luminork): harmonize create change set btw sdf & luminork

- app/web/src/workers/mjolnir_queue.ts
- app/web/src/workers/webworker.test.ts
- app/web/src/workers/webworker.ts
1. quieting down the bust logging
2. but the real fix, i made a dedupe queue and didnt fill it ☹️ 
3. fix to wrongly deleting the MvIndex atom MTM
I'm _somewhat_ confident that the "my whole grid started going skeletons" problems is related to MvIndex deletion. Here is the theory:
1. the IndexMv patches
2. then its MTM gets deleted
3. on the next index patch
4. we try to patch, but cannot find the previous atom
5. so we run niflheim
6. which replaces all the MTMs in a giant sql statement
7. and calls to bust all the tanstack caches
8. which re-runs all the UI queries
On a large enough workspace, those queries will contend and run slowly enough, as well as pushing all the data across the thread interface, you'll see skeletons.
1. Seeing that on load only one getSchemaMembers query fires. …
> App & Web Worker are querying & firing requests way too much

- app/auth-portal/src/pages/WorkspaceAuthTokensPage.vue
"1m" in the current placeholder implies that the token will be for 1 month, but it results in a 1 minute token.
This placeholder change makes it less misleading.
old placeholder -
new placeholder -
> change auth token placeholder to be less misleading

- lib/edda-server/src/materialized_view/deployment.rs
We apparently have some deployment-level MVs in the MvIndex where we are missing the MV itself. While it's a problem that we were missing the actual MV listed in the index, we're also in the process of building the missing MV when this error happens. Now, if we encounter this, we'll log a warning that it happened so we don't have this happening without any visibility, but we'll also proceed as if it wasn't in the MvIndex to start with to allow the build to continue and hopefully finish.
> Proceed without the previous version if unable to retrieve during deployment MV building

- bin/si-mcp-server/src/tools/commonBehavior.ts
- bin/si-mcp-server/src/tools/funcCreate.ts
This PR completes the demo for [ENG-3238](https://linear.app/system-initiative/issue/ENG-3238/scaffold-the-authoring-mcp-tools) by more cleanly capturing the error which happens if you attempt to create a duplicate action function of any kind except Manual.
Because there is not yet a Luminork API endpoint for the AI to use to check what action functions a schema has, this version can only respond to the error when it happens instead of preempting it.
> SI AI capture duplicate action kind error and respond appropriately

- app/web/cypress/ux/tile-view/get-tiles.cy.ts
> longer timeouts for get-tiles

- bin/clover/src/pipelines/hetzner/spec.ts
- bin/clover/src/spec/props.ts
Handles complex object types, specifically `oneOf` including ones with multiple type props.  This fixes the `label` objects not being maps.
`anyOf` as I don't think there are any.
Manually. The PR will validate AWS is oaky
> feat(clover): handle oneOf and normalize objects

- lib/luminork-server/src/service/v1/schemas/create_schema.rs
- lib/luminork-server/src/service/v1/schemas/get_schema.rs
- lib/luminork-server/src/service/v1/schemas/mod.rs
- lib/luminork-server/src/service/v1/schemas/unlock_schema.rs
There’s a specific usecase that if you have a schemaId and want to unlock it then we should ensure that it’s installed
Also return the SchemaId from the create_schema endpoint
> feat(luminork): When unlocking a schema ensure that it's installed

- app/web/src/newhotness/ComponentContextMenu.vue
This change aligns the deletion shortcut with the context menu option for deleting selecting components that include a mix of non-ghosted and ghosted components. This fixes scenarios where you can delete an unexpected selection of components (potentially unsafe) and aligns product behavior.
Right click context menu behavior:
> Prevent shortcut delete with mixed components

- bin/clover/src/pipelines/dummy/spec.ts
- bin/clover/src/pipelines/hetzner/funcs/management/discover.ts
- bin/clover/src/pipelines/hetzner/funcs/management/import.ts
- bin/clover/src/pipelines/hetzner/pipeline-steps/addDefaultProps.ts
- bin/clover/src/pipelines/hetzner/spec.ts
- bin/clover/src/pipelines/types.ts
- bin/clover/src/spec/props.ts
* Set the asset names to things like `Hetzner::Credential::ApiToken` and `Hetzner::Resource::Certificate`
* Ensure the Extra prop has the name and the endpoint correct
Manually! You know the drill by now.
> feat(clover): set names correctly

- lib/luminork-server/src/service/v1/change_sets/delete.rs
- lib/sdf-server/src/service/v2/change_set/abandon.rs
This change attempts to reduce the chances error or long waits when abandoning a change set. Prior to this change the workspace snapshot for the target change set was loaded via the
`DalContext::update_visibility_and_snapshot_to_visibility` method. No code in either the SDF or Luminork API handler is using the loaded workspace snapshot, and in the case of another bug, this load led to an error which resulted in not being able to abandon a change set. Finally, the workspace snapshot load can take some time if it is not already in cache, and will take up to 10 seconds if the snapshot is no longer available in the layer cache database (this is due to the current layer cache spin lock retry logic).
> chore(sdf,luminork): skip loading snapshot when abandoning a change set

- lib/naxum/src/middleware/jetstream_post_process/future.rs
- lib/naxum/src/middleware/jetstream_post_process/on_failure.rs
- lib/naxum/src/middleware/jetstream_post_process/on_success.rs
- lib/naxum/src/middleware/jetstream_post_process/service.rs
- lib/naxum/src/response/inner.rs
- lib/rebaser-server/src/change_set_processor_task.rs
- lib/rebaser-server/src/rebase.rs
- lib/shuttle-server/src/middleware.rs
This change is primarily focused on the code called in the
`ChangeSetProcessorTask` for each request that is being processed.
Prior to this change any error that was encountered that used the
question mark operator (i.e. Rust's `?`) would trigger the `default`
Naxum handler to return a `Result::Err(_)`. The `JetstreamPostProcess`
middleware had a custom `OnFailure` function which would copy the
message from the original stream subscription to the dead letter queue
stream (i.e. "DLQ"), treating all errors as unrecoverable. With more
time and experience seeing the service deployed in production, it's
clear that not all errors are unrecoverable, but rather some errors at
certain points in the business logic *should* be retried (as not
retrying some of these requests would lead to dropped …
> core(rebaser): allow certain errors to trigger request retries

- bin/auth-api/src/routes/workspace.routes.ts
Move the workspace details call to the automation router, which means it can be acessed by web tokens AND api tokens
I need this to get the workspace url from the token, so we can generate nice urls for our users.
Me and @jkeiser  tested it by running locally and ensuring that the api call workspace for both types of tokens
> feat(auth-api): Allow getting workspace details with api token

- lib/dal-materialized-views/src/cached/schema.rs
- lib/dal/src/cached_module.rs
- lib/edda-server/src/materialized_view/deployment.rs
- lib/luminork-server/src/service/v1/schemas/get_variant.rs
- lib/si-frontend-mv-types-rs/src/cached_schema.rs
Currently, when modules are promoted as builtins, they only contain a single schema, and a single variant (the default variant, which is the latest).  When exposing builtins as uninstalled, we only ever want to show the latest variant as we don’t want users to install old builtins.
We decided to stop building these while working on supporting incremental builds of the Deployment MVs, and at that time, we found that if we simply stop building the CachedSchemaVariantMV alltogether, it brings the total build time down to 16s (locally) for all current builtins. 
Given this, we likely don’t need to support incremental builds for some time, so we’ll ship this as a stand alone improvement and wait for our needs to grow again to revist incremental builds
Locally ran the sync, see that it finishes …
> fix(edda): Stop building CachedSchemaVariant MVs

- Cargo.lock
- Cargo.toml
- app/web/src/newhotness/logic_composables/search.ts
- component/lambda/functions/si_types.py
- lib/frigg/BUCK
- lib/frigg/Cargo.toml
- lib/frigg/src/workspace.rs
- lib/luminork-server/BUCK
- lib/luminork-server/Cargo.toml
- lib/luminork-server/src/lib.rs
- lib/luminork-server/src/search/component.rs
- lib/luminork-server/src/search/mod.rs
- lib/luminork-server/src/search/parser.rs
- lib/luminork-server/src/search/query.rs
- lib/luminork-server/src/service/v1/components/mod.rs
- lib/luminork-server/src/service/v1/components/search_components.rs
- lib/sdf-extract/src/change_set.rs
- lib/sdf-server/BUCK
- lib/sdf-server/Cargo.toml
- third-party/rust/BUCK
- third-party/rust/Cargo.lock
- third-party/rust/Cargo.toml
This adds the ability to search for components using the same query syntax as the frontend. Right now, this is just an additional option on top of the Luminork component search, but we will quickly create a new API endpoint so we can deprecate this one.
```
POST /v1/w/:workspaceId/change-sets/:changeSetId/components/search
{ queryString: "Instance region:us-east-1" }
{ components: ['01K4T90DB8FKV6PTD9D85NV2T1', '01K4T90DDMQC17HG3JQ72KJKYB'] }
```
There are three major differences:
* Instead of fuzzy search, searching for bare words like `Instance` will only return things that *contain* the word Instance.
* Attribute path search is now case-insensitive
* Searching for `AWS::EC2::Instance` will now return EC2 instances (this did not work because it was considered an attr search for …
> feat: Component search api

- lib/dal/src/attribute/attributes.rs
- lib/luminork-server/src/service/v1/components/mod.rs
FIXES: BUG-1080
When a user tries to update a read-only prop, we should throw a 412.
Trying to change the KeyName of an AWS::EC2::KeyPair as the following request:
```
curl -X 'PUT' \
'http://localhost:5380/v1/w/01HPJ3K7RC486W9RPR3T0B6HS2/change-sets/01K6WQ2YG46GJYSXFA4S58F2EX/components/01K6WPWQX5VCJ2NETCDQ433VEP' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"attributes": {
"/domain/KeyName": "updated-key-name
}
}'
```
now throws an error so that the user knows what the issue is:
```
{
"message": "attribute error: cannot update create-only property at path '/domain/KeyName' when component has a resource attached",
"statusCode": 412,
"code": null
}
```
> feat(luminork): Error when a user tries to update a readonly property

- lib/luminork-server/src/search/query.rs
When you search for `AWS::EC2::*`, it should get you all EC2 components. When you search for region:us-*-1, it should give you us-east-1 and us-west-1.
> feat: wildcard support in search API

- bin/si-mcp-server/deno.json
- bin/si-mcp-server/deno.lock
- bin/si-mcp-server/src/tools/componentUpdate.ts
Depends-on #7438
When a user tries to update a READ-ONLY prop, we need to capture the error and hint the user:
```
can you update the KeyPair component and set the KeyName to be "updated-name"
⏺ I'll update the KeyPair component's KeyName to "updated-name". Let me first find the KeyPair component and then update it.
⎿  <response>{"status":"success","data":[{"id":"01K6DS9XXCXW5EDW22920QRAQE","name":"HEAD","status":"Open","isHead":true}]}</response>
<hints>Apply, Force-Apply, and Abandon change sets using their 'id' and the change-set-status-update tool.</hints>
⏺ si-mcp-server - component-list (MCP)(changeSetId: "01K6DS9XXCXW5EDW22920QRAQE", filters: {"filterGroups":[{"responseField":"schemaName","regularExpressions":["KeyPair"]}]})
⎿ …
```
> fix(si-mcp-server): Capture when trying to update a read-only prop

- app/web/src/newhotness/ComponentDebugPanel.vue
- lib/dal/src/component/debug.rs
Previously the `ComponentDebugPanel` was displaying only the schema variant id of the component, incorrectly labeled as "schema ID"
This changes it to show both the correct schema id and schema variant id for the component.
> debug panel now shows both schema id and schema variant id

- app/web/src/components/CodeViewer.vue
- app/web/src/newhotness/FuncRunDetails.vue
- app/web/src/newhotness/LatestFuncRunDetails.vue
- app/web/src/newhotness/layout_components/CollapsingGridItem.vue
- app/web/src/newhotness/layout_components/FuncRunDetailsLayout.vue
- app/web/src/newhotness/layout_components/GridItemWithLiveHeader.vue
UI improvements to the `FuncRunDetails` page, primarily the ability to collapse/expand the three panels on the right side.
The left panel does not collapse, nor does either column in `LatestFuncRunDetails`
> collapsing panels in FuncRunDetails right column

- app/web/src/workers/webworker.ts
The bulk patch update was not ensuring all cache busts occurred. This fixes that.
> fix(web): ensure possible conns get cache busted

- bin/clover/src/pipelines/hetzner/funcs/management/discover.ts
- bin/clover/src/pipelines/hetzner/funcs/management/import.ts
- bin/clover/src/pipelines/hetzner/pipeline-steps/addDefaultProps.ts
- bin/clover/src/pipelines/hetzner/provider.ts
- bin/clover/src/pipelines/hetzner/spec.ts
Basically, the shape of nested objects hetzner returns from gets is different than the shape we send with posts, so we need to do some normalization work. We keep track of things we know need to be scalars and otherwise recurse through the objects to extract what we need. We also ignore sub-assets (like metrics) to ensure we aren't conflating the shape of the things we build with redundant information.
Tested with Server, PrimaryIps, and Datacenters. Discovery and Import seem to be correct.
> fix(clover): ensure hetzner imports handle complex objects

- bin/si-mcp-server/deno.lock
- bin/si-mcp-server/src/data/schemaHints.ts
- bin/si-mcp-server/src/tools/componentDiscover.ts
- bin/si-mcp-server/src/tools/componentImport.ts
```
⏺ Great! The discovery was actually successful - it found 1 server. The error message was misleading. Let me check the components in the change set to see the discovered server:
⏺ si-mcp-server - component-list (MCP)(changeSetId: "01K6XSA575QK3Y3MDG9DKDW58E", filters: {"filterGroups":[{"responseField":"schemaName","regularExpressions":["Hetzner::Cloud::Servers"]}]})
⎿ <response>{"status":"success","data":[{"componentId":"01K6XSW6TNFFQWD6E8BNCFPDCN","componentName":"Discover Hetzner::Cloud::Servers - Temporary","schemaName":"Hetzner::Cloud::Servers"}]}</re
sponse>
⏺ I discovered 1 Hetzner Cloud server in your account:
Server Details:
- Name: ubuntu-2gb-nbg1-1
- ID: 110313551
- Status: running
- Server Type: cpx11 (CPX 11 - 2 vCPU cores, 2GB RAM, 40GB disk)
- Location: Nuremberg …
```
> feat(mcp-server): Add the ability to trigger the discovery of Hetzner assets in si-mcp-server

- app/web/src/newhotness/AddComponentModal.vue
This PR changes the controls for the AddComponentModal so that the left and right arrow keys are free to use for moving the cursor inside the input box. The tab and shift tab controls now switch categories since they previously just did the same thing as the up and down arrows.
> changed controls for AddComponentModal
